### PR TITLE
fix for bug 11596 - gm and g^ do not remember column for vertical motion in folds

### PR DESCRIPTION
**Pull request by cero1988**
I changed nv_g_home_m_cmd for doing nothing in case of gm executed on a folded line
Do you think that this could be a good solution ?

### CODE REVIEW

**Comment by brammool** [comment]
Although technically moving the cursor horizontally in a closed fold has no meaning, one has to wonder why the user (or a script) would use the command.  Doing nothing (ignoring the command) is not really better than executing the command, right?  Or is there a situation where it would cause trouble?

**Comment by cero1988** [comment]
The problem when executing gm on a folded line is that the ruler show the new column, but when you move cursor on another row, It return to the first column, 
So I thought that doing nothing were better

**Comment by brammool** [comment]
See my comment on #11596 - fixing the cursor columns should be possible.

**Comment by chrisbra** [comment]
closing in favor of #15398

**Pull request closed without merging**
