### PR TITLE
 CI: suppress: incompatible-pointer-types

### PR DESCRIPTION
**Pull request by pheiduck**
CFLAGS="-Wno-incompatible-pointer-types"

### CODE REVIEW

**Comment by brammool** [comment]
Where did you see such a warning?

**Comment by pheiduck** [comment]
> Where did you see such a warning?

here: https://github.com/vim/vim/actions/runs/3535406106/jobs/5933392590#step:9:56

**Comment by brammool** [comment]
Looks like that still happens: https://github.com/vim/vim/actions/runs/3536195418/jobs/5935002220
It doesn't always get reported, I have no clue why.

**Comment by brammool** [comment]
Still failing.  Shouldn't the compiler flag be added in ci/build-snd-dummy.sh ?

**Comment by pheiduck** [comment]
> Still failing. Shouldn't the compiler flag be added in ci/build-snd-dummy.sh ?

lets try it out.

**Comment by brammool** [comment]
Missing quotes

**Comment by brammool** [comment]
Why did you close the PR?  We do need to find a solution somehow....

**Comment by brammool** [comment]
OK, I see the other PR to disable the sound dummy.  I'll include that one and the I'll assume you can try again to enable it and find a way to suppress the error.

**Pull request closed without merging**
