### PR TITLE
Update some Spanish msgid strings

### PR DESCRIPTION
**Pull request by cquike**
Some of the msgid strings in es.po where outdated and I have now bring them up to date.
Note that there might be other outdated msgid. The ones I have modified where found while using vi and realizing there are untranslated messages. Probably there are other msgid strings that are yet to be synchronized.
I have tried the compiles es.mo and it now shows the proper message in Spanish.

### CODE REVIEW

**Comment by brammool** [comment]
Thanks.  The file has not been updated in a long time.  Did you try to contact the maintainer?  I can include this patch, but it would be good to update all the translations.

**Comment by TarunavBA** [comment]
@cquike looks good.

**Comment by cquike** [comment]
I contacted the maintainer after creating the PR actually, but has not replied yet.
Indeed there are more translations to update.  I might go back to those when I have time. BTW, is there a standard workflow for the translators to get updated msgid strings?

**Comment by chrisbra** [comment]
Check https://github.com/vim/vim/blob/master/src/po/README.txt

**Comment by cquike** [comment]
Thank you @chrisbra. I should have guessed it :) I think it is going to be a bit of a daunting task to update the es.po file...
I have updated the commit to fix the CI problem in freebsd_12. Apparently the headers of the po file didn't contain a Plural-Form keyword.

**Pull request closed without merging**
