### PR TITLE
Fix wildchar/wildmenu/pum memory corruption with special wildchar's

### PR DESCRIPTION
**Pull request by ychin**
Currently, using `wildchar=<Esc>` or `wildchar=<C-\>` can lead to a memory corruption if using wildmenu+pum, or wrong states if only using wildmenu. This is due to the code only using one single place inside the cmdline process loop to perform wild menu clean up (by checking `end_wildmenu`) but there are other odd situations where the loop could have exited and we need a post-loop clean up just to be sure. If the clean up was not done you would have a stale popup menu referring to invalid memory, or if not using popup menu, incorrect status line (if `laststatus=0`).

For example, if you hit `<Esc>` two times when it's wildchar, there's a hard-coded behavior to exit command-line as a failsafe for user, and if you hit `<C-\><C-\><C-N>` it will also exit command-line, but the clean up code would not have hit because of specialized `<C-\>` handling.

Fix Ctrl-E / Ctrl-Y to not cancel/accept wildmenu if they are also used for 'wildchar'/'wildcharm'. Currently they don't behave properly, and also have potentially memory unsafe behavior as the logic is currently not accounting for this situation and try to do both. (Previous patch that addressed this: #11677)

Also, correctly document Escape key behavior (double-hit it to escape) in wildchar docs as it's previously undocumented.

In addition, block known invalid chars to be set in `wildchar` option, such as Ctrl-C and `<CR>`. This is just to make it clear to the user they shouldn't be set, and is not required for this bug fix.

### CODE REVIEW

**Comment by ychin** [comment]
I found this when working on #13362. Since this fixes a memory corruption issue I decided to split into two PRs, but #13362 is the continuation of this. You could merge this first, or merge both together.

**Comment by Shane-XB-Qian** [comment]
> hit `<Esc>` two times

have not looked into your PR deeply, but just a drop-by msg : 
what we discussed at #13331 that 'dismiss' i was wish it work like 'ctrl-l' in bash cli, which just to clean list choices,
but this double `<esc>` in vim cli is different, it totally cancel everything, the had input prompt chars was cleared too.

**Comment by ychin** [comment]
> > hit `<Esc>` two times
> 
> have not looked into your PR deeply, but just a drop-by msg : what we discussed at #13331 that 'dismiss' i was wish it work like 'ctrl-l' in bash cli, which just to clean list choices, but this double `<esc>` in vim cli is different, it totally cancel everything, the had input prompt chars was cleared too.

I think that's what Ctrl-E/Ctrl-Y is for? This double <Esc> behavior is a very special case where it's used as wildchar (which I honestly don't understand why anyone would set it this way to be honest). <Esc> is usually for escaping the command-line mode anyway and I don't think it's a useful key to overload with more meaning.

**Comment by ychin** [comment]
Or are you talking about not using wildmenu, and something like the list choices displayed in Ctrl-D or `wildmode=list` like you mentioned in the other PR? I think that's a different discussion from what I'm trying to fix here. Either way I don't think `<Esc>` should be used for that purpose as the key has very special meaning in Vim.

**Comment by Shane-XB-Qian** [comment]
i was trying to help clarify the different, or if you can make 'c-e' work on wildmode=list which make its list choice be dismissed by 'c-e' when it presented like wildmune or pum would be great, but didnot expect it have to change.
and yes, `<esc>` is a special key, and you're a TUI guy you may feel it's a similar behavior like others tui tools, sometime it worked like 'alt', that's another reason i jumpped in, wish this not changed, it is history :smile:

**Comment by ychin** [comment]
I think what I don't understand is what you mean by "dismiss"  wildmode=list? Recall that when you have wildmode=list, the completion does *not* fill in the choice. Or did you mean wildmost=full (in which case it's true that the current change would not make that work)?

**Comment by Shane-XB-Qian** [comment]
> I think what I don't understand is what you mean by "dismissing"  wildmode=list? Recall that when you have wildmode=list, the completion does *not* fill in the choice. Or did you mean wildmost=full (in which case it's true that the current change would not make that work)?

yes, list and/with full which had said that option in https://github.com/vim/vim/pull/13331#issuecomment-1761223994

i think these 3 list/wildmenu/pum are similar cases, now this PR you're trying to make it work for 'wildmenu' (and 'c-e' worked for 'pum' already)
// agagin, i didnot expect you have to make it work for 'list', but it would be nice (enhancement) one :simile: it would work like bash cli if so.

-- 
shane.xb.qian

**Comment by ychin** [comment]
Yeah it could be a future enhancement but I have to point out `list` is very different from `full`. You were saying that it takes up too much screen real estate when using list, and the issue there is more one of redraw, and something you will also see when using Ex-mode and `Ctrl-D` as I mentioned. I think `full` could be implemented as an enhancement though.

If you want to add a clear for `wildmode=list`, you could just map the following (Ctrl-O in this example):

```vim
cnoremap <C-O> <C-\>e<SID>CmdlineRedraw()<CR>
function! s:CmdlineRedraw()
    let c = getcmdline()
    redraw
    return c
endfunction
```

**Comment by Shane-XB-Qian** [comment]
ok, i think you got my point, and yea, some kind of vim script could make it work also.
so, natively support would be great, but 'not' also is ok, that's why i say didnot expect it have to change.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
