### PR TITLE
Improve README for mac

### PR DESCRIPTION
**Pull request by BetaFold3**
This is for installation instruction of vim on MacOS

### CODE REVIEW

**Comment by chdiza** [comment]
I don't think Vim should be pushing a particular package manager.  That's nothing against Homebrew (which I use for non-Vim stuff).

The installation for MacOS is just like it is for Unix.  Clone the repo, or download a release tarball, then `/.configure`, `make`, `sudo make install`.

**Comment by BetaFold3** [comment]
@chdiza Installing via homebrew is the fastest yet stable way in MacOSX. I suppose we should encourage that.

How about we adding a text like: "Alternatively, you also can install Vim via source like any other Unix systems"?

**Comment by medicalwei** [comment]
If there are build requirements, please list it out.  Actually I prefer asking users to use package manager (without going down to the details, maybe?) before pushing user to build the source code.  But make sure that users have choices between them.

**Comment by nuko8** [comment]
> If there are build requirements, please list it out. 

For the default build:
1. `sh`, `clang` and `make.`  The last two are to be installed with the `CommandLineTools` package.   If you don't have one, do `xcode-select --install` just like those who do software development with OS X are supposed to do.  (If you want to join the vim development, you might want `autoconf` in addition to them.)  
2. `libSystemB.dylib`, `libncurses.dylib`, `libiconv.dylib` and standard Objective-C frameworks such as `AppKit` (This is needed for the clipboard support, not for GUI) and `Foundation`.   All those come with OS X by default.   So you never need to check if they are installed or not.
3. Go to the top directory of the source tree, do

```
./configure
make
sudo make install
```

A newly built vim will be installed under `/usr/local`.

That's it.  **Nothing special for OS X.  It's the same as other UNIX variants.**  Probably, people don't want to read what is written in `src/INSTALL` again in `src/INSTALLmac.txt`.

Also, I don't like any idea that a specific package manager is recommended to the user.

**Comment by brammool** [comment]
Nuko wrote:

> > If there are build requirements, please list it out. 
> 
> For the default build:
> 1. `sh`, `clang` and `make.`  The last two are to be installed with the `CommandLineTools` package.   If you don't have one, do `xcode-select --install` just like those who do software development with OS X are supposed to do.  (If you want to join the vim development, you might want `autoconf` in addition to them.)  
> 2. `libSystemB.dylib`, `libncurses.dylib`, `libiconv.dylib` and standard Objective-C frameworks such as `AppKit` (This is needed for the clipboard support, not for GUI) and `Foundation`.   All those come with OS X by default.   So you never need to check if they are installed or not.
> 3. Go to the top directory of the source tree, do
> 
> ```
> ./configure
> make
> sudo make install
> ```
> 
> A newly built vim will be installed under `/usr/local`.
> 
> That's it.  **Nothing special for OS X.  It's the same as other UNIX variants.**  Probably, people don't want to read what is written in `src/INSTALL` again in `src/INSTALLmac.txt`.
> 
> Also, I don't like any idea that a specific package manager is recommended to the user.

How about merging those and making it a bit simpler:

README_mac.txt for version 8.0 of Vim: Vi IMproved.

This file explains the installation of Vim on Macintosh systems.
See "README.txt" for general information about Vim.

Alternative A: Using Homebrew
1. Install Homebrew from http://brew.sh/
2. Install latest Vim with:  brew install vim

Alternative B: From sources, like on Unix
1. Get the build tools: "clang" and "make".  These can be installed with the
   "CommandLineTools" package.   If you don't have one, do
   xcode-select --install
   Just like for any software development with OS X.
2. Get the source code.  Best is to use git (which you need to install first),
   see http://www.vim.org/git.php
   Or you can download and unpack the Unix tar archive, see
   http://www.vim.org/download.php
3. Go to the top directory of the source tree, do
   make
   sudo make install
   A newly built vim will be installed under "/usr/local".

## 

ARTHUR: This new learning amazes me, Sir Bedevere.  Explain again how sheep's
        bladders may be employed to prevent earthquakes.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nuko8** [comment]
> How about merging those and making it a bit simpler:

IMHO, I still don't like the idea that a specific package manager has to be mentioned there.   Even in case we should need to mention it at all costs, the order of Alternatives is absolutely wrong.

Potential readers of `README_mac.txt` are considered to be those who have managed to download the tarball and unarchived it all the way, or cloned the repository after having learned git with some effort.  Naturally, they want not only to install vim but also _to build it from the source for themselves_.

For those good people, "Alternative A" would look a terrible joke.  It sounds like "Sorry, this is not for you.  Go back and install another software before having Vim."   It's bad to toss them around like that.

Rather, we should encourage them to proceed further and higher, giving them a hint about how to get a full power to control over the build system.   Presumably, among such good people, someone will start sending us well-written bug reports and patches someday.

That's why I think the order of Alternatives is wrong;  Alternative B must precede Alternative A if the latter is desperately needed.

As for package management system.   If we still need to mention it,  we should remain neutral about it so that we will absolutely free from any consequences of users' preferences.  We can't be responsible for every bit a certain package manager arbitrarily does with vim.

I can't say I know all about the package management systems designed for OS X, but all people serious about the matter can name MacPort, Fink as well as Homebrew.

Again, I don't think we need to mention the package management systems, but if we have to do that, we should remain neutral and mention all parties as possible as we can for the sake of our freedom.

**Comment by chdiza** [comment]
Also, if the package managers are mentioned at all, they should merely be _mentioned_ (with a link to their homepages).  We don't need to include instructions on how to use the package managers.  So e.g., no `brew install vim`.

**Comment by brammool** [comment]
nuko8 wrote:

> > How about merging those and making it a bit simpler:
> 
> IMHO, I still don't like the idea that a specific package manager has
> to be mentioned there.   Even in case we should need to mention it at
> all costs, the order of Alternatives is absolutely wrong.
> 
> Potential readers of `README_mac.txt` are considered to be those who
> have managed to download the tarball and unarchived it all the way, or
> cloned the repository after having learned git with some effort.
> Naturally, they want not only to install vim but also _to build it
> from the source for themselves_.
> 
> For those good people, "Alternative A" would look a terrible joke.  It
> sounds like "Sorry, this is not for you.  Go back and install another
> software before having Vim."   It's bad to toss them around like that.
> 
> Rather, we should encourage them to proceed further and higher, giving
> them a hint about how to get a full power to control over the build
> system.   Presumably, among such good people, someone will start
> sending us well-written bug reports and patches someday.
> 
> That's why I think the order of Alternatives is wrong;  Alternative B
> must precede Alternative A if the latter is desperately needed.

OK, let's put the build instructions first.  I think that some people
may fail to make this work, so mentioning using Homebrew as a fallback
makes sense.

> As for package management system.   If we still need to mention it,
> we should remain neutral about it so that we will absolutely free from
> any consequences of users' preferences.  We can't be responsible for
> every bit a certain package manager arbitrarily does with vim.
> 
> I can't say I know all about the package management systems designed
> for OS X, but all people serious about the matter can name MacPort,
> Fink as well as Homebrew.
> 
> Again, I don't think we need to mention the package management
> systems, but if we have to do that, we should remain neutral and
> mention all parties as possible as we can for the sake of our freedom.

Well, we only need to mention one that works.  I'm sure people who have
MacPort or Fink know about them alread.

## 

Ten bugs in the hand is better than one as yet undetected.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by raimue** [comment]
People who use any of these packaging systems will know to search in these systems for the software than to read `READMEdir/README_mac.txt`, which is already quite obscure to find. Only those who want to build from source would look into such a file.

If people never heard of any of these packaging systems, vim should not endorse only one of the available packaging system (Homebrew, MacPorts, Fink, Rudix, pkgsrc, ...).

**Comment by chrisbra** [comment]
Closing, as this has been fixed.

**Pull request closed without merging**
