### PR TITLE
[in remember of Bram]: CI: clang-17

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by chrisbra** [comment]
Hm, there seems to be a problem with clang?

```
addr2line: DWARF error: invalid or unhandled FORM value: 0x23
regexp.c:2430:25: runtime error: call to function do_Upper through pointer to incorrect function type 'void *(*)(int *, int)'
/home/runner/work/vim/vim/src/regexp.c:1732: note: do_Upper defined here
    #0 0x55c2da0a7c23 in vim_regsub_both /home/runner/work/vim/vim/src/regexp.c:2430:25
    #1 0x55c2da0a4ee2 in vim_regsub /home/runner/work/vim/vim/src/regexp.c:1939:14
    #2 0x55c2d9b7105a in do_string_sub /home/runner/work/vim/vim/src/eval.c:7446:15
    #3 0x55c2d9bac51d in f_substitute /home/runner/work/vim/vim/src/evalfunc.c:10303:25
    #4 0x55c2da53d860 in call_bfunc /home/runner/work/vim/vim/src/vim9execute.c:1263:5
    #5 0x55c2da4eebbf in exec_instructions /home/runner/work/vim/vim/src/vim9execute.c:4257:7
    #6 0x55c2da5219cb in call_def_function /home/runner/work/vim/vim/src/vim9execute.c:6179:11
    #7 0x55c2da44cb2a in call_user_func /home/runner/work/vim/vim/src/userfunc.c:2796:6
    #8 0x55c2da44bc66 in call_user_func_check /home/runner/work/vim/vim/src/userfunc.c:3229:10
    #9 0x55c2da446406 in call_func /home/runner/work/vim/vim/src/userfunc.c:3834:15
    #10 0x55c2da444938 in get_func_tv /home/runner/work/vim/vim/src/userfunc.c:1943:8
    #11 0x55c2da471813 in ex_call_inner /home/runner/work/vim/vim/src/userfunc.c:5965:6
    #12 0x55c2da471813 in ex_call /home/runner/work/vim/vim/src/userfunc.c:6302:11
    #13 0x55c2d9c30410 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #14 0x55c2d9c260be in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #15 0x55c2da198e16 in do_source_ext /home/runner/work/vim/vim/src/scriptfile.c:1760:5
    #16 0x55c2da196a73 in do_source /home/runner/work/vim/vim/src/scriptfile.c:1906:12
    #17 0x55c2da196a73 in cmd_source /home/runner/work/vim/vim/src/scriptfile.c:1251:14
    #18 0x55c2d9c30410 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #19 0x55c2d9c260be in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #20 0x55c2d9f38c0a in nv_colon /home/runner/work/vim/vim/src/normal.c:3196:15
    #21 0x55c2d9f17387 in normal_cmd /home/runner/work/vim/vim/src/normal.c:939:5
    #22 0x55c2da839436 in main_loop /home/runner/work/vim/vim/src/main.c
    #23 0x55c2da837359 in vim_main2 /home/runner/work/vim/vim/src/main.c:895:5
    #24 0x55c2da82f0f4 in main /home/runner/work/vim/vim/src/main.c:441:12
    #0 0x7f0d59b4ad8f in __libc_init_first ??:?
    #1 0x7f0d59b4ae3f in __libc_start_main ??:?
    #2 0x55c2d9899f34 in _start ??:?

```

**Comment by chrisbra** [comment]
same error :(

**Comment by pheiduck** [comment]
> same error :(

Yep, I should wait until next clang 17.0.x release and do a rebase then. ;)

**Comment by ychin** [comment]
I think the problem here is that the code is relying on some undefined behaviors (I think?) here. `do_Upper`'s type is `fptr_T (*)(int *d, int c)`, but the code is trying to cast it to `fptr_T` itself, which is `void* (*)(int *d, int c)`.

Note that this is intentional. The code is trying to play with type system in C and relying on this behavior working in C compilers but I think it's undefined behavior. The relevant bits in regexp.c:

```c
/*
 * We should define ftpr as a pointer to a function returning a pointer to
 * a function returning a pointer to a function ...
 * This is impossible, so we declare a pointer to a function returning a
 * void pointer. This should work for all compilers.
 */
typedef void (*(*fptr_T)(int *, int));

    static fptr_T
do_Upper(int *d, int c)
{
    *d = MB_TOUPPER(c);

    return (fptr_T)do_Upper;
}

//…

static int vim_regsub_both(...) {
//…
    fptr_T	func_one = (fptr_T)NULL;
//…
		case 'u':   func_one = (fptr_T)do_upper;
//…
}
```

I think one way to fix this is by simply defining `do_Upper` to return `void*` itself, so the types would match.

Looking more closely though, this seems… a little over-engineered? The usage of complicated function pointers imply a lot of different generic cases that need to take advantage of this but there are really 4 functions here (e.g. `do_Upper`) to account for upper/lower case and one-time application versus all. The ability for a function to return itself (the cause of this behavior) doesn't seem to actually be necessary at all as there are already `func_one` and `func_all` to distinguish them. If I fix it I would probably simply refactor to not use the function pointers.

**Comment by ychin** [comment]
Actually, is that a runtime error and not a compiler error? Did clang add some runtime check for this or something?

**Comment by pheiduck** [comment]
@ychin I guess it is an runtime error as it's showing since **clang-17-rc1**

**Comment by pheiduck** [comment]
> I think the problem here is that the code is relying on some undefined behaviors (I think?) here. `do_Upper`'s type is `fptr_T (*)(int *d, int c)`, but the code is trying to cast it to `fptr_T` itself, which is `void* (*)(int *d, int c)`.
> 
> Note that this is intentional. The code is trying to play fast and loose with type system in C and relying on this behavior working in C compilers but I think it's undefined behavior. The relevant bits in regexp.c:
> 
> ```c
> /*
>  * We should define ftpr as a pointer to a function returning a pointer to
>  * a function returning a pointer to a function ...
>  * This is impossible, so we declare a pointer to a function returning a
>  * void pointer. This should work for all compilers.
>  */
> typedef void (*(*fptr_T)(int *, int));
> 
>     static fptr_T
> do_Upper(int *d, int c)
> {
>     *d = MB_TOUPPER(c);
> 
>     return (fptr_T)do_Upper;
> }
> 
> //…
> 
> static int vim_regsub_both(...) {
> //…
>     fptr_T	func_one = (fptr_T)NULL;
> //…
> 		case 'U':   func_all = (fptr_T)do_Upper;
> //…
> 	    else if (func_all != (fptr_T)NULL)
> 		// Turbo C complains without the typecast
> 		func_all = (fptr_T)(func_all(&cc, c));
> //…
> }
> ```
> 
> I think one way to fix this is by simply defining `do_Upper` to return `void*` itself, so the types would match.
> 
> Looking more closely though, this seems… a little over-engineered? The usage of complicated function pointers imply a lot of different generic cases that need to take advantage of this but there are really 4 functions here (e.g. `do_Upper`) to account for upper/lower case and one-time application versus all. The ability for a function to return itself (the cause of this behavior) doesn't seem to actually be necessary at all as there are already `func_one` and `func_all` to distinguish them. If I fix it I would probably simply refactor to not use the function pointers.

Send a PR?

**Comment by ychin** [comment]
Yeah I will send a new PR in a bit. Just need to test it.

I tried it locally and yes it's indeed UBSAN (undefined behavior sanitizer). Seems like clang 17 just got a little more rigorous in checking this.

**Comment by ychin** [comment]
#13117 should fix the issue and simplify the code as well.

**Comment by ychin** [comment]
See #13122.

**Comment by pheiduck** [comment]
Refactoring is still needed:

```
if_python.c:1061:5: runtime error: call to function run_eval through pointer to incorrect function type 'void (*)(const char *, void *, PyGILState_STATE *)'
/home/runner/work/vim/vim/src/./if_py_both.h:6132: note: run_eval defined here
    #0 0x5586bbde115f in DoPyCommand /home/runner/work/vim/vim/src/if_python.c:1061:5
    #1 0x5586bbde115f in do_pyeval /home/runner/work/vim/vim/src/if_python.c:1526:5
    #2 0x5586bb26b3f0 in f_pyeval /home/runner/work/vim/vim/src/evalfunc.c:8230:5
    #3 0x5586bb24fafe in call_internal_func /home/runner/work/vim/vim/src/evalfunc.c:3145:5
    #4 0x5586bbb1a4b5 in call_func /home/runner/work/vim/vim/src/userfunc.c:3852:14
    #5 0x5586bbb189b8 in get_func_tv /home/runner/work/vim/vim/src/userfunc.c:1943:8
    #6 0x5586bb23fb9f in eval_func /home/runner/work/vim/vim/src/eval.c:2354:8
    #7 0x5586bb23dd4a in eval9 /home/runner/work/vim/vim/src/eval.c:4258:9
    #8 0x5586bb2462e0 in eval8 /home/runner/work/vim/vim/src/eval.c:3819:11
    #9 0x5586bb244e5e in eval7 /home/runner/work/vim/vim/src/eval.c:3623:9
    #10 0x5586bb243250 in eval6 /home/runner/work/vim/vim/src/eval.c:3402:9
    #11 0x5586bb242465 in eval5 /home/runner/work/vim/vim/src/eval.c:3[29](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:30)1:9
    #12 0x5586bb2410a5 in eval4 /home/runner/work/vim/vim/src/eval.c:3142:9
    #13 0x5586bb24011d in eval3 /home/runner/work/vim/vim/src/eval.c:[30](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:31)03:9
    #14 0x5586bb20debf in eval2 /home/runner/work/vim/vim/src/eval.c:2877:9
    #15 0x5586bb20debf in eval1 /home/runner/work/vim/vim/src/eval.c:2723:9
    #16 0x5586bbb17c8e in get_func_arguments /home/runner/work/vim/vim/src/userfunc.c:1859:6
    #17 0x5586bbb1870d in get_func_tv /home/runner/work/vim/vim/src/userfunc.c:1922:11
    #18 0x5586bbb458c3 in ex_call_inner /home/runner/work/vim/vim/src/userfunc.c:5970:6
    #19 0x5586bbb458c3 in ex_call /home/runner/work/vim/vim/src/userfunc.c:6307:11
    #20 0x5586bb2fc180 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #21 0x5586bb2f1e2e in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #22 0x5586bbb22992 in call_user_func /home/runner/work/vim/vim/src/userfunc.c:3056:2
    #23 0x5586bbb1fce6 in call_user_func_check /home/runner/work/vim/vim/src/userfunc.c:3229:10
    #24 0x5586bbb1a486 in call_func /home/runner/work/vim/vim/src/userfunc.c:3834:15
    #25 0x5586bbb189b8 in get_func_tv /home/runner/work/vim/vim/src/userfunc.c:1943:8
    #26 0x5586bbb458c3 in ex_call_inner /home/runner/work/vim/vim/src/userfunc.c:5970:6
    #27 0x5586bbb458c3 in ex_call /home/runner/work/vim/vim/src/userfunc.c:6307:11
    #28 0x5586bb2fc180 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #29 0x5586bb2f1e2e in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #30 0x5586bb23af02 in ex_execute /home/runner/work/vim/vim/src/eval.c:7296:6
    #[31](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:32) 0x5586bb2fc180 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #[32](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:33) 0x5586bb2f1e2e in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #[33](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:34) 0x5586bbb22992 in call_user_func /home/runner/work/vim/vim/src/userfunc.c:3056:2
    #[34](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:35) 0x5586bbb1fce6 in call_user_func_check /home/runner/work/vim/vim/src/userfunc.c:3229:10
    #[35](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:36) 0x5586bbb1a486 in call_func /home/runner/work/vim/vim/src/userfunc.c:3834:15
    #[36](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:37) 0x5586bbb189b8 in get_func_tv /home/runner/work/vim/vim/src/userfunc.c:1943:8
    #[37](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:38) 0x5586bbb458c3 in ex_call_inner /home/runner/work/vim/vim/src/userfunc.c:5970:6
    #[38](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:39) 0x5586bbb458c3 in ex_call /home/runner/work/vim/vim/src/userfunc.c:6307:11
    #[39](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:40) 0x5586bb2fc180 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #[40](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:41) 0x5586bb2f1e2e in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #[41](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:42) 0x5586bb868438 in do_source_ext /home/runner/work/vim/vim/src/scriptfile.c:1762:5
    #[42](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:43) 0x5586bb866093 in do_source /home/runner/work/vim/vim/src/scriptfile.c:1908:12
    #[43](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:44) 0x5586bb866093 in cmd_source /home/runner/work/vim/vim/src/scriptfile.c:1253:14
    #[44](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:45) 0x5586bb2fc180 in do_one_cmd /home/runner/work/vim/vim/src/ex_docmd.c:2582:2
    #[45](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:46) 0x5586bb2f1e2e in do_cmdline /home/runner/work/vim/vim/src/ex_docmd.c:994:17
    #[46](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:47) 0x5586bbf15154 in exe_commands /home/runner/work/vim/vim/src/main.c:3173:2
    #[47](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:48) 0x5586bbf15154 in vim_main2 /home/runner/work/vim/vim/src/main.c:790:2
    #[48](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:49) 0x5586bbf0d374 in main /home/runner/work/vim/vim/src/main.c:441:12
    #[49](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:50) 0x7fba02429d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #[50](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:51) 0x7fba02429e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #0 0x[55](https://github.com/vim/vim/actions/runs/6240181405/job/16939704624#step:20:56)86baf62f04 in _start ??:?
```

**Comment by ychin** [comment]
Oh, I forgot to run / test it to see what else needed to be fixed after my PR…

**Comment by ychin** [comment]
#13128

**Comment by pheiduck** [comment]
@ychin still undefined-behavior
https://github.com/vim/vim/actions/runs/6252669629/job/16976420178#step:20:29

**Comment by ychin** [comment]
Ugh, I wish these are compile-time errors rather than runtime errors. Let me turn on Clang 17 locally in a custom branch to make sure it passes CI for my next PR

**Comment by ychin** [comment]
Ok, #13140 should fix this. I was smarter this time and turned on clang 17 in my local branch's CI and it passed, so hopefully this is the last one.

**Comment by pheiduck** [comment]
@chrisbra it's ready to merge

**Pull request closed without merging**
