### PR TITLE
Update Git runtime files

### PR DESCRIPTION
**Pull request by tpope**
These are the latest versions of the `git*.vim` runtime files that I maintain. Note that I am requesting **removal** of `ftplugin/git.vim`, as I believe everything in there was of extremely dubious value.

I am also including a few tweaks to filetype detection:

* Detect the files created by `git notes edit` and `git branch --edit-description` as `gitcommit`.
* Loosen the 40 character SHA-1 matches to account for upcoming SHA-256 support.
* Remove an extremely old rule for detecting `gitsendemail`. (Git switched to `.gitsendemail.msg.*` in 2008.)

### CODE REVIEW

**Comment by brammool** [comment]
Thanks for the update.
Can you please add tests for the filetype detection changes in src/testdir/test_filetype.vim?

**Comment by tpope** [comment]
No problem, added. I believe the CI failure is spurious as it's unrelated to any change I made.

**Comment by tpope** [comment]
Unclear why, but a fresh push rebased on the latest master has fixed the CI issues.

**Comment by brammool** [comment]
Thanks, I'll make a patch for the filetype changes and the rest will be in the next runtime files update.

**Pull request closed without merging**
