### PR TITLE
ftplugin/nroff.vim: Add comments and sections customizations.

### PR DESCRIPTION
**Pull request by averms**
I sent this as an email to <cspiegel@gmail.com> on October 15th and haven't received a response yet so I decided to open a pull request. If I didn't wait long enough, feel free to close.

### CODE REVIEW

**Comment by brammool** [comment]
I haven't heard from @cspiegel since the original pull request.  I don't even know if that gmail.com address is valid.
Since it's just a one-liner, I wouldn't mind if you take over maintainership.

**Comment by cspiegel** [comment]
@a-vrma Sorry, I completely missed that email!  But by all means you can take over maintainership if you'd like, as I'm not particularly proficient in roff.

**Comment by averms** [comment]
> But by all means you can take over maintainership if you'd like, as I'm not particularly proficient in roff.

Sure, I'm happy to take over maintainership.

@brammool, should I push a commit on this pull request changing the 'Maintainer' line?

**Comment by k-takata** [comment]
It would be better to also update `.github/CODEOWNERS`.

**Comment by chrisbra** [comment]
Yes, as @k-takata  mentions, update [.github/CODEOWNERS](https://github.com/vim/vim/blob/master/.github/CODEOWNERS) and add yourself for the `runtime/ftplugin/nroff.vim` file. In addition, please move @cspiegel to `PreviousMaintainers` and add yourself as `Maintainer`. Thanks.

**Comment by Shane-XB-Qian** [comment]
have a curious question: 
after such flow, even he/she fixed an issue from users, looks code still remained at maintainer's local, since he/she had no access to merge code still, unless she/he sent out a pr, but looks no offenly saw that. 
then how come those vim embedded plugins got be updated? someone would offline scheduled to send mail to ask those maintainers, then he collected to update them (merge to vim repo) all in some timing?
// all in all, it meant embedded plugins were working as offline(mail) style flow, and some of you would collect update from them then merge news as bunch?
// as i knew, looks the workflow like that, but not sure the 'timing', looks occasionally it happened..

**Comment by chrisbra** [comment]
@Shane-XB-Qian Check the [CONTRIBUTING.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files) and see if this answers your questions.

**Comment by Shane-XB-Qian** [comment]
ok, i see, `The maintainer will take care of issues and send updates to Bram for distribution with Vim.`, so it's not 'scheduled'.
// but still, not sure the 'timing', looks just the updates sent out from maintainers were collected had enough amount, then the merge happened.. seems this.

**Comment by chrisbra** [comment]
well, the maintainer is in charge. He should know, when the files are stable enough to be included with the next vim runtime file update.

**Comment by Shane-XB-Qian** [comment]
> the next vim runtime file update.

ok, supposed it meant as long as maintainers sent out the patches, then bram would find out a 'timing' to merge it, there is no 'schedule' (and looks no saying it would 'instantly' merge as well). 
// got it, thx your reply.

// asking this, coz i was thinking embedded plugins update was working per some kinds of 'schedule', but now looks it kicked off per when maintainers sent out, though it it's not instantly happened when bram got those update.

**Comment by brammool** [comment]
@a-vrma  yes, please update this pull request as mentioned in the previous comments.

**Comment by palopezv** [comment]
@brammool Please drop my address from nroff.vim header. Or make sure to send patches to upstream at https://github.com/palopezv/vim-nroff Thanks.

**Comment by brammool** [comment]
I do not see your address in the existing file or in this pull request.

**Comment by Shane-XB-Qian** [comment]
@palopezv your name is in `syntax`, this pr is for `ftplugin`, though looks both was for `roff`.
// for runtime (embeded plugins) files, perhaps just follow bram's general workflow which was per patch via mail/mail-list.
// 'pr flow' perhaps not suitable for all things.. :) specially those are embeded into vim, not a good idea to separate to many places.

**Comment by averms** [comment]
Updated.

**Comment by brammool** [comment]
I'll include it, thanks.

**Pull request closed without merging**
