### PR TITLE
add sytax recognition for lua utf8 funcs

### PR DESCRIPTION
**Pull request by nobodyatandnothing**

### CODE REVIEW

**Comment by brammool** [comment]
Have you contacted the maintainer?  See the file header.

**Comment by nobodyatandnothing** [comment]
yes, i did. is it common to stll moniter the same email address for 10 years?

**Comment by brammool** [comment]
I have another email address, I'll send a message there.

**Comment by dkearns** [comment]
Marcus replied to me a couple of months ago in response to a patch I sent him and pointed me at some updates here: [github.com/marcuscf/vim-lua](http://github.com/marcuscf/vim-lua)

He floated the idea of transferring maintenance duties to someone else.  @nobodyatandnothing would you be interested?

**Comment by marcuscf** [comment]
@nobodyatandnothing 
> yes, i did. is it common to stll moniter the same email address for 10 years?

I don't check that address very often but I'm still around :-)

As @dkearns said, I have a few updates on https://github.com/marcuscf/vim-lua including utf8 functions and others.

I think this pull request can be merged because it's an obvious improvement but if anyone is interested https://github.com/marcuscf/vim-lua/blob/master/syntax/lua.vim has more syntax updates, including Lua 5.3 and 5.4 support. Maybe someone could create a pull request from that?

On the other hand the _indent_ file that I have in my repo has too many changes and not enough testing to be merged. I got a lot of ideas from other users on GitHub but never really completed my own version.

> He floated the idea of transferring maintenance duties to someone else

Yeah, if somebody who still programs in Lua could maintain these files it would be great. Especially the final steps of checking everything in practice, creating clean commits/patches from the latest version and sending pull requests. I did add 5.3 and 5.4 syntax support but since I don't program in Lua anymore I was not sure the changes were good enough to be merged.

**Comment by brammool** [comment]
I'll include it then.
A PR for the 5.3 and 5.4 support is welcome, please let Marcus review.

**Pull request closed without merging**
