### PR TITLE
Enable z= even when 'spell' is disabled

### PR DESCRIPTION
**Pull request by ghgary**
The spell command z= and functions spellbadword() and spellsuggest() are
now functional even when 'spell' is disabled.  Documentation and tests
have been updated and the issue has been removed from todo.txt.

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks for converting into a proper PR! 👍

**Comment by vim-ml** [comment]
On 2020-06-09, Christian Brabandt wrote:
> Thanks for converting into a proper PR! 👍

You're welcome.  With the instructions from Yegappan, it was pretty
easy.  I just needed a shove.

However...

The AppVeyor build failed with errors in term.c.  I didn't change
term.c, or any header files.  See:

    https://ci.appveyor.com/project/chrisbra/vim/builds/33419078/job/8k28jgpkb0s2rhr5

The failures begin with this:

    gcc -c -I. -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=i686 -Wall -O2 term.c -o obji686/term.o
    term.c: In function 'handle_u7_response':
    term.c:4394:2: warning: implicit declaration of function 'LOG_TR' [-Wimplicit-function-declaration]
     4394 |  LOG_TR(("Received U7 status: %s", tp));
	  |  ^~~~~~
    term.c:4394:34: warning: left-hand operand of comma expression has no effect [-Wunused-value]
     4394 |  LOG_TR(("Received U7 status: %s", tp));
	  |                                  ^
    term.c:4395:2: error: 'u7_status' undeclared (first use in this function); did you mean 'job_status'?
     4395 |  u7_status.tr_progress = STATUS_GOT;
	  |  ^~~~~~~~~
	  |  job_status
    term.c:4395:2: note: each undeclared identifier is reported only once for each function it appears in
    term.c:4395:26: error: 'STATUS_GOT' undeclared (first use in this function); did you mean 'STATSTG'?
     4395 |  u7_status.tr_progress = STATUS_GOT;
	  |                          ^~~~~~~~~~
	  |                          STATSTG

and go on from there.

This was a HUGE build on Windows, "Building MinGW 32bit console
version", which I'm not currently set up to replicate.

What now?

Regards,
Gary

**Comment by chrisbra** [comment]
yes, I also noticed that. Can you rebase on 8.2.940? I think Bram has already fixed it with the last 2 changes (your PR seems to be based on 8.2.938)

**Comment by vim-ml** [comment]
Hi Gary,

On Tue, Jun 9, 2020 at 1:20 PM Gary Johnson <garyjohn@spocom.com> wrote:

> On 2020-06-09, Christian Brabandt wrote:
> > Thanks for converting into a proper PR! 👍
>
> You're welcome.  With the instructions from Yegappan, it was pretty
> easy.  I just needed a shove.
>
> However...
>
> The AppVeyor build failed with errors in term.c.  I didn't change
> term.c, or any header files.  See:
>
>
> https://ci.appveyor.com/project/chrisbra/vim/builds/33419078/job/8k28jgpkb0s2rhr5
>
> The failures begin with this:
>
>     gcc -c -I. -Iproto -DWIN32 -DWINVER=0x0600 -D_WIN32_WINNT=0x0600
> -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H -DHAVE_GETTEXT -DHAVE_LOCALE_H
> -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_JOB_CHANNEL -DFEAT_IPV6
> -DHAVE_INET_NTOP -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_MBYTE_IME
> -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -march=i686 -Wall -O2 term.c -o
> obji686/term.o
>     term.c: In function 'handle_u7_response':
>     term.c:4394:2: warning: implicit declaration of function 'LOG_TR'
> [-Wimplicit-function-declaration]
>      4394 |  LOG_TR(("Received U7 status: %s", tp));
>           |  ^~~~~~
>           |                          STATSTG
>
> and go on from there.
>
> This was a HUGE build on Windows, "Building MinGW 32bit console
> version", which I'm not currently set up to replicate.
>
> What now?
>

As you can see from the below report:

https://ci.appveyor.com/project/chrisbra/vim/builds/33419708/job/m5k7dnueoen24u9w

The build failure is caused by "patch 8.2.0939: checking for term escape
sequences
is long and confusing" and is not related to your PR.

BTW, I forgot to mention about the code coverage in the mail yesterday. You
can
check the code coverage for your changes at the below link:

https://codecov.io/gh/vim/vim/commit/4443e5e67df9f1656573d26c902728b1f8320392

It is good to maintain the code coverage percentage by adding additional
tests
for the new/changed lines of code.

- Yegappan

**Pull request closed without merging**
