### PR TITLE
Add some search/lookup terms to if_pyth.txt.

### PR DESCRIPTION
**Pull request by shlomif**
To make it easier to research / use - it tripped me today.

----

I hereby disclaim any implicit or explicit ownership of my changes in this
changeset, and put them under a multiple licence consisting of your choice of
one of more of:

- The CC0 / Public Domain - https://creativecommons.org/choose/zero/ .

- The MIT / Expat license - https://en.wikipedia.org/wiki/MIT_License

- The default licence of your project

- The https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License - version
2.1 or higher

- The https://en.wikipedia.org/wiki/GNU_General_Public_License - version 2 or
higher

- Any licence in the 2018-Aug-27 popular licenses list of
https://opensource.org/licenses

- The https://en.wikipedia.org/wiki/Apache_License version 2.0 or later

- The https://en.wikipedia.org/wiki/Artistic_License version 2.0 or later

- The https://en.wikipedia.org/wiki/ISC_license

- The https://opensource.org/licenses/BSD-2-Clause

Crediting me will be nice, but not mandatory, and you can change the licence
of the project without needing my permission.

### CODE REVIEW

**Comment by chrisbra** [comment]
The following comment was made on the mailinglist: https://groups.google.com/d/msg/vim_dev/zdgbTKBnJrA/lGJ80Y8lEAAJ

**Comment by brammool** [comment]
The example is right under :pydo, but it actually uses :py3do.  Does the same example work with :pydo?

**Comment by chrisbra** [comment]
fixed by 20aac6c1126988339611576d425965a25a77765

**Comment by shlomif** [comment]
On Wed, 05 Sep 2018 13:17:58 -0700
Christian Brabandt <notifications@github.com> wrote:

> Closed #3381.
> 

thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://youtu.be/n6KAGqjdmsk - “Hurt Me Tomorrow”

Chuck Norris’ E-mails are signed with “Sent using Chuck Norris’ brain (which
he can also kill you using it).”.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request closed without merging**
