### PR TITLE
Runtime: Refine syntax matching for dosini files

### PR DESCRIPTION
**Pull request by ix5**
dosiniLabel match no longer includes the equal sign, add new dosiniValue
group-name

Update upstream information as well

(I have added a request with the maintainer as well, see with https://github.com/xuhdev/syntax-dosini.vim/pull/3, but I think he/she is otherwise occupied.)

### CODE REVIEW

**Comment by ap** [comment]
As I’ve commented on xuhdev/syntax-dosini.vim#3, this patch introduces a `dosiniValue` highlight group but doesn’t link it to anything. It should probably be linked to `String`.

**Comment by ix5** [comment]
Updated `dosiniValue` to `String`

**Comment by chrisbra** [comment]
Thanks, since the runtime file is maintained let's leave this to the maintainer. I suppose he will send an update to Bram to have it distributed with Vim. So closing for now. (@xuhdev, once this issue is satisfied, please send an update to Bram).

**Comment by xuhdev** [comment]
@chrisbra @ix5 Done!

**Pull request closed without merging**
