### PR TITLE
Add support for nginx syntax highlighting

### PR DESCRIPTION
**Pull request by chr4**
This adds advanced nginx syntax highlighting from https://github.com/chr4/nginx.vim, as requested per https://github.com/vim/vim/issues/8824

I've tried to migrate it to the code styles used here, feel free to adjust if necessary.

### CODE REVIEW

**Comment by k-takata** [comment]
Could you also update `.github/CODEOWNERS`?

**Comment by chr4** [comment]
> Could you also update `.github/CODEOWNERS`?

Done!

**Comment by brammool** [comment]
Thanks for making this PR.  Please also add a header to the ftplugin and indent files.  They may be small, but there might still be comments on them.
For the pattern in filetype.vim, we usually use one command with patterns separated by a comma.

**Comment by chr4** [comment]
Thanks for the feedback! I've adjusted the files, please review whether I got it right.

**Comment by dkearns** [comment]
Thanks for including these.  I find it much nicer to have runtime filetype support available out of the box.

**Comment by chr4** [comment]
🤦🏻 fixed header lines.

**Comment by brammool** [comment]
I included this, but just noticed that the indent file doesn't set b:undo_indent and the ftplugin file doesn't set b:undo_ftplugin.
Please add that.

**Comment by dkearns** [comment]
Missed that, because I didn't look. 

See [Set b:undo_ftplugin and b:undo_indent](https://github.com/chr4/nginx.vim/pull/18)

**Comment by chr4** [comment]
Merged, also added the changes to this PR.

**Pull request closed without merging**
