### PR TITLE
support --nofork on the Windows batch files (fix issue #658)

### PR DESCRIPTION
**Pull request by killerswan**
Anybody have any thoughts? :smile_cat:

### CODE REVIEW

**Comment by mattn** [comment]
I'm not sure but we've better to add `setlocal` on the top of bat file.

**Comment by killerswan** [comment]
Ahh, I've never played around with `setlocal` before.   How far back does support for that feature go?

**Comment by mattn** [comment]
setlocal works on XP, So you can put setlocal in all of the bat file which dosinst generated, I think.

**Comment by killerswan** [comment]
Ooooh, and I don't need to know all the exit paths: the `endlocal` is implicit, according to [this](https://technet.microsoft.com/en-us/library/bb490898.aspx).

**Comment by killerswan** [comment]
@mattn, I've added that now!

**Pull request closed without merging**
