### PR TITLE
Call changed_lines() with the correct lnum in empty buffer in ex_append

### LINKED ISSUE #9438: A redraw is needed to display the first line of the text inserted into an empty buffer by :insert or :append from a mapping or a timer
### Steps to reproduce

1. Run `vim --clean`
2. Create mapping `:nnoremap <F2> <Cmd>append<CR>aaaaa<CR>bbbbb<CR>.<CR>`
3. Press `<F2>`
4. The `bbbbb` is displayed immediately, but the `aaaaa` is not displayed until the next redraw

### Expected behaviour

The `aaaaa` is displayed immediately

### Version of Vim

Vim 8.2.3890

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish 3.3.1

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #9438

### CODE REVIEW

**Comment by zeertzjq** [comment]
Why does code coverage drop that much when I remove two empty lines in tests...

**Comment by brammool** [comment]
> Why does code coverage drop that much when I remove two empty lines in
> tests...

Code coverage for pull requests tends not to work very well.
You can hopefully look at the code you changed to see if it is covered
by tests.  But the total percentage is irrelevant.

-- 
hundred-and-one symptoms of being an internet addict:
166. You have been on your computer soo long that you didn't realize
     you had grandchildren.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
The first commit I pushed to the branch passed all checks. Then I pushed another commit to the branch only removing two blank lines from the tests I added, and code coverage suddenly dropped.

**Comment by zeertzjq** [comment]
I'll post more about the problem I'm trying to solve here. The problem is a side-effect of patch 7.4.1970. Patch 7.4.1970 changed `ex_append` to call `appended_lines_mark()` with `1` as `lnum` when the buffer is empty (before that patch it passed `0`), which in turn calls `changed_lines()` with `2` as `lnum` (before that patch it passed `1`), and the first line is not marked as modified. As a result, the first line is sometimes not displayed, e.g., when `:insert` or `:append` is used from a timer in an empty buffer.

**Comment by zeertzjq** [comment]
And in this PR I'm just changing it to call `appended_lines()` instead of `appended_lines_mark()`, and with `0` as `lnum` instead of `1`, so the marks are still not affected, but the first line is marked as modified, so it will be displayed correctly by `win_update()`.

**Pull request closed without merging**
