### PR TITLE
Support IPv6 channel

### PR DESCRIPTION
**Pull request by ichizok**
* Use `getaddrinfo()` instead of `gethostbyname()`
* Make `ch_open()` accept IPv6 address (enable to parse IPv6 literal in `channel_open_func()`)
* Add `CheckIPv6` command for IPv6 tests to check loopback device has IPv6 address
* Add `g:testfunc` variable to refer the executing test name in testing: in order to switch test-server script (below) in channel tests
* Add test_channel_6.py to launch IPv6 test server
* Configure script: add `getaddrinfo()` check and remove libnsl check since `getaddrinfo()` doesn't need libnsl.

### CODE REVIEW

**Comment by brammool** [comment]
> * Use `getaddrinfo()` instead of `gethostbyname()`

I wonder how many systems supporting gethostbyname() do not have
getaddrinfo()?

-- 
Snoring is prohibited unless all bedroom windows are closed and securely
locked.
		[real standing law in Massachusetts, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
> I wonder how many systems supporting gethostbyname() do not have
> getaddrinfo()?

I don't know... should do as the following by the configure checking?

If the environment supports `getaddrinfo()`: use `getaddrinfo()` and enable IPv6
Otherwise: use `gethostbyname()` and only IPv4 (same as current)

**Comment by brammool** [comment]
> > I wonder how many systems supporting gethostbyname() do not have
> > getaddrinfo()?
> 
> I don't know... should do as the following by the configure checking?
> 
> If the environment supports `getaddrinfo()`: use `getaddrinfo()` and
> enable IPv6
> Otherwise: use `gethostbyname()` and only IPv4 (same as current)

Unless we are sure 99% of systems have get getaddrinfo() I think we
should have a confire check for it and fall back to the older
implementation when not available.

-- 
A parent can be arrested if his child cannot hold back a burp during a church
service.
		[real standing law in Nebraska, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
* Add IPv4 (`gethostbyname`, current implementation) fallback
* Add "ipv6" to feature-list

**Comment by brammool** [comment]
This looks like it's complete.  Is it ready to include now?

**Comment by ichizok** [comment]
> This looks like it's complete. Is it ready to include now?

Yes, all set.

**Pull request closed without merging**
