### PR TITLE
make clipboard and ASCII NUL work better

### PR DESCRIPTION
**Pull request by chrisbra**
This is for fixing issue #6149

### CODE REVIEW

**Comment by brammool** [comment]
I'll include it, but it appears the test passes even without the code change.

**Comment by chrisbra** [comment]
it should fail, it certainly did for me:

```
1 FAILED:
Found errors in Test_clipboard_nul():
Caught exception in Test_clipboard_nul(): Vim(normal):E353: Nothing in register * @ function RunTheTest[39]..Test_clipboard_nul, line 7
```

**Comment by brammool** [comment]
on what OS did you test?

**Comment by chrisbra** [comment]
Windows 10, built using Mingw 64bit. I suspect the appveyor test should fail with a similar message.

**Pull request closed without merging**
