### PR TITLE
Files for haskell persistent library are not recognized

### PR DESCRIPTION
**Pull request by lykahb**
Add filetype for the [persistent library](https://hackage.haskell.org/package/persistent). The extension `.persistentmodels` is recommended [here](https://hackage.haskell.org/package/persistent-2.14.5.0/docs/Database-Persist-TH.html#v:persistFileWith).

### CODE REVIEW

**Comment by brammool** [comment]
> Add filetype for the [persistent library](https://hackage.haskell.org/package/persistent). The extension `.persistentmodels` is recommended [here](https://hackage.haskell.org/package/persistent-2.14.5.0/docs/Database-Persist-TH.html#v:persistFileWith).

This uses the 'filetype' value "haskell.persistent".  This implies that
"persistent" by itself is a filetype.  Would it be used with anything
besides haskell?

I could not find an example of such a file.  What does it look like?

-- 
hundred-and-one symptoms of being an internet addict:
244. You use more than 20 passwords.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lykahb** [comment]
I do not think that this format would ever be used by anything else other than the haskell persistent library. It is a rather narrow use case, so I prefixed the filetype with haskell to avoid the potential name clashes.

Here are a few examples of the persistent files:
- https://github.com/naruto-unison/naruto-unison/blob/959786fe6f98fd8f9387c42c89ea04db5e34d544/config/models.persistentmodels
- https://github.com/Happy0/wordify-webapp/blob/7247dd751c2c20a55b6a8cc75ef7acdc5e9807be/config/models.persistentmodels
- https://github.com/chiroptical/cataract/blob/main/config/models.persistentmodels

**Comment by brammool** [comment]
> I do not think that this format would ever be used by anything else
> other than the haskell persistent library. It is a rather narrow use
> case, so I prefixed the filetype with haskell to avoid the potential
> name clashes.

When using a dot in the filetype: {base}.{extend}  this means that the
file has the filetype {base} with extra syntax items defined by
{extend}.  So you can have "c.doxygen" and "cpp.doxygen", where the
doxygen items (annotations found in comments) are used in "c" and "cpp"
filetypes.

If "persistent" is not used on top of any other filetype, then using a
specific name, such as "haskellpersist", works better.

It also looks like the examples do not contain any haskell syntax items.
Calling it "haskell plus some extra" is misleading then.

> Here are a few examples of the persistent files:
> - https://github.com/naruto-unison/naruto-unison/blob/959786fe6f98fd8f9387c42c89ea04db5e34d544/config/models.persistentmodels
> - https://github.com/Happy0/wordify-webapp/blob/7247dd751c2c20a55b6a8cc75ef7acdc5e9807be/config/models.persistentmodels
> - https://github.com/chiroptical/cataract/blob/main/config/models.persistentmodels

Thanks.  It looks like a specification of database entries.

-- 
hundred-and-one symptoms of being an internet addict:
246. You use up your free 1 Gbyte in two days.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lykahb** [comment]
Thank you for explaining the intended meaning of dot. The file may have haskell types occurring inside of it. Also, it may be included into a haskell file as an interpreted multiline string. It's not haskell plus extra, though.

Renamed to haskellpersistent.

**Pull request closed without merging**
