### PR TITLE
Fix session test by checking XDG_CONFIG_HOME too

### PR DESCRIPTION
**Pull request by jmdevin**
I haven't written vim tests before (I just finally got sick of this one
failing), so if someone who actually knows what they're doing could look this
over, I would appreciate it.

### CODE REVIEW

**Comment by chrisbra** [comment]
So it fails for you, because you are using ~/.config/vim directory in your system?

**Comment by jmdevin** [comment]
Correct. I'm not quite sure why `make test` would care which I'm using, but it seems to.

**Comment by chrisbra** [comment]
Thanks. However I think this is slightly simpler?
```diff
diff --git a/src/testdir/test_mksession.vim b/src/testdir/test_mksession.vim
index 914d1e3a4..cf4dcae71 100644
--- a/src/testdir/test_mksession.vim
+++ b/src/testdir/test_mksession.vim
@@ -1270,7 +1270,7 @@ func Test_mkview_default_home()
     " use escape() to handle backslash path separators
     call assert_match('^' .. escape($ORIGHOME, '\') .. '/vimfiles', &viewdir)
   elseif has('unix')
-    call assert_match('^' .. $ORIGHOME .. '/.vim', &viewdir)
+    call assert_match('^' .. $ORIGHOME .. '/' .. '\(\.config/\|\.\)' ..  'vim/', &viewdir)
   elseif has('amiga')
     call assert_match('^home:vimfiles', &viewdir)
   elseif has('mac')
```

**Comment by jmdevin** [comment]
It's simpler, but I believe it would fail if I had $XDG_HOME_CONFIG set to something other than the default of `$HOME/.config`.

**Comment by chrisbra** [comment]
okay fair enough

**Pull request closed without merging**
