### PR TITLE
PEM files are not recognized

### PR DESCRIPTION
**Pull request by ObserverOfTime**
The format is defined in [RFC7468](https://www.rfc-editor.org/rfc/rfc7468).

Things to consider:
- Should the filetype be "pem" or something else?
- Should we support more extensions (e.g. `.key`)?

### CODE REVIEW

**Comment by chrisbra** [comment]
the highlighting looks strange: 

image

I think pemLabel should be the same as pemBegin?

**Comment by brammool** [comment]
> the highlighting looks strange: 
> 
> image
> 
> I think pemLabel should be the same as pemBegin?

The RFC points out the label after BEGIN and END, thus recognizing it
separately in the syntax makes sense.  Section 4 also lists known
labels, these could be highlighted specifically.

-- 
hundred-and-one symptoms of being an internet addict:
238. You think faxes are old-fashioned.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> The format is defined in [RFC7468](https://www.rfc-editor.org/rfc/rfc7468).
> 
> Things to consider:
> - Should the filename be "pem" or something else?

Using "pem" for the 'filetype' name should be OK.  It could be more
specific, but I doubt that is useful.  The RFC mentions that PEM stands
for Privacy Enhanced Mail:

   The tradition within the RFC series can be traced back to Privacy-
   Enhanced Mail (PEM) [RFC1421], based on a proposal by Marshall Rose
   in Message Encapsulation [RFC934].  Originally called "PEM
   encapsulation mechanism", "encapsulated PEM message", or (arguably)
   "PEM printable encoding", today the format is sometimes referred to
   as "PEM encoding".  Variations include OpenPGP ASCII armor [RFC4880]
   and OpenSSH key file format [RFC4716].

"PEM encoding" should be more accurate, but is that generally used?
And I would not know a short name that is not confusing.  "pemencoding"
doesn't ring a bell for me.

> - Should we support more extensions (e.g. `.key`)?

The essential part of this filetype is encoded text in between lines:

	"-----BEGIN {label} -----"

and

	"-----END {label} -----"

If a file contains more than that we should give it a different filetype
name.

Section 5.3 of the RFC mentions ".crt" and ".cer".  Otherwise we can use
extensions that seem useful and don't conflict with other filetypes.
Generally it's better to first add the filetype and later add more
extensions when we find some that make sense.

-- 
hundred-and-one symptoms of being an internet addict:
237. You tattoo your email address on your forehead.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ObserverOfTime** [comment]
> Section 4 also lists known labels, these could be highlighted specifically.

I don't know if it's possible to highlight the known labels while keeping the catch-all match.

> The essential part of this filetype is encoded text in between lines:
>
>         "-----BEGIN {label} -----"

I suppose we could check if the first line matches `^-----BEGIN `.
Or the first few lines to account for possible comments?

**Comment by brammool** [comment]
Well, it can be several nested regions:
toplevel: from BEGIN to END line
marker: the line with BEGIN or END
label: the label part of "marker"

The toplevel can appear any number of times.  Just avoid matching it inside another one.

**Pull request closed without merging**
