### PR TITLE
Allow netrw to browse to root directories on Windows

### PR DESCRIPTION
**Pull request by Tumbler**
Fixes Issue https://github.com/vim/vim/issues/1085

### CODE REVIEW

**Comment by jfsse** [comment]
I am new to git and vim. This seems to work Is this going to be merged?

**Comment by mattn** [comment]
@cecamp ping

**Comment by cecamp** [comment]
jfsse wrote:
>
> I am new to git and vim. This seems to work Is this going to be merged?
>
>
Eventually -- I have some outstanding issues with netrw to address, and
my home computer's partition under Windows refuses to shrink (I wanted a
dual-boot system, and I need to make space for a linux partition). 
Guess I'll have to use a vm again.

Chip Campbell

**Comment by vim-ml** [comment]
> Eventually -- I have some outstanding issues with netrw to address, and
> my home computer's partition under Windows refuses to shrink (I wanted a
> dual-boot system, and I need to make space for a linux partition). 

If it's of any help, I've tried your modified version of this fix from your website and it works fine for me.

~Tumbler

**Comment by jfsse** [comment]
Good tip. Now I also have tested the version from the website and it works for me also.

**Comment by chrisbra** [comment]
closing then.

**Pull request closed without merging**
