### PR TITLE
Support final and const object and class variables

### PR DESCRIPTION
**Pull request by yegappan**
Implement the following item from the todo list:

- "final" object members - can only be set in the constructor.

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
was there something changed since that decision https://github.com/vim/vim/pull/12932#issuecomment-1699624713
which said 'final/const' is not but 'readonly' was preferred?

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
anyway, i think 'final' should be there, but the 'readonly' it was a confused concept.

**Comment by yegappan** [comment]
> was there something changed since that decision [#12932 (comment)](https://github.com/vim/vim/pull/12932#issuecomment-1699624713) which said 'final/const' is not but 'readonly' was preferred?

Any variable can be made a constant by using the `final` keyword.  This PR adds support for making an object variable constant (and can be assigned only in the constructor).  These variables cannot be reassigned even by other methods in the object.
This to make the use of the `final` keyword consistent between object variables and variables defined outside of an object.

**Comment by Shane-XB-Qian** [comment]
yea, i agreed and preferred 'final' (or 'const') should be there.

**Comment by vim-ml** [comment]
Hi,

I was waiting for PR https://github.com/vim/vim/pull/13670 to be merged.
As that PR is now merged, this PR (support for final and const object/class
variables) is ready.

Regards,
Yegappan

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
