### PR TITLE
fix xxd -b -r corrupting files

### LINKED ISSUE #13410: xxd -b -r corrupts files
### Steps to reproduce

simple test script:
```sh
#!/bin/sh
dd status=none if=/dev/urandom of=testfile1 bs=1k count=10
xxd -b testfile1 > testfile1.hex
xxd -b -r testfile1.hex > testfile2
if cmp -s testfile1 testfile2; then
    echo "Files are identical"
else
    echo "Files are different"
fi
rm testfile1 testfile1.hex testfile2
```

### Expected behaviour

test script should say "Files are identical" like it does with not using -b

### Version of Vim

9.0.2059 (latest commit as of writing)

### Environment

OS: fedora 38
Terminal: kitty
$TERM: xterm-kitty
shell: zsh 5.9

tested with xxd from fedora repos, as well as compiling latest [xxd.c](https://raw.githubusercontent.com/vim/vim/0ab500dede4edd8d5aee7ddc63444537be527871/src/xxd/xxd.c) from with `cc -O2 -DUNIX xxd.c -o xxd`

### PR DESCRIPTION
**Pull request by Un1q32**
fixes #13410

### CODE REVIEW

**Comment by k-takata** [comment]
@OldWorldOrdr 
Could you include this test? https://github.com/vim/vim/issues/13410#issuecomment-1776797453

**Comment by Shane-XB-Qian** [comment]
keep the credits if matter, perhaps just wait 12 hours, or k.taKate you can do it.
// no need to hurry, and perhaps gave some time to re-check/think, maybe. :smile:

--
shane.xb.qian

**Comment by OldWorldOrdr** [comment]
> @OldWorldOrdr Could you include this test? [#13410 (comment)](https://github.com/vim/vim/issues/13410#issuecomment-1776797453)

done

**Comment by chrisbra** [comment]
please also update the version header: https://github.com/vim/vim/blob/5b49428bfc9c2e723f9b2e3eea2e442621082c74/src/xxd/xxd.c#L139

**Comment by OldWorldOrdr** [comment]
> please also update the version header:
> 
> https://github.com/vim/vim/blob/5b49428bfc9c2e723f9b2e3eea2e442621082c74/src/xxd/xxd.c#L139

done

**Comment by OldWorldOrdr** [comment]
anything else need to be done?

**Comment by tristhaus** [comment]
FWIW my tests were successful, including a manual test with +42k bytes and one with all possible bytes.

**Comment by chrisbra** [comment]
I just haven't gotten to merge it yet, too busy with non-Vim stuff :(

**Pull request closed without merging**
