### PR TITLE
plugin/gzip.vim: add brotli support

### PR DESCRIPTION
**Pull request by 532910**
Add support for editing *.br files

Signed-off-by: Sergio E. Nemirowski <sergio@outerface.net>

### CODE REVIEW

**Comment by brammool** [comment]
I'll include it, thanks.

**Comment by 532910** [comment]
Please add lzop (`*.lzo`) also!

**Comment by 532910** [comment]
Bram, thank you for adding it. But what's about lzop? And what was wrong with my PR?

**Comment by brammool** [comment]
> Bram, thank you for adding it. But what's about lzop? And what was
> wrong with my PR?

I don't see lzop in the patch.

I don't understand the remark about something being wrong.

-- 
hundred-and-one symptoms of being an internet addict:
81. At social functions you introduce your husband as "my domain server."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> And what was wrong with my PR?

Nothing.  Bram doesn't use the "Merge" button.  He applies the changes manually to his repo and pushes that out.

**Pull request closed without merging**
