### PR TITLE
add openscad filetype and syntax

### PR DESCRIPTION
**Pull request by salkin-mada**

### CODE REVIEW

**Comment by brammool** [comment]
I'll make a patch for the filetype detection.  The syntax file will be in the next runtime files update.

**Comment by brammool** [comment]
I notice the syntax file is setting 'iskeyword'.  If that is really what you want, this belongs in a filetype plugin.
If this was intended to be used for the syntax file, the ":syn iskeyword" should be used.

**Comment by salkin-mada** [comment]
> I notice the syntax file is setting 'iskeyword'. If that is really what you want, this belongs in a filetype plugin. If this was intended to be used for the syntax file, the ":syn iskeyword" should be used.

Ah true! Thanks. Should I create a new PR for the syntax or just force push again here, nevertheless that its closed?

**Comment by brammool** [comment]
Please create a new PR. I had already included the file.

**Pull request closed without merging**
