### PR TITLE
netrw:launch:unix:gvim: do not detach

### PR DESCRIPTION
**Pull request by Konfekt**
On Debian 12 when detaching the program wouldn't launch at all

### CODE REVIEW

**Comment by chrisbra** [comment]
Ah, I think that is a famous bug, that we have not yet fixed. For some it works and for some it does not and I think it may also be related to your $SHELL. Hopefully this workaround works for everyboday.

**Comment by Konfekt** [comment]
A link to the issue could help? It was `/bin/zsh`

**Comment by chrisbra** [comment]
couldn't find it. I believe this one is it: #8314 and #8951

**Comment by Konfekt** [comment]
Yes, maybe https://github.com/vim/vim/issues/8951#issuecomment-1207140070 is a good start

**Comment by Konfekt** [comment]
It seemingly only affects `zsh`. I checked that with `$SHELL=/bin/bash` there's no issue. Should an additional check for `&shell =~ '\<zsh$'` be added? Not backgrounding seems to work fine with `bash` as well, though

**Comment by chrisbra** [comment]
If this doesn't cause any harm, let's keep it like this. Keeps it simpler.

**Pull request closed without merging**
