### PR TITLE
Make_mvc.mak does not recognize nmake for VS2015 Update 1

### PR DESCRIPTION
**Pull request by nanis**
Add the relevant version string to the list of version strings to be checked.

### CODE REVIEW

**Comment by k-takata** [comment]
Could you check #224? (and see also #496)

**Comment by nanis** [comment]
@k-takata Definitely. Thanks for pointing that out to me. I'll report back in a day.

**Comment by nanis** [comment]
Worked like a charm.

My tree with the patch applied https://github.com/nanis/vim/tree/Make_mvc-patch

**Comment by chrisbra** [comment]
Fixed with 7.4.960.

**Pull request closed without merging**
