### PR TITLE
Add style check for help files

### PR DESCRIPTION
**Pull request by h-east**
When this PR is merged, I will work on the TODO over the next week or so.

TODO: Check over 80 columns.
(See near the end of `Test_help_files()` in test_codestyle.vim)

--
Best regards,
Hirohito Higashi (h_east)

### CODE REVIEW

**Review by cvwillegen — COMMENTED** [review]
From the diff on Github, it's not obvious if all the space/tab problems have been fixed here...

**Comment by h-east** [comment]
@cvwillegen 
Huh? I added [test code](https://github.com/vim/vim/pull/11952/commits/4144f22062f3baae576dbba8f3f2085aba5ad425#diff-40e056371fe28c3c079a4cf274ac313b9a9c8330f561ed04db5bd08c073d37ae
).
We can check by the CI result is green or not.

**Comment by cvwillegen** [comment]
Wait, I know what's the problem! I saw the test code, so I _assumed_ it was correct, but GitHub doesn't show the difference between spaces and tabs (in the web browser). So, I saw red and green lines that had 'blocks' in them that were the same length, or perhaps a different length, and that must have been mixed space/tab lines that you replaced by all tabs, and they turned out to be the same length..

Sorry for the trouble!

**Comment by brammool** [comment]
I'll include the changes to help files.  After the next runtime files update you can sync this PR and only the test change should remain.

**Comment by h-east** [comment]
@brammool Feel free to merge.

**Pull request closed without merging**
