### PR TITLE
runtime: remove inactive maintainer

### PR DESCRIPTION
**Pull request by dundargoc**
The mail address doesn't seem to exist anymore and most files haven't
been updated in 10+ years.

### CODE REVIEW

**Comment by chrisbra** [comment]
Have you verified that the email address is invalid? Also if we change those, dan sharp should be moved to `Former Maintainer` and probably add a note like `This runtime file is looking for a new maintainer`.

**Comment by dundargoc** [comment]
> Have you verified that the email address is invalid?

I tried mailing him from two different mail addresses from two different email providers. I don't know if there's a more formal way to verify if it exists (or if that even matters, only accepting *some* emails based on an arbitrary criteria is even more problematic than not working at all).

**Comment by chrisbra** [comment]
okay thanks

**Comment by brammool** [comment]
Dan replied to me. He won't maintain the files anymore.  The email address at SourceForge no longer works, that can be removed.  Looks like this PR is OK to include now.

**Comment by Shane-XB-Qian** [comment]
thanks those contributor.

**Pull request closed without merging**
