### PR TITLE
ConPTY support

### PR DESCRIPTION
**Pull request by ghost**
~~Triggers that winpty.dll does not exist.~~
I would like to ask how to change this.
There are various ways. Please show me the way.

```:term vim``` a number of times, the color of the status bar changes. This could not be completed.

I was late as I went to my father's grave visit. I'm sorry.

### CODE REVIEW

**Comment by ghost** [comment]
I had forgotten all about gVim. I will start from now.

**Comment by ghost** [comment]
I can not get the standard I/O of the console by all means.
Without it VTP can not be used.
Therefore ConPTY can not be used.
End.

**Comment by ghost** [comment]
Using AllocConsole in advance will succeed. The console window is displayed.
I can not get anything from STARTUPINFO.
Console window with SW_HIDE attribute has no standard input/output.
CONIN$, CONOUT$ will fail if there is no console window.
"CON" is also the same.
CreateProcess (CREATE_NEW_CONSOLE) fails.
OpenConsole (undocumented API) also fails unless after AllocConsole.
here we go?
In order to turn on VTP, the displayed console window is required specification.

**Comment by ghost** [comment]
Oops.

> What we announced in the associated blog post was a Pseudo Console, not a Pseudo Terminal/TTY.
https://github.com/Microsoft/console/issues/235

It does not seem to fit gVim. I will advance.

**Comment by ghost** [comment]
image

**Comment by ghost** [comment]
In gVim:

image

**Comment by ghost** [comment]
I'm sorry I have not finished it yet. Code reading is insufficient.

**Comment by ghost** [comment]
Windows 10 (1809) has been released. how is it?

**Comment by ghost** [comment]
I'm late.
Since the test did not succeed, I have read the code further.
I have commented out one test with this commit.
That will fail.

It looks line conhost.exe is deadlocked.
If you kill that conhost.exe process, Vim keeps running.
I am looking for a workaround.

AppVeyor now has an error. to correct.

**Comment by ghost** [comment]
About nonblocking test.
In Windows, pipe implementation is done in the file system called NPFS.
Generally, file systems do not support non-blocking.

**Comment by ghost** [comment]
Repeating to hang up immediately after committing...

**Comment by ghost** [comment]
I will retire.
Please use this code freely.
Thank you very much.

**Comment by brammool** [comment]
Why did you close this?  Is it not fully working and you are giving up?

**Comment by k-takata** [comment]
I don't know why @ntak closed this PR, but...

> Please use this code freely.

Because @ntak deleted his account, we cannot retrieve his code anymore.
So, I created a copy of his patch manually:
https://gist.github.com/k-takata/d743783c86fc80509b0b0b1d56582c5b
(I haven't tested this yet at all.)

**Comment by blayz3r** [comment]
So is ConPTY support dead? Any plans on continuing the PR

**Comment by chrisbra** [comment]
@blayz3r  instead of bumping this issue, you should try out the patch and see if this fixes your problems.

**Comment by blayz3r** [comment]
Right. Can do that. Is the plan to merge it into vim proper. It looked like the project was just abandoned. @chrisbra BTW how do I compile vim with the patch

**Comment by k-takata** [comment]
See #3794.

**Pull request closed without merging**
