### PR TITLE
NSIS Translation, plus a few minor improvements & fixes

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Comment by brammool** [comment]
I had already included this patch, but forgot to close the pull request.
I'll close it now.  If something is missing, please open a new one.

**Comment by bitigchi** [comment]
If I want to submit an update/improvement, shall I wait for the previous updates to be visible on Github, or I just open another pull request?

**Comment by brammool** [comment]
> If I want to submit an update/improvement, shall I wait for the
> previous updates to be visible on Github, or I just open another pull
> request?

If you don't want to wait for the next runtime file update, it's easier
for me to merge if you send me the new version of the whole file.

-- 
hundred-and-one symptoms of being an internet addict:
17. You turn on your intercom when leaving the room so you can hear if new
    e-mail arrives.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
FYI, sent an e-mail with the latest changes.

**Pull request closed without merging**
