### PR TITLE
[WIP] rewrite hitest.vim

### PR DESCRIPTION
**Pull request by lacygoill**
There are several issues with `$VIMRUNTIME/syntax/hitest.vim`.
```vim
vim9script
&wildchar = char2nr("\<Tab>")
&wildcharm = &wildchar
runtime syntax/hitest.vim
```
    E475: Invalid argument: SpecialKeySpecialKey

Expected: no error is given.
Actual: an error is given:

    E475: Invalid argument: SpecialKeySpecialKey

I think that's because the script executes a macro.  This can be fixed by temporarily resetting `&wildcharm` to its default value.

---
```vim
vim9script
execute "set <S-F12>=\<Esc>A"
execute "set <F35>=\<Esc>x"
inoremap <F35> <Nop>
inoremap <S-F12> <Nop>
source $VIMRUNTIME/syntax/hitest.vim
```
Expected: The highlight groups in the second column are highlighted, and their names are properly spelled.
Actual: They are not highlighted, and their names are prefixed with an `A`.

That's because of these `<Esc>` which are pressed by `:normal`:

    global /^/ exe "normal Wi\<CR>\t\eAA\ex"
                                    ^^  ^^

This could be fixed by appending `:normal` with a bang.

---

It seems the script relies on the value of `'highlight'` to determine which groups are meant to highlight languages, and which ones are not (those are under the "various occasions" section).

But `'highlight'` is not reliable.  Which is why we get some wrong groups in the 2nd section:

   - `MatchParen`
   - `Normal`
   - `PopupSign`

For example, `PopupSign` has nothing to do with any language syntax, so it should be in the first section ("various occasions"), not the 2nd one.

A better alternative would be to look for help tags starting with `hl-`.  Something like this:
```vim
vim9script
echo getcompletion('hl-', 'help')
    ->filter((_, helptag: string): bool => helptag =~ '^hl-\w\+$')
    ->map((_, helptag: string) => helptag->substitute('^hl-', '', ''))
```
Although, it's still imperfect, because the Vim help is missing a few tags:

  - `hl-lCursor`
  - `hl-ToolbarButton`
  - `hl-ToolbarLine`

But as soon as those are added, the previous code will automatically pick them up.

---

I think the script tries to print linked highlight groups on the same line:

    silent! global /links to/ normal mz3ElD0#$p'zdd

But it fails.  At the end, no link is printed.  I think part of the issue comes from the `#` normal command which assumes that there is a previous occurrence of the group under the cursor.  There might not be.  And if there aren't, `dd` deletes a line which should be kept.

Anyway, on my machine, I only get these kind of lines:

    SomeGroup SomeGroup
              ^-------^
              useless repetition

And no link is followed.  Not sure how to fix the current code to make it work.

---

About these lines:

    " Move split 'links to' lines to the same line
    % substitute /^\(\w\+\)\n\s*\(links to.*\)/\1\t\2/e

The pattern never matches (but we don't get any error because of `:help s_e`).  It's useless.  It might have been necessary in the past when "links to" was on a separate line, but that's not the case anymore.

---

There is a 16-lines-long `if` block (`if exists('hitest_filetypes')`).  I haven't been able to find any documentation about its meaning.  AFAICT, this variable is not set or referenced anywhere else, so the whole block seems useless.  I've also done a quick test, setting `g:hitest_filetypes`; it didn't make any difference in the results.

---

The script takes too much time.  I tested with this command, which simply opens a help buffer and my vimrc:

    $ vim +'set wildcharm& | execute "set <S-F12>=" | execute "set <F35>=" | help' +'edit $MYVIMRC'

Then, I ran:

    :Time source $VIMRUNTIME/syntax/hitest.vim

Where `:Time` is:
```vim
vim9script
command -range=1 -addr=other -nargs=+ -complete=command Time Time(<q-args>, <count>)
def Time(cmd: string, cnt: number)
    var time: list<number> = reltime()
    try
        if cnt > 1
            var i: number = 0
            while i < cnt
                execute cmd
                ++i
            endwhile
        else
            execute cmd
        endif
    catch
        echomsg v:exception
    finally
        time = time->reltime()
        redraw
        echomsg time
            ->reltimestr()
            ->matchstr('.*\....') .. $' seconds to run :{cmd}'
    endtry
enddef
```
Here are 10 measurements, while the system is idle:

    4.306 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    5.433 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    5.288 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    5.337 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    5.339 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    5.292 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    2.993 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    2.929 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    2.988 seconds to run :source $VIMRUNTIME/syntax/hitest.vim
    2.991 seconds to run :source $VIMRUNTIME/syntax/hitest.vim

That's 4.29 seconds on average.

The current PR tries to rewrite the script completely.  Instead of using a macro, and edit the buffer with normal commands, it uses more recent functions like [`hlset()`](https://vimhelp.org/builtin.txt.html#hlset%28%29) and [`hlget()`](https://vimhelp.org/builtin.txt.html#hlget%28%29).

It should fix all the previously mentioned issues, and is faster:

    0.081 seconds to run :source ~/s.vim
    0.083 seconds to run :source ~/s.vim
    0.086 seconds to run :source ~/s.vim
    0.087 seconds to run :source ~/s.vim
    0.077 seconds to run :source ~/s.vim
    0.078 seconds to run :source ~/s.vim
    0.076 seconds to run :source ~/s.vim
    0.087 seconds to run :source ~/s.vim
    0.077 seconds to run :source ~/s.vim
    0.081 seconds to run :source ~/s.vim

That's 0.081 seconds on average, which is about 53 times faster than the current script.

It also provides a few features which are documented in a popup help window.  The latter can be toggled by pressing `g?`.  For example, it tries to let the user:

   - interactively "edit" the highlight group under the cursor (by adding/removing/changing arbitrary attributes)
   - save the current state of all the highlight groups
   - traverse a stack of states (undo/redo)
   - interactively create new groups, and rename or duplicate existing ones
   - open the help for the group under the cursor (by pressing `K`) if one is available
   - save the current colors as a Vim script file (i.e. with `:highlight` commands)

I don't know how reliable it is, as I've just finished it.
It probably requires a very recent Vim version (if only because it uses [`:help interp-string`](https://vimhelp.org/eval.txt.html#interp-string)).

If more documentation is necessary, I can try to write one.  Although, the current script is not better documented, and the popup should already have enough information.

I can't maintain the script, but I can try to fix some of its issues if they don't take too much time, and if it's considered as useful.  Otherwise, feel free to close the PR.

### CODE REVIEW

**Comment by lacygoill** [comment]
I didn't realize this would lower test coverage so much.  I'll try the extract the code responsible for providing the new features in a separate script, and maybe suggest it to the devs of https://github.com/vim/colorschemes , or just discard it.

**Comment by lacygoill** [comment]
> Any other comments?

Apparently not many people are interested.  AFAICT, the new script still works.

**Comment by brammool** [comment]
The original idea of the script was to "see all the groups currently active".
So you don't need to open a file with specific items to see what highlight is used.

I'm not sure what the goal is of the modified script that is proposed here.
I thought it was just intended to work better and faster, but now I see all kinds of commands.
And the script has grown to 1150 lines.
Perhaps this is useful for someone who is creating or editing a colorscheme?

**Comment by lacygoill** [comment]
Understood.  I removed all the extra features, which brings the number of code lines down to 184 (+ 15 lines of comments and 29 empty lines).

**Comment by lacygoill** [comment]
I've reduced the code even more.  Now, it's only 95 lines of code, which is pretty much on par with the old script.

**Comment by backdround** [comment]
Original `hitest` doesn't work for people who have some mappings, because of absence of `bang` for `normal` commands.

**Comment by brammool** [comment]
Can you please add a header to the new file, with a maintainer item?
And an entry in .github/CODEOWNERS if possible.

**Pull request closed without merging**
