### PR TITLE
Filetype detection for fennel

### PR DESCRIPTION
**Pull request by dchinmay2**
cc @bakpakin I used your plugin

### CODE REVIEW

**Comment by dchinmay2** [comment]
Do I need to make these tests pass?

**Comment by brammool** [comment]
Please add a test in src/testdir/test_filetype.vim

**Comment by brammool** [comment]
Oh, and the getline() should not be around the autocommand.  Since you check the hashbang line, use runtime/scripts.vim.

**Comment by dchinmay2** [comment]
>  Since you check the hashbang line, use runtime/scripts.vim.

Ah sorry I'll change that.

> Please add a test in src/testdir/test_filetype.vim

I'll need help with that, I have no idea what kind of test to add :sweat_smile:

**Comment by dchinmay2** [comment]
I had a look at the file, I'll try to write a test

**Comment by dchinmay2** [comment]
I wrote the tests, please take a look

**Comment by dchinmay2** [comment]
I copied the detection code from https://github.com/bakpakin/fennel.vim which is MIT-licensed, not sure if it is allowed?

cc @bakpakin

**Comment by brammool** [comment]
I do not see anything specific here, there is only one way to write it, so the license doesn't matter.
Looks OK now, I'll include it.

**Comment by bakpakin** [comment]
For the record, this is fine w/ me

**Pull request closed without merging**
