### PR TITLE
Fix visual block gap on scroll with scrolloff

### LINKED ISSUE #6053: Visual selection drawn incontinuously
**Describe the bug**

As the title says visual selection may be drawn incontinuosly in some cases:
 
screenshot

**To Reproduce**

1. `vim +'set scrolloff=7' +44 https://raw.githubusercontent.com/metashell/metashell/master/test/system/mdb/test_continue.cpp` (I have no configuration.)
2. (Ensure that initial(!) `winheight(0) == 40`, or at least close to it.)
3. Press <kbd>V</kbd> then <kbd>CTRL-D</kbd> 7 times. (Sometimes also enough pressing once and standing on line 43/44… there are various possible circumstances.)

**Expected behavior**

No missing parts.

**Environment:**
 - Vim version 8.2 (Stock Arch Linux)
 - OS: Arch Linux
 - Terminal: urxvt/alacritty

### PR DESCRIPTION
**Pull request by aufarg**
After scrolling down using CTRL+D, one win_update() is called and the
following steps will happen in order:

  1) Propagate the line informations that is not above the wp->w_topline
     entries upwards.

  2) Calculate the range of lines affected by the scroll.

  3) Updates wl_lnum of affected lines.

In some cases, win_update() starts with buf->b_mod_set set to true. One
example where this can happen is when two scroll happens, the first
scroll results in the cursor pointing to a parentheses/bracket and the
second scroll results in the matched parentheses/bracket positioned
right at w->w_topline.

The first scroll generates a CursorMoved event that gets applied by
matchparen autocommand, which will result in a call to match_add() and
set buf->b_mod_set to true. The second scroll generates the same event,
in this calling match_delete() and set buf->b_mod_set to true.

When buf->b_mod_set is set to true and the modified line is positioned
right at w->w_topline, the step 1) of win_update() does not happen
because the first conditional will be be chosen instead. This results in
stale wl_lnum for lines above wp->w_topline.

The calculation done on the second step requires the wp->w_topline to be
found. However, if the propagation step does not happen, the line that
correponds to wp->w_topline will be situated are the line with higher
index than the reality, hence the resulting rendering gap. This doesn
not happen when scrolloff is not set because the lines are drawn until
the end anyway.

This commit fixes this by making sure we propagate the line if the
window has definitely scrolled.

Fixes: #6053

### CODE REVIEW

**Comment by aufarg** [comment]
I don't know how write the test function for this. The current test function that I wrote is able reproduce the bug, but I don't know how to do the assertion. `feedkeys()` seems to not wait until the command is completed and `screenattr()` is not updated, while using `:normal` does not trigger the bug (it seems the visual selection is drawn once for both `CTRL+D`).

**Comment by brammool** [comment]
For feedkeys() add "x" to execute right away.
In a test redrawing might work differently.  An alternative is to use a screendump test.  It's slower, but good to reproduce screen updating problems.  And it's easy to see what is wrong.

**Comment by aufarg** [comment]
Okay, I managed to use screendump test for this.

**Comment by brammool** [comment]
Thanks!  Now I can easily see what you are fixing.

**Pull request closed without merging**
