### PR TITLE
Add `term_getruncmd` function

### PR DESCRIPTION
**Pull request by ichizok**
`term_getruncmd()` is to get information of the process running on the shell of terminal window.
Windows support was done by @mattn.

Example:
Do `:terminal` to run `&shell` and execute `sleep 10` on the shell,
then `term_getruncmd(<buf>)` returns `{'process': <pid of sleep>, 'command': 'sleep'}`.

confirmed on:

* [x] Windows
* [x] macOS
* [x] Linux
* [x] Solaris
* [ ] *BSD

Ozaki Kiichi

### CODE REVIEW

**Comment by mattn** [comment]
I can improve this something for Windows after this will be merged.

**Comment by mattn** [comment]
Ah, sorry. I missed Issue No.

**Comment by brammool** [comment]
Ozaki Kiichi wrote:

> `term_getruncmd()` is to get information of the process running on the shell of terminal window.
> Windows support was done by @mattn.
> 
> Example:
> Do `:terminal` to run `&shell` and execute `sleep 10` on the shell,
> then `term_getruncmd(<buf>)` returns `{'process': <pid of sleep>, 'command': 'sleep'}`.
> 
> confirmed on:
> 
> * [x] Windows
> * [x] macOS
> * [x] Linux
> * [ ] *BSD
> * [ ] Solaris

What is the practical use of this?

-- 
5 out of 4 people have trouble with fractions.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tyru** [comment]
Now I see this feature, I came up an idea of plugin like this:

* :TermList
  * Opens a buffer which lists terminal buffers in every lines, with title, status, command line
  * `<CR>` opens/jumps to the terminal buffer
* TermRun {cmd}
  * Runs `{cmd}` with `term_start()`, and associates it to current tabpage (adds to `t:running_terms` list)
  * Show the running command in statusline, or Vim window title, or WinBar to be able to click to open the buffer

**Comment by brammool** [comment]
> Now I see this feature, I came up an idea of plugin like this:
> 
> * :TermList
>   * Opens a buffer which lists terminal buffers in every lines, with title, status, command line
>   * `<CR>` opens/jumps to the terminal buffer
> * TermRun {cmd}
>   * Runs `{cmd}` with `term_start()`, and associates it to current tabpage (adds to `t:running_terms` list)
>   * Show the running command in statusline, or Vim window title, or WinBar to be able to click to open the buffer

What happened with the plan to use term_getjob() and then job_info()?

-- 
Every time I lose weight, it finds me again!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tyru** [comment]
@brammool Sorry if I'm wrong, but it seems `term_getjob()` and `job_info()` cannot get command line (running program name and its arguments).

**Comment by brammool** [comment]
Yes, so the idea was to improve job_info() instead of adding a new function.

**Comment by tyru** [comment]
@brammool Ah, it sounds it's a better API!
It can also get command line from a job invoked by `job_start()`, not only terminal :)

**Comment by ichizok** [comment]
The point of `term_getruncmd()` is to get the process which is "associated with the tty device (of the specified job/term)" and "running on foreground".
In other words, this is the information associated with tty device, rather than job.
Thus it should be assumed the terminal, or the job with tty at least.

**Comment by chrisbra** [comment]
This pull request **introduces 1 alert** when merging fe092d68e7512831f567a0e572f264e172c808ad into 8b0d5ce881ac16a36ea00018ba13a58b0fdb7534 - [view on LGTM.com](https://lgtm.com/projects/g/vim/vim/rev/pr-c951dc0122ca786b307165b1b2b14e944d9ec241)

**new alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chrisbra** [comment]
This pull request **introduces 1 alert** when merging 445d436b30821db9aabf7f1ec28d69de4f80f35b into 8b0d5ce881ac16a36ea00018ba13a58b0fdb7534 - [view on LGTM.com](https://lgtm.com/projects/g/vim/vim/rev/pr-2c4e48469fb0467cf4a6cee007b285023a0f8c10)

**new alerts:**

* 1 for Wrong type of arguments to formatting function

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by brammool** [comment]
Can we close this, since job_info() returns the process ID and the command arguments?

**Comment by ichizok** [comment]
> Can we close this, since job_info() returns the process ID and the command arguments?

No, job_info() cannot cover the feature of this term_getruncmd().

```
:term /bin/bash

bash$ sleep 10
```

When did the above operations, the details of each commands are the below:
 
```
"bash" == run from term_start(), job_info() returns this process info
  |
  |- "sleep 10" == foreground process, child of "bash", Vim cannot follow this for now and term_getruncmd() returns this command line
```

However, in retrospect, maybe this function name should indicate the relevance to tty (e.g. tty_getcmd) rather than term_xxx.
I'll close this since I have no practical idea for now, thank you.

**Comment by brammool** [comment]
Ah, you want info about the command that was started in the shell.  Hmm, that is a bit far from Vim.  Also the shell could start a shell that runs a command, or run a command in the background, etc.  I don't think functionality for this should be build into Vim.

**Pull request closed without merging**
