### PR TITLE
refactor C omni completion in Vim9 script

### PR DESCRIPTION
**Pull request by lacygoill**
Probably too early to merge, but I thought someone might find this useful (for better performance) and/or report bugs.  It works on 8.2.2808.

### CODE REVIEW

**Comment by brammool** [comment]
> Probably too early to merge, but I thought someone might find this
> useful (for better performance) and/or report bugs.

Thanks.  I'll add a remark in the todo list, to include this once Vim9
is stable.  Feel free to update the PR over time till then.


-- 
I have read and understood the above. X________________

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Please check if this is ready to be included.

**Comment by lacygoill** [comment]
I've regularly made a simple test in `src/evalfunc.c`.  Inserting the `e` character, then typing `C-x C-o`.  It has been working fine for several months.  But I don't know how reliable it is in the general case.  I pushed a last commit for minor changes.  If there are still issues, I would need more feedback.

**Comment by lacygoill** [comment]
I forgot: the code compiles.  Adding `:defcompile` at the end of the script, then sourcing it, does not give any error.

**Comment by brammool** [comment]
Let me include it now, will be in the next runtime files update.  We'll see if we run into any problems.

**Pull request closed without merging**
