### PR TITLE
Add the blob2list() and list2blob() functions

### PR DESCRIPTION
**Pull request by yegappan**
Related e-mail threads on the vim-dev mailing list:

https://groups.google.com/g/vim_dev/c/c82X7U4MD9Y/m/x_Gd9ylRBQAJ
https://groups.google.com/g/vim_dev/c/4CDTjFu-P9A/m/OtS5qTsUCAAJ

### CODE REVIEW

**Comment by brammool** [comment]
check_for_blob_arg() is only used for Vim9 script, but is then followed by another check for VAR_BLOB.
Looks like when using check_for_blob_arg() always the second check can be dropped.
Similarly for check_for_list_arg() in f_list2blob().

**Comment by brammool** [comment]
list2blob() fails if one of the numbers is negative.  As it is now, a value over 255 ends up overflowing, taking the lower 8 bits.
I think we should also fail if the number is above 255.
This is a bit strict, I suppose if someone wants to do avoids errors filtering the list first would be the solution.

**Comment by brammool** [comment]
Sorry for the confusion, since it was a small change I already added the check for the number value.  And give an error message mentioning the invalid number, otherwise there is no clue, other than getting an empty result.
I hope this works OK, otherwise we can still change it.

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Sep 14, 2021 at 1:39 PM Bram Moolenaar ***@***.***>
wrote:

> Sorry for the confusion, since it was a small change I already added the
> check for the number value. And give an error message mentioning the
> invalid number, otherwise there is no clue, other than getting an empty
> result.
> I hope this works OK, otherwise we can still change it.
>
>
>
Your changes look good to me.

Regards,
Yegappan

**Pull request closed without merging**
