### PR TITLE
Add improved Modula-2 runtime support

### PR DESCRIPTION
**Pull request by dkearns**
This is an initial attempt at merging @trijezdci's improvements.  See #6796.

Outstanding issues:
- is it reasonable to remove `*.m2`, `*.mi`, and `*.md` extensions? The latter was removed sometime ago.  These extensions are mentioned in several places but I don't recall having seen them and Benjamin mentions that they're non-standard in his repo and recommends removing them. E.g., [Ulm's Modula-2 compiler](http://www.mathematik.uni-ulm.de/modula/man/man1/m2c.html) uses *.m2
- should there be a default `modula2` filetype for backward compatibility which simply sources the appropriate default dialect?  I'm not sure what dialect the current syntax file is targetting.
- the dialect selection should be documented in a help file entry
- filetype detection tests

### CODE REVIEW

**Comment by dkearns** [comment]
@yegappan I'll try and get this done soon as well if you want to tag it as vim-9.1 milestone.  GCC recently included the Modula-2 frontend and current support could certainly be improved.

**Comment by yegappan** [comment]
I have added this PR to the vim-9.1 milestone.  We can revisit this after the other PRs are merged.

**Comment by trijezdci** [comment]
I have added a HELP file with a description of dialect tags.

https://github.com/trijezdci/M2-Syntax-Colour/blob/master/Vim/HELP

**Comment by trijezdci** [comment]
> * Benjamin mentions that they're non-standard in his repo and recommends removing them. E.g., [Ulm's Modula-2 compiler](http://www.mathematik.uni-ulm.de/modula/man/man1/m2c.html) uses *.m2

The Mtc Modula-2 to ANSI-C translator of the University of Ulm uses non-standard filetypes:

*.d instead of the standard *.def
*.m2 instead of the standard *.mod

This doesn't justify using those. Try and do a search for published Modula-2 sources with these non-standard file endings. I predict that you won't find any. And the Mtc translator is hopelessly outdated since it only supports ANSI-C. If you were to convert any legacy Modula-2 sources with it, chances are that the ANSI-C output will not build on any modern C compiler. This software simply doesn't set any standards and the bad habits by its creators shouldn't be perpetuated.

The standard has always been .def and .mod, either in all uppercase or lowercase.

**Comment by trijezdci** [comment]
> @chrisbra I think this is ready to take a look at now, thanks.

@dkearns Thanks a lot for getting this done.

Unfortunately, there is a discrepancy in the documentation comments regarding the number of lines that are being checked to find a dialect tag.

It says 200 lines in line 2272 of file runtime/doc/syntax.txt, but 100 lines in line 26 of file iso.vim, line 27 of file pim.vim and line 24 of file r10.vim, all within directory runtime/syntax/modula2/opt.

I had specified 200 lines generously in order to accommodate source files that list author, copyright and license terms at the beginning and I implemented it that way as can be seen in line 540 of file runtime/autoload/dist/ft.vim which defines constant LINE_COUNT with a value of 200.

I don't remember why I wrote 100 lines into the comments of the iso/pim/r10 specific vim files. This is definitely a mistake. Although it won't have an impact on the behaviour, it should nevertheless be corrected as it represents documentation. I am sorry about the inconvenience.

**Comment by chrisbra** [comment]
fine with me, but could you please address @trijezdci points?

**Comment by trijezdci** [comment]
> You're right that they're not much use as is and Bram removed `*.md` some time ago so he was obviously not opposed to dropping these even as an old eighties M2 programmer.
> 
> I took your challenge and found about a [thousand files](https://github.com/search?q=path%3A%2F.*%5C.%28mi%7Cmd%7Cm2%7Cd%29%24%2F+%2F%5E%28%3F-i%29+*%28IMPLEMENTATION%7CDEFINITION%29+*MODULE+.*%3B%2F&type=code) using these extensions on GitHub.

These are all archaic non-standard uses.

I don't think such archaic non-standard uses should be auto-recognised.

> Personally, I find it quite handy to have the highlighting work when engaging in some programming archeology

You can always use the VIM menu and choose the language manually. Removing automatic recognition of non-standard file extensions will not prevent you or anyone else from using syntax highlighting with files whose non-standard file extensions are not automatically recognised.

First and foremost, VIM's language support should be correct, complete and consistent, that is to say ...

(1) VIM should recognise standard file extensions (=> correctness)
(2) For supported languages where files come in pairs, like *.h and *.c for C, VIM should recognise both file extensions, not just one (completeness and consistency).

At present, VIM recognises *.mi as Modula-2, but not the corresponding *.md. As you have already pointed out, Bram had removed *.md. Either both are recognised (as non-standard Modula-2), or neither should be.

The same applies to the pair (*.d, *.m2). At present, VIM recognises *.m2 as Modula-2, but not the corresponding *.d. Again, either both are recognised, or neither should be.

There have also been uses of the pair (*.d, *.m). Neither is recognised by VIM as Modula-2, but if other non-standard uses are recognised, then how can it be justified that this non-standard usage isn't?!

In fact, (*.d, *.m) makes the most sense of all non-standard uses as it is merely an abbreviated variant of the standard (*.def, *.mod), perhaps even forced on the compiler developers by a filesystem that didn't permit more than one character file extension or severely restricted the total length of the filename including the extension. 

So, I say, in order to avoid name space pollution, VIM' auto-recognition should exclude non-standard uses altogether. For non-standard uses there is manual selection via the language menu.


> I'll send a PR to your rep with some of the changes I made here and you decide how you want to proceed with regard to syncing the repos to make updates easier.

thanks

**Comment by trijezdci** [comment]
> I was planning on fixing all the issues you mention, I just didn't consider it necessary to include in this change.

Fair enough.

> Just to be clear, I have already removed the non-standard extensions in this PR.

> Anyway, unless @chrisbra objects, you can consider them gone.

Great. Thanks.

**Comment by chrisbra** [comment]
I am fine to merge. Can we consider #6796  fixed with this then?

**Pull request closed without merging**
