### PR TITLE
Update tutor.utf-8

### PR DESCRIPTION
**Pull request by HobDev**
i is used to enter text before cursor.

### CODE REVIEW

**Comment by brammool** [comment]
Strange that nobody mentioned this before.  It's indeed wrong.  I also updated the Dutch translation.

**Comment by micbou** [comment]
`AFTER` was correct. It's not about the position of the cursor but the position of the text that must be inserted:
 - `some_` (`_` represents a space) must be inserted between the second space and the `t` of `text` so the cursor must be placed on the `t`, not the space;
 - `si` must be inserted between the `s` and the `n` of `misng` so the cursor must be positioned on the `n`, not the `s`;
 - etc;

**Comment by brammool** [comment]
> `AFTER` was correct. It's not about the position of the cursor but the position of the text that must be inserted:
>  - `some_` (`_` represents a space) must be inserted between the second space and the `t` of `text` so the cursor must be placed on the `t`, not the space;
>  - `si` must be inserted between the `s` and the `n` of `misng` so the cursor must be positioned on the `n`, not the `s`;
>  - etc;

It said "AFTER where".  What does that even mean?  One has to imagine
the missing text to be able to be there to understand.  It's a lot
easier to understand to use BEFORE, since "i" inserts text before a
character.  Then we make it "character BEFORE which".  I think that's
easier to read.

-- 
SIGIRO -- irony detected (iron core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by micbou** [comment]
I don't know if it's easier to understand but it's definitely wrong. Consider the case where the text is supposed to be inserted at the start of the line. There is no such "first character BEFORE [the position] where the text is to be inserted".

**Comment by brammool** [comment]
> I don't know if it's easier to understand but it's definitely wrong.
> Consider the case where the text is supposed to be inserted at the
> start of the line. There is no such "first character BEFORE [the
> position] where the text is to be inserted".

It is now "character BEFORE which", and that also works for the start of
the line.

-- 
Communication is one of the most compli..., eh, well, it's hard.
You know what I mean.  Not?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
