### PR TITLE
apache: Add authorization containers

### PR DESCRIPTION
**Pull request by dreua**
As documented in: https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html
There are a few other new keywords on this page that I didn't include. I believe those three are (or will be) very commonly used.

### CODE REVIEW

**Comment by brammool** [comment]
David told he he is OK with this change, thus I'll include it.

**Comment by brammool** [comment]
David Auer wrote:

As documented in: https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html
There are a few other new keywords on this page that I didn&#39;t include. I believe those three are (or will be) very commonly used.
You can view, comment on, or merge this pull request online at:

  https://github.com/vim/vim/pull/10284

-- Commit Summary --

  * apache: Add authorization containers

-- File Changes --

    M runtime/syntax/apache.vim (3)

-- Patch Links --

https://github.com/vim/vim/pull/10284.patch
https://github.com/vim/vim/pull/10284.diff

-- 
"I simultaneously try to keep my head in the clouds and my feet on the
ground.  Sometimes it's a stretch, though."              -- Larry Wall

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dreua** [comment]
@brammool did you intend to add something to this issue or was this just an email-hiccup?

**Comment by brammool** [comment]
Some emails that were stuck somewhere apparently now show up.

**Pull request closed without merging**
