### PR TITLE
FIx a couple spelling errors

### PR DESCRIPTION
**Pull request by frewsxcv**
'suprise' -> 'surprise'

### CODE REVIEW

**Comment by chrisbra** [comment]
Note this is not yet the final repository and will be wiped.

**Comment by chrisbra** [comment]
For now, I'll submit your patch to the vim-dev ml

**Comment by brammool** [comment]
Included as patch 7.4.683

**Comment by frewsxcv** [comment]
:)

**Comment by netroby** [comment]
@brammool  why not using github PR system? this would be very well for developers who want to contribe via github

**Comment by mattn** [comment]
I'm not sure but vim-dev want to make history of changes as straight line, i guess. Maybe it is similar to https://github.com/golang/go is so.

**Pull request closed without merging**
