### PR TITLE
tex.vim: add align as a math environment

### PR DESCRIPTION
**Pull request by mtmkls**
The align environment from amsmath is highly recommended over eqnarray.

I tried to contact the maintainer of this file, but the given email address doesn't exist.

### CODE REVIEW

**Comment by k-takata** [comment]
Cc: @cecamp

**Comment by e-kwsm** [comment]
#3010

I think it is preferable to support environments of amsmath.

**Comment by k-takata** [comment]
Ah, I forgot that.
It might be better to include http://www.drchip.org/astronaut/vim/#LATEXPKGS, otherwise it should be documented somewhere.

**Comment by k-takata** [comment]
Oh, it is written in `:help tex-package`. Closing.

BTW,

> I tried to contact the maintainer of this file, but the given email address doesn't exist.

His new email address is written here:
https://github.com/vim/vim/blob/0d76683e094c6cac2e879601aff3acf1163cbe0b/runtime/doc/pi_netrw.txt#L6-L7

**Pull request closed without merging**
