### PR TITLE
runtime: Update Fotran files

### PR DESCRIPTION
**Pull request by Ajit-Thakkar**
Syntax file changes
1. Improvements in the handling of subroutine/function/module names, call statements, data statements, common blocks, procedure declarations, etc.
2. Begin adding a few features such as new intrinsic functions from the Fortran 2018 and Fortran 2023 ISO/IEC standards. Change highlighting for old features deleted or deemed obsolescent.
3. Complete the ongoing removal of support for obsolete dialects.
4. Simplify the option-controlling variables for the syntax file.
5. Update maintainer information. Add a 2nd maintainer to facilitate the eventual withdrawal of the older one.

Ftplugin and indent changes 
Update maintainer information. Add a 2nd maintainer to facilitate the eventual withdrawal of the older one.

### CODE REVIEW

**Comment by chrisbra** [comment]
can you please clarify those two points?

**Comment by Ajit-Thakkar** [comment]
> can you please clarify those two points?

Yes. @k-takata is quite right on both points.
This PR is a runtime update. 
Update Fortran files is a better title.

My apologies. This is only the 2nd time I've used github and I botched the manner in which I submitted the PR.

**Comment by chrisbra** [comment]
not following. I mean my comments regarding the use of the setting: `fortran_more_precise` and of the used `dialect`

**Comment by Ajit-Thakkar** [comment]
> not following. I mean my comments regarding the use of the setting: `fortran_more_precise` and of the used `dialect`

I am confused too. Could not find those comments BUT I guessed what you might have meant. 
So I corrected two small items in the syntax file that I had missed 
by removing a) the last occurrence of the variable fortran_more_precise, 
and 
b) a remaining comment about dialects.

**Comment by chrisbra** [comment]
and have you pushed again? Note to self: if we remove the `fortran_more_precise` variable, we need to remove it from the documentation as well at `:h ft-fortran-syntax`

**Comment by Ajit-Thakkar** [comment]
1) I thought I had pushed again.
2) I will update the help document
3) and make small changes in the ftplugin and indent files

So please hold off on this PR for a day or two.

What is the deadline for changes to make it to vim 9.1?

**Comment by chrisbra** [comment]
closing in favor of #13629

**Pull request closed without merging**
