### PR TITLE
Support offset in readblob()

### PR DESCRIPTION
**Pull request by k-takata**
Support specifying offset and size in `readblob()`.
This should be useful when someone wants to read only a part of a large file.

See: https://github.com/vim/vim/issues/11397#issuecomment-1283487837

### CODE REVIEW

**Comment by brammool** [comment]
```
+	if (size == 0)
+	    size = st.st_size - offset;
```
It's better not to change the arguments of a function, it makes debugging a bit harder.
"size" is size_t, which is unsigned.  If offset happens to be larger than st.st_size things go wrong.
It should probably return an empty result if offset is beyond the end of the file.

If offset is negative and -offset is larger than the file size, I wonder what happens.
The fseek() manual doesn't say.

**Comment by k-takata** [comment]
> It's better not to change the arguments of a function, it makes debugging a bit harder.

agree.

> If offset is negative and -offset is larger than the file size, I wonder what happens.
The fseek() manual doesn't say.

It says:

```
ERRORS
       EINVAL The whence argument to fseek() was not  SEEK_SET,  SEEK_END,  or
              SEEK_CUR.  Or: the resulting file offset would be negative.
```

So, that should be an error. However, it doesn't say about when offset goes beyond the end of the file.

**Comment by k-takata** [comment]
I'm thinking whether we should accept "0" as a normal value for "size".
File size can be 0, and `readblob()` returns `0z` for such files.
However, reading 0 bytes from a non-empty file seems not so useful...?

**Comment by brammool** [comment]
> I'm thinking whether we should accept "0" as a normal value for "size".
> File size can be 0, and `readblob()` returns `0z` for such files.
> However, reading 0 bytes from a non-empty file seems not so useful...?

It's always good that an optional argument has a value that means it
works like the argument wasn't there.  Zero seems like a good value for
that.  However, if the size results from some computation, and the
result of the computation ends up being zero, then it's unexpected to
get the whole file.  Perhaps using -1 for "as if the argument wasn't
there" is better?


-- 
   [The rest of the ARMY stand around looking at a loss.]
INSPECTOR END OF FILM: (picks up megaphone) All right!  Clear off!  Go on!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Okay, updated. Let's see if the CI passes.

**Comment by brammool** [comment]
I think it's better to only give an error message when the file can't be read.
When trying to read bytes that aren't there we can just have an empty result.
I'll make it work like that.

**Comment by 0cjs** [comment]
How long is this likely to take to appear in currently-used operating systems, such as Debian 11 and Ubuntu 22.04? If this isn't on a branch from which they're taking patches, is there a way to test if this second parameter is available?

**Comment by chrisbra** [comment]
For Debian and Ubuntu not at all, as long as they do not distribute new versions (or unless you add a new repository that provides updated vim builds). You may work around it by using the vim-appimage available e.g. here: https://github.com/vim/vim-appimage/

> is there a way to test if this second parameter is available?

    :echo has("patch-9.0.0795")

**Pull request closed without merging**
