### PR TITLE
TermDebug: explicit handling of termdebugger rr

### PR DESCRIPTION
**Pull request by GitMensch**
see discussion in #9379

### CODE REVIEW

**Comment by ii14** [comment]
In my opinion the command should be entirely customizable by providing an option to provide a custom function that returns a list, that can be passed directly to `term_start()`. This way if a new debugger with a gdb frontend comes along, no special handling will have to be added and users won't have to update vim just so they can use it.

My suggestion is for termdebug to check if `exists('*Termdebugger')`, and then call it with a dictionary, like `let gdb_cmd = Termdebugger({'tty': tty})`.

**Comment by brammool** [comment]
How about using a global variable g:termdebugcmdfilter that is a function reference to a function that gets the list that would be given to term_start, and allows for modifying that list and returning it.  The the "pty" argument can be used and changed, for example.

**Comment by ii14** [comment]
I believe function reference cannot be assigned to a lowercase global variable, can it?

**Comment by ii14** [comment]
One problem with this is going to be the check for `executable(gdbcmd[0])`, because it happens before we know what's the pty. I think this check will just have to be moved after creating the pty buffer.

Also I think it'd be a good idea to save the result from the function to a script local variable that can be later referenced in `s:CheckGdbRunning()` for example, just to make sure it's not called multiple times.

**Comment by brammool** [comment]
> I believe function reference cannot be assigned to a lowercase global
> variable, can it?

As mentioned in the other PR, if we put all the Termdebug configuration
items in a dictionary, then it becomes quite a bit simpler.


-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
It seems this is possible using the `g:termdebug_config['command']` varibale. See `:h g:termdebugger`. So I am closing this.

**Comment by GitMensch** [comment]
How to adjust the tty option position using the configuration of the command? This is what this PR was about...

**Comment by chrisbra** [comment]
Well, that was not clear from the PR description. It should be possible using `g:termdebug_config['command_add_args']`.

**Pull request closed without merging**
