### PR TITLE
feat: distinguish between hercules and gosum files, (only go.sum is gosum, rest hercules?)

### PR DESCRIPTION
**Pull request by amaanq**
I hope my vimscript code to distinguish between the two is ok, please double check that, thanks!!

Amaan

### CODE REVIEW

**Comment by brammool** [comment]
> I hope my vimscript code to distinguish between the two is ok, please
> double check that, thanks!!

It should work to match with "go.sum" first:

   au BufNewFile,BufRead go.sum				setf gosum
   au BufNewFile,BufRead *.vc,*.ev,*.sum,*.errsum	setf hercules


There are a few other places where "<afile>" is used that should not be
needed, we can look into them later.

-- 
Engineers will go without food and hygiene for days to solve a problem.
(Other times just because they forgot.)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by amaanq** [comment]
> 
> > I hope my vimscript code to distinguish between the two is ok, please
> > double check that, thanks!!
> 
> It should work to match with "go.sum" first:
> 
>    au BufNewFile,BufRead go.sum				setf gosum
>    au BufNewFile,BufRead *.vc,*.ev,*.sum,*.errsum	setf hercules
> 
> 
> There are a few other places where "<afile>" is used that should not be
> needed, we can look into them later.
> 
> -- 
> Engineers will go without food and hygiene for days to solve a problem.
> (Other times just because they forgot.)
> 				(Scott Adams - The Dilbert principle)
> 
>  /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
> ///                                                                      \\\
> \\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
>  \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
> 

What should be used instead of <afile>?

**Comment by brammool** [comment]
> > > I hope my vimscript code to distinguish between the two is ok, please
> > > double check that, thanks!!
> > 
> > It should work to match with "go.sum" first:
> > 
> >    au BufNewFile,BufRead go.sum				setf gosum
> >    au BufNewFile,BufRead *.vc,*.ev,*.sum,*.errsum	setf hercules
> > 
> > 
> > There are a few other places where "<afile>" is used that should not be
> > needed, we can look into them later.
> 
> What should be used instead of <afile>?

What I suggested, this just uses autocmd patterns.

You don't need to worry about other <afile> uses in this PR, it's just a
generic remark about simplifying this file.

-- 
Engineers are widely recognized as superior marriage material: intelligent,
dependable, employed, honest, and handy around the house.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by amaanq** [comment]
> What I suggested, this just uses autocmd patterns.

Oops, sorry I responded earlier on mobile and the formatting was way off..

Fixed now!

**Pull request closed without merging**
