### PR TITLE
Github CI fails, because the SND Module is not available

### PR DESCRIPTION
**Pull request by chrisbra**
Disable it for now, so that tests can run

### CODE REVIEW

**Comment by pheiduck** [comment]
I am a bit confused why my if condition is no working.
Because it should let the CI run also when the Package is not available. 🤔

**Comment by chrisbra** [comment]
> Because it should let the CI run also when the Package is not available. 

Yeah, I think the `apt-cache` commands still succeeds (maybe because the package is still referenced), but the actual install commands fails instead.

**Comment by chrisbra** [comment]
I think this commit properly checks the result: d47431954aaa5b2d9c8c2fc9504ad918fa47bfc6

**Comment by chrisbra** [comment]
let me squash and re-submit

**Comment by chrisbra** [comment]
closing in favor of #12801

**Pull request closed without merging**
