### PR TITLE
Problem: Hollywood 9 syntax highlighting not supported.

### PR DESCRIPTION
**Pull request by sodero**
Solution: Update the existing Hollywood Vim syntax file.

### CODE REVIEW

**Comment by brammool** [comment]
Standard answer: Have you contacted the maintainer?

**Comment by sodero** [comment]
Yes (strictly speaking it was the other way around, he contacted me so that I could integrate this).

**Comment by brammool** [comment]
> Yes (strictly speaking it was the other way around, he contacted me so
> that I could integrate this).

So are you the maintainer now?

-- 
hundred-and-one symptoms of being an internet addict:
110. You actually volunteer to become your employer's webmaster.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by sodero** [comment]
No, I was just asked by the maintainer to upstream the latest version since I'm currently  doing most of the Amiga specific work, see MUI-Vim.

**Comment by brammool** [comment]
OK, so I'll just include this without adjusting the maintainer.

**Pull request closed without merging**
