### PR TITLE
runtime(doc): fix grammar in termdebug doc, remove trailing spaces

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Comment by chrisbra** [comment]
damn, I was trying to carefully write proper English :(

**Comment by chrisbra** [comment]
thanks, I include it

**Comment by Shane-XB-Qian** [comment]
> damn, I was trying to carefully write proper English :( 

TBH i didnot feel yours vs his that modification had much difference, or even mine,
all meant if a buf local mapping was existed already,
damn, so horrible to write 'proper English', ahaha~

-- 
shane.xb.qian

**Comment by wilhelmtell** [comment]
The original was fine English, there were no grammar errors. I agree though that all things being equal in writing like in programming less is more. One word shorter? Sure I'll take that.

**Comment by zeertzjq** [comment]
Ah yes, actually it was fine, but the `map-local` tag should be `:map-local`.

**Pull request merged**
