### PR TITLE
Preventing nested for-one-command

### PR DESCRIPTION
**Pull request by pierreganty**
Discussion at #12115

### CODE REVIEW

**Comment by chrisbra** [comment]
can you please add the following test:
```patch
diff --git a/src/testdir/test_selectmode.vim b/src/testdir/test_selectmode.vim
index 6e2c36927..bf1b52b32 100644
--- a/src/testdir/test_selectmode.vim
+++ b/src/testdir/test_selectmode.vim
@@ -310,4 +310,15 @@ func Test_selectmode_register()
   bw!
 endfunc

+func Test_ins_ctrl_o_in_insert_mode_resets_selectmode()
+  new
+  " ctrl-o in insert mode resets restart_VIsual_select
+  call setline(1, 'abcdef')
+  call cursor(1, 1)
+  exe "norm! \<c-v>\<c-g>\<c-o>c\<c-o>\<c-v>\<right>\<right>IABC"
+  call assert_equal('ABCbcdef', getline(1))
+
+  bwipe!
+endfunc
+
 " vim: shiftwidth=2 sts=2 expandtab
```
I tried to push to your fork, but wasn't possible :( 

Nevertheless, I am not sure if this is okay to include. 

Opinions?

**Comment by pierreganty** [comment]
The test works fine by me. Behaves differently with or without the patch.

**Comment by pierreganty** [comment]
I have little experience with git. Please let me know what is the preferred path out of this mess I created.

**Comment by chrisbra** [comment]
let me include this. I am thinking nobody won't notice this change anyhow 🤷

**Pull request closed without merging**
