### PR TITLE
Fix #874 noinsert breaks redo register problem

### LINKED ISSUE #874: completeopt noinsert breaks redo register
Reproduce ways
1. `vim -Nu test.vim`
2. Press `i<F5>soun<CR><CR><ESC>.`

```
" test.vim
set completeopt+=noinsert

inoremap <F5>  <C-R>=Test()<CR>

function! Test() abort
  call complete(1, ['source', 'soundfold'])
  return ''
endfunction
```

Expected result:

```
soundfold
soundfold

```

Current result:

```
soundfold
source

```

I have reproduced it in Vim 7.4.1943.

### PR DESCRIPTION
**Pull request by Shougo**
It fixes #874 problem

### CODE REVIEW

**Comment by vim-ml** [comment]
Hi,

2016-7-5(Tue) 21:52:46 UTC+9 Shougo:

> It fixes #874 problem
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/905
> 
> Commit Summary
> 
>   Fix #874 noinsert breaks redo register problem
> 
> File Changes
> 
> ```
> M
> src/edit.c
> (1)
> ```
> 
> Patch Links:
> 
>   https://github.com/vim/vim/pull/905.patch
>   https://github.com/vim/vim/pull/905.diff

Why you do not write a test?
You will surely write?

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by brammool** [comment]
Shougo wrote:

> It fixes #874 problem

We also have #875 that is supposed to fix this.  What is the best
solution?

## 

hundred-and-one symptoms of being an internet addict:
208. Your goals for the future are obtaining an T1 connection and
     a 130 gig hard drive.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Am 2016-07-05 23:18, schrieb Bram Moolenaar:

> Shougo wrote:
> 
> > It fixes #874 problem
> 
> We also have #875 that is supposed to fix this. What is the best
> solution?

According to PR #875, this does not fix issue #874 but a different 
problem
(that no entry is inserted on pressing enter)

Best,
Christian

**Comment by brammool** [comment]
Duplicate

**Comment by Shougo** [comment]
Thanks.

**Pull request closed without merging**
