### PR TITLE
Add commentstring to matlab.vim

### PR DESCRIPTION
**Pull request by tdehaeze**

### CODE REVIEW

**Comment by chrisbra** [comment]
have you contacted the maintainer of the file?

**Comment by tdehaeze** [comment]
I just did. I'm waiting for an answer.

**Comment by tdehaeze** [comment]
Still no news.

**Comment by brammool** [comment]
I'll include it now.

**Comment by MrScriptMaster** [comment]
Ваш отчет успешно принят и ожидает проверки.

**Pull request closed without merging**
