### PR TITLE
Fix vim/vim#14437 and some other problems in diff mode.

### PR DESCRIPTION
**Pull request by ynkdir**
In diff mode Vim merges overlapped diff blocks.  But it doesn't work expectedly in some situation.

Here is diagram of added test.

https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=vim_diff_read.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1t9z_dy3Q3zZBHx5wG_mtEekAnI89ANfn%26export%3Ddownload

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. Can you give an example what vimdiff currently does and how it should look like?

**Comment by ynkdir** [comment]
For example.

```
$ cat a.txt
a
b
c
$ cat b.txt
a
x
c
$ cat c.txt
y
b
c
$ vim --clean -d a.txt b.txt c.txt
```

result

result

expected

expected

**Comment by chrisbra** [comment]
okay thanks. That is clearly wrong

**Comment by ynkdir** [comment]
Thank you.

**Pull request closed without merging**
