### PR TITLE
CI: if condition is always true

### PR DESCRIPTION
**Pull request by pheiduck**
rework for: https://github.com/vim/vim/pull/12390
Tested if statement locally and worked as expected.

### CODE REVIEW

**Comment by chrisbra** [comment]
can we do it like this perhaps?

```patch
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 40932b7f4..ba62744bf 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -180,13 +180,14 @@ jobs:
           DEST_DIR: ${{ env.TMPDIR }}/linux-modules-extra-${{ env.LINUX_VERSION }}
         run: |
           cd /lib/modules/${{ env.LINUX_VERSION }}
-          if apt-cache show linux-modules-extra-${{ env.LINUX_VERSION }} >/dev/null 2>&1 ; then
-          echo "Module " linux-modules-extra-${{ env.LINUX_VERSION }} "doesn't seem to exist, continue anyway"; exit 0
+          module=linux-modules-extra-${{ env.LINUX_VERSION }}
+          if ! apt-cache show $module  >/dev/null 2>&1 ; then
+          echo "Module $module doesn't seem to exist, continue anyway"
           else
-          sudo apt-get install -d -y linux-modules-extra-${{ env.LINUX_VERSION }}
-          sudo dpkg -x /var/cache/apt/archives/linux-modules-extra-${{ env.LINUX_VERSION }}*.deb "${DEST_DIR}"
-          tar -cvC "${DEST_DIR}"/lib/modules/${{ env.LINUX_VERSION }} kernel/sound | sudo tar -x
-          sudo depmod --verbose
+          sudo apt-get install -d -y $module &&
+          sudo dpkg -x /var/cache/apt/archives/${module}*.deb "${DEST_DIR}" &&
+          tar -cvC "${DEST_DIR}"/lib/modules/${{ env.LINUX_VERSION }} kernel/sound | sudo tar -x &&
+          sudo depmod --verbose &&
           sudo modprobe --verbose snd-dummy
           fi
```

**Comment by pheiduck** [comment]
@chrisbra sure, lets try it out.

**Comment by pheiduck** [comment]
okay @brammool was to fast merging it.
But I guess its fine as I have done it.
As it was working as expected on my tests.

**Comment by chrisbra** [comment]
yeah, Bram was too fast 🙈 okay fine

**Comment by brammool** [comment]
> okay @brammool was to fast merging it.

Glad to be of service :-).

> But I guess its fine as I have done it.
> As it was working as expected on my tests.

I checked a few CI actions and it looked OK (before it would give the
error message, after installing modules).

If there is yet another way this can fail, it's always possible to make
yet another PR.

-- 
hundred-and-one symptoms of being an internet addict:
29. Your phone bill comes to your doorstep in a box.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I think it is fine for now. Thanks Bram!

**Pull request closed without merging**
