### PR TITLE
LSP messages are not parsed properly if the http header and json payload are received separately

### PR DESCRIPTION
**Pull request by yegappan**
Collapse all the received data before parsing the LSP messages.

### CODE REVIEW

**Comment by chrisbra** [comment]
Hi Yegappan, could that also fix the issue from the vim-win32-installer repository?

**Comment by vim-ml** [comment]
Hi Christian,

On Sun, Apr 17, 2022 at 1:15 PM Christian Brabandt <
***@***.***> wrote:

> Hi Yegappan, could that also fix the issue from the vim-win32-installer
> repository?
>
>
> Is it possible to do one vim-win32-installer test run with the LSP test
enabled again ?

Thanks,
Yegappan

**Comment by vim-ml** [comment]
On So, 17 Apr 2022, Yegappan Lakshmanan wrote:

> Hi Christian,
> 
> On Sun, Apr 17, 2022 at 1:15 PM Christian Brabandt ***@***.***> wrote:
> 
> 
>     Hi Yegappan, could that also fix the issue from the vim-win32-installer repository?
> 
> 
> 
> Is it possible to do one vim-win32-installer test run with the LSP test enabled again ?

Yes of course. Once this is merged, I can enable the test again.

Best,
Christian
-- 
Ein Mensch in einer fremden Stadt fragt:
  "Wissen Sie, wo es zum Bahnhof geht?"
Bioenergetiker: "Machen Sie mal sch... sch... sch... !"

**Comment by vim-ml** [comment]
Hi Christian,

On Sun, Apr 17, 2022 at 1:24 PM Christian Brabandt ***@***.***> wrote:
>
>
> On So, 17 Apr 2022, Yegappan Lakshmanan wrote:
>
> > Hi Christian,
> >
> > On Sun, Apr 17, 2022 at 1:15 PM Christian Brabandt ***@***.***> wrote:
> >
> >
> >     Hi Yegappan, could that also fix the issue from the vim-win32-installer repository?
> >
> >
> >
> > Is it possible to do one vim-win32-installer test run with the LSP test enabled again ?
>
> Yes of course. Once this is merged, I can enable the test again.
>

It looks like the LSP tests are now passing in the vim-win32-installer
CI but failing somewhere else?

Regards,
Yegappan

**Comment by vim-ml** [comment]
Christian wrote:

> > It looks like the LSP tests are now passing in the vim-win32-installer
> > CI but failing somewhere else?
> 
> Yes, it seems test_alot.vim now times out. I have no idea how to debug 
> this .(

If needed we can split off things from test_alot.vim and run them
separately.  It's a bit more efficient to run multiple tests without
starting a new Vim instance, but if it makes debugging harder that's
more important to fix than efficiency.

-- 
Q. What happens to programmers when they die?
A: MS-Windows programmers are reinstalled.  C++ programmers become undefined,
   anyone who refers to them will die as well. Java programmers reincarnate
   after being garbage collected, unless they are in permgen, in which case
   they become zombies.  Zimbu programmers leave a stack trace that tells us
   exactly where they died and how they got there.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
Now, It finally worked. I'll keep an eye on that to see if this happens more often.

**Comment by vim-ml** [comment]
Am 2022-04-21 17:46, schrieb Yegappan Lakshmanan:
> Hi Christian,
> 
> On Sun, Apr 17, 2022 at 1:24 PM Christian Brabandt ***@***.***> 
> wrote:
>> 
>> 
>> On So, 17 Apr 2022, Yegappan Lakshmanan wrote:
>> 
>> > Hi Christian,
>> >
>> > On Sun, Apr 17, 2022 at 1:15 PM Christian Brabandt ***@***.***> wrote:
>> >
>> >
>> >     Hi Yegappan, could that also fix the issue from the vim-win32-installer repository?
>> >
>> >
>> >
>> > Is it possible to do one vim-win32-installer test run with the LSP test enabled again ?
>> 
>> Yes of course. Once this is merged, I can enable the test again.
>> 
> 
> It looks like the LSP tests are now passing in the vim-win32-installer
> CI but failing somewhere else?

Yes, it seems test_alot.vim now times out. I have no idea how to debug 
this .(

**Pull request closed without merging**
