### PR TITLE
Filenames with whitespaces AND ':Termdebug args' issues fix. 

### PR DESCRIPTION
**Pull request by ubaldot**
1. Filenames with whitespaces issue should be fixed now  #12357 
2. ":Termdebug args" should work now #15254

### CODE REVIEW

**Comment by ubaldot** [comment]
I also remove the reset of few variables at shutoff as it is no longer needed given that we have an Init function.

**Comment by chrisbra** [comment]
thanks!

**Comment by ubaldot** [comment]
@chrisbra the changes `var AT = empty(at) ? $"\"{expand('%:p')}:{line('.')}\"" : at` **shall be reverted**! 

I am experiencing issues  with gdb saying `no source file named C` when I try to set a breakpoint. I cannot root-cause the problem, but by restoring `var AT = empty(at) ? $"{fnameescape(expand('%:p'))}:{line('.')}" : at` things work well again.

**Comment by errael** [comment]
> @chrisbra the changes `var AT = empty(at) ? $"\"{expand('%:p')}:{line('.')}\"" : at` **shall be reverted**!
> 
> I am experiencing issues with gdb saying `no source file named C` when I try to set a breakpoint. I cannot root-cause the problem, but by restoring `var AT = empty(at) ? $"{fnameescape(expand('%:p'))}:{line('.')}" : at` things work well again.

What does the string with/without PR changes look like?

**Comment by ubaldot** [comment]
> What does the string with/without PR changes look like?

Before PR: `C:\Users\yt75534\Documents\defrecs\stm32f4x\ADC_Readings\application\temperature_sensor\tempsens_LM335.c:60`
After PR: `"C:\Users\yt75534\Documents\defrecs\stm32f4x\ADC_Readings\application\temperature_sensor\tempsens_LM335.c:60"`

It is only the double quote that differs. But for some reason, in my case the double quotes make troubles,. However, I am using a special gdb (arm-eabi-none-gdb).

**Comment by errael** [comment]
> It is only the double quote that differs. But for some reason, in my case the double quotes make troubles,. However, I am using a special gdb (arm-eabi-none-gdb on Windows 10).

I just tried this using current build plus #15226. 
```
588.519723005 : ch_log(): sending to gdb: -break-insert "/src/tools/vim/src/evalfunc.c:7543"
```

Things work OK. I'm on linux. If things work OK on  windows with regular gdb then I'd be inclined to keep the current behavior and add an option for "don't quote mi command options" or whatever.

Caveat, I didn't try anything with blanks in the file name.

**Comment by ubaldot** [comment]
> Things work OK. I'm on linux. If things work OK on windows with regular gdb then I'd be inclined to keep the current behavior and add an option for "don't quote mi command options" or whatever.

I agree. I may add an "if" condition to check if users is running the regular gdb or another version. 

> Caveat, I didn't try anything with blanks in the file name.

The best would be to add a test with filenames with spaces and without. At that point we leave the github workflow to run the tests for us. I should have some time for doing it today.

**Comment by ubaldot** [comment]
Update: tested regular gdb on Windows and WSL2 (Ubuntu) with both files with empty spaces and without empty spaces. They all work well. Hence, the problem relies on arm-eabi-none-gdb, but then the same symptom may appear on other gdb:s. 

I could add something like the following:

```
var weird_gdbs = ['arm-eabi-none-gdb', 'my-gdb', 'another-weird-gdb' ]

var AT =""
if index(weird_gdbs, GetCommand()[0]) != -1  
  AT = empty(at) ? $"{fnameescape(expand('%:p'))}:{line('.')}" : at
else 
   AT = empty(at) ? $"\"{expand('%:p')}:{line('.')}\"" : at
endif
```

and populate the list `weird_gdbs` as long as users ask for support for a specific gdb? 

What do you think?

**Comment by errael** [comment]
In the spec for [mi3](https://sourceware.org/gdb/current/onlinedocs/gdb.html/GDB_002fMI-Input-Syntax.html#GDB_003fMI-Input-Syntax) there's
```
parameter →
    non-blank-sequence | c-string

non-blank-sequence →
    anything, provided it doesn’t contain special characters
    such as "-", nl, """ and of course " "

c-string →
    """ seven-bit-iso-c-string-content """
```

Handling this problem in terms of gdb/mi compliance seems easier to maintain
and document; having a configurable like `gdb_mi_parameter_can_not_quote` or
`gdb_mi_broken_c_string` or something. In any event, it seems like its time
for a function that sits near `SendCommand`, something like
`CreateMiParameter` or `CreateParameter` instead of putting work-around code
all over the place.

I've wondered about have more inteligence in `SendCommand()` to automatically
format gdb/mi messages. But that seems like a lot of work; and since
`termdebug` has been around for a while, probably not worth it. (at least not
at this time)

**Comment by errael** [comment]
(I lost something from the previous post)

> populate the list non_standard_gdbs as long as users ask for support for a specific gdb?

It seems like using `GetCommand()[0]` is a problem. Couldn't some weird command
have different versions, some of which handle quotes?
(followed by discussion of phrasing this issue in terms of gdb/mi compliance
rather than specific/innumerable gdb versions)

**Comment by LemonBoy** [comment]
> What do you think?

Christ.

The problem is solved (with `arm-none-eabi-gdb` on Windows 11) by escaping all the backslashes, if you look at the path you're passing you'll notice a number of backslash + letter combinations that are valid escape sequences. Please add a helper function (`QuoteArg`) to 1) add quotes if not present 2) escape the quotes and backslashes present in the string, do not repeat the logic everywhere.

You probably want to apply this when sending the `file <arg>` command to gdb.

One more issue, if you specify an absolute path for `gdb_cmd` the `$"You have a file/folder named '{gdb_cmd}' in the current directory Termdebug may not work properly. Please exit and rename such a file/folder."` error is raised. The check should be refined to actually check the file exists in the CWD.

**Comment by ubaldot** [comment]
> In the spec for [mi3](https://sourceware.org/gdb/current/onlinedocs/gdb.html/GDB_002fMI-Input-Syntax.html#GDB_003fMI-Input-Syntax) there's
> 
> ```
> parameter →
>     non-blank-sequence | c-string
> 
> non-blank-sequence →
>     anything, provided it doesn’t contain special characters
>     such as "-", nl, """ and of course " "
> 
> c-string →
>     """ seven-bit-iso-c-string-content """
> ```
> 
> Handling this problem in terms of gdb/mi compliance seems easier to maintain and document; having a configurable like `gdb_mi_parameter_can_not_quote` or `gdb_mi_broken_c_string` or something. In any event, it seems like its time for a function that sits near `SendCommand`, something like `CreateMiParameter` or `CreateParameter` instead of putting work-around code all over the place.
> 

In-fact, I admit that what I proposed is utterly bad! 
FYI: there is also a mi4 (not documented). The problem in upgrading mi interface also require the user to upgrade gdb. But yes, I wonder how many are still stuck to very old gdb versions... 

> I've wondered about have more inteligence in `SendCommand()` to automatically format gdb/mi messages. But that seems like a lot of work; and since `termdebug` has been around for a while, probably not worth it. (at least not at this time)

Agree. Also, take a look here #10300

**Comment by ubaldot** [comment]
> One more issue, if you specify an absolute path for `gdb_cmd` the `$"You have a file/folder named '{gdb_cmd}' in the current directory Termdebug may not work properly. Please exit and rename such a file/folder."` error is raised. The check should be refined to actually check the file exists in the CWD.

Ops! Sorry! -> https://github.com/vim/vim/pull/15268

**Comment by ubaldot** [comment]
> The problem is solved (with `arm-none-eabi-gdb` on Windows 11) by escaping all the backslashes, if you look at the path you're passing you'll notice a number of backslash + letter combinations that are valid escape sequences. Please add a helper function (`QuoteArg`) to 1) add quotes if not present 2) escape the quotes and backslashes present in the string, do not repeat the logic everywhere.
> 

Do you mean something like this: https://github.com/vim/vim/pull/15270 ?

**Pull request closed without merging**
