### PR TITLE
Add support for menus in Terminal mode using :rmenu and variants

### PR DESCRIPTION
**Pull request by ychin**
This adds support for adding menus while in Terminal-Job mode.  Unfortunately `:tmenu` is already taken for adding tooltips to menus, so we cannot have a nice symmetry with `:tmap`.  I chose to use `:rmenu`/`:rnoremenu`/`:runmenu` instead as a compromise, but I couldn't really find a good memorable letter for "terminal".

I also decided to make `:amenu` not support terminal mode. Technically you could inject a `<C-\>n` sequence first to put it into Terminal-Normal mode, but I think with the many quirks of how terminal mode works (e.g. going into insert mode by pressing 'i' means something very different), it's likely to introduce bugs and issues. The user can still manually map it using `:rmenu`.

### CODE REVIEW

**Comment by brammool** [comment]
Yee Cheng Chin wrote:

> This adds support for adding menus while in Terminal-Job mode.
> Unfortunately `:tmenu` is already taken for adding tooltips to menus,
> so we cannot have a nice symmetry with `:tmap`.  I chose to use
> `:rmenu`/`:rnoremenu`/`:runmenu` instead as a compromise, but I
> couldn't really find a good memorable letter for "terminal".

Thanks for working on this.

I find ":rmenu" too cryptic.  How about using ":tlmenu", as for
"TerminaL"?  Using two letters instead of one sounds better to me than
dropping the "t".

> I also decided to make `:amenu` not support terminal mode. Technically
> you could inject a `<C-\>n` sequence first to put it into
> Terminal-Normal mode, but I think with the many quirks of how terminal
> mode works (e.g. going into insert mode by pressing 'i' means
> something very different), it's likely to introduce bugs and issues.
> The user can still manually map it using `:rmenu`.

That makes sense.  Also because we probably have existing :amenu
entries that just won't work.

-- 
hundred-and-one symptoms of being an internet addict:
75. You start wondering whether you could actually upgrade your brain
    with a Pentium Pro microprocessor 80.  The upgrade works just fine.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
> I find ":rmenu" too cryptic.  How about using ":tlmenu", as for "TerminaL"?  Using two letters instead of one sounds better to me than dropping the "t".

":tlmenu" does sound more intuitive and easier to remember. One issue is that menus have a "mode char" described in `menu_mode_chars`, where it's defined to have only one character. We could probably extend that to work with more than one chars too, but among the things that would mean is that it will make the formatting for `showing-menus` slightly off with the two character column, and making sure the "MenuPopup" autocmd works with it. I'll work on that.

**Comment by ychin** [comment]
Committed the code to do `tlmenu` instead of `rmenu`. Also left a command at ex_cmds.h to remind people to run `make cmdidxs` when adding Ex commands since otherwise there's no clear way to find out.

**Comment by ychin** [comment]
Hi, I believe I have fixed up everything so it passes all the tests, and the command is now `tlmenu` instead of `rmenu`. Let me know if I need to fix anything else.

**Pull request closed without merging**
