### PR TITLE
Implement a cross-platform way to get the OS cache dir

### PR DESCRIPTION
**Pull request by LemonBoy**
Borrow the name from NeoVim's stdpath() but handle only a single case,
"cache". If needed this function can be easily expanded to handle more
cases and, if the XDG specification is ever adopted, to return some
sensible values for other kind of data beside cached files.

### CODE REVIEW

**Comment by brammool** [comment]
So the XDG standard specifies this as " user-specific non-essential (cached) data ".  What does that mean?
No idea what to use it for.  Does "non-essential" mean it can disappear any moment?
Does "user-specific" mean other users cannot access it?  Or can they?

**Comment by LemonBoy** [comment]
> Does "non-essential" mean it can disappear any moment? 

It only means the data is not essential for the program to work, if the cache is purged the application will populate it again.

> Does "user-specific" mean other users cannot access it? Or can they?

"user-specific" opposed to "system-wide". Think of it as a local, per-user, `/var/cache`.
The specification doesn't say anything about permissions.

**Comment by brammool** [comment]
This sounds rather unreliable.  I can see that my ~/.cache directory isn't cleared on reboot, thus files are catching dust there, nobody ever cleans it up. And if someone has a script running to avoid that, it means files can disappear "under your fingers".
And different systems may have different behavior, since the standard doesn't say anything.
Oh, and it looks like my cache directory is readable by the group but not other users.  Thus it can't be used to share files with other users.
This appears to need a "use at your own risk" warning.

**Comment by LemonBoy** [comment]
> Oh, and it looks like my cache directory is readable by the group but not other users. Thus it can't be used to share files with other users.

That's where the _user-specific_ part comes into play.

> This appears to need a "use at your own risk" warning.

It doesn't seem to me that the current documentation is promising more than it is delivering, `stdpath` is all about giving the user a sensible default to avoid getting lost in a maze of `if has` (and having to handle all the different cases) or hardcoding some paths that may or may not make too much sense.

**Comment by brammool** [comment]
> > Oh, and it looks like my cache directory is readable by the group
> > but not other users. Thus it can't be used to share files with other
> > users.
> 
> That's where the _user-specific_ part comes into play.
> 
> > This appears to need a "use at your own risk" warning.
> 
> It doesn't seem to me that the current documentation is promising more
> than it is delivering, `stdpath` is all about giving the user a
> sensible default to avoid getting lost in a maze of `if has` (and
> having to handle all the different cases) or hardcoding some paths
> that may or may not make too much sense.

My point is that without specifying the properties of the directory, one
cannot be sure how it can be used.  It should state some things like:
- Only accessible by the current user.
- Will survive a system reboot.
- Files are removed only when intentionally cleaning up, no expiry date.

Other problems are name clashes, how does one make sure that the files
created there are not colliding with other applications?

Is there anything said about the size of the files that can be stored?
How does one prevent the files stored there continuously growing (I
actually had to manually inspect ~/.cache and remove stuff from an app I
used only once almost a year ago).

All these questions make such a path totally useless.

-- 
Engineers understand that their appearance only bothers other people and
therefore it is not worth optimizing.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am a bit confused. What do we need the cache directory for? Can you please clarify, what Vim would use the cache dir for? Swapfiles? Undofiles? vimrc?  Others?

**Comment by LemonBoy** [comment]
> I am a bit confused. What do we need the cache directory for? Can you please clarify, what Vim would use the cache dir for? Swapfiles? Undofiles? vimrc? Others?

Often plugins need a safe place to store their cached data (eg. think of some language servers, plugins downloading data from internet, plugins preprocessing a lot of data in a more manageable format) or, as you mentioned, users (like me) may find this useful to choose where to store the swapfiles/undofiles.

> My point is that without specifying the properties of the directory, one
> cannot be sure how it can be used.  It should state some things like:
> - Only accessible by the current user.
> - Will survive a system reboot.
> - Files are removed only when intentionally cleaning up, no expiry date.

None of this can be enforced at any level, if the user sets up this folder on a ramdisk or has a script to periodically remove the content we can't do much. Given the implementation of `stdpath` we can pull this argument inside-out: we're using the path that, according to the OS/DE, applications are supposed to use for this kind of data. The burden of respecting this contract is definitely not on Vim.

> Other problems are name clashes, how does one make sure that the files
created there are not colliding with other applications?

You can't, the same way you can't provide any guarantee about the unicity of temporary files. We could append a `/vim` at the end so that the base path becomes something like `~/.cache/vim/` and introduce this "namespace".

> Is there anything said about the size of the files that can be stored?
How does one prevent the files stored there continuously growing (I
actually had to manually inspect ~/.cache and remove stuff from an app I
used only once almost a year ago).

This is definitely off-topic and a rant about the general state of the OS mechanism to store cached/temporary data.

**Comment by brammool** [comment]
> > I am a bit confused. What do we need the cache directory for? Can
> > you please clarify, what Vim would use the cache dir for? Swapfiles?
> > Undofiles? vimrc? Others?
> 
> Often plugins need a safe place to store their cached data (eg. think
> of some language servers, plugins downloading data from internet,
> plugins preprocessing a lot of data in a more manageable format) or,
> as you mentioned, users (like me) may find this useful to choose where
> to store the swapfiles/undofiles.

Right, this makes clear that you misinderstand the intention of the
cache directory.  Files there could be deleted any moment, thus you
should not store an undo file there.  A swapfile gone missing will also
cause trouble, you can't always re-create it.

This is exactly the problem with offering a path without specifying
exactly how it can be used.

> > My point is that without specifying the properties of the directory, one
> > cannot be sure how it can be used.  It should state some things like:
> > - Only accessible by the current user.
> > - Will survive a system reboot.
> > - Files are removed only when intentionally cleaning up, no expiry date.
> 
> None of this can be enforced at any level, if the user sets up this
> folder on a ramdisk or has a script to periodically remove the content
> we can't do much. Given the implementation of `stdpath` we can pull
> this argument inside-out: we're using the path that, according to the
> OS/DE, applications are supposed to use for this kind of data. The
> burden of respecting this contract is definitely not on Vim.

In this case, there does not appear to be any contract.

If we would say that for Unix it's the ~/.cache directory, then at least
the user has some clue what it means (only readable by the user and the
group, will survive a system crash, won't be cleared automatically
unless you have setup something for that).

If the directory comes from $XDG_CACHE_HOME I have no clue.  Will it be
cleared on system restart or not?  Can the group access it?  It does
state it's for private use, but does that guarantee other users can't
access it?

> > Other problems are name clashes, how does one make sure that the files
> > created there are not colliding with other applications?
> 
> You can't, the same way you can't provide any guarantee about the
> unicity of temporary files. We could append a `/vim` at the end so
> that the base path becomes something like `~/.cache/vim/` and
> introduce this "namespace".

Vim provides the tempname() exactly for that reason.  These are
guaranteed to be unique and private.

> > Is there anything said about the size of the files that can be stored?
> > How does one prevent the files stored there continuously growing (I
> > actually had to manually inspect ~/.cache and remove stuff from an app I
> > used only once almost a year ago).
> 
> This is definitely off-topic and a rant about the general state of the
> OS mechanism to store cached/temporary data.

It is totally on topic: if we provide a directory to store files, then
we must also specify how to get rid of them.  I don't know how many
people have complained about swap files laying around.

-- 
If they don't keep on exercising their lips, he thought, their brains
start working.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
