### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by benknoble** [comment]
Drive-by comment: the diff on the shell scripts would more accurately highlight the true issues if it left the indentation alone and focused on the quotes and expansion issues.

**Comment by a1346054** [comment]
Hmm that's just my editor warning about mixed indentation, so I dealt with that too to silence that warning.

**Comment by benknoble** [comment]
Then I would recommend folding that in with a separate fix-whitespace commit. Have one commit "fix shellcheck warnings" about variable quotes, `$()`, etc., and another that does all the indentation/whitespace stuff. Much easier to follow

**Comment by brammool** [comment]
Thanks.  I'll include most of it.  Changing backticks to $() might not work with older shells, I'm not sure, thus I'll leave that out.

**Pull request closed without merging**
