### PR TITLE
Fix spelling, change indentation for 'if...then' and 'for...loop'.

### PR DESCRIPTION
**Pull request by StephenWall**
Change indention rule for 'if' statements and loops to format them like this:

    IF some condition
    THEN
        -- Do some cool statements
        INSERT blah blah blah;
    END IF;

### CODE REVIEW

**Comment by chrisbra** [comment]
have you contacted the files maintainer (mentioned at the top of the file)?

**Comment by StephenWall** [comment]
I will do so.

**Comment by StephenWall** [comment]
No response yet from the author.

**Comment by brammool** [comment]
Let me include this now.  Would be nice if you could write a few test cases.

**Pull request closed without merging**
