### PR TITLE
Added am.po

### PR DESCRIPTION
**Pull request by gagikh**
Created po file for Armenian lang tranlation

### CODE REVIEW

**Comment by RestorerZ** [comment]
@gagikh ,
And, yes, it can add you as a maintainer to the file https://github.com/vim/vim/blob/master /.github/MAINTAINERS

**Comment by gagikh** [comment]
> Thanks. Did you run it through [check.vim](https://github.com/vim/vim/blob/master/src/po/check.vim)?

Yes, checked but makefile is not pushed, will push soon

**Comment by RestorerZ** [comment]
@gagikh ,
Please compare your translation and the POT file for the current state of the Vim codebase.
[vim.pot.zip](https://github.com/user-attachments/files/17119708/vim.pot.zip)

**Comment by gagikh** [comment]
> @gagikh , Please compare your translation and the POT file for the current state of the Vim codebase. [vim.pot.zip](https://github.com/user-attachments/files/17119708/vim.pot.zip)

Thanks @RestorerZ for the info and file, merged with POT.

**Comment by RestorerZ** [comment]
@gagikh ,
This is a really big breakthrough compared to what it was. But why did you stop in the middle? Or it should be continued...
Я не так, чтоб  очень хорошо ззнал армянский, но, учитыавая, что большую часть мы, так или иниче, по историческим и религиозным причнанам бок о бок порожили с арманами и грузинамими вместе, кое что я понимаю. Тем более, что считаю что Армения это культруная "колыбель" Заковказкой культуры, уж чем там вам грузины обязаны я промолчу. И это одна из причин спроисть Вас почему Вы указыаете язык свойей культуры не как "hy", а как "arm". Вы так стесняетесь названия своего языка7
Я же Вам дал чёткие ссылки на требования к указанию кодов языка.

You have also been given clear references to the requirements of knowledge of the language code
https://www.gnu.org/software/gettext/manual/html_node/Language-Codes.html

But instead of the required set number 1, you used set number 2, and even with the letter "B", which generally implies a bibliographic extension.

> B and T codes
> While most languages are given one code by the standard, twenty of the languages described have two three-letter codes, a "bibliographic" code (ISO 639-2/B), which is derived from the English name for the language and was a necessary [legacy](https://en.wikipedia.org/wiki/Legacy_systems) feature, and a "terminological" code (ISO 639-2/T), which is derived from the native name for the language and resembles the language's two-letter code in ISO 639-1. There were originally 22 B codes; scc and scr are now deprecated.
> 
> In general the T codes are favored; [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) uses ISO 639-2/T.

just understand, if it works for you, then it's not a fact that it will work for others.
But, in any case, it remains up to you. But I hope you understand that the GOST standards were written in order for it to work for as many people as possible.

P.S. I would still change the Vim version. This, both for you and for other translators, would make your work easier if you knew where to start from.

Ps. Ps. Sc. Please add the line "# Original translations." to the beginning of the text.
In the future, this will make it easier to work both when changing the encoding and when recognizing the original encoding.

**Comment by gagikh** [comment]
> Or it should be continue

**Comment by gagikh** [comment]
> @gagikh , This is a really big breakthrough compared to what it was. But why did you stop in the middle? Or it should be continued... Я не так, чтоб очень хорошо ззнал армянский, но, учитыавая, что большую часть мы, так или иниче, по историческим и религиозным причнанам бок о бок порожили с арманами и грузинамими вместе, кое что я понимаю. Тем более, что считаю что Армения это культруная "колыбель" Заковказкой культуры, уж чем там вам грузины обязаны я промолчу. И это одна из причин спроисть Вас почему Вы указыаете язык свойей культуры не как "hy", а как "arm". Вы так стесняетесь названия своего языка7 Я же Вам дал чёткие ссылки на требования к указанию кодов языка.
> 
> You have also been given clear references to the requirements of knowledge of the language code https://www.gnu.org/software/gettext/manual/html_node/Language-Codes.html
> 
> But instead of the required set number 1, you used set number 2, and even with the letter "B", which generally implies a bibliographic extension.
> 
> > B and T codes
> > While most languages are given one code by the standard, twenty of the languages described have two three-letter codes, a "bibliographic" code (ISO 639-2/B), which is derived from the English name for the language and was a necessary [legacy](https://en.wikipedia.org/wiki/Legacy_systems) feature, and a "terminological" code (ISO 639-2/T), which is derived from the native name for the language and resembles the language's two-letter code in ISO 639-1. There were originally 22 B codes; scc and scr are now deprecated.
> > In general the T codes are favored; [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) uses ISO 639-2/T.
> 
> just understand, if it works for you, then it's not a fact that it will work for others. But, in any case, it remains up to you. But I hope you understand that the GOST standards were written in order for it to work for as many people as possible.
> 
> P.S. I would still change the Vim version. This, both for you and for other translators, would make your work easier if you knew where to start from.
> 
> Ps. Ps. Sc. Please add the line "# Original translations." to the beginning of the text. In the future, this will make it easier to work both when changing the encoding and when recognizing the original encoding.

Hi @RestorerZ ,
Thanks for your carefull review. Of course Ill continue translation and push if possible. I have started with vim 7.1 and have translations checked on that version only, I swithced to the latest vim so that will translate and check with latest one. Again thanks for your notes about language locale specification. Ill change to hy.

**Pull request closed without merging**
