### PR TITLE
hollywood.vim: Fixed syntax highlighting for If-Then-Statements and generic For-In-Loops

### PR DESCRIPTION
**Pull request by nx-s**
A few fixes to the "hollywood.vim" script for fixing the highlighting of the oneliner statement `If-Then` and extended the script to correctly highlight generic For-In-Loops.

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks, but did you check with the maintainer?

**Comment by nx-s** [comment]
I have already informed him. I hope, he will respond soon. As the script was initially created by me, I guess, he will approve it, too :)

Thanks,
Tom

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sicher versendet mit [Proton Mail](https://pr.tn/ref/906NC4BZEYM0).

Christian Brabandt ***@***.***> schrieb am Donnerstag, 20. Juni 2024 um 8:10 nachm.:

**Comment by nx-s** [comment]
Got reply from Ola. Unfortunately, he is absence until 8/7 -- which I am not sure what it means. 8th of July or 7th of August?

Anyway, that's still a while. Good for him, bad for the PR.

Cheers,
Tom

Christian Brabandt ***@***.***> schrieb am Donnerstag, 20. Juni 2024 um 8:10 nachm.:

**Comment by chrisbra** [comment]
can you please squash?

**Comment by chrisbra** [comment]
thanks all

**Pull request closed without merging**
