### PR TITLE
More improvement

### PR DESCRIPTION
**Pull request by mattn**
This change will reduce much of the flicker of popupmenu.

### CODE REVIEW

**Comment by brammool** [comment]
Hmm, this means the popup menu is only redraw when it resized.  Where is it then redrawn if there was no resize?

**Comment by mattn** [comment]
Updated patch to reduce redrawing of popupmenu

**Comment by brammool** [comment]
This causes tests to fail.  Perhaps there should be a call to pum_redraw() after the pum_display() in insexpand.c ?

**Comment by mattn** [comment]
The cause of test fail seems to be timed-out and not related on this change.

**Comment by brammool** [comment]
It doesn't look like a timeout, e.g. https://travis-ci.org/github/vim/vim/jobs/744424902
On Travis the "huge" tests all fail and the errors are related to the popup menu.

**Comment by mattn** [comment]
I'm try this again.

**Pull request closed without merging**
