### PR TITLE
runtime: add Idris2 and Ipkg filetypes

### PR DESCRIPTION
**Pull request by srghma**
related https://github.com/neovim/neovim/pull/31068

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. Can you please amend the documentation at `:h filetype-overrule` and mention the `g:filetype_idr` variable?

**Comment by clason** [comment]
Are there actually significant enough differences between the Idris dialects that you would need (or want) to distinguish them as different filetypes? Otherwise this just adds complications for downstream for little benefit.

**Comment by srghma** [comment]
@clason the one I know that `postulate` keyword is removed in Idris2

other - https://idris2.readthedocs.io/en/latest/updates/updates.html

**Comment by clason** [comment]
That sounds very much like the syntax is mostly compatible, meaning that there's no reason not to support both under one filetype. (Syntax highlighting is not linting.)

**Comment by srghma** [comment]
@clason should I change the returned filetype to idris instead of idris2?

**Comment by clason** [comment]
Whatever is most used in practice (plugins, configs, etc.) I would recommend searching for existing idris filetype plugins (like https://github.com/idris-hackers/idris-vim) and following those.

**Comment by clason** [comment]
https://github.com/ShinKage/idris2-nvim Looks like the newest one. I would suggest asking(!) there for guidance; you might also want to ask if you could upstream the syntax and ftplugin files while you're at it.

**Comment by clason** [comment]
Please keep the parser out of this; a rename would only be necessary if there is a need for a separate, incompatible(!) parser for Idris(1) -- which so far doesn't sound like it.

So it sounds like `idris2` is the correct choice here, and there's no need for the global variable.

**Comment by srghma** [comment]
> You could still ask about upstreaming the filetype plugin

I didnt really understand. Why add `au BufNewFile,BufRead *.idr			setf idris2` to https://github.com/ShinKage/idris2-nvim if it will be added here and to neovim thereafter 

> it also includes the lidris2 filetype

yes, good idea, I will return lidris2 support to https://github.com/ShinKage/idris2-nvim

**Comment by clason** [comment]
What do you mean, "add"? It's already there https://github.com/ShinKage/idris2-nvim/blob/main/ftdetect/lidris2.vim (and remains there for people stuck with older Vim versions).

**Comment by chrisbra** [comment]
thanks!

**Comment by chrisbra** [comment]
Hm, actually I did expect *ipkg*  to be the filetype for the https://de.wikipedia.org/wiki/IPKG files. But since this format seems to be effectively dead, it might be fine to re-use this filetype.

**Pull request closed without merging**
