### PR TITLE
Add ! for ":csope find ..." command

### PR DESCRIPTION
**Pull request by anishsane**
If ':cs find' command was called with a '!', e.g.
:cs! find ......
and cscopequickfix option was appropriately set, vim will not jump to the first result in the quickfix window.
It will only list the results in the quickfix window.

Automatically jumping to the first result is disturbing to the user. I would rather have an option where we just present the user with a list of result and the user then chooses from the list.

Since it is optional (!), the existing behavior of the command will remain unchanged.

### CODE REVIEW

**Comment by vim-ml** [comment]
Hi,

This part looks weird:

-		qf_jump(qi, 0, 0, forceit);
+
+		if (!forceit)
+		{
+		    qf_jump(qi, 0, 0, forceit);
+		}

Might as well write qf_jump(qi, 0, 0, false) there...

Christ van Willegen

**Comment by brammool** [comment]
Anishane wrote:

>  If ':cs find' command was called with a '!', e.g.
> :cs! find ......
> and cscopequickfix option was appropriately set, vim will not jump to the first result in the quickfix window.
> It will only list the results in the quickfix window.
> 
> Automatically jumping to the first result is disturbing to the user. I would rather have an option where we just present the user with a list of result and the user then chooses from the list.
> 
> Since it is optional (!), the existing behavior of the command will remain unchanged.

Using ! for this is quite unexpected.  I would expect it to abandon the
current buffer, even when there are changes.

Also, it only applies when 'cscopequickfix' was set.  How about adding
something there to not jump to the first result?

Also, there is the ":lcscope" command, to use the location list instead
of the quickfix list.  Using another command perhaps?

Or perhaps use something else than "find".

I don't use cscope, thus I don't have much of a preference.

-- 
Have you heard about the new Beowulf cluster? It's so fast, it executes
an infinite loop in 6 seconds.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
2017-06-14 23:08 GMT+03:00 Bram Moolenaar <vim-dev-github@256bit.org>:
>
> Anishane wrote:
>
>> If ':cs find' command was called with a '!', e.g.
>> :cs! find ......
>> and cscopequickfix option was appropriately set, vim will not jump to the
>> first result in the quickfix window.
>> It will only list the results in the quickfix window.
>>
>> Automatically jumping to the first result is disturbing to the user. I
>> would rather have an option where we just present the user with a list of
>> result and the user then chooses from the list.
>>
>> Since it is optional (!), the existing behavior of the command will remain
>> unchanged.
>
> Using ! for this is quite unexpected. I would expect it to abandon the
> current buffer, even when there are changes.

This is the behaviour of some plugins. And this is the behaviour of
:grep (but not :vimgrep for some reason). I think that plugins in
question (e.g. ag.vim, AFAIR ack.vim as well) simply follow :grep
behaviour because this is what they aim to replace.

Would not say that this is consistent with the rest of VimL though.

**Comment by vim-ml** [comment]
Hi ZyX,

2017-6-15(Thu) 5:22:42 UTC+9 ZyX:
> 2017-06-14 23:08 GMT+03:00 Bram Moolenaar <vim-dev-github@256bit.org>:
> >
> > Anishane wrote:
> >
> >> If ':cs find' command was called with a '!', e.g.
> >> :cs! find ......
> >> and cscopequickfix option was appropriately set, vim will not jump to the
> >> first result in the quickfix window.
> >> It will only list the results in the quickfix window.
> >>
> >> Automatically jumping to the first result is disturbing to the user. I
> >> would rather have an option where we just present the user with a list of
> >> result and the user then chooses from the list.
> >>
> >> Since it is optional (!), the existing behavior of the command will remain
> >> unchanged.
> >
> > Using ! for this is quite unexpected. I would expect it to abandon the
> > current buffer, even when there are changes.
> 
> This is the behaviour of some plugins. And this is the behaviour of
> :grep (but not :vimgrep for some reason). I think that plugins in
> question (e.g. ag.vim, AFAIR ack.vim as well) simply follow :grep
> behaviour because this is what they aim to replace.
> 
> Would not say that this is consistent with the rest of VimL though.

Stop using `VimL`.

The official answer is done.
https://groups.google.com/d/msg/vim_dev/3Z5yM8KER2w/wAqws0QSEAAJ
> That is right.  I don't know where "vimL" came from, it looks like 
> someone wanted to fit anything into four characters.  It's not really a 
> language anyway.  "Vim script" is the short form. 

It has already been excluded from Vim's document with the following patch.
Patch 8.0.0360
https://groups.google.com/d/msg/vim_dev/QEl3OuEn1rs/7y2BVbt3CgAJ


Still, why use that keyword?
Besides, on the official mailing list.
Is this?
https://groups.google.com/d/msg/vim_dev/3Z5yM8KER2w/rjsLtQHNDwAJ
> VimL is faster to type.

It does not matter to us.
If you really want to type so, please write the following settings in your .vimrc.

iabbrev VimL Vim script


Anyway, please stop it because it is a nuisance.
--
Best regards,
Hirohito Higashi (h_east)

**Comment by anishsane** [comment]
Yes, I took the idea of using the ! from `:grep` only.

**Comment by brammool** [comment]
> Yes, I took the idea of using the ! from `:grep` only.

For :grep the ! means the current buffer will be abandoned if there are
changes.


-- 
I wonder how much deeper the ocean would be without sponges.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> For :grep the ! means the current buffer will be abandoned if there are
> changes.

Actually, it doesn't.  `:help grep` states

    The ":grep!" form of
    the |:grep| command doesn't jump to the first match automatically.

Which is backed up by `:help :make` and `:help :grep`

    							*:mak* *:make*
    ...
    			7. If [!] is not given the first error is jumped to.
    ...
    :gr[ep][!] [arguments]	Just like ":make", but use 'grepprg' instead of
    			'makeprg' and 'grepformat' instead of 'errorformat'.

**Comment by brammool** [comment]
James McCoy wrote:

> > For :grep the ! means the current buffer will be abandoned if there are
> > changes.
> 
> Actually, it doesn't.  `:help grep` states
> 
>     The ":grep!" form of
>     the |:grep| command doesn't jump to the first match automatically.
> 
> Which is backed up by `:help :make` and `:help :grep`
> 
>     							*:mak* *:make*
>     ...
>     			7. If [!] is not given the first error is jumped to.
>     ...
>     :gr[ep][!] [arguments]	Just like ":make", but use 'grepprg' instead of
>     			'makeprg' and 'grepformat' instead of 'errorformat'.

Yeah, that was a mistake.  It was corrected when the :vimgrep command
was added.  When setting 'grepprg' to "internal" you get this
behavior for :grep as well.

Clearly this is confusing, we should use ! for abandoning the buffer, for
any command that navigates to another file.  Unfortunately we can't
change existing commands without causing trouble (possibly losing
changes if a user makes a mistake).

-- 
The 50-50-90 rule: Anytime you have a 50-50 chance of getting
something right, there's a 90% probability you'll get it wrong.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by anishsane** [comment]
The requirement and the pull request was for this plugin: https://github.com/chazy/cscope_maps
I used below wrapper over the `:cs` command and I am getting more or less similar behavior. So, this pull request is no longer needed.

    function! s:cscope_find(cs_command)
        let cmd=":b " . bufnr("%") . " | normal " . line(".") . "G" . virtcol(".") . "|"
        exec a:cs_command
        exec cmd
        botright copen
        nnoremap <buffer> <CR> :let swb=&swb<CR>:set swb=<CR><CR>:let &swb=swb<CR>
    endfunction

**Pull request closed without merging**
