### PR TITLE
coverity: use  CFLAGS: -Wno-error=deprecated-declarations to avoid bu…

### PR DESCRIPTION
**Pull request by pheiduck**
…ild error

### CODE REVIEW

**Comment by brammool** [comment]
Let's just ignore that warning completely.

**Comment by pheiduck** [comment]
> Let's just ignore that warning completely.
What do you mean by that?

**Comment by brammool** [comment]
> > Let's just ignore that warning completely.
> What do you mean by that?

      CFLAGS: -Wno-error=deprecated-declarations

This means the warning is given, but not considered an error.

      CFLAGS: -Wno-deprecated-declarations

This means the warning is not given.  We should do that for the other
builds as well, because it obscures real problems.


-- 
Every time I lose weight, it finds me again!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pheiduck** [comment]
@brammool  https://github.com/vim/vim/pull/11003

**Pull request closed without merging**
