### PR TITLE
runtime: Detect maxima files

### PR DESCRIPTION
**Pull request by doronbehar**

### CODE REVIEW

**Comment by brammool** [comment]
Please add test entries in src/testdir/test_filetype.vim

**Comment by doronbehar** [comment]
> Please add test entries in src/testdir/test_filetype.vim

Done.

**Comment by brammool** [comment]
Thanks, but these are just patterns, so you can add entries to the table above.
A separate function is only needed when the detection depends on the file contents.

**Comment by doronbehar** [comment]
Done, and added another file pattern I forgot last time.

**Comment by doronbehar** [comment]
Thanks!

**Comment by gdupras** [comment]
".dem" is also used by gnuplot for demos. See here: http://gnuplot.info/demos.

**Comment by brammool** [comment]
The *.mc pattern was already used to call the dist#ft#McSetf() function.
Can you please add Maxima detection to that function, and remove the new *.mc pattern?

**Comment by doronbehar** [comment]
Removed both `.dem` and `.mc` patterns, and added a comment explaining why I omitted them.

**Comment by doronbehar** [comment]
I don't understand why the PR is at merge conflict - I rebased to `master`..

**Comment by brammool** [comment]
> I don't understand why the PR is at merge conflict - I rebased to `master`..

I don't know what you did, but it shows the change as adding lines, not
changing the existing line to a new one.

Anyway, I'll include the change and update the comment.

I hope you can look into detecting the filetype from the file content at
some point.

-- 
Giving a commit hash to refer to a patch is like giving longitude and
lattitude to refer to a city.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by doronbehar** [comment]
Thanks for #18185 , it looks good to me.

**Comment by yegappan** [comment]
Is this PR still needed and applicable?

**Comment by doronbehar** [comment]
Not needed since https://github.com/vim/vim/commit/928a13135629fa8e73796760077b1b877918a080 - committed two days after this was opened.

**Pull request closed without merging**
