### PR TITLE
Fix haskellcomplete: reset variables

### PR DESCRIPTION
**Pull request by alx741**
So further completions work properly

### CODE REVIEW

**Comment by brammool** [comment]
You probably want to send this to https://github.com/alx741/haskellcomplete.vim

**Comment by alx741** [comment]
> You probably want to send this to https://github.com/alx741/haskellcomplete.vim

Yes, I am the maintainer of https://github.com/alx741/haskellcomplete.vim (and haskellcomplete.vim in the runtime of course) I'm trying to reflect the changes upstream... Should I do it some other way?

**Comment by alx741** [comment]
any updates on this?

**Comment by chrisbra** [comment]
the prefered way to send updates of runtime files is to send the complete files for inclusion with Vim to Bram directly.

**Comment by k-takata** [comment]
Don't you update the "Last Change" date in the header?

**Comment by alx741** [comment]
> Don't you update the "Last Change" date in the header?

oh! I forgot about that, will change it

Will send the new file to Bram then. Thanks guys

**Comment by brammool** [comment]
Included now, sorry it took so long.

**Pull request closed without merging**
