### PR TITLE
Set pamconf for ~/.pam_environment

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by mgedmin** [comment]
This doesn't seem right.

/etc/pam.conf (and /etc/pam.d/*) looks like this:

```
# Format:
# serv.	module	   ctrl	      module [path]	...[args..]		     #
# name	type	   flag							     #

...
session required        pam_env.so readenv=1 user_readenv=1 envfile=/etc/default/locale
...
```

~/.pam_environment (and /etc/environment) looks like this:

```
LANG="lt_LT.UTF-8"
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
```

The format is quite different.

**Comment by tesuji** [comment]
Oh, I missed that. Wishing there are syntax for `~/.pam_environment`.
closed as wrong fix.

**Comment by mgedmin** [comment]
.pam_environment is a simple KEY=VALUE format, you can probably use `:setf sh` for that.

It would be nice if there was a filetype that allows just KEY=VALUE without all the bells and whistles of full shell syntax.  Maybe `conf` or `dosini`?  Neither is an exact fit, but...

It's annoying that the pam_env manual page doesn't specify the exact format, other than (KEY=VALUE).  The quoting rules are unclear to me, e.g. are \-escapes supported?  Ar the quotes mandatory?  Must they be double quotes, or can they be single quotes?

**Comment by tesuji** [comment]
Thanks for considering this. I opened https://github.com/linux-pam/linux-pam/issues/221
for asking upstream support from linux-pam.

**Pull request closed without merging**
