### PR TITLE
Matched text isn't highlighted in cmdline pum

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  Matched text isn't highlighted in cmdline pum.
Solution: Use cmdline completion pattern in cmdline mode.

### CODE REVIEW

**Comment by zeertzjq** [comment]
For non-fuzzy matching this isn't always accurate, as every kind of Cmdline completion has a different kind of non-fuzzy matching procedure. This PR only uses prefix matching like what is used Insert mode completion.

**Comment by Shane-XB-Qian** [comment]
perhaps better be refer this ticket with #15021

and this fuzzy of cli I recalled was impl by @yegappan so perhaps he can input something?

or I am not sure cli pum should be something like insert-compl? vs fuzzy of cli was good but fuzzy of insert-compl so far I can't completely feel that's a good idea.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
um.. the cli compl seems was from @ychin
let's see if there some input, or just your said way.

--
shane.xb.qian

**Comment by chrisbra** [comment]
Thanks for that!

**Pull request closed without merging**
