### PR TITLE
Add :vsb[uffer]

### PR DESCRIPTION
**Pull request by bobrippling**
I found myself doing `:vs | b <buffer I wanted>` too often, so in the same way that `:split` has a `:vsplit` counterpart, I have added `:sbuffer`'s counterpart, `:vsbuffer`.

I suppose `:vert sb <buffer>` works, but I found that to be roughly as long to type as my initial solution to the problem.

This patch also adds `:sbuffer` and `:vsbuffer` tests.

### CODE REVIEW

**Comment by bstaletic** [comment]
What's the benefit over placing `cnoreabbrev vsb vert sb` in your vimrc?

**Comment by bobrippling** [comment]
Mainly having it treated as a command, so if I want to edit a file that has `"vsb "` in its name, it won't be expanded. Perhaps we could think about a more general way of doing this, to specify that an abbreviation should only be expanded at the start of a command?

**Comment by andymass** [comment]
@bobrippling,

     cnoreabbrev <expr> vsb getcmdtype()==':' && getcmdline()=='vsb' ? 'vert sb' : 'vsb'

alternatively, see the plugin [cmdalias](https://www.vim.org/scripts/script.php?script_id=746).

**Comment by bobrippling** [comment]
@andymass fantastic! Thank you

**Pull request closed without merging**
