### PR TITLE
lua: indent curly bracket followed by line comment

### LINKED ISSUE #12305: lua indentation messed by comments
### Steps to reproduce

open test.lua:
```lua
do
    { --
    }
end
```
gg=G, then it becomes:
```lua
do
    { --
}
end
```

### Expected behaviour

stay unchanged

### Version of Vim

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 16 2022 23:27:53)

### Environment

MacOS 13.2.1, xterm-256color, iTerm2

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by champignoom**
fixes https://github.com/vim/vim/issues/12305

### CODE REVIEW

**Comment by chrisbra** [comment]
have you contacted the maintainer of the file?

**Comment by champignoom** [comment]
> have you contacted the maintainer of the file?

https://github.com/vim/vim/blob/5b10a140983c16140d69a214494c4b8af8b34763/runtime/indent/lua.vim#L3

I tried but then got an error message in Portuguese:
> Mensagem do serviço de email no servidor [mx3.bol.com.br](http://mx3.bol.com.br/)

**Comment by brammool** [comment]
> > have you contacted the maintainer of the file?
> 
> https://github.com/vim/vim/blob/5b10a140983c16140d69a214494c4b8af8b34763/runtime/indent/lua.vim#L3
> 
> I tried but then got an error message in Portuguese:
> > Mensagem do serviço de email no servidor [mx3.bol.com.br](http://mx3.bol.com.br/)

I have another email address for Marcus, I'll send him the link to this
github PR.

-- 
CRONE:  Who sent you?
ARTHUR: The Knights Who Say GNU!
CRONE:  Aaaagh!  (she looks around in rear) No!  We have no licenses here.
           "Monty Python and the Holy editor wars" PYTHON (MONTY) SOFTWARE LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I'll adjust the CODEOWNERS file (using Tabs instead of spaces), thanks.

**Pull request merged**
