### PR TITLE
Support CSS Color Module Level 4 RGBA hex format

### PR DESCRIPTION
**Pull request by hauleth**
Ref: https://drafts.csswg.org/css-color/#hex-notation

### CODE REVIEW

**Comment by k-takata** [comment]
Did you contact the maintainer?

**Comment by hauleth** [comment]
@k-takata not yet. But I am doing it right now.

**Comment by hauleth** [comment]
@k-takata I have sent email to maintainer on 2.12 and no feedback yet.

**Comment by brammool** [comment]
This was already included.

**Pull request closed without merging**
