### PR TITLE
Tinytests

### PR DESCRIPTION
**Pull request by ghost**
The primary purpose of these proposed changes is to ensure that the "tinytests" target in testdir/Make_ming.mak can be run correctly regardless of the 'fileformat' property of the .in and .ok files in the workspace.  If the fileformat of the test.out file is not the same as the fileformat of the .ok file, diff will report differences and the test will fail.  This becomes possible if git-checkout changes line endings.  

The first commit prevents test22 from failing if does not have CRLF line endings.  With this change, the fileformat change made to .in files in Make_ming.mak is no longer necessary and can be removed.  

The remaining commits change Make_ming.mak so that:
  1.  the fileformat of .in files is not changed,
  2.  the fileformat for test.out and .ok files are forced to be the same,
  3.  the scratch directory "dostmp" becomes unnecessary and can be eliminated, and
  4.  direct references to DOS utilities are changed to use the defined Make variables.

With syntax changes, I think these changes to Make_ming.mak are appropriate for Make_dos.mak as well.

### CODE REVIEW

**Comment by brammool** [comment]
Looking at the github actions, which have three Mingw targets, they all still appear to use dostmp:
..\gvim -u dos.vim -U NONE --noplugin --not-a-term "+set ff=unix|f test.out|wq"  dostmp\test26.out
Is this using src/testdir/Make_dos.mak?

**Comment by vim-ml** [comment]
On 09/21/2020 3:25 PM, Bram Moolenaar (Vim Github Repository) wrote:
>
> Looking at the github actions, which have three Mingw targets, they 
> all still appear to use dostmp:
> ..\gvim -u dos.vim -U NONE --noplugin --not-a-term "+set ff=unix|f 
> test.out|wq" dostmp\test26.out
> Is this using src/testdir/Make_dos.mak?
>
yes

**Comment by vim-ml** [comment]
On 09/21/2020 3:25 PM, Bram Moolenaar (Vim Github Repository) wrote:
>
> Looking at the github actions, which have three Mingw targets, they 
> all still appear to use dostmp:
> ..\gvim -u dos.vim -U NONE --noplugin --not-a-term "+set ff=unix|f 
> test.out|wq" dostmp\test26.out
> Is this using src/testdir/Make_dos.mak?
>
Yes it is.  I noticed that as well but I have no idea how to change it.

**Comment by brammool** [comment]
I do not see any reference to testdir/Make_ming.mak from any of the Makefiles in the src directory.
The src/Make_cyg_ming.mak file does not even have a "test" target.
Only src/Make_mvc.mak refers to testdir/Make_dos.mak.

Have you been using testdir/Make_ming.mak only directly?

**Comment by ghost** [comment]
On Mon, Sep 21, 2020 at 4:48 PM Bram Moolenaar <notifications@github.com>
wrote:

> I do not see any reference to testdir/Make_ming.mak from any of the
> Makefiles in the src directory.
> The src/Make_cyg_ming.mak file does not even have a "test" target.
> Only src/Make_mvc.mak refers to testdir/Make_dos.mak.
>
> Have you been using testdir/Make_ming.mak only directly?
>
Yes.  I "cd testdir" and then "mingw32-make -f Make_ming.mak ..." .

By the way, I've now made similar modifications to Make_dos.mak but do not
have Visual Studio.
Would you like me to push that to github as well?
If I do push it to github, do I then need to submit another pull request?

Sorry for the questions but this is my first time using github and pull
requests.

**Comment by ghost** [comment]
The tests and test procedure are not broken and so changes are not needed.

**Pull request closed without merging**
