### PR TITLE
Moving the cursor in popupwin's filter, do not highlight. 

### PR DESCRIPTION
**Pull request by rbtnn**
_code_

```
function! MyFilter(winid, key) abort
    if a:key == "0"
        call win_execute(a:winid, "call setpos('.', [0, 1, 1, 0])")
        return 1
    endif
    if a:key == "G"
        call win_execute(a:winid, "call setpos('.', [0, line('$'), 1, 0])")
        return 1
    endif
    if a:key == "j"
        call win_execute(a:winid, "call setpos('.', [0, line('.') + 1, 1, 0])")
        return 1
    endif
    if a:key == "k"
        call win_execute(a:winid, "call setpos('.', [0, line('.') - 1, 1, 0])")
        return 1
    endif
    if a:key == 'x'
        call popup_close(a:winid)
        return 1
    endif
    return 0
endfunction

call popup_menu(['123', '222', '333', '444', '555', '666', '777', '888', '999'], {
            \ 'maxheight' : 3,
            \ 'filter' : 'MyFilter'
            \ })
```
1. call popup_menu()

2. press G
3. do not highlight the cursor line

### CODE REVIEW

**Comment by rbtnn** [comment]
```vim
call popup_menu(['123', '222', '333'], *{
        \ filter: 'MyFilter',
        \ })
```
```vim
call popup_menu(['123', '222', '333'], *{
        \ filter: 'MyFilter',
        \ })
```

```vim
call popup_create(['123', '222', '333'], *{
        \ filter: 'MyFilter',
        \ })
```

**Comment by rbtnn** [comment]
Setting `filter` property of a popupwin created from `popup_create`, Is the cursor highlight?

* popup_menu -> highlight
```vim
call popup_menu(['123', '222', '333'], *{
        \ })
```

* popup_menu + filter -> highlight
```vim
call popup_menu(['123', '222', '333'], *{
        \ filter: 'MyFilter',
        \ })
```

* popup_create + filter -> highlight or not highlight?
```vim
call popup_create(['123', '222', '333'], *{
        \ filter: 'MyFilter',
        \ })
```

**Comment by rbtnn** [comment]
I think to need to add `cursorline` property such as `&cursorline` to popup options which means whether highlights at the cursor line.

**Comment by brammool** [comment]
The highlighting is currently part of the menu filter.  It should not be used for all popup windows.  Perhaps we can decouple it from the menu filter and make it a property of the popup?  Your change would then need to check the flag before setting the highlight.  And the property would default to on for popup_menu().

**Comment by brammool** [comment]
Is this ready now?

**Comment by rbtnn** [comment]
Yes, this is ready.

**Pull request closed without merging**
