### PR TITLE
Improve processing of key events in W32 GUI

### LINKED ISSUE #9895: Can't map ctrl slash in nightly gVIM build on Windows
### Steps to reproduce

I tried both `noremap <C-/>` and `noremap <C-_>' to map ctrl slash but neither worked. Press Ctrl+V followed by Ctrl+/ in insert mode does nothing.

### Expected behaviour

Map ctrl slash

### Version of Vim

v8.2.4501 64 bit windows installer from https://github.com/vim/vim-win32-installer/releases

### Environment

Windows

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by LemonBoy**
This changeset adds what's essentially a replacement for
TranslateMessage that takes into account the user keyboard layout and
enables more events to be processed without having to special-case them.

The use of MapVirtualKey allows Vim to resolve some of the "virtual"
keycodes such as VK_OEM_{1..6} and friends according to the user kb
layout.

We call ToUnicode with an intentionally reduced keyboard state to avoid
a pitfall of TranslateMessage: not every combinations of Ctrl+<key>
produce a keycode (eg. Ctrl+] does not) and thus no WM_CHAR would be
emitted for them. Since we only care about the character rather than its
interaction with Ctrl or Alt let's drop those from the state matrix.

The remaining code performs what TranslateMessage would do and pump the
appropriate messages in the main loop.

Two main differences:
- Dead keys are handled in-place, no WM_DEADCHAR is emitted.
- Modifiers are handled together with the keys they're associated to
  rather than leaving them in the input queue.

Please test this patch with different keyboard layouts and try mappings including Ctrl and Alt, I've been using this for a couple of days with no problem at all.

Fixes the problem I noticed on my Windows machine and allows me to map `<C-]>`.

Fixes #9895 again, in a different way.

CC @mattn and @k-takata, your feedback as seasoned Win32 hackers is much appreciated.

### CODE REVIEW

**Comment by LemonBoy** [comment]
No feedback about this PR? This change is much needed to make gVim able to map keys like `<C-]>` when using non-entirely-standard keyboard layouts like [this one](https://github.com/thomasfaingnaert/win-us-intl-altgr/blob/b1990ef65aea9451dcc60a2b8fd8be547e0cfbcc/us-international-altgr-deadkeys.klc#L48-L49).

**Comment by LemonBoy** [comment]
> This break IME (input method editor). I can not input multi-byte strings with this patch.

Thanks for the feedback, I did try the latest version of this patch with the Japanese IME and now it seems to be working again.

**Comment by mattn** [comment]
I'm okay to merge.

**Comment by cmon1701** [comment]
This change breaks key presses of ‚:’ and other keys of neo2's 3rd level. 
See https://www.neo-layout.org/ 
3rd level (Ebene in German): https://dl.neo-layout.org/grafik/bilder-einzeln/flat/neo-3-tkl.path.svg
‚:‘ is pressed via Capslock+; (QWERTY) / mod3+d (neo2).
It works till gvim_8.2.4803 and is broken starting from gvim_8.2.4807 on (independent of x86 or x64).

Can you please fix this patch? **8.2.4807: processing key eveints in Win32 GUI is not ideal** 
Thanks!!

**Comment by chrisbra** [comment]
@cmon1701 can you check, if #10823 or #11760 fixes it properly? (I am not actually sure, if #11760 is a sub- or superset of #10823)

**Comment by cmon1701** [comment]
Hi chrisbra,
thanks for your quick response!
I have never compiled vim (Win GUI) so far. Are there any executables that incorporate your mentioned fixes or could you please provide them for me? Thanks!
(This is also broken in the newest version, 9.0.1103.)

**Comment by chrisbra** [comment]
unfortunately, there doesn't seem to be a way to download those compiled binaries. I have now created #11762 to address this and give users the possibility to download the artifcats and test that. That means, once it is merged and PR authors rebase their work on top of it, you can then download artifacts and test those changes.

**Comment by cmon1701** [comment]
@chrisbra thank you!!

**Comment by zewpo** [comment]
@chrisbra  and @cmon1701  
I believe that #11760  is a superset of  #10823
@haron13-2019  [@ant0sha] can confirm.

@cmon1701  when you can access a build of gvim (I'm not sure how @chrisbra #11762 works yet), but if you can get at least
Patch 9.0.1112 (which includes #11760), then you should be able to check if it resolves the issue regarding "keys of neo2's 3rd level"

**Comment by chrisbra** [comment]
You go to the Appveyor CI page for [vim](https://ci.appveyor.com/project/chrisbra/vim/history) and click on the PR that you are interested in. E.g. for #11767 you click on https://ci.appveyor.com/project/chrisbra/vim/builds/45810751 and there you will see the last Appveyor (windows builds and tests) results for that particular build. You will have a tab called artifacts, from which you can then download those build binaries (vim.exe and gvim.exe)

**Comment by zewpo** [comment]
Cool, thanks @chrisbra

**Comment by sme-prus001** [comment]
Ah, I've left my comment on the code page. After 4807 you can't press Ctrl+S (Windows 10) in Cyrillic layout in insert mode - you get 'ы' instead. You can't underestimate the lack of fast saving. The same is for other Ctrl keys too, like Ctrl+A, Ctrl+C, Ctrl+V etc. I didn't try 4806 but in 4803 everything was ok.

**Comment by zewpo** [comment]
Hi @sme-prus001   

This PR was done over 10 months ago, and since then more recent changes have addressed some Ctrl+... functionality, at least I'm aware of the Ctrl+_ behavior was put back.

Would it be possible for you to confirm if this is still a problem with the latest gVim?   If you need to, you can grab an installer from here:  https://github.com/vim/vim-win32-installer/releases

I'll see if I can add some test scripts to cover this.

**Comment by sme-prus001** [comment]
Hi,
Thank you for the response.
I think it's in all the releases since that, because I was first alarmed when I installed the latest 9.0 and the functionality was not there. So I went to try other versions and find out what and when happened and found that commit. The url you gave me is exactly what I used.
You must have Cyrillic (or other non-Latin?) keyboard installed, open vim, insert mode, Alt+Shift to switch to Cyrillic, type some text, press Ctrl+S. If saved - ok, if 'ы' appeared - bad.
Vim should be installed with options "Vim with all enhancements (default)", "Remap a few keys", "Right: popup menu, Left: select mode (Windows)".
***@***.***
Regards
Georgiy Pruss

**Comment by zewpo** [comment]
@sme-prus001  thanks for the info.   I'll try and test it.

**Comment by risa2000** [comment]
@LemonBoy
As I just found out (and described in #12595) the changes which possibly started here broke key handling in vim and gVim on Windows with Czech keyboard layout.

It seems that vim and gVim started to mangle the key codes from the keyboard. It is still unclear for me why, but the current state is that pressing `Ctrl-<right key to P>` on `Czech` keyboard layout in Windows produced `Esc(code)` for past 20 years in vim, until recently. Now it produces either plain character (ignores `Ctrl`) in gVim, or produces wrong Ctrl code in vim (see my issue for details).

Just for the record here, I will reiterate that the keyboard still emits `Esc(code)` on pressing `Ctrl-<right key to P>`, because using the same Czech keyboard layout in same Windows, while connected via putty to linux terminal on linux box, and running vim 9 in there works as expected. So the problem is definitely in vim and in particular in vim handling of the key codes on Windows.

Could you confirm that the changes you committed, modify, or filter key codes received from the OS?
If yes, could you explain, what was your goal?

**Pull request closed without merging**
