### PR TITLE
Correctly detect apachestyle comments

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR makes the comments correctly detected in apachestyle syntax.
Without this modification, comments are not correctly detected / not shown into the correct color.

It's really tiny as it just swaps the order of 2 lines.

Thank you very much 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Note that I tried to contact Christian, the author of this file, but he's unreachable.

**Comment by brammool** [comment]
Ben Rubson wrote:

> Note that I tried to contact Christian, the author of this file, but
> he's unreachable.

In that case, would you mind taking over maintenance?
The last change was long ago, thus it won't be much work.

-- 
In a world without walls and borders, who needs windows and gates?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by benrubson** [comment]
> In that case, would you mind taking over maintenance?

Sure, feel free to add me to the top of the file as the last maintainer.

**Comment by brammool** [comment]
Ben Rubson wrote:

> > In that case, would you mind taking over maintenance?
> 
> Sure, feel free to add me to the top of the file as the last maintainer.

The idea is that the maintainer takes care of this.  Also updating the
"last changed" field.  Then please send me the updated file.

-- 
Nobody will ever need more than 640 kB RAM.
		-- Bill Gates, 1983
Windows 98 requires 16 MB RAM.
		-- Bill Gates, 1999
Logical conclusion: Nobody will ever need Windows 98.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by benrubson** [comment]
Done !
While there, I added common Apache style config files to be correctly detected.
Many thx 👍

**Comment by brammool** [comment]
Thanks.  I'll include it.  I updated the header a bit.

**Pull request closed without merging**
