### PR TITLE
syntax/dep3patch.vim: Last-Update should not have a 'd' on the end

### PR DESCRIPTION
**Pull request by vanvugt**
Per the specification:
https://dep-team.pages.debian.net/deps/dep3/

### CODE REVIEW

**Comment by chrisbra** [comment]
did you contact the maintainer?

**Comment by vanvugt** [comment]
> did you contact the maintainer?

I have now.

**Comment by jamessan** [comment]
Applied to the vim-debian repo.  I'll send an update to Bram.

**Comment by chrisbra** [comment]
Closing then

**Pull request closed without merging**
