### PR TITLE
tests: use v:progpath instead of GetVimProg

### PR DESCRIPTION
**Pull request by blueyed**
TODO:

- [ ] do not write it to vimcmd in the first place

Ref: https://github.com/vim/vim/commit/da65058a9c4774dc534c7ae98d24c58b5db669fa#r34658132

### CODE REVIEW

**Comment by blueyed** [comment]
`v:progpath` was mentioned to not work in https://github.com/vim/vim/pull/2186, but then crossed out.

/cc @ichizok

**Comment by brammool** [comment]
This is not going to work, because on some systems v:progpath is just "vim".  I tried on Mac OS.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> `v:progpath` was mentioned to not work in
> https://github.com/vim/vim/pull/2186, but then crossed out.

No idea why it was crossed out, it can reproduce it with the current
version of Vim (on MacOS).

-- 
The real
trick is
this: to
keep the
lines as
short as
possible
and keep
the size
the same
yet free
from the
need for
hyphena-
Dammit!!  (Matthew Winn)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> v:progpath

According to https://github.com/vim/vim/pull/2186#issuecomment-334345195 it is relative / just "vim" when not starting it with an absolute path?
According to the help this sounds like a bug, since it should be absolute always.

From https://github.com/vim/vim/commit/da65058a9c4774dc534c7ae98d24c58b5db669fa#r34664494:

> $VIMPROG may be different from v:progpath, depending on what test you are running and how. I sometimes source a test*.vim file and expect the vim command executed in the terminal be the one that was most recently build, not the one I'm currently running.

So in the case of sourcing a test it would fall back to '../vim' then (because there is no `vimcmd`), no?  (and the Makefile would also write '../vim' there).

How do you "source a test*.vim file" exactly?
(It is required to be in `src/testdir` then already (for the relative "imports"), and tests are not run automatically when sourcing.  Do you run the test function then manually?)

(Also it appears to make a difference only for a few tests, i.e. other tests would use the current Vim instance anyway - resulting in a mix of current/build Vim being used)

> The vimcmd file has two lines, the stuff in the second line is not in v:progpath, thus we can't drop writing "vimcmd".

Yes, I've not meant to remove the file completely.

**Comment by blueyed** [comment]
For reference: `v:progpath` is used already in other tests.  According to the argument above it should use `GetVimProg()` then probably?

**Comment by brammool** [comment]
Daniel Hahler wrote:

> > v:progpath
> 
> According to
> https://github.com/vim/vim/pull/2186#issuecomment-334345195 it is
> relative / just "vim" when not starting it with an absolute path?
> According to the help this sounds like a bug, since it should be
> absolute always.

The docs may be a bit confusing.  It mentions "including the path", but
that means it includes the path if it was given.  The help also says to
use "exepath()" to get the full path, but on Linux a special trick is
used to get the actual path of the executable, which ends up to always
be a full path.  While on Mac you only get the full path if Vim was
started with a path, not when just typing "vim".

I'll add some more explanation to the help.

-- 
Q: What is a patch 22?
A: A patch you need to include to make it possible to include patches.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> For reference: `v:progpath` is a used already in other tests.
> According to the argument above it should use `GetVimProg()` then
> probably?

There are actually quite a lot of them.  We defenitely want to avoid the
inconsistency.  Since changing it either way will change the executable
used in corner cases, perhaps we should go for the simpler one and use
v:progpath?

-- 
"I can't complain, but sometimes I still do."   (Joe Walsh)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
>> For reference: `v:progpath` is a used already in other tests. According to
>> the argument above it should use `GetVimProg()` then probably?

> There are actually quite a lot of them. We defenitely want to avoid the
> inconsistency. Since changing it either way will change the executable used
> in corner cases, perhaps we should go for the simpler one and use v:progpath?

I think having a method (`GetVimProg`) allows for more flexibility, e.g. when
you want to prepend something always (e.g. "covimerage run --append" to get
coverage).
For this however it would need to return a list then, and would not really
reflect what the name implies then.

So for this it would be better to not use `v:progpath`/`GetVimProg` in tests,
but the already existing `GetVimCommand()` and `GetVimCommandClean()` functions
(which currently return a string - but could be changed to use a list (not
necessary, but cleaner)).

**Comment by brammool** [comment]
Daniel Hahler wrote:

> >> For reference: `v:progpath` is a used already in other tests. According to
> >> the argument above it should use `GetVimProg()` then probably?
> 
> > There are actually quite a lot of them. We defenitely want to avoid the
> > inconsistency. Since changing it either way will change the executable used
> > in corner cases, perhaps we should go for the simpler one and use v:progpath?
> 
> I think having a method (`GetVimProg`) allows for more flexibility, e.g. when
> you want to prepend something always (e.g. "covimerage run --append" to get
> coverage).
> For this however it would need to return a list then, and would not really
> reflect what the name implies then.
> 
> So for this it would be better to not use `v:progpath`/`GetVimProg` in tests,
> but the already existing `GetVimCommand()` and `GetVimCommandClean()` functions
> (which currently return a string - but could be changed to use a list (not
> necessary, but cleaner)).

OK, let me do that and see what we end up with.  We can at least drop
some "-u NONE" and "--clean" arguments.

-- 
"I simultaneously try to keep my head in the clouds and my feet on the
ground.  Sometimes it's a stretch, though."              -- Larry Wall

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
