### PR TITLE
[RFC] Add getcmdscreenpos() and getcmdcompltype()

### PR DESCRIPTION
**Pull request by Shougo**
Hi.  This is the port of https://github.com/neovim/neovim/pull/18284.
It is useful for popup competion in command line mode.

~~`getcmdscreenpos()` works for me.  But `getcmdcompletion()` does not work well on Vim.~~
~~It works on neovim.~~

~~I think the implementation is same with Vim and neovim.~~
~~But the completion context seems wrong....~~

~~Can you check my implementation?~~

### CODE REVIEW

**Comment by LemonBoy** [comment]
> But the completion context seems wrong....
> Can you check my implementation?

I'll give you a small hint, check Vim's declaration of `command_complete` array... and compare it to NeoVim's...
Also, you need a `char_u` cast to let the compiler shut up.

**Comment by Shougo** [comment]
Thank you.  I have fixed it.  But it does not fix my errors.

`set_expand_context()` does not work as expected...

**Comment by Shougo** [comment]
I have fixed the errors.

**Comment by brammool** [comment]
Is this still WIP?
Any comments?

**Comment by lacygoill** [comment]
From the name of the `getcmdcompletion()` function, I thought it was giving the currently inserted completion when a pum was visible.  But actually, it gives the type of the current completion as specified by the third argument of `input()` or by the `-complete` argument of `:command`.  Maybe we could make sure to always mention the word "type" in conjunction with "completion":
```diff
diff --git a/runtime/doc/builtin.txt b/runtime/doc/builtin.txt
index 6abf76706..2ad34ffcf 100644
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -213,8 +213,8 @@ getcharmod()			Number	modifiers for the last typed character
 getcharpos({expr})		List	position of cursor, mark, etc.
 getcharsearch()			Dict	last character search
 getcharstr([expr])		String	get one character from the user
-getcmdcompletion()		String	return the current command-line
-					completion
+getcmdcompletion()		String	return the type of the current
+					command-line completion
 getcmdline()			String	return the current command-line
 getcmdpos()			Number	return cursor position in command-line
 getcmdscreenpos()		Number	return cursor screen position in
@@ -3213,9 +3213,9 @@ getcharstr([expr])					*getcharstr()*
 		result is converted to a string.
 
 getcmdcompletion()					*getcmdcompletion()*
-		Return the current command-line completion type.  Only works
-		when the command line is being edited, thus requires use of
-		|c_CTRL-\_e| or |c_CTRL-R_=|.
+		Return the type of the current command-line completion.
+		Only works when the command line is being edited, thus requires
+		use of |c_CTRL-\_e| or |c_CTRL-R_=|.
 		See |command-completion| for the return string.
 		Also see |getcmdtype()|, |setcmdpos()| and |getcmdline()|.
 		Returns an empty string when completion is not defined.
diff --git a/runtime/doc/usr_41.txt b/runtime/doc/usr_41.txt
index c9b79e797..abcbd3453 100644
--- a/runtime/doc/usr_41.txt
+++ b/runtime/doc/usr_41.txt
@@ -976,7 +976,8 @@ Buffers, windows and the argument list:
 	swapname()		get the swap file path of a buffer
 
 Command line:					*command-line-functions*
-	getcmdcompletion()	get the current command line completion
+	getcmdcompletion()	get the type of the current command line
+				completion
 	getcmdline()		get the current command line
 	getcmdpos()		get position of the cursor in the command line
 	getcmdscreenpos()	get screen position of the cursor in the
```
FWIW, if it's not too late, I would also consider including "type" in the name of the function itself:

    getcmdcompletion()
    getcmdcompletiontype()
                    ^--^

I did a quick test, and both `getcmdcompletion()` as well as `getcmdscreenpos()` seem to work as intended.

**Comment by Shougo** [comment]
> Is this still WIP?
> Any comments?

Sorry.  It is not WIP.

**Comment by Shougo** [comment]
I have renamed the function name.

**Comment by brammool** [comment]
When I see getcmdcmptype() I guess "cmp" stands for compare, but it means completion.
getcmdcmpltype() ?   Perhaps there is a better name.  We do have getcmdtype() already.

**Comment by Shougo** [comment]
OK.  I have renamed.

**Comment by zeertzjq** [comment]
`cmpl` has never appeared in help files, whereas `compl` has appeared in several help tags, so `compl` should be a better abbreviation.

**Pull request closed without merging**
