### PR TITLE
Windows terminal stable gui colors 

### LINKED ISSUE #11373: Vim with termguicolors in Windows Terminal outputs wrong color
### Steps to reproduce

```
vim --clean +"set ls=2 tgc"
```

### Expected behaviour

In the old conhost terminal, the colors are output properly. Same thing should happen in Windows Terminal.

[![vim in conhost][1]][1]

[1]: https://i.stack.imgur.com/fUNtg.png

### Actual Behavior

But in Windows Terminal (v1.16.2524.0), the colors with `:h termguicolors` enabled is incorrect.

[![vim in Windows Terminal][2]][2]

  [2]: https://i.stack.imgur.com/G6XAq.png

### Version of Vim

9.0.648

### Environment

Operating system: Windows 11 version 21H2 (OS Build 22000.1098)
Terminal: Windows Terminal v1.16.2642.0 with Solarized Light colorscheme (comes with the terminal by default)
Value of $TERM: nil (also tried with 'xterm-256colors')
Shell: cmd.exe (also tried with powershell)

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by zewpo**
Closes #11373 

Problem: Windows Terminal had unstable color control, see https://github.com/vim/vim/issues/11373
Solution: Dont try and read the old command prompt colortable, use modern VT sequences instead.

### CODE REVIEW

**Comment by zewpo** [comment]
@k-takata    do the tests just use the changes in my PR, applied to the same faulty 815 in master?  If so, then they will still fail, or do the tests somehow also ignore 815?

**Comment by k-takata** [comment]
Ah, the CI checkouts the code with `refs/remotes/pull/11450/merge`, so the CI tests the code that is merged with the top of the master branch, which means v9.0.0815 is included.

Sorry for wasting your time. It would be better to rerun the tests after Bram is back.

**Comment by zewpo** [comment]
OK, thanks, I will dig deeper to see how the testing works, if I can replicate it against my own repo, it could reveal what I want to see for this.

**Comment by zewpo** [comment]
@k-takata   all good on my end.
https://github.com/zewpo/vim/actions/runs/3336651545

**Comment by zewpo** [comment]
closes #11373

**Comment by zewpo** [comment]
Converting this PR to draft.    

There is still some incorrect behavior occuring between some combinations of tgc and nors on the various windows terminal consoles.

I'm assuming `set nors` on windows is supposed to act the same as `set t_ti= t_te=` on linux.  Someone please correct me if I am mistaken.  

Well, it is not acting the same as linux in quite a few versions of the windows consoles.  I want to make sure it does for this PR, so I will take it out of draft after I have fixed it.

**Comment by brammool** [comment]
The issue mentions this PR fixes the problem.  I'll await it is no longer marked as draft though.

**Comment by zewpo** [comment]
@brammool   Sorry about all the noise from the CI tests.  Every time I do a commit to my own branch, it triggers these in your master vim branch, because of this PR.   Lesson learned.  Will keep it a bit more quiet after this one.

**Review by zewpo — COMMENTED** [review]
OK, ready for review.   reverted some of the more aggressive changes, to keep it manageable.

**Review by zewpo — COMMENTED** [review]
PR ready for review again.    Just made another commit, because testing revealed some issues with screen restore still occurred on win 10 - fixed now.  tested to be working on win 7, 8, 10, 11 and 11_insider.

**Review by zewpo — COMMENTED** [review]
and.. same fix for windows 10 command prompt.  Now command prompts restore nicely on all versions of windows 7,8,10,11 & 11_insider, as well as all windows terminals for win 10, 11 and 11 insider.    I cant think of what else to test right now.    happy for suggestions.

**Review by zewpo — COMMENTED** [review]
fixed compile TINY;  _rgb warnings [-Wunused-variable],  and error: 'p_tgc' undeclared

**Comment by zewpo** [comment]
This PR #11450 is failing test Test_popup_and_window_resize() on windows HUGE with non-gui vim.    But, this test is passing in my dev environment, which is in sync with this PR.   I also installed a fresh win2022, and my code is passing this test on that also.     So I am not sure how to debug what is happening here in this CI testing.  Any suggestions?

**Review by zewpo — COMMENTED** [review]
so... reverted all the screen-restore changes.  and just leaving the color fix, to see if that is enough to make CI testing pass.

**Review by zewpo — COMMENTED** [review]
OK, so I have simplified this PR, now I'm only submitting changes that fix the color issue.  And, I will work on the screen restore separately to tihs PR because it is more complex, and that has been holding me back from finishing this PR.

**Comment by zewpo** [comment]
I believe this PR is finally ready.  I dont know why the macos (huge) build is failing ci test.  I dont think that is related to this PR. All other CI tests are now passing.

**Review by zewpo — COMMENTED** [review]
fixed regression of Windows 10 Command Prompt rgb color issue, same as WT fix.

**Review by zewpo — COMMENTED** [review]
Able to use vtp_working in more places independent of tgc.  No need to check for Win 11, because Win 10 behaves the same.

**Comment by zewpo** [comment]
@brammool   It's like rolling dice, trying to get all the CI tests to pass.   I'm confident this PR is ready to go.  It solves the issue linked.   Is there anything else you'd like to see done for this PR?

**Comment by brammool** [comment]
> @brammool   It's like rolling dice, trying to get all the CI tests to
> pass.   I'm confident this PR is ready to go.  It solves the issue
> linked.   Is there anything else you'd like to see done for this PR?

There are some flaky tests, and it appears MacOS is most sensitive to
them (probably just because those systems are heavily loaded the tests
run a bit slower).  I sometimes run tests under valgrind to simulate a
slower system and can tune some wait times, but it's just guessing
really.

You'll have to make a best guess if a PR touches code that might
influence the test that is flaky or fails.

For this PR I can't judge from the code changes what works better.
Others have had chances to comment already, so I think I'll just include
it now and assume that if this causes new problems to be reported we'll
have to reconsider.

-- 
hundred-and-one symptoms of being an internet addict:
36. You miss more than five meals a week downloading the latest games from
    Apogee.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
