### PR TITLE
Installation instructions for MAC OSX

### PR DESCRIPTION
**Pull request by kieranbrowne**

### CODE REVIEW

**Comment by nuko8** [comment]
First , you should talk about Xcode or CommandLineTools; otherwise, `vim` won't compile because there may be neither `make`, `clang`, nor other command line utilities to build and install `vim` successfully (even that `git`!)   by default on some versions of Mac OS X.

Next, you should mention various options of `configure`; in particular, `--disable-darwin` and `--with-mac-arch`, which are most relevant to that particular OS.

To check the resulting executable, consider making use of `make test`.

Last but not least.  It could be OK to replace `/usr/bin/vim` of your system with a newly compiled `vim` at your own risk.  But, generally speaking, I do think such recommendation is wrong.

It's far better to use the PATH environment variable than overwriting or aliasing `vim`, and that's a widely accepted way for years.

**Comment by kieranbrowne** [comment]
Thanks for the response, I'll make those changes.

**Comment by wellle** [comment]
How about suggesting

```
sudo make install
```

instead of overwriting system Vim or messing with aliases or PATH?

**Comment by sukima** [comment]
I realize this is late but there is a patch sent to the mailing list: https://gist.github.com/sukima/4d649a5dfeb38a05a344 I don't remember the outcome of that.

**Comment by nuko8** [comment]
There's nothing special to OS X to build and install Vim.  It's as easy as that for other UNIX variants.

First, make sure you've installed Xcode or CommandLineToots.  If not, open a terminal and do

```
$ make --version
```

Then, a window pops up instructing you to install the developer tools.

Or, if you're sure you've not installed the tools yet,

```
$ xcode-select --install
```

will do the same.

Next, download and unarchive the tarball or clone the git repository, and, just like other UNIX variants,

```
$ cd vim/src
$ make
$ make test
$ sudo make install
```

or

```
$ cd vim
$ ./configure
$ make
$ make test
$ sudo make install
```

Both of them will install the executables into `/usr/local/bin` with  the runtime into `/usr/local/share/vim/vim74`.

If you find the default configuration is not enough for your needs, read `src/INSTALL` for general information about build and installation, e.g., how to pass variables to `make` and options to `configure`, and read `src/INSTALLmac.txt` for the information specific to OS X.

Reading `src/Makefile` and `src/configure.in` is often useful and helpful to figure out how to set up the build and installation system to meet your demands.

**Pull request closed without merging**
