### PR TITLE
Not all error messages are ready for translation.

### PR DESCRIPTION
**Pull request by RestorerZ**
Not all error messages are ready for translation. Added N_(). Continued patch 9.0.1572

### CODE REVIEW

**Comment by brammool** [comment]
> Not all error messages are ready for translation. Added N_().
> Continued patch 9.0.1572

Thanks.  I noticed quite a few Netbeans messages were not translated.
These might not be so important, the netbeans interface isn't used much,
we mainly keep it around for existing usage.  But translating them keeps
it consistent.

The messages after "#ifdef NBDEBUG" need no translation, these are for
debugging only.  Just like messages for internal errors are not
translated.

-- 
hundred-and-one symptoms of being an internet addict:
62. If your doorbell rings, you think that new mail has arrived.  And then
    you're disappointed that it's only someone at the door.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by RestorerZ** [comment]
> I noticed quite a few Netbeans messages were not translated. These might not be so important, the netbeans interface isn't used much, we mainly keep it around for existing usage. But translating them keeps it consistent.

Yes, these are mainly messages for NetBeans and, as you rightly said, it is necessary to maintain uniformity.


> The messages after "#ifdef NBDEBUG" need no translation, these are for debugging only.

Fixed it. This is indeed for internal use.

> Just like messages for internal errors are not translated.

But in this, let Bram disagree with you.
Yes, I know your [position](https://github.com/vim/vim/pull/12356#issuecomment-1537539272) on this issue, but there are a few points.

Firstly, these messages are displayed to the user, which means he must understand that something has happened.
Secondly, not all users speak English at your level, and at my very elementary level, too.
Thirdly, when the interface and messages are in the user's native language and suddenly some message appears in a language that he does not understand, and even the program does not work as he expects, then this, at least, confuses him, if not stupor.

But when it is clearly and clearly written in the message in his native language that this is an internal error and some explanations are given, then he perceives it normally. And at the same time he understands that it wasn't him who did something wrong there, but a really serious problem happened and calmly writes an bug report and sends it to the developer. Well, or addresses this question to someone who understands.

Well, that's something like that.

**Comment by brammool** [comment]
> > I noticed quite a few Netbeans messages were not translated. These
> > might not be so important, the netbeans interface isn't used much,
> > we mainly keep it around for existing usage. But translating them
> > keeps it consistent.
> 
> Yes, these are mainly messages for NetBeans and, as you rightly said,
> it is necessary to maintain uniformity.
> 
> > The messages after "#ifdef NBDEBUG" need no translation, these are
> > for debugging only.
> 
> Fixed it. This is indeed for internal use.
> 
> > Just like messages for internal errors are not translated.
> 
> But in this, let Bram disagree with you.
> Yes, I know your [position](https://github.com/vim/vim/pull/12356#issuecomment-1537539272) on this issue, but there are a few points.
> 
> Firstly, these messages are displayed to the user, which means he must
> understand that something has happened.
> Secondly, not all users speak English at your level, and at my very
> elementary level, too.
> Thirdly, when the interface and messages are in the user's native
> language and suddenly some message appears in a language that he does
> not understand, and even the program does not work as he expects, then
> this, at least, confuses him, if not stupor.
> 
> But when it is clearly and clearly written in the message in his
> native language that this is an internal error and some explanations
> are given, then he perceives it normally. And at the same time he
> understands that it wasn't him who did something wrong there, but a
> really serious problem happened and calmly writes an bug report and
> sends it to the developer. Well, or addresses this question to someone
> who understands.
> 
> Well, that's something like that.

The internal messages almost never show up.  When one does show up then
it's not something the user can do something about, it's not like a
wrong option value or scrypt typo.  The only thing an average user can
do is ask on the mailing list or open an issue.  For that the message
doesn't need to be translated.

One thing I have been thinking about is to add a remark about what to
do, and that remark can be translated.  Currently it's a bit
inconsistent, some internal messages start with "INTERNAL: ", but quite
a few don't.  Some messages are used both as a normal error message and
as an internal message.  We should remove "INTERNAL: " from the messages
and add an extra message in iemsg() and siemsg().  We could point to the
help in that message (but the help usually isn't translated...).

-- 
hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by RestorerZ** [comment]
> One thing I have been thinking about is to add a remark about what to do, and that remark can be translated. Currently it's a bit inconsistent, some internal messages start with "INTERNAL: ", but quite a few don't. Some messages are used both as a normal error message and as an internal message. We should remove "INTERNAL: " from the messages and add an extra message in iemsg() and siemsg().

Yes, Bram, if there was some kind of message like **_"Internal error. Inform the developer about it"_**, then it would be enough and understandable to the user. Everything else really doesn't concern him.


> We could point to the help in that message (but the help usually isn't translated...).

Unfortunately, this is the case, the translation of the help is very lacking. The full translation is available only in French and Serbian. User Manual in Japanese, Polish and Italian.
Once upon a time there was a more or less complete translation of documentation into Russian from Vasily Ragozin.

**Comment by brammool** [comment]
> > One thing I have been thinking about is to add a remark about what
> > to do, and that remark can be translated. Currently it's a bit
> > inconsistent, some internal messages start with "INTERNAL: ", but
> > quite a few don't. Some messages are used both as a normal error
> > message and as an internal message. We should remove "INTERNAL: "
> > from the messages and add an extra message in iemsg() and siemsg().
> 
> Yes, Bram, if there was some kind of message like **_"Internal error.
> Inform the developer about it"_**, then it would be enough and
> understandable to the user. Everything else really doesn't concern
> him.

I have made a patch for this, since it was fairly easy.  Some tests had
to be adjusted for the new message.


-- 
hundred-and-one symptoms of being an internet addict:
74. Your most erotic dreams are about cybersex

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
