### PR TITLE
Add racket filetype detection

### LINKED ISSUE #12162: [filetype] Racket files are detected as Scheme, even though vim supports ft=racket out of the box
### Steps to reproduce

1. vim -u DEFAULTS
2. :e test.rkt
3. set ft?

### Expected behaviour

filetype=racket

### Version of Vim

9.0.1337

### Environment

OS: Arch Linux
Terminal: kitty
TERM: xterm-kitty
Shell: zsh 5.9

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by kakig**
Fixes #12162.

### CODE REVIEW

**Comment by benknoble** [comment]
Someone who actually has to deal with this file should weigh in, but given that the whole file isn't alphabetical, it might be worth keeping the Scheme and Racket lines close together (as Racket descends from and includes implementations of Scheme).

**Comment by amaanq** [comment]
I tend to keep them as alphabetized as I can when making filetype detection changes

**Comment by kakig** [comment]
> I tend to keep them as alphabetized as I can when making filetype detection changes

Yes, the changes are already alphabetized.

**Comment by benknoble** [comment]
You'll have to update the filetype tests to fix the build error.

**Comment by kakig** [comment]
Sorry about that, and thanks for the guidance. It is my first time contributing to a larger project. The errors should be fixed now.

**Comment by benknoble** [comment]
No worries! Just figured I'd give you a nudge for the workflow errors.

**Pull request closed without merging**
