### PR TITLE
runtime/syntax/gitconfig.vim: do not change iskeyword

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/vim/vim/issues/2810#issuecomment-382127299

/cc @tpope (assuming that you prefer this over git-send-email)

### CODE REVIEW

**Comment by tpope** [comment]
Digits should be allowed.

**Comment by blueyed** [comment]
Thanks, amended.

**Comment by chrisbra** [comment]
Alternatively, instead of using `:setlocal iskeyword` you can use `:syntax iskeyword`. That has been added specifically for changing the 'iskeyword' setting only for the syntax files without affecting other things in Vim. That means you would not have to change your syntax regular expressions. See `:h :syn-iskeyword`

**Comment by chrisbra** [comment]
I think this has been merged by the upstream @tpope 
So I am closing this. 

@tpope  you might want to send an updated version to Bram for distribution with Vim 8.1

**Comment by tpope** [comment]
Unfortunately Vim 8.1 already dropped before your comment. I'll aim to avoid waiting till the last minute with Vim 8.2.

**Comment by chrisbra** [comment]
> Unfortunately Vim 8.1 already dropped before your comment. I'll aim to avoid waiting till the last minute with Vim 8.2.

@tpope You can always send updates to Bram whenever you think they should be included. Bram updates runtime files every once in a while and not just before a release.

**Pull request closed without merging**
