### PR TITLE
+textprop feature should not contain popup windows.  add +popupwin feature.

### PR DESCRIPTION
**Pull request by rbtnn**
`+textprop` feature contains Text properties and Popup windows now.  But I think It is unreasonable that `+textprop` feature reminiscent of  Popup windows.

### CODE REVIEW

**Comment by brammool** [comment]
We've been trying to simplify the #ifdefs in the code.  I don't know a good reason to include popup windows and not text properties, or the other way around.  It's true that the FEAT_TEXT_PROP name is misleading.  But what would be better without making it very long?  FEAT_PROP_POPUP ?  FEAT_TXTPROP_POPWIN ?

**Comment by rbtnn** [comment]
> We've been trying to simplify the #ifdefs in the code. 

I got it.

> But what would be better without making it very long? FEAT_PROP_POPUP ? FEAT_TXTPROP_POPWIN ?

I think that even if it is long,  prefer FEAT_TXTPROP_POPWIN  to FEAT_PROP_POPUP and `+textprop/popupwin` to `+textprop`

**Comment by rbtnn** [comment]
I found a typo.  `POPUP_NONE` →　`USEPOPUP_NONE`
If not merge this PR, please fix it.

https://github.com/vim/vim/blob/master/src/popupmenu.c#L764

**Comment by brammool** [comment]
Naruhiko Nishino wrote:

> > We've been trying to simplify the #ifdefs in the code. 
> 
> I got it.
> 
> > But what would be better without making it very long? FEAT_PROP_POPUP ? FEAT_TXTPROP_POPWIN ?
> 
> I think that even if it is long,  prefer FEAT_TXTPROP_POPWIN  to FEAT_PROP_POPUP and `+textprop` to `+textprop/popupwin`

I suppose FEAT_PROP_POPUP is good enough.  Can you update the pull
request for that?

We could define both +textprop and +popupwin.  This is user visible.
Adding a slash is unusual.

-- 
hundred-and-one symptoms of being an internet addict:
155. You forget to eat because you're too busy surfing the net.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Naruhiko Nishino wrote:

> I found a typo.  `POPUP_NONE` →　`USEPOPUP_NONE`
> If not merge this PR, please fix it.
> 
> https://github.com/vim/vim/blob/master/src/popupmenu.c#L764

Thanks for noticing, I'll include the fix.

-- 
hundred-and-one symptoms of being an internet addict:
154. You fondle your mouse.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rbtnn** [comment]
>I suppose FEAT_PROP_POPUP is good enough.  Can you update the pull
>request for that?
>
>We could define both +textprop and +popupwin.  This is user visible.
>Adding a slash is unusual.

I got it. I'll update it.

**Comment by rbtnn** [comment]
>>I suppose FEAT_PROP_POPUP is good enough. Can you update the pull
>>request for that?
>>
>>We could define both +textprop and +popupwin. This is user visible.
>>Adding a slash is unusual.
>
>I got it. I'll update it.

I create new PR for this and close this PR. 

https://github.com/vim/vim/pull/5291

**Pull request closed without merging**
