### PR TITLE
Simplify creating nv_cmdidxs.h

### PR DESCRIPTION
**Pull request by ichizok**
* Extract `nv_cmds[]` from normal.c and move to nv_cmds.h
* Add create_nvcmdidxs.c as the helper program for `make nvcmdidxs`; create_nvcmdidxs.c shows all `nv_cmds[].cmdchar`

Enable to update nv_cmdidxs.h without building vim itself.

### CODE REVIEW

**Comment by brammool** [comment]
Thanks, it does make building simpler.

Is there a reason to go back from Vim9 to legacy syntax for the script?

**Comment by ichizok** [comment]
> Is there a reason to go back from Vim9 to legacy syntax for the script?

To able to do `make nvcmdidxs` by the not-latest vim as distribution-provided (e.g. Ubuntu-20.04 provides Vim 8.1.2269 now and cannot use vim9script).

**Comment by ichizok** [comment]
And, currently it seems vim9 cannot convert `list<..>` to `list<dict<...>>` by `map()`.

```vim
var nv_cmdtbl = systemlist(cmd)->map((i, ch) => {idx: i, cmdchar: ch})
```
```
E488: Trailing characters: idx: i, cmdchar: ch})
```

**Comment by lacygoill** [comment]
> And, currently it seems vim9 cannot convert list<..> to list<dict<...>> by map().

Maybe the error message could be improved, but the issue is that if the body of a lambda starts with `{`, it's parsed as a block; not as a dictionary.

To tell Vim to parse the body as a dictionary, the latter must be surrounded with parentheses.

    var nv_cmdtbl = systemlist(cmd)->map((i, ch) => ({idx: i, cmdchar: ch}))
                                                    ^                     ^

See [`:help vim9-curly`](https://vimhelp.org/vim9.txt.html#vim9-curly).

**Comment by ichizok** [comment]
> > And, currently it seems vim9 cannot convert list<..> to list<dict<...>> by map().
> 
> Maybe the error message could be improved, but the issue is that if the body of a lambda starts with `{`, it's parsed as a block; not as a dictionary.
> 
> To tell Vim to parse the body as a dictionary, the latter must be surrounded with parentheses.
> 
> ```
> var nv_cmdtbl = systemlist(cmd)->map((i, ch) => ({idx: i, cmdchar: ch}))
>                                                 ^                     ^
> ```
> 
> See [`:help vim9-curly`](https://vimhelp.org/vim9.txt.html#vim9-curly).

I missed it... Thank you.

**Pull request closed without merging**
