### PR TITLE
Add command to filter quickfix entries

### PR DESCRIPTION
**Pull request by yegappan**
Add the ":cfilter" and ":lfilter" commands to filter entries matching a
pattern from the quickfix/location list. The :cfilter command creates
a new quickfix list with entries matching the specified regex pattern.
When "!" is supplied, creates a list with entries not matching the pattern.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Wondering why this is needed to be written in C. Implementing this in VimL as a plugin looks far easier then writing it in C: and thus less error-prone and more maintainable.

**Comment by yegappan** [comment]
Many of the existing Vim functionality can be implemented in VimL. But the native
implementation is preferred either because it is optimized or the functionality is
available even if the plugins are not present.

Also, if the cfilter/lfilter commands are implemented in VimL, the commands have to start
with an upper case letter (Cfilter/Lfilter) which will be different from the other native
quickfix commands and difficult to type/remember.

BTW, this patch is in the todo list for some time. I am moving all my outstanding
patches to the github workflow.

**Comment by ZyX-I** [comment]
Upper case letter is a non-issue, one can use `:cnoreabbrev` if it bothers him too much. Optimizing some functionality needs justification: is filtering of actually used long lists that slow? Plugins distributed with Vim are rarely switched off.

Solution written in the C code is harder to extend and harder to maintain. E.g. according to the help, match is performed on the error messages and full path, what the user will do if he wants only one or the other, and match on relative path (BTW, I cannot imagine why would I need both at once and separate matching of these entities)? If that was VimL code I could simply copy it and perform some modifications (and maybe even writing PR then). Altering C code is harder in terms of required qualification and harder to push changes through Bram (if they do anything but fix a bug).

Also there is a replacement: just use regular search in a quickfix buffer. Sometimes this may be more and sometimes less convenient, but this functionality does not require any modifications to the code.

**Comment by Konfekt** [comment]
The `:cnoreabbrev cfilter Cfilter` approach is error prone. See https://github.com/Konfekt/vim-alias for all the edge cases to replicate a first lower case command version of a command properly. And still there  cases, when a `cabbrev` does not cut it, for example if it is following a `|`. Somehow, `|` is part of the abbreviation to be expanded and therefore `|cfilter` does not expand to `|Cfilter`.

As a user, any command implemented in Vim is preferred to a plug-in solution, not only be speed, but because of the large user base, test of time and the entry barrier.

That said,

``` vim
command! -nargs=1 Cfilter call setqflist(filter(getqflist(), 'v:val["text"] =~ <q-args>'))
```

achieves something similar to `:cfilter`. But as long as it is not in Vim, as a user you wonder if this simple code misses out on a million of edge cases.

**Comment by ZyX-I** [comment]
@Konfekt I suggested to use plugins shipped with Vim, not some third-party plugin or a snippet in user vimrc. So user base is the same. Abbreviation/mapping/etc is to be used only by users who cannot stand upper case letter which narrows down a number of edge cases one needs to care about (there normally is some code style that user is following). I do not see how using a shipped-in plugin may affect the entry barrier, in any case most of users do not read documentation from start to end so the source of knowledge are tutorials/advices/SE answers/…, web search or references in related functionality documentation: neither of which is affected by moving `Cfilter` to e.g. `pi_quickfix.txt`.

And what is “test of time”?

**Comment by Konfekt** [comment]
The test of time means that functions in Vim will become more and more stable as time passes by thanks to the large user base. And entry barrier referred to that every code that lands in Vim is thoroughly checked by the gate keepers. 

Both of these apply to plug-ins as well as vim-plugins but these were more about two personal observations: 
- the functions delivered with Vim seem stabler than those in the scripts. In the end, Vimscript depends on those.
- for example changing a plug-in requires reaching out to the maintainer, who sometimes does not reply. Regarding the source code, it seems as if anyone can modify it. 

Here's another issue that Aliases can't cope of: tab-completion of commands. 

Other than that, is there maybe a noticeable speed difference between a the Vim script and C solution? In the end, the `:cfilter` command is most convenient with a long quickfix-list.

**Comment by ZyX-I** [comment]
> The test of time means that functions in Vim will become more and more stable as time passes by thanks to the large user base. And entry barrier referred to that every code that lands in Vim is thoroughly checked by the gate keepers.

I constantly see that new functionality is added and then almost immediately followed by a sequence of bug fix patches, there is a single one official gate keeper (Bram). The same process of stabilizing over time applies to runtime files as well, but if you write code in VimL you are guaranteed to avoid some errors (e.g. double free in this case is a bug in Vim and not your plugin, and it is rare; it is also harder to forget about `free()`; no `malloc` returning NULL to care about; etc).

> the functions delivered with Vim seem stabler than those in the scripts. In the end, Vimscript depends on those.

As anything else, this depends on how often this is used. E.g. racket (mzscheme) bindings were crashing for me for a large period of time and I am not sure they are not crashing currently.

> for example changing a plug-in requires reaching out to the maintainer, who sometimes does not reply. Regarding the source code, it seems as if anyone can modify it.

If he does not reply then you may take over the maintainership. Patches with new functionality done to C code and not plugins tend to stay in todo list for years, procedure of accepting changes to the runtime files is much faster.

> Other than that, is there maybe a noticeable speed difference between a the Vim script and C solution? In the end, the :cfilter command is most convenient with a long quickfix-list.

This needs a proof.

**Comment by brammool** [comment]
I don't think these commands are very useful.  Most likely someone wants to create a user command to perform filtering.  A better option is to add an example of filtering using getqflist() and setqflist() in the help.

**Comment by Konfekt** [comment]
Such as

`````` vim
command! -nargs=1 Cfilter call setqflist(filter(getqflist(), 'v:val["text"] =~ <q-args>'))
``` ?
``````

**Pull request closed without merging**
