### PR TITLE
Implement 'diffref' option, and 'diffmaster'/'diffnomaster' commands

### PR DESCRIPTION
**Pull request by flarn2006**
This is a rewrite of the functionality from pull request #3527. This adds a `diffref` window option, as well as two commands, `:diffmaster` and `:diffnomaster`, which let you set or clear a master window. This has the same effect as setting `diffbuf` in #3527; see that PR for more details.

I've also added help text for the new functionality.

### CODE REVIEW

**Review by tonymec — COMMENTED** [review]
For a boolean option, the opposite of `'diffmaster'` should be `'nodiffmaster'`, not `'diffnomaster'`. Or else, if you create a separate boolean option `'diffnomaster'`, then it will be possible to clear it by `:set nodiffnomaster`.

Best regards,
Tony.

**Comment by flarn2006** [comment]
"diffnomaster" is a command, not an option.

**Comment by flarn2006** [comment]
Thought I fixed the issue I mentioned in #3527, but I'm still running into similar issues as I use it at work. Gonna take a look at it later today.

**Comment by flarn2006** [comment]
Found where the issue is; haven't gotten around to fixing it yet.

**Comment by brammool** [comment]
Had a quick look at this again.
- We should only add the 'diffmaster' option, window-local.
- No need for new commands.
- When setting 'diffmaster', the 'diffmaster' option in other windows of the same tab will be reset.
- There should be a test that clearly shows the effect, a screenshot test in test_diffmode.vim is the best
- When a buffer has 'diffmaster' set it should be possible to recognize this somehow.  An item in the window title and/or statusline is useful, perhaps "[master]".

**Comment by brammool** [comment]
any progress?

**Comment by flarn2006** [comment]
Nah sorry, I haven't looked at this in a while.

**Comment by brammool** [comment]
Closing for lack of activity.  Please reopen when improvements have been made.

**Pull request closed without merging**
