### PR TITLE
suggestion: add a option of close button to popup window

### PR DESCRIPTION
**Pull request by mnishz**
**Is your feature request related something that is currently hard to do? Please describe.**
I'd like to use several popup windows as notification tool, and I don't want the popup windows to close automatically (no 'time' option).
In this situation, it is not easy to close popup window individually.

**Describe the solution you'd like**
Like tab page, add a option of "X" button to close popup window.

**Pros**
* Able to close popup window individually.
* Don't need type (or remember) the command to close popup window.
* Bigginer-friendly?

**Cons**
* User might close popup window accidentally?

**Example**
`:call popup_create('foobar', {'border': [], 'close': 1})`

**Screenshot**

### CODE REVIEW

**Comment by brammool** [comment]
> I'd like to use several popup windows as notification tool, and I
> don't want the popup windows to close automatically (no 'time'
> option).  In this situation, it is not easy to close popup window
> individually.
> 
> Like tab page, add a option of "X" button to close popup window.
> 
> **Pros**
> * Able to close popup window individually.
> * Don't need type (or remember) the command to close popup window.
> * Bigginer-friendly?
> 
> **Cons**
> * User might close popup window accidentally?
> 
> **Example**
> `:call popup_create('foobar', {'border': [], 'close': 1})`
> 
> **Screenshot**
> 

Thanks.  Yes, I have also been thinking of a close button.
Also for a notification that stays up longer.

It does require a top border to exist.  One can make the character used
there empty if needed.  I suppose without a border it's hard to decide
where to put the X.

Another way would be to close the popup on any click in it.
Not with a drag used for selecting text though.
Thus perhaps we should make the "close" option select the kind of close,
instead of just on/off.

-- 
If I tell you "you have a beautiful body", would you hold it against me?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mnishz** [comment]
Thank you for your comment, Bram. I've updated my patch according to your idea. There are 2 options.
* 'close': 'button' -> Closable by clicking 'X' button
* 'close': 'click' -> Closable by clicking content area

Is my understanding correct?

**Comment by brammool** [comment]
Masato Nishihata wrote:

> Thank you for your comment, Bram. I've updated my patch according to your idea. There are 2 options.
> * 'close': 'button' -> Closable by clicking 'X' button
> * 'close': 'click' -> Closable by clicking content area
> 
> Is my understanding correct?
> 

Thanks.  I'll make some further changes and update the help.
If you see something wrong in my changes, please make another pull
request.

-- 
ZOOT:  I'm afraid our life must seem very dull and quiet compared to yours.
       We are but eightscore young blondes, all between sixteen and
       nineteen-and-a-half, cut off in this castle, with no one to protect us.
       Oooh.  It is a lonely life ... bathing ...  dressing ... undressing ...
       making exciting underwear....
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mnishz** [comment]
Thanks a lot! I forgot to write the help... And in fact, my patch includes 3 options, 'button', 'click' and 'none'. 'none' is default value and doesn't change any from current behavior.

Please change my code if style, naming or coding is not appropriate. If needed, I'll add tests for the new code after your changes.

Thank you.

**Pull request closed without merging**
