### PR TITLE
win32: Remove Global IME support

### PR DESCRIPTION
**Pull request by k-takata**
Global IME was introduced into Windows 9x and Windows NT 4.0 to provide
limited Asian character input support.
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa741221(v=vs.85)
Windows 2000 started to provide complete cross-language input support.
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752003(v=vs.85)

We dropped support for Win9x and WinNT4 long time ago. No need to keep
supporting Global IME.

### CODE REVIEW

**Comment by brammool** [comment]
Newer Windows systems have other IME support, but does the old Global IME still work on Windows 7?  Or on Windows XP?

**Comment by k-takata** [comment]
I couldn't find that information. Microsoft closed the download site of Global IME many years ago.
If someone has an installer of it, it might be able to use on XP?

Your official binaries are built without Global IME, and no one complained about it. I assume no one use it.

**Comment by brammool** [comment]
OK, if it has been unsupported for a few years then there is no point in supporting it in Vim.

**Comment by brammool** [comment]
I also updated the help text, not sure if what remains is a good explanation of how IME works now.

**Comment by k-takata** [comment]
I checked your modification. I think it's okay.

**Pull request closed without merging**
