### PR TITLE
debcopyright.vim: support for Files-Included

### PR DESCRIPTION
**Pull request by josch**
Full support (including for components) was finished with this commit: https://salsa.debian.org/debian/devscripts/-/commit/ee90dad7712a7db1e9541b405e065a08d29d62f8

### CODE REVIEW

**Comment by jamessan** [comment]
@josch Could you update the `Last Change` date in the header?

**Comment by josch** [comment]
> @josch Could you update the `Last Change` date in the header?

Thank you, done! :slightly_smiling_face:

**Review by jamessan — APPROVED** [review]
Applied upstream. Thanks!

**Comment by chrisbra** [comment]
thanks both

**Pull request closed without merging**
