### PR TITLE
runtime(yaml): improve syntax highlighting for YAML

### LINKED ISSUE #8234: Syntax coloring for YAML files breaks on some quotes
**Describe the bug**
The syntax coloring for the YAML files messes up the colors in many situations...

**To Reproduce**
Try this YAML text in gvim:
```yml
 name: Get full list of services for {{ inp | join(', ') }}
  register: newservices
  changed_when: False
  check_mode: ansible_check_mode
  command: |-
    xmllint -format -pretty 1 -xpath /Foo/Bar
```

**Expected behavior**
Something similar to (or better than) how GitHub's syntax-coloring code renders it above.

**Screenshots**
Note, how the "text" begins on the second quote -- and never ends:
image

**Environment (please complete the following information):**
 - Vim version 8.2.1110
 - FreeBSD/11
 - GUI

### LINKED ISSUE #10730: Syntax highlighting for long YAML strings is slow
### Steps to reproduce

Run `vim -u NONE +"syntax on" /tmp/foo.yaml` in a terminal emulator.

Middle-click paste the string `{"foo":"barbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbarbar"}`

Pasting will take several seconds.  Note it doesnt happen with `syntax off` or `foo.json` or `foo.txt`.

### Expected behaviour

Fast pasting should work in YAML mode too.

### Version of Vim

Vim 9.0.0000

### Environment

Linux x86_64/glibc
urxvt

### Logs and stack traces

_No response_

### LINKED ISSUE #11517: yaml syntax does not handle \ characters in multiline strings
### Steps to reproduce

Tested with this snippet:

```yaml
---
- hosts: localhost
  vars:
    win_shell: |
      Move-Item -Path "C:\OldPath\*.dat" -Destination "C:\NewPath\"

  tasks:
    - debug:
        msg: "{{win_shell}}"
```

The result is this:
image

### Expected behaviour

The syntax should not count `\` characters as escaping characters in a multiline string,

### Version of Vim

8.2

### Environment

WSL 2.0 - Debian 11.5
Windows Terminal
xterm-256color
zsh

Can be reproduced on other distros

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by itchyny**
This PR fixes various known issues of YAML syntax highlighting.

- Recognize block scalar style to avoid unexpected highlighting by `yamlFlowString` (fix #11517)
- Improve performance of `yamlFlowMappingKey` by allowing execution by the NFA engine (fix #10730)
  - It was intentionally disabled before patterns were optimized by `s:SimplifyToAssumeAllPrintable`.
- Fix detection of flow style mapping indicators (fix #8234).
- Enable highlighting of explicit mapping value indicators and node properties in flow style.

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks, can you please add a syntax test for your changes?

**Comment by itchyny** [comment]
I added a YAML test file and dumps. Here's screenshots for how this PR improves the syntax.
|BEFORE|AFTER|
|--|--|
|before|after|

**Comment by zzzyxwvut** [comment]
@itchyny, there has been some improvement for syntax test  
files that contain wrapped and/or folded lines (see #15150)  
in that no lines (or their parts) should anymore go missing  
from generated screen dump files, provided any such line  
fits a `19x75` window.  Looking at `dumps/yaml.yaml_*.dump`,  
quite a few lines are incomplete or gone right now.  Could  
you please regenerate screen dumps for `input/yaml.yaml.html`  
(this file is missing) in your up-to-date fork repository.  
And if all is well, create a PR with rewritten screen dumps.  
Maybe, publish the input file?

By the way, `yaml.yaml_99.dump` would no longer be created  
for comparison (see #15164), so its current copy should be  
removed.

**Comment by itchyny** [comment]
@zzzyxwvut Sorry, I don't see what to do, probably because I don't still understand what #15150 is intended for. I am not the original author of the YAML syntax file, and I don't mind you change the syntax dump files along with your changes. The input file exists at `runtime/syntax/testdir/input/yaml.yaml`. But if syntax dump generation logic changed and dumps don't match, the tests should fail, shouldn't they?

**Pull request closed without merging**
