### PR TITLE
runtime(cmakecache): add basic syntax support

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by Freed-Wu** [comment]
@bfrg Thanks for you release it as same license as vim!

**Comment by chrisbra** [comment]
@bfreg please ACK if you are fine with including it here.

**Comment by bfrg** [comment]
Yes, I'm okay with including it in Vim. Though, the header of the syntax file should probably be adapted to Vim's code style.

**Comment by chrisbra** [comment]
@Freed-Wu can you please make those changes?

**Comment by Freed-Wu** [comment]
Sorry due to mess of too many PRs.

**Pull request closed without merging**
