### PR TITLE
Some xf86conf keywords are not supported

### PR DESCRIPTION
**Pull request by ObserverOfTime**
Problem:    Some xf86conf keywords are not supported.
Solution:   Add keywords for InputClass match entries.

---

I also removed the reference to the dead URL.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
(I won't assume the maintenance of this file either)

**Comment by brammool** [comment]
Have you tried the email in the header?  It was working last year.

**Comment by ObserverOfTime** [comment]
No, because he's listed as the *former* maintainer.

**Comment by brammool** [comment]
OK, I'll include the changes then.  But please notify David, I don't know if he has a copy somewhere else.

**Pull request closed without merging**
