### PR TITLE
Improved test coverage of window commands

### PR DESCRIPTION
**Pull request by dpelle**
This PR improves test coverage of vim/src/window.c.

### CODE REVIEW

**Comment by dpelle** [comment]
2 remarks about this PR:

1) A test fails on Windows in AppVeyor. I don't really understand why,
but it's a side effect of a totally unrelated test Test_three_windows()
in test_autocmd.vim.  Tests are green on Linux and macOs.  I wonder
why the failure is specific to Windows.

2) I also commented out pieces of the new test Test_window_width()
as despite setting 'winfixwidth', the window width changes (off by 1)
when creating a new window.  It looks like a bug discovered by the new
test. See FIXME comment in Test_window_width().

**Comment by brammool** [comment]
Dominique wrote:

> 2 remarks about this PR:
> 
> 1) A test fails on Windows in AppVeyor. I don't really understand why,
> but it's a side effect of a totally unrelated test Test_three_windows()
> in test_autocmd.vim.  Tests are green on Linux and macOs.  I wonder
> why the failure is specific to Windows.

The last run it failed in Test_window_height().  Hmm, when I run it with
the console Vim the test passes.  With gvim it fails.

Problem is that the buffer list still has Xtestje1, but the file has
been deleted.  When wiping the current buffer Vim takes another buffer
to put in the window, and apparently in this situation it's the Xtestje1
that is leftover from another test.  Wiping that buffer should solve
it...  Hmm, it doesn't.  It appears the timestamp check that happens in
the GUI interferes.  Let's run the autocmd tests separately.

> 2) I also commented out pieces of the new test Test_window_width()
> as despite setting 'winfixwidth', the window width changes (off by 1)
> when creating a new window.  It looks like a bug discovered by the new
> test. See FIXME comment in Test_window_width().

Have you tried doing this by hand?

-- 
If you feel lonely, try schizophrenia.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
Bram Moolenaar wrote

> Dominique wrote:
>
> > 2 remarks about this PR:
> >
> > 1) A test fails on Windows in AppVeyor. I don't really understand why,
> > but it's a side effect of a totally unrelated test Test_three_windows()
> > in test_autocmd.vim. Tests are green on Linux and macOs. I wonder
> > why the failure is specific to Windows.
>
> The last run it failed in Test_window_height(). Hmm, when I run it with
> the console Vim the test passes. With gvim it fails.
>
> Problem is that the buffer list still has Xtestje1, but the file has
> been deleted. When wiping the current buffer Vim takes another buffer
> to put in the window, and apparently in this situation it's the Xtestje1
> that is leftover from another test. Wiping that buffer should solve
> it... Hmm, it doesn't. It appears the timestamp check that happens in
> the GUI interferes. Let's run the autocmd tests separately.
>
> > 2) I also commented out pieces of the new test Test_window_width()
> > as despite setting 'winfixwidth', the window width changes (off by 1)
> > when creating a new window. It looks like a bug discovered by the new
> > test. See FIXME comment in Test_window_width().
>
> Have you tried doing this by hand?

Yes, it's reproducible by hand, with latest vim-8.0.485 and older.
For example, try this:

$ vim -u NONE
:wincmd v
:6 wincmd |
:set winfixwidth
:wincmd v
:echo winwidth(2)

The echo in the last command shows that 2nd window
has a width of 5, whereas I would expect a width of 6.

Dominique

**Comment by brammool** [comment]
Dominique wrote:

> > > 2 remarks about this PR:
> > >
> > > 1) A test fails on Windows in AppVeyor. I don't really understand why,
> > > but it's a side effect of a totally unrelated test Test_three_windows()
> > > in test_autocmd.vim. Tests are green on Linux and macOs. I wonder
> > > why the failure is specific to Windows.
> >
> > The last run it failed in Test_window_height(). Hmm, when I run it with
> > the console Vim the test passes. With gvim it fails.
> >
> > Problem is that the buffer list still has Xtestje1, but the file has
> > been deleted. When wiping the current buffer Vim takes another buffer
> > to put in the window, and apparently in this situation it's the Xtestje1
> > that is leftover from another test. Wiping that buffer should solve
> > it... Hmm, it doesn't. It appears the timestamp check that happens in
> > the GUI interferes. Let's run the autocmd tests separately.
> >
> > > 2) I also commented out pieces of the new test Test_window_width()
> > > as despite setting 'winfixwidth', the window width changes (off by 1)
> > > when creating a new window. It looks like a bug discovered by the new
> > > test. See FIXME comment in Test_window_width().
> >
> > Have you tried doing this by hand?
> 
> Yes, it's reproducible by hand, with latest vim-8.0.485 and older.
> For example, try this:
> 
> $ vim -u NONE
> :wincmd v
> :6 wincmd |
> :set winfixwidth
> :wincmd v
> :echo winwidth(2)
> 
> The echo in the last command shows that 2nd window
> has a width of 5, whereas I would expect a width of 6.

It appears this is a long standing problem.  When setting the width for
a 'winfixwidth' window the newly added separator isn't accounted for.

-- 
"Hit any key to continue" is very confusing when you have two keyboards.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
