### PR TITLE
feat: add godot game engine syntax/ftplugin/indent files

### PR DESCRIPTION
**Pull request by habamax**
Currently vim has detection of gdscript and gdresource files but actual
syntax/indent/ftplugin files are missing.

Additionally, gdshader detection is added to filetype.vim

Files are extracted and simplified from the plugin I maintain: https://github.com/habamax/vim-godot

### CODE REVIEW

**Comment by brammool** [comment]
I made a patch for the filetype recognition.

The syntax file gdresource.vim and gdscript.vim use line continuation, they should set and restore 'cpo'.
I'll add entries to CODEOWNERS

**Comment by habamax** [comment]
Sure I will add it. Actually, I had it in the legacy version of the scripts, but then I "remembered" I was told for vim9script you don't have to save/restore cpo.

**Comment by habamax** [comment]
Oh, those are in syntax files!

**Comment by lacygoill** [comment]
As soon as a script starts with the `:vim9script` command, the usual "save/restore cpo" becomes useless.  It's only needed in legacy scripts.

---

Minor nitpick, but we might want to use `<C-\><C-N>` instead of `<Esc>` in these mappings:

    xmap <silent><buffer><expr> ]] "\<esc>" .. v:count1 .. ']]m>gv'
    xmap <silent><buffer><expr> [[ "\<esc>" .. v:count1 .. '[[m>gv'

This should work:

    xmap <buffer><expr> ]] $'<C-\><C-N>{v:count1}]]m>gv'
    xmap <buffer><expr> [[ $'<C-\><C-N>{v:count1}[[m>gv'

Rationale: In the RHS of a recursive mapping, `<Esc>` can give unexpected results.  For example:
```vim
vim9script
execute("set <F31>=\<Esc>d")
imap <C-B> <Esc>ddi
:0 put =['a', 'b', 'c']
:2
feedkeys("i\<C-B>", 'x')
```
Expected:  The buffer contains these lines:

    a
    c

Actual:  The buffer contains these lines:

    a
    <F31>dib
    c

`<C-\><C-N>` has the same semantics as `<Esc>` but is more reliable:
```vim
vim9script
execute("set <F31>=\<Esc>d")
imap <C-B> <C-\><C-N>ddi
:0 put =['a', 'b', 'c']
:2
feedkeys("i\<C-B>", 'x')
```
    a
    c

Also, I don't think we need `<silent>`, unless the mappings enter the command-line (they don't seem to do that here, but I might be wrong).  And we don't need double quotes and backslashes to encode `<Esc>` in the mappings; mapping commands like `:xmap` understand key notations without.

Again, all of this is nitpicking, but it might make the mappings a little more reliable and less verbose (thus more readable).

**Comment by habamax** [comment]
thx @lacygoill, looks better, will update it

**Pull request closed without merging**
