### PR TITLE
Fix build failure with if_lua

### LINKED ISSUE #12814: No Longer compiles/links on Cygwin w/patch 1719 and --enable-luainterp=dynamic
### Steps to reproduce

1. git clone git@github.com:vim/vim
2. cd vim
3. git checkout v9.0.1719 -b v9.0.1719
4. ./configure --enable-luainterp=dynamic
5. make

Compilation seems to work fine, however, the link fails with the following:

/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x25dd): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x25ea): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x25f5): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2602): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x260f): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x261c): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x265c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x2669): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x2674): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2681): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x268e): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x269b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x289c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x28a9): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x28b4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x28c1): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x28ce): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x28db): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x2aac): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x2ab9): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x2ac4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2ad1): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x2ade): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x2aeb): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2d26): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2d33): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2d3e): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2d4b): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2d5e): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2d6b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2dc6): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2dd3): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2dde): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2deb): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2dfe): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e0b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2e56): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2e63): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2e6e): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2e7b): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e8e): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e9b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x3a44): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x3a51): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x3a5c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x3a69): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x3a7c): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x3a89): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x3ac9): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x3ad6): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x3ae1): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x3aee): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x3afb): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x3b08): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x3fe4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x3ff1): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x3ffc): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x4009): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x401c): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4029): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x4069): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x4076): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x4081): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x408e): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x409b): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x40a8): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x4310): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x431d): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x4328): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x4335): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4348): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4355): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x43c0): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x43cd): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x43d8): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x43e5): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x43f8): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4405): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x4458): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x4465): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x4470): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x447d): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4490): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x449d): undefined reference to `lua_settop'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [Makefile:2062: vim.exe] Error 1
make[1]: Leaving directory '/home/smartin/src/github/vim/src'
make: *** [Makefile:29: first] Error 2

Patch v9.0.1718 and earlier compile and link fine with luainterp enabled dynamically.

Latest version of Cygwin/Windows 11, and lua 5.3.

> gcc --version
gcc (GCC) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> make --version
GNU Make 4.4.1
Built for x86_64-pc-cygwin
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

> ld --version
GNU ld (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

### Expected behaviour

Version v9.0.1718 and earlier compile and link fine with --enable-luainterp=dynamic

The lua changes specific to 1719 clearly aren't completely clean/tested.

### Version of Vim

9.0.1719 (No executable actually compiles)

### Environment

Operating System: Windows 11/Cygwin 64-bit
Terminal: Windows Terminal Preview/Cygwin Mintty, doesn't matter which
Value of $TERM: xterm-256color
Shell: bash

### Logs and stack traces

```shell
link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
  gcc   -L/usr/local/lib -Wl,--as-needed        -o vim.exe objects/alloc.o objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/float.o objects/fold.o objects/getchar.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/list.o objects/locale.o objects/logfile.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/strings.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9class.o objects/vim9cmds.o objects/vim9compile.o objects/vim9execute.o objects/vim9expr.o objects/vim9instr.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o  objects/vterm_encoding.o objects/vterm_keyboard.o objects/vterm_mouse.o objects/vterm_parser.o objects/vterm_pen.o objects/vterm_screen.o objects/vterm_state.o objects/vterm_unicode.o objects/vterm_vterm.o objects/if_lua.o       objects/winclip.o objects/netbeans.o objects/job.o objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o        -lm -lncurses  -lsodium -liconv -lacl -lintl
/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x25dd): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x25ea): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x25f5): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2602): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x260f): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x261c): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x265c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x2669): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x2674): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2681): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x268e): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x269b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x289c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x28a9): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x28b4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x28c1): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x28ce): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x28db): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x2aac): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x2ab9): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x2ac4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x2ad1): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x2ade): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x2aeb): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2d26): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2d33): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2d3e): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2d4b): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2d5e): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2d6b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2dc6): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2dd3): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2dde): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2deb): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2dfe): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e0b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x2e56): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x2e63): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x2e6e): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x2e7b): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e8e): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x2e9b): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x3a44): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x3a51): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x3a5c): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x3a69): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x3a7c): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x3a89): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x3ac9): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x3ad6): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x3ae1): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x3aee): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x3afb): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x3b08): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x3fe4): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x3ff1): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x3ffc): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x4009): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x401c): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4029): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_setudata':
/home/smartin/src/github/vim/src/if_lua.c:89:(.text+0x4069): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:90:(.text+0x4076): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:91:(.text+0x4081): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:92:(.text+0x408e): undefined reference to `lua_pushvalue'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:93:(.text+0x409b): undefined reference to `lua_rawset'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:94:(.text+0x40a8): undefined reference to `lua_settop'
/bin/ld: objects/if_lua.o: in function `luaV_getudata':
/home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x4310): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x431d): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x4328): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x4335): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4348): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4355): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x43c0): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x43cd): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x43d8): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x43e5): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x43f8): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4405): undefined reference to `lua_settop'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:79:(.text+0x4458): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:80:(.text+0x4465): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:81:(.text+0x4470): undefined reference to `lua_pushlightuserdata'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:82:(.text+0x447d): undefined reference to `lua_rawget'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x4490): undefined reference to `lua_rotate'
/bin/ld: /home/smartin/src/github/vim/src/if_lua.c:83:(.text+0x449d): undefined reference to `lua_settop'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [Makefile:2062: vim.exe] Error 1
make[1]: Leaving directory '/home/smartin/src/github/vim/src'
make: *** [Makefile:29: first] Error 2
```

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #12814

### CODE REVIEW

**Comment by zeertzjq** [comment]
The Windows build failures looks strange. `lua_rotate` appears in link errors but it doesn't seem used.

**Comment by jessepav** [comment]
In Lua 5.3, `lua_remove` is a macro that ends up calling `lua_rotate`. Maybe it's compiling against headers from a different version of Lua that it's attempting to link against? I'm not sure how the `--enable-luainterp=dynamic` code searches for a DLL, so that could be a factor too.

**Comment by zeertzjq** [comment]
I guess it should work if these two functions are moved below the `#ifdef DYNAMIC_LUA` block.

**Review by k-takata — APPROVED** [review]
I confirmed this on Windows with lua 5.4 with /dyn.

**Pull request closed without merging**
