### PR TITLE
Add "vs", "Vs" and "CTRL-Vs" to mode() result

### PR DESCRIPTION
**Pull request by zeertzjq**
`mode()` returns `viS` for Visual using v_CTRL-O in Select mode.

### CODE REVIEW

**Comment by brammool** [comment]
Looks like this also adds "ViS" and CTRL-ViS".  that should be documented.

I wonder why adding "iS", the "i" suggests insert mode, but that is not relevant here.
Not sure what would work best, considering any future additions.

**Comment by zeertzjq** [comment]
I'm not very clear about the name convention of `mode()` results.  Does `i` in `niR` and `niV` also mean insert mode?

**Comment by zeertzjq** [comment]
I'm not very clear about the naming convention of `mode()` results. What does `i` mean in `niI`, `niR` and `niV`?

**Comment by zeertzjq** [comment]
I'll change `iS` to `s` first.

**Comment by brammool** [comment]
Using "vs" and friends seems OK.  It's basically Visual mode that was entered from Select mode, which matters for when a command was given, then it falls back to Select mode.

The help can be a bit clearer about this "using |v_CTRL-O|" => "using |v_CTRL-O" from Select mode"

**Pull request closed without merging**
