### PR TITLE
Revert visualbell in vim.exe 16 color mode

### PR DESCRIPTION
**Pull request by ghost**
#11532

16-color visualbell, screen recovery from background color inversion.
I can do it right away, so I did it right away, meow meow.

### CODE REVIEW

**Comment by zewpo** [comment]
Thanks @ntak   
I think this PR is good.   It fixes another thing that I missed.

**Comment by brammool** [comment]
While we are at it: If the condition is false then WriteConsoleOutputAttribute() is not called.  That means "oldattrs" is not used.  Can we then skip ReadConsoleOutputAttribute() as well?  And also not allocate "oldattrs".

Although I wonder, if only FillConsoleOutputAttribute() is invoked to invert the attributes, when are the attributes restored?  And if that works, do we need the code to save and restore the attributes at all?

**Comment by zewpo** [comment]
@brammool  

> when are the attributes restored?

good q, I will investigate.

**Comment by zewpo** [comment]
So, current build from master - in a 16 color mode WCH (Windows Console Host).  It does NOT restore - it just stays reversed color!

unable to test with higher color mode on WCH at the moment.

It does restore for WT.  Not sure why yet - still investigating.

**Comment by zewpo** [comment]
Alright, I've verified and confirm that this PR fixes the color restore problem for the visual bell.   It fixes it everywhere that is currently broken where I can replicate it.  Even in the WCH tgc issue, which I can test now too.

I'm still not sure how it restores in the case it is using tgc - still investigating that.  But, color does restore there too - not sure if related to this PR, or maybe it works via a fork in the control earlier in the logic before it gets to here.  If so, then that might explain the apparent dead code.!?  Still investigating.

PS. I've also worked out the cause of the WCH tgc regression issue - will issue a separate PR for that shortly.  Just mentioning it here because I was actually able to verify and confirm that this PR for visual bell is also fixed in this case too.

**Comment by zewpo** [comment]
> While we are at it: If the condition is false then WriteConsoleOutputAttribute() is not called. That means "oldattrs" is not used. Can we then skip ReadConsoleOutputAttribute() as well? And also not allocate "oldattrs".

I tested this, and yes, it all still works, if we use the same if condition on the Read.    oldattrs are only needed if it is going to write them.   Let me know if you want another PR for this too?

> Although I wonder, if only FillConsoleOutputAttribute() is invoked to invert the attributes, when are the attributes restored? And if that works, do we need the code to save and restore the attributes at all?

yeah, restoring of the oldattr attributes here IS still needed for 16 color mode.   But not needed when color is >= 256,  then the colors are restored by code in term.c.  Actually - which my last PR broke!  I'm about to submit a PR that fixes what I broke in term.c

**Comment by brammool** [comment]
Is this now fixes with Patch 9.0.1235 ?  I adjusted the condition for restoring to only do the work when saving succeeded.
Hopefully that works best.

**Comment by zewpo** [comment]
I confirm that this visual bell fix merged into Patch 9.0.1235 is working well for MS-Console and Win-Terminal apps, ie. both working in 16 color mode as well as termguicolor modes.

And, so, I think the color regressions are mostly OK now.

Still lurking a regression somewhere for screen restore on exit - for the console buffer size and cursor shape don't get restored properly.   I can see an easy way to revert that regression, but that easy-fix then breaks the EOL fix that I did.    I know there is a way to fix both sets of issues, because I see that some projects using libuv manage to do both - just need some time to research how they do it and figure it out properly.

**Comment by zewpo** [comment]
Just to wrap up this thread. PR https://github.com/vim/vim/pull/11882 completes fixing all of the regressions that I mentioned above.

**Comment by brammool** [comment]
@ntak - please close this if the included patches cover what is in this PR.
Otherwise, please sync and let us know what's missing.

**Pull request closed without merging**
