### PR TITLE
[#1665] Add "Apprentice" colorscheme as per issue #1665

### PR DESCRIPTION
**Pull request by romainl**
Hello, as [per issue #1665](https://github.com/vim/vim/issues/1665) and [Christian Brabandt's request](https://github.com/romainl/Apprentice/issues/31) I submit my colorscheme [Apprentice](https://github.com/romainl/Apprentice) for inclusion in the base distribution.

### CODE REVIEW

**Comment by romainl** [comment]
FWIW, `Test_cmdline_complete_user_cmd()` had:

* "blue" hardcoded for the first colorscheme,
* "blue" hardcoded for the first colorscheme starting with a "b".

Now, the expected values are dynamically built from the content of `$VIMRUNTIME/colors` so that we can add colorschemes that come *before* "blue" (like "apprentice" or "balrog") without worrying about broken builds.

**Comment by lunacookies** [comment]
Why close the issue @romainl?

**Comment by romainl** [comment]
@arzg because it was messy. https://github.com/vim/vim/pull/1964 is cleaner IMO.

**Comment by lunacookies** [comment]
@romainl Yeah, I see that now. Thanks!

**Pull request closed without merging**
