### PR TITLE
Support for matching multiple words

### PR DESCRIPTION
**Pull request by yegappan**
When a pattern has multiple words, fuzzy match each word (in any order)
and return the matching strings sorted by the match score.

### CODE REVIEW

**Comment by brammool** [comment]
Hmm, so if I match "one two" on a text that contains "two one", it stil matches?  Isn't that a bit unexpected?  If I would match "one_two" then it would not match "two_one", right?  Thus we are making white space very special.  Not sure if that is the goal.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Oct 18, 2020 at 6:14 AM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:
>
> Hmm, so if I match "one two" on a text that contains "two one", it
> stil matches? Isn't that a bit unexpected?
>

Yes. If you search for "one two", it will match both "one two" and
"two one". Of course, the "one two" match will score higher than
"two one". This is useful, because the user then doesn't need to
know the order in which the words occur in the text.

The popular fuzzy matching tools like fzf does support this type
of matching. Also this feature was asked by several users.

>
> If I would match "one_two" then it would not match "two_one", right?
> Thus we are making white space very special. Not sure if that is the
> goal.
>

Yes. The white space separated text is treated as separate words.
Each word is fuzzy matched separately.

Regards,
Yegappan

**Comment by bfrg** [comment]
Wouldn't it be better to make this optional? How can we fuzzy search for a literal white space character (not uncommon in file paths on Windows)?

**Comment by vim-ml** [comment]
Hi,

On Sun, Oct 18, 2020 at 1:16 PM bfrg <vim-dev-github@256bit.org> wrote:

> Wouldn't it be better to make this optional? How can we fuzzy search for a
> literal white space character (not uncommon in file paths on Windows)?
>
>
> A character after a space is given an additional bonus score. So when you
search
for a file path with space using a pattern that contains space, the file
path with the
space will match first because of the higher score compared to a file path
without
space in it.

- Yegappan

**Comment by brammool** [comment]
We already have the optional {dict} argument.  How about adding an item in there to disallow reordering words? 
Naming it isn't so easy, "keep order" has a completely different meaning.  Perhaps "sequential"?

**Comment by vim-ml** [comment]
On 2020-10-19, Bram Moolenaar wrote:
> We already have the optional {dict} argument. How about adding an item in there
> to disallow reordering words?
> Naming it isn't so easy, "keep order" has a completely different meaning.
> Perhaps "sequential"?

"Retain order"?  "Keep sequence"?  Just "sequential" doesn't convey
the meaning very well, at least not to me.

Regards,
Gary

**Comment by lacygoill** [comment]
This is a welcome addition.  Emulating this feature in Vim script was not trivial, and time-consuming.  I've made a brief test, and it seems to work.  However, I've noticed that the `matchseq` key is ignored when filtering a list of dictionaries instead of a list of strings.

Here is a test which currently fails, while I think it should pass:

    vim9script
    [#{text: 'one two'}, #{text: 'two one'}]
      ->matchfuzzy('two one', #{key: 'text', matchseq: true})
      ->assert_equal([{'text': 'two one'}])

**Comment by lacygoill** [comment]
> Emulating this feature in Vim script was not trivial, and time-consuming.

Just to give an idea.  Before the patch:

    vim9script

    def Permutations(l: list<string>): list<list<string>>
        if len(l) == 0
            return [[]]
        endif
        var ret = []
        for sublistPermutation in Permutations(l[1:])
            for permutation in InsertItemAtAllPositions(l[0], sublistPermutation)
                ret += [permutation]
            endfor
        endfor
        return ret
    enddef

    def InsertItemAtAllPositions(item: string, l: list<string>): list<list<string>>
        var ret = []
        for i in range(len(l) + 1)
            ret += [ (i == 0 ? [] : l[0 : i - 1]) + [item] + l[i : ] ]
        endfor
        return ret
    enddef

    var matchfuzzypos: list<any>
    var filtered_source: list<dict<string>>
    var pos: list<list<number>>

    var tokens = split('one two three')
    g:source = ['...']
    if len(tokens) >= 4
        var rest = tokens[2:]->join()->substitute('\s\+', '', 'g')
        tokens = [tokens[0], tokens[1], rest]
    endif

    matchfuzzypos = tokens
        ->Permutations()
        ->map({_, v -> join(v, '')})
        ->map({_, v -> matchfuzzypos(g:source, v, #{key: 'text'})})
        ->reduce({a, v -> [a[0] + v[0], a[1] + v[1]]})

After the patch:

    vim9script
    var source = ['...']
    var filtered_source: list<dict<string>>
    var pos: list<list<number>>
    [filtered_source, pos] = matchfuzzypos(source, 'one two three', #{key: 'text'})

**Comment by lacygoill** [comment]
I've noticed something else, although I'm not sure whether it could or should be changed.

When `matchfuzzy*()` filters a sequence of words, it is allowed to have some overlapping between the positions of 2 different words.

For example:

    echo matchfuzzy(['ftplugin-docs'], 'fun undo')
    ['ftplugin-docs']

`fun` has been matched on these positions:

    v   v  v
    ftplugin-docs

`undo` has been matched on these positions:

    ftplugin-docs
        ^  ^ ^^

If we place the two sets of positions on top of each other, we can see that the start of the second set starts before the end of the first one:

    v   v  v
    ftplugin-docs
        ^  ^ ^^

Note that `fzf(1)` does the same thing, so maybe that's what people expect (I don't; I would expect overlapping to be disallowed).  I suspect that changing this would make the performance drastically decrease; if so, forget about this post.

**Comment by lacygoill** [comment]
> I don't; I would expect overlapping to be disallowed

Although, if the overlapping matches are scored lower than the non-overlapping ones, that's not an issue.

**Comment by vim-ml** [comment]
Hi,

On Tue, Oct 20, 2020 at 1:03 AM lacygoill <vim-dev-github@256bit.org> wrote:

> This is a welcome addition. Emulating this feature in Vim script was not
> trivial, and time-consuming. I've made a brief test, and it seems to work.
> However, I've noticed that the matchseq key is ignored when filtering a
> list of dictionaries instead of a list of strings.
>
> Here is a test which currently fails, while I think it should pass:
>
> vim9script
> [#{text: 'one two'}, #{text: 'two one'}]
>   ->matchfuzzy('two one', #{key: 'text', matchseq: true})
>   ->assert_equal([{'text': 'two one'}])
>
>
>
Thanks for reporting this issue. I have updated the PR with a fix for this.

Regards,
Yegappan

**Comment by vim-ml** [comment]
Hi,

On Tue, Oct 20, 2020 at 1:32 AM lacygoill <vim-dev-github@256bit.org> wrote:

> I've noticed something else, although I'm not sure whether it could or
> should be changed.
>
> When matchfuzzy*() filters a sequence of words, it is allowed to have
> some overlapping between the positions of 2 different words.
>
> For example:
>
> echo matchfuzzy(['ftplugin-docs'], 'fun undo')
> ['ftplugin-docs']
>
> fun has been matched on these positions:
>
> v   v  v
> ftplugin-docs
>
> undo has been matched on these positions:
>
> ftplugin-docs
>     ^  ^ ^^
>
> If we place the two sets of positions on top of each other, we can see
> that the start of the second set starts before the end of the first one:
>
> v   v  v
> ftplugin-docs
>     ^  ^ ^^
>
> Note that fzf(1) does the same thing, so maybe that's what people expect
> (I don't; I would expect overlapping to be disallowed). I suspect that
> changing this would make the performance drastically decrease; if so,
> forget about this post.
>
>
>
Yes. Each word in the search pattern is separately fuzzy matched from the
start
of the text. So you may have overlapping matches. As you have already
observed, fzf also uses a similar search algorithm.

Regards,
Yegappan

**Comment by gdupras** [comment]
What is considered a "word"? Does this take into account 'iskeyword'?

**Comment by vim-ml** [comment]
Hi,

On Tue, Oct 20, 2020 at 5:20 AM ProgMetalSlug <vim-dev-github@256bit.org>
wrote:

> What is considered a "word"? Does this take into account 'iskeyword'?
>
>
>
Currently the matchffuzy() function considers a series of characters
separated by white space (space character or a tab) to be a "word".
It doesn't consider characters not in 'iskeyword' to be a word separator.

- Yegappan

**Comment by brammool** [comment]
Are there any open remarks?  Otherwise, let me know when this is ready to include.

**Comment by vim-ml** [comment]
Hi Bram,

On Fri, Oct 23, 2020 at 3:39 AM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

> Are there any open remarks? Otherwise, let me know when this is ready to
> include.
>
>
>
No. There are no open remarks about this change. This is ready
to be included.

Regards,
Yegappan

**Pull request closed without merging**
