### PR TITLE
python close,isatty,readable,seekable,writable for vim.message …

### PR DESCRIPTION
**Pull request by rpuntaie**
… to avoid AttributeError 'vim.message' object has no attribute 'isatty'

### CODE REVIEW

**Comment by chrisbra** [comment]
Note that this fails some tests.

**Comment by rpuntaie** [comment]
Tests succeed now. But although I've added some extra tests, coverage has decreased by 0.01% to 58.091%. Is this a problem?

**Comment by kdart** [comment]
@rpuntaie Since you've been in that code could you please also add the "closed" attribute? I'm getting a similar error from some module trying to get the "closed" attribute on vim.message.

**Comment by rpuntaie** [comment]
Yeah, I'll take care of that.

**Comment by kdart** [comment]
Cool, thanks!

**Pull request closed without merging**
