### PR TITLE
fix scrolling in terminal

### LINKED ISSUE #1982: scrolling in terminal make flicker
after [patch 8.0.0938](https://github.com/vim/vim/commit/6bb18a878cc4cc79cdca4b7497367e59a90125e7)

## master/HEAD
terminal

## without 8.0.0938
terminal1

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 799c656b0..ee5be4433 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1500,6 +1500,7 @@ handle_moverect(VTermRect dest, VTermRect src, void *user)
     term_T	*term = (term_T *)user;
     win_T	*wp;
 
+#if 0
     if (dest.start_col == src.start_col
 	    && dest.end_col == src.end_col
 	    && dest.start_row < src.start_row)
@@ -1510,6 +1511,7 @@ handle_moverect(VTermRect dest, VTermRect src, void *user)
 		win_del_lines(wp, dest.start_row,
 				 src.start_row - dest.start_row, FALSE, FALSE);
 	}
+#endif
     redraw_buf_later(term->tl_buffer, NOT_VALID);
     return 1;
 }
```

### PR DESCRIPTION
**Pull request by mattn**
close #1982

### CODE REVIEW

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> close #1982

Can you please give a better explanation?


-- 
hundred-and-one symptoms of being an internet addict:
6. You refuse to go to a vacation spot with no electricity and no phone lines.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
Calling win_del_lines is heavy when scroll-up many lines. It can be skipped.

**Comment by mattn** [comment]
The reason of flicker is that the time-span of scrolling is larger than the time span of redrawing new line text at bottom. The most of frames that user seeing while scrolling are empty lines in the screen not drawn texts.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> The reason of flicker is that the time-span of scrolling is larger
> than the time span of redrawing new line text at bottom. The most of
> frames that user seeing while scrolling are empty lines in the screen
> not drawn texts.

I had to go through some code to find what this does.  It basically
disabled win_do_lines().  Thus no scrolling is actually done.  This
makes the win_del_lines() call ineffective.

The scrolling is very useful when redrawing is slow, e.g. with a slower
connection and fast graphics.

I guess that it currently scrolls one line at a time, thus skipping this
when scrolling more than one line probably doesn't make a difference.

We could have this depend on the type of terminal.

Or we could not scroll right away, but remember the number of lines to
be scrolled until actually redrawing text.  Then we can decide to scroll
only if there are few lines to scroll.

-- 
hundred-and-one symptoms of being an internet addict:
16. You step out of your room and realize that your parents have moved and
    you don't have a clue when it happened.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Without @mattn's patch, scrolling is terribly slow on Win32 GUI and causes flickering.
Executing `type eval.c` without the patch is more than 10x slower than with the patch.
I also tested `type eval.c` or `cat eval.c` on Win32 CUI and Cygwin:

|               |Win32 GUI      |Win32 CUI      |Cygwin         |
|---------------|---------------|---------------|---------------|
|without PR#2010|> 10 sec (F)   |~ 2 sec (F)    | ~ 1 sec (F)   |
|with PR#2010   |< 1 sec (N)    |~ 1 sec (N)    | ~ 1 sec (N)   |

F: Flicker, N: No flicker

**Comment by k-takata** [comment]
How about the following patch? (Suggested by @ichizok)

```diff
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -1912,6 +1912,11 @@ handle_moverect(VTermRect dest, VTermRec
 	VTermColor  fg, bg;
 	VTermScreenCellAttrs attr;
 	int	    clear_attr;
+	int	    disable_redraw = p_tf
+#ifdef FEAT_GUI
+					    || gui.in_use
+#endif
+					    ;
 
 	/* Set the color to clear lines with. */
 	vterm_state_get_default_colors(vterm_obtain_state(term->tl_vterm),
@@ -1919,6 +1924,8 @@ handle_moverect(VTermRect dest, VTermRec
 	vim_memset(&attr, 0, sizeof(attr));
 	clear_attr = cell2attr(attr, fg, bg);
 
+	if (disable_redraw)
+	    ++RedrawingDisabled;
 	FOR_ALL_WINDOWS(wp)
 	{
 	    if (wp->w_buffer == term->tl_buffer)
@@ -1926,6 +1933,8 @@ handle_moverect(VTermRect dest, VTermRec
 				 src.start_row - dest.start_row, FALSE, FALSE,
 				 clear_attr);
 	}
+	if (disable_redraw)
+	    --RedrawingDisabled;
     }
 
     term->tl_dirty_row_start = MIN(term->tl_dirty_row_start, dest.start_row);
```

**Comment by brammool** [comment]
Ken Takata wrote:

> How about the following patch? (Suggested by @ichizok)
> 
> ```diff
> --- a/src/terminal.c
> +++ b/src/terminal.c
> @@ -1912,6 +1912,11 @@ handle_moverect(VTermRect dest, VTermRec
>  	VTermColor  fg, bg;
>  	VTermScreenCellAttrs attr;
>  	int	    clear_attr;
> +	int	    disable_redraw = p_tf
> +#ifdef FEAT_GUI
> +					    || gui.in_use
> +#endif
> +					    ;
>  
>  	/* Set the color to clear lines with. */
>  	vterm_state_get_default_colors(vterm_obtain_state(term->tl_vterm),
> @@ -1919,6 +1924,8 @@ handle_moverect(VTermRect dest, VTermRec
>  	vim_memset(&attr, 0, sizeof(attr));
>  	clear_attr = cell2attr(attr, fg, bg);
>  
> +	if (disable_redraw)
> +	    ++RedrawingDisabled;
>  	FOR_ALL_WINDOWS(wp)
>  	{
>  	    if (wp->w_buffer == term->tl_buffer)
> @@ -1926,6 +1933,8 @@ handle_moverect(VTermRect dest, VTermRec
>  				 src.start_row - dest.start_row, FALSE, FALSE,
>  				 clear_attr);
>  	}
> +	if (disable_redraw)
> +	    --RedrawingDisabled;
>      }
>  
>      term->tl_dirty_row_start = MIN(term->tl_dirty_row_start, dest.start_row);
> ```

This deserves an explanation.

-- 
hundred-and-one symptoms of being an internet addict:
268. You get up in the morning and go online before getting your coffee.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
From your previous comment,

> The scrolling is very useful when redrawing is slow, e.g. with a slower connection and fast graphics.

but this is not the case (at least) on Windows GUI/CUI and Cygwin.
I think it's better to disable redrawing on GUI or when 'ttyfast' is set.

**Comment by brammool** [comment]
I am still awaiting an improvement of this patch, at least comments about why this is done.

**Comment by mattn** [comment]
Just because, redrawing whole part is faster than calling win_del_lines on Win32 GUI.

**Comment by brammool** [comment]
Closing this, since it's useless as it is.
An alternative might be skipping the whole part of deleting lines under specific conditions.  It must certainly remain for the terminal (e.g. when using a remote terminal).

**Pull request closed without merging**
