### PR TITLE
Update es tutor

### PR DESCRIPTION
**Pull request by victorhck**
updated spanish tutor and tutor.utf-8 to 1.7 version

### CODE REVIEW

**Comment by brammool** [comment]
Thanks for making the update, I'll include it.
I'll fix the iconv command in the Makefile.

**Comment by victorhck** [comment]
it's a pleasure!!
What would be the next thing to update? Something to start? I would like to help.
Greetings.

**Comment by brammool** [comment]
> it's a pleasure!!
> What would be the next thing to update? Something to start? I would
> like to help.

The translations are quite old.  These are in src/po/es.po.
Instructions are in src/po/README.txt

-- 
From "know your smileys":
 :-X	My lips are sealed

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
it's safe to delete this branch? Or do I have to wait until the changes are included upstream?

> The translations are quite old.  These are in src/po/es.po.

I'll check that.

Greetings.

**Comment by brammool** [comment]
> it's safe to delete this branch? Or do I have to wait until the
> changes are included upstream?

Yes, I have included the patch in my copy.  The next runtime files
update will include this.

> > The translations are quite old.  These are in src/po/es.po.
> 
> I'll check that.

That will be very welcome.

-- 
From "know your smileys":
 :-D	Big smile

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
> Instructions are in src/po/README.txt

Yep! I'm trying to get new strings running

`$ make es  `

And I get this error and nothing happens:

```
Makefile:4: ../auto/config.mk: No such file or directory
make: *** No hay ninguna regla para construir el objetivo '../auto/config.mk'.  Alto.
```
Really there's no such file config.mk in that directory. Only there's a file called `configure`

Greetngs

**Comment by chrisbra** [comment]
you need to have vim build. The Makefile requires that a vim has been build. So run `make` in the `src` directory. That should build you a vim to use.

**Comment by victorhck** [comment]
I'll move this topic to issue #10163

**Pull request closed without merging**
