### PR TITLE
Change to compiler attributes to slightly speed up

### PR DESCRIPTION
**Pull request by dpelle**
Change to compiler attributes to slightly speed up:

- Mark some error logging functions as `__attribute__((cold))`.
  The paths leading to calls of cold functions within code are marked
  as unlikely to help branch prediction mechanism and instruction
  cache hits.
  See: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html

- move `likely` & `unlikely` macros from `vim9execute.c` to `vim.h`
  so they can be used in other places.  I used them in `misc2.c`
  and `vim9compile.c`

- define `ATTRIBUTE_FORMAT_PRINTF` macro in `vim.h` to avoid several
  `#ifdef` wherever `__attribute__((format(printf, ...)))` was  used.
  And mark a few more functions with `ATTRIBUTE_FORMAT_PRINTF`.

sum and indent benchmarks with vim-8.2.3215 clang-12 -O2 luajit before change:
```
           ----- [sum benchmark]-------    ----[indent benchmark] ---
Vim old:   6.041052  6.148449  5.979461    0.574140  0.555627  0.557713
Python:    0.404520  0.380632  0.379797    0.177340  0.152720  0.151942
Lua:       0.004480  0.004244  0.004246    0.129233  0.129052  0.129261
Vim new:   0.129743  0.129349  0.129919    0.082961  0.082470  0.082970
```

sum and indent benchmarks with vim-8.2.3215 clang-12 -O2 luajit after change:
```
           ----- [sum benchmark]-------    ----[indent benchmark] ---
Vim old:   5.975176  5.854275  5.929380    0.568814  0.572812  0.566962
Python:    0.378158  0.374005  0.374160    0.144057  0.145641  0.162473
Lua:       0.004243  0.004250  0.004240    0.128840  0.129053  0.124206
Vim new:   0.122790  0.122743  0.122933    0.078902  0.078892  0.078865
```
It's not a big performance improvement, but vim9 is consistently slightly
faster (~5%) on my i7-7700T CPU @ 2.90GHz. Hopefully it's also faster on
other CPUs.

### CODE REVIEW

**Comment by brammool** [comment]
Dominique wrote:

> Change to compiler attributes to slightly speed up:
> 
> - Mark some error logging functions as `__attribute__((cold))`.
>   The paths leading to calls of cold functions within code are marked
>   as unlikely to help branch prediction mechanism and instruction
>   cache hits.
>   See: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html
> 
> - move `likely` & `unlikely` macros from `vim9execute.c` to `vim.h`
>   so they can be used in other places.  I used them in `misc2.c`
>   and `vim9compile.c`
> 
> - define `ATTRIBUTE_FORMAT_PRINTF` macro in `vim.h` to avoid several
>   `#ifdef` wherever `__attribute__((format(printf, ...)))` was  used.
>   And mark a few more functions with `ATTRIBUTE_FORMAT_PRINTF`.
> 
> sum and indent benchmarks with vim-8.2.3215 clang-12 -O2 luajit before change:
> ```
>            ----- [sum benchmark]-------    ----[indent benchmark] ---
> Vim old:   6.041052  6.148449  5.979461    0.574140  0.555627  0.557713
> Python:    0.404520  0.380632  0.379797    0.177340  0.152720  0.151942
> Lua:       0.004480  0.004244  0.004246    0.129233  0.129052  0.129261
> Vim new:   0.129743  0.129349  0.129919    0.082961  0.082470  0.082970
> ```
> 
> sum and indent benchmarks with vim-8.2.3215 clang-12 -O2 luajit after change:
> ```
>            ----- [sum benchmark]-------    ----[indent benchmark] ---
> Vim old:   5.975176  5.854275  5.929380    0.568814  0.572812  0.566962
> Python:    0.378158  0.374005  0.374160    0.144057  0.145641  0.162473
> Lua:       0.004243  0.004250  0.004240    0.128840  0.129053  0.124206
> Vim new:   0.122790  0.122743  0.122933    0.078902  0.078892  0.078865
> ```
> It's not a big performance improvement, but vim9 is consistently slightly
> faster (~5%) on my i7-7700T CPU @ 2.90GHz. Hopefully it's also faster on
> other CPUs.

Thanks.  Every little bit helps.

I'm wondering, using likely() and unlikely() for every ga_grow() is a
bit of a hassle.  Perhaps we can use a macro:

#define GA_GROW_FAILS(gap, count)  (unlikely(ga_grow(gap, count) == FAIL))
#define GA_GROW_OK(gap, count)  (likely(ga_grow(gap, count) == OK))

Which is also easier to read:

	if (GA_GROW_FAILS(stack, 1))
	    return FAIL;


-- 
hundred-and-one symptoms of being an internet addict:
233. You start dreaming about web pages...in html.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool  wrote:

> I'm wondering, using likely() and unlikely() for every ga_grow() is a
> bit of a hassle.  Perhaps we can use a macro:

Yes, this also bothered me a bit, as I did not want to pollute the code
everywhere with many uses of likely/unlikely.

But I think I found a better way.  In `proto/misc2.pro`, instead of 
having the declaration...
```
int ga_grow(garray_T *gap, int n);
```
... we can have something like this:
```
int ga_grow(garray_T *gap, int n) BUILTIN_EXPECT(OK);
```
... which indicates that the function is likely to return OK.

vim.h would contain something like this:
```
#if defined(__GNUC__) || defined(__clang__)
#define BUILTIN_EXPECT(expr, val) __builtin_expect(expr, val)
else
#else
#define BUILTIN_EXPECT(expr, val)
```

So when a any source file uses `if (ga_grow(...) == OK)`, the
optimizer can see that condition is likely to be true and
`if (ga_grow(....) == FAIL)` is likely to be false, without
having to pollute all uses of `ga_grow(...)`. The same could
be done for several other functions of course.

**Comment by dpelle** [comment]
In my previous comment, I wrote: 

> But I think I found a better way

Ignore my previous comment, I should have tried it before writing my message
as my suggestion does not work.

Your `GA_GROW_OK`, `GA_GROW_FAIL` macro may be OK
but I was hoping for something without having to modified the code
where it's used. I'll think more about it and update my PR later.

**Comment by dpelle** [comment]
I've rebased the PR with vim-8.2.3270 and:
* use the `GA_GROW_FAILS` macro
* remove changes from `misc2.c` and `vim9compile.c`

The performance improvement is now somehow smaller.
vim9 is still slightly faster with the change, but it's only 1.72% faster which is disappointing.
So I'm not sure whether it's worth merging it.
The change to cleanup formatting attribute is good at least.

**Comment by brammool** [comment]
> I've rebased the PR with vim-8.2.3270 and:
> * use the `GA_GROW_FAILS` macro
> * remove changes from `misc2.c` and `vim9compile.c`
> 
> The performance improvement is now somehow smaller.
> vim9 is still slightly faster with the change, but it's only 1.72% faster which is disappointing.
> So I'm not sure whether it's worth merging it.
> The change to cleanup formatting attribute is good at least.

Let me first include the change to the PRINTF macro, that is a nice
cleanup.

Adding the cold attribute in the .pro files won't work, these files are
generated.  Is there another way for this?  What does "cold" do anyway?

For ga_grow() we should use the macro everywhere.  That should hopefully
help a bit.  It is used quite often.


-- 
Not too long ago, unzipping in public was illegal...

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool  asked:

> Adding the cold attribute in the .pro files won't work, these files are
> generated. Is there another way for this? What does "cold" do anyway?

OK.  The `__attribute__((cold))` is documented at:
https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Function-Attributes.html

Quoting the doc:

> The cold attribute is used to inform the compiler that a function is unlikely executed. The function is optimized for size rather than speed and on many targets it is placed into special subsection of the text section so all cold functions appears close together improving code locality of non-cold parts of program. The paths leading to call of cold functions within code are marked as unlikely by the branch prediction mechanism. It is thus useful to mark functions used to handle unlikely conditions, such as perror, as cold to improve optimization of hot functions that do call marked functions in rare occasions. 

The idea is that functions like emsg(...) are not meant to be called often so by declaring cold, cold like this:
```
if (...)
  emsg(...)
```
should do this automatically (without having to add unlikely ourselves):
```
if (unlikely(...))
  emsg(...)
```
... as we tell the compiler that path which include the cold function is meant to execute rarely. Additionally, cold functions are put together to not pollute instruction cache and are optimized for size rather than speed as speed should not matter much for those functions.

But frankly, these attributes don't help as much as I hoped for.

I also tried to use `__attribute__((malloc))`` for functions like `alloc()`, `lalloc()`, `vim_strsave()` (etc.)
but I did could not see any improvement at all with this attribute, so I did not use it in the end. Quoting the doc at the same links as above:

> The malloc attribute is used to tell the compiler that a function may be treated as if any non-NULL pointer it returns cannot alias any other pointer valid when the function returns and that the memory has undefined content. This will often improve optimization. Standard functions with this property include malloc and calloc. realloc-like functions do not have this property as the memory pointed to does not have undefined content.

**Comment by brammool** [comment]
Dominique wrote:

> @brammool  asked:
> 
> > Adding the cold attribute in the .pro files won't work, these files are
> > generated. Is there another way for this? What does "cold" do anyway?
> 
> OK.  The `__attribute__((cold))` is documented at:
> https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Function-Attributes.html
> 
> Quoting the doc:
> 
> > The cold attribute is used to inform the compiler that a function is unlikely executed. The function is optimized for size rather than speed and on many targets it is placed into special subsection of the text section so all cold functions appears close together improving code locality of non-cold parts of program. The paths leading to call of cold functions within code are marked as unlikely by the branch prediction mechanism. It is thus useful to mark functions used to handle unlikely conditions, such as perror, as cold to improve optimization of hot functions that do call marked functions in rare occasions. 
> 
> The idea is that functions like emsg(...) are not meant to be called often so by declaring cold, cold like this:
> ```
> if (...)
>   emsg(...)
> ```
> should do this automatically (without having to add unlikely ourselves):
> ```
> if (unlikely(...))
>   emsg(...)
> ```
> ... as we tell the compiler that path which include the cold function
> is meant to execute rarely. Additionally, cold functions are put
> together to not pollute instruction cache and are optimized for size
> rather than speed as speed should not matter much for those functions.
> 
> But frankly, these attributes don't help as much as I hoped for.

Looking at the docs, I only expect minimal effect of using the "cold"
attribute.  Modern processors with lots of cache already do most of the
optimizing.

> I also tried to use `__attribute__((malloc))`` for functions like
> `alloc()`, `lalloc()`, `vim_strsave()` (etc.)
> but I did could not see any improvement at all with this attribute, so
> I did not use it in the end. Quoting the doc at the same links as
> above:
> 
> > The malloc attribute is used to tell the compiler that a function
> > may be treated as if any non-NULL pointer it returns cannot alias
> > any other pointer valid when the function returns and that the
> > memory has undefined content. This will often improve optimization.
> > Standard functions with this property include malloc and calloc.
> > realloc-like functions do not have this property as the memory
> > pointed to does not have undefined content.

I would expect the branch prediction to be the largest improvement,
which means adding likely() and unlikely() in the right places.
ga_grow() and alloc() failing is the most obvious target, since these
are used a lot and clearly are unlikely to fail.

In the end it's only measurements that can tell the outcome, the rest is
guessing.

Using macros GA_GROW_FAILS() and GA_GROW_OK() doesn't clutter the code
too much, and since there is a chance of improvement I'm OK with using
these.

Perhaps we can do something similar with alloc().

-- 
Q:  Why do ducks have flat feet?
A:  To stamp out forest fires.

Q:  Why do elephants have flat feet?
A:  To stamp out flaming ducks.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
The `ATTRIBUTE_FORMAT_PRINTF` in this PR were already merged.
The remaining changes (likely & unlikely macros...) are not worth integrating after all as the performance improvement is tiny, almost noise.

Closing.

**Pull request closed without merging**
