### PR TITLE
Add functions to get information about buffers, windows and tabpages

### PR DESCRIPTION
**Pull request by yegappan**
Add the getbufinfo(), getwininfo() and gettabinfo() functions to get information about
the list of buffers, windows and tabpages respectively.

### CODE REVIEW

**Comment by brammool** [comment]
Yegappan Lakshmanan wrote:

> Add the getbufinfo(), getwininfo() and gettabinfo() functions to get information about
> the list of buffers, windows and tabpages respectively.

Thanks.

I would like to invite everybody to review these new functions.  Is this
the right way to get the information?

For getbufinfo() I think it would be useful to be able to specify
whether unlisted buffers are included.  That reflects adding "!" to
":buffers".

gettabinfo() should return a list of window IDs.

getwininfo() should accept a window ID instead of a window nr.
See win_getid() and win_id2win().  The window ID is more useful than the
window nr, since the nr changes for every layout change.

I do not like how options are added.  The list will soon get outdated.
It should be possible to go over the list of all options and use the
ones that are local to a window or buffer.

## 

The fastest way to get an engineer to solve a problem is to declare that the
problem is unsolvable.  No engineer can walk away from an unsolvable problem
until it's solved.
                (Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, May 23, 2016 at 12:57 PM, Bram Moolenaar vim-dev-github@256bit.org
wrote:

> Yegappan Lakshmanan wrote:
> 
> > Add the getbufinfo(), getwininfo() and gettabinfo() functions to get
> > information about
> > the list of buffers, windows and tabpages respectively.
> 
> Thanks.
> 
> I would like to invite everybody to review these new functions. Is this
> the right way to get the information?
> 
> For getbufinfo() I think it would be useful to be able to specify
> whether unlisted buffers are included. That reflects adding "!" to
> ":buffers".
> 
> gettabinfo() should return a list of window IDs.
> 
> getwininfo() should accept a window ID instead of a window nr.
> See win_getid() and win_id2win(). The window ID is more useful than the
> window nr, since the nr changes for every layout change.
> 
> I do not like how options are added. The list will soon get outdated.
> It should be possible to go over the list of all options and use the
> ones that are local to a window or buffer.
> 
> I am trying to use the list of options from option.c to get only the window
> local options by checking for (var == VAR_WIN).

I noticed that for the 'statusline' option, the var field in vimoption
is not set to VAR_WIN. For all the other window local options, var is set
to VAR_WIN. Is this intentional or is it a bug?

Thanks,
Yegappan

**Comment by vim-ml** [comment]
Hi,

On Sun, Jun 5, 2016 at 11:46 AM, Yegappan Lakshmanan
yegappanl@gmail.com wrote:

> > Yegappan Lakshmanan wrote:
> > 
> > > Add the getbufinfo(), getwininfo() and gettabinfo() functions to get
> > > information about
> > > the list of buffers, windows and tabpages respectively.
> > 
> > Thanks.
> > 
> > I would like to invite everybody to review these new functions. Is this
> > the right way to get the information?
> > 
> > For getbufinfo() I think it would be useful to be able to specify
> > whether unlisted buffers are included. That reflects adding "!" to
> > ":buffers".
> > 
> > gettabinfo() should return a list of window IDs.
> > 
> > getwininfo() should accept a window ID instead of a window nr.
> > See win_getid() and win_id2win(). The window ID is more useful than the
> > window nr, since the nr changes for every layout change.
> > 
> > I do not like how options are added. The list will soon get outdated.
> > It should be possible to go over the list of all options and use the
> > ones that are local to a window or buffer.
> 
> I am trying to use the list of options from option.c to get only the window
> local options by checking for (var == VAR_WIN).
> 
> I noticed that for the 'statusline' option, the var field in vimoption
> is not set to VAR_WIN. For all the other window local options, var is set
> to VAR_WIN. Is this intentional or is it a bug?

I figured out why the 'statusline' option is set up this way (as it is a
global or local to window option and it is the only option with this
property). You can ignore this question.
- Yegappan

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, May 23, 2016 at 12:57 PM, Bram Moolenaar vim-dev-github@256bit.org
wrote:

> Yegappan Lakshmanan wrote:
> 
> > Add the getbufinfo(), getwininfo() and gettabinfo() functions to get
> > information about
> > the list of buffers, windows and tabpages respectively.
> 
> Thanks.
> 
> I would like to invite everybody to review these new functions. Is this
> the right way to get the information?
> 
> For getbufinfo() I think it would be useful to be able to specify
> whether unlisted buffers are included. That reflects adding "!" to
> ":buffers".

I have added support for filtering the buffer list.

> gettabinfo() should return a list of window IDs.

Done.

> getwininfo() should accept a window ID instead of a window nr.

Done.

> See win_getid() and win_id2win(). The window ID is more useful than the
> window nr, since the nr changes for every layout change.
> 
> I do not like how options are added. The list will soon get outdated.
> It should be possible to go over the list of all options and use the
> ones that are local to a window or buffer.
> 
> Done. I have updated the patch to go through the options[] array
> and get the list of options that are local to a window or buffer.

Regards,
Yegappan

**Comment by yegappan** [comment]
Changes merged into Vim main through patch 7.4.2204.

**Pull request closed without merging**
