### PR TITLE
Add breakpoint as a python keyword

### PR DESCRIPTION
**Pull request by jordan-bonecutter**

### CODE REVIEW

**Comment by gdupras** [comment]
We should preserve alphabetical order of the keywords and builtin functions, as the comments in the syntax file mention. Those comments reference the tables on these pages:

[https://docs.python.org/3/reference/lexical_analysis.html#keywords](https://docs.python.org/3/reference/lexical_analysis.html#keywords)

[https://docs.python.org/3/library/functions.html](https://docs.python.org/3/library/functions.html)

**Comment by brammool** [comment]
@zvezdan

**Comment by zvezdan** [comment]
@brammool Thanks for notifying me.
There are several other keywords we need to add and some other changes to the syntax files that I got contacted about.
Would the author of the change prefer to commit this only or wait for me to send all the changes together.
I can probably do it over the next weekend.

**Comment by jordan-bonecutter** [comment]
I can wait, I've already made my changes locally :) Just thought I may as well submit a PR.

**Comment by zvezdan** [comment]
More importantly, `breakpoint` is **not** a Python keyword.
It can be checked (using Python 3.9):
```
$ python3 -c 'import keyword, pprint; pprint.pprint(keyword.kwlist, compact=True)'
['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async',
 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except',
 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda',
 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with',
 'yield']
```
The `__peg_parser__` is an Easter egg that's going to be removed in Python 3.10, but all others are keywords as documented: https://docs.python.org/3/reference/lexical_analysis.html#keywords (this link is referenced from the syntax file comment too). Obviously, `breakpoint` is not in the list of keywords.

It is a *built-in* function: https://docs.python.org/3/library/functions.html#built-in-functions and can be seen in:
```
$ python3 -c 'import builtins, pprint; pprint.pprint(dir(builtins), compact=True)'
['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException',
 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning',
 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError',
 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning',
 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False',
 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning',
 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError',
 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError',
 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError',
 'NameError', 'None', 'NotADirectoryError', 'NotImplemented',
 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning',
 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError',
 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration',
 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError', 'SystemExit',
 'TabError', 'TimeoutError', 'True', 'TypeError', 'UnboundLocalError',
 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeError',
 'UnicodeTranslateError', 'UnicodeWarning', 'UserWarning', 'ValueError',
 'Warning', 'ZeroDivisionError', '__build_class__', '__debug__', '__doc__',
 '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs',
 'all', 'any', 'ascii', 'bin', 'bool', 'breakpoint', 'bytearray', 'bytes',
 'callable', 'chr', 'classmethod', 'compile', 'complex', 'copyright', 'credits',
 'delattr', 'dict', 'dir', 'divmod', 'enumerate', 'eval', 'exec', 'exit',
 'filter', 'float', 'format', 'frozenset', 'getattr', 'globals', 'hasattr',
 'hash', 'help', 'hex', 'id', 'input', 'int', 'isinstance', 'issubclass',
 'iter', 'len', 'license', 'list', 'locals', 'map', 'max', 'memoryview', 'min',
 'next', 'object', 'oct', 'open', 'ord', 'pow', 'print', 'property', 'quit',
 'range', 'repr', 'reversed', 'round', 'set', 'setattr', 'slice', 'sorted',
 'staticmethod', 'str', 'sum', 'super', 'tuple', 'type', 'vars', 'zip']
```
I'm working on the change right now that will update both *keywords* and *builtins*, and `breakpoint` will be correctly highlighted as a *builtin* after I send it to Bram.

**Comment by zvezdan** [comment]
Just sent https://github.com/vim/vim/pull/7855

**Comment by gdupras** [comment]
Added in 9faec4e.

**Pull request closed without merging**
