### PR TITLE
Add a macro to iterate over all the grow array items

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by brammool** [comment]
Yegappan wrote:

>  * Add a macro to iterate over all the grow array items

Hmm, I'm not sure this is really an improvement.  There isn't any
complexity that the macro takes care of, and it shortens the code only a
little bit.  A disadvantage is that it obscures what the for loop really
does.  And inlining the declaration of the loop variable would require
another macro.

What do others think?

-- 
hundred-and-one symptoms of being an internet addict:
250. You've given up the search for the "perfect woman" and instead,
     sit in front of the PC until you're just too tired to care.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Wed, Mar 8, 2023 at 1:59 PM Bram Moolenaar ***@***.***>
wrote:

>
> Yegappan wrote:
>
> > * Add a macro to iterate over all the grow array items
>
> Hmm, I'm not sure this is really an improvement. There isn't any
> complexity that the macro takes care of, and it shortens the code only a
> little bit. A disadvantage is that it obscures what the for loop really
>

The macro makes it explicit that we are looping over all the items in a
grow array.
So it makes the intent of the loop more apparent (and it is used in many
places).


> does. And inlining the declaration of the loop variable would require
> another macro.
>

Yes.  With this macro, we cannot inline the loop variable declaration.

Regards,
Yegappan


>
> What do others think?
>
>
>

**Comment by chrisbra** [comment]
@yegappan do you still think this is good to include?

**Comment by chrisbra** [comment]
closing because seems to have been staled

**Pull request closed without merging**
