### PR TITLE
new motion gM for middle of line

### PR DESCRIPTION
**Pull request by mattn**
`gm` is middle of screen line. but often want to get middle of line.

### CODE REVIEW

**Comment by brammool** [comment]
Yasuhiro wrote:

> `gm` is middle of screen line. but often want to get middle of line.

Shouldn't this move to the middle of the text?  That matters especially
if there is a lot of indent.
It doesn't really fit in, considering that the other "g" commands use
the screen line for reference, not the text.

-- 
The sooner you fall behind, the more time you'll have to catch up.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
Vim have way to jump to middle of lines for vertical direction. It is 50%. But doesn't have the way for horizontal. For example, there are many text in one line, I often want to jump to middle of line not middle of screen. It is easy if user set wrap option. But someone set nowrap.

> It doesn't really fit in, considering that the other "g" commands use the screen line for reference, not the text.

What motion you expect for this?

**Comment by brammool** [comment]
Yasuhiro wrote:

> Vim have way to jump to middle of lines for vertical direction. It is
> 50%. But doesn't have the way for horizontal. For example, there are
> many text in one line, I often want to jump to middle of line not
> middle of screen. It is easy if user set wrap option. But someone set
> nowrap.

OK, so jumping to halfway the text (counting characters or cells) is
most useful.

Comparing to the % command, gM could also take a count that is used as a
percentage:  20gM  jumps to 20% of the text.  Using the count to go
lines down doesn't seem very useful.

When editing text with very long lines, I would think the percentage can
be quite useful.  Currently one would do 4000|, knowing how long the
text is.

> > It doesn't really fit in, considering that the other "g" commands use the screen line for reference, not the text.
> 
> What motion you expect for this?

I can't think of something better than gM.

-- 
From "know your smileys":
 :-X	My lips are sealed

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
implemented `20gM`.

**Pull request closed without merging**
