### PR TITLE
CI: Append warning flags to CFLAGS

### PR DESCRIPTION
**Pull request by ichizok**
Warning flags "-Wall -Wextra" are useful.

When build v8.2.0529 by gcc (with `-funsigned-char` on amd64):

```
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -Wall -Wextra -funsigned-char -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/vim9script.o vim9script.c
vim9compile.c: In function ‘check_type’:
vim9compile.c:2475:45: warning: comparison is always true due to limited range of data type [-Wtype-limits]
      if (ret == OK && expected->tt_argcount != -1
                                             ^~
```

### CODE REVIEW

**Comment by jamessan** [comment]
> Warning flags "-Wall -Wextra" are useful.

Agreed, but the warnings will likely go missed unless they're turned into errors, so the Travis jobs fail.

**Comment by dpelle** [comment]
@jamessan wrote:

> Agreed, but the warnings will likely go missed unless
> they're turned into errors, so the Travis jobs fail.

Agreed. We can add `-Werror` in CI.
I'd also suggest adding `-Wshadow` which is not implied by `-Wall` and `-Wextra`.
Others?

**Comment by jamessan** [comment]
Looks like the new flags are causing configure to fail.  A good enhancement for the CI would be to dump out either config.log or config.status (I forget which and can't check right now) when configure fails.  That would allow us to see _why_ it's failing.

**Comment by ichizok** [comment]
Changed to overwrite `CFLAGS` in src/auto/config.mk instead of in setting `CFLAGS` in .travis.yml to avoid errors in configuring script.

**Comment by ichizok** [comment]
Fixed the causes of the errors.

**Comment by brammool** [comment]
I'll include it, but I wonder if we can use UNUSED instead of  "(void)user".

**Comment by ichizok** [comment]
> I'll include it, but I wonder if we can use UNUSED instead of "(void)user".

Oh, sorry, I overlooked that "UNUSED" is also defined in vterm_internal.h (assumed that only in vim.h)...
Yes, we can use "UNUSED".

**Comment by jamessan** [comment]
Probably would have been better to not change libvterm at all.  The more unnecessary changes are made, the harder it is to integrate changes from upstream.

**Comment by brammool** [comment]
> Probably would have been better to not change libvterm at all.  The
> more unnecessary changes are made, the harder it is to integrate
> changes from upstream.

Avoiding compiler warnings is not unnecessary.  I perfer to have a
warning-free build, so that actual problems get noticed.

What is "upstream" anyway?  How do I send patch "upstream"?


-- 
(letter from Mark to Mike, about the film's probable certificate)
      For an 'A' we would have to: Lose as many shits as possible; Take Jesus
      Christ out, if possible; Loose "I fart in your general direction"; Lose
      "the oral sex"; Lose "oh, fuck off"; Lose "We make castanets out of your
      testicles"
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
> I perfer to have a warning-free build, so that actual problems get noticed.

Agreed, but that should be done for _Vim's_ code, not a dependency that you happen to bundle with Vim.

> What is "upstream" anyway?

The libvterm project.

> How do I send patch "upstream"?

File a bug at https://launchpad.net/~libvterm/ or email LeoNerd.  I'm not sure why you're asking, as you've discussed things with him before about libvterm.

**Comment by brammool** [comment]
James McCoy wrote:

> > I perfer to have a warning-free build, so that actual problems get noticed.
> 
> Agreed, but that should be done for _Vim's_ code, not a dependency
> that you happen to bundle with Vim.

Paul has insisted to keep using C99 syntax, even though it's a poorly
supported standard.  That means we can't use the code as-is.  Since we
make changes, we also need to fix the warnings.
 
> > What is "upstream" anyway?
> 
> The libvterm project.
> 
> > How do I send patch "upstream"?
> 
> File a bug at https://launchpad.net/~libvterm/ or email LeoNerd.  I'm
> not sure why you're asking, as you've discussed things with him before
> about libvterm.

I know about that, of course, but there is also the neovim copy/fork of
that on github.  The code on launchpad doesn't use git or any tools that
I know, the one from neovim is not the original.  On top of that the
code has diverted, there are improvements on both sides, so now we have
three versions and I don't know what direction to go.  For now, we fix
things in the Vim version.

-- 
The chat program is in public domain.  This is not the GNU public license.
If it breaks then you get to keep both pieces.
		-- Copyright notice for the chat program

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
