### PR TITLE
Fixed indentation of dec_cursor() function of src/misc2.c

### PR DESCRIPTION
**Pull request by kashewnuts**

### CODE REVIEW

**Comment by vim-ml** [comment]
2016年12月8日木曜日 0時22分59秒 UTC+9 kashew_nuts:
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/1313
> 
> Commit Summary
> 
>   fix indent
> 
> 
> File Changes
> 
>   
>     M
>     src/misc2.c
>     (2)
>   
> 
> 
> Patch Links:
> 
>   https://github.com/vim/vim/pull/1313.patch
>   https://github.com/vim/vim/pull/1313.diff
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub

My real name is Kashun Yoshida!

**Comment by jamessan** [comment]
> My real name is Kashun Yoshida!

So update your GitHub profile to show that. :)

**Comment by vim-ml** [comment]
Hi James!

2016-12-8(Thu) 1:01:15 UTC+9 James McCoy:
> My real name is Kashun Yoshida!
> 
> 
> So update your GitHub profile to show that. :)

It maybe true.
However, I have not registered my real name on GitHub, but Bram has recognized that Github's h-east is Hirohito Higashi.
Probably, I think that he judge by e-mail signature.

--
Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by brammool** [comment]
I'll include it, thanks.  I won't send out a separate patch though, will tag along with the next change to this file.

**Pull request closed without merging**
