### PR TITLE
Add findcommand() function

### PR DESCRIPTION
**Pull request by arp242**
Right now there is no way to know which shortcut commands refer to which
commands. This adds findcommand() to solve that.

Context: I made a little VimScript to show the help for the command you
typed: pressing <F1> while you typed ":syntax" shows the help for
:syntax. But I'd also like this to work for all the shortcut commands,
which is hard without this patch, especially if you want it to be a bit
smarter (i.e. load ":syn-match" if you typed :sy match").

### CODE REVIEW

**Comment by arp242** [comment]
Hm, the Windows AppVeyor build fails with:

    ex_docmd.c(3685) : error C2275: 'exarg_T' : illegal use of this type as an expression
            c:\projects\vim\src\ex_cmds.h(85) : see declaration of 'exarg_T'

For the line:

    exarg_T ea;

Not entirely sure why that should fail, and why it fails only on Windows 🤔

I don't have a Windows machine to test, so if anyone has any hints then that would be appreciated.

**Comment by chrisbra** [comment]
> exarg_T ea;

can you put this at the beginning of the function please?

**Comment by k-takata** [comment]
MSVC 2010 doesn't support to declare a variable in the middle of the block.

**Comment by arp242** [comment]
Ah thanks: C89 style. I'm so used to writing it like this I didn't think about that 😅 I updated the PR and it seems grand now.

**Comment by matveyt** [comment]
Well, but couldn't we instead of this just to omit sorting step while expanding "command" specifically, so both `getcompletion("syn", "command")` will return `["syntax", "syntime", "syncbind"]` in this order, and also `:syn<tab>` will nicely expand into "syntax" first?

**Comment by arp242** [comment]
> Well, but couldn't we instead of this just to omit sorting step while expanding "command" specifically, so both `getcompletion("syn", "command")` will return `["syntax", "syntime", "syncbind"]` in this order, and also `:syn<tab>` will nicely expand into "syntax" first?

I wouldn't be in favour of that myself; I think the completion and "shortcut" logic are quite different things, and I don't think many people would expect the cmdline completion behaviour to be modified based on that. Having `:substitute` on top when doing `:s<Tab>` seems really weird to me, and would be doubly weird with `wildmode=full`.

**Comment by brammool** [comment]
Instead of "shorcut" the term "abbreviation" should be used.  This is mentioned in section 20.2 of the user manual.
"findcommand" isn't quite right.  How about "fullcommand" ?

**Comment by arp242** [comment]
I avoided using the word "abbreviation" to avoid confusing between this and `:abbr` abbreviations.

At any rate, I updated the name to `fullcommand()` and tweaked the help page a bit.

**Pull request closed without merging**
