### PR TITLE
Support multibyte characters with breakat

### PR DESCRIPTION
**Pull request by mattn**
This is a pull-request working in progress.

screenshot

This patch behaves a little bit incorrectly. The following lines doesn't follow and scroll with breaking lines above.

### CODE REVIEW

**Comment by mattn** [comment]
@brammool Hmm, it is difficult to figure out why do not scroll-down correctly. Can you figure out what is still wrong?

**Comment by brammool** [comment]
Sorry, I already have a lot of things to look into.

**Comment by brammool** [comment]
I don't know about the scroll-down problem, but here are a few remarks on the patch:
- Going through the list is quite slow, this should use binary search.  Sort the numbers in fill_breakat_flags() and do the binary search in has_breakat_chars()
- In has_breakat_chars() the formatting is not in Vim style.  "*p == NULL" should be "*p == NUL".

**Comment by cvwillegen** [comment]
Is this still being worked on? Do you have an automated test for this functionality?

**Comment by chrisbra** [comment]
This seems to have been stalled. I am closing this one. If you ever make progress (or rebase on current master), please create a new PR.

**Pull request closed without merging**
