### PR TITLE
termdebug: accept lists in g:termdebugger

### PR DESCRIPTION
**Pull request by ii14**
Accept lists in g:termdebugger to support the [rr debugger](https://rr-project.org/):

    let g:termdebugger = ['rr', 'replay', '--']

### CODE REVIEW

**Comment by brammool** [comment]
Thanks. I'll include it and use your example for the help.

**Comment by GitMensch** [comment]
@ii14: Did you found a way to have the "common" stdio of the recorded process in the terminal buffer for the application?

**Comment by GitMensch** [comment]
I've found a way, but I don't like it:

This needs a manual adjustment of the new setting _and_ termdebug.

`let g:termdebugger = ['rr', 'replay', '--']`

--> working replay

`let g:termdebugger = ['rr', 'replay']
+ move the tty setting directly after getting the command and change it

```diff
  " Open a terminal window to run the debugger.
-    let gdb_cmd += ['-tty', pty]
+  let gdb_cmd += ['--tty', pty, '--']
```

Obviously we don't want to adjust termdebug each time...
Any ideas how to solve this?

**Comment by ii14** [comment]
> Third thought... if we could use something like $pty that gets resolved by vim this issue would be fixed, too (both get the tty parameter, but GDB "ignores" it because it is in target remote mode).

Maybe a user defined function?
```vim
function! GdbCommand(params)
  return ['rr', 'replay', '--tty', a:params.tty, '--', '...']
endfunction
```

**Comment by GitMensch** [comment]
I'm not sure about the most reasonable way to handle this. For now I've adjusted the tty setting, see #10390.
If this is applied one would set on of

```viml
let g:termdebugger = ['rr', 'replay']
let g:termdebugger = ['rr', '/some/trace/name/or/dir']
```

Then start Termdebug - the correct tty-parameter and the "from now on pass GDB parameters" `--`, which is needed for mi and other parts - would be set by the plugin.

**Pull request closed without merging**
