### PR TITLE
add setting to plsql syntax file to disable procedure folding

### PR DESCRIPTION
**Pull request by lee-lindley**
PLSQL syntax folding can run too long on large files that ommit optional syntax (procedure end block names).
This commit adds a variable setting that turns off syntax folding for procedures.

### CODE REVIEW

**Comment by chrisbra** [comment]
ping @lee-lindley

**Comment by chrisbra** [comment]
ah sorry, I got that wrong. You are already the runtime file maintainer 🙈

**Comment by brammool** [comment]
> PLSQL syntax folding can run too long on large files that ommit
> optional syntax (procedure end block names).

Using exists() does not work well.  Better:

	if get(g:, "plsql_disable_procedure_fold", 0)

Then the user can disable it with:
	let g:plsql_disable_procedure_fold = 1

-- 
ARTHUR:  Be quiet!
DENNIS:  Well you can't expect to wield supreme executive power just 'cause
         some watery tart threw a sword at you!
ARTHUR:  Shut up!
DENNIS:  I mean, if I went around sayin' I was an empereror just because some
         moistened bint had lobbed a scimitar at me they'd put me away!
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I'll include it, thanks.

**Pull request closed without merging**
