### PR TITLE
runtime(mermaid): Syntax fix

### PR DESCRIPTION
**Pull request by KSR-Yasuda**
Fixed the syntax for mermaid-js roughly.

Since it is mixed up with tons of diagram syntaxes, this won't be complete, though.

* runtime(mermaid): Fix arrow syntax
    - Fixed it has dropped some of arrows (such as `->>` in `sequenceDiagram` syntax).
* runtime(mermaid): Disable syntax for identifier to avoid false match
    - The syntax for `mermaidIdentifier` is probably for method name in `classDiagram` syntax,
      but it also unexpectedly matches `node(text)` or such in `flowchart` syntax.
* runtime(mermaid): Add some C++ type syntax highlight
    - Added more major type names to be highlighted (probably for `classDiagram`).

### CODE REVIEW

**Comment by chrisbra** [comment]
Can you please update the last change header of the file?
Would you be willing to maintain this file?  Then please also add yourself as maintainer.

**Comment by KSR-Yasuda** [comment]
Perhaps I had better send PR to the syntax's maintainer's repo <https://github.com/craigmac/vim-mermaid> ?

Tried to fix it anyway, but I think it is beyond me to be a maintainer since I'm not familiar with Vim syntax settings.

**Comment by KSR-Yasuda** [comment]
Changed header.

Also [posted the same patch to the maintainer's repo](https://github.com/craigmac/vim-mermaid/pull/2).
I'd like to wait for review anyway.

**Comment by craigmac** [comment]
LGTM. I've switched to using treesitter highlighting, so if you want to maintain this file I can add you. You appear to be more familiar with Vim syntax highlighting than I was!

**Comment by KSR-Yasuda** [comment]
Thank you for review & merge :)

**Pull request merged**
