### PR TITLE
Support for Windows Terminal

### PR DESCRIPTION
**Pull request by ghost**
Ambiguous width characters cannot be entered, probably due to the terminal.
Other features are probably fine.

### CODE REVIEW

**Comment by brammool** [comment]
Did someone try this out?

**Comment by ghost** [comment]
Only I have tried. Not unstable, but I am not relieved.
Ambiguous width not available in Japanese, not practical.
I thought it would work in an English environment.

Well, operation in the terminal has improved.

**Comment by k-takata** [comment]
I wonder if this should be fixed in Vim side. If Windows Terminal works differently from Command Prompt, then shouldn't Windows Terminal be fixed? (Working around it in Vim might be handy for you, though.)
Windows Terminal is still in preview phase, so if there is an issue in it, it should be better to be fixed before v1.0.

**Comment by ghost** [comment]
I fully agree. Here is closed.

**Pull request closed without merging**
