### PR TITLE
runtime/syntax/c.vim: Link typedef to Typedef instead of Structure

### PR DESCRIPTION
**Pull request by husamalhomsi**

### CODE REVIEW

**Comment by brammool** [comment]
OK, in case you want to highlight "typedef" differently.  But let's make it use the same highlighting as before by default.

**Comment by husamalhomsi** [comment]
@brammool Could you clarify why this was rejected?

**Comment by chrisbra** [comment]
I don't think it was rejected. Bram included it in his runtime files and it will be pushed here with the next runtime file updates.

**Comment by husamalhomsi** [comment]
@chrisbra I see. Thanks for letting me know.

> Bram included it in his runtime files

Where can I find these? They don't seem to be in his GitHub forks.

**Pull request closed without merging**
