### PR TITLE
win32: Reimplementation of VIMDLL

### PR DESCRIPTION
**Pull request by k-takata**
The VIMDLL support was removed at [8.1.1066](https://github.com/vim/vim/commit/89828e9fe6de4d70e0e2ccd3c711bd26632c26a9).
I reimplemented it on MSVC and MinGW.
The differences from the old implementation are:

* Supports MSVC and MinGW. (Don't support Borland C++.)
* Supports gvim.exe and vim.exe.
  If you build with `nmake -f Make_mvc.mak VIMDLL=yes`, vim{32,64}.dll
  will be built and also stub gvim.exe and vim.exe will be built.
  The shared codes between GUI and CUI are all built into the DLL.
  So the total size of the distribution files can be reduced.
* Supports `vim -g` and the `:gui` commands.
  If the commands are executed with the `-f` option, vim.exe will open a GUI
  window directly. Otherwise, vim.exe will execute gvim.exe. `:gui` will
  use `:mksession` to inherit the session to gvim.exe.

Related: https://github.com/vim/vim/pull/4171#issuecomment-477512999

### CODE REVIEW

**Comment by k-takata** [comment]
Example file sizes:

|           | VIMDLL=no | VIMDLL=yes |
|-----------|----------:|-----------:|
| gvim.exe  | 2,841,088 |     85,504 |
| vim.exe   | 2,679,296 |     88,064 |
| vim32.dll |         - |  2,867,712 |
| **Total** | 5,520,384 |  3,041,280 |

Total file size is reduced about 2.4 MB.

**Comment by k-takata** [comment]
@brammool 
https://groups.google.com/d/msg/vim_dev/9JS4qp5cFLA/Tkc3OcGuCAAJ

> > * Supports `vim -g` and the `:gui` commands.
> >   If the commands are executed with the `-f` option, vim.exe will open a GUI
> >   window directly. Otherwise, vim.exe will execute gvim.exe. `:gui` will
> >   use `:mksession` to inherit the session to gvim.exe.
> 
> Does this really work?  Any variable values would be lost. 

`:gui` with `:mksession` works almost fine. It inherits global status. But It is not perfect as you pointed out.
(On the other hand, `:gui -f` works perfect, because vim.exe itself opens the window in the same process.)
If there are any unsaved files, `:gui` automatically falls back to `:gui -f`.

**Comment by brammool** [comment]
> @brammool 
> 
> > > * Supports `vim -g` and the `:gui` commands.
> > >   If the commands are executed with the `-f` option, vim.exe will open a GUI
> > >   window directly. Otherwise, vim.exe will execute gvim.exe. `:gui` will
> > >   use `:mksession` to inherit the session to gvim.exe.
> > 
> > Does this really work?  Any variable values would be lost. 
> 
> `:gui` with `:mksession` works almost fine. It inherits global status. But It is not perfect as you pointed out.
> (On the other hand, `:gui -f` works perfect, because vim.exe itself opens the window in the same process.)
> If there are any unsaved files, `:gui` automatically falls back to `:gui -f`.

I rather not implement this, unless it works perfectly.  Otherwise we
will keep getting bug reports around this.
Ideally this works the same way as it does on Unix.  But I suppose
bringing back the command prompt won't be possible, since Windows
doesn't have a way to detach, other than starting a GUI program.

-- 
Apologies for taking up the bandwidth with the apology.  Anything else I
can apologise for ...... er no can't think of anything, sorry about that.
		Andy Hunt (Member of British Olympic Apology Squad)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> But I suppose bringing back the command prompt won't be possible, since Windows doesn't have a way to detach, other than starting a GUI program.

Yes, unix shell can use Ctrl-Z and `bg` to move the process to the background, but Windows doesn't support it. Opening a GUI from vim.exe and stay in foreground is useless. So, `:gui -f` is not useful.
And `:gui -b` doesn't work perfectly as it uses `:mksession`. So it might be better to disable `:gui`.

I think that `vim -g` is still useful. It works perfectly.

**Comment by k-takata** [comment]
I disabled the `:gui` command in the latest commit.

**Comment by brammool** [comment]
Thanks.  So now we mainly save space and the installer will get a lot smaller.
If someone sees a drawback, please let us know.
Otherwise I'll include it soon.

**Comment by k-takata** [comment]
I had a report that "gvim --serverlist" didn't work, so I fixed it.
I also revised the makefiles, update nsis script for VIMDLL.

I think this is ready to be included. If there are still some problems, they can be fixed one by one.

**Pull request closed without merging**
