### PR TITLE
messagesopt "wait" maximum value should be set

### PR DESCRIPTION
**Pull request by Shougo**
Fix https://github.com/vim/vim/pull/16068#issuecomment-2524848344.

"wait" maximum value should be set.

I have set it to 10000.

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks!

**Comment by h-east** [comment]
Overflow can still occur with this PR.
Anything less than 0 should be an error?
https://github.com/vim/vim/pull/16068#issuecomment-2524848344

Also, I think the following should be included in the documentation:
https://github.com/vim/vim/pull/16068#issuecomment-2525123471
> Need to specify either "hit-enter" or "wait:", or both.

**Comment by h-east** [comment]
> Also, I think the following should be included in the documentation:

Sorry, already included.
```
This item is ignored when "hit-enter" is present, but required when "hit-enter" is not present.
```

**Comment by h-east** [comment]
> Anything less than 0 should be an error?

I PRed.
https://github.com/vim/vim/pull/16187

**Pull request closed without merging**
