### PR TITLE
Feature: fastwincmd

### PR DESCRIPTION
**Pull request by jakalope**
Terminal emulation windows require a `CTRL-K` (or 'termkey') prefix to switch to another window. For a terminal-heavy workflow, this isn't desirable. This changeset adds an option 'fastwincmd' that allows one to navigate away from a terminal window with `CTRL-{H,J,K,L}` keystrokes directly.

Perhaps a more flexible solution would be to allow arbitrary remapping, as is done in insert mode, but as this is my first contribution, I felt I should simply open the discussion (in case it wasn't already opened).

### CODE REVIEW

**Comment by mattn** [comment]
I prefer to add tmap command for terminal than fixed keys.

**Comment by jakalope** [comment]
@mattn I'd be happy to implement `tmap` if no one is working on it yet. I'd need a back-of-the-napkin list of things that need to be done for this to work properly.

**Comment by brammool** [comment]
> @mattn I'd be happy to implement `tmap` if no one is working on it
> yet. I'd need a back-of-the-napkin list of things that need to be done
> for this to work properly.

The terminal mappings would be used when inside terminal_loop().
Currently available by use_terminal_cursor(), that could be renamed.

You need to change:
- get_map_mode()
- get_real_state()
- and probably some other stuff
- Update the help
- write a few tests

It's nearly all a variant on existing mapping code.

-- 
One difference between a man and a machine is that a machine is quiet
when well oiled.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jakalope** [comment]
Closing with the intention of making a new PR for `tmap` and associates.

**Pull request closed without merging**
