### PR TITLE
Popup window is sticking out.

### PR DESCRIPTION
**Pull request by rbtnn**
+---- Only padding space is sticking out now.
    --------+ |
            | v
     +---------+
     |popup    |
     |window   |
     +---------+
            |
            |
            |

_before_
before
_after_
after

### CODE REVIEW

**Comment by rbtnn** [comment]
I'll add test.

**Comment by brammool** [comment]
The popup can extend beyond the right of the screen if needed.  Depending on the options.
I do notice that for computing the text width and position the border and padding on the left is not taken into account.  I'll fix that.  I'm not sure anything else is needed.  Perhaps an extra option to avoid the popup being cut off?

**Comment by rbtnn** [comment]
> The popup can extend beyond the right of the screen if needed. Depending on the options.

I see.

> I do notice that for computing the text width and position the border and padding on the left is not taken into account. I'll fix that.

Isn't `right_extra` also? 

https://github.com/vim/vim/commit/51c313104096c7af5024aebbf295f7f03486874b#diff-7d2ae970f06481cdd82cece2a74b6c8cR591

**Comment by rbtnn** [comment]
I saw `Test_popupwin_20.dump` and understood the specifications. 

> I'm not sure anything else is needed. Perhaps an extra option to avoid the popup being cut off?

I think the extra option is unnecessary.

**Comment by brammool** [comment]
> > The popup can extend beyond the right of the screen if needed. Depending on the options.
> I see.
> 
> > I do notice that for computing the text width and position the border and padding on the left is not taken into account. I'll fix that.
> Isn't `right_extra` also? 

I think it's OK that the right padding and border is not visible.
Apparently we have run out of space, thus sacrificing those to show more
text makes sense.

-- 
hundred-and-one symptoms of being an internet addict:
202. You're amazed to find out Spam is a food.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
