### PR TITLE
termdebug: frame related commands

### PR DESCRIPTION
**Pull request by GitMensch**
partially fixing #10393

... its been a while that this was setting around. I do hope someone may take this as an option to get the commands already into termdebug before I try to add a window - as that is complicated and we have no finished design for that.

I do know that this PR is missing something: the help text - if possible please add it (as the PRs are not merged "directly" I think that's fine). Also I did not have another look at the FIXME note in the Frames command.

One thing I'd do suggest is to add a default mapping for Down as "D" and Up as "d". But as - again - only K is default mapped I was not sure if that's "too intrusive".

Thanks for considering this contribution!

### CODE REVIEW

**Comment by brammool** [comment]
> partially fixing #10393
> 
> ... its been a while that this was setting around. I do hope someone
> may take this as an option to get the commands already into termdebug
> before I try to add a window - as that is complicated and we have no
> finished design for that.

Assuming that a few people will try out the patches and improvements are
made, it's probably easier to just have one patch.  Otherwise merge
conflicts will make it harder to include both.

Just to be clear: with "window" you mean a Vim window that displays the
current stack, like what "where" would output.  With an indication of
the current location, if not at the top.  The window would be updated
whenever the program is stopped.  Commands in the window and clicking
with the mouse could be used to select a certain frame, like what "frame
123" would do in the gdb window.

> I do know that this PR is missing something: the help text - if
> possible please add it (as the PRs are not merged "directly" I think
> that's fine). Also I did not have another look at the FIXME note in
> the Frames command.

Please do add help text early.  Not only to make it easy for users to
try it out, it also helps checking that it works in a way it's easy to
explain to someone.  If writing the help text is hard, then perhaps the
code needs to be adjusted to make the usage simpler.

> One thing I'd do suggest is to add a default mapping for Down as "D"
> and Up as "d". But as - again - only K is default mapped I was not
> sure if that's "too intrusive".

The frame "up" and "down" commands are probably used most often.  Using
uppercase would be "U" and "D", but both are regularly used commands,
thus that gets confusing.  Perhaps using "+" and "-" is better?  They
are regular commands, but personally I don't use them, thus I would be
OK with mapping them.

I have several other things to work on, thus I'll await what you and
others can come up with, possibly until it's ready to include.

-- 
hundred-and-one symptoms of being an internet addict:
139. You down your lunch in five minutes, at your desk, so you can
     spend the rest of the hour surfing the Net.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by GitMensch** [comment]
> Just to be clear: with "window" you mean a Vim window that displays the
current stack, like what "where" would output.  With an indication of
the current location, if not at the top.  The window would be updated
whenever the program is stopped.

Yes

> Commands in the window and clicking
with the mouse could be used to select a certain frame, like what "frame
123" would do in the gdb window.

Sounds cool - that would be the case if you (or someone else) add it - I only can do the "view" part and the code for up/down/number - as that is what the `Frame` command (currently in this PR) does already.

> The frame "up" and "down" commands ... using "+" and "-" is better ...  I would be OK with mapping them.

OK, I'll do that.

> Assuming that a few people will try out the patches and improvements are made, it's probably easier to just have one patch. 

I'll add the help text and the mapping for this PR, because the window is really "a separate" thing from the commands and "the way the window is created/positioned" is the part that's not clear yet - so we can add it with a later PR.

**Comment by chrisbra** [comment]
any update here please @GitMensch ?

**Comment by GitMensch** [comment]
@chrisbra Implemented with help and default mapping as requested. Leaving the window to a separate PR to be re-implemented like `:Var`.

**Review by yegappan — APPROVED** [review]

**Comment by GitMensch** [comment]
Is there an actual option to test-coverage those changes?

**Comment by GitMensch** [comment]
> Currently there is no test coverage for the termdebug plugin. But it will be good to add some test coverage though.

Sounds good, moved that to a new issue.

As I'm new to this changed scenario - how will merges be done (as before "in a bunch", then committed with a new patch number)?

**Comment by yegappan** [comment]
Christian is merging the runtime file changes directly (without a patch number).  This way the authors of the runtime file changes
get credit for their changes while at the same time there is no proliferation of patches.  The patch number is used only for the
core source changes (src and testdir).  So for any runtime file changes open a PR.

**Pull request merged**
