### PR TITLE
use ubuntu-latest

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by chrisbra** [comment]
Can you please give a reasoning for switching?

**Comment by pheiduck** [comment]
For Maintaining the CI Core System its easier to keep ubuntu updated, (if ubuntu ship a new LTS Version) the *-latest isn't forced to the new version, so I think its save to use.

**Comment by brammool** [comment]
This appears to make the CodeQL actions fail.

**Comment by pheiduck** [comment]
We can revert the change for CodeQL

**Pull request closed without merging**
