### PR TITLE
Add new JavaScript document properties to completion file

### PR DESCRIPTION
**Pull request by jsit**
Adding a lot of new [document properites](https://developer.mozilla.org/en-US/docs/Web/API/Document#Properties) to JavaScript completion.

### CODE REVIEW

**Comment by chrisbra** [comment]
Have you contacted the maintainer?

**Comment by jsit** [comment]
Yes, I emailed him yesterday in addition to creating this PR.

**Comment by jsit** [comment]
@chrisbra I contacted Mikołaj Machowski (@vvizzo) and he confirmed that he is no longer the maintainer of the JavaScript completion file, writing:

> I am not currently actively maintaining js complete file. The best way is to fork on github, create issue with PR.

(@vvizzo please confirm here as well if you're able.)

What do you suggest? There was no repository for this completion file anywhere; I think there ought to be one on GitHub, owned by an active maintainer who can review/accept PRs so that the completion file.

**Comment by chrisbra** [comment]
> What do you suggest? There was no repository for this completion file anywhere; I think there ought to be one on GitHub, owned by an active maintainer who can review/accept PRs so that the completion file.

Well, would you be willing to become the new maintainer?

**Comment by jsit** [comment]
I don't think I'm the right person for the job. You might ask @1995eaton, who maintains [vim-better-javascript-completion](https://github.com/1995eaton/vim-better-javascript-completion).

**Comment by vvizzo** [comment]
Just for confirmation: i am no longer maintaining this completion file.   Best,   m. 
            
          
     
      
       
        Dnia 14 lipca 2020 15:52 Jay Sitter &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 github.com @chrisbra  I contacted Mikołaj Machowski ( github.com @vvizzo ) and he confirmed that he is no longer the maintainer of the JavaScript completion file, writing: 
 
 I am not currently actively maintaining js complete file. The best way is to fork on github, create issue with PR. 
 
 ( github.com @vvizzo  please confirm here as well if you&#39;re able.) 
 What do you suggest? There was no repository for this completion file anywhere; I think there ought to be one on GitHub, owned by an active maintainer who can review/accept PRs so that the completion file.

**Comment by yegappan** [comment]
Can you update and rebase this PR to the latest?

**Comment by chrisbra** [comment]
included as of a0fddaa2f4b7358484eb54ccdd1b7433d18a9039

**Pull request closed without merging**
