### PR TITLE
French and German keymaps

### PR DESCRIPTION
**Pull request by yerlaser**
Surprised to see that keymaps for two very popular languages are missing.
Adding French (azerty) and German (qwertz) keymaps.
In my tests, AltGr keys don't work reliably across platforms, so I omitted them.
Anyways, keymaps are supposed to be used for colloquial text entry with few special symbols.

### CODE REVIEW

**Comment by brammool** [comment]
I would appreciate feedback about these keymaps.

**Comment by yerlaser** [comment]
Just to confirm, you're awaiting feedback from someone else, not me?
Otherwise, it's not clear what kind of feedback I can provide.

**Comment by brammool** [comment]
Feedback from anybody that might want to use these keymaps.

**Comment by chrisbra** [comment]
as a german user (who does not use keymaps), please mention why those would be needed?

**Comment by yerlaser** [comment]
Your question is ambiguous but I will try to answer nevertheless.

1) if you are doubtful if keymaps are a useful feature then, yes, they shine for non-Latin alphabet languages. However, they can still be quite useful even for Latin alphabet based languages. For example, the German keyboard layout has @, {}, [] symbols accessible only with Right Alt. It is painful to type for touch typist. These symbols correspond to quite frequently used VIM functions in Normal and Visual modes, e.g. running macros or jumping around paragraphs. Even worse, back quote is a dead key. So, if you need to go to position before last jump, you need to press Shift+=, Space, Shift+=, Space. Four key presses instead of two. French keyboard layout is similarly inconvenient.

2) you might say that one can simply change OS keyboard layout. But that's is even more inconvenient, because every time you switch to normal mode you must remember to also change OS layout back to US English and vice versa.

3) I know that many Germans are so used to standard German layout that they type even English texts with that layout. However, programmers, sysadmins and other technical people still often use standard US QWERTY layout because of the easily accessible special symbols.

**Comment by brammool** [comment]
Well, since they are small files and can be ignored if not using them, let me just include them.

**Pull request closed without merging**
