### PR TITLE
VIM: Haiku patches

### PR DESCRIPTION
**Pull request by extrowerk**
dbq

### CODE REVIEW

**Comment by nuko8** [comment]
Thank you for the contribution.

A quick question:  The file ` src/proto/gui_haiku.pro` uses the `__ARGS()` macro which has been got rid of since b7604cc19 (7.4.1098).  So it looks like the proposed patch set won't work with the current codebase to build Vim, but I cannot be sure of that since I don't know about Haiku (as an operating system :)   So will you make sure whether or not the patch set of this PR is good for merging into the current codebase?

If you find it need to update, please do that.  Also, please fix the coding style; it looks inconsistent.  For the details, please refer to the second section of `:help develop.txt` or Bram's recent work `src/terminal.c` when you find the instructions of the help document unclear or insufficient.

**Comment by brammool** [comment]
For copyright reasons:  Please reveal your real name and clearly state that this code contribution is either written under the Vim license or fully compatible with the Vim license (e.g. MIT).

**Comment by extrowerk** [comment]
@brammool : Do you need it in cleartext here, or should i email you?

@nuko8 : thanks, i'll try my best, but it will take a while.

**Comment by extrowerk** [comment]
@nuko : ofc it builds and runs just fine on every main Haiku arch. I know you guys got rid the ARGS stuff, but i patched "vim.h" too :)
It is actually the really old vim BeOS port (for vim 5.4, but fixme) updated for Haiku and for "modern" standards, that's why there is still some legacy things here and there.
I try to maintain the vim port at haikuports https://github.com/haikuports/haikuports/tree/master/app-editors/vim
So i'm pretty sure it works, but i'll try to get it more modernized.

**Comment by nuko8** [comment]
@miqlas 

You don't have to modernize the code too much :)  The only requirement about compilers is
> C COMPILER
>
> The minimal C compiler version supported is C89, also known as ANSI C.
> Later standards don't add much and C89 is the widest supported.
>
> One restriction that this implies: no // comments, only /* comments */.

(Excerpt from `:help development`)

Also, note that

> VIM IS... MULTI PLATFORM
> ...
> - Support many compilers and libraries.  Not everybody is able or allowed to
>  install another compiler or GUI library.

(Excerpt from `:help development`)

So feel free to ask us for any changes on our build system if necessary.

**Comment by extrowerk** [comment]
I just updated the proto file to the current style/standard.
Sorry for my bad english, i don't want to use the advanced features of Haiku (integrated machine learning for automatical bug-correction in binary programs, and world peace, free beer) in vim core, just to bring my patchset to the current vim standards.

I hope i'm on the right track. If you can spot any bug, just let me know, and i'll try to fix it.

**Comment by extrowerk** [comment]
Just fixed the // comments. Is there anything else what i can do?

**Comment by extrowerk** [comment]
@nuko8 : as far as i know the sources and my patches, all the haiku specific thing guarded with #ifdef, so it shouldn' make any problem on other platforms.
About the compilers: on Haiku the oldest available compiler is GCC2.95.3 and it can compile just fine my patchset.
So if it is guarded by #ifdef and it is Haiku specific, then every compiler on Haiku could build it.

But i'm all ears, what should i change in the sources to get it merged.

**Comment by nuko8** [comment]
Then, please read through `:help coding-style`, make sure whether or not the code of the patches complies with the requirements mentioned there.  If you find something not following the requirements, try correcting it to fulfill them.  Though that is really laborious, it's worth doing as it will help people work with your work later once the patches gets merged.

**Comment by brammool** [comment]
miqlas wrote:

> @brammool : Do you need it in cleartext here, or should i email you?

Best is if you can send it to the Vim mailing list.
If you don't want to reveal your real name, I'm not sure I want to
include your code.  We can email in private, if you prefer.

> @nuko8 : thanks, i'll try my best, but it will take a while.

-- 
Two fish in a tank. One says to the other:
"Do you know how to drive this thing?"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by extrowerk** [comment]
@brammool : easy: http://extrowerk.com/about/

**Comment by brammool** [comment]
Ah, I now see your name is not in the github profile, but the website is.
For the license: best is to add a comment to haiku-specific files who wrote it and that it can be distributed under the Vim license.

**Comment by extrowerk** [comment]
@brammool : already sent email to the original author, still waiting for answer about the copyright status...

**Comment by extrowerk** [comment]
@brammool : Got an answer from the original authors, they allowed to reuse the whole code under vim-license.

**Comment by brammool** [comment]
Miqlas wrote:

> @brammool : Got an answer from the original authors, they allowed to
> reuse the whole code under vim-license.

Very good, thanks.  Can you add a comment about that in the main file or
readme file?

-- 
Yesterday is history.
Tomorrow is a mystery.
Today is a gift.
That's why it is called 'present'.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by extrowerk** [comment]
@brammool : Notes added about the license, conflict solved, is there anything what i can do?

**Comment by brammool** [comment]
> @brammool : Notes added about the license, conflict solved, is there
> anything what i can do?

It's in the todo list, I'll get to it in a while.

-- 
From "know your smileys":
 +<(:-) The Pope

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by extrowerk** [comment]
@brammool : just solved the merge conflict here.
Feel free to look at it if you got some spare time.

**Comment by brammool** [comment]
> @brammool : just solved the merge conflict here.
> Feel free to look at it if you got some spare time.

It's in the todo list.  But it's a very long list...

-- 
ARTHUR:        I command you as King of the Britons to stand aside!
BLACK KNIGHT:  I move for no man.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bitigchi** [comment]
This is cool. I have been using Haiku for the last month or so, and it really is impressive. Looks like Vim is already ready.

**Comment by extrowerk** [comment]
I don't really have time to work in this, sorry.

**Comment by bitigchi** [comment]
I've updated this PR for 8.2, I will open a new one soon once it's ready.

**Pull request closed without merging**
