### PR TITLE
CI: second try: macOS m1(arm64) build w/ --disable-channel --disable-messages

### PR DESCRIPTION
**Pull request by pheiduck**
we should disable flaky tests otherwise its not possible to use as CI:
`--disable-channel`

### CODE REVIEW

**Comment by brammool** [comment]
BTW: disable-messages has no effect.
disable-channel makes it skip a lot of tests, but let's first make this work and we'll see if we can enable the channel feature.

**Comment by pheiduck** [comment]
> Do the tests take so long or did it get stuck in a timer test? Unfortunately we can't tell the difference. We may have to run this a few times to find out if something fails often/always/sometimes.

Test_nocatch_timer_garbage_collect() takes to long

**Comment by pheiduck** [comment]
> BTW: disable-messages has no effect.
> disable-channel makes it skip a lot of tests, but let's first make this work and we'll see if we can enable the channel feature.

We can try to run it without disable this tests, but I thing the will get flaky again.

**Comment by brammool** [comment]
Hmm, it appears to get stuck on the hit-enter prompt in that test.  It worked on other platforms though.
Anyway, can feed some other characters to get out of that prompt.
I'll think of a way to break out of a test that gets stuck.

**Comment by brammool** [comment]
Glad to see the test timeout is working.  Fixed a side effect just now.
It appears there are a couple of tests that just keep failing.  Is there a has() or exists() way to detect we are on this MacOS m1 system?    We can use "has('mac')" but it would be good to be more specific.

**Comment by brammool** [comment]
It appears "uname -a" includes "arm64", I suppose that is unique enough.

**Comment by pheiduck** [comment]
> It appears "uname -a" includes "arm64", I suppose that is unique enough.

Yes, I will trigger the CI again an remove --disable flags then.

**Comment by pheiduck** [comment]
Test_nocatch_timer_garbage_collect() is still stuck.

**Comment by brammool** [comment]
> > It appears "uname -a" includes "arm64", I suppose that is unique enough.
> 
> Yes, I will trigger the CI again an remove --disable flags then.

Something weird is happening.  The cscope test fails when adding comment
lines to the RunTheTest() function.  Smells like some kind of memory
corruption.

-- 
hundred-and-one symptoms of being an internet addict:
149. You find your computer sexier than your girlfriend

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > Do the tests take so long or did it get stuck in a timer test?
> > Unfortunately we can't tell the difference. We may have to run this
> > a few times to find out if something fails often/always/sometimes.
> 
> Test_nocatch_timer_garbage_collect() takes to long

It gets stuck for no apparent reason.  There might be something else
causing these problems...

-- 
You are not really successful until someone claims he sat
beside you in school.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> > > Do the tests take so long or did it get stuck in a timer test?
> > > Unfortunately we can't tell the difference. We may have to run this
> > > a few times to find out if something fails often/always/sometimes.
> > 
> > Test_nocatch_timer_garbage_collect() takes to long
> 
> It gets stuck for no apparent reason.  There might be something else
> causing these problems...

I suspect CheckNotMacM1() is not working.  Can you check what "uname -a"
returns in this job?  You can add something that will intentionally
break the tests:

	call assert_equal('nothing', system('uname -a '))

-- 
hundred-and-one symptoms of being an internet addict:
151. You find yourself engaged to someone you've never actually met,
     except through e-mail.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I wrote:

> > > > Do the tests take so long or did it get stuck in a timer test?
> > > > Unfortunately we can't tell the difference. We may have to run this
> > > > a few times to find out if something fails often/always/sometimes.
> > > 
> > > Test_nocatch_timer_garbage_collect() takes to long
> > 
> > It gets stuck for no apparent reason.  There might be something else
> > causing these problems...
> 
> I suspect CheckNotMacM1() is not working.  Can you check what "uname -a"
> returns in this job?  You can add something that will intentionally
> break the tests:
> 
> 	call assert_equal('nothing', system('uname -a '))

Or if someone has a Mac M1, let us know the output of "uname -a".

-- 
hundred-and-one symptoms of being an internet addict:
153. You find yourself staring at your "inbox" waiting for new e-mail
     to arrive.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by pheiduck** [comment]
> Or if someone has a Mac M1, let us know the output of "uname -a".
`Darwin admins-Virtual-Machine.local 22.0.0 Darwin Kernel Version 22.0.0: Mon Aug  1 06:31:45 PDT 2022; root:xnu-8792.0.207.0.6~26/RELEASE_ARM64_VMAPPLE arm64`

**Comment by brammool** [comment]
So the pattern match was correct...  Ah, using a Check command doesn't work in a _nocatch_ test function!

**Comment by brammool** [comment]
please merge 9.0.0574.  Fingers crossed...

**Comment by brammool** [comment]
Just one failing test remaining.  I suppose Vim gets an Esc somehow, Let's just skip the test.  I'll make a patch (you could also include it in this PR, but I don't mind.

**Pull request closed without merging**
