### PR TITLE
Add :const for safer scripting

### PR DESCRIPTION
**Pull request by rhysd**
Hi all,

This PR has proposed adding `:const` command to Vim.

## Problem

Scope of variables in Vim script function is very dynamic.

```vim
let i = 0
if some_condition
    " In heavily nested or big statements...
    let i = 1 " Unexpectedly using the same name variable
endif
echo i " => 1
```

This sometimes causes a bug by modifying variables unexpectedly. To prevent this, (if `i` is intended not to be modified,) `:lockvar` is effective:

```vim
let i = 0
lockvar i
if some_condition
    let i = 1  " Error
endif
echo i
```

However, using `:let` and `:lockvar` has following downsides:

- it is hard to give `:lockvar` at everywhere it is required
- using `:let` and `:lockvar` may not be efficient because it introduces overhead of one more command.

## Solution

In JavaScript, [`const`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) is provided for defining a variable.

```javascript
const number = 42;
number = 99;  // TypeError: invalid assignment to const `number'
```

`:const` does the similar thing in Vim script. With it, above example can be written as follows:

```vim
const i = 0
if some_condition
    let i = 1  " E995
endif
echo i " => 1
```

Here `:const` is used instead of `:let`. `:const` internally locks the variable `i`. So `i` is no longer modifiable. And it is more efficient than using both `:let` and `:lockvar` because both are done in one command.

In addition, `:const` raises an error if the variable is already existing:

```vim
let x = 0
const x = 1  " => E995
```

So `:const` does not lock and overwrite existing variable unexpectedly and `x` is guaranteed to be a new variable.

Another use case of `:const` would be defining constants in the script. For example:

```vim
const s:SEP = has('win32') ? '\' : '/'
```

Here the constant is not intended to be modified any more. So `:const` is better than `:let`.

### CODE REVIEW

**Comment by brammool** [comment]
Thanks for doing this.  I was actually thinking about this, since I was working with Javascript.  And the ":const" command was available.

**Comment by k-takata** [comment]
Fixed by [8.1.1539](https://github.com/vim/vim/commit/9937a055437ef67b57a1bdec8f0799b669c9dbf0).

**Comment by rhysd** [comment]
@brammool 

Thank you for your quick review and merge!
My name (Ryuichi Hayashida) seems missing in the patch 8.1.1539. Would you like to keep adding it at Vim 8.2 release note at `runtime/doc/version8.txt` in your mind?

**Comment by brammool** [comment]
> @brammool 
> 
> Thank you for your quick review and merge!
> My name (Ryuichi Hayashida) seems missing in the patch 8.1.1539. Would
> you like to keep adding it at Vim 8.2 release note at
> `runtime/doc/version8.txt` in your mind?

Will do.  I didn't see your name on github.
I'll also reference the pull request, somehow that was missing (Ken
closed the pull request manually).

-- 
hundred-and-one symptoms of being an internet addict:
200. You really believe in the concept of a "paperless" office.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rhysd** [comment]
> Will do.  I didn't see your name on github.

@brammool Thank you for your kind consideration. And I'm sorry that I forgot to show my name in advance.

**Pull request closed without merging**
