### PR TITLE
Update syntax bindzone

### PR DESCRIPTION
**Pull request by heptalium**
- Added more resource record types.
- Updated the network classes.

### CODE REVIEW

**Comment by chrisbra** [comment]
Have you contacted the maintainer of the file?

**Comment by heptalium** [comment]
No. Should I do that? And how?

**Comment by chrisbra** [comment]
yes, that is the prefered way. Use the email in the syntax file you are changing. If there is no reaction, come back here please.

**Comment by heptalium** [comment]
I didn't receive any answer.

**Comment by bjoe2k4** [comment]
Any update on this? `CAA` type RR would be nice to have, too!

**Comment by brammool** [comment]
I'll include it now.  Also keep CHAOS and add HESIOD, which appear to be part of the syntax.

**Pull request closed without merging**
