### PR TITLE
OpenDocument extensions -> g:zipPlugin_ext?

### PR DESCRIPTION
**Pull request by jablko**
@cecamp, would you consider adding the [OpenDocument extensions][1] to g:zipPlugin_ext?

[1]: http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1420388_253892949

### CODE REVIEW

**Comment by cecamp** [comment]
Looks good; I'll put it into my website version for the nonce (http://www.drchip.org/astronaut/vim/index.html#ZIP) for others to use and comment upon.  Eventually BramM will get it.

**Comment by jablko** [comment]
> Looks good; I'll put it into my website version for the nonce (http://www.drchip.org/astronaut/vim/index.html#ZIP) for others to use and comment upon. Eventually BramM will get it.

Excellent, thank you!

Just ruminating, but while I was about this, I was thinking how common the ZIP format is, how many file extensions there are, and whether there's an authoritative list or a better way than maintaining a growing list ... Does Vim do some filetype detection based on content/magic number, not just filename? What about treating all files (or files without filetype) that start with 0x4b50 as ZIP files? and if `g:zip_unzipcmd` fails, falling back to another filetype? I see there's already some logic like that in `zip#Browse`: https://github.com/vim/vim/blob/a87b72cc316e065d66dcbcf7ec1cde330adef3a3/runtime/autoload/zip.vim#L70

**Comment by brammool** [comment]
@cecamp was this sufficiently tested now?

**Comment by brammool** [comment]
@cecamp Did this get included?

**Comment by bitigchi** [comment]
The version on @cecamp's website seems to have it.

http://www.drchip.org/astronaut/vim/vbafiles/zip.vba.gz

**Comment by yegappan** [comment]
Is this PR still applicable or this can be closed?

**Comment by chrisbra** [comment]
seems to be included as of 71badf9547e8f89571b9a095 so closing.

**Pull request closed without merging**
