### PR TITLE
Add PowerShell files to vim

### LINKED ISSUE #8041: Adding PowerShell files to vim
There was a request to add PowerShell syntax files to vim, but we also have other scripts that contribute to a complete bundle. I see other languages added compilers and other scripts, so should everything be included, and is there interest in adding PowerShell support now that it's ubiquitous across platforms?

https://github.com/PProvost/vim-ps1/issues/50 (I'm one of the maintainers)

### PR DESCRIPTION
**Pull request by heaths**
Resolves #8041

### CODE REVIEW

**Comment by brammool** [comment]
Thanks for this.  I will assume that making this pull request means you want the files to be distributed with Vim and agree that the files can distributed under the Vim license.

**Comment by brammool** [comment]
Note that I had to add setting 'cpo' in the filetype files.

**Comment by heaths** [comment]
@brammool I'm confused. You closed this PR with a patch that does not actually include the added files - only changes to filetype.vim. How are the syntax files, etc., supposed to be resolved?

**Comment by dkearns** [comment]
They get pushed out in a separate periodic batch update, usually once a week or so, as there's often updates coming in directly via email as well.

The commit message is usually "Update runtime files".

**Comment by brammool** [comment]
> @brammool I'm confused. You closed this PR with a patch that does not
> actually include the added files - only changes to filetype.vim. How
> are the syntax files, etc., supposed to be resolved?

They will be included in the next runtime files update.  That happens
once in a while, avoids lots of small changes.  The filetype change
requires a test update, that's why it is a separate change.

-- 
Creating the world with Emacs:   M-x let-there-be-light
Creating the world with Vim:     :make world

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
