### PR TITLE
Add (g)vim.desktop files and install to /usr/share/applications

### PR DESCRIPTION
**Pull request by jamessan**
Here are the .desktop files Debian has been using for a number of years, as
well as a patch to install the files, as requested in #454.

### CODE REVIEW

**Comment by nuko8** [comment]
Just to make sure.

You wrote in the title `/usr/share/applications`, but you actually meant `$(DESTDIR)$(DATADIR)/applications` for that, right?

**Comment by tonymec** [comment]
Won't this overwrite any $DESTDIR/$DATADIR/vim.desktop and $DESTDIR/$DATADIR/gvim.desktop every time I run "make install"? Or wouldn't $DESTDIR/$DATADIR/ be irrelevant anyway compared to desktop files in ~/.desktop/ ?

**Comment by vim-ml** [comment]
On Mon, Oct 19, 2015 at 12:29:05AM -0700, Tony Mechelynck wrote:

> Won't this overwrite any $DESTDIR/$DATADIR/vim.desktop and $DESTDIR/$DATADIR/
> gvim.desktop every time I run "make install"?

Doesn't "make install" overwrite any $DEST_BIN/$VIMTARGET?  The point of
"make install" is to install.  If you don't want it to overwrite
something, then install somewhere else or don't run that part of the
install.

## Cheers,

James
GPG Key: 4096R/331BA3DB 2011-12-05 James McCoy jamessan@jamessan.com

**Comment by vim-ml** [comment]
On Sun, Oct 18, 2015 at 08:48:58PM -0700, nuko8 wrote:

> Just to make sure.
> 
> You wrote in the title /usr/share/applications, but you actually meant $
> (DESTDIR)$(DATADIR)/applications for that, right?

Correct.  The typical location that would expand to is
/usr/share/applications or /usr/local/share/applications.  I chose to
use the expanded form because I thought that would be a clearer
description.

## Cheers,

James
GPG Key: 4096R/331BA3DB 2011-12-05 James McCoy jamessan@jamessan.com

**Comment by coldfix** [comment]
I notice in the archlinux .desktop file lists a number of additional mimetypes. Would you consider including a more comprehensive list?

**Comment by jamessan** [comment]
Sure.  Updated with the list from the Arch Linux desktop files. Too bad desktop files don't let one specify a wildcard.  Using `text/*` would be simpler than keeping up with the myriad text-related mime types.

**Comment by brammool** [comment]
James McCoy wrote:

> Here are the .desktop files Debian has been using for a number of years, as
> well as a patch to install the files, as requested in #454.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/455
> 
> -- Commit Summary --
> - Add (g)vim.desktop files and install to /usr/share/applications
> 
> -- File Changes --
> 
> ```
> A runtime/gvim.desktop (80)
> A runtime/vim.desktop (80)
> M src/Makefile (3)
> ```
> 
> -- Patch Links --
> 
> https://github.com/vim/vim/pull/455.patch
> https://github.com/vim/vim/pull/455.diff

Thanks, I'll look into it this week.

## 

hundred-and-one symptoms of being an internet addict:
48. You get a tatoo that says "This body best viewed with Netscape 3.1 or
    higher."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
