### PR TITLE
spanish tutor: fix typos and bugs

### PR DESCRIPTION
**Pull request by victorhck**

### CODE REVIEW

**Comment by victorhck** [comment]
> There is an encoding problem in tutor.es. Make sure you edit as latin1 file.

How can I test that?
(sometimes easy tasks becomes hard for non developers like me)

**Comment by brammool** [comment]
> > There is an encoding problem in tutor.es. Make sure you edit as latin1 file.
> 
> How can I test that?
> (sometimes easy tasks becomes hard for non developers like me)

	:set fenc
	fileencoding=latin1

Vim will show "[converted]" when opening the file.  If you don't see
that either your version of Vim lacks something, or your setup doesn't
allow it.  Specifically the 'fileencodings' option.

-- 
GALAHAD: No. Look, I can tackle this lot single-handed!
GIRLS:   Yes, yes, let him Tackle us single-handed!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by victorhck** [comment]
In tutor.es file I run `:set fileencoding=latin1` and saved the file. and pushed a new commit.
Now in tutor.es file, I see [converted] at bottom, and if I run `set fenc` I get `fileencoding=latin1`
In tutor.es.utf-8 file, if I run `set fenc` I get `fileencoding=utf-8

**Comment by brammool** [comment]
Now it looks OK.  Thanks, I'll include it.

**Comment by victorhck** [comment]
a pleasure!
Thanks for your work!

**Pull request closed without merging**
