### PR TITLE
Resolve more size_t to in warnings on Windows

### PR DESCRIPTION
**Pull request by mrdubya**
Next round of warnings reduction on Windows.

### CODE REVIEW

**Comment by mrdubya** [comment]
Investigating ...

**Comment by chrisbra** [comment]
seems like you reverted back Patch 9.1.0399. It should be int, otherwise the value cannot get negative.

**Comment by mrdubya** [comment]
Yup, you're right. It is that line that is throwing a size_t to int warning on Windows. I'll try something else.

**Comment by mrdubya** [comment]
Rats. Not having a good day. The expression involves three different integer types, and different platforms/compilers complain about different combinations. Sometimes a cast has to be used ... :(

**Comment by mrdubya** [comment]
Ok, that seems to have worked bar one flaky test failing.  Commit of all casts - I feel dirty. Still, Windows builds are warning free ... for now.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
