### PR TITLE
Increases the max numberwidth to 20

### PR DESCRIPTION
**Pull request by shtanton**
This is based on an [issue](https://github.com/neovim/neovim/issues/4722) opened on neovim but makes more sense to fix it here.

### CODE REVIEW

**Comment by brammool** [comment]
Why would anyone ever want such a wide number column?  
Using NUMBUFLEN as the maximum doesn't make any sense.

**Comment by shtanton** [comment]
NUMBUFLEN was suggested in the original issue on neovim.
As I understand it, it is used a lot for char buffers that contain numbers, and someone else recently increased the size of the string to 57 bytes in neovim so 65 wasn't much of a stretch.

I totally respect that this is overkill and it'll be a looong time before computers have enough RAM for line numbers to get here.

The buffer was 18 bytes before, how about I leave that alone but still increase the maximum value for numberwidth to 17?

**Comment by andymass** [comment]
Comment by the `extra[18];` says "%ld" and 'fdc' must fit in here, which seems wrong anyway since long can be 20 chars and fdc can be up to 12.

**Comment by shtanton** [comment]
I don't have a lot of C experience, but my understanding is:
long is up to 19 characters, plus the space, plus the null.
So I thought extra would need to be 21 bytes.

**Pull request closed without merging**
