### PR TITLE
Update spec syntax

### PR DESCRIPTION
**Pull request by ghost**
Add [weak dependencies](https://fedoraproject.org/wiki/Packaging:WeakDependencies) syntax highlighting.

### CODE REVIEW

**Comment by chrisbra** [comment]
please discuss with the syntax file maintainer

**Comment by igor-raits** [comment]
I would throw away `Last change` field, otherwise +1 as from maintainer side.

**Comment by igor-raits** [comment]
@brammool merge please.

**Comment by brammool** [comment]
Igor Gnatenko wrote:

> @brammool merge please.

I prefer to get the updated file from the maintainer.  That way I avoid
getting out of sync.

## 

DINGO: Wicked wicked Zoot ... she is a bad person and she must pay the
       penalty.  And here in Castle Anthrax, we have but one punishment
       ... you must tie her down on a bed ... and spank her.  Come!
GIRLS: A spanking!  A spanking!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
I am closing this, as this has to be fixed by the runtime file maintainer. Feel free to create a new issue, if the maintainer is not reachable.

**Pull request closed without merging**
