### PR TITLE
WIP: Fix codecov  [skip appveyor]

### PR DESCRIPTION
**Pull request by blueyed**
/cc @chrisbra

### CODE REVIEW

**Comment by blueyed** [comment]
Looks like the "Cannot open source file misc2.c" from gcov is not really fatal.

But it makes sense to use the same `.gcov` files as with coveralls anyway I guess.

But then I've also noticed with another project that `gcov` should be rather run per `.gcno` file (which is what codecov-bash appears to be doing (https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L955)), not sure about cpp-coveralls - this could explain flaky coverage with coveralls.

**Comment by blueyed** [comment]
Well, with codecov `.gcov` files might also overwrite themselves.
See https://github.com/awesomeWM/awesome/blob/c4ff89a5fe1a8829d801c196ff45319a75d8a9b1/.travis.yml#L178-L198 for a method to upload/generate them per .gcno file.
(but it does not really need multiple uploads to codecov - changed in a pending PR for that project)

**Comment by chrisbra** [comment]
what problem are you trying to fix here?

**Comment by blueyed** [comment]
Have you read the comment and code with https://github.com/awesomeWM/awesome/blob/c4ff89a5fe1a8829d801c196ff45319a75d8a9b1/.travis.yml#L178-L198 ?
`gcov` generates multiple output files, which might overwrite themselves.
Therefore I think they should be put into subdirs.  But I am not really sure, it's just what I've noticed with another C project.

**Comment by blueyed** [comment]
(This PR's code is not really relevant (yet) - I've just thought that the `cd` might be bad already in the first place).

Feel free to close this, I do not plan to work on this soon.

But I would say that this might help with flaky coverage.

**Comment by brammool** [comment]
Well, in it's current form this PR is not useful, so if you don't plan to work on this we might as well close it.
The codecov.io flakyness appears on individual pull requests, but on submitted patches it doesn't appear to be so bad.

**Comment by blueyed** [comment]
Just for reference: on https://codecov.io/gh/vim/vim/branch/master/commits you can see that coverage is rather flaky.
I think https://github.com/gcovr/gcovr/ is a good tool for running gcov properly, and can generate a coverage.xml file to be uploaded to codecov then.  See https://github.com/neovim/neovim/blob/master/ci/common/submit_coverage.sh.

**Pull request closed without merging**
