### PR TITLE
WIP: l10n(zh_TW): update translations

### PR DESCRIPTION
**Pull request by pan93412**
## Progress
- [x] Start project
- [ ] Review all the translation
- [ ] Re-add the header
- [ ] Generate zh_TW.po (BIG5)

If you are interested in this project, please open a
issue in this translation repository (tw-translation/vim:master)
that I can allocate the part you have to translate.

Thanks for you guys help.

### CODE REVIEW

**Comment by k-takata** [comment]
>  * [ ] Generate zh_TW.po (BIG5)

As I wrote in another PR (https://github.com/vim/vim/pull/3261#discussion_r205970404), it might be better to create a tool to insert backslashes where needed (based on `sjiscorr.c`).

**Comment by pan93412** [comment]
>  it might be better to create a tool to insert backslashes where needed

Hmm? I don't know what is it mean.

**Comment by k-takata** [comment]
See the comment in the original translation:

```
# DO NOT USE WORDS WITH BACKSLASH ('\') AS SECOND BYTE OF BIG5 CHARS
# EG: '功', # 許功蓋
# [blacklist: 餐枯閱珮穀跚淚躡豹擺璞縷髏吭歿俞]
# [blacklist: 娉崤黠孀廄琵愧鈾暝么吒苒塿踊]
# you can replace these characters with alternative words.
# THIS WILL CAUSE INCOMPATIBLE ON gettext 0.10.36+
```

The code of `功` is 0xA55C in big5, the second byte is 0x5C which is same as backslash `\`.
Very very old version of gettext doesn't handle this kind of characters well. It handles `功` as a byte 0xA5 and a real backslash. So, the second byte causes a problem. To work around this, we should add a backslash after the character: `功\`.

Recent versions of gettext doesn't have this issue. However, for the backward compatibility, we set two environment variables: `OLD_PO_FILE_INPUT=yes` and `OLD_PO_FILE_OUTPUT=yes`. Because of this, we still need to add `\` after such characters.

One of the Japanese encodings (sjis (or cp932)) has the same issue. So we use [`sjiscorr.c`](https://github.com/vim/vim/blob/master/src/po/sjiscorr.c).
We translate the messages file `ja.po` with UTF-8, then convert it to sjis (cp932) with `iconv`, but the result contains many problematic characters ended with 0x5C. Then we use `sjiscorr.c` to add 0x5C after them.

See the Makefile for how to do this:
https://github.com/vim/vim/blob/b434ae2a1fcbbd43244c6130451de7f14346e224/src/po/Makefile#L77-L86

**Comment by pan93412** [comment]
> > * [ ]  Generate zh_TW.po (BIG5)
> 
> As I wrote in another PR ([#3261 (comment)](https://github.com/vim/vim/pull/3261#discussion_r205970404)), it might be better to create a tool to insert backslashes where needed (based on `sjiscorr.c`).

But the original po file say: 
> `# DO NOT USE WORDS WITH BACKSLASH ('\') AS SECOND BYTE OF BIG5 CHARS`

So can I add it? I don't know.

**Comment by k-takata** [comment]
> But the original po file say:
> 
> > `# DO NOT USE WORDS WITH BACKSLASH ('\') AS SECOND BYTE OF BIG5 CHARS`
> 
> So can I add it? I don't know.

The original po was simply converted the encoding to big5.
E.g. `iconv -f utf-8 -t big5 zh_TW.UTF-8.po | sed -e 's/charset=UTF-8/charset=big5' > zh_TW.po`
If you use this way, you should not use the blacklisted characters in your translation.

If you can create a filter program like `sjiscorr` (e.g. `big5corr`) that appends backslash after the blacklisted characters, you can use the characters.
E.g. `iconv -f utf-8 -t big5 zh_TW.UTF-8.po | ./big5corr > zh_TW.po`

It depends on you which way to use.

**Comment by k-takata** [comment]
I created a patch for you:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/cbd1de08dc88236138da5d9b030edf7e1f6bd65e/big5corr.patch?fileviewer=file-view-default
I created `big5corr` based on `sjiscorr`.
If you merge this patch, the blacklisted characters should be also used. (I haven't test this with the real translation data, though.)

**Comment by pan93412** [comment]
> I created a patch for you:
> https://bitbucket.org/k_takata/vim-ktakata-mq/src/cbd1de08dc88236138da5d9b030edf7e1f6bd65e/big5corr.patch?fileviewer=file-view-default
> I created `big5corr` based on `sjiscorr`.
> If you merge this patch, the blacklisted characters should be also used. (I haven't test this with the real translation data, though.)
> 
> EDIT: After you update `zh_TW.UTF-8.po`, run `make` in the `src/po/` directory. Then `zh_TW.po` will be automatically updated.

Oh, Thanks very much! I'll try that after I translated. :-)

**Comment by hungte** [comment]
Hi, this is Hung-Te, the original zh-TW po creator. Probably the original email server has stopped working - that I didn't see your mail, sorry. I can help checking if the changes here make sense.

**Comment by brammool** [comment]
What is the status of this PR?

**Comment by pan93412** [comment]
I have something to do and there aren't really much time for me to complete the remaining translations. I think, if someone want to help me complete that, then I'll be appreciated.

Or, I might do it after I've done coreutils and complete my project. Thanks to @brammool for caring this.

**Pull request closed without merging**
