### PR TITLE
Update xdiff from Git 2.33 to Git 2.40 (latest)

### PR DESCRIPTION
**Pull request by ychin**
I have started to play around with the diff code in Vim, and noticed that Vim's xdiff was last updated in 2021 (#8431), so just starting a PR to sync from upstream to make sure we have the latest code from Git.  I didn't see any significant breaking changes in the commits other than mostly optimizations and cleanups.

The commits in this PR are intentionally structured so that you can look at the merge history to see what I have done. 8f73594 and 9ef24f0 represent the Git raw 2.33 and 2.40 files respectively. I performed the merge in 48c97ae to combine Vim's changes and 2.40 updates.

```
* 98ffcb778d 2023-03-17 23:50:23 Yee Cheng Chin (HEAD -> xdiff-upstream-git-2.40, origin/xdiff-upstream-git-2.40) Update xdiff README
*   48c97ae3b5 2023-03-17 23:52:03 Yee Cheng Chin Merge commit '9ef24f022b2c920bc25730a7540a8a2ac180b23f' into xdiff-upstream-git-2.40
|\  
| * 9ef24f022b 2023-03-17 23:15:36 Yee Cheng Chin Git xdiff 2.40
* | bbce569280 2023-03-17 23:16:59 Yee Cheng Chin Add back Vim local xdiff changes (on top of Git 2.33.0)
|/  
* 8f7359444a 2023-03-17 23:13:42 Yee Cheng Chin Git xdiff 2.33
* 76739ad62b 2023-03-17 23:12:00 Yee Cheng Chin Remove existing xdiff code to prepare for a merge
```

Feel free to do `vimdiff <(git diff -U0 8f7359444a..bbce569280) <(git diff -U0 9ef24f022b..48c97ae3b5)` to review the diff of diffs to see what changed in terms of patch on top of Git.

Main merge conflicts:

- Git xdiff now uses `calloc`, which I just bound to `lalloc_clear`
- Vim used to add a manual check for out-of-memory issue in `find_longest_common_sequence` in xpatience.c to satisfy Coverity, but upstream added explicit checks for this now, so I removed the Vim-custom code.

Also, this comment (https://github.com/vim/vim/pull/8431#issuecomment-909051892) by @chrisbra mentioned a refactoring to make upstream merging easier in the future, but it didn't seem to have been merged. Since this upstream sync wasn't too painful I propose we could add that after this.

### CODE REVIEW

**Comment by ychin** [comment]
FWIW I'm thinking of porting Neovim's diffopt's "linematch" (https://github.com/neovim/neovim/pull/14537) and/or better diff highlighting, similar to how VSCode highlights diff chunks and Git's word-diff mode (which exist outside of xdiff).

**Comment by ychin** [comment]
> * Git xdiff now uses `calloc`, which I just bound to `lalloc_clear`

I think technically `calloc(n, size)` behaves differently from `malloc(n * size); memset(0,...)`, because if `n` is too large, calloc can pre-emptively return an error rather than malloc which could have overflow issues. It would only matter if `n` is huge though, and the old Git xdiff code just did the equivalent of `malloc(n * size)` anyway.

**Comment by brammool** [comment]
I'll include it, except for xmerge.c, since the only exported function  xdl_merge() is unused.

**Comment by ychin** [comment]
I wonder if we should just delete xmerge.c if we don't plan to track from upstream (and maybe update README). The Makefile doesn't even build it anyway so it's essentially unused. Keeping an outdated file could make it confusing for future merges. Given that we haven't really made any modifications to xmerge.c, we could always pull it from Git source code in the future if we decide we want merge functionality in Vim.

**Comment by brammool** [comment]
> I wonder if we should just delete xmerge.c if we don't plan to track
> from upstream (and maybe update README). The Makefile doesn't even
> build it anyway so it's essentially unused. Keeping an outdated file
> could make it confusing for future merges. Given that we haven't
> really made any modifications to xmerge.c, we could always pull it
> from Git source code in the future if we decide we want merge
> functionality in Vim.

Where do you see an outdated xmerge.c file?  AFAIK we never included
this file.

-- 
You cannot propel yourself forward by patting yourself on the back.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ychin** [comment]
Oh crap you are right. Thanks for double-checking. I got confused myself.

**Pull request closed without merging**
