### PR TITLE
travis: Update to trusty

### PR DESCRIPTION
**Pull request by k-takata**
* Set dist explicitly.
* Install ruby-dev.
* Update lua to newer version.
* Run `rvm reset` to use the default version of ruby. (Link fails without this.)

### CODE REVIEW

**Comment by brammool** [comment]
Ken Takata wrote:

> * Set dist explicitly.
> * Install ruby-dev.
> * Update lua to newer version.
> * Run `rvm reset` to use the default version of ruby. (Link fails without this.)

It no longer fails on Ruby, but can't find GTK:

	checking --disable-gtktest argument... gtk test enabled
	checking for pkg-config... /usr/bin/pkg-config
	no

It falls back to Athena, but that fails to start with:

Warning: Missing charsets in String to FontSet conversion

and:

Caught exception in Test_1_set_secure(): Vim(gui):E665: Cannot start GUI, no valid font found @ function RunTheTest[24]..Test_1_set_secure, line 2

This works just fine on my Ubuntu machine.

-- 
"Time flies like an arrow".  So I put an arrow on my desk, now
awaiting one of these time flies showing up.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jamessan** [comment]
There's no explicit enabling/disabling of GUI testing in the Travis config, so it's just relying on whatever happens to be in the environment.  It would be better to explicitly install the required packages to build one of the GUIs and explicitly enable/disable building the GUI in relevant parts of the build matrix.

Then there wouldn't be haphazard build issues as Travis changes the environment.

**Comment by nuko8** [comment]
> Caught exception in Test_1_set_secure(): Vim(gui):E665: Cannot start GUI, no valid font found @ function RunTheTest[24]..Test_1_set_secure, line 2

Since this test is run with the font `7x13`, one of the fonts which are usually installed as part of X11, there seems to be another issue on Travis side, too, in addition to the one pointed out by @jamessan.

The current Travis CI looks like as if one or a combination of the following happened:

1.  it hadn't created nor installed `/usr/X11R6/share/fonts/misc/fonts.alias`, and hence X11 couldn't identify `7x13` with its actual XLFD.
2.  The file differed from the one we usually have.
3. It hadn't installed the font file itself, so even after the alias was resolved, X11 couldn't load it.
4.  The font paths were not set property.
5.  All those preliminaries were done, but someone forgot to update lists or caches using `mkfontdir`,`mkfontscale` and `fc-cache`.

Anyway, it doesn't looks like the X11 was made fully operational for our GUI test.  So it's highly likely that the CI would still bother us even after implementing @jamessan 's idea...

**Comment by brammool** [comment]
Kazunobu Kuriyama wrote:

> > Caught exception in Test_1_set_secure(): Vim(gui):E665: Cannot start GUI, no valid font found @ function RunTheTest[24]..Test_1_set_secure, line 2
> 
> Since this test is run with the font `7x13`, one of the fonts which are usually installed as part of X11, there seems to be another issue on Travis side, too, in addition to the one pointed out by @jamessan.
> 
> The current Travis CI looks like as if one or a combination of the following happened:
> 
> 1.  it hadn't created nor installed `/usr/X11R6/share/fonts/misc/fonts.alias`, and hence X11 couldn't identify `7x13` with its actual XLFD.
> 2.  The file differed from the one we usually have.
> 3. It hadn't installed the font file itself, so even after the alias was resolved, X11 couldn't load it.
> 4.  The font paths were not set property.
> 5.  All those preliminaries were done, but someone forgot to update lists or caches using `mkfontdir`,`mkfontscale` and `fc-cache`.
> 
> Anyway, it doesn't looks like the X11 was made fully operational for our GUI test.  So it's highly likely that the CI would still bother us even after implementing @jamessan 's idea...

Let me switch back to precise for now, since currently all builds are
failing.  I hope someone can spend some time on a pull request to figure
out the right configuration for trusty.

-- 
ARTHUR: Right! Knights! Forward!
   ARTHUR leads a charge toward the castle.  Various shots of them battling on,
   despite being hit by a variety of farm animals.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
