### PR TITLE
CI: Re-enable snd-dummy on Ubuntu

### PR DESCRIPTION
**Pull request by ichizok**
* Enable snd-dummy and sound tests
* Replace `apt` with `apt-get` according to the warning: `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

### CODE REVIEW

**Comment by pheiduck** [comment]
I have worked on this as well:
https://github.com/vim/vim/pull/11092

**Comment by pheiduck** [comment]
coverity should also be updated then.

**Comment by pheiduck** [comment]
And if I am correct @brammool wants to have tagged Version for Ubuntu CI

**Comment by ichizok** [comment]
@pheiduck Sorry, I missed your PR.
I changed the focus of this PR to re-enabling snd-dummy and sound tests.

**Comment by brammool** [comment]
It looks like this PR does not depend on another, so let me include this first.
I hope that the other PR can be synced to head without trouble.

**Pull request closed without merging**
