### PR TITLE
runtime: recognize sway file types

### PR DESCRIPTION
**Pull request by ribru17**
See https://github.com/FuelLabs/sway. Comments taken from their syntax documentation. File extension taken from the same documentation/GitHub's own recognition of these file types

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. What is the difference to swayconfig? 
ping @jamespeapen @litoj fyi

**Comment by ribru17** [comment]
My understanding (which could be incorrect) is that sway config is for configuring the sway window manager (https://swaywm.org/) while this PR is for the sway programming language which is for some garbage blockchain nonsense

**Comment by chrisbra** [comment]
> some garbage blockchain nonsense

🤣 Now the question is, why should we include some blockchain nonsense :)

**Comment by jamespeapen** [comment]
> My understanding (which could be incorrect) is that sway config is for configuring the sway window manager (https://swaywm.org/) while this PR is for the sway programming language which is for some garbage blockchain nonsense

Yes - vim's current swayconfig is for the Wayland window manager and it does not have an official file extension.
I have not heard of this PR's filetype before but it is unrelated.

**Comment by ribru17** [comment]
> > some garbage blockchain nonsense
> 
> 🤣 Now the question is, why should we include some blockchain nonsense :)

Lol good question; I thought it should be because the repo seems pretty popular and github itself at least recognizes the language, associating it with .sw files

**Pull request closed without merging**
