### PR TITLE
filetype: Debian devscripts configuration files are not recognized

### PR DESCRIPTION
**Pull request by Freed-Wu**
Problem:  Debian devscripts configuration files are not recognized
Solution: recognize devscripts.conf and .devscripts files as sh filetype
          (sourced by /bin/sh)

### CODE REVIEW

**Comment by chrisbra** [comment]
@jamessan do you approve?

**Comment by jamessan** [comment]
These files are a small subset of sh syntax -- just comments and variable assignment. Using sh filetype will work, even if it's too liberal in what it accepts.

**Comment by chrisbra** [comment]
> These files are a small subset of sh syntax -- just comments and variable assignment. Using sh filetype will work, even if it's too liberal in what it accepts.

I think we don't have anything other than the "shell" filetype for such a restricted "shell dialect". I leave that decision to include this to you @jamessan Whatever you prefer, I will commit :)

**Review by jamessan — APPROVED** [review]

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
