### PR TITLE
add pytest linter

### PR DESCRIPTION
**Pull request by Konfekt**
likely requires @mgedmin 's copyright approval and @tpict 's for ftplugin default

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks, but can you please update the failing test?

**Comment by Konfekt** [comment]
@mgedmin Would you mind hinting at why the environment variable to disable warnings is needed, instead of say simply passing `--disable-warnings`?

**Comment by chrisbra** [comment]
please squash in the following change:
```diff
diff --git a/src/testdir/test_compiler.vim b/src/testdir/test_compiler.vim
index b7315e1b8..0a841bc06 100644
--- a/src/testdir/test_compiler.vim
+++ b/src/testdir/test_compiler.vim
@@ -71,10 +71,10 @@ func Test_compiler_completion()
   call assert_match('^"compiler ' .. clist .. '$', @:)

   call feedkeys(":compiler p\<C-A>\<C-B>\"\<CR>", 'tx')
-  call assert_match('"compiler pandoc pbx perl\( p[a-z_]\+\)\+ pylint pyunit', @:)
+  call assert_match('"compiler pandoc pbx perl\( p[a-z_]\+\)\+ pylint pytest pyunit', @:)

   call feedkeys(":compiler! p\<C-A>\<C-B>\"\<CR>", 'tx')
-  call assert_match('"compiler! pandoc pbx perl\( p[a-z_]\+\)\+ pylint pyunit', @:)
+  call assert_match('"compiler! pandoc pbx perl\( p[a-z_]\+\)\+ pylint pytest pyunit', @:)
 endfunc

 func Test_compiler_error()
```

**Comment by Konfekt** [comment]
```
Failures: 
	From test_alot.vim:
	Found errors in Test_compiler_completion():
	command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[613]..function RunTheTest[57]..Test_compiler_completion line 6: Pattern '"compiler pandoc pbx perl\\( p[a-z_]\\+\\)\\+ pylint pyunit' does not match '"compiler pandoc pbx perl perlcritic php pip_compile podchecker powershell pylint pytest pyunit'
	command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[613]..function RunTheTest[57]..Test_compiler_completion line 9: Pattern '"compiler! pandoc pbx perl\\( p[a-z_]\\+\\)\\+ pylint pyunit' does not match '"compiler! pandoc pbx perl perlcritic php pip_compile podchecker powershell pylint pytest pyunit'
```

I don't grasp immediately what this check tries to ensure. Must `pytest` be placed before `pylint` somehow?

**Comment by Konfekt** [comment]
Oh, I misread. I rather have to fix the test than the code in the PR. Why not let it end with `pyunit` instead ?

**Comment by Konfekt** [comment]
Oh, thank you, @chrisbra , I read your squash request to late, but I think we came to the same conclusion

**Comment by chrisbra** [comment]
yes, I think it is fine.

**Comment by mgedmin** [comment]
> likely requires @mgedmin 's copyright approval and @tpict 's for ftplugin default

For the &errorformat bits from my .vimrc?  I hereby place them in public domain, or whatever wording works for "use them as you see fit".

**Comment by Konfekt** [comment]
In the above-mentioned PR to downstream, I added a refinement to unsetting the compiler

**Pull request closed without merging**
