### PR TITLE
if_python: Fix python312

### LINKED ISSUE #13281: if_python3.c(499) warning C4273 py3_PyBool_Type
Hello

When Vim 9.0.1984 is compiled with msvc C/C++ version 19.29.30140, there is a warning: 
```
if_python3.c(499): warning C4273 py3_PyBool_Type : inconsistent dll linkage
Python310\Include\boolobject.h(10): see previous definition of 'py3_PyBool_Type'

```

### PR DESCRIPTION
**Pull request by k-takata**
Close #13281

Py_SIZE() uses PyLong_Type and PyBool_Type starting from Python 3.12. We need to define our own Py_SIZE() to replace Py{Bool,Long}_Type with py3_Py{Bool,Long}_Type.
We also need to redefine PyTuple_GET_SIZE() and PyList_GET_SIZE(), because they use Py_SIZE().

### CODE REVIEW

**Comment by k-takata** [comment]
I saw a report that using Python 3.12 on macOS failed with the following error:

```
ld: Undefined symbols:
  _py3_PyBool_Type, referenced from:
      _DictionaryUpdate in if_python3.o
      _PyList_GET_SIZE in if_python3.o
      _PyTuple_GET_SIZE in if_python3.o
  _py3_PyLong_Type, referenced from:
      _DictionaryUpdate in if_python3.o
      _PyList_GET_SIZE in if_python3.o
      _PyTuple_GET_SIZE in if_python3.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [vim] Error 1
make: *** [first] Error 2
```
This PR also fix this.

**Comment by ychin** [comment]
Just for reference this is where the stable ABI path remaps the macros to just call the functions themselves:

https://github.com/vim/vim/blob/ac9c6d5c786a016ca1dce297d167a5a963881f7e/src/if_py_both.h#L153-L156

**Comment by k-takata** [comment]
Actually, I'm wondering if we need to support non-stable-ABI implementation for Python 3.8 or later.

**Comment by ychin** [comment]
Yeah this is a good question. When I did the PR I kept backwards compatibility because it made sense to have a way to revert back to the old behavior, and it's quite useful for testing. It probably also makes sense to not use if you aren't using a dynamic build since you already know what lib you are linking against but even then it's not that big of a difference.

Technically, the non-stable ABI is a little faster (e.g. the Py_SIZE macro in question here), and the object types are structs defined in the header instead of opaque types that you have to allocate in heap through pre-defined APIs. I'm not sure if Vim's Python bindings are doing so much that it actually matters though. If you set the minimum compatible Python version (Py_LIMITED_API) to be higher (3.11) it will take advantage of more recent APIs as well.

**Comment by ychin** [comment]
Ok. I still stand by what I suggested in the above comment though. I think it's just much simpler to bind the `PyTuple_GET_SIZE` macro to a `PyTuple_Size` function call and avoid having to copy-and-paste from some Python headers that may change in the future. I may do another PR and discuss it there.

**Pull request closed without merging**
