### PR TITLE
Update Italian langauge for NSIS

### PR DESCRIPTION
**Pull request by bovirus**
@ichizok 

Fixed some issues (use english term like default, directory, poup menu) and change verbs in third person.

Checked and fxied issues about string truncate why too long.

Please check and merge.

### CODE REVIEW

**Comment by bovirus** [comment]
@ichizok

I updated the NSIS instalelr language  file.
I shared the translations with Antion that was agree about them.
Please merge and close the PR.

**Comment by brammool** [comment]
There are no changes to the installer itself, best to review is Antonion Colombo @azc100

**Comment by bovirus** [comment]
@azc100

please confirm to Bram that the file posted is as we shared.

Thanks.

**Comment by azc100** [comment]
Hi Bram,

Yes, I am aware that there are no modifications to the Installation
software itself.
This is just an update that introduces a better Italian translation for a
few of the statements.
And, as Roberto states, it has been reviewed by me before being sent to you.

As far as I can tell, it is OK to put it into the Vim distribution.

As a side matter, I realized (speaking with Roberto) that the src/po/it.po
file has not been updated since last August. I am preparing a new version,
which I will send you as soon as it is ready.

Thanks and all the best, Antonio


Il giorno sab 13 mag 2023 alle ore 16:19 Bram Moolenaar <
***@***.***> ha scritto:

**Comment by brammool** [comment]
> Yes, I am aware that there are no modifications to the Installation
> software itself.

I made that remark for Ozaki Kiichi, who was referred to.

> This is just an update that introduces a better Italian translation for a
> few of the statements.
> And, as Roberto states, it has been reviewed by me before being sent to you.
> 
> As far as I can tell, it is OK to put it into the Vim distribution.

Thanks for checking.

> As a side matter, I realized (speaking with Roberto) that the src/po/it.po
> file has not been updated since last August. I am preparing a new version,
> which I will send you as soon as it is ready.

That will be very good.

-- 
Give a man a computer program and you give him a headache,
but teach him to program computers and you give him the power
to create headaches for others for the rest of his life...
        R. B. Forest

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
