### PR TITLE
update po headers as per scootergrisen request

### PR DESCRIPTION
**Pull request by vvizzo**
As an official translator of Vim updated headers of po files for Polish (all three encodings: UTF-8, cp1250, iso-8859-2) as per scootergrisen suggestions.

### CODE REVIEW

**Comment by chrisbra** [comment]
Are there no new translated messages?

**Comment by vvizzo** [comment]
No, just headers unified with scootergrisen suggestions.

**Comment by brammool** [comment]
> As an official translator of Vim updated headers of po files for
> Polish (all three encodings: UTF-8, cp1250, iso-8859-2) as per
> scootergrisen suggestions.

Thanks.

-- 
Amazing but true: If all the salmon caught in Canada in one year were laid
end to end across the Sahara Desert, the smell would be absolutely awful.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Included in https://github.com/vim/vim/commit/6dc819b1299e1d9f99303568772ade544d5c1322. Closing.

**Pull request closed without merging**
