### PR TITLE
vim9script: fix import autoload 'foo.vim' in case of symlink

### LINKED ISSUE #508: `<c-n>` on some LSP completion options triggers an "Item not found ... ParseMarkdown" error
H, there. I'm not sure when this started happening, but I typed:

```
<style>
.title {
    border-
```

and then hit `<c-n>` to scroll through the list of completions. It seems to scroll correctly, but there is this error for every time I scroll:

```
Error detected while compiling CompleteChanged Autocommands for "<buffer=1>"..function <SNR>43_LspResolve[11]..<SNR>43_ShowCompletionDocumentatio
n[59]..FileType Autocommands for "*"..function <SNR>19_LoadFTPlugin[18]..script /nix/store/9ywm4gggqcwacn30qbjp5apqwk57zzkc-lsp/ftplugin/lspgfm.v
im[76]..function <SNR>123_RenderGitHubMarkdownText:
line   16:
E1048: Item not found in script: ParseMarkdown
```

`ft` is set to `html` in this file.

### LINKED ISSUE #14775: [vim9script] imported autoloaded functions might not exist
### Steps to reproduce

1. Put this in `~/.vim/autoload/foo.vim`:
   ```
   vim9script
   
   echo "autoloading foo.vim"
   
   export def Foo()
       echo "Foo"
   enddef
   ```
   and put that in `~/.vim/plugin/foo.vim`:
   ```
   vim9script
   
   import autoload 'foo.vim'
   
   def Setup()
       foo.Foo()
   enddef
   
   nnoremap <leader>S <ScriptCmd>Setup()<CR>
   nnoremap <leader>F <ScriptCmd>foo.Foo()<CR>
   ```
2. Start vim
3. Type `<leader>S`. This produces the errors:
   ```
   Error detected while compiling function <SNR>17_Setup:
   line    1:
   E1048: Item not found in script: Foo
   ```
4. Type `<leader>F`. This echos:
   ```
   autoloading foo.vim
   Foo
   ```
5. Quit and restart vim
6. Type `<leader>F`. This echos:
   ```
   autoloading foo.vim
   Foo
   ```
7. Type `<leader>S`. This works this time and echos:
   ```
   Foo
   ```

Notes:
- Appending `defcompile` to the end of `plugin/foo.vim` produces the error on startup and then `<leader>S` consistently fails even if typed after `<leader>F` (which still works).
- Replacing the call `foo.Foo()` in `Setup()` with `foo#Foo()` works and the `autoloading foo.vim` is echoed only when `<leader>S` is typed for the first time (if done before `<leader>F` of course) but in that case the import is not needed (except for the `<leader>F` mapping).

### Expected behaviour

No error should be printed and `Foo` should be echoed independently of the order of invocation of the mappings.

Or the documentation should be updated to clarify how autoloaded imports should be used.

### Version of Vim

9.1.412

### Environment

OS: Ubuntu 22.04
terminal: tmux 3.5 in GNOME Terminal 3.44.0
$TERM: tmux-256color
shell: bash 5.1.16(1)-release

```
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled May 15 2024 09:40:09)
Included patches: 1-412
Compiled by odormond@LAP-CH-607-LIN
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             +xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "~/.config/vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/odormond/.local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -fno-strength-reduce -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lelf 
```

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Item can't be found in script imported like `import autoload 'foo.vim'` when first used in the call of compiled function, because the scripttitem for real file used in `compile_load_scriptvar` lacks autoload prefix.  

fixes #14775 
fixes https://github.com/yegappan/lsp/issues/508

### CODE REVIEW

**Comment by chrisbra** [comment]
@yegappan do you agree?

**Comment by yegappan** [comment]
I am not able to reproduce the problem described in #14775.  When I follow the steps described in that issue, I don't see any errors and the auloaded function works properly.

**Comment by nwounkn** [comment]
I noticed that #14775 doesn't mention `~/.vim` being a symlink to another directory. That's when I get the error.

**Comment by Konfekt** [comment]
>  ~/.vim being a symlink to another directory

This is likely it

**Review by yegappan — APPROVED** [review]

**Comment by yegappan** [comment]
I am able to reproduce the issue after using a symbolic link for the `.vim` directory.  The PR looks good to me.

**Comment by chrisbra** [comment]
thanks.

**Pull request closed without merging**
