### PR TITLE
Deverse

### PR DESCRIPTION
**Pull request by jmullman**
This may or may not cut it insofar as the [contribution guidelines](https://github.com/vim/vim/blob/master/CONTRIBUTING.md) go, since runtime files are in kind of a gray area.

That being said, these files have been edited to remove religious text.

### CODE REVIEW

**Comment by vim-ml** [comment]
James Mitchell Ullman (Vim Github Repository) wrote:

> That being said, these files have been edited to remove religious text.
> 
> Thank Goddess!

:-)

I wonder, at times, how well contributions from other mythologies would 
be welcomed.  Good to see such nipped before getting out-of-hand.

**Comment by grochmal** [comment]
Well, DrChip (the maintainer of that file) works at the Catholic University.

But moreover, the [netrw on DrChip's page](http://www.drchip.org/astronaut/vim/#NETRW) is several versions ahead (162a instead of 156) of the one in the Vim repo.  DrChip is certainly reading this, it is wise to contact him explicitly since a next version of netrw submitted into the Vim repo may simply overwrite your changes.

**Comment by esiegerman** [comment]
Agreed in principle.  Note, though, that the change deletes some start-fold markers -- `{{{1` and the like -- but not the corresponding end-fold markers.  I'd suggest restoring the deleted starts (as standalone comment lines, if need be), _not_ finding and deleting the (now-unmatched) ends.

**Comment by cecamp** [comment]
No, I will not accept these changes.

**Pull request closed without merging**
