### PR TITLE
Fix disassemble for instructions with optional static:

### PR DESCRIPTION
**Pull request by errael**
Fix disassemble for instructions with optional static:
ISN_GET_OBJ_MEMBER and ISN_GET_ITF_MEMBER

### CODE REVIEW

**Comment by errael** [comment]
@yegappan disassemble fix for optional static. I too a quick look at the disassemble tests and didn't quite get it. I can look some more if it's needed. Are there any helper scripts for doing this?

Here's an excerpt with showing the change.
```
$ grep -E 'OBJ|ITF' xxx
   1 ITF_MEMBER 0 on I [STATIC]
   4 ITF_MEMBER 0 on I
   7 ITF_MEMBER 1 on I [STATIC]
  10 ITF_MEMBER 1 on I
   1 OBJ_MEMBER 0 [STATIC]
   4 OBJ_MEMBER 0
   7 OBJ_MEMBER 1 [STATIC]
  10 OBJ_MEMBER 1
```

**Review by yegappan — APPROVED** [review]

**Comment by yegappan** [comment]
> @yegappan disassemble fix for optional static. I too a quick look at the disassemble 
> tests and didn't quite get it. I can look some more if it's needed. 
> Are there any helper scripts for doing this?
> 
> Here's an excerpt with showing the change.
>

Can you share the Vim9 script that generated the below instructions?

> 
> ```
> $ grep -E 'OBJ|ITF' xxx
>    1 ITF_MEMBER 0 on I [STATIC]
>    4 ITF_MEMBER 0 on I
>    7 ITF_MEMBER 1 on I [STATIC]
>   10 ITF_MEMBER 1 on I
>    1 OBJ_MEMBER 0 [STATIC]
>    4 OBJ_MEMBER 0
>    7 OBJ_MEMBER 1 [STATIC]
>   10 OBJ_MEMBER 1
> ```

**Comment by errael** [comment]
> the Vim9 script that generated the ... instructions?
```
vim9script
interface I
    public static s_var: number
    public this.o_var: number
    public static s_var2: number
    public this.o_var2: number
endinterface
class C implements I
    public static s_var: number     #<<<<< 
    public this.o_var: number       #<<<<<
    public static s_var2: number
    public this.o_var2: number
endclass

def F1(i: I)
    var x: number
    x = i.s_var
    x = i.o_var
    x = i.s_var2
    x = i.o_var2
enddef

def F2(o: C)
    var x: number
    x = o.s_var
    x = o.o_var
    x = o.s_var2
    x = o.o_var2
enddef

disa F1
disa F2
```

**Comment by yegappan** [comment]
I have created the PR https://github.com/vim/vim/pull/13037 with a disassemble test for this.

**Pull request closed without merging**
