### PR TITLE
Fix warnings about NSStringPboardType being deprecated in macOS 10.14

### PR DESCRIPTION
**Pull request by ghost**
I got warnings about NSStringPboardType being deprecated when compiling vim in macOS 10.14.

You can wait to merge this when macOS 10.14 is officially released.

The suggested replacement to use by Apple is the "NSPasteboardTypeString", which as far as I know and tested, work the same as the older type.

Here are the warnings for reference:

```

os_macosx.m:67:6: warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
            NSStringPboardType, nil];
            ^~~~~~~~~~~~~~~~~~
            NSPasteboardTypeString
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:320:32: note: 'NSStringPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSStringPboardType NS_DEPRECATED_WITH_REPLACEMENT_MAC("NSPasteboardTypeString", 10_0, 10_14);
                               ^
os_macosx.m:98:22: warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
                [[pb stringForType:NSStringPboardType] mutableCopy];
                                   ^~~~~~~~~~~~~~~~~~
                                   NSPasteboardTypeString
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:320:32: note: 'NSStringPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSStringPboardType NS_DEPRECATED_WITH_REPLACEMENT_MAC("NSPasteboardTypeString", 10_0, 10_14);
                               ^
os_macosx.m:182:3: warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
                NSStringPboardType, nil];
                ^~~~~~~~~~~~~~~~~~
                NSPasteboardTypeString
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:320:32: note: 'NSStringPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSStringPboardType NS_DEPRECATED_WITH_REPLACEMENT_MAC("NSPasteboardTypeString", 10_0, 10_14);
                               ^
os_macosx.m:189:31: warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
        [pb setString:string forType:NSStringPboardType];
                                     ^~~~~~~~~~~~~~~~~~
                                     NSPasteboardTypeString
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:320:32: note: 'NSStringPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSStringPboardType NS_DEPRECATED_WITH_REPLACEMENT_MAC("NSPasteboardTypeString", 10_0, 10_14);
                               ^
4 warnings generated.
```

### CODE REVIEW

**Comment by chdiza** [comment]
Is this going to break compilation on older versions of macOS?

**Comment by ghost** [comment]
On systems older than OS X 10.6.

If needed, I can check for OS X < 10.6 and use the older type to maintain compatibility.

**Comment by chdiza** [comment]
> If needed, I can check for OS X < 10.6 and use the older type to maintain compatibility.

Yes.

**Comment by ghost** [comment]
Done. I don't have a system with 10.5 or older though so I can't guarantee that it doesn't break compilation on 10.5 or older.

**Comment by kencu** [comment]
Hi! Turns out this does break 10.5 and older, and over at MacPorts we have some avid users of those older PPC machines that are still humming along pleasantly, and who love vim. Please see <https://trac.macports.org/ticket/56994> and <https://github.com/macports/macports-ports/pull/2740>

I have always found Apple's nomenclature for this rather vague and non-obvious, but the macro you want to use to see if you can use features that exist only in a newer SDK would be this:
```
#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
   do_new_sdk_stuff();
#else
    do_old_sdk_stuff();
#endif

**Comment by ghost** [comment]
@kencu: Thanks for the heads up. You're right, Apple wasn't really clear on which macro to use and I no longer had a 10.5 system to test it on.

Here's a patch that uses your suggestion, please test if you do have access to a 10.5 system or older:

```patch
diff --git a/src/os_macosx.m b/src/os_macosx.m
index 752bdae11..50ca361fb 100644
--- a/src/os_macosx.m
+++ b/src/os_macosx.m
@@ -63,7 +63,7 @@ clip_mch_request_selection(VimClipboard *cbd)
     NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
 
     NSPasteboard *pb = [NSPasteboard generalPasteboard];
-#ifdef AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
     NSArray *supportedTypes = [NSArray arrayWithObjects:VimPboardType,
 	    NSPasteboardTypeString, nil];
 #else
@@ -99,7 +99,7 @@ clip_mch_request_selection(VimClipboard *cbd)
     {
 	/* Use NSPasteboardTypeString.  The motion type is detected automatically.
 	 */
-#ifdef AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
 	NSMutableString *mstring =
 		[[pb stringForType:NSPasteboardTypeString] mutableCopy];
 #else
@@ -188,7 +188,7 @@ clip_mch_set_selection(VimClipboard *cbd)
 
 	/* See clip_mch_request_selection() for info on pasteboard types. */
 	NSPasteboard *pb = [NSPasteboard generalPasteboard];
-#ifdef AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
 	NSArray *supportedTypes = [NSArray arrayWithObjects:VimPboardType,
 		NSPasteboardTypeString, nil];
 #else
@@ -201,7 +201,7 @@ clip_mch_set_selection(VimClipboard *cbd)
 	NSArray *plist = [NSArray arrayWithObjects:motion, string, nil];
 	[pb setPropertyList:plist forType:VimPboardType];
 
-#ifdef AVAILABLE_MAC_OS_X_VERSION_10_6_AND_LATER
+#if MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
 	[pb setString:string forType:NSPasteboardTypeString];
 #else
 	[pb setString:string forType:NSStringPboardType];
```

**Comment by ghost** [comment]
I can't seem to re-open this PR, but @brammool: Can you please include the patch?

Thanks!

**Comment by kencu** [comment]
Great! - that patch looks identical to mine, except for the MacPorts default patchlevel.  <https://github.com/macports/macports-ports/pull/2740/commits/b918f32ffd46a19ba3d25a84f66f4716bac2aaef#diff-23aa6c80a367a2dec5cedb6c1cffe901>. I confirm it works on 10.4 and 10.5, and also does the right  thing on 10.14

**Pull request closed without merging**
