### PR TITLE
Problem:    Hollywood syntax highlighting is not up to date.

### PR DESCRIPTION
**Pull request by sodero**
Solution:   Update Hollywood syntax highlighting with 9.1 additions.

### CODE REVIEW

**Comment by chrisbra** [comment]
did you contact the maintainer of the script? He doesn't seem to be on github...

**Comment by sodero** [comment]
> did you contact the maintainer of the script? He doesn't seem to be on github...

I've tried, but I haven't got an answer. But we've had an exchange about upstreaming in the past and he was very positive when the current 9.0 file was integrated.

**Comment by brammool** [comment]
Would Tom Crecelius be OK with listing you as the maintainer, while he remains the author?
That makes the situation clearer.  You will then need to take care of reported issues somehow.
If we can add your user ID to CODEOWNERS that also helps.

**Comment by sodero** [comment]
> Would Tom Crecelius be OK with listing you as the maintainer, while he remains the author? That makes the situation clearer. You will then need to take care of reported issues somehow. If we can add your user ID to CODEOWNERS that also helps.

I'll do my best to get in contact with him and see what he thinks. For me it's no problem to take care of reported issues. I'll let you know as soon I succeed or fail.

**Comment by sodero** [comment]
@brammool Tom Crecelius is OK with your suggestion, so I changed the maintainer to myself.

**Comment by brammool** [comment]
Thanks, I'll include it now and it will be part of the next runtime files update.
Please check after that if something went missing (had a warning in the merge, but I think it ended up OK).

**Comment by sodero** [comment]
> Thanks, I'll include it now and it will be part of the next runtime files update. Please check after that if something went missing (had a warning in the merge, but I think it ended up OK).

Excellent, thanks! I'll double check after the next update.

**Pull request closed without merging**
