### PR TITLE
v:last_reg global variable as feature request #12003

### PR DESCRIPTION
**Pull request by cero1988**
added global variable v:last_reg with the latested putted register as feature request #12003

### CODE REVIEW

**Comment by brammool** [comment]
We should have a more generic mechanism for commands previously executed.  The operator used is also relevant.  Making a list of them will also be useful.

I sometimes type something different from what I intended, it would then be good to be able to see what happened, the last few commands executed.  At least for changes, possibly also for other commands.  E.g. if you wonder why a window was closed.

**Comment by cero1988** [comment]
you mean like :history, but with the post operator commands used ?

**Comment by brammool** [comment]
> you mean like :history, but with the post operator commands used ?

The :history command only keeps command lines, as text.
That's probably the best we can do for Ex commands, since they are
largely unstructured.

For Normal mode commands we do have some structure, such as the count,
the register, movement command, operator, etc.  I'm not sure what would
be useful to provide.  Alternatively a list of commands as text could be
provided.  For operators that's often what is in the redo buffer.  But
it may get complicated, e.g. when using the Visual area.

-- 
What is the difference between a professional and an amateur?
The ark was built by an amateur; professionals gave us the Titanic.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cero1988** [comment]
I could create a new history like :history nvcmd with all the last normal mode command used, for the non printable keys i could translate the more commonly used like the Arrow keys in text

**Comment by chrisbra** [comment]
I am closing this one for inactivity. If you ever create a new :history command for normal mode commands, please create a new PR then. thanks.

**Pull request closed without merging**
