### PR TITLE
Unicode: Update Unicode Tables to Unicode Release 13

### PR DESCRIPTION
**Pull request by chrisbra**
Unicode v.13 has been released last year in March. So let's update the character tables to this release.

### CODE REVIEW

**Comment by brammool** [comment]
Please adjust the indent of the ambiguous table, so we can see what actually changed.

The change to emoji_wide[] drops a lot of intervals, how did that happen?

**Comment by chrisbra** [comment]
> Please adjust the indent of the ambiguous table, so we can see what actually changed.

Okay, this was caused by a unicode.vim, which did not account for differences in the two tables. So adjusted unicde.vim accordingly and the ambiguous table did not change.

> The change to emoji_wide[] drops a lot of intervals, how did that happen?

Most of the emojis were dropped because they are already part of doublewidth table. I think in the past, we simply haven't updated that table because it seemed wrong to drop most of those entries.

**Comment by brammool** [comment]
Thanks for the update.
Still a bit surprised that some wide emoji entries are removed.  Take the first few:
```
-	{0x23ed, 0x23ef},
-	{0x23f1, 0x23f2},
-	{0x23f8, 0x23fa},
-	{0x24c2, 0x24c2},
```

These are gaps in  the doublewidth table:
```
	{0x23e9, 0x23ec},
	{0x23f0, 0x23f0},
	{0x23f3, 0x23f3},
	{0x25fd, 0x25fe},
```

I recall that these entries were guessed, based on what I've seen.  E.g. the 0x23ed character is single width in my xterm, but double width in the GUI: ⏭  And 0x23f1 is a clock: ⏱  In my xterm I only see the left half.

**Comment by chrisbra** [comment]
okay, let's revert the emoji_wide table then.

**Pull request closed without merging**
