### PR TITLE
Better Haskell support

### PR DESCRIPTION
**Pull request by coot**
* Added `cabalproject` filetype & syntax file
* Added `cabalconfig` filetype & syntax file
* Recognise `*.hsc` files either as haskell or hamster files.

### CODE REVIEW

**Comment by coot** [comment]
@dfishburn you might want to review this PR if the proposed changes will still correctly recognise `*.hsc` files as `hamster` filetype.

**Comment by k-takata** [comment]
The CODEOWNERS needs to be updated.

```diff
--- a/.github/CODEOWNERS
+++ b/.github/CODEOWNERS
@@ -112,6 +112,8 @@ runtime/syntax/asm.vim			@dkearns
 runtime/syntax/asmh8300.vim		@dkearns
 runtime/syntax/awk.vim			@dkearns
 runtime/syntax/bst.vim			@tpope
+runtime/syntax/cabalconfig.vim		@coot
+runtime/syntax/cabalproject.vim		@coot
 runtime/syntax/csh.vim			@cecamp
 runtime/syntax/cucumber.vim		@tpope
 runtime/syntax/dcl.vim			@cecamp
```

**Review by dfishburn — COMMENTED** [review]
If Haskell files are .hsc, I would suggest we redirect those to the Haskell filetype, and leave hsm files as Hamster.  I doubt many people use Hamster files.
So yes, this code looks fine.

**Comment by coot** [comment]
Only some `Haskell` files use `.hsc` extension,, but they are not that uncommon. Every larger projects is using some bindings to some `C` library and most often `.hsc` files are involved.  It makes sense to use `*.hsc` for `Haskell` by default.

**Comment by coot** [comment]
I opened PR #7354 to map `*.hsc` files to `haskell`.

**Comment by brammool** [comment]
Ken Takata wrote:

> The CODEOWNERS needs to be updated.
> 
> ```diff
> --- a/.github/CODEOWNERS
> +++ b/.github/CODEOWNERS
> @@ -112,6 +112,8 @@ runtime/syntax/asm.vim			@dkearns
>  runtime/syntax/asmh8300.vim		@dkearns
>  runtime/syntax/awk.vim			@dkearns
>  runtime/syntax/bst.vim			@tpope
> +runtime/syntax/cabalconfig.vim		@coot
> +runtime/syntax/cabalproject.vim		@coot
>  runtime/syntax/csh.vim			@cecamp
>  runtime/syntax/cucumber.vim		@tpope
>  runtime/syntax/dcl.vim			@cecamp
> ```

Already done, will go out with the next runtime files update.

-- 
Not too long ago, a program was something you watched on TV...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by coot** [comment]
Please add a line `runtime/syntax/haskell.vim @coot` to the `CODEOWNERS` file.

**Comment by coot** [comment]
```diff
diff --git a/.github/CODEOWNERS b/.github/CODEOWNERS
index 929447d77..3c1b1ebf7 100644
--- a/.github/CODEOWNERS
+++ b/.github/CODEOWNERS
@@ -112,6 +112,8 @@ runtime/syntax/asm.vim                      @dkearns
 runtime/syntax/asmh8300.vim            @dkearns
 runtime/syntax/awk.vim                 @dkearns
 runtime/syntax/bst.vim                 @tpope
+runtime/syntax/cabalconfig.vim         @coot
+runtime/syntax/cabalproject.vim                @coot
 runtime/syntax/csh.vim                 @cecamp
 runtime/syntax/cucumber.vim            @tpope
 runtime/syntax/dcl.vim                 @cecamp
@@ -123,6 +125,7 @@ runtime/syntax/gitcommit.vim                @tpope
 runtime/syntax/gitconfig.vim           @tpope
 runtime/syntax/gitrebase.vim           @tpope
 runtime/syntax/haml.vim                        @tpope
+runtime/syntax/haskell.vim             @coot
 runtime/syntax/hgcommit.vim            @k-takata
 runtime/syntax/lex.vim                 @cecamp
 runtime/syntax/liquid.vim              @tpope
```

**Comment by brammool** [comment]
I'll do that.

**Pull request closed without merging**
