### PR TITLE
Fix file type of pacman.conf and pacman hook files.

### PR DESCRIPTION
**Pull request by chaoren**
They're just generic configuration files with # comments.

pacman.conf example:
https://archlinux.org/pacman/pacman.conf.5.html#_example

hook file example:
https://man.archlinux.org/man/alpm-hooks.5#EXAMPLES

dosini has ; comments, so that's not correct.

### CODE REVIEW

**Comment by brammool** [comment]
Please also update src/testdir/test_filetype.vim

**Comment by chaoren** [comment]
Done. Sorry, didn't realize they had tests.

**Comment by Mudskipper875** [comment]
The `conf` filetype seems to be bit lacking for these files. Since only the
semicolon comments are a problem, perhaps a new filetype can be created for
them since several common programs other than pacman have config files with a
similar format. Off the top of my head, the ones I can recall are mpv, vlc,
htop, i3blocks, dunst, qbittorrent, pcmanfm, xdg-mime (mimeapps.list),
xfce4-terminal and several more.

**Comment by brammool** [comment]
What could we use as a common name for (config) files with semicolon comments?

**Comment by Mudskipper875** [comment]
The programs I listed above have config files *without* semicolon comments, I
apologise if I wasn't being clear.

---
This is the config file format for such programs
```ini
[section]
option = value
option2=value2

# Comment
```

Currenty, the **dosini** and **cfg** filetypes have compatible syntax highlighting for
the above format. The only problem is that **dosini** has `#` and `;` comments and
**cfg** has `#`, `;` and `//` comments.

Currently there is a [**config**](https://github.com/vim/vim/blob/master/runtime/syntax/config.vim) filetype which seems to be used only for a couple of
[autoconf files](https://github.com/vim/vim/blob/3fcccf94e8bc142d2c79c3b62087145896df6b36/runtime/filetype.vim#L402). I suggest renaming `config.vim` to `autoconf.vim` and using
config.vim for files with above format.

**Comment by chaoren** [comment]
I think they're just the Unix variant of INI files?

https://en.wikipedia.org/wiki/INI_file#Comments_2

We could call it `unixini.vim` (as opposed to `dosini`) or just `ini.vim`?

**Comment by chaoren** [comment]
My main gripe with it being `dosini` was that [`commentstring` was set to `;`](https://github.com/vim/vim/blob/master/runtime/ftplugin/dosini.vim), so plugins that use it (e.g., [vim-commentary](https://github.com/tpope/vim-commentary)) don't behave correctly.

It looks like [`cfg` sets `commentstring` to `#`](https://github.com/vim/vim/blob/master/runtime/ftplugin/cfg.vim) and since you say they have compatible syntax highlighting, maybe we should just use `cfg` instead?

**Comment by brammool** [comment]
> The programs I listed above have config files *without* semicolon comments, I
> apologise if I wasn't being clear.
> 
> ---
> This is the config file format for such programs
> ```ini
> [section]
> option = value
> option2=value2
> 
> # Comment
> ```
> 
> Currenty, the **dosini** and **cfg** filetypes have compatible syntax
> highlighting for the above format. The only problem is that **dosini**
> has `#` and `;` comments and
> **cfg** has `#`, `;` and `//` comments.

It sounds like these should have separate filetypes then.
They do have in common that a header has the form "[section]" ?

> Currently there is a [**config**](https://github.com/vim/vim/blob/master/runtime/syntax/config.vim) filetype which seems to be used only for a couple of
> [autoconf files](https://github.com/vim/vim/blob/3fcccf94e8bc142d2c79c3b62087145896df6b36/runtime/filetype.vim#L402). I suggest renaming `config.vim` to `autoconf.vim` and using
> config.vim for files with above format.

Renaming filetypes always causes trouble for those using the old name.
Currently "config" is used for autoconf, we can keep it that way, even
though the name isn't a good choice.

The filetype used for generic configure files with "#" comments is
"conf".

So it seems we need a new name for "cfg" files, instead of using
"dosini".  Is ".editorconfig" one of those?

It appears some of these files used "dosini" just as a quick and dirty
solution.  It would be better to have a separate name for each filetype,
and then in the syntax/indent plugins source the dosini one until
something more accurate is done.

-- 
"After a few years of marriage a man can look right at a woman
without seeing her and a woman can see right through a man
without looking at him."
 - Helen Rowland

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Mudskipper875** [comment]
> It would be better to have a separate name for each filetype, and then in the syntax/indent plugins source the dosini one until something more accurate is done.

I agree. But perhaps the new filetype could temporarily source `cfg.vim` instead of `dosini.vim` since it addresses the [commentstring issue](https://github.com/vim/vim/pull/10213#issuecomment-1133504364) mentioned by @chaoren

> I think they're just the Unix variant of INI files (https://en.wikipedia.org/wiki/INI_file#Comments_2)?
> 
> We could call it `unixini.vim` (as opposed to `dosini`) or just `ini.vim`?
> 
> FYI, the pacman source calls it [a pacman-style INI config file](https://gitlab.archlinux.org/pacman/pacman/-/blob/master/src/common/ini.c#L29).

As @chaoren said, we could call the new filetype `unixini.vim` or maybe `confini.vim`/`configini.vim`

The `cfg.vim` filetype currently seems to be used by default only for [Mercurial config files](https://github.com/vim/vim/blob/bfaa24f95343af9c058696644375d04e660f1b00/runtime/filetype.vim#L1136).
I found some programs with config files which have `cfg.vim` manually set with a modeline - such as Dunst ([dunstrc](https://github.com/dunst-project/dunst/blob/3bba0b01f924a4af9c2a0b13125446153f3d4125/dunstrc#L445)) and Ranger ([rifle.conf](https://github.com/ranger/ranger/blob/aaf032252e428a1f0d2f3c6f742811f7f4b880c2/ranger/config/rifle.conf#L1)).  I think even these configs only support `#` comments, so a new filetype will be an improvement for them.

> Is ".editorconfig" one of those?

".editorconfig" uses the proper `dosini.vim` syntax ([editorconfig.org](https://editorconfig.org/))

**Comment by Mudskipper875** [comment]
Done (#10518).

**Pull request closed without merging**
