### PR TITLE
Run DO_AUTOCHDIR (honoring &acd option) when writing an unnamed buffer for the first time.

### LINKED ISSUE #777: PWD not changed to follow buffer when writing a new file when &autochdir is on
The working directory doesn't follow the buffer when it should, after writing a new file from a new buffer.

This seems like it's related to issue #704 
## Steps to reproduce:
1. Start vim from home directory with no arguments: `vim -N -u NONE`
2. `:set autochdir`
3. `:w /tmp/new_file.temp`
## Outcome:

The `%` register is set to "/tmp/new_file.temp" but the `:pwd` command gives the directory you started vim in.
## Expected outcome:

The `%` register should be set to "new_file.temp" and the `:pwd` command should give "/tmp".

Further information:

vim 7.4.1752
Linux

### PR DESCRIPTION
**Pull request by misterfish**
Hi, this is intended to fix #777.

@h3xx Does this seem right to you now and can you think of unforeseen side-effects?

### CODE REVIEW

**Comment by h3xx** [comment]
You may want to surround this with `#ifdef FEAT_AUTOCHDIR`. I don't really know, I'm not in touch with vim's source code. I base this entirely on [this patch](https://github.com/vim/vim/issues/704#issuecomment-206510880).

**Comment by misterfish** [comment]
I don't think it's necessary -- it's already guarded in macros.h:

```
#ifdef FEAT_AUTOCHDIR
# define DO_AUTOCHDIR if (p_acd) do_autochdir();
#else
# define DO_AUTOCHDIR
#endif
```

**Comment by brammool** [comment]
Mister fish wrote:

> Hi, this is intended to fix #777.
> 
> @h3xx Does this seem right to you now and can you think of unforeseen side-effects?

Thanks.  Can we please have your real name?

## 

BEDEVERE: And that, my lord, is how we know the Earth to be banana-shaped.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by misterfish** [comment]
On Fri, May 20, 2016 at 09:17:06AM -0700, Bram Moolenaar wrote:

> Mister fish wrote:
> 
> > Hi, this is intended to fix #777.
> > 
> > @h3xx Does this seem right to you now and can you think of unforeseen side-effects?
> 
> Thanks.  Can we please have your real name?

No problem: ‘Allen Haim’

Grts.

**Comment by misterfish** [comment]
I accidentally closed this pull request when I deleted my local branch.

If desired I can make a new one :p

**Pull request closed without merging**
