### PR TITLE
Port the NeoVim changes to add foldopen, foldclose and foldsep chars to 'fillchars'

### PR DESCRIPTION
**Pull request by yegappan**
Port the following:
https://github.com/neovim/neovim/pull/11568

### CODE REVIEW

**Comment by nickspoons** [comment]
Unfortunately, this does not work with multi-byte characters, which is the only real use-case I can see for the feature. If I try with the example given in the neovim PR (`set fillchars+=foldopen:▾,foldsep:│,foldclose:▸`), terminal vim displays � for the `foldopen` and `foldclose` characters, and nothing for the `foldsep` char.

```sh
vim -Nu NONE -S <(cat <<'EOF'
    set fillchars+=foldopen:▾,foldsep:│,foldclose:▸
    set foldmethod=marker foldcolumn=3 foldlevel=1
    setf vim
EOF
) <(cat <<'EOF'
    " a: {{{
    " b: {{{
    " }}}
    " }}}
EOF
)
```

Displays the following in termite:
screenshot-2021-02-18_104225

And in xterm:
screenshot-2021-02-18_104801

I am testing in linux, I don't have the environment to build on windows but can test a [nightly release](https://github.com/vim/vim-win32-installer/releases) when it becomes available.

**Comment by yegappan** [comment]
Currently multibyte character is not supported for the foldopen, foldclose and foldsep items in
the 'fillchars' option. I will look into porting that support from NeoVim.

**Comment by vim-ml** [comment]
Hi,

On Wed, Feb 17, 2021 at 1:50 PM Nick Jensen <vim-dev-github@256bit.org>
wrote:

> Unfortunately, this does not work with multi-byte characters, which is the
> only real use-case I can see for the feature. If I try with the example
> given in the neovim PR (set fillchars+=foldopen:▾,foldsep:│,foldclose:▸),
> terminal vim displays � for the foldopen and foldclose characters, and
> nothing for the foldsep char.
>
> I am testing in linux, I don't have the environment to build on windows but can test a nightly release <https://github.com/vim/vim-win32-installer/releases> when it becomes available.
>
>
>
The support for using multibyte characters for 'foldopen', 'foldclose' and
'foldsep' items in 'fillchars' has now been added (8.2.2563).
Can you try the latest build?

Thanks,
Yegappan

**Comment by nickspoons** [comment]
screenshot-2021-03-04_094318

Looks great! Thanks Yegappan ❤️

**Pull request closed without merging**
