### PR TITLE
CI: m1/arm64 rm --disable-channel

### PR DESCRIPTION
**Pull request by pheiduck**
maybe we have again failing tests here...

### CODE REVIEW

**Comment by brammool** [comment]
I sent out a fix the the test that ignores /private on only one string.

The failure in Test_quit_long_message we have seen before.  In your PR, can you change the value from "rows" from 6 to 10 so that we can see the error that is hiding now?

**Comment by brammool** [comment]
Hmm, the dump diff correctly says that the number of lines differs, but that's not what we wanted to see.
Let me make a patch, it might be useful to see more lines whenever the test fails.

**Comment by pheiduck** [comment]
@brammool it's ready to merge

**Comment by brammool** [comment]
Merged as Patch 9.0.0596 (reference was missing in the submit)

**Pull request closed without merging**
