### PR TITLE
Update __FUNCTION__ in C syntax

### PR DESCRIPTION
**Pull request by hitched97**
__FUNCTION__ is not only for gnu.

### CODE REVIEW

**Comment by brammool** [comment]
It's not clear why you want to make this change.   __func__ is the C99 symbol, __FUNCTION__ is not in a standard, only some compilers support it, and the recommendation is to use __func__ for new code.  Although it appears MSVC doesn't support it.

**Comment by hitched97** [comment]
I note `__func__` also appears in the `if exists("c_gnu")` block, and, as you say, it's part of the C standard.

**Comment by brammool** [comment]
> I note `__func__` also appears in the `if exists("c_gnu")` block, and,
> as you say, it's part of the C standard.

The code is:

if !exists("c_no_ansi") || exists("c_ansi_constants") || exists("c_gnu")
...
  if !exists("c_no_c99")
    syn keyword cConstant __func__ __VA_ARGS__

Thus unless "c_no_ansi" and "c_no_c99" are set by the user, then
__func__ is highlighted.


-- 
hundred-and-one symptoms of being an internet addict:
240. You think Webster's Dictionary is a directory of WEB sites.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by hitched97** [comment]
Ah, gotcha, did not see the later occurrence.

**Pull request closed without merging**
