### PR TITLE
[WIP] src/Make_all.mak: define NEW_TESTS automatically

### PR DESCRIPTION
**Pull request by blueyed**
It adds test_shortpathname, and test_user_func - which appear to have
been forgotten to add.

Used the following to compare the output (NEW_TESTS2 being the new one):

    $(shell printf '%s\n' $(NEW_TESTS) > 1)
    $(shell printf '%s\n' $(NEW_TESTS2) > 2)
    $(error $(shell echo $(NEW_TESTS) | wc -c) $(shell echo $(NEW_TESTS2) | wc -c))

TODO:
- [ ] rename test_eval_func to not having to filter it out?

### CODE REVIEW

**Comment by k-takata** [comment]
`Make_dos.mak` should work with `nmake`. Changing it to GNU make is not acceptable.

**Comment by blueyed** [comment]
Yeah, too bad - closing this then, since it does not appear to be trivial to make it compatible.

It was mainly meant to make merging with Neovim easier, but there it can be used (hopefully): https://github.com/neovim/neovim/pull/8909

**Comment by blueyed** [comment]
Just for completeness, those diff would / might have been possible on top then:


```diff
 src/testdir/Make_all.mak | 134 ++---------------------------------------------
 src/testdir/README.txt   |   4 +-
 2 files changed, 5 insertions(+), 133 deletions(-)

diff --git a/src/testdir/Make_all.mak b/src/testdir/Make_all.mak
index 45f45d7fd..9084ebb23 100644
--- a/src/testdir/Make_all.mak
+++ b/src/testdir/Make_all.mak
@@ -62,137 +62,11 @@ SCRIPTS_GUI =
 
 
 # Tests using runtest.vim
-# Keep test_alot*.res as the last one, sort the others.
 # test_largefile.res is omitted, it uses too much resources to run on CI.
-NEW_TESTS = test_arabic.res \
-	    test_arglist.res \
-	    test_assert.res \
-	    test_autochdir.res \
-	    test_autocmd.res \
-	    test_autoload.res \
-	    test_backspace_opt.res \
-	    test_blockedit.res \
-	    test_breakindent.res \
-	    test_bufwintabinfo.res \
-	    test_cdo.res \
-	    test_changelist.res \
-	    test_channel.res \
-	    test_charsearch.res \
-	    test_cindent.res \
-	    test_clientserver.res \
-	    test_close_count.res \
-	    test_cmdline.res \
-	    test_command_count.res \
-	    test_comparators.res \
-	    test_crypt.res \
-	    test_cscope.res \
-	    test_curswant.res \
-	    test_diffmode.res \
-	    test_digraph.res \
-	    test_display.res \
-	    test_edit.res \
-	    test_erasebackword.res \
-	    test_escaped_glob.res \
-	    test_eval_stuff.res \
-	    test_exec_while_if.res \
-	    test_exists.res \
-	    test_exists_autocmd.res \
-	    test_exit.res \
-	    test_farsi.res \
-	    test_file_size.res \
-	    test_find_complete.res \
-	    test_fixeol.res \
-	    test_fnameescape.res \
-	    test_fold.res \
-	    test_getcwd.res \
-	    test_getvar.res \
-	    test_gf.res \
-	    test_gn.res \
-	    test_gui.res \
-	    test_gui_init.res \
-	    test_hardcopy.res \
-	    test_help.res \
-	    test_hide.res \
-	    test_highlight.res \
-	    test_history.res \
-	    test_hlsearch.res \
-	    test_iminsert.res \
-	    test_increment.res \
-	    test_increment_dbcs.res \
-	    test_ins_complete.res \
-	    test_job_fails.res \
-	    test_json.res \
-	    test_jumplist.res \
-	    test_langmap.res \
-	    test_let.res \
-	    test_lineending.res \
-	    test_listchars.res \
-	    test_listdict.res \
-	    test_listlbr.res \
-	    test_lua.res \
-	    test_makeencoding.res \
-	    test_man.res \
-	    test_maparg.res \
-	    test_marks.res \
-	    test_matchadd_conceal.res \
-	    test_mksession.res \
-	    test_nested_function.res \
-	    test_netbeans.res \
-	    test_normal.res \
-	    test_number.res \
-	    test_options.res \
-	    test_packadd.res \
-	    test_paste.res \
-	    test_perl.res \
-	    test_plus_arg_edit.res \
-	    test_preview.res \
-	    test_profile.res \
-	    test_prompt_buffer.res \
-	    test_python2.res \
-	    test_python3.res \
-	    test_pyx2.res \
-	    test_pyx3.res \
-	    test_quickfix.res \
-	    test_quotestar.res \
-	    test_regex_char_classes.res \
-	    test_registers.res \
-	    test_retab.res \
-	    test_ruby.res \
-	    test_scrollbind.res \
-	    test_search.res \
-	    test_shortpathname.res \
-	    test_signs.res \
-	    test_smartindent.res \
-	    test_spell.res \
-	    test_startup.res \
-	    test_stat.res \
-	    test_substitute.res \
-	    test_swap.res \
-	    test_syntax.res \
-	    test_system.res \
-	    test_tab.res \
-	    test_tcl.res \
-	    test_terminal.res \
-	    test_terminal_fail.res \
-	    test_textformat.res \
-	    test_textobjects.res \
-	    test_undo.res \
-	    test_user_func.res \
-	    test_usercommands.res \
-	    test_vartabs.res \
-	    test_viminfo.res \
-	    test_vimscript.res \
-	    test_visual.res \
-	    test_winbar.res \
-	    test_winbuf_close.res \
-	    test_window_id.res \
-	    test_windows_home.res \
-	    test_wordcount.res \
-	    test_writefile.res \
-	    test_xxd.res \
-	    test_alot_latin.res \
-	    test_alot_utf8.res \
-	    test_alot.res
+NEW_TESTS_ALOT = $(sort $(basename $(notdir $(wildcard test_alot_*.vim)))) test_alot
+NEW_TESTS_IN_ALOT = $(shell sed '/^source/ s/^source //;s/\.vim$$//' test_alot*.vim)
+# test_eval_func is special: used as include in old-style test (test_eval.in).
+NEW_TESTS = $(addsuffix .res,$(sort $(filter-out $(NEW_TESTS_ALOT) $(NEW_TESTS_IN_ALOT) test_largefile test_eval_func,$(basename $(notdir $(wildcard test_*.vim))))) $(NEW_TESTS_ALOT))
 
 
 # Explicit dependencies.
diff --git a/src/testdir/README.txt b/src/testdir/README.txt
index 7aa185f0a..d9d7ec8fe 100644
--- a/src/testdir/README.txt
+++ b/src/testdir/README.txt
@@ -14,9 +14,7 @@ can.  Use an old style test when it needs to run without the +eval feature.
 TO ADD A NEW STYLE TEST:
 
 1) Create a test_<subject>.vim file.
-2) Add test_<subject>.res to NEW_TESTS in Make_all.mak in alphabetical order.
-3) Also add an entry in src/Makefile.
-4) Use make test_<subject>.res to run a single test in src/testdir/.
+2) Use make test_<subject>.res to run a single test in src/testdir/.
    Use make test_<subject>  to run a single test in src/.
 
 What you can use (see test_assert.vim for an example):
```

**Comment by brammool** [comment]
Do you mean that Neovim doesn't build without GNU make installed?  Not very flexible...

**Comment by blueyed** [comment]
It appears so - good for easier merging at least.

**Comment by vim-ml** [comment]
Am Sa., 25. Aug. 2018 um 20:07 Uhr schrieb Bram Moolenaar
<vim-dev-github@256bit.org>:
>
> Do you mean that Neovim doesn't build without GNU make installed? Not very flexible...

Neovim's build system is very flexible, because it's defined in CMake.
That means the build supports Xcode, MSVC, ninja, etc., for free. We
haven't yet converted the Vim testdir tests to a CMake task, but the
3000+ unit/integration tests written in Lua are CMake-driven.

Eventually Vim will convert to CMake, just as Vim eventually moved to
GitHub and other day-zero steps taken by Neovim in 2014.

-- 
Justin M. Keyes

**Pull request closed without merging**
