### PR TITLE
configure options for enabling fips warning

### PR DESCRIPTION
**Pull request by zdohnal**
Hi,

few OSes already provide support for FIPS enablement on the system. FIPS standard defines only several 'safe' crypto algorithms, but Vim uses pk-zip, blowfish and blowfish2 encryptions, which are not among the safe algorithms defined by FIPS.
But I am aware many Vim users are satisfied with current Vim's cryptography and it is mentioned in help pages these cryptographic methods are not designed for protection of sensitive data, I would like you to consider adding this patch to Vim project. In my humble opinion it is valid compromise for current usage of Vim and FIPS.
The patch is about adding configure options (which are disabled by default) --enable-fips-warning (turns on FIPS warning), --with-system-fips-file=PATH (the link to system-fips file, applicable only when --enable-fips-warning is used and default path is /etc/system-fips) and --with-fips-enabled-file=PATH (the link to fips_enabled file, applicable only when --enable-fips-warning is used and default path is /proc/sys/crypto/fips_enabled).

The first option - --enable-fips-warning - enables FIPS warning, which is shown when:
- :X is used
- when user opens encrypted file
It looks this way (f.e. when blowfish2 cm is used):

Need encryption key for "test"
Warning: This cryptography is not FIPS140-2 compliant.
Enter encryption key: *

The warning is shown only when FIPS is installed and active, which is known to user if:
1) system-fips file exists
2) fips_enabled file contains '1'

That's the reason why two other configure options are there - --with-system-fips-file=PATH and --with-fips-enabled-file=PATH - I'm not sure if other OSes (tried on Fedora+RHEL) have different places for these files, so I created options for setting different paths for these two files.

I tested the new configure options manually (general run, when files are missing, when paths are configured to different files)+ I ran 'make test' (I regenerated configure file, configure Vim with huge features and enabled fips warning, then ran 'make' and 'make test') and they worked correctly. 

Would you mind adding this patch to Vim project?

### CODE REVIEW

**Comment by brammool** [comment]
This is not useful.  As I understand it there is a FIPS certification mechanism used by some people.  Thus one has to check that the system (not just a program) is certified.  Telling users something is not certified is quite pointless, since by default nothing is certified.  It would be useful to tell the user that what he is doing is FIPS certified, but that won't ever happen for Vim.

**Comment by zdohnal** [comment]
@brammool What is the point of saying that a program is FIPS certified in FIPS certified system or in system with FIPS module enabled? The patch is about integration of Vim (never will be FIPS certified - so let's warn them at least about it) into such systems. 
Because when you don't have FIPS enabled, you don't care if a program is FIPS compliant or not. And when you have FIPS enabled, you expect every program in system is FIPS compliant - in this case warning makes sense IMHO.

**Comment by tonymec** [comment]
@zdohnal 's arguments are not totally without merit, yet the proposed change looks a little pointless to me: Vim's encryption methods are not meant to protect users against a serious cryptographer with a fast computer and that's that — if you want really secure encryption (and if you believe that it is *possible* to get *really* secure encryption in today's world), don't use Vim for it, period.

@zdohnal : if you think you can write **and debug** an even better encryption subsystem in addition to the three Vim already has (and which are needed for compatibility with earlier versions of Vim), go ahead, Vim is free (as in speech) and open source code. Once such code is reasonably well tested and made part of Vim, it might be a little less pointless to warn about weak encryption methods.

Best regards,
Tony.

**Comment by zdohnal** [comment]
@tonymec Hi Tony,
I created the patch with your first paragraph in mind - Vim's cryptography is not meant to protect against serious attacker - that's why I did not try to create new cryptography for Vim. But even if I wrote the new algorithm, it still wouldn't be enough, because old algorithms would be still there and their removal (only way to make Vim FIPS compliant, AFAIK) would cause serious troubles for users during update.
With all mentioned above, I wrote the patch, which seemed like compromise for both sides. Vim could stay in FIPS certified system and Vim didn't have to design a new cryptography conforming FIPS. Maybe it is just me, but I cannot imagine system without Vim (at least Linux/Unix ones) :)

@brammool Would it be acceptable to change current message/add a message in crypt_check_method() function in src/crypt.c to (it will be shown for every encryption):

'Using encryption XY. See ':help 'cm''.'

and add into runtime/doc/options.txt a sentence (at the end of 'cm' help) similar to following:

'Encryptions mentioned above are not meant for protecting critical or sensitive data and they do not comply with existing security standards, e.g. FIPS 140-2.'

Would you mind considering such change, Bram?

Have a nice day,
Zdenek

**Comment by brammool** [comment]
> @tonymec Hi Tony,
> I created the patch with your first paragraph in mind - Vim's cryptography is not meant to protect against serious attacker - that's why I did not try to create new cryptography for Vim. But even if I wrote the new algorithm, it still wouldn't be enough, because old algorithms would be still there and their removal (only way to make Vim FIPS compliant, AFAIK) would cause serious troubles for users during update.
> With all mentioned above, I wrote the patch, which seemed like compromise for both sides. Vim could stay in FIPS certified system and Vim didn't have to design a new cryptography conforming FIPS. Maybe it is just me, but I cannot imagine system without Vim (at least Linux/Unix ones) :)
> 
> @brammool Would it be acceptable to change current message/add a message in crypt_check_method() function in src/crypt.c to (it will be shown for every encryption):
> 
> 'Using encryption XY. See ':help 'cm''.'
> 
> and add into runtime/doc/options.txt a sentence (at the end of 'cm' help) similar to following:
> 
> 'Encryptions mentioned above are not meant for protecting critical or sensitive data and they do not comply with existing security standards, e.g. FIPS 140-2.'
> 
> Would you mind considering such change, Bram?

If we make a list of all the standards that Vim does not support, I'm
sure it will get quite long.  Adding just one gives a false sense that
we even tried.

Certification works to add something to certain software, it should be
obvious that if the certification isn't claimed that the software does
not comply.

I also don't see how it matters, since you can still edit plain text,
right?  That's like the worst encryption possible.  Using ROT13 is
second best :-).

-- 
GOD: That is your purpose Arthur ... the Quest for the Holy Grail ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nmav** [comment]
I think FIPS may not be the right standard to reference. What @zdohnal is raising is that vim is giving a false sense of security to its users by claiming encryption capabilities. Would it help merge this patch if it printed instead (unconditionally):

 * `Warning: This cryptography is not secure; use gnupg instead.`

Why do I suggest this text? It's because vim provides an implementation of blowfish, but no unit tests or interoperability tests are performed, key derivation is undocumented; could be ok, though no-one can vet for it. Additionally, mixing application code with cryptography is considered bad practice (the first point is an indication on why that's bad), and furthermore blowfish is a relic of the past, could have been an interesting choice 20 years ago when the alternative is DES, though today there are options like AES which are considered the baseline.

**Comment by zdohnal** [comment]
I agree with @nmav , IMHO such warning is better than illusion of security given by current algorithms. 
When user uses pk_zip algorithm in Vim, Vim already warns him about algorithm being 'weak', which gives false sense of security of the other algorithms implemented in Vim are secure. IMHO such warning is relevant for all three cryptomethods - so Vim  could show:

"Warning: Using a weak encryption method; use external cryptographic tools for stronger encryption."

or

"Warning: Using a weak encryption method; see :help 'cm'"

and then in help pages can be:

"Encryptions mentioned above are not meant for protecting critical or sensitive data. Please use external cryptographic tools for stronger encryption."

**Comment by brammool** [comment]
> I think FIPS may not be the right standard to reference. What @zdohnal
> is raising is that vim is giving a false sense of security to its
> users by claiming encryption capabilities. Would it help merge this
> patch if it printed instead:
> 
>  * `Warning: This cryptography is not secure; use gnupg instead.`
> 
> Why do I suggest this text? It's because vim provides an
> implementation of blowfish, but no unit tests or interoperability
> tests are performed, key derivation is undocumented; could be ok,
> though no-one can vet for it. Additionally, mixing application code
> with cryptography is considered bad practice (the first point is an
> indication on why that's bad), and furthermore blowfish is a relic of
> the past, could have been an interesting choice 20 years ago when the
> alternative is DES, though today there are options like AES which are
> considered the baseline.

A warning is not very useful unless proper instructions are given for
at least one alternative.  It's very easy to use a strong encryptyion in
a way it discards protection (e.g. using temp files).  Also, since Vim
keeps plain text in memory and uses a swap file, it can't be guaranteed
safe in any way.  You probably need to encrypt the filesystem too.

There are already remarks that the built-in encryption is not guaranteed
to be strong enough.  Still, it gives a reasonable protection against a
normal third party.

-- 
If cars evolved at the same rate as computers have, they'd cost five euro, 
run for a year on a couple of liters of petrol, and explode once a day.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
