### PR TITLE
Runtime: update neomutt keywords

### PR DESCRIPTION
**Pull request by avidseeker**
neomutt.vim hasn't been updated for two years and neomutt folks have been refactoring a lot of the config.

@flatcap

### CODE REVIEW

**Comment by chrisbra** [comment]
@flatcap can you please ACK?

**Comment by avidseeker** [comment]
Also relevant to this PR: https://github.com/neomutt/neomutt/discussions/4369

**Comment by chrisbra** [comment]
Thanks, but I have a few comments:
1) If you submit a new runtime file on behalf of somebody else, I would really really appreciate a comment by the original creator, especially if he is mentioned as maintainer
2) please add a new filetype test around here: https://github.com/vim/vim/blob/7477861e0d1d4bb168a65585c49c66e57b3ec636/src/testdir/test_filetype.vim#L515
3) If `g:neolog_default_colors` is not set, I suppose one does not get any highlighting? Is that intended?
4) Can you please consolidate the Last Change header to use `YYYY <Short_Month_Name> DD`? That's what we generally prefer here.

**Comment by chrisbra** [comment]
let me close this here. If @neomutt maintainers want such a change in Vims repo, I suppose they can create a new PR then.

**Comment by flatcap** [comment]
Sorry for not replying sooner; I'm just back from a 3 month hiking expedition.

Thanks :heart: for your fixes, @avidseeker -- updating that file is hard work!
I'll merge them into [neomutt.vim](https://github.com/neomutt/neomutt.vim) and give the whole file a good review, then resubmit here.

**Comment by flatcap** [comment]
Superseded by #15858

**Pull request closed without merging**
