### PR TITLE
Update python.vim

### PR DESCRIPTION
**Pull request by ghost**
Stop overriding users' vimrc settings.

### CODE REVIEW

**Comment by chrisbra** [comment]
please discuss this with the maintainer of the file. Note, there exists several methods, for overriding filetype specific settings.

**Comment by vvizzo** [comment]
:help after

**Comment by ghost** [comment]
@chrisbra:
" Maintainer:   Johannes Zellner johannes@zellner.org
" Last Change By Johannes: Wed, 21 Apr 2004 13:13:08 CEST
It seems to me the "maintainer" has abandoned this file, since there hasn't been any activity by them in over a decade. Who then should I contact?

@vvizzo: I'm not sure how that helps. The topic found is "after-directory" which seems to be talking about that being, essentially, the last elements in vim's equivalent of $PATH... Creating a file there with set commands to overrule python.vim doesn't seem to work.

**Comment by tyru** [comment]
Hmm... I think workflow change is needed after all...
At least need to think ftplugins/indent plugins/etc. of abandoned maintainers. #594

**Comment by zvezdan** [comment]
@zonidjan The fact that the file hasn't been touched in a long time doesn't mean it's abandoned. It could simply mean there was nothing to change. The Python indentation or PEP-8 recommendations didn't change since then.
@tyru There's no indication that maintainer had been contacted at all in the comments above. Just the date on the file, which doesn't mean much more than the file being stable/mature.

The change proposed in this patch would affect most of the users negatively. That's probably the reason @chrisbra rejected it.

The patch creator wanted the settings from .vimrc to "win" over the plugin rules. What if the user does not set any preferences in .vimrc? The plugin **must** set the default `sw`, `sts`, ... in case user sets nothing. The users who activated the plugin in their .vimrc will get the standard settings automatically.

OTOH, it's very easy to override the plugin settings. You could add customizations in ~/.vim/ftplugin/python.vim, but for this it's not needed. According to the Vim docs, it can be done in .vimrc:

```
" File type dependent options
if has("autocmd")
    " Enable file type detection, plugins, and indentation rules.
    filetype plugin indent on
    " ... other file types here ...
    " C++, Java, Python: non-standard 2-space indent
    autocmd FileType cpp,java,python setl sw=2 sts=2 et
    " ... other content here ...
endif
```

**Comment by ghost** [comment]
I should be able to just stick "set sts=2" in my vimrc, and have it work. Not hunt through docs for hours trying to find how to set my own settings (the very name implies the program should only give defaults!). Not modify vim-provided files.
Oh, and it has nothing to do with "activating a plugin". All it takes is "syntax on" (if that). And that's commonly done by distros' default vimrc, too. (If not from source).

Regardless, the easiest solution should not be for me to add an auto-patch to my package manager to remove things from a /usr/share/\* files.

The issue here is not that python.vim modifies vim's own internal defaults to a new default.
The issue is that it overrides what I have in my own vimrc (system or user).

**Comment by chrisbra** [comment]
Trying to be constructive here, please refrain from starting to flame 
here. thanks.

As I said before, this needs to be discussed with the ftplugin file 
maintainer.
I could imagine, that he would accept a solution, if you don't 
unconditionally
delete those settings, but instead add a condition, that would not set 
these
options if a certain variable has been set.

so instead of
,----
| " As suggested by PEP8.
| setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=8
`----

use something like:

,----
| if !get(g:, 'python_set_pep8_options', 1)
|   " As suggested by PEP8.
|   setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=8
`----

So you would then set this variable in your .vimrc
let g:python_set_pep8_options=0
and be done with it.

However this should be documented below
:h ft-python-plugin

But as I said, this needs to be discussed with the ftplugin maintainer. 
He will
then send an updated filetype plugin for inclusion with Vim to Bram.

Regardless, you might want to read, when a ftplugin becomes active. It's 
not activated
on :syntax on. And No, you don't need (and shouldn't never need) to 
change
files below /usr/share/

Best,
Christian

Am 2016-07-27 07:07, schrieb John:

> I should be able to just stick "set sts=2" in my vimrc, and have it
> work. Not hunt through docs for hours trying to find how to set my own
> settings (the very name implies the program should only give
> defaults!). Not modify vim-provided files.
> Oh, and it has nothing to do with "activating a plugin". All it takes
> is "syntax on" (if that). And that's commonly done by distros' default
> vimrc, too. (If not from source).
> 
> Regardless, the easiest solution should not be for me to add an
> auto-patch to my package manager to remove things from a /usr/share/*
> files.
> 
> The issue here is not that python.vim modifies vim's own internal
> defaults to a new default.
> The issue is that it overrides what I have in my own vimrc (system or
> user).

**Comment by ghost** [comment]
Emailed maintainer as of July 27, no response back.

**Pull request closed without merging**
