### PR TITLE
Add changedtick variable to a quickfix/location list and the QuickFixChanged autocmd

### PR DESCRIPTION
**Pull request by yegappan**
When a plugin is asynchronously updating a quickfix list, if the user invokes a quickfix
command or another plugin incorrectly updates the quickfix list, it is not possible to
detect the unexpected change to the quickfix list.

Add a changedtick variable to a quickfix/location list which gets updated whenever
the quickfix list is modified.

Add a new QuickFixChanged autocmd which gets invoked every time a quickfix
list is modified and pass the quickfix list identifier.

### CODE REVIEW

**Comment by vim-ml** [comment]
Op 30 nov. 2017 07:44 schreef "Yegappan Lakshmanan" <
vim-dev-github@256bit.org>:

     res = qf_init(wp, p_ef, p_efm, (eap->cmdidx != CMD_caddfile
 			&& eap->cmdidx != CMD_laddfile), *eap->cmdlinep, enc);
+    if (wp != NULL)
+	qi = GET_LOC_LIST(wp);
+    if (res >= 0)
+	qf_list_changed(qi, qi->qf_curlist);
 #ifdef FEAT_AUTOCMD
     if (au_name != NULL)
 	apply_autocmds(EVENT_QUICKFIXCMDPOST, au_name, NULL, FALSE, curbuf);
 #endif


Could qi be NULL here?

Christ van Willegen

**Comment by vim-ml** [comment]
Hi,

On Wed, Nov 29, 2017 at 11:09 PM, Christ van Willegen
<cvwillegen@gmail.com> wrote:
>
>
> Op 30 nov. 2017 07:44 schreef "Yegappan Lakshmanan"
> <vim-dev-github@256bit.org>:
>
>      res = qf_init(wp, p_ef, p_efm, (eap->cmdidx != CMD_caddfile
>   && eap->cmdidx != CMD_laddfile), *eap->cmdlinep, enc);
> +    if (wp != NULL)
> + qi = GET_LOC_LIST(wp);
> +    if (res >= 0)
> + qf_list_changed(qi, qi->qf_curlist);
>  #ifdef FEAT_AUTOCMD
>      if (au_name != NULL)
>   apply_autocmds(EVENT_QUICKFIXCMDPOST, au_name, NULL, FALSE, curbuf);
>  #endif
>
>
> Could qi be NULL here?
>

It is theoretically possible that qi could be NULL. I have added a check for qi
and pushed the change.

- Yegappan

**Comment by yegappan** [comment]
Will separate out the changes for the changedtick quickfix list variable from the new autocmd changes and submit another pull request.

**Comment by lacygoill** [comment]
Hello,

is the `QuickFixChanged` event necessary to use this new variable `changedtick`? Because at the moment, I don't think it's available yet.

**Comment by vim-ml** [comment]
Hi,

On Sun, Feb 11, 2018 at 5:41 PM, lacygoill <vim-dev-github@256bit.org> wrote:
> Hello,
>
> is the QuickFixChanged event necessary to use this new variable changedtick?
>

No. The autocmd is not needed to use the changedtick variable
in the quickfix/location list.

>
> Because at the moment, I don't think it's available yet.
>

Are you able to get the changedtick variable value using the getqflist()
and getloclist() functions?

- Yegappan

**Comment by lacygoill** [comment]
@yegappan Ah ok, I thought the event was necessary. Sorry for the confusion. Yes, I can get the `changedtick` variable with:

    :echo getqflist({'changedtick': 1})

**Pull request closed without merging**
