### PR TITLE
get_number: add trailing newline with CR etc

### LINKED ISSUE #4972: get_number: missing newline
Using just `<Enter>` with the following command list (`call inputlist([1,2,3]) | call inputlist([4,5,6])`) shows:

```
1
2
3
Type number and <Enter> or click with mouse (empty cancels): 4
5
6
Type number and <Enter> or click with mouse (empty cancels):
```

It would be better if there was an implicit newline when just "<Enter>" is used, and also with selecting a number:
```
1
2
3
Type number and <Enter> or click with mouse (empty cancels): 1
4
5
6
Type number and <Enter> or click with mouse (empty cancels):
```

(I've noticed this with ultisnips which spawns several calls to `inputlist()` after each other - certainly a misfeature, but it would be nice to have newlines there inbetween then)

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/vim/vim/issues/4972.

There might be a better way, but the messaging system is not easy to wrap my head around.

### CODE REVIEW

**Comment by brammool** [comment]
Daniel Hahler wrote:

> Fixes https://github.com/vim/vim/issues/4972.
> 
> There might be a better way, but the messaging system is not easy to
> wrap your head around.

No, it's tricky.  And I think this isn't quite right.

Please try this alternative:

--- vim81/src/misc1.c        2019-09-22 21:29:49.663425989 +0200
+++ misc1.c     2019-09-24 22:28:04.071509651 +0200
@@ -1548,8 +1548,6 @@
        if (msg_row > 0)
            cmdline_row = msg_row - 1;
        need_wait_return = FALSE;
-       msg_didany = FALSE;
-       msg_didout = FALSE;
     }
     else
        cmdline_row = save_cmdline_row;


We should have a test for this to avoid regressions.

-- 
FATHER:    Who are you?
PRINCE:    I'm ... your son ...
FATHER:    Not you.
LAUNCELOT: I'm ... er ... Sir Launcelot, sir.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
@brammool 
Your patch appears to fix it.
It was applied in 8c96af9c0 (patch 8.1.2096) (accidentally probably) already, closing.

**Comment by brammool** [comment]
> @brammool 
> Your patch appears to fix it.
> It was applied in 8c96af9c0 (patch 8.1.2096) (accidentally probably)
> already, closing.

Sorry for accidentally fixing the bug :-).

Was there a test for this problem?

Hmm, I think I also fixed #4984.

-- 
"I love deadlines.  I especially like the whooshing sound they
make as they go flying by."
                         -- Douglas Adams

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> Was there a test for this problem?

No.

> Hmm, I think I also fixed #4984.

Will check it later.

**Pull request closed without merging**
