### PR TITLE
spec syntax: support %_unitdir in spec.vim

### LINKED ISSUE #76: [patch] spec syntax: support %_unitdir and %global in spec.vim
```
Currently the spec highlighting doesn't recognize '_unitdir' and 'global' 

What version of the product are you using? On what operating system?
latest hg


```

Original issue reported on code.google.com by `jan.syna...@gmail.com` on 19 Jul 2012 at 12:31

Attachments:
- [spec-highlight.patch](https://storage.googleapis.com/google-code-attachments/vim/issue-76/comment-0/spec-highlight.patch)

### PR DESCRIPTION
**Pull request by mcepl**
Currently the spec highlighting doesn't recognize '_unitdir'

Fixes #76

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
This is Fedora/Red Hat specific, so -> no.

We should get all macro from RPM API and then hughlight them.

**Review by igor-raits — CHANGES_REQUESTED** [review]
This is Fedora/Red Hat specific, so -> no.

We should get all macro from RPM API and then hughlight them.

**Comment by mcepl** [comment]
> This is Fedora/Red Hat specific, so -> no.

And so what? Or in other words, how do you propose to highlight it?

**Comment by ismail** [comment]
This also makes sense for openSUSE/SUSE.

**Comment by brammool** [comment]
Included.

**Pull request closed without merging**
