### PR TITLE
add cpp syntax highlight in devicetree files

### PR DESCRIPTION
**Pull request by liambeguin**
It's now common to run the C preprocessor on devicetree files in order  
to take advantage of #include and #define statements.                   
                                                                        
Copy CPP section from the C syntax file.

### CODE REVIEW

**Comment by brammool** [comment]
Have you contacted the maintainer, Daniel Mack?
I haven't heard from him in years, but his email might still be valid.

**Comment by liambeguin** [comment]
I haven't tried to reach out, but I believe @zonque is his github handle.

**Comment by zonque** [comment]
Could you provide an example on what this changes, ideally as a screenshot as well as source files? I tried this on some dts files from the Linux kernel tree and I somehow don't grok how the new syntax file helps. But I guess I'm just holding it wrong :)

**Comment by liambeguin** [comment]
The main difference is that with the update we're now highlighting preprocessor keywords.
The code added is a little complex but since there's no difference with what's supported for C, I thought copying that section was best.

```
#include "file.h"
#define TEST

/ {
	model = "ZynqMP ZCU102 RevB";
	compatible = "xlnx,zynqmp-zcu102-revB", "xlnx,zynqmp-zcu102", "xlnx,zynqmp";
};

#if defined(TEST)
&gem3 {
	phy-handle = <&phyc>;
	phyc: phy@c {
		reg = <0xc>;
		ti,rx-internal-delay = <0x8>;
		ti,tx-internal-delay = <0xa>;
		ti,fifo-depth = <0x1>;
		ti,rxctrl-strap-worka;
	};
	/* Cleanup from RevA */
	/delete-node/ phy@21;
};
#else
&gem3 {
	phy-handle = <&phyc>;
	phyc: phy@c {
		reg = <0xc>;
		ti,rx-internal-delay = <0x8>;
		ti,tx-internal-delay = <0xa>;
		ti,fifo-depth = <0x1>;
		ti,rxctrl-strap-worka;
	};
	/* Cleanup from RevA */
	/delete-node/ phy@21;
};
#endif

#if 0
/* Fix collision with u61 */
&i2c0 {
	i2c-mux@75 {
		i2c@2 {
			max15303@1b { /* u8 */
				compatible = "maxim,max15303";
				reg = <0x1b>;
			};
			/delete-node/ max15303@20;
		};
	};
};
#endif
```

## original syntax
image

## updated syntax
image

**Comment by zonque** [comment]
A okay, thanks for explaining! I guess this is good to go in then. Thanks a lot :)

**Comment by brammool** [comment]
Thanks, I'll include it.

**Pull request closed without merging**
