### PR TITLE
Fix ConPTY double-free

### PR DESCRIPTION
**Pull request by ghost**
channel_free_channel() was called twice. That's my old patch.
In some situations, vim.exe will go down.

I must reduce these mistakes consciously.

### CODE REVIEW

**Comment by ghost** [comment]
This is a problem report.
https://github.com/vim-jp/issues/issues/1338

**Comment by mattn** [comment]
This is not fixed. channel_clear_one call channel_parse_messages to get rest contents. It makes double-free.

https://gist.github.com/8cb49a86b74559a10bccd753785e42d3

**Comment by ghost** [comment]
That is my mistake. I forgot to point out. I'm sorry to trouble you. Correct and submit again.

**Comment by brammool** [comment]
> This is not fixed. channel_clear_one call channel_parse_messages to get rest contents. It makes double-free.
> 
> https://gist.github.com/8cb49a86b74559a10bccd753785e42d3 

I do not see how channel_clear_one() calls channel_parse_messages().
Can you explain?

The problem I see now is that channel_free_channel(channel) frees
"channel", thus using channel->ch_job after that is wrong. 

While looking at the patch I was also wondering whether there could be an
endless loop, since channel_free() may postpone the actual freeing, in
which case going back to first_channel is a problem.
Let's see if we can make this more robust.... Well, it can never happen,
since "safe_to_invoke_callback" is set near the start of
channel_parse_messages().

This should be simpler and avoids accessing freed memory:

	if (channel->ch_to_be_freed || channel->ch_killing)
	{
	    channel_free_contents(channel);
	    if (channel->ch_job != NULL)
		channel->ch_job->jv_channel = NULL;

	    // free the channel and then start over
	    channel_free_channel(channel);
	    channel = first_channel;
	    continue;
	}


-- 
CUSTOMER:     You're not fooling anyone y'know.  Look, isn't there something
              you can do?
DEAD PERSON:  I feel happy... I feel happy.
    [whop]
CUSTOMER:     Ah, thanks very much.
MORTICIAN:    Not at all.  See you on Thursday.
CUSTOMER:     Right.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
My skills are not enough. There is no better way than that change.
Should I submit a new PR? Or please correct it.
I think it should have been written from the beginning.

**Comment by brammool** [comment]
Should be fixed by patch 8.2.0442

**Comment by mattn** [comment]
Not fixed. Still crash. channel_parse_messages is called recursibly. So need to block freeing.

**Comment by brammool** [comment]
> Not fixed. Still crash. channel_parse_messages is called recursibly.
> So need to block freeing.

Please explain how channel_parse_messages() can be called recursively.

-- 
Q: Is selling software the same as selling hardware?
A: No, good hardware is sold new, good software has already been used by many.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
via channel_clear_one().
https://github.com/vim-jp/issues/issues/1338#issuecomment-601701859

In other words, like this ... ?
````diff
diff --git a/src/channel.c b/src/channel.c
index a57ed9ccf..b2dc78f25 100644
--- a/src/channel.c
+++ b/src/channel.c
@@ -4456,6 +4456,7 @@ channel_parse_messages(void)
 	}
 	if (channel->ch_to_be_freed || channel->ch_killing)
 	{
+	    channel->ch_killing = FALSE;
 	    channel_free_contents(channel);
 	    if (channel->ch_job != NULL)
 		channel->ch_job->jv_channel = NULL;
````

**Comment by brammool** [comment]
> via channel_clear_one().
> https://github.com/vim-jp/issues/issues/1338#issuecomment-601701859

Channel_clear_one() calls
    channel_peek()
    channel_get()
    remove_cb_node()
    free_callback()
    remove_json_node()
    remove_from_writeque()
None of these call another channel function.

Isn't it through channel_close()?  It invokes callbacks, so just about
anything can happen there.


> In other words, like this ... ?
> ````diff
> diff --git a/src/channel.c b/src/channel.c
> index a57ed9ccf..b2dc78f25 100644
> --- a/src/channel.c
> +++ b/src/channel.c
> @@ -4456,6 +4456,7 @@ channel_parse_messages(void)
>  	}
>  	if (channel->ch_to_be_freed || channel->ch_killing)
>  	{
> +	    channel->ch_killing = FALSE;
>  	    channel_free_contents(channel);
>  	    if (channel->ch_job != NULL)
>  		channel->ch_job->jv_channel = NULL;
> ````

If channel_parse_messages() is called resursively it should probably
just return.  Or perhaps only do the part with channel_has_readahead().
Would be good to have a repro case.

Let me just add a check for recursive use, that is the safest.  If that
breaks something we'll find out and then we know what to fix.

-- 
Courtroom Quote #19:
Q:  Doctor, how many autopsies have you performed on dead people?
A:  All my autopsies have been performed on dead people.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
In this comment, the reporter states that the problem has been resolved.
https://github.com/vim-jp/issues/issues/1338#issuecomment-604516660

Repro case Japanese: "再現手順".
https://github.com/vim-jp/issues/issues/1338#issue-584987899

I have to tell me that I never end up studying. Thank you very much.

**Pull request closed without merging**
