### PR TITLE
Add new HTML 5 tags (used the official HTML 5.1 W3C Recommendation, 1 November 2016: https://www.w3.org/TR/2016/REC-html51-20161101/index.html)

### PR DESCRIPTION
**Pull request by jorgesumle**
…, 1 November 2016: https://www.w3.org/TR/2016/REC-html51-20161101/index.html)

Sent email to the mantainer, but there is no reply yet.

EDIT: I was using the wrong reference, so I amended the commit and forced push again. Now, I've included the elements from the most recent official reference (also known as a W3C Recommendation). I don't have to re-email the maintainer, because I told him to approve my changes sending him this link.

### CODE REVIEW

**Comment by joeky888** [comment]
This PR should be accepted,

why does no one reply to this :p

**Comment by brammool** [comment]
Please check the header of the file for the name and email of the maintainer.
Send the patch to the maintainer, sending it here won't have much effect.

**Comment by jorgesumle** [comment]
@brammool, I emailed the maintainer last month, but hasn't replied. What should I do then?

**Comment by tonymec** [comment]
If I were you, I would wait until after the winter holidays have passed, then retry, and if you still get no reply, say so in the `vim-dev` list, or even here. In that case a new maintainter (you, maybe?) will have to be sought.

But this is only what **I** would do; *“Your Mileage May Vary”*.

**Comment by joeky888** [comment]
What if something happened to the author which caused him can not reply physically?

No offense.

**Comment by tonymec** [comment]
No offense taken.

If the author is physically unable to reply, he will hardly be able to send any changes to Bram, will he?

If he doesn't see this thread, it means he neither follows the Vim issues on github, nor on the vim_dev list, which I would (rightly or wrongly) interpret as having lost interest in developing Vim, and among others, its syntax scripts.

Best regards,
Tony.

**Comment by chrisbra** [comment]
Unfortunately, the maintainer of that file is known to be unresponsive, which is a shame. We have had that problem already in the past. In my opinion, if there are other people willing to maintain that file, I would go with that alternative.

@j16180339887 that is the normal workflow for runtime files. And in general it is better to have a maintainer take care of the specifics of syntax/filetype or other script files that to have us maintain those files for languages we don't use and sometimes even not know. So in general it is a good idea to have specific maintainers, however sometimes that does not work so well.

**Comment by jorgesumle** [comment]
@brammool, maybe you could also email this maintainer. If he/she still doesn't respond, you should assign this syntax file to a Vim contributor who knows HTML very well. I'm not in the dev mailing list, but Vim is very popular and surely will be many people wanting to help.

@tonymec, thanks for the suggestion. Sorry if I took the wrong steps, I'm not very familiar with Vim development. I'll do that, in January I'll email the maintainer again and see what happens.

**Comment by brammool** [comment]
> @brammool, maybe you could also email this maintainer. If he/she still
> doesn't respond, you should assign this syntax file to a Vim
> contributor who knows HTML very well. I'm not in the dev mailing list,
> but Vim is very popular and surely will be many people wanting to
> help.
> 
> @tonymec, thanks for the suggestion. Sorry, if I took the wrong steps,
> I'm not very familiar with Vim development. I'll do that, in January
> I'll email the maintainer again and see what happens.

Claudio has not been responsive, I have not received a message from him
for a long time.  If someone wants to take over one of his runtime
files, please do so.

-- 
hundred-and-one symptoms of being an internet addict:
144. You eagerly await the update of the "Cool Site of the Day."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by jorgesumle** [comment]
Since no-one has volunteered to take over the HTML syntax file, I offer to help maintaining the HTML syntax file. Here is the patch...

<pre><code>--- html.vim.1	2016-12-29 04:37:42.222663781 +0100
+++ html.vim	2016-12-29 04:44:39.916691972 +0100
@@ -1,9 +1,8 @@
 " Vim syntax file
 " Language:	HTML
-" Maintainer:	Claudio Fleiner &lt;claudio@fleiner.com&gt;
-" URL:		http://www.fleiner.com/vim/syntax/html.vim
-" Last Change:	2015 Jan 07
-"		included patch from David Felix
+" Maintainer:	Jorge Maldonado Ventura &lt;jorgesumle@freakspot.net&gt;
+" Last Change:	2016 Dec 29
+"		included patch from Jorge Maldonado Ventura
 
 " Please check :help html.vim for some comments and a description of the options
 
@@ -53,6 +52,14 @@
 syn keyword htmlTagName contained colgroup del fieldset iframe ins legend
 syn keyword htmlTagName contained object optgroup q s tbody tfoot thead
 
+" new html 5 tags
+syn keyword htmlTagName contained article aside audio bdi canvas datalist
+syn keyword htmlTagName contained details embed figcaption figure
+syn keyword htmlTagName contained footer header hgroup main mark
+syn keyword htmlTagName contained menuitem meter nav output picture
+syn keyword htmlTagName contained progress rb rp rt rtc ruby section
+syn keyword htmlTagName contained slot source template time track video wbr
+
 " legal arg names
 syn keyword htmlArg contained action
 syn keyword htmlArg contained align alink alt archive background bgcolor
</code></pre>

**Comment by k-takata** [comment]
Removing the previous maintainer name is a bad idea.
Instead of that, change "Maintainer:" to "Previous Maintainer:".

**Comment by jorgesumle** [comment]
Thanks for the correction @k-takata. Below is the corrected patch
<pre><code>--- html.vim.1	2016-12-29 04:37:42.222663781 +0100
+++ html.vim	2016-12-29 09:39:12.966790086 +0100
@@ -1,9 +1,9 @@
 " Vim syntax file
-" Language:	HTML
-" Maintainer:	Claudio Fleiner &lt;claudio@fleiner.com&gt;
-" URL:		http://www.fleiner.com/vim/syntax/html.vim
-" Last Change:	2015 Jan 07
-"		included patch from David Felix
+" Language:             HTML
+" Maintainer:           Jorge Maldonado Ventura &lt;jorgesumle@freakspot.net&gt;
+" Previous Maintainer:  Claudio Fleiner &lt;claudio@fleiner.com&gt;
+" Last Change:          2016 Dec 29
+"                       included patch from Jorge Maldonado Ventura
 
 " Please check :help html.vim for some comments and a description of the options
 
@@ -53,6 +53,14 @@
 syn keyword htmlTagName contained colgroup del fieldset iframe ins legend
 syn keyword htmlTagName contained object optgroup q s tbody tfoot thead
 
+" new html 5 tags
+syn keyword htmlTagName contained article aside audio bdi canvas datalist
+syn keyword htmlTagName contained details embed figcaption figure
+syn keyword htmlTagName contained footer header hgroup main mark
+syn keyword htmlTagName contained menuitem meter nav output picture
+syn keyword htmlTagName contained progress rb rp rt rtc ruby section
+syn keyword htmlTagName contained slot source template time track video wbr
+
 " legal arg names
 syn keyword htmlArg contained action
 syn keyword htmlArg contained align alink alt archive background bgcolor</code></pre>

**Comment by chrisbra** [comment]
thanks. Please go ahead and send the complete file to Bram for inclusion with Vim and mention, that the previous maintainer is unresponsive and you take over maintanance.  If you like to maintain that file in a public repository, you might want to mention it in the header of the file, so that other can contribute.

**Comment by jorgesumle** [comment]
> Please go ahead and send the complete file to Bram for inclusion with Vim and mention, that the previous maintainer is unresponsive and you take over maintanance.

Already did that, I'm waiting for his response. 

> If you like to maintain that file in a public repository, you might want to mention it in the header of the file, so that other can contribute.

Thanks for the suggestion. I'll do that when I or someone else make the next patch.

**Comment by brammool** [comment]
Thanks for taking over maintenance.  I'll include the change and await any comments.

**Pull request closed without merging**
