### PR TITLE
Fix typo s/wich/which/.

### PR DESCRIPTION
**Pull request by kenjitoyama**

### CODE REVIEW

**Comment by k-takata** [comment]
Have you contacted the maintainer?

**Comment by kenjitoyama** [comment]
Hi @k-takata, the link at line 11 (https://gnuada.svn.sourceforge.net/svnroot/gnuada/trunk/tools/vim/autoload/decada.vim) is currently 404. Is that still the canonical upstream project?

**Comment by k-takata** [comment]
Not sure. Is the email alive?

**Comment by chrisbra** [comment]
Isn't he also active on github: cc @krischik

**Comment by brammool** [comment]
Has been included already.

**Pull request closed without merging**
