### PR TITLE
Fix #255 and improve dead key support under Windows

### LINKED ISSUE #255: Avoid interpreting kepress '`' + 'i" as 'ì' instead of '`i' and going to the respective mark on the English International Keyboard on Windows
```
I run gVim7.4 on Windows 7 with the English International keyboard. 

It configured in a way so that pressing '`' + 'i' gives you 'ì'. In Vim insert 
mode that's the desired behavior. However it isn't in command mode where I 
effectively have to press '`' + ' ' + 'i' to go to the mark 'i'.

I observed similar behavior for the caret '^' key. Pressing it makes vim wait 
for a vowel to be able to render 'â', 'î' etc instead of directly going to be 
beginning of the line. It only goes there when I press '^' + ' '. In insert 
mode it's useful to be able to type 'â'. It isn't in command mode and there 
it's completely useless to wait for another character. I thereby propose that 
vim looks directly for whether the '`' key or the '^' gets pressed and doesn't 
wait for a character.
```

Original issue reported on code.google.com by `christia...@gmail.com` on 8 Sep 2014 at 12:01

### PR DESCRIPTION
**Pull request by 2072**
This is a follow up to patch 413 (#250) and issue #255.

This patch resuscitates dead keys when not in insert/select mode: `(!(get_real_state() & (INSERT | CMDLINE | SELECTMODE)`

The typical example is described in #255.

### CODE REVIEW

**Comment by brammool** [comment]
John Wellesz wrote:

> This is a follow up to patch 413 (#250) and issue #255.
> 
> This patch resuscitates dead keys when not in insert/select mode: `(!(get_real_state() & (INSERT | CMDLINE | SELECTMODE)`

Thanks, handling the character differently when not typing text makes
sense.

Previously the dead_key variable was reset to zero.  Did you leave that
out intentionally?

## 

SIGFUN -- signature too funny (core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by 2072** [comment]
> Previously the dead_key variable was reset to zero.  Did you leave that
> out intentionally?

Yes that was intentional but partly a mistake: `dead_key` is set to 0 in `_OnChar()` which is invoked when `MyTranslateMessage()` is called in `process_message()` except that `MyTranslateMessage()` could also invoke `_OnSysChar()` if ALT was pressed. Also it's safer to reset `dead_key` before generating artificial key press messages.

So this is fixed by 59e424b.

I was not completely happy with what I did in 7.4.413 as the behaviour with dead keys was still different from other Windows application: dead keys' nominal characters were not output as expected when typing numbers with the numeric key pad or hitting return after hitting a dead key (for example). So I fixed that in aa527ed which introduces a new static function: `outputDeadKey_rePost()`.

I included detailed comments in the sources because dead keys are not easy to understand and are full of traps.

**Comment by 2072** [comment]
Is there something amiss with this pull request? (It's been open for 3 months)

**Comment by chrisbra** [comment]
Could we get this included before the next official Windows release please?

**Comment by brammool** [comment]
Christian wrote:

> Could we get this included before the next official Windows release please?

I'm trying to catch up with including patches, but there is still a pile
to do...

## 

ARTHUR:    Be quiet!  I order you to shut up.
OLD WOMAN: Order, eh -- who does he think he is?
ARTHUR:    I am your king!
OLD WOMAN: Well, I didn't vote for you.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
