### PR TITLE
Make 'virtualedit' option global-local

### PR DESCRIPTION
**Pull request by ghgary**

### CODE REVIEW

**Comment by vim-ml** [comment]
On 2021-07-25, Gary Johnson wrote:
> -------------------------------------------------------------------------------
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/8638
> 
> Commit Summary
> 
>   • Make the 'virtualedit' option global-local
>   • Merge branch 'master' into gj_ve_global_local
> 
> File Changes
> 
>   • M runtime/doc/options.txt (2)
>   • M src/buffer.c (1)
>   • M src/change.c (2)
>   • M src/drawscreen.c (8)
>   • M src/edit.c (6)
>   • M src/misc2.c (21)
>   • M src/normal.c (6)
>   • M src/ops.c (16)
>   • M src/option.c (20)
>   • M src/option.h (1)
>   • M src/optiondefs.h (3)
>   • M src/optionstr.c (32)
>   • M src/proto/option.pro (1)
>   • M src/register.c (9)
>   • M src/structs.h (2)
>   • M src/testdir/test_virtualedit.vim (64)
> 
> Patch Links:
> 
>   • https://github.com/vim/vim/pull/8638.patch
>   • https://github.com/vim/vim/pull/8638.diff

I'm getting CI failures from this PR that I don't understand.  For
example, a build titled "linux (huge, gcc, none)" fails with these
last lines in the log:

749  File 'sign.c'
750  Lines executed:94.58% of 1200
751  Creating 'sign.c.gcov'
752
753 {'message': "Couldn't find a repository matching this job.", 'error': True}
754  Error: Process completed with exit code 1.

Huh?  I have no idea what that means or what to do about it.

How do I fix that?

Regards,
Gary

**Comment by chrisbra** [comment]
This error can be ignored. For some reason the coverity job only works when the patch has been merged.  Don't know why or how to fix it.

**Comment by brammool** [comment]
Thanks, mostly looks good.
One situation is not covered: If the global value is set, there is no way do disable it locally, since an empty value means to use the global value.  How about using "none", using it for the local value would then overrule the global value.
There are actually other options where this could be useful.  But since nobody asked for it, probably less so.

**Comment by vim-ml** [comment]
On 2021-07-25, Bram Moolenaar wrote:
> Thanks, mostly looks good.
> One situation is not covered: If the global value is set, there is no way do
> disable it locally, since an empty value means to use the global value. How
> about using "none", using it for the local value would then overrule the global
> value.
> There are actually other options where this could be useful. But since nobody
> asked for it, probably less so.

I noticed that, but since other options I checked seemed to have
that same problem, I thought it was a deliberate feature of
global-local options.

If you'd like "none", I'll add it.

Regards,
Gary

**Comment by gdupras** [comment]
An example of this is `'showbreak'`. From the help files:

```
A window-local value overrules a global value.  If the global value is
set and you want no value in the current window use NONE:
	:setlocal showbreak=NONE
```

**Comment by brammool** [comment]
Gabriel Dupras wrote:

> An example of this is `'showbreak'`. From the help files:
> 
> ```
> A window-local value overrules a global value.  If the global value is
> set and you want no value in the current window use NONE:
> 	:setlocal showbreak=NONE
> ```

For 'virtualedit' we can use either NONE or none.  Best is probably to
accept both.

-- 
hundred-and-one symptoms of being an internet addict:
242. You turn down a better-paying job because it doesn't come with
     a free e-mail account.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
