### PR TITLE
Update Turkish tutor to v1.7

### PR DESCRIPTION
**Pull request by bitigchi**
1. Added missing translations
2. Updated current translations
3. Fixed orthographical and grammatical errors

### CODE REVIEW

**Comment by brammool** [comment]
Please resolve the conflicts.  Might be that the iso9 encoding causes a problem, you can also email me the new files (in an attachment).

**Comment by bitigchi** [comment]
Fixed the encoding problem, but I don't understand why it shows that there are conflicts in both files. What would be the proper way to address these issues?

**Comment by brammool** [comment]
Well, if it mentions conflicts, there probably are.  Git can be hard to deal with conflicts, unfortunately.

**Comment by brammool** [comment]
Now I could include the patch without problems, thanks!

**Comment by bitigchi** [comment]
Thank you, very happy to contribute!

**Pull request closed without merging**
