### PR TITLE
Add functions to manage digraphs

### PR DESCRIPTION
**Pull request by mityu**
I added useful `setdigraphs()` and `getdigraphs()` functions to VimScript for the following reasons.

- setdigraphs()

Currently, you cannot define digraphs that start with a white space because the `:digraph` command cannot handle the white space on the head of chars.
Providing a function to define digraphs, in other words adding `setdigraphs()` function, can solve this. Example:

```vim
call setdigraphs(' a', 12354)
```
Space key is really suitable for assigning to a prefix key. So, it's worth to add `setdigraphs()` function.

(Added) 
Plus, as @lacygoill mentioned [here](https://github.com/vim/vim/pull/8580#issuecomment-881768087), `:digraphs` command can break the syntax. For example, when you use a opening round bracket without closing pair, the following code is not highlighted correctly:

```vim
digraphs a( 12354
" Code here is not highlighted correctly...
```

But in case of using the function, this problem doesn't appear.

- getdigraphs()

There's two reasons why I added this function.
First, if VimScript has `setdigraphs()` function, most users expect that `getdigraphs()` function exists. Having `setdigraphs()` function but not having `getdigraphs()` function is confusing.
Second, if you have `getdigraphs()` function, it will be easy to implement custom textobjects that have a support for digraphs like below. If you have a way to define such custom textobjects, you can make much more convenient your environment for editing texts in non-English languages on Vim. So, it will be useful.
For these reasons, I decided to implement `getdigraphs()` function.

```vim
function! TextobjectBetweenCharacter() abort
  let char = getcharstr()
  if char ==# "\<ESC>"
    return ''
  elseif char ==# "\<C-k>"
    let digraph = ''

    for i in range(2)
      let char = getcharstr()
      if char ==# "\<ESC>"
        return ''
      endif
      let digraph ..= char
    endfor

    let char = getdigraphs(digraph)
  endif

  " Select text between `char`...
  return ''
endfunction

omap <expr> id TextobjectBetweenCharacter()
```

**NOTE**
I'm not sure whether the function names are good. Perhaps should they be `setdigraph()` and `getdigraph()`?  What do you think about this?

### CODE REVIEW

**Comment by lacygoill** [comment]
I think all Ex commands which have a non-trivial syntax should have a function counterpart.  `:digraphs` is one of them; it needs a lot of code to be correctly highlighted:

    syntax keyword vim9DigraphsCmd dig[raphs]
        \ contained
        \ nextgroup=
        \     vim9DigraphsChars,
        \     vim9DigraphsCharsInvalid,
        \     vim9DigraphsCmdBang
        \ skipwhite
    syntax match vim9DigraphsCharsInvalid /\S\+/
        \ contained
        \ nextgroup=vim9DigraphsNumber
        \ skipwhite
        syntax match vim9DigraphsCmdBang /!/ contained
    syntax match vim9DigraphsChars /\s\@<=\%([^ \t|]\|\\|\)\{2}\_s\@=/
        \ contained
        \ nextgroup=vim9DigraphsNumber
        \ skipwhite
    syntax match vim9DigraphsNumber /\d\+/
        \ contained
        \ nextgroup=vim9DigraphsChars,vim9DigraphsCharsInvalid
        \ skipwhite

    highlight def link vim9DigraphsChars vim9String
    highlight def link vim9DigraphsCmd vim9GenericCmd
    highlight def link vim9DigraphsNumber vim9Number

So, I think this feature is very useful.

---

> I'm not sure whether the function names are good. Perhaps should they be setdigraph() and getdigraph()? What do you think about this?

The command is plural, but I think that's because it can set several digraphs in a single execution.
OTOH, this function would only set 1 digraph per invocation, right?  If so, yes, I think the singular form would be better.

**Comment by mityu** [comment]
> I think all Ex commands which have a non-trivial syntax should have a function counterpart. :digraphs is one of them; it needs a lot of code to be correctly highlighted:

I think so. (Actually, I was going to include it in the reasons, but at that time I was so sleepy that I forgot writing it. Thank you for commenting it. I added it to my top comment :))

> The command is plural, but I think that's because it can set several digraphs in a single execution.
> OTOH, this function would only set 1 digraph per invocation, right? If so, yes, I think the singular form would be better.

Yes, this function sets no more than 1 digraph for one call.
I didn't know that `:digrpahs` command can define multiple digraphs at once, so I thought these functions names should be plural form if I follow to the command name. But now I understand why the `:digraphs` command is plural form and think the singular form is better too. I'll change them. Thank you.

**Comment by yegappan** [comment]
Based on similar functions for other features, there will be feature requests
to return all the digraphs and to set multiple digraphs in a single call.

What do you think about modifying getdigraph() to return all the digraphs
if no arguments are supplied? Another approach is to introduce a new
getdigraphlist() function for this.

Similarly you can introduce a setdigraphlist() function that takes a List
of digraphs and set multiple digraphs.

**Comment by mityu** [comment]
First, by considering type-checking in vim9script, I think it's better to introduce `getdigraphlist()` than modifying `getdigraph()` to make it return all digraphs when no arguments is given. When we return one digraph, the type should be `string`, but when we return multiple digraphs, the type should be `list<dict<string>>`.  Since these types are different, providing these functions separately will lead to type-checking in vim9script more strict. So, let's add `getdigraphlist()`.

Then, in this case, it's better to add `setdigraphlist()` for the following reasons. First is that  users will expect Vim has `setdigraphlist()` if Vim has `getdigraphlist()`. In addition to this, similar to above, introducing `setdigraphlist()` function can make type-checking in vim9script more strict. Therefore, I would like to take the approach that introducing `setdigraphlist()`.

**Comment by mityu** [comment]
I'm thinking the spec of getdigraphlist() as follows:

`getdigraphlist([{list-all}])`
- In default, it returns only the user-defined digraphs.
- But if {list-all} is specified and it is true, it returns all the digraphs, including the built-in digraphs.
- The type of return value is always dict<string>.

What do you think of this, @lacygoill and @yegappan? Is it enough or should it be made more flexible?

**Comment by brammool** [comment]
It indeed seems best to have four functions, set one, set list, get one, get list.

For the arguments, instead of using a number, wouldn't it be better to use a string with one character?
The big advantage is that in a script file you can read the character.  For a number you would have to convert it to know what character it is.
Example:  ```setdigraph('ho', 'ほ')```
Then another advantage is that the type of the list is a list of list of strings, instead of having a mix of string and number.

**Comment by mityu** [comment]
@brammool Thank you for reviewing.

> It indeed seems best to have four functions, set one, set list, get one, get list.

Now I'm thinking to use dictionary to set/get multiple digraphs because digraph is a kind of mapping. Mapping functions such as maparg(), mapcheck(), and mapset() use dictionaries. Digraph functions should follow it.
However, I don't have good idea about the name for set/get list functions. Once I named them setdigraphlist() and getdigraphlist(), but the argument/the return value is dictionary, so it's confusing. Also, I thought setdigraphitems() and getdigraphitems() are not good. Do you have any good idea for this?


> For the arguments, instead of using a number, wouldn't it be better to use a string with one character?
I strongly agree. Specifying a character by number is a bit confusing. Specifying characters as-is is awesome idea. I'll update the implementation.

**Comment by vim-ml** [comment]
Hi,

On Sat, Jul 17, 2021 at 12:22 AM mityu ***@***.***> wrote:

> I'm thinking the spec of getdigraphlist() as follows:
>
> getdigraphlist([{list-all}])
>
>    - In default, it returns only the user-defined digraphs.
>    - But if {list-all} is specified and it is true, it returns all the
>    digraphs, including the built-in digraphs.
>    - The type of return value is always dict.
>
> What do you think of this, @lacygoill <https://github.com/lacygoill> and
> @yegappan <https://github.com/yegappan>? Is it enough or should it be
> made more flexible?
>
>
> This looks good to me.

Regards,
Yegappan

**Comment by brammool** [comment]
> @brammool Thank you for reviewing.
> 
> > It indeed seems best to have four functions, set one, set list, get one, get list.
> 
> Now I'm thinking to use dictionary to set/get multiple digraphs
> because digraph is a kind of mapping. Mapping functions such as
> maparg(), mapcheck(), and mapset() use dictionaries. Digraph functions
> should follow it.
> However, I don't have good idea about the name for set/get list
> functions. Once I named them setdigraphlist() and getdigraphlist(),
> but the argument/the return value is dictionary, so it's confusing.
> Also, I thought setdigraphitems() and getdigraphitems() are not good.
> Do you have any good idea for this?

It is basically a list of pairs.  That allows for duplicates, but that
can also happen by doing it with two calls.

We don't have a separate type for a pair or a tuple.  Using a list with
two items works just fine.  A tuple can be useful if the items have
different types, but since we now use strings only that is not relevant.

I don't see a good reason to use a dictionary.  It would be possible.

-- 
"Hit any key to continue" it said, but nothing happened after F sharp.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mityu** [comment]
Certainly. OK, I understood. Thank you. I'm going to add setdigraphlist() and getdigraphlist().

**Comment by mityu** [comment]
Works have done.

**Comment by mityu** [comment]
Sorry, I take it back. Some problems are still left.

**Comment by h-east** [comment]
Hi Bram, mityu and all.

Most functions added since Vim 8.0 are prefixed with feature name.
For example:
Channel functions has a "ch_" prefix.
JSON functions has a "json_" prefix.
Job functions has a "job_" prefix.
Timer functions has a "timer_" prefix.
...etc.

How about renaming the digraph functions in the same way?
digraph_get(), digraph_get_list(), digraph_set(), digraph_set_list().

Sorry for the late proposal:bow:.

--
Best regards,
Hirohito Higashi (h_east)

**Comment by mityu** [comment]
Certainly, sign related functions also have `sign_` prefix. It looks good to me.

**Comment by brammool** [comment]
Yes, but then only one underscore: digraph_getlist(), digraph_setlist().

**Pull request closed without merging**
