### PR TITLE
runtime(cpp): Fix digit separator in octals and floats

### PR DESCRIPTION
**Pull request by adah1972**
and the incorrect rendering of floats that start with ".".

### CODE REVIEW

**Comment by adah1972** [comment]
The original maintainer, vim-jp project, has been inactive for three years. But I have not changed the comment about the maintainer.

The current modes does not seem to require a dedicated maintainer, anyway....

**Comment by adah1972** [comment]
This commit allows literals like `0'644` and `3.14159'26535'89793` to be correctly highlighted in Vim.

**Comment by zeertzjq** [comment]
Related https://github.com/vim-jp/vim-cpp/pull/67

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
