### PR TITLE
Update iss syntax file

### PR DESCRIPTION
**Pull request by ObserverOfTime**
- Add 'ExternalSize:' parameter
- Add 'setntfscompression' files flag
- Fix escaped left brace highlight
- Fix 'String:' parameter highlight
- Remove trailing whitespace

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
I tried to e-mail the maintainer but either something went wrong on my side or his address no longer exists.

```
[<jmills@cs.mun.ca>](mailto:jmills@cs.mun.ca): host esa03.ucs.mun.ca[134.153.136.23] said: 550 #5.1.0
    Address rejected. (in reply to RCPT TO command)
```

**Comment by brammool** [comment]
Also see #2739
Perhaps @jase413 ?

**Comment by ObserverOfTime** [comment]
I don't think the maintainer will respond at this point. Maybe it's time to merge it?

**Comment by chrisbra** [comment]
okay, let me merge it then.

**Comment by jase413** [comment]
Thanks for doing this! Sorry for the delayed response. I haven't maintained this file in a long, long time.

**Pull request merged**
