### PR TITLE
Update and rename bug_report.md to bug_report.yml

### PR DESCRIPTION
**Pull request by serjan-nasredin**

### CODE REVIEW

**Comment by chrisbra** [comment]
can you please explain why?

**Comment by snxx-lppxx** [comment]
Hi @chrisbra! I decided to change and improve the template.

**Comment by brammool** [comment]
How can we try this out before submitting the change?

**Comment by snxx-lppxx** [comment]
Hey @brammool, check it out: <https://github.com/snxx-lppxx/foo/issues/new/choose>.

**Comment by hseg** [comment]
Note one regression this creates -- the CLI interface doesn't support the YAML forms https://github.com/cli/cli/issues/5865 and doesn't even list them, so users reporting via it won't see this even prompted as an option. I nearly opened an issue without the proper template because of this.

**Pull request closed without merging**
