### PR TITLE
Add EditorConfig syntax file and update filetype mapping

### PR DESCRIPTION
**Pull request by gpanders**
Use 'editorconfig' as the filetype for .editorconfig files, and add a
syntax file that highlights known EditorConfig properties (and shows as
an error unknown properties, useful for catching typos or mistakes).

### CODE REVIEW

**Comment by brammool** [comment]
Please add a "last change" date to the syntax file header, so we can tell which one is the latest if we have two versions

**Comment by gpanders** [comment]
Done

**Comment by k-takata** [comment]
Could you update `.github/CODEOWNERS`?

**Comment by gpanders** [comment]
Sure, done.

**Pull request closed without merging**
