### PR TITLE
German menu translation updated

### PR DESCRIPTION
**Pull request by jonbriem**
Some menu items in the German translation were outdated, updated those and added some missing ones.

### CODE REVIEW

**Comment by brammool** [comment]
Please ask the maintainer, he is mentioned in the header.

**Comment by chrisbra** [comment]
The file is from 2006 and I haven't seen him in a long while. That's why I took over the other translations, but I never looked at the menu translations.

**Comment by brammool** [comment]
I thought the timestamp indicated a recent change, but that must have been a side effect.
@jonbiem can you take over maintenance?  If yes, then please also update the header.

**Comment by jonbriem** [comment]
I've sent the current maintainer an email, lets give him 1-2 days to respond. I'm not actually a native German speaker but good enough for maintenance I suppose, if he doesn't respond I'll take over the maintenance.

**Comment by chrisbra** [comment]
> I'm not actually a native German speaker but good enough for maintenance I suppose, if he doesn't respond I'll take over the maintenance.

Thanks. I can always review the proposed translations, just ping me. 

Actually, it looks like only the non-german parts of the translations changed, not the translations themselves. So I think it should be okay.

**Comment by jonbriem** [comment]
I've received no response from the maintainer and so I've added myself as maintainer of the file

**Comment by brammool** [comment]
Jon -

> I've received no response from the maintainer and so I've added myself
> as maintainer of the file

OK, I'll include your version then.

If you make further improvements, you can also send the whole file,
instead of a pull request or patch.

- Bram

-- 
The CIA drives around in cars with the "Intel inside" logo.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Change was included.

**Pull request closed without merging**
