### PR TITLE
Control the ambiguous width character in Windows 10 (1903)'s :terminal

### PR DESCRIPTION
**Pull request by ghost**
A patch for handling ambiguous width characters in ConPTY on Windows 10 (1903).
A bug in libvterm's internal buffer, which needed to be fixed together.

The logic has been changed again in Insider preview. However, Microsoft needs to resolve this issue first.
https://github.com/microsoft/terminal/issues/724

### CODE REVIEW

**Comment by brammool** [comment]
Can a few people try this out?  On different MS-Windows versions, ideally.

**Comment by ghost** [comment]
People have not yet tested it.
The operation check was done with Vista, 7, Win10 (1607), Win10 (1809), Win10 (1903), Insider build 18898.

The display of ambiguios characters on Win10 (1809) is buggy and can not be fixed in userland.
The cursor turns red in Insider build 18898. Since the transmitted sequence is also super buggy, I have to look at it.

This patch makes the little buggy Win10 (1903) ConPTY work properly.

This works with winpty. It only responds to ConPTY sequences.

**Comment by brammool** [comment]
The changes in libvterm are different from other optional flags.  Please discuss this with the libvterm author, Paul Evans.  I would like to keep the Vim copy of libvterm close to the original, as well as we can.

The return value of  vterm_get_special_pty_type() is unclear.  It seems that only the value 2 matters.  Perhaps it can just return true/fals?

**Comment by chrisbra** [comment]
ping @leonerd

**Comment by ghost** [comment]
The reason for not making it true/fals, special exceptions will increase in the future.

For an environment where the number is 0 and not related to ConPTY.
The number is 1, which is reserved for Windows 10 (1809 or earlier). However, ConPTY seems to be broken, so I do not know if I can correct it.
The number is 2, Windows 10 (1903). This is also broken but corrected.

InsiderBuild has been changed to ConPTY, which requires a value of 3. The logic of 2 can not be used anymore. This ConPTY (now Build 18898) has problems with correction, as the cursor is red and it is overly broken, such as drawing dust.

ConPTY and WindowsTerminal are API compatible but behave differently and can not be identified (the device ID is the same), probably the number is 4.

The current patch is combined with the libvterm bug fix, so I'll start by separating it.

**Comment by brammool** [comment]
Is there still work planned on this?

**Comment by ghost** [comment]
Insider build does not fix a bug that cannot display 2 cell characters.
https://github.com/microsoft/terminal/issues/724
If this is not fixed, there is nothing I can do now.

There is no more work planned.

**Comment by brammool** [comment]
Nobuhiro Takasaki wrote:

> Insider build does not fix a bug that cannot display 2 cell characters.
> https://github.com/microsoft/terminal/issues/724
> If this is not fixed, there is nothing I can do now.
> 
> There is no more work planned.

To be clear: Despite the bug in the Windows 10 terminal, this pull
request should be included?

-- 
hundred-and-one symptoms of being an internet addict:
241. You try to look for Net Search even when you're in File Manager.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
It's an easy-to-understand and fatal bug in Windows, but it has been left for more than four months. 
Problem with WriteConsoleOutputW().

I think applying a patch is a better way to fix this problem than continuing to pray.

**Pull request closed without merging**
