### PR TITLE
Updated tagfunc patch

### PR DESCRIPTION
**Pull request by andymass**
This is an updated version of Robert Webb, Lech Lorens, and Christian Brabandt's tagfunc patch.  It is intended to supersede #1628.

Compared to the old patch, it
   - is updated for modern vim
   - additionally passes the relevant tagstack entry to tagfunc.  Plugins will need to use the "from" field to perform tag searches on `:tag` (without argument) etc.
   - allows returning `v:null` from tagfunc to use built-in tag search instead.
   - adds `user_data` to store a string in the tag stack so plugins can keep track of things between calls
   - has some crashes fixed

This feature is critical for enabling language server plugins and other external utilities (such as GNU global) to operate natively with vim's regular tag features (`:tag`, `:tselect`, `:tnext`, etc).  Pseudo-example:

    set tagfunc=TagFunc
    function TagFunc(pattern, flags, info)
           " call external utility to obtain l:list_of_tags from a language server or other utility
           return l:list_of_tags
    endfunction

Tests are needed, but there are some existing issues with tags (e.g., #3944).  Any comments on the API welcome.

### CODE REVIEW

**Comment by chrisbra** [comment]
Hi Andy, thanks for pushing this topic. If you intend to maintain it, I'll remove my version, so that there don't exist several different tagfunc patches.

**Comment by brammool** [comment]
Andy, what is the state of this patch?  I can't include it like this, there is no test, at least.

**Comment by andymass** [comment]
Updated and test added.  

I noticed the todo.txt has a comment "should probably return a string with extra info instead of dict entries."  Are you suggesting a tagfunc should return a list of strings which are like the lines in a tagfile?  The intent (of the old patch's authors) was to match the output format of `taglist()` so you can return this directly, or apply a filter.  Currently, the "name," "filename," and "cmd" fields are mandatory for the return values of the tagfunc.

**Comment by brammool** [comment]
Andy Massimino wrote:

> Updated and test added.  
> 
> I noticed the todo.txt has a comment "should probably return a string
> with extra info instead of dict entries."  Are you suggesting a
> tagfunc should return a list of strings which are like the lines in a
> tagfile?  The intent (of the old patch's authors) was to match the
> output format of `taglist()` so you can return this directly, or apply
> a filter.  Currently, the "name," "filename," and "cmd" fields are
> mandatory for the return values of the tagfunc.

I was looking at what happens in find_tfu_tags().  It takes the tag
entry that tagfunc() returns, and then builds a string like what would
be found in a tags file.  And this is a bit complicated, using both
known and unknown dict keys.

An alternative would be that the tagfunc returns a string, just like it
would be found in a tags file.  This should be quite easy to do, since
the tagfunc implementation knows what fields it has to put in there.
Disadvantage: One has to understand the tag line format.

Another alternative would be to not use a string to store the matching
tags, but the parsed information.  That would require some refactoring
in the code that creates the list of matches.  Still, this needs to be
efficient, because the list can get very long.  Copying one string is
much more efficient than creating a struct with all the pieces.  So we
end up doing work for something that will work worse.  Not a good idea.

It appears that the possibility to use the output from taglist(), do
some filtering and return it from tagfunc() is the main reason to use
the "list of dicts" format.

So, looking at it again, the current implementation is probably the best
choice.


Anyway, a problem in the current code is that if there is anything
wrong, then it just skips the entry.  Or the whole list.  The author of
a tagfunc implementation doesn't get any hint about what he is doing
wrong.  I think that we should be strict and produce an error when the
entries are not valid.

-- 
Marriage isn't a word.  It's a sentence.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by andymass** [comment]
Added an error message for invalid return format (require either list of dicts with certain mandatory fields or v:null).

**Pull request closed without merging**
