### PR TITLE
Fix various typos in menu_fr_fr.latin1.vim

### PR DESCRIPTION
**Pull request by ghost**
The diff generated by GitHub is noisy. I don't understand why...

Fix only 3 minor typos :

formattage > formatage
Enregister > Enregistrer
Difference\ avec > Différence\ avec

### CODE REVIEW

**Comment by k-takata** [comment]
> The diff generated by GitHub is noisy. I don't understand why...

Didn't you change the encoding of the file from latin1 to utf-8?
It should be latin1 as the filename says.

**Comment by ghost** [comment]
I performed these changes using GitHub online editor in my broswer (Google Chrome).

GitHub displayed the following warning when I started editing the file: We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8.

**Comment by ghost** [comment]
I can't find any way to prevent this unexpected encoding change... And the GitHub Desktop application doesn't even work on my computer.

Please find below the changes suggested in menu_fr_fr.latin1.vim :

line 50 :
-menutrans Split\ &Diff\ with\.\.\.		&Difference\ avec\.\.\.
+menutrans Split\ &Diff\ with\.\.\.		&Différence\ avec\.\.\.

line 124 :
-let g:menutrans_textwidth_dialog = "Entrez la nouvelle largeur du texte\n(0 pour désactiver le formattage)."
+let g:menutrans_textwidth_dialog = "Entrez la nouvelle largeur du texte\n(0 pour désactiver le formatage)."

line 343 :
-tmenu ToolBar.SaveSesn			Enregister session courante
+tmenu ToolBar.SaveSesn			Enregistrer session courante

Feel free to accept / reject this patch.
With Best Regards,

**Comment by brammool** [comment]
I'll include the changes from the email.  Thanks!

**Pull request closed without merging**
