### PR TITLE
 Add async, await and template strings for Javascript syntax.

### PR DESCRIPTION
**Pull request by rsamuelklatchko**

### CODE REVIEW

**Comment by chrisbra** [comment]
I am not sure what the status for javascript syntax file is. Claudio is known to be unresponsive, I am not sure if the **Updater** is the new maintainer. Please try to contact him and discuss the changes with him.

**Comment by qstrahl** [comment]
https://github.com/pangloss/vim-javascript is the current go-to syntax plugin for JavaScript. There was talk of including it in vim as a default plugin a long time ago, I think, but I don't know what came of that.

**Comment by chrisbra** [comment]
still open https://github.com/pangloss/vim-javascript/issues/922

**Comment by brammool** [comment]
javaScriptStringT was already included, I added await and async now.

**Pull request closed without merging**
