### PR TITLE
User manual editing pass, chapters 1 through 4

### PR DESCRIPTION
**Pull request by tremby**
I got bored on a semi-recent flight and having forgotten to bring a book fell upon what I had to hand on my laptop, which was the vim user guide. I learnt some new tricks and also started noticing improvements I'd make to the text, and noting them down.

Today I did a pass through chapters 1 to 4 actually making the changes.

Since obviously many of these are subjective (though certainly some are I think objectively improvements), I've kept the changes split out to very small separate commits. I've given justification in some cases in the commit message bodies.

The hope is that if some kinds of changes are appreciated/wanted but others are not, I can get an idea of that, pull out the unwanted changes, and then produce less noise if/when I go through the rest of the manual. I'd be happy to do this, but of course won't spend the time if it wouldn't be welcome.

Clearly it'd be a good idea to squash commits together if/when a changeset will be accepted.

There's a mixture here of
- grammar tweaks
- consistency fixes like casing and quoting
- rewording for clarity
- rewording to avoid awkward words/phrases or to be more inclusive
- fixing incorrectly-used phrases (for example "e.g." to "i.e." in one case)

and some other miscellaneous bits.

### CODE REVIEW

**Comment by brammool** [comment]
Bart Nagel wrote:

> I got bored on a semi-recent flight and having forgotten to bring a
> book fell upon what I had to hand on my laptop, which was the vim user
> guide. I learnt some new tricks and also started noticing improvements
> I&#39;d make to the text, and noting them down.
> 
> Today I did a pass through chapters 1 to 4 actually making the changes.
> 
> Since obviously many of these are subjective (though certainly some
> are I think objectively improvements), I&#39;ve kept the changes split
> out to very small separate commits. I&#39;ve given justification in
> some cases in the commit message bodies.
> 
> The hope is that if some kinds of changes are appreciated/wanted but
> others are not, I can get an idea of that, and so produce less noise
> if/when I go through the rest of the manual. I&#39;d be happy to do
> this, but of course won&#39;t spend the time if it wouldn&#39;t be
> welcome.
> 
> Clearly it&#39;d be a good idea to squash commits together if/when a
> changeset will be accepted.
> 
> There&#39;s a mixture here of
> - grammar tweaks
> - consistency fixes like casing and quoting
> - rewording for clarity
> - rewording to avoid awkward words/phrases or to be more inclusive
> - fixing incorrectly-used phrases (for example &quot;e.g.&quot; to &quot;i.e.&quot; in one case)
> and some other miscellaneous bits.

Thanks for taking the time to look into this. Most of this text comes
from the book "Vi IMproved - Vim" and was already copy-edited.
Several things are a matter of taste.

For example, "Replace comma with semicolon before &#39;see x&#39;",
I would prefer the comma.

I would appreciate someone else, preferably a native English speaker, to
look through these changes.


-- 
Team-building exercises come in many forms but they all trace their roots back
to the prison system.  In your typical team-building exercise the employees
are subjected to a variety of unpleasant situations until they become either a
cohesive team or a ring of car jackers.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tremby** [comment]
I can absolutely tear out particular changes you don't agree with -- this is precisely why I made separate commits for things.

The fuller rationale for that particular change ("You can configure the Vim editor to produce backup files, see |07.4|" -> "You can configure the Vim editor to produce backup files; see |07.4|"): with a comma it could look like "see" is the start of a second list item -- another thing you can configure the Vim editor to do. And in some cases there may even be a comma-separated list, followed by "see X", and a semicolon would be more important in that situation for ease of reading and comprehension. Example with both issues:

> You can configure the Vim editor to produce backup files, see the future and write your code for you, see |07.4|.

The semicolon makes a longer gap as it's being read, and shows that there's a slight change of focus. A dash would do the same. But a comma doesn't do this. I stand by this change but you're the boss. :)

BTW, I am a native English speaker. I think you meant just that *you* are not, rather than saying that *I'm* not; I'm pointing it out just to be clear.

Did you have another reviewer in mind? I'd like to continue editing if I get the go-ahead from such a person, or from you.

**Comment by tremby** [comment]
> and was already copy-edited.

Not every editor catches everything, and cultures and feelings and priorities change too. One or two of my changes are for improved inclusivity, for example.

**Comment by dcslagel** [comment]
Hi @tremby, @brammool,  

Here is review feedback on some of this change.  My native language is english.

1. For instances of replacing comma with semi-colon, I checked with an college-level english teacher.  The semi-colon is correct.  Alternatively, sometimes the second idea can be a separate sentence.  
For example:
'The bars themselves may be hidden or invisible; see below.' 
could also be 
'The bars themselves may be hidden or invisible. See below.' 
So these would be good changes to make.

2. For instances of removing capitalization of the first word following a colon, it looks like there is a range of accepted styles in the different style manuals, and cultural differences between British and American usage. 
For Vim documentation, probably Bram's preference will be most consistent. 
So it makes sense to **not** make these changes.

3. For instances of adding double quotes around command letters, that looks consistent with other places in the manual. 
So these should be added.

DC

**Comment by tremby** [comment]
@dcslagel: thank you for this review. Just curious: which style manuals recommend capitals after colons? It's not something I've often seen before. (I grew up in the UK and now live in Canada.)

**Comment by dcslagel** [comment]
Hi , @tremby, I got that information from Wikipedia.  Here is the link:
https://en.wikipedia.org/w/index.php?title=Colon_(punctuation)
Go to the section 'Use of capitals'.  The exact quote listing the style guides is: "American English goes further and permits writers to similarly capitalize the first word of any independent clause following a colon. This follows the guidelines of some modern American style guides, including those published by the **Associated Press** and the **Modern Language Association**.".

I have to admit I didn't go and look up the style guides to verify. 

DC

**Comment by dcslagel** [comment]
@tremby, Here is the Modern Language Association's Style guide on colons.  
It supports your lowercase changes..  

https://style.mla.org/colons-how-to-use-them/

"Lowercase or Capital Letter after a Colon?
Use a lowercase letter when the word that follows the colon is normally lowercased:
    Bonnie had to admit what was already obvious to her roommates: she was allergic to the cat.

Use a capital letter when the colon introduces
    a rule or principle
    several related sentences
    a capitalized word such as a proper noun"

DC

**Comment by dcslagel** [comment]
@tremby, @brammool,

Here are some findings on the other style guides.   Does vim documentation follow a particular style guide?

 The Associated Press style guide and the Chicago Style guide are behind paywalls.  So I am unable to find definite information on them.  However this site has a comparative discussion:

https://apvschicago.com/2011/04/capitalization-after-colons.html

"AP (p. 366): Lowercase the first word unless it is a proper noun or the start of a complete sentence.

    These are some of my favorite things to have for dinner: ravioli, Ethiopian food and breakfast.
    She told me her secret ingredient: It was butter.

Chicago (6.61): Lowercase the first word unless it is a proper noun or the start of at least two complete sentences or a direct question.

    I finished reading my friend’s first draft: it was painful.
    We can do several things this weekend: We can watch King’s Speech. We can do our taxes. Or we can have a tequila party."

DC

**Comment by brammool** [comment]
I'll include some of this.  As remarks indicate: using semicolon seems like a good idea, but we'll keep the capital after a colon.  I'll probably miss a few pieces, please check after the next runtime file update.

**Pull request closed without merging**
