### PR TITLE
runtime(comment): fix commment toggle with mixed tab&spaces

### PR DESCRIPTION
**Pull request by habamax**
- fix regression where toggling doesn't properly remove comment chars in files with tabs indents only.
- refactor toggling comments for mixed tab&spaces files.

Relates https://github.com/vim/vim/issues/15797#issuecomment-2408822379

PS, I wanted to come up with tests but figured out there is regression so I had to fix it first.

I will introduce tests later, spent time on fixing regression.

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks!

**Comment by habamax** [comment]
I tried to come up with tests and failed miserably with the simplest one:

`test_pack_comment.vim`
```
vim9script

packadd comment

def g:Test_basic_comment()
    setline(1, "hello world")
    :1
    norm gcc
    assert_equal("/* hello world */", getline(1))
enddef
```

The result I can't unpack, looks like to test custom operators you need to do something extra?

```
$ make test_comment_pack
cd testdir; make test_comment_pack VIMPROG=../vim  SCRIPTSOURCE=../../runtime
make[1]: Entering directory '/home/habamax/prj/habamax-vim/src/testdir'
rm -f test_comment_pack.res test.log messages starttime
if test -n "${ASAN_OPTIONS}"; then \
        ASAN_OPTIONS="${ASAN_OPTIONS}_test_comment_pack" UBSAN_OPTIONS="${UBSAN_OPTIONS}_test_comment_pack" VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim --gui-dialog-file guidialog -U NONE --noplugin --not-a-term -S runtest.vim test_comment_pack.vim --cmd 'au SwapExists * let v:swapchoice = "e"' | LC_ALL=C awk '/Executing Test_/{match($0, "([0-9][0-9]:[0-9][0-9] *)?Executing Test_[^\\)]*\\)"); print substr($0, RSTART, RLENGTH) "\r"; fflush()}' ; \
else \
        VIMRUNTIME=../../runtime  ../vim -f  -u unix.vim --gui-dialog-file guidialog -U NONE --noplugin --not-a-term -S runtest.vim test_comment_pack.vim --cmd 'au SwapExists * let v:swapchoice = "e"' | LC_ALL=C awk '/Executing Test_/{match($0, "([0-9][0-9]:[0-9][0-9] *)?Executing Test_[^\\)]*\\)"); print substr($0, RSTART, RLENGTH) "\r"; fflush()}' ; \
fi
00:00 Executing Test_basic_comment()


From test_comment_pack.vim:
Executed Test_basic_comment()                      in   0.000575 seconds
Executed 1 test                          in   0.017187 seconds
1 FAILED:
Found errors in Test_basic_comment():
Caught exception in Test_basic_comment(): Vim(normal):E117: Unknown function: vim @ command line..script /home/habamax/prj/habamax-vim/src/testdir/runtest.vim[617]..function RunTheTest[57]..Test_basic_comment, line 4
make[1]: *** [Makefile:73: test_comment_pack] Error 1
make[1]: Leaving directory '/home/habamax/prj/habamax-vim/src/testdir'
make: *** [Makefile:2259: test_comment_pack] Error 2
```

**Comment by chrisbra** [comment]
Hm, I tried it and I see the same, not sure where the `vim` comes from :(

**Comment by chrisbra** [comment]
Perhaps it is easier to run this from a terminal test. E.g. run Vim in a terminal window with a specific file, feeding it some input keys like `gcc` (`term_sendkeys()`). This comes closer to real input handling. Then you can write the file and after closing the terminal Vim, you can inspect the newly written file.

**Pull request closed without merging**
