### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by zeertzjq**

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. I'll tag with `typo` and leave it open until we have collected a few of those to warrant a proper patch.

**Review by chrisbra — APPROVED** [review]

**Review by szepeviktor — APPROVED** [review]

**Comment by k-takata** [comment]
Could you also include this typo fix?

```diff
--- a/src/errors.h
+++ b/src/errors.h
@@ -3510,6 +3510,6 @@ EXTERN char e_invalid_format_specifier_str[]
 EXTERN char e_member_str_type_mismatch_expected_str_but_got_str[]
 	INIT(= N_("E1406: Member \"%s\": type mismatch, expected %s but got %s"));
 EXTERN char e_method_str_type_mismatch_expected_str_but_got_str[]
-	INIT(= N_("E1407: Member \"%s\": type mismatch, expected %s but got %s"));
+	INIT(= N_("E1407: Method \"%s\": type mismatch, expected %s but got %s"));
 
 // E1371 - E1399 unused
```

**Comment by k-takata** [comment]
Another one:
```diff
--- a/runtime/doc/builtin.txt
+++ b/runtime/doc/builtin.txt
@@ -2207,7 +2207,7 @@ environ()						*environ()*
 
 err_teapot([{expr}])					*err_teapot()*
 		Produce an error with number 418, needed for implementation of
-		RFC 2325.
+		RFC 2324.
 		If {expr} is present and it is TRUE error 503 is given,
 		indicating that coffee is temporarily not available.
 		If {expr} is present it must be a String.
```

https://datatracker.ietf.org/doc/html/rfc2324
https://en.wikipedia.org/wiki/Hyper_Text_Coffee_Pot_Control_Protocol

**Comment by zeertzjq** [comment]
I think this PR is large enough. It's been having merge conflicts every day :)

**Comment by chrisbra** [comment]
thank you! Will merge

**Pull request closed without merging**
