### PR TITLE
runtime(doc): Add missing null_<type> help tags

### PR DESCRIPTION
**Pull request by dkearns**
Problem:  Not all null_<type> values have a help tag
Solution: Add missing help tags

### CODE REVIEW

**Comment by errael** [comment]
I'm hoping that `null_class` will just disappear, #13501. Is there some way it could be used?

null_object is meaningful
```
var o = C.new()
o = null_object     # free resources
```

In fact, I'd like to see
```
var o: object
```
This, and variants like declaring a function argument type, could avoid some of the "E715: Dictionary required" errors.

**Comment by chrisbra** [comment]
thanks, can you please run `make tags` in the `runtime/doc` directory and commit on top?

**Review by yegappan — APPROVED** [review]

**Comment by chrisbra** [comment]
thanks!

**Comment by dkearns** [comment]
@errael, it sounds like a dedicated "Language Specification: Tossing Class References" discussion thread is needed.  Discussion is already in several disparate locations.

I find it difficult to sensibly answer these questions without understanding the intended eventual scope and capabilities of the language.

**Pull request merged**
