### PR TITLE
Fix: profiling for condition lines (e.g. `elseif`)

### PR DESCRIPTION
**Pull request by ichizok**
## Problem summary

There is a case that script line is not profiled in spite of executed.

## Repro steps

func.vim

```vim
func! Foo()
  if 0
    let x = 0
  elseif 1
    let x = 1
  endif
endfunc
call Foo()
```

`vim --clean +'profile start prof.log' +'profile func Foo' +'so func.vim' +'qall!'`

prof.log

```
FUNCTION  Foo()
Called 1 time
Total time:   0.000026
 Self time:   0.000026

count  total (s)   self (s)
    1              0.000007   if 0
                                let x = 0
                              elseif 1
    1              0.000004     let x = 1
    1              0.000003   endif

(snip)
```

The line of `elseif 1` was executed but not profiled (0 count).

## Cause

https://github.com/vim/vim/blob/master/src/ex_docmd.c#L2009-L2021

When `ea.skip` is false, `func_line_exec()` is called and do profiling for the line.
Basically means `ea.skip` depends on the state of the last line: `(cstack->cs_idx >= 0 && !(cstack->cs_flags[cstack->cs_idx] & CSF_ACTIVE))`, but `elseif` (or `else`) is executed when the last line is not active (==`ea.skip` is true).

Therefore I think it should take into account what the command of the line is, regarding to whether do profiling or not.

## In addition

```vim
func! Foo1()
  while 1
    break
  endwhile
endfunc

func! Foo2()
  while 1
    return
  endwhile
endfunc
```

Currently, profiling this, both `endwhile` of `Foo1` and `Foo2` are counted 0:

```
count
    1   while 1
    1     break
    0   endwhile

    1   while 1
    1     return
    0   endwhile
```

I think it should `endwhile` of `Foo1` is counted 1.
That is, when leaving from `while` (also `for`) loop by `break` or by the loop condition failure, I think `endwhile` (`endfor`) should be treated as executed and counted up.

### CODE REVIEW

**Comment by brammool** [comment]
Ozaki Kiichi wrote:

> ## Problem summary
> 
> There is a case that script line is not profiled in spite of executed.
> 
> ## Repro steps
> 
> func.vim
> 
> ```vim
> func! Foo()
>   if 0
>     let x = 0
>   elseif 1
>     let x = 1
>   endif
> endfunc
> call Foo()
> ```
> 
> `vim --clean +'profile start prof.log' +'profile func Foo' +'so func.vim' +'qall!'`
> 
> prof.log
> 
> ```
> FUNCTION  Foo()
> Called 1 time
> Total time:   0.000026
>  Self time:   0.000026
> 
> count  total (s)   self (s)
>     1              0.000007   if 0
>                                 let x = 0
>                               elseif 1
>     1              0.000004     let x = 1
>     1              0.000003   endif
> 
> (snip)
> ```
> 
> The line of `elseif 1` was executed but not profiled (0 count).

Yes, Vim does evaluate the condition.

> ## Cause
> 
> https://github.com/vim/vim/blob/master/src/ex_docmd.c#L2009-L2021
> 
> When `ea.skip` is false, `func_line_exec()` is called and do profiling for the line.
> Basically means `ea.skip` depends on the state of the last line: `(cstack->cs_idx >= 0 && !(cstack->cs_flags[cstack->cs_idx] & CSF_ACTIVE))`, but `elseif` (or `else`) is executed when the last line is not active (==`ea.skip` is true).
> 
> Therefore I think it should take into account what the command of the line is, regarding to whether do profiling or not.
> 
> ## In addition
> 
> ```vim
> func! Foo1()
>   while 1
>     break
>   endwhile
> endfunc
> 
> func! Foo2()
>   while 1
>     return
>   endwhile
> endfunc
> ```
> 
> Currently, profiling this, both `endwhile` of `Foo1` and `Foo2` are counted 0:
> 
> ```
> count
>     1   while 1
>     1     break
>     0   endwhile
> 
>     1   while 1
>     1     return
>     0   endwhile
> ```
> 
> I think it should `endwhile` of `Foo1` is counted 1.
> That is, when leaving from `while` (also `for`) loop by `break` or by the loop condition failure, I think `endwhile` (`endfor`) should be treated as executed and counted up.

I don't agree for the "return" case.  The "return" means Vim jumps out
of the function.  What follows is not executed, only skipped over.
While with the "break" Vim does sort-of execute the endwhile, it
terminates the matching "while".


-- 
"Hit any key to continue" it said, but nothing happened after F sharp.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
> I don't agree for the "return" case.  The "return" means Vim jumps out
> of the function.  What follows is not executed, only skipped over.

Sorry for the lack of clarity, I think so too: when `return`, `endwhile` should not be counted (0 count), same as current.

**Comment by ichizok** [comment]
Another (problematic) example

func.vim:

```vim
func! Cond()
  sleep 1
  return 1
endfunc
func! Foo()
  if 0
    let x = 0
  elseif Cond()
    let x = 1
  else
    let x = 2
  endif
endfunc
call Foo()
```

This is the case that a process taking time is called at elseif-conditional sentense.

`vim --clean +'profile start prof.log' +'profile func Foo' +'so func.vim' +'qall!'`

prof.log

```
FUNCTION  Foo()
Called 1 time
Total time:   1.005080
 Self time:   0.000050

count  total (s)   self (s)
    1              0.000004   if 0
                                let x = 0
                              elseif Cond()
    1              0.000018     let x = 1
    1              0.000002   else
                                let x = 2
                              endif

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   1.005080   0.000050  Foo()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   1.005080   0.000050  Foo()
```

`Foo()` took about 1 second, but this profiling result does not show where took time although `elseif Cond()` was executed.

Expected result:

```
FUNCTION  Foo()
Called 1 time
Total time:   1.005197
 Self time:   0.000058

count  total (s)   self (s)
    1              0.000008   if 0
                                let x = 0
    1   1.005160   0.000021   elseif Cond()
    1              0.000012     let x = 1
                              else
                                let x = 2
    1              0.000003   endif

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   1.005197   0.000058  Foo()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   1.005197   0.000058  Foo()
```

**Comment by blueyed** [comment]
@ichizok 
Is this ready from your side?
Are your comments / problems all fixed?

**Comment by ichizok** [comment]
> Are your comments / problems all fixed?

Yes (by latest commit).

**Comment by ZyX-I** [comment]
There is also a known problem that while skipping contributes to self time, profiling will give you no idea where time was actually spent. This is not a theoretical issues because skipping is fast, this is one of the major causes leading to my formatvim plugin being written using code generation, 2html AFAIR had the same issue, which resulted in using some code generation there as well.

You may see the problem by running `vim -u NONE -i NONE -N --cmd 'so proftest.vim'` with `proftest.vim` containing

```VimL
function! Test()
    let i = 0
    while i < 1000
        let i += 1
        if 0
            t
            " Repeat the above line another 1023 times
        endif
    endwhile
endfunction

profile start /tmp/profile.log
profile func Test
call Test()
profile pause
qa
```

. In the resulting profile you will see

    FUNCTION  Test()
    Called 1 time
    Total time:   0.583690
     Self time:   0.583690
    
    count  total (s)   self (s)
        1              0.000011     let i = 0
     1001              0.001230     while i < 1000
     1000              0.001294         let i += 1
     1000              0.000875         if 0
                                            t
                                            …
                                        endif
     1000              0.000756     endwhile
    
    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
        1   0.583690             Test()
    
    FUNCTIONS SORTED ON SELF TIME
    count  total (s)   self (s)  function
        1              0.583690  Test()
    
If you sum all times you will get 0.004166 which is two orders of magnitude less then displayed self time (0.583690).

**Comment by blueyed** [comment]
> coverage/coveralls — Coverage decreased (-19.5%) to 48.966%

Is this a problem with coveralls, or this PR?
Maybe try rebasing / retriggering the build?

**Comment by brammool** [comment]
There was a CI failure, this usually causes the coverage to be inaccurate.

About skipping lines: it's hard to say where the time for skipping should be counted.  We could put it on the "if 0", but then it merges with the time spent evaluating the expression.  Putting the time on the lines themselves would give the impression that they were executed.  In the example we could put the time on the "endif", but if an "elseif" follows it gets confusing again.  Would need to do something weird, such has having the "elseif" line twice, once with the skip time and once with executed time.

**Comment by blueyed** [comment]
@brammool 
There was no CI error IIRC (looks like this was pushed again after my comment).

> About skipping lines: it's hard to say where the time for skipping should be counted.

Having the line twice would be really weird indeed.

Couldn't there be another total ("Misc time") where it would be added to, without being on the line itself?

**Comment by blueyed** [comment]
I've used this patch with Neomake's test now.
You can see the difference at: https://codecov.io/gh/neomake/neomake/pull/2027/changes

**Comment by blueyed** [comment]
Yeah, the current build ran 3h ago.
Now one job timed out, that could be restarted.
However, coverage looks OK now.

**Pull request closed without merging**
