### PR TITLE
Correctly expand filenames if currentworking dir is ~

### PR DESCRIPTION
**Pull request by chrisbra**
So when $HOME is Vims current directory, it will be correctly shortened to `~/`. However when using `home_replace` to replace the path by `~/`, the directory separator will be put into dirname, which will make the following `STRLEN` count the length of the trailing directory separator. 

Because of this, the following `if()` condition, which checks if `p` points to a directory separator will fail and therefore, the leading `~/` won't be shortened.

As this seems to happen only for the special case of `~/`, simply check this case and subtract one from namelen.

related #6204 #5979

### CODE REVIEW

**Comment by HarmtH** [comment]
You've beaten me to it, although I would propose not special casing it in the first place, although it probably has its reasons (all the tests succeed though).

``` diff
diff --git a/src/filepath.c b/src/filepath.c
index ad7b8b03d..a8a0e7bc6 100644
--- a/src/filepath.c
+++ b/src/filepath.c
@@ -2396,11 +2396,6 @@ home_replace(
                if (--dstlen > 0)
                    *dst++ = '~';
 
-               /*
-                * If it's just the home directory, add  "/".
-                */
-               if (!vim_ispathsep(src[0]) && --dstlen > 0)
-                   *dst++ = '/';
                break;
            }
            if (p == homedir_env)
```

**Comment by chrisbra** [comment]
indeed, that might even be the proper fix. I am not sure, if this has unwanted consequences for the other call sites of `home_replace`.

**Comment by chrisbra** [comment]
hm, the newly added test fails on windows....

**Comment by brammool** [comment]
Looks like this is still in progress?

**Comment by chrisbra** [comment]
yes, I am struggeling with the windows part of it. I am currently thinking, that os_mswin.c `mch_FullName()` is actually incorrect about handling filenames like `~/foobar`, it will return a full path like `c:\users\<userid>\~\foobar` . And that causes problems later in `modify_fname()`. In contrast, os_unix `mch_FullName()` returns correctly `/home/userid/foobar`, which makes more sense. 

Trying to fix the windows `mch_Fullname()` however seems to completly mess up appveyor tests. Not sure what was going on there. I'am thinking about another way to fix this.

**Comment by chrisbra** [comment]
should be ready, once the tests succeed.

**Comment by chrisbra** [comment]
hm, appveyor failure seems to be related to the recent terminal handling changes.

**Pull request closed without merging**
