### PR TITLE
Fix netrw duplicated window #12304

### PR DESCRIPTION
**Pull request by stac47**
Hello,

I don't see any MR with th fix described within the issue #12304. Here it is.
Regards,

### CODE REVIEW

**Comment by brammool** [comment]
I already have this fix in my local copy, but I'm not 100% sure if Charles has it in the original version, thus I'll leave this open for now.

**Comment by cecamp** [comment]
Netrw is up to v173; I didn't see the duplicated window problem with it. That version has been sent on to Bram on or soon after May 3. Its also on my website.

**Comment by stac47** [comment]
Hey, Sorry for this silly question @cecamp, what is your website? (I mean on vim.org, the latest version is 150, googling did not give me relevant results and I don't find a pointer in the `netrw.vim`)

**Comment by stac47** [comment]
Oh I found out: http://www.drchip.org/astronaut/vim/index.html

**Pull request closed without merging**
