### PR TITLE
Redraw on right side of screen to cmd.exe only

### PR DESCRIPTION
**Pull request by ghost**
cmd.exe on Windows 10 does not scroll the right edge of the screen, It redraws at FEAT_VTP.
At the cmd.exe compatible terminal (ex. ConEmu) it breaks the screen.
This detected the terminal and split the process.

### CODE REVIEW

**Comment by brammool** [comment]
> cmd.exe on Windows 10 does not scroll the right edge of the screen, It
> redraws at FEAT_VTP.
> At the cmd.exe compatible terminal (ex. ConEmu) it breaks the screen.
> This detected the terminal and split the process.

Do you have a screenshot to illustrate the problem that this patch
fixes?


-- 
hundred-and-one symptoms of being an internet addict:
137. You decide to stay in college for an additional year or two,
     just so you can have the free Internet access.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
Currently in ConEmu it looks something like this.

screen c d__vim_vim_src - vim 2018_06_29 16_19_35

Stopping redrawing on the right:

screen c d__vim_vim_src - vim 2018_06_29 16_26_16

If redrawing on the right side of the screen is unnecessary, separate processing.

ConEmu may also have the cause of the failure. However, I want to do as much as I can.

**Comment by brammool** [comment]
That first screenshot looks quite bad.  Does a CTRL-L (clear + redraw) fix it?
I don't quite understand sending escape sequences to the console, doesn't this have side effects?

**Comment by ghost** [comment]
This movie pressed CTRL-E and CTRL-L alternaterly.
Even if I press CTRL-L more the once here, it will be the same movie.

os_win32

The result of the inquiry enters the input stream, it is written here:

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idquerystatespanspan-idquerystatespanspan-idquerystatespanquery-state

Source code to be sampled is not presented by Microsoft. This procedure is my creation.
Processing is simple, so there are no side effects.

**Comment by ghost** [comment]
ConEmu returns ```^[[?1;2c``` for inquiries.
cmd.exe returns ```^[[?1;0c``` .
Other than this method, terminals can not be distinguished.

Use ctrl+L, but the expected screen is not output.
Stop additional drawing to the right end of the screen, the expected screen is output.

Here I am reading the key buffer, I think that there was nothing in the standard input. I have tried it.

**Comment by ghost** [comment]
I mentioned ConEmu as an example here, but I applies to other cmd.exe compatible terminals as well.
There is a bug in scrolling vtp of cmd.exe.
Redraw on the right edge of the screen will fix it.
Due to my carelessness, it will not work properly with compatible terminals such as ComEmu.
I'm sorry.

**Comment by ghost** [comment]
ConEmu returns ```^[[?1;2c``` using this function with WriteConsoleInput.
Perhaps it is correct to read in ReadConsoleInput.
https://github.com/Maximus5/ConEmu/blob/0a4f947e930bf6ee98e6b1d6940e91982f68233b/src/ConEmuHk/Ansi.cpp#L2390

**Comment by ghost** [comment]
Ah, ```:term=xterm``` is recommended for ConEmu.
That means ```:term=win32``` is not used.
Oops... It's late to notice...
I close this issue. I had a misunderstanding.
Thank you very much.

**Comment by k-takata** [comment]
Do you mean that users should `:set term=xterm` explicitly on ConEmu?

**Comment by ghost** [comment]
I forgot being guided here.
https://conemu.github.io/en/VimXterm.html#requirements

This patch causes a new problem on ConEmu side.
Even for me.
I want to avoid it.

**Pull request closed without merging**
