### PR TITLE
Add Raml syntax highlighting and indent

### PR DESCRIPTION
**Pull request by leisurelicht**
Add indent and syntax highlighting support for raml files

### CODE REVIEW

**Comment by brammool** [comment]
> Add indent and syntax highlighting support for raml files

The syntax file says: 

	Maintainer:  Eric Hopkins <eric.on.tech@gmail.com>

But it appears you are someone else.
I would like the maintainer to state he is OK with including this file
with the Vim distribution.

-- 
Q:  Why do ducks have flat feet?
A:  To stamp out forest fires.

Q:  Why do elephants have flat feet?
A:  To stamp out flaming ducks.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leisurelicht** [comment]
I got syntax file from [vim-raml](https://github.com/IN3D/vim-raml) and find he use WTFPL license.
So I think it‘s ok. Should I contant him first？

**Comment by chrisbra** [comment]
Why is a special syntax highlighting file needed? RAML is a syntax for defining API calls and uses the YAML specification, so why do we need an extra syntax file?

**Comment by leisurelicht** [comment]
> Why is a special syntax highlighting file needed? RAML is a syntax for defining API calls and uses the YAML specification, so why do we need an extra syntax file?

Yes, raml is base on yaml specification. But now raml have a lot of different keyword.

**Comment by brammool** [comment]
> I got syntax file from [vim-raml](https://github.com/IN3D/vim-raml)
> and find he use WTFPL license.  So I think it‘s ok. Should I contant
> him first？

WTFPL is not regarded a real license.  It also has a problem because
including it means including bad language, and not including it means
the license isn't specified.

Best is if this can be included under the Vim license, with a remark
stating that in the file itself.  Please ask the author about that.
And best is if the author sends it directly to me.


-- 
I have to exercise early in the morning before my brain
figures out what I'm doing.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by IN3D** [comment]
>Best is if this can be included under the Vim license, with a remark stating that in the file itself. Please ask the author about that. And best is if the author sends it directly to me.

Hi Bram, I'm the original author of vim-raml.

Your comments about the license (or lack thereof) are correct, it was a poor choice of mine at the time. After seeing a couple of emails regarding this I've now updated my plugin to use the Vim license.

I won't have much time for the next week or two; but if there's interest in bringing RAML syntax into Vim itself I would very happy to make a pull request as the original author later.

**Comment by brammool** [comment]
Eric Hopkins wrote:

> >Best is if this can be included under the Vim license, with a remark
> >stating that in the file itself. Please ask the author about that.
> >And best is if the author sends it directly to me.
> 
> Hi Bram, I'm the original author of vim-raml.
> 
> Your comments about the license (or lack thereof) are correct, it was
> a poor choice of mine at the time. After seeing a couple of emails
> regarding this I've now updated my plugin to use the Vim license.

Thanks, that avoids any confusion.

> I won't have much time for the next week or two; but if there's
> interest in bringing RAML syntax into Vim itself I would very happy to
> make a pull request as the original author later.

I can include what's there now, but I hope you can update the license
remark soon.

-- 
   LAUNCELOT leaps into SHOT with a mighty cry and runs the GUARD through and
   hacks him to the floor.  Blood.  Swashbuckling music (perhaps).
   LAUNCELOT races through into the castle screaming.
SECOND SENTRY: Hey!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leisurelicht** [comment]
> I can include what's there now, but I hope you can update the license remark soon.

Eric Hopkins have updated vim-raml to use vim license。 
So I am updated my syntax file remark to use vim license like vim-raml and push it, should I just create a new pull request?

**Comment by brammool** [comment]
> > I can include what's there now, but I hope you can update the
> > license remark soon.
> 
> I am update the file license remark to vim now, should I just create a
> new pull request ?

Thanks!  I just downloaded the current version now.  If you make further
changes, it's easiest for me if you send me the whole file.

-- 
PRINCE:    He's come to rescue me, father.
LAUNCELOT: (embarrassed) Well, let's not jump to conclusions ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by leisurelicht** [comment]
> Thanks! I just downloaded the current version now. If you make further changes, it's easiest for me if you send me the whole file.

I am created a new pull request https://github.com/vim/vim/pull/3596 to update syntax and indent file remark to use vim license.

**Pull request closed without merging**
