### PR TITLE
A typo in a variable name breaks conversion with :TOhtml

### PR DESCRIPTION
**Pull request by lyokha**
This patch replaces `s:settings_no_doc` -> `s:settings.no_doc`

### CODE REVIEW

**Comment by brammool** [comment]
It's easy enough to include the fix, but please contact the maintainer.  The email address is in the header.

**Comment by fritzophrenic** [comment]
Thanks, it has been a long time since I put out an update. I'll try to get something out while I'm off work this week for the holidays.

**Comment by fritzophrenic** [comment]
As it turns out, this issue has already been fixed, presumably by Bram, here: https://github.com/vim/vim/commit/f1dcd14fc5d4370476cd82895a4479ca2d252e54#diff-0fd732992c6f1a9b27a162d1fbb5e849b7fa49965a8f83779e5bb4a57ac121be

My task now is to integrate this change, along with the entire addition of new features which I was unaware of, from here: https://github.com/vim/vim/commit/6ebe4f970b8b398087076a72a7aae6e680fb92da#diff-0fd732992c6f1a9b27a162d1fbb5e849b7fa49965a8f83779e5bb4a57ac121be

That commit a couple months ago added g:html_no_doc, h:html_no_links, and g:html_no_modeline. I'll pull in the changes, add a couple tests, and make it a new version before adding some other bugfixes that are in my TODO list.

**Comment by yegappan** [comment]
Any updates on this?

**Comment by fritzophrenic** [comment]
Should be fixed in be4e01637e71c8d5095c33b9861fd70b41476732

**Comment by lyokha** [comment]
Yes, it is fixed, at least in my

```ShellSession
$ vim --version 
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 13 2023 00:00:00)
```

**Pull request closed without merging**
