### PR TITLE
syntax: dockerfile: Add LABEL, ARG and STOPSIGNAL commands

### PR DESCRIPTION
**Pull request by t-nelis**
Per reference documentation at:
https://docs.docker.com/engine/reference/builder/

### CODE REVIEW

**Comment by chrisbra** [comment]
please contact the syntax script maintainer and discuss the issue with him. Thanks.

**Comment by t-nelis** [comment]
@chrisbra Done, thanks.

**Comment by honza** [comment]
+1

**Comment by chrisbra** [comment]
@honza, since you are the maintainer of the file, please include the patch it in your version and send the updated file to Bram for inclusion with Vim. Once this is done, I'll close this then. Thanks!

**Comment by honza** [comment]
I'm confused. Are you saying you want me to email the patch to the maintainer instead of merging the pull request?

**Comment by chrisbra** [comment]
@honza we are not using githubs PR workflow. The old e-mail based workflow is still the current method for updating runtime files. That means, you as maintainer apply the patch locally to your master version of the runtime file. You then send the whole file to Bram for inclusion with the next runtime files update.

This avoids inconsistencies and also does not depend on github as development form, while we can still use github as hosting provider.

**Comment by honza** [comment]
@chrisbra Sounds good. I'll get it done ASAP.

**Comment by honza** [comment]
@chrisbra The patch was committed [4 days ago](https://github.com/vim/vim/commit/0952131376a517fc12dc5ae908a97018b4ee23f0#diff-b31c517c9785059e366523fbf07f734f). I think we can close this now.

**Comment by MrScriptMaster** [comment]
Ваш отчет успешно принят и ожидает проверки.

**Pull request closed without merging**
