### PR TITLE
Custom cmdline completion support

### PR DESCRIPTION
**Pull request by Shougo**
I have added two features.

* `getcmdcompltype()` returns custom and customlist functions

* `getcompletion()` supports both custom and customlist

Both features are useful for auto completion plugins.

### CODE REVIEW

**Comment by Shougo** [comment]
Hm....

If I fix the memory leak, the tests are failed.  Can you tell me the solution?

**Comment by Shougo** [comment]
Tests are passed.

**Comment by brammool** [comment]
> No comment for the PR?

Should be OK, I'll put it in the todo list.

-- 
BRIDGEKEEPER: What is the air-speed velocity of an unladen swallow?
ARTHUR:       What do you mean?  An African or European swallow?
BRIDGEKEEPER: Er ...  I don't know that ... Aaaaarrrrrrggghhh!
   BRIDGEKEEPER is cast into the gorge.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Shougo** [comment]
Thanks.

**Review by zeertzjq — APPROVED** [review]
LGTM.

This may be backward-incompatible for plugins that compare the return value of `getcmdcompltype()` with the strings "custom" or "customlist", but no plugin seems to be doing that.

**Review by chrisbra — APPROVED** [review]

**Comment by zeertzjq** [comment]
This needs a rebase now.

**Comment by Shougo** [comment]
I have rebased it.

**Comment by zeertzjq** [comment]
Needs another rebase now.

**Comment by Shougo** [comment]
I have rebased now.

**Pull request closed without merging**
