### PR TITLE
Popup window with title is flickering on gVim.exe

### PR DESCRIPTION
**Pull request by rbtnn**
This PR will be fix the flickering.

__before__
before
__after__
after

### CODE REVIEW

**Comment by vim-ml** [comment]
Op vr 20 nov. 2020 11:40 schreef Naruhiko Nishino <vim-dev-github@256bit.org
>:

> This PR will be fix the flickering.
>

+	    if (0 < title_len)
+	    {


Personally, I find this inverted condition hard to read. Could you
change it to tl>0?


Thanks!


Christ van Willegen

**Comment by rbtnn** [comment]
>Personally, I find this inverted condition hard to read. Could you
>change it to tl>0?
>
>
>Thanks!
>
>
>Christ van Willegen

Thank you for this reviewing. I fixed the inverted condition.

**Comment by brammool** [comment]
Any relation with #7317 ?  Or are the two completely separate?

**Comment by rbtnn** [comment]
These are the two completely separate.

**Pull request closed without merging**
