### PR TITLE
fix spelling error

### PR DESCRIPTION
**Pull request by uniontech-lilinjie**
Signed-off-by: lilinjie <102012657+uniontech-lilinjie@users.noreply.github.com>
fix spelling error

### CODE REVIEW

**Comment by brammool** [comment]
Have you contacted the maintainer?   I don't know a github user name for "scootergrisen", unfortunately.

**Comment by brammool** [comment]
Note that there is also this PR: https://github.com/vim/vim/pull/10703
I hope someone can find the maintainer, or otherwise someone can take over.

**Comment by nickspoons** [comment]
Is this fix even correct? I know Danish as a second language, not a native speaker, but I would have thought "patchet af" was more correct than "patched af". Tricky because "patch" is not a danish word, so I'm not 100% sure how the past tense is applied here.

**Comment by nickspoons** [comment]
Apologies, I have verified with another dansker that "patched af" is the preferred usage, so this PR is correct.

**Comment by brammool** [comment]
OK, I'll include it then.  If the maintainer objects we can change it again or revert.

**Pull request closed without merging**
