### PR TITLE
pythoncomplete: quash possible messages from evaling user code

### PR DESCRIPTION
**Pull request by yousong**
```
Problem:  Python packages like scapy outputs fair amount of warning
          messages at import time when detecting its runtime
          environment.  This is irrelevant in the context of
          pythoncomplete
Solution: silent! the vimcomplete python call and unsilent the showdbg
          call there within
```

### CODE REVIEW

**Comment by yousong** [comment]
Hi, do I need to provide extra input to move the pull request forward?

**Comment by k-takata** [comment]
Have you tried to contact the maintainer of this file?

**Comment by yousong** [comment]
Hi, @k-takata , thanks for the response!

> Have you tried to contact the maintainer of this file?

Not yet.  Should I contact Aaron the author of the file and make the change appear in [1] first, then wait and see it brought into vim repo here?

 [1] http://www.vim.org/scripts/script.php?script_id=1542

**Comment by k-takata** [comment]
Yes, please.
Please also check [CONTRIBUTING.md](https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files).

**Comment by yousong** [comment]
Thanks for the instructions.  I am closing this for now.

**Comment by k-takata** [comment]
If the maintainer didn't response, feel free to reopen this PR.

**Comment by yousong** [comment]
Hello, I contacted Aaron the maintainer of pythoncomplete a while ago and learned that he has not been doing vim development for quite a while and as such the content at vim.com is now not maintained.

**Comment by chrisbra** [comment]
so, would you like to become the new maintainer?

**Comment by yousong** [comment]
Switched to https://github.com/python-mode/python-mode

**Pull request closed without merging**
