### PR TITLE
Update table in 'compatible' to match code behaviour

### PR DESCRIPTION
**Pull request by HaleTom**
Make the table in 'compatible' reflect the behaviour of the code in
option.c

Resolves issue #1139

There are three relvant variations on when a related option changes when
setting / unsetting 'compatible'. Document these the clearly.

Also clarify the meaning of the previously disconnected sentence:

> "See the option marked with a '+' below."

### CODE REVIEW

**Comment by HaleTom** [comment]
There are some blanks in the `effect` column which needs the attention of someone far more familiar with `vim` than I am.

Still, the "what and when" alignment with options.c` has been done. I didn't want to get bored or make a mistake, so I wrote a [shell script](https://gist.github.com/HaleTom/a793106d85cf7be1bdb873631a9e1553) to do the grunt work for me.

**Comment by brammool** [comment]
Options are reset, not unset.

We need all the values for the "set value" column.  In most cases it's just the default value.
Otherwise it's the Vi default.

**Comment by HaleTom** [comment]
I've filled the `set default` column with the `vi default` value as listed in `:help`. I used `default` value if there is no difference listed between `vi` an `vim` defaults.

Sometimes this seems strange, for example `tagcase` doesn't list a `vi default` even though there is supposedly a different default based on the table in #1139.
1. I suggest you carefully review all the options this may effect (those marked with a `*`).
2. I need your help in describing `'cscoperelative'` in 39 ASCII characters

**Comment by brammool** [comment]
I am including the patch.

**Pull request closed without merging**
