### PR TITLE
Update asterisk syntax

### PR DESCRIPTION
**Pull request by 532910**
Add switch statement
https://wiki.asterisk.org/wiki/display/AST/Switch+Statements

More codecs
https://wiki.asterisk.org/wiki/display/AST/Asterisk+Audio+and+Video+Capabilities

Spaces are allowed between equal

### CODE REVIEW

**Comment by k-takata** [comment]
Have you tried contacting the maintainer?

**Comment by 532910** [comment]
I've just sent him a letter.

**Comment by jaunis** [comment]
Hello,
All right for the new codecs and the switch keyword, but I have doubts about the other modification.
You allow spaces before the "=" sign when setting variables; I believe it is not valid: https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Application_Set

And it has the side-effect of breaking dialplan extension highlighting, although I don't understand why.

**Comment by 532910** [comment]
> https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Application_Set

Indeed, `Set(QWE = qwe)` produces warning `Please avoid unnecessary spaces on variables as it may lead to unexpected results ('QWE ' set to ' qwe').`

But I added spaces for context options, for example:

```
[tcp]
        type = transport
```
spaces are allowed here
https://wiki.asterisk.org/wiki/display/AST/Asterisk+Main+Configuration+File

**Comment by jaunis** [comment]
In this case the syntax file should be re-written to properly differentiate context options from variables (which is not so easy, admittedly).

Since the current modification introduces a regression in extensions highlighting, I think it should not be included in this pull request. I suggest you republish the pull request with only the 1st and 3rd line included. Re-writing the file for context options handling may go in a separate pull-request.

**Comment by 532910** [comment]
Agree, done.

**Comment by 532910** [comment]
https://github.com/vim/vim/issues/7070

**Comment by jaunis** [comment]
OK for me but I don't have the merging rights.

**Comment by 532910** [comment]
Yep, I know.

**Comment by brammool** [comment]
I see that the maintainer OK'ed this change, thus I'll include it.  Please don't forget to update your own copy.

**Pull request closed without merging**
