### PR TITLE
Fix crash of system()

### PR DESCRIPTION
**Pull request by mattn**
https://groups.google.com/d/msg/vim_use/_-leBpqJ4hs/Xwouf0l7BwAJ

And maybe https://groups.google.com/d/msg/vim_dev/FLCEaLv4cpk/dJILEsASBgAJ

### CODE REVIEW

**Comment by mattn** [comment]
Sorry, still wrong.

**Comment by k-takata** [comment]
Is really the block `else STRCPY(buf, cmd);` needed? Before 8.1.2092, such block doesn't exist.

**Comment by mattn** [comment]
I had mistakely removed the STRCPY.

https://github.com/vim/vim/commit/1a613398068580ca1286ac2ed920f20c978aa662#diff-64502d25491840f7291ee96e905111c1L1769

**Comment by k-takata** [comment]
Ah, you are right.

**Comment by k-takata** [comment]
Hmm, but then, the `STRCPY(buf, cmd);` line is also needed in the `else if (itmp != NULL)` block?

**Comment by mattn** [comment]
How about this?
```diff
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 3679b1fc4..c457ee20b 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -1776,7 +1776,10 @@ make_filter_cmd(
 	    STRCAT(buf, itmp);
 	}
     }
-    else if (itmp != NULL)
+    else
+    {
+	STRCPY(buf, cmd);
+	if (itmp != NULL)
 	{
 	    char_u	*p;
 
@@ -1803,8 +1806,7 @@ make_filter_cmd(
 		}
 	    }
 	}
-    else
-	STRCPY(buf, cmd);
+    }
 #endif
     if (otmp != NULL)
 	append_redir(buf, (int)len, p_srr, otmp);
```

**Comment by mattn** [comment]
Could you please check newest change?

**Comment by k-takata** [comment]
Looks okay now.

**Pull request closed without merging**
