### PR TITLE
Add support for sourcing a Vim9 script from a buffer

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by habamax** [comment]
Can it source the following:

```
vim9script

def Hello()
   var myList = ['multi',
            'lined',
            'list'
            ]
   echo myList[0]
enddef

nnoremap <F5> <ScriptCmd>Hello()<CR>
```

* `:4,7source`
* `:11source` -- would proper script context be used here?
?

**Comment by brammool** [comment]
We can keep using sourcing_a_script(), hide the details of how that is decided.

I don't think we should try to be clever and detect the kind of script.  If someone sources some sequence of buffer lines we can't really know whether they are legacy or Vim9 script.  They could even be some lines in a help file. We can require using "vim9cmd source".  Unless "vim9script" is the first command in the range of lines.

We also need to define what happens when sourcing from the same buffer again.  I suppose this would work like "vim9script noclear".  That way you could, for example, source a function again after modifying it.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Mar 20, 2022 at 3:43 AM Bram Moolenaar ***@***.***>
wrote:

> We can keep using sourcing_a_script(), hide the details of how that is
> decided.
>
I have updated the PR to restore this function.


> I don't think we should try to be clever and detect the kind of script. If
> someone sources some sequence of buffer lines we can't really know whether
> they are legacy or Vim9 script. They could even be some lines in a help
> file. We can require using "vim9cmd source". Unless "vim9script" is the
> first command in the range of lines.
>
Currently the code relies on the first sourced line to detect the script
type and
doesn't try to detect the type of script.


> We also need to define what happens when sourcing from the same buffer
> again. I suppose this would work like "vim9script noclear". That way you
> could, for example, source a function again after modifying it.
>
>
> Yes. I have added a test for sourcing a Vim9 script with a function
multiple times.

- Yegappan

**Comment by brammool** [comment]
There is a remark in the help about using the same SID when sourcing multiple times.
It would be good to say a few things about what happens when redefining a function.  I suppose that works.
But other items from the script are still there, thus it would work like "vim9script noclear".
As is explained at "vim9-reload".

When sourcing just a few lines, e.g. from a help buffer, "vim9cmd source" should work.
Please add a test for that.

**Comment by Shane-XB-Qian** [comment]
#9967

// let me add a refer/remark to there to show the diff with legacy one.

--
shane.xb.qian

**Comment by habamax** [comment]
> To source a Vim9 script from a buffer, it must start with "vim9script" as the first line. For a legacy script, you can source any range of lines.

I have this operator to run both vimscript and vim9script ranges:

```
# source vimscript (operator)
def SourceVim(...args: list<any>): any
    if len(args) == 0
        &opfunc = matchstr(expand('<stack>'), '[^. ]*\ze[')
        return 'g@'
    endif
    if getline(1) =~ '^vim9script$'
        vim9cmd :'[,']source
    else
        :'[,']source
    endif
    return ''
enddef
nnoremap <silent> <expr> <space>v SourceVim()
xnoremap <silent> <expr> <space>v SourceVim()
nnoremap <silent> <expr> <space>vv SourceVim() .. '_'
```

**Pull request closed without merging**
