### PR TITLE
consolidate python indent config

### PR DESCRIPTION
**Pull request by lacygoill**
See https://github.com/vim/vim/pull/10929 for more context.

### CODE REVIEW

**Comment by brammool** [comment]
Maybe my comment on the previous PR didn't get through or was unclear.
Currently, if a user changes "g:pyindent_continue" after the indent is used, it will take effect.
After this change that no longer works, thus it's not backwards compatible, even though the value is used once.
It will be a little bit more work, but it is possible to maintain backwards compatibility with some extra work.
Like there currently is an exists() call.
Same for the other existing g:pyindent_ values, looks like there are three.

**Comment by lacygoill** [comment]
> Maybe my comment on the previous PR didn't get through or was unclear.

It seems the comment didn't get through to GitHub.

   > Currently, if a user changes "g:pyindent_continue" after the indent is used, it will take effect.
   > After this change that no longer works, thus it's not backwards compatible, even though the value is used once.
   > It will be a little bit more work, but it is possible to maintain backwards compatibility with some extra work.
   > Like there currently is an exists() call.
   > Same for the other existing g:pyindent_ values, looks like there are three.

OK, I'll try to improve the PR.

**Comment by lacygoill** [comment]
> Currently, if a user changes "g:pyindent_continue" after the indent is used, it will take effect.
   > After this change that no longer works, thus it's not backwards compatible, even though the value is used once.
   > It will be a little bit more work, but it is possible to maintain backwards compatibility with some extra work.
   > Like there currently is an exists() call.
   > Same for the other existing g:pyindent_ values, looks like there are three.

Actually, I think I already noticed the issue and fixed it in [this commit](https://github.com/vim/vim/pull/10929/commits/525620190ca83d876b49d2f98f244b074ee4d6c8).

`g:python_indent.continue` is not computed when the script is sourced.  It's computed when the indent function is called via an `eval()`:

    return indent(a:lnum - 1) + g:python_indent.continue->eval()
                                                          ^----^

Same thing for `g:python_indent.nested_paren` and `g:python_indent.open_paren`:

    return indent(plnum) + g:python_indent.nested_paren->eval()
                                                         ^----^

    return indent(plnum) + g:python_indent.open_paren->eval()
                                                       ^----^

So, it should be backward compatible.  I'll make more tests later to be sure.

BTW, `exists()` is no longer used; it's replaced by `get()`, which defaults to 0 without the third optional argument.  This means that if the keys are not set, they don't add or remove anything to the computed indentation level, just like before.

**Comment by brammool** [comment]
But the value of ""g:pyindent_continue" is only taken once, if the user changes it later it has no effect.
One can change "g:python_indent.continue" but that is not backwards compatible.

**Comment by brammool** [comment]
Looks OK.  The first block in the test should not have INDENT_EXE, so that the default values are set in g:python_indent.

**Pull request closed without merging**
