### PR TITLE
Add larger Windows icon sizes

### PR DESCRIPTION
**Pull request by planteen**
Looks better on HiDPI displays (e.g., 4k 3840x2160 resolution). Rasterized Linux SVG icon. Added sizes are 256x256, 96x96, 80x80, 72x72, 64x64, 60x60, 48x48, 40x40, 32x32, 24x24, 20x20, 16x16 at 32bpp and 64x64, 48x48, 32x32, 16x16 at 8bpp. Left existing 4bpp 32x32 and 16x16 icons.

### CODE REVIEW

**Comment by brammool** [comment]
Cody Planteen wrote:

> Looks better on HiDPI displays (e.g., 4k 3840x2160 resolution).
> Rasterized Linux SVG icon. Added sizes are 256x256, 96x96, 80x80,
> 72x72, 64x64, 60x60, 48x48, 40x40, 32x32, 24x24, 20x20, 16x16 at 32bpp
> and 64x64, 48x48, 32x32, 16x16 at 8bpp. Left existing 4bpp 32x32 and
> 16x16 icons.

Thanks.  It's a big file, is there a way to make it smaller?

Can a few people try it out and check that it looks good?

## 

hundred-and-one symptoms of being an internet addict:
28. You have comandeered your teenager's phone line for the net and even his
    friends know not to call on his line anymore.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by planteen** [comment]
Yes, the large sizes can be compressed.

I have heard that having a compressed 256x256 icon may cause problems with Windows XP. See here:
http://icofx.ro/forum/viewtopic.php?f=3&t=603

I have not tried a compressed icon on Windows XP myself. I'll try to get my hands on an old XP machine to test a compressed icon. Is XP compatibility still desired for gvim?

**Comment by brammool** [comment]
Cody Planteen wrote:

> Yes, the large sizes can be compressed.
> 
> I have heard that having a compressed 256x256 icon may cause problems with Windows XP. See here:
> http://icofx.ro/forum/viewtopic.php?f=3&t=603
> 
> I have not tried a compressed icon on Windows XP myself. I'll try to
> get my hands on a machine to test a compressed icon. Is XP
> compatibility still desired for gvim?

Yes, we support Windows XP.

400 Kbyte is a lot for an icon.  And that page states that it can't be
compressed if it needs to work on XP.

Is there a way to include two icons, and the big one is only used on
Windows 7 and up?  I suppose that might not be possible.

## 

How To Keep A Healthy Level Of Insanity:
7. Finish all your sentences with "in accordance with the prophecy".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by planteen** [comment]
For a compromise, I removed the 256x256 icon size. A compressed 256x256 icon could be added someday in the future when Windows XP support is not required. This reduces the file size from 418 KiB to 154 KiB. It still looks much better on HiDPI displays. The taskbar icon display looks great on Windows 10 when using multiple displays that mix HiDPI and regular DPI. Thoughts?

**Comment by brammool** [comment]
If you look at the 32x32 icon, it's very blurry and the colors are off.
The 32x32 icon in this set should be very similar to the original one.

**Comment by scootergrisen** [comment]
I just put this text in here from another issue so its the same place.

> It seems the largest icon that the Windows exe have is 48 pixels.
> 
> I suggest adding larger icons.
> Like up to 256 pixels or whatever is good.
> It seems the largest i can view in Windows 7 is 256 pixels.
> 
> Also the 48 pixel icon does not look good. It looks like it have been upscaled from a smaller icon as opposed to being downscaled from a larger icon.
> 

45953826-91e9ec00-c00b-11e8-933c-f4a607499753

**Comment by brammool** [comment]
> I just put this text in here from another issue so its the same place.
> 
> > It seems the largest icon that the Windows exe have is 48 pixels.
> > 
> > I suggest adding larger icons.
> > Like up to 256 pixels or whatever is good.
> > It seems the largest i can view in Windows 7 is 256 pixels.
> > 
> > Also the 48 pixel icon does not look good. It looks like it have been upscaled from a smaller icon as opposed to being downscaled from a larger icon.

Note that we still don't have a set of icons with good sharpness and
colors.

-- 
hundred-and-one symptoms of being an internet addict:
27. You refer to your age as 3.x.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Closing this, as there has been no progress.

**Pull request closed without merging**
