### PR TITLE
Add columnspace option

### PR DESCRIPTION
**Pull request by tkonolige**
This patch adds a option for setting the space between columns in a GUI.

Let me know if there is anything this patch needs.

### CODE REVIEW

**Comment by chrisbra** [comment]
what problem does this solve?

**Comment by tkonolige** [comment]
It is in the todo list ([`runtime/doc/todo.txt`](https://github.com/vim/vim/blob/169ebb080454357279ad5ad21ac532deaec605e8/runtime/doc/todo.txt#L2584)).

Some fonts either have too much spacing or too little spacing between letters. This allows users to adjust how tight or loose character spacing is.

**Comment by chrisbra** [comment]
And where is p_columnspace used? I only see the basic initialization, but it is not used anywhere. What sense has this?

**Comment by tkonolige** [comment]
This is just to get the option into the editor so other GUI's can use it. Specifically, we would like this in mccvim: macvim-dev/macvim#321

**Comment by chrisbra** [comment]
That would have been useful information that should be mentioned at  the description.

I think this should possible also be usable by at least the gtk and windows builds. I am not sure about a new option, can't we use the 'renderoptions' for that?

**Comment by nuko8** [comment]
I'm wondering if the proposed way -- adding pixels between wrongly designed glyphs -- addresses the following concerns:
1.  **How to assign pixels**  For left-to-right sentences, which side are additional pixels given?  Or, are they given evenly on both sides?   What to do when the given number of pixels is odd?  What if right-to-left sentences?
2. **Font Substitution** The proposed way could be OK for some Latin font faces having wrongly designed glyphs.  But what happens to font substitution?  Does the proposed way work well for double-width characters, symbols. or emoji?
3. **Rendering Engine Dependency**  For some rendering engines, it looks possible to specify additional spacing by the number of pixels.  But other engines prefer constants such as `condensed`, `normal` and `expanded` without or with prefix `semi`, `extra` or `ultra` to the number of pixels.  Which is the better way to specify additional spacing?  Can we make a unified interface or option for that for our various GUIs?

I think those concerns have kept an idea like "Add spacecolumn option" staying in the TODO list.

**Comment by tkonolige** [comment]
1. Either side should work.
2. I'm not sure how to handle this.
3. Fonts already render differently on various rendering engines. `columnspace` just allows the user to fix these errors. If the engine doesn't support pixel spacing, it can map a pixel value to its internal constants.

**Comment by brammool** [comment]
This is not useful without any GUI actually using it.

**Comment by brammool** [comment]
No update for a long time, therefore closing.

**Pull request closed without merging**
