### PR TITLE
Fix for messages behavior depends on 'fileformat' of current buffer 

### LINKED ISSUE #11735: messages behavior depends on 'fileformat' of current buffer
### Steps to reproduce

1. Run `vim --clean`
2. Run `:echomsg "\r"`
3. `^M` is printed
4. Run `:messages`
5. `^M` is printed
6. Run `:setlocal fileformat=mac`
7. Run `:messages`
8. `^J` is printed

### Expected behaviour

Changing 'fileformat' of current buffer should not affect messages behavior

### Version of Vim

9.0.1046

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by cero1988**
This fixes #11735

### CODE REVIEW

**Comment by chrisbra** [comment]
I slightly changed your description

**Comment by brammool** [comment]
What message depends on the 'fileformat' value of the buffer?  Can't we use all messages with EOL_UNIX?

**Comment by cero1988** [comment]
before to print each message, the eol characters are printed as It were printed originally
before committing, the eol characters were being all printed in regard of the current buffer filetype

**Comment by cero1988** [comment]
now I have understood
I agree, we can use EOL_UNIX for all messages
I will update the pull requests to do so

**Comment by cero1988** [comment]
I have updated the pull request, what do you think ?

**Comment by brammool** [comment]
> now I have understood
> I agree, we can use EOL_UNIX for all messages
> I will update the pull requests to do so

Seeing the adjusted patch, the CAR to NL translation, when 'fileformat'
is "mac" for the buffer, is used for the :echomsg command and for the
:messages command.  I don't understand why.  The translation is useful
when taking text from the buffer that is using Mac format.  These
commands do not really do that.  Especially :messages, which lists
various messages with text from any buffer.

How about this approach instead:
- In transchar_nonprint(), when "buf" is NULL then do not check for
  'fileformat' to be EOL_MAC.  Thus non CAR to NL translation
- In most places in src/message.c where a "transchar" function is
  called, pass a NULL buffer. E.g. "transchar(name)" would become
  "transchar_buf(NULL, name)".


-- 
hundred-and-one symptoms of being an internet addict:
91. It's Saturday afternoon in the middle of May and you
    are on computer.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cero1988** [comment]
thanks for the tips, I will update the code and reopen the pull request

**Pull request closed without merging**
