### PR TITLE
Fix undo test flakiness

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:    Undo test is flaky.
Solution:   Change time to "1 second ago" in both dumps.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Hmm, it can actually be "2 seconds ago" in https://github.com/vim/vim/actions/runs/5838947710/job/15836564531?pr=12625

**Comment by chrisbra** [comment]
I am confused. Where are those `.vim` files used? They are not dumps, and you did not reference it in any tests?

**Comment by zeertzjq** [comment]
They are passed to the `ReadAndFilter()` function in `screendump.vim`.

**Comment by chrisbra** [comment]
ah I see.

**Pull request closed without merging**
