### PR TITLE
runtime(java): Improve the recognition of literals

### PR DESCRIPTION
**Pull request by zzzyxwvut**
* Emend the Unicode and octal escape sequence patterns;
* Accept the (repeated) underscore separators in all  
  numerical literals;
* Recognise hexadecimal floating-point literals.

(The space escape sequence `\s` will be introduced along  
with text blocks in another PR.)

References:
https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.3  
https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.10.1  
https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.10.2  
https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.10.7

### CODE REVIEW

**Comment by zzzyxwvut** [comment]
I'm sorry for breaking the screen dump generator again.

This time, I made sure to put the long lines at the end of  
the file, and, lo and behold, the missing lines (see below)  
are present, but in `java_numbers_99.dump` only.

These lines (commented out) are not at the beginning of  
`java_numbers_03.dump`:

```java
//
//      long min_hex_l = 0x8000_0000_0000_0000L;
```

And stripping all indentation has no effect, the same lines  
go missing:

```java
//
//long min_hex_l = 0x8000_0000_0000_0000L;
```

So it appears that lines over 75 of any characters cause  
this problem.

**Comment by zzzyxwvut** [comment]
The `HexSignificand` part is botched for hexadecimal floating-  
point literals of `javaNumber`, it flouts this rule:

> In a hexadecimal or binary literal, the integer is only
> denoted by the digits after the 0x or 0b characters and
> before any type suffix. Therefore, underscores may not
> appear immediately after 0x or 0b, or after the last digit
> in the numeral.


by recognising e.g., `-0x_0.0p0`.

I'll add more tests, correct it, and push the branch later  
today.

**Comment by chrisbra** [comment]
thanks!

**Comment by zzzyxwvut** [comment]
@chrisbra, regarding discontinuity, I may have found a fix.

Please look at [this branch](https://github.com/zzzyxwvut/vimvim/tree/runtime/syntax/dumps/wip).

**Pull request merged**
