### PR TITLE
runtime(octave): add basic syntax and indent support

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by chrisbra** [comment]
yes sure, please go ahead

**Comment by Freed-Wu** [comment]
> an unpublished version with significant improvements

I think a significant improvement deserve holding off. @McSinyx

**Comment by McSinyx** [comment]
To give it some context, I believe these are taken from https://github.com/gnu-octave/vim-octave and the syntax file should be identical to Rik's octave.vim 4.2.0.  Rik has published some recent [updates for up to Octave 8.1](https://www.vim.org/scripts/script.php?script_id=3600).

Regarding the indent file, it was a quick hack based on that for Lua.  I (listed as maintainer in the file) haven't used Octave in years and cannot attest for the quality of these indentation rules.  On the other hand, Rik's published an [indent file](https://www.vim.org/scripts/script.php?script_id=6056) accompanying the syntax highlighting for Octave 8.1.

> I was talking to Rik about having the syntax file included some time ago [...] If I remember correctly he also had an unpublished version with significant improvements.

Both of Rik's scripts linked above were published on 2023-03-28, so maybe these significant improvements were actually published there.

**Comment by Freed-Wu** [comment]
> On the other hand, Rik's published an indent file accompanying the syntax highlighting for Octave 8.1.

> Rik has published some recent updates for up to Octave 8.1.

Let us wait Rik :+1:

**Comment by Freed-Wu** [comment]
I think close it and wait a PR from the original author will be better :smile:

**Pull request closed without merging**
