### PR TITLE
[ci - updates] lua 5.4 and Python 3.10 for Windows CI

### PR DESCRIPTION
**Pull request by pheiduck**
- lua 5.4 for Windows CI
- Python 3.10 for Windows CI

### CODE REVIEW

**Comment by brammool** [comment]
@ichizok  what do you think?

**Comment by ichizok** [comment]
I think we can use python 3.10 rather than 3.9, why python 3.9?

**Comment by pheiduck** [comment]
> I think we can use python 3.10 rather than 3.9, why python 3.9?

I was not sure if I can bring it to the version. But vim also runs with Python 3.10

**Comment by brammool** [comment]
Tests fail on Windows.

**Comment by pheiduck** [comment]
is something from the upstream patches which triggers this since patch 8.2.4344: https://github.com/pheiduck/vim/actions/runs/1830638694

**Comment by brammool** [comment]
That should be fixed now, please trigger CI again.

**Comment by brammool** [comment]
I do not think the timeout needs to be increased.  Somehow the FileChangedShell was hanging.  It's not clear why.

**Comment by ichizok** [comment]
`Test_FileChangedShell_edit_dialog()` uses `feedkeys('L', 'L')` (lowlevel input) to input to dialog, but on windows `feedkeys(.., 'L')` seems to have no effect.

**Comment by pheiduck** [comment]
@brammool added the last commit only to trigger the CI again.

**Comment by brammool** [comment]
Ah yes, lowlevel feedkeys() does not work on Windows.

**Pull request closed without merging**
