### PR TITLE
Removes duplicate helps for CmdlineChanged, CmdlineEnter and CmdlineLeave

### PR DESCRIPTION
**Pull request by phongnh**
Please check this PR, thanks.

### CODE REVIEW

**Comment by vim-ml** [comment]
On 2018-03-16, Phong Nguyen wrote:
> Please check this PR, thanks.
> 
> -------------------------------------------------------------------------------
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/2720
> 
> Commit Summary
> 
>   • Removes duplicate helps for CmdlineChanged, CmdlineEnter and CmdlineLeave
> 
> File Changes
> 
>   • M runtime/doc/autocmd.txt (4)
> 
> Patch Links:
> 
>   • https://github.com/vim/vim/pull/2720.patch
>   • https://github.com/vim/vim/pull/2720.diff

Those line were recently added because they were missing from that
section of autocmd.txt.  Are you saying they were added to that
section twice?

Regards,
Gary

**Comment by phongnh** [comment]
Yes. They were added twice as you can see from diff view or the following screenshot.

screen shot 2018-03-16 at 10 19 05 pm

**Comment by brammool** [comment]
> Yes. They were added twice as you can see from diff view or the
> following screenshot.
> 
> screen shot 2018-03-16 at 10 19 05 pm

The problem only exists in the git repository.  Will be fixed by the
next runtime update.

-- 
How To Keep A Healthy Level Of Insanity:
1. At lunch time, sit in your parked car with sunglasses on and point
   a hair dryer at passing cars. See if they slow down.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Fixed a while ago.

**Pull request closed without merging**
