### PR TITLE
Add `:filter` support for various commands

### PR DESCRIPTION
**Pull request by coot**
This PR adds support for `:filter /pat` for: `:command`, `:highlight`, `:jumps`, `:let`, `:llist`, `:clist` and `:set`.   Note that I merged #1757 into it, so it should be applied after it.

The PR includes tests and documentation.

### CODE REVIEW

**Comment by brammool** [comment]
Marcin Szamotulski wrote:

> This PR adds support for `:filter /pat` for: `:command`, `:highlight`,
> `:jumps`, `:let`, `:llist`, `:clist` and `:set`.   Note that I merged
> #1757 into it, so it should be applied after it.

This also includes the change to add "module" to quickfix.  That is
unrelated, right?


-- 
BEDEVERE: Wait.  Wait ... tell me, what also floats on water?
ALL:      Bread?  No, no, no.  Apples .... gravy ... very small rocks ...
ARTHUR:   A duck.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by coot** [comment]
Yes, I merged the `module` part, and added support for filtering file names or module names in `:filter /pat/ clist`.

**Comment by brammool** [comment]
Marcin Szamotulski wrote:

> Yes, I merged the `module` part, and added support for filtering file
> names or module names in `:filter /pat/ clist`.

Can we split this in two patches?

-- 
Never under any circumstances take a sleeping pill
and a laxative on the same night.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by coot** [comment]
Sure, I'll rewrite the history in this PR and I'll close the other one.

**Comment by k-takata** [comment]
Why are you going to close the other one?
Unrelated changes should be different PRs.

**Comment by coot** [comment]
`filter` is build on top of the other one.  I actually closed both and made
a new PR in #2327.

**Pull request closed without merging**
