### PR TITLE
use ubuntu-latest

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by jamessan** [comment]
Blindly using the `*-latest` images isn't a good idea.  That means there's a risk for breakage whenever GitHub updates it, when CI is supposed to be stable to detect whether the newly introduced changes in the PR are causing problems.

**Comment by chrisbra** [comment]
as mentioned elsewhere, please explain the reasoning for that change

**Comment by pheiduck** [comment]
For Maintaining the CI Core System its easier to keep ubuntu updated, (if ubuntu ship a new LTS Version) the ***-latest** isn't forced to the new version, o I think its save to use.

**Comment by jamessan** [comment]
> For Maintaining the CI Core System

Not sure what you're referring to here, however I do know that switching to latest right now would cause a significant amount of the CI to fail. Having that arbitrarily happen when GitHub decides to change what latest points to isn't the basis for a stable CI.

**Comment by pheiduck** [comment]
Agree so it’s better to use version tags

**Pull request closed without merging**
