### PR TITLE
Fix cmdwin bug

### PR DESCRIPTION
**Pull request by mattn**
Repro step:
```
$ vim --clean -S example.vim
```

example.vim
```
sp
call feedkeys("q::call win_gotoid(1000)\<CR>\<CR>")
```

Sometimes, `E315: ml_get: invalid lnum: 1` occur. Sometimes, vim crash. This bug is caused that vim does not restore original cmdwin to close.

### CODE REVIEW

**Comment by mattn** [comment]
Sorry, I can't write test always crash or error occured. But I think that we should add something to make sure.

**Comment by brammool** [comment]
It appears to fail in the next function after Test_cmdwin_bug().
What is the sleep for?  Can we remove it?

**Comment by mattn** [comment]
>What is the sleep for? Can we remove it?

Yes, It is enough that we can check  no crashes.

**Comment by brammool** [comment]
I think the fix should be to disallow win_gotoid() when in the command line window.
The test does not fail with an error.

**Comment by brammool** [comment]
OK, test with feedkeys() and "x!" argument works

**Comment by mattn** [comment]
I think that vim should allow to switch window since the command run from cmdwin should work as same as command line. For example:

```
:call DoSomething()
q:k<cr>
```
This should work successfully twice. DoSomething might use win_gotoid().

**Pull request closed without merging**
