### PR TITLE
Upgrade to python 3.11 in AppVeyor MSVC 2015 build

### PR DESCRIPTION
**Pull request by zewpo**
Prob:  The appveyor msvc 2015 image comes with older python 3.8 preinstalled.
Sln:  Add python 3.11 installation step

### CODE REVIEW

**Comment by brammool** [comment]
> Prob:  The appveyor msvc 2015 build can be faster.
> Sln:  Use the VIMDLL option to compile both gVim and Vim in a single pass.
> Result:  This saves ~62 seconds off the build process.

Although the faster build is nice, we do want to test building the GUI
and console versions.  Ideally we build all three.  This is to check
that the conditions are OK.  I guess the separate console and GUI
versions are what is used most often.

> Prob:  The appveyor msvc 2015 image comes with older python 3.8 preinstalled.
> Sln:  Add python 3.11 installation step
> Result:  This adds ~6 seconds to the build process.

I don't care too much, but I assume building with the latest Python is
the best for AppVeyor.  Theoretically we could make a change that breaks
older Python versions, but it's unlikely.

-- 
hundred-and-one symptoms of being an internet addict:
7. You finally do take that vacation, but only after buying a USB modem
   and a laptop.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zewpo** [comment]
Thanks for the feedback @brammool 

OK, I've removed the DLL console change out this PR, so it's now focussed only on upgrading AppVeyor msvc 2015 to use python 3.11.

W.R.T. to the DLL console build.   Is it not sufficient that the GHA matrix already systematically test the scenarios with/without DLL, gVm/vim, msvc/mingw etc?   I thought the only reasons for keeping AppVeyor in the mix, was for speed and testing old VS 2015.

**Comment by brammool** [comment]
> Thanks for the feedback @brammool 
> 
> OK, I've removed the DLL console change out this PR, so it's now
> focussed only on upgrading AppVeyor msvc 2015 to use python 3.11.
> 
> W.R.T. to the DLL console build.   Is it not sufficient that the GHA
> matrix already systematically test the scenarios with/without DLL,
> gVm/vim, msvc/mingw etc?   I thought the only reasons for keeping
> AppVeyor in the mix, was for speed and testing old VS 2015.

It's good that all three configurations are tested somewhere.

Either system may be down or failing for some time, it's good to have a
backup.

-- 
hundred-and-one symptoms of being an internet addict:
13. You refer to going to the bathroom as downloading.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
It looks that python is not working: https://ci.appveyor.com/project/chrisbra/vim/builds/45942497#L17265
```
	test_python2.vim: python feature missing
	test_python3.vim: python3 feature missing
	test_pyx2.vim: python feature missing
	test_pyx3.vim: python3 feature missing
```

**Comment by zewpo** [comment]
ouch, I will investigate.

**Comment by zewpo** [comment]
@k-takata  good news (I think) is that it's not new - not caused by patch 9.0.1200.     

Looking back further in the appveyor logs, I can still see the same earlier this month.  

Looking at the .appveryor.bat script file, it doesn't look like it ever built the console with python.  Only the gui has python.   I checked a sample of the git log history of the appveyor.bat file - going back to about 2016 - and it never did python for console.

So, is it something we want to start making it do?

**Comment by k-takata** [comment]
Oh, I pointed the wrong lines.
The GUI version is compiled with +python3/dyn but it is not working:
https://ci.appveyor.com/project/chrisbra/vim/builds/45942497?fullLog=true#L4477
```
From test_python3.vim:
    Skipped
NO tests executed
SKIPPED test_python3.vim: python3 feature missing
```

I don't think we need to enable python3 on the console version.

**Comment by k-takata** [comment]
Perhaps, the PATH setting is missing?

**Comment by zewpo** [comment]
Ahh, sorry, OK, maybe I missed new py3 PATH for the GUI test.  I will look again :)

**Comment by zewpo** [comment]
yeah, I made a silly mistake.  typo in the path.   new PR coming real soon !

**Comment by zewpo** [comment]
Thanks @k-takata  for spotting the issue.   

I rushed a bit after @brammool earlier feedback about the DLL. I quickly split it out but left a typo in the yaml file.   

PR https://github.com/vim/vim/pull/11828 is now up to fix this.  It refactors it by moving the cmd script segments out of the yml file, into the bat file, and re-using variables properly instead of hardcoded path names.   hopefully it will help avoid the mistake from happening again.

**Comment by brammool** [comment]
> @k-takata  good news (I think) is that it's not new - not caused by patch 9.0.1200.     
> 
> Looking back further in the appveyor logs, I can still see the same earlier this month.  
> 
> Looking at the .appveryor.bat script file, it doesn't look like it ever built the console with python.  Only the gui has python.   I checked a sample of the git log history of the appveyor.bat file - going back to about 2016 - and it never did python for console.
> 
> So, is it something we want to start making it do?

I don't think there is a connection between GUI/console and Python.  If
Python is tested in one of the two builds that should be sufficient.

The only relevant #ifdef I see is in if_py_both.h, for the GUI
need_mouse_correct is set.

-- 
hundred-and-one symptoms of being an internet addict:
24. You realize there is not a sound in the house and you have no idea where
    your children are.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
