### PR TITLE
remove conditions that are always true or false

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by brammool** [comment]
Thanks.  The one in quickfix.c I'm not so sure about, I'll leave it out.

**Comment by vim-ml** [comment]
Hi,

On Tue, Mar 22, 2022 at 1:37 PM Bram Moolenaar ***@***.***>
wrote:

> Thanks. The one in quickfix.c I'm not so sure about, I'll leave it out.
>
>
> The check for a valid qi->qf_curlist in quickfix.c is needed as the
quickfix list can be
modified when opening the buffer by an autocmd. So this change cannot be
applied.

Regards,
Yegappan

**Comment by dundargoc** [comment]
@yegappan I've stared at the quickfix code for 10 minutes and I don't get it. `qi` doesn't seem to be used in the function (except for comparisons), how can it change? Mind giving me a quick hint?

**Comment by vim-ml** [comment]
Hi,

On Wed, Mar 23, 2022 at 3:51 AM dundargoc ***@***.***> wrote:

> @yegappan <https://github.com/yegappan> I've stared at the quickfix code
> for 10 minutes and I don't get it. qi doesn't seem to be used in the
> function (except for comparisons), how can it change? Mind giving me a
> quick hint?
>
>
>
The quickfix list can be changed from an autocmd. For example, the
following commands
will make the condition in that if statement false:

:cexpr ""
:autocmd BufEnter *.c colder
:vimgrep buf_T *.c

For other conditions in that if statement, you can replace 'colder' with
'call setqflist([], 'f')'
and 'call setqflist([], 'r').

Regards,
Yegappan

**Comment by dundargoc** [comment]
Dear lord, how do you even keep track of that?  O_O

Anyway, I understand now. Thanks for the help.

**Comment by vim-ml** [comment]
Hi,

On Wed, Mar 23, 2022 at 11:53 AM dundargoc ***@***.***>
wrote:

> Dear lord, how do you even keep track of that? O_O
>
>
Over a period of time, based on the bug reports (fuzzy tests) and the new
tests, several
mechanisms were added to detect these race conditions.

1. Use is_qf_entry_present() to make sure the current entry is still
present in
    the quickfix list.
2. Use qf_changedtick to detect that the entries are not modified in the
quickfix list.
3. Use the quickfix list identifier to make sure the list is still present
and is present
    at the correct index in the stack.
4. Use quickfix_busy to postpone the removal of location lists.
5. Use the qf_delq to queue all the location list delete requests and
process them
     when it is safer.

Regards,
Yegappan


> Anyway, I understand now. Thanks for the help.
>
>
>

**Pull request closed without merging**
