### PR TITLE
ArgList: Added argdedupe command to remove duplicate arguments

### PR DESCRIPTION
**Pull request by nir9**
Fixing the issue #6210
Added ":argdedupe" command that cleans the args from any duplicates.

### CODE REVIEW

**Comment by nir9** [comment]
This PR adds the ability to ignore duplicate files added with argadd and argedit, if a user attempts to argedit a file that already exists in the args it will not be added to the args and the user will move to the already existing entry. I fixed the tests accordingly.

**Comment by brammool** [comment]
Problem is that this is not backwards compatible. Some users (and plugins) may depend on the current behavior.
I'm not sure what would be the best way forward:
- Add a ++dedupe option
- Keep the commands as-is and add an :argdedupe command to clean it  afterwards
- Add new commands that have the dedupe behavior

I tend to think that adding :argdedupe might be the best, so you can do ":argedit file | argdedupe"
Or just type :argdedupe once you find out it's desired.

**Comment by nir9** [comment]
@brammool Added the argdedupe according to your suggestion, also added a test for the new command

**Comment by brammool** [comment]
Did you close it just because it was old?  There was a note in the todo list, but it has gone down a bit because new things got added.

**Comment by nir9** [comment]
Oh this is actually by mistake I forgot about this and rebased my forks master branch (I am now working on a different fix) dropping these commits XD so I guess the GitHub automatically closed this pull request

I will soon try to restore the commits (looks like they still exist on GitHub) and put them on a different branch and reopen this pull request so they don't get lost.

**Comment by nir9** [comment]
Hi, I have re-added the original commits, though I have removed the changes I did to the tags and cmdidxs since you can anyway just compile them again easily so no need for them to be included in the changes (they can be compiled once you decide to add this to vim)

**Comment by brammool** [comment]
Please do include the changes to cmdidxs, so that CI can run and test the change.

**Comment by nir9** [comment]
@brammool Added the generated cmdidxs :)

**Pull request closed without merging**
