### PR TITLE
Filter oldfiles

### PR DESCRIPTION
**Pull request by coot**
This pull request adds an argument to `oldfiles` which is a file pattern.  It lets filter the output of `oldfiles` which usually is lengthy and not easily readable.

### CODE REVIEW

**Comment by brammool** [comment]
If the pattern contains special characters, such as |, then this won't work.
The argument must be used like with :grep, use // to enclose the pattern.
Also, we need a test to check that it's working.

**Comment by justinmk** [comment]
You can already do this with:

```
echo filter(copy(v:oldfiles), 'v:val =~ "foo"')
```

I wish that people focused on exposing general mechanisms in Vim instead of adding special cases to random features like this. `v:oldfiles` is exposed. If `filter(copy(v:oldfiles), 'v:val =~ "foo"')` is not convenient enough, then perhaps better list-processing facilities should be designed.

**Comment by vim-ml** [comment]
On Tuesday, September 29, 2015 at 4:18:00 PM UTC-5, Justin M. Keyes wrote:

> You can already do this with:
> 
> echo filter(copy(v:oldfiles), 'v:val =~ "foo"')
> 
> I wish that people focused on exposing general mechanisms in Vim instead of adding petty special cases to random features like this. v:oldfiles is exposed. If filter(copy(v:oldfiles), 'v:val =~ "foo"') is not convenient enough, then perhaps better list-processing facilities should be designed.

The :oldfiles command isn't just for _viewing_ the v:oldfiles list.

It also gives a number for each list entry, that lets you do things like :e #<12 to edit the 12th file in the list or :args #<2 #<4 #<6 to edit the 2nd, 4th, and 6th file.

Your method would not allow that simple use case. This makes :oldfiles a more functional "most recent files" feature, and I support its inclusion.

Note however that I'll still probably stick with the MRU plugin because the user interface is quite a bit friendlier and it is more easily configurable. But I don't _need_ the plugin necessarily with this feature addition.

**Comment by coot** [comment]
Actually if I open a file `/tmp/a|b` the `v:oldfiles` list only contains a file `/tmp/a`.  @brammool the intention was to have an interface like the `:buffer` command has rather than `:vimgrep`.

**Pull request closed without merging**
