### PR TITLE
translation(ru): The main file README.txt and uganda.txt

### PR DESCRIPTION
**Pull request by RestorerZ**
Added "README.rux.txt" and "uganda.rux" files to be able to include them in the
Vim installer.

### CODE REVIEW

**Comment by RestorerZ** [comment]
The error is due to the "tags-ru" file:
https://github.com/vim/vim/blob/63833bb0217fbfd5556a77103bd6c1ce78cfd996/src/testdir/test_taglist.vim#L103

**Comment by chrisbra** [comment]
thanks!

**Comment by zzzyxwvut** [comment]
Shouldn't a generated `tags-ru` and copied over to the  
installation directory `share/vim/vimXY/doc/` be explicitly  
ignored?

```diff
diff --git a/.gitignore b/.gitignore
index 52444475e..241e96eaf 100644
--- a/.gitignore
+++ b/.gitignore
@@ -96,6 +96,7 @@ src/kword_test
 
 # Generated by "make install"
 runtime/doc/doctags
+runtime/doc/tags-*
 
 # Temporarily generated by "runtime/syntax/generator/make"
 runtime/syntax/generator/generator.err
```

It comes out of the blue with `make install` after `v9.1.0217`.  
Try `git status`.

**Comment by RestorerZ** [comment]
@zzzyxwvut , I'm sorry that I didn't have time to answer you right away.
Now, as I understand it, this problem has been solved thanks to a PR from @Shane-XB-Qian

**Comment by zzzyxwvut** [comment]
No problem.  There is always a chance to overlook something  
with complex multi-stage builds when no previous example can  
be consulted about what files to touch.

**Comment by Shane-XB-Qian** [comment]
enjoy~ :smile: actually i didnot know that comment from @zzzyxwvut existed, but looked into Makefile, and was hesitated to check...

**Comment by Shane-XB-Qian** [comment]
enjoy~ :smile: actually i didnot know that comment from @zzzyxwvut existed, but looked into Makefile, and was hesitated to check...

**Comment by julio-b** [comment]
> The error is due to the "tags-ru" file:
> 
> https://github.com/vim/vim/blob/63833bb0217fbfd5556a77103bd6c1ce78cfd996/src/testdir/test_taglist.vim#L103
> 
> I deleted this "tags-ru" file.

Hi, i think this test still fails for some reason.
```
From test_taglist.vim:
Executed Test_tagfiles()                           in   0.007742 seconds
Filtered 12 tests with $TEST_FILTER and $TEST_SKIP_PAT
Executed 1 test                          in   0.016981 seconds
1 FAILED:
Found errors in Test_tagfiles():
command line..script /home/j/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_tagfiles line 11: Expected 1 but got 2
```

**Pull request merged**
