### PR TITLE
In builtin overview specify {buf} as param for appendbufline.

### PR DESCRIPTION
**Pull request by errael**
Get the overview and Detail to match. `{buf}` is used every where for this

### CODE REVIEW

**Comment by zeertzjq** [comment]
This change seems needed for `setbufline()` as well.

**Comment by zeertzjq** [comment]
Also, the "Last change" date at the top of the file should be updated.

**Comment by errael** [comment]
> This change seems needed for `setbufline()` as well.

Thanks

**Comment by chrisbra** [comment]
thanks

**Comment by errael** [comment]
@chrisbra What are you doing here? **Go play and enjoy**.

**Pull request merged**
