### PR TITLE
Remove `*.tmpl` filetype

### PR DESCRIPTION
**Pull request by 178inaba**
`*.tmpl` is a generic extension for template files, so delete the settings.

Example: vim-go
https://github.com/fatih/vim-go/blob/8c32f9f205a72b1b71d0ec61fb25a325392cb4b5/ftdetect/gofiletype.vim#L10

### CODE REVIEW

**Comment by chrisbra** [comment]
there are a couple of more htmlcheetah mentions. You might want to contact the (syntax) script maintainer, if that syntax is still used or if we can remove the syntax files as well (since they are from 2003).

**Comment by 178inaba** [comment]
@imax Nice to meet you!
I submitted a pull request to delete the filetype associated with the extension `*.tmpl`.
Currently, we are considering removing htmlcheetah syntax script.
Are you currently using htmlcheetah?

**Comment by imax** [comment]
Sorry, I no longer follow Vim development. Please do as you see fit.

**Comment by 178inaba** [comment]
@imax Thank you for your reply!

**Comment by brammool** [comment]
Why not keep the syntax file?  It's not getting in the way, is it?
Is there some other filetype we can associate *.tmpl with?
A quick search suggests "Xfire User Interface Template" which looks like HTML.

**Comment by brammool** [comment]
Oh, and golang .tmpl files are also html, so we could easily make syntax and indent files for "tmpl" that redirect to the html ones.

**Comment by 178inaba** [comment]
@brammool Sorry.
As for htmlcheetah, I searched on the web and found only old information, and I thought that it is syntax that is no longer used.
I will undo the deletion of the syntax, as the syntax is not in the way.

**Comment by 178inaba** [comment]
@brammool I think that `*.tmpl` is used as source code of various HTML template engines.
Searching GitHub with `index.tmpl` will tell you that.
https://github.com/search?q=filename%3Aindex.tmpl
So vim proposes to leave it to the user's configuration without associating `*.tmpl`.

**Pull request closed without merging**
