### PR TITLE
Fix match finding halting the whole program (issue #8671)

### PR DESCRIPTION
**Pull request by SilverGozas**
Match finding algorithm used to halt while looking for matches
in the current buffer if you typed too fast after opening the
auto-complete menu because of the match finder only stopping
after it found the first match again, which never happened again
which resulted in soft halt. Now match finder has an additional
stop condition after it loops around the buffer more than once
which ensures that all matches are found, but buffer is not
parsed infinitely.

### CODE REVIEW

**Comment by AndyGozas** [comment]
Important notice: while this patch was first created by me for neovim, it was not yet fully reviewed and was neither denied nor acceped by the official neovim repository, because they will be porting patches from VIM anyway and don't want to have duplicate solutions for the same problem.

**Comment by brammool** [comment]
In this condition:
```vim
	else if (prev_pos.lnum >= last_match_pos.lnum
		|| (prev_pos.lnum == last_match_pos.lnum
		    && prev_pos.col >= last_match_pos.col)) {
```
The first ">=" should be ">".  Otherwise the second part would never be used.

Would it be possible to add a test for this?

**Comment by AndyGozas** [comment]
> In this condition:
> 
> ```viml
> 	else if (prev_pos.lnum >= last_match_pos.lnum
> 		|| (prev_pos.lnum == last_match_pos.lnum
> 		    && prev_pos.col >= last_match_pos.col)) {
> ```
> 
> The first ">=" should be ">". Otherwise the second part would never be used.
> 
> Would it be possible to add a test for this?

So sorry, that was quite dumb of me. About the test -- if you mean a test for the whole issue, then I only know of a way to test the fix manually, which is described in this issue: https://github.com/vim/vim/issues/8671, but sadly I have not yet come up with a way to test this automatically. I will sure think about how to do that, but I can not guarantee that I will eventually come up with one.

**Comment by brammool** [comment]
Andy Gozas wrote:

> > In this condition:
> > 
> > ```viml
> > 	else if (prev_pos.lnum >= last_match_pos.lnum
> > 		|| (prev_pos.lnum == last_match_pos.lnum
> > 		    && prev_pos.col >= last_match_pos.col)) {
> > ```
> > 
> > The first ">=" should be ">". Otherwise the second part would never be used.
> > 
> > Would it be possible to add a test for this?
> 
> So sorry, that was quite dumb of me. About the test -- if you mean a
> test for the whole issue, then I only know of a way to test the fix
> manually, which is described in this issue:
> https://github.com/vim/vim/issues/8671, but sadly I have not yet come
> up with a way to test this automatically. I will sure think about how
> to do that, but I can not guarantee that I will eventually come up
> with one.

Ideally we have a test for every fix, so that we avoid regressions.
But I understand that this one is very timing sensitive.  One would need
to be able to force the order in which things happen, which isn't really
possible.  And the test should be predictable, otherwise it would fail
on some systems.

-- 
Facepalm reply #9: "Speed up, you can drive 80 here" "Why, the cars behind us
are also driving 60"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by AndyGozas** [comment]
The bigger issue with writing a test for this condition that I ran into is actually testing for a halt. Because to my knowledge, the current testing methods rely on vim actually completing something, but the problem is that these testing methods do not allow (as far as I know -- maybe I'm wrong) to send an actuall interrupt to the process, because sending an interrupt seems to be the only way to exit the halt (feeding <C-c> using feedkeys does not work). So I'm kind of stuck, cause I don't see any good elegant ways to test for this halt. And even if we were to find a way to test for the halt, It does not happen reliably, it might happen on the tenth symbol, or might on the twentieth, or might on the hundredth one. We can't predict when it would happen and if it would happen at all in the span. Maybe if we use a 1000 symbol long test we would be able to say that it's 99.99 whatever % accurate, but still, probably never 100% accurate.

**Comment by brammool** [comment]
> The bigger issue with writing a test for this condition that I ran
> into is actually testing for a halt. Because to my knowledge, the
> current testing methods rely on vim actually completing something, but
> the problem is that these testing methods do not allow (as far as I
> know -- maybe I'm wrong) to send an actuall interrupt to the process,
> because sending an interrupt seems to be the only way to exit the halt
> (feeding <C-c> using feedkeys does not work). So I'm kind of stuck,
> cause I don't see any good elegant ways to test for this halt. And
> even if we were to find a way to test for the halt, It does not happen
> reliably, it might happen on the tenth symbol, or might on the
> twentieth, or might on the hundredth one. We can't predict when it
> would happen and if it would happen at all in the span. Maybe if we
> use a 1000 symbol long test we would be able to say that it's 99.99
> whatever % accurate, but still, probably never 100% accurate.

Your fix removes the halt, right?  So without the fix it would hang and
fail.  That's OK (although annoying that you have to kill the test when
reproducing the problem).  But with the fix the test would not halt and
pass.


-- 
ZOOT:  I'm afraid our life must seem very dull and quiet compared to yours.
       We are but eightscore young blondes, all between sixteen and
       nineteen-and-a-half, cut off in this castle, with no one to protect us.
       Oooh.  It is a lonely life ... bathing ...  dressing ... undressing ...
       making exciting underwear....
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by AndyGozas** [comment]
So I've made the test, but while testing, I've found out that this fix does break the backwards keyword local completion (^X^P) which I am fixing right now.

**Comment by AndyGozas** [comment]
Fixed. The code looks a lot uglier now, but it passes all tests.

**Comment by brammool** [comment]
There is an Appveyor error that needs to be fixed.

**Comment by brammool** [comment]
And that is C99 syntax, which we don't fully support.  Please fall back to C89 syntax.

**Comment by AndyGozas** [comment]
> And that is C99 syntax, which we don't fully support. Please fall back to C89 syntax.

Sorry, didn't know. This should be fixed now

**Comment by AndyGozas** [comment]
I think, taking into account the backwards search issue I've had to deal with recently, I should add a test for that too. I will do this today.

**Comment by AndyGozas** [comment]
During testing I was unable to reproduce this bug with backwards match finding. Maybe this bug just doesn't happen with backwards completion. I'm not sure why, but maybe when going backwards, the first match is considered something else other than what is right under cursor, and as we know the source of the problem is that the match right under cursor disappears and is never found again.
I've added a test for this nevertheless, and also in the code I did not remove the reserve exit condition for backwards match finding just to be extra safe in case this bug appears after some change in match finding algorithm.

**Pull request closed without merging**
