### PR TITLE
WIP: libxxd

### PR DESCRIPTION
**Pull request by johnandersen777**
Hi all,

I find myself popening xxd way too much. I have started on this branch to make
xxd a library. I assume there is going to be resistance to this so tell me how I can
make this happen and keep everyone happy.

Thanks,
John

### CODE REVIEW

**Comment by chrisbra** [comment]
No resistance from my side, but what problem are you trying to solve? Or what is the reason to libify xxd?

**Comment by johnandersen777** [comment]
@chrisbra Sweet! I just constantly find myself wanting to do this:

```c
#include <xxd.h>

int main(int argc, char **argv) {
  char msg[] = "This \0 is the message \0 asdfjalsdkfj";
  xxd_stdout(msg, sizeof(msg) / sizeof(*msg));
}
```

But instead I have to do this:

```c
#include <stdio.h>

int main(int argc, char **argv) {
  char msg[] = "This \0 is the message \0 asdfjalsdkfj";
  FILE *xxd = popen("xxd", "w");
  fwrite(msg, 1, sizeof(msg) / sizeof(*msg), xxd);
  pclose(xxd);
}
```

One motivation is to have code that looks less hackish (popen). The biggest reason is to have C code which doesn't need to set up sockets or pipes or something to talk to the child (xxd) to send input and receive output if I want the dump as a string.

**Comment by johnandersen777** [comment]
fuuuuuuuck i forgot i'd have to mess with the makefiles :upside_down_face:

**Comment by johnandersen777** [comment]
Ok I found the best reason why the popen way is not good enough.

notdope

Those `---------` bars should be right around the dump!

**Comment by brammool** [comment]
Christian Brabandt wrote:

> No resistance from my side, but what problem are you trying to solve?
> Or what is the reason to libify xxd? 

Right.  There are many tools like this, to manipulate text and function
in a pipe.

Also, how does it help to make it a library?

-- 
OLD WOMAN: Well, how did you become king, then?
ARTHUR: The Lady of the Lake, her arm clad in the purest shimmering samite,
        held Excalibur aloft from the bosom of the water to signify by Divine
        Providence ...  that I, Arthur, was to carry Excalibur ...  That is
        why I am your king!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
