### PR TITLE
Update src/INSTALLmac.txt

### LINKED ISSUE #8084: macOS: make test: glibtool not found
`src/INSTALLmac.txt` says to run `make test`, but when I did, I got the error `glibtool: command not found`.

**Steps to Reproduce**

```sh
curl -LJO https://github.com/vim/vim/archive/refs/tags/v8.2.2730.tar.gz
gunzip vim-8.2.2730.tar.gz
tar -x -f vim-8.2.2730.tar
cd vim-8.2.2730/src
make
make test
```

**Environment**

- macOS 11.2 (20D64)
- Xcode 12.4 (12D4e)

### PR DESCRIPTION
**Pull request by ma11hew28**
This fixes #8084.

### CODE REVIEW

**Comment by brammool** [comment]
I don't like the way this goes.  It removes some useful remarks, such as the "make --version" part, and adds remarks about MacVim and Homebrew which are not relevant here and missing URLs.

**Comment by ma11hew28** [comment]
OK. I could try again.

**Comment by ma11hew28** [comment]
My last commit fixes #2444.

**Comment by brammool** [comment]
> My last commit fixes #2444.

I'm wondering about the "arch" choice.  I assume "ppc" no longer works.
In some Q/A I found hints that the current choices are "x86_64 arm64".
Perhaps "intel" works too.  Can you try that out?


-- 
You are only young once, but you can stay immature indefinitely.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ma11hew28** [comment]
In my last commit:

- I added instructions on how to install `glibtool` on macOS.
- I updated `READMEdir/README_mac.txt`. I hadn't noticed that file before, but I found it while searching all files for "Macintosh". (I did that search because I was thinking probably all occurrences of "Macintosh" (case-insensitive) should be renamed to "Mac" and all occurrences of "Mac OS X" (and the like) should be renamed to "macOS", but I guess that's a separate issue and also a minor one.)
- I left the line `#CONF_OPT_DARWIN = --with-mac-arch=intel` in `src/Makefile` how it is (instead of changing `intel` back to `i386`) because:
  - The output of running `./configure --help` from `src` lists (to the right of "`--with-mac-arch=ARCH`") "`current`, `intel`, `ppc` or `both`". (`i386` isn't included.)

  - I tried out different values. Ie, I tried `make` with the appropriate line commented out in (or added to) the Makefile. And when I tried `intel`, `ppc`, or `both`, I got this error:

    ```
    checking --with-tlib argument... empty: automatic terminal library selection
    checking for tgetent in -ltinfo... no
    checking for tgetent in -lncurses... no
    checking for tgetent in -ltermlib... no
    checking for tgetent in -ltermcap... no
    checking for tgetent in -lcurses... no
    no terminal library found
    checking for tgetent()... configure: error: NOT FOUND!
          You need to install a terminal library; for example ncurses.
          Or specify the name of the library with --with-tlib.
    make[1]: *** [config] Error 1
    make: *** [reconfig] Error 2
    ```

    When I tried `intel`, the first error logged to `src/auto/config.log` was:

    ```
    configure:4767: checking for sys/types.h
    configure:4767: gcc -c -Oz   -Wall -Wno-deprecated-declarations  -DMACOS_X -arch intel -DMACOS_X_DARWIN conftest.c >&5
    clang: error: invalid arch name '-arch intel'
    configure:4767: $? = 1
    ```

    When I tried `ppc`, the first error logged to `src/auto/config.log` was:

    ```
    configure:4767: checking for sys/types.h
    configure:4767: gcc -c -O2   -Wall -Wno-deprecated-declarations  -DMACOS_X -arch ppc -DMACOS_X_DARWIN conftest.c >&5
    In file included from conftest.c:14:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:68:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:828:2: error: Unsupported architecture
    #error Unsupported architecture
    ```

    When I tried `both`, the first error logged to `src/auto/config.log` was:

    ```
    configure:4697: gcc -o conftest -O2   -Wall -Wno-deprecated-declarations -isysroot /Applications/Xcode.app/Contents/Developer/SDKs/MacOSX10.4u.sdk -arch i386 -arch ppc  -DMACOS_X  conftest.c  >&5
    clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/SDKs/MacOSX10.4u.sdk' [-Wmissing-sysroot]
    clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/SDKs/MacOSX10.4u.sdk' [-Wmissing-sysroot]
    ld: warning: Csu support file -lcrt1.o not found, changing to target macOS 10.8 where it is not needed
    ld: library not found for -lSystem
    error: unable to create target: 'No available targets are compatible with triple "powerpc-apple-macosx10.4.0"'
    1 error generated.
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    configure:4697: $? = 1
    ```

    When I tried other values (besides `intel`, `ppc`, or `both`) such as `current`, `i386`, `x86_64`, and `arm64`, `make` returned a successful exit status. (And, of course, `make` worked when I left `--with-mac-arch` commented out, which is how I compiled the version of Vim that I'm currently running.) Even after I ran `make` with `--with-mac-arch` set to `arm64`, I ran `lipo -archs vim` (according to [Building a Universal macOS Binary | Apple Developer Documentation][1]) and got as output `x86_64` (not `arm64`).

    I performed all trials (above) on my MacBook Air (13-inch, Early 2014) running macOS 11.2 (20D64) and Xcode 12.4 (12D4e).

  - I searched in `src/configure.ac` for `MACARCH" =` and saw that `--with-mac-arch` is only checked against each these values: `intel`, `ppc`, and `both`. Otherwise, I don't think it matters what `--with-mac-arch` is set to, or if it's set at all.


  [1]: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by ma11hew28** [comment]
Any update on this?

I thought of another reason I left the line `#CONF_OPT_DARWIN = --with-mac-arch=intel` in `src/Makefile` how it is (instead of changing `intel` back to `i386`):

- I think it's a better user experience for `make` with `CONF_OPT_DARWIN = --with-mac-arch=intel` to fail than it is for `make` with `CONF_OPT_DARWIN = --with-mac-arch=i386` to "succeed" (ie, fail silently). For example, if a user from their Apple silicon Mac wants to build an Intel binary, it'd be better for them to run `make` with `CONF_OPT_DARWIN = --with-mac-arch=intel` and see it fail than to run `make` with `CONF_OPT_DARWIN = --with-mac-arch=i386` and see it succeed (when it actually failed to build an Intel binary and instead built an Apple silicon binary, since `configure` interprets `i386` to mean `current`).

I think the set of valid values for `--with-mac-arch` should be limited. Ie, if `--with-mac-arch` is set to an unrecognized value, then `configure` should fail.

**Comment by brammool** [comment]
I have included this and moved things around a bit.  Please check after the next runtime file update.

**Comment by ma11hew28** [comment]
OK, great. Thanks, @brammool. Will do.

**Pull request closed without merging**
