### PR TITLE
Idlang syntax updates

### PR DESCRIPTION
**Pull request by sappjw**
Implement highlighting fixes for a couple IDL statements and routines

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks. Did you try to contact the upstream maintainer?

**Comment by sappjw** [comment]
No, there was nobody listed in [MAINTAINERS](.github/maintainers) for `runtime/syntax/idlang` and I didn't email the maintainer in the file.

**Comment by chrisbra** [comment]
then please do.

**Comment by sappjw** [comment]
It looks like he hasn't committed to this repository ever. Is he actually maintaining it any more?

**Comment by chrisbra** [comment]
That's one of the reasons to try to contact him. To know, whether the maintainer is still actively maintaining the file and he is okay with the proposed change. If the maintainer does not react or is unreachable, we can still consider to merge it here. But first one should always try to get an ACK from the maintainer.

**Comment by chrisbra** [comment]
let me include it now.

**Pull request closed without merging**
