### PR TITLE
update kivy syntax file

### PR DESCRIPTION
**Pull request by tshirtman**
- differenciates between root and normal rules
- correctly highlight python after ":", both on same line or next block,
  including blocks with empty lines in them (as long as indentation
  doesn't change)
- differente context/colors for canvas instructions, and their
  properties, with the value also highlighted as python
- fixes comments not including XXX/TODO/FIXME/NOTE when on their own line
- special treatment for id property
- magically fixes some parsing errors that would break next line after a
  comment, a number with a dot, and some bad string end detection

### CODE REVIEW

**Comment by brammool** [comment]
Did you contact Corey Prophitt ?

**Comment by tshirtman** [comment]
I did not, contributing it here was a bit of an afterthought, will try to.

**Comment by tshirtman** [comment]
He answered and is fine with me taking over, however i found some issues with it earlier today, so i'll try to fix them before merging :). Will reopen the PR then.

**Comment by chrisbra** [comment]
sounds good. Please be advised, that Bram prefers getting the runtime files sent by mail and he will then included it later in a runtime file update.

**Comment by tshirtman** [comment]
Good to know, thank you.

**Comment by brammool** [comment]
Gabriel Pettier wrote:

> He answered and is fine with me taking over, however i found some
> issues with it earlier today, so i'll try to fix them before merging
> :). Will reopen the PR then.

Thanks.  Please have the original maintainer send me a note, so it's
100% clear he is fine with you taking over.

-- 
"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
