### PR TITLE
Additional Test Case - Normal Mode Motion

### PR DESCRIPTION
**Pull request by bryphe**

### CODE REVIEW

**Comment by k-takata** [comment]
I think you intended to create a PR on onivim/libvim, but this is the fourth time you mistakenly created PR here. Please don't forget to select the target repository.

**Comment by bryphe** [comment]
Sorry about the noise, @k-takata . It's unfortunate that GitHub doesn't provide a way to set a 'default' target repository. I'll break the link for now so I don't inadvertently spam here.

**Comment by oblitum** [comment]
@bryphe, fyi, there's [`hub pull-request`](https://hub.github.com/).

**Comment by bryphe** [comment]
Thanks @oblitum ! I didn't know about that tool - looks very useful.

**Pull request closed without merging**
