### PR TITLE
Fix #1168 completion problem from #875

### LINKED ISSUE #1168: Patch 7.4.2013 breaks completion entry ordering
Patch 7.4.2013 fixes #874, but introduces a bug where the completion entries aren't shown in the order intended by the code.

Repro Steps:
1) Use the following `test.vim` file

```
" test.vim
function! TestComplete(findstart, base)
  if a:findstart
    return 0
  else
    let batch_size = 5
    " 3 batches of completion entries
    for i in range(0, 2)
      " add entries in batches
      for j in range(i * batch_size, i * batch_size + batch_size - 1)
        call complete_add(j)
      endfor
      sleep 300m " simulate delay

      if complete_check()
        break
      endif
    endfor
    return []
  endif
endfunction

set omnifunc=TestComplete
```

2) `vim -Nu test.vim`
3) Enter insert mode and invoke omnifunc via Ctrl-X Ctrl-O

Expected Result (works in 7.4.2012):
screenshot from 2016-10-14 20-29-16

Actual Result (7.4.2013):
screenshot from 2016-10-14 20-34-38

Problem still repros in 8.0.0032. If I remove the code change made by 7.4.2013 from `src/edit.c`, then 8.0.0032 works as expected.

### PR DESCRIPTION
**Pull request by Shougo**
It fixes #1168 problem.

### CODE REVIEW

**Comment by vim-ml** [comment]
You should add a test.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by Shougo** [comment]
OK.  I have added the test.
But it is very hard to simulate the completion wait.
Because the test omnifunc is asynchronous.
The test fix is wellcome.

**Comment by vim-ml** [comment]
2016-10-15(Sat) 13:58:03 UTC+9 Shougo:

> OK.  I have added the test.
> 
> But it is very hard to simulate the completion wait.
> 
> Because the test omnifunc is asynchronous.

Issue#1168 repro steps doesn't seem to asynchronous for me.
Where is the asynchronous?

> The test fix is wellcome.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by Shougo** [comment]
> Issue#1168 repro steps doesn't seem to asynchronous for me. Where is the asynchronous?

Because it uses `complete_check()` and `complete_add()`.

The problem is already fixed by Bram.
So, closing.

**Comment by vim-ml** [comment]
2016-10-18(Tue) 0:13:48 UTC+9 Shougo:

> Issue#1168 repro steps doesn't seem to asynchronous for me. Where is the asynchronous?
> 
> Because it uses complete_check() and complete_add().

(Below is Off topic)
No.
In this case, Those functions are not asynchronous because they are called from the main loop.

main loop
  ...
  Test_complete_add()
    feedkeys("i<c-x><C-o>" ...)
      TestCompleteAdd()
        complete_add()
        complete_check()

You don't understand about the asynchronous processing.

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

> The problem is already fixed by Bram.
> 
> So, closing.

**Pull request closed without merging**
