### PR TITLE
runtime: add Ubuntu Kinetic

### PR DESCRIPTION
**Pull request by xypron**
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>

### CODE REVIEW

**Comment by brammool** [comment]
Please send this to the Debian maintainers.  @jamessan

**Comment by xypron** [comment]
@brammool
>> Please send this to the Debian maintainers.
According to CONTRIBUTING.md pull requests should be created and not mails. A MAINTAINERS file with email addresses per directory or file is not provided. So it is unclear whom you refer to.

**Comment by jamessan** [comment]
@xypron You already opened a MR in Salsa, but to the wrong repo.  It should be https://salsa.debian.org/vim-team/vim-debian instead.

**Comment by xypron** [comment]
https://salsa.debian.org/vim-team/vim-debian/-/merge_requests/7

**Comment by jamessan** [comment]
Merged to vim-debian.  I'll send an update to Bram soon.

**Comment by chrisbra** [comment]
closing then.

**Pull request closed without merging**
