### PR TITLE
feat: allow remapping of man.vim \K

### PR DESCRIPTION
**Pull request by archf**
Now I can do something like:
`nmap <F1> <Plug>ManPreGetPage<CR>`

Signed-off-by: Félix Archambault <fel.archambault@gmail.com>

### CODE REVIEW

**Comment by chrisbra** [comment]
please contact the maintainer of the plugin.

**Comment by archf** [comment]
Are ftplugins maintained in a separated repo?

**Comment by chrisbra** [comment]
no, please contact the maintainer from his email address at the top of the plugin.

**Comment by goweol** [comment]
I'm man plugin maintainer.  Is this acked-by sufficient?

Acked-By: SungHyun Nam <goweol@gmail.com>

**Comment by chrisbra** [comment]
I would go with sending an updated plugin file to Bram via mail. We don't use the PR workflow from github. Thanks.

**Comment by brammool** [comment]
I'll include it and add a note to the help.

**Pull request closed without merging**
