### PR TITLE
Rename of pum hl_group is incomplete

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  Rename of pum hl_group is incomplete.
Solution: Also rename in the test.  Rename to user_hlattr in code to
          avoid confusion with pum_extra.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Waiting for #15353

**Comment by glepnir** [comment]
this name more better

**Comment by chrisbra** [comment]
thanks, can you please rebase now?

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
