### PR TITLE
turkish menu fix

### PR DESCRIPTION
**Pull request by lesorubshayan**
close https://github.com/vim/vim/pull/10724

### CODE REVIEW

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
you don't need to ping me, when creating a PR. Please don't change the maintainer. unlesss you intend to take over the file maintainership or the mentioned maintainer indicates he will do so.

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
Thanks. Please change the Commit Author.

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
closing for the reasons mentioned here https://github.com/vim/vim/pull/14703#issuecomment-2092337585

**Pull request closed without merging**
