### PR TITLE
Include Vim9 script support

### PR DESCRIPTION
**Pull request by brammool**
Still experimental, but ready to include in the base code.

### CODE REVIEW

**Comment by mattn** [comment]
This seems breaking compatibility with if_python3.

```vim
function! s:foo()
let py = 'python3'
execute py "<< EOF"
def do_something():
  return 1
EOF
endfunction
```

```
Error detected while processing C:\dev\vim9\src\fooo.vim: line    8: E126: Missing :endfunction 
```

**Comment by mattn** [comment]
```
  let echo = 10
  edit += 20
  echo edit
```
This show 20 but

```
  let echo = 10
  unlet edit
  edit += 20
```
This open new file. I wonder user possibly confuse.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> This seems breaking compatibility with if_python3.
> 
> ```vim
> function! s:foo()
> let py = 'python3'
> execute py "<< EOF"
> def do_something():
>   return 1
> EOF
> endfunction
> ```
> 
> ```
> Error detected while processing C:\dev\vim9\src\fooo.vim: line    8: E126: Missing :endfunction 
> ```

It would also have failed when Python would be using "function".
Since this is using "execute" the parser does not see the "<< EOF" that
would normally make it skip over the Python code.
I think this will just not work.

-- 
The only way the average employee can speak to an executive is by taking a
second job as a golf caddie.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
For users of vim-plug. Vim 9 break compatibility of syntax that using in vim-plug.

image

If you want to fix temporarry:

```diff
--- plug.vim.orig	2020-01-27 00:32:28 +0000
+++ plug.vim	2020-01-27 00:32:38 +0000
@@ -1428,8 +1428,7 @@
 endfunction
 
 function! s:update_python()
-let py_exe = has('python') ? 'python' : 'python3'
-execute py_exe "<< EOF"
+python3 << EOF
 import datetime
 import functools
 import os
```

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> For users of vim-plug. Vim 9 break compatibility of syntax that using
> in vim-plug.
> 
> image
> 
> If you want to fix temporarry:
> 
> ```diff
> --- plug.vim.orig	2020-01-27 00:32:28 +0000
> +++ plug.vim	2020-01-27 00:32:38 +0000
> @@ -1428,8 +1428,7 @@
>  endfunction
>  
>  function! s:update_python()
> -let py_exe = has('python') ? 'python' : 'python3'
> -execute py_exe "<< EOF"
> +python3 << EOF
>  import datetime
>  import functools
>  import os
> ```

Please check that 8.2.0150 fixes this.

-- 
Engineers will go without food and hygiene for days to solve a problem.
(Other times just because they forgot.)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
> Please check that 8.2.0150 fixes this.

I can confirm it fixes the issue.

**Comment by mattn** [comment]
> Please check that 8.2.0150 fixes this.

Confirmed the fix. Thank you.

**Comment by mattn** [comment]
I'm thiking that Vim9 script require `let` to avoid shadowing `edit` as expression not normal command.

**Comment by brammool** [comment]
> I'm thiking that Vim9 script require `let` to avoid shadowing `edit`
> as expression not normal command.

"let" is used for a declaration, using it for assignment will be very
confusing.

If your variable is called "edit", then ":e file" still works.

-- 
No engineer can take a shower without wondering if some sort of Teflon coating
would make showering unnecessary.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Was included

**Pull request closed without merging**
