### PR TITLE
feat: Add first class support for json format (Issue #11426)

### PR DESCRIPTION
**Pull request by habamax**
Use `gq` with motion to reformat `json` by adding
```
import autoload 'dist/json.vim'
setlocal formatexpr=json.FormatExpr()
```
to `.vim/ftplugin/json.vim`

Or use a command:
```
import autoload 'dist/json.vim'
command -range=% JSONFormat json.FormatRange(<line1>, <line2>)
```

https://github.com/vim/vim/issues/11426

### CODE REVIEW

**Comment by brammool** [comment]
> Use `gq` with motion to reformat `json` by adding
> ```
> setl formatexpr=dist#json#FormatExpr()
> ```
> to `after/json.vim`
> 
> Or use a command:
> ```
> import autoload 'dist/json.vim'
> command -range=% JSONFormat json.Format(<line1>, <line2>)
> ```

With the "export" mechanism that is in the patch, which is the right
choice, the suggested script should be in ~/.vim/ftplugin/json.vim, not
in "after".

I hope some people can try it out and comment on the output of this
formatter.  I would expect at least a statement of the intention, such
as to take any one-liner JSON and turn it into one key-value pair per
line. 

-- 
10 Monologs = 5 Dialogs

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by prabirshrestha** [comment]
Thanks for the quick PR but I think the api should be different.

* Shouldn't use just line number. As my json could start in a random column.
* I would expect json object as the parameter. `json_format({ 'some': 'object' })`. One can easily convert any chunk of string to json object by using existing `json_encode()` function.
* One should be able to provide custom space/tab with size indent size when formatting.

**Comment by habamax** [comment]
> Thanks for the quick PR but I think the api should be different.
> 
>     * Shouldn't use just line number. As my json could start in a random column.
> 
>     * I would expect json object as the parameter. `json_format({ 'some': 'object' })`. One can easily convert any chunk of string to json object by using existing `json_encode()` function.
> 
>     * One should be able to provide custom space/tab with size indent size when formatting.

Then I am a bit lost. I am not sure there is json object in vim. `json_encode` works with vim data structures and converts them to string representation of json.

Anyway, I can extract a function from `json.Format()` that would take a json string as parameter and return formatted json string. How to apply that function then would be on a callers shoulders (column instead of line?)

**Comment by habamax** [comment]
> With the "export" mechanism that is in the patch, which is the right choice, the suggested script should be in ~/.vim/ftplugin/json.vim, not in "after".

@brammool I have changed the comment for the function to reflect this.

**Comment by habamax** [comment]
> * I would expect json object as the parameter. `json_format({ 'some': 'object' })`. One can easily convert any chunk of string to json object by using existing

Is this about converting vim's dict and array to formatted JSON string?

**Comment by prabirshrestha** [comment]
Yes. You don't need to implement formatting string, but instead objects (vim dict/array/boolean/string/number/float/null and so on. refer to `:h json_decode`)

```vim
let json_string = '{"some":"object"}'
let json_obj = json_decode(json_string)
let json_formatted = json_format(json_obj);
```

**Comment by habamax** [comment]
> Yes. You don't need to implement formatting string, but instead objects (vim dict/array/boolean/string/number/float/null and so on. refer to `:h json_decode`)
> 
> ```viml
> let json_string = '{"some":"object"}'
> let json_obj = json_decode(json_string)
> let json_formatted = json_format(json_obj);
> ```

I am not going to implement `json_format` as vim-api, hopefully there would be someone who can do it.

But I can make this one to accept vim objects and convert it to formatted json.

**Comment by habamax** [comment]
@prabirshrestha 

I have added `json.Format()` that accepts both a string with json and a vim structures.

https://asciinema.org/a/oJoH9Ketphr0M03v9LA3lUy7v

If this is needed as a `json_format` built-in, then hopefully someone would be able to translate and optimize this vim9script to C.

**Comment by brammool** [comment]
> Thanks for the quick PR but I think the api should be different.
> 
> * Shouldn't use just line number. As my json could start in a random column.

Formatting works on lines.  If you want to format part of a line, you
probably need to split it, format the right part and join them back
together.  An example of what you want to do is useful.

> * I would expect json object as the parameter. `json_format({ 'some':
> 'object' })`. One can easily convert any chunk of string to json
> object by using existing `json_encode()` function.
> * One should be able to provide custom space/tab with size indent size when formatting.

See my other message about this.

-- 
How To Keep A Healthy Level Of Insanity:
4. Put your garbage can on your desk and label it "in".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Yes. You don't need to implement formatting string, but instead objects (vim dict/array/boolean/string/number/float/null and so on. refer to `:h json_decode`)
> 
> ```vim
> let json_string = '{"some":"object"}'
> let json_obj = json_decode(json_string)
> let json_formatted = json_format(json_obj);
> ```

We are talking about very different things here.  This feature is about
json as text in a buffer, that we want to format to make it easy to read
for the user.  I know some tools (and browsers) spit out a blurp of json
that you would want to see what's in there and what it means.
Formatting the text makes that possible.

This is not about interpreting the meaning of the json or converting it
in any way.  We do already have support for that (since json is a nice
format for inter-process communication).  That is aimed at using json in
script and other languages, not how it is represented as text in a
buffer.

Of course there is a connection, and the formatting should not change
the meaning of the json, so it can also be used programatically if
wanted.  Main concern there is handling special characters and escaping,
that should not be underestimated.

But the primary goal here is to format the json so you can easily see
what it means.  There might be some options for how to break lines and
what indents you prefer, I don't expect much else, the json format is
quite well defined.

-- 
How To Keep A Healthy Level Of Insanity:
3. Every time someone asks you to do something, ask if they want fries
   with that.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by habamax** [comment]
> But the primary goal here is to format the json so you can easily see what it means. There might be some options for how to break lines and what indents you prefer, I don't expect much else, the json format is quite well defined.

@brammool it was there from the beginning -- it uses current settings of `expandtab` and `shiftwidth`.

The `json.Format()` function also accepts a dictionary with params where user can provide `use_tabs: bool`, `indent: number` (would be used if `use_tabs` is `false` -- number of spaces)

**Comment by brammool** [comment]
Have some users tried this out?  I would like to get some feedback from those who would like to use it.

**Comment by habamax** [comment]
> Have some users tried this out? I would like to get some feedback from those who would like to use it.

Not sure @prabirshrestha or anyone else had tried it.

There is a requested function to format vim dict/list structures, which is quite handy: https://asciinema.org/a/W7O5INJPGfsFfTcCj6Hd8BylW

**Comment by yegappan** [comment]
Any updates on this?

**Comment by habamax** [comment]
Well, it is in my config, I use it.

Not sure if anyone else tried it or found useful.

**Comment by chrisbra** [comment]
I think this is fine to include. Can you please add yourself as maintainer to the script?

**Comment by habamax** [comment]
> Can you please add yourself as maintainer to the script?

is this `.github/CODEOWNERS`?

**Comment by habamax** [comment]
`.github/CODEOWNERS` doesn't have entries for `runtime/autoload/dist/*.vim` at all though.

**Comment by chrisbra** [comment]
Can you also please add a Last Change header (so it should look similar to what the header is for other runtime files). Then, please add a section in `:h filetype.txt` (perhaps using the help-tag `:h ft-json-plugin`) that Vim now comes with a `json` formatter plugin and how to use it. Please also update the Last Change header for the `filetype.txt` help file.

**Comment by chrisbra** [comment]
> .github/CODEOWNERS doesn't have entries for runtime/autoload/dist/*.vim at all though.

Can you add one please?

**Comment by chrisbra** [comment]
Thanks!

**Pull request merged**
