### PR TITLE
Refactor undo.c to remove calls to STRLEN()

### PR DESCRIPTION
**Pull request by basilisk0315**
Is it worth using string_T in the undoline_T struct? Or in other places as well? I haven't done so because I wanted to get some feedback first.

Also, when using the comment `:undolist` the saved value doesn't line up with the heading. See here:
Screenshot 2024-11-05 140600

Should this be changed so the saved value is right-justified under it's heading?

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. This seems to be fine at a first look. Just verifying (I didn't check it yet), this doesn't change the undofile right?

**Comment by basilisk0315** [comment]
No there is no change to the undofile.

**Comment by chrisbra** [comment]
thanks. Let me add a test for the change of the `:undolist` command as well.

**Comment by chrisbra** [comment]
Ah, I misread your message. I thaught you already changed the alignment of the save_number. Actually I think this is fine, we don't need to right-align the number. So I think we are fine.

**Pull request closed without merging**
