### PR TITLE
Fix screenpos() not taking skipcol into account

### LINKED ISSUE #12476: screenpos() returns wrong result for wrapped line
### Steps to reproduce

```
vim --clean
```
```
call setline(1, 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet')
exe "normal! z1\<CR>$"
echo screenpos(0, line('.'), col('.'))
```
The result is all zeros:
image

### Expected behaviour

Should return something non-zero, because the position is visible.

Related: [8.2.3193](https://github.com/vim/vim/commit/189663bdac1156237c49925f77bd197c1bdea12c)

### Version of Vim

9.0.1558

### Environment

Ubuntu 22.04

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by zeertzjq**
Fix #12476

### CODE REVIEW

**Comment by brammool** [comment]
> Fix #12476

Thanks.  I noticed that w_skipcol is subtracted unconditionally, but it
should only happen for w_topline.  Adding a test for this I found
another problem in plines_win_nofold() where w_skipcol also needs to be
subtracted.  The tests pass now, I hope this doesn't break another
corner case.

-- 
To be rich is not the end, but only a change of worries.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Why did you close this PR?  Fixed by another PR perhaps?

**Comment by zeertzjq** [comment]
Oops, I thought this will soon be included in a larger patch.

**Comment by brammool** [comment]
I had already included it and made some changes on top.   Let me finish this and then please check it doesn't interfere with the other PRs.

**Pull request closed without merging**
