### PR TITLE
Allow completion functions to associate data with completion items

### LINKED ISSUE #2508: Proposal: Additional meta field in completion-items
That would allow providing additional information for `CompleteDone` auto command, like modules needed to be added to import list (source https://github.com/vim/vim/issues/2505#issuecomment-354376933).

Ref #2505

### PR DESCRIPTION
**Pull request by puremourning**
When using v:completed_item, it is useful to be able to perform
subsequent actions based on the completed item. This allows user defined
completion functions to supply custom data (in the form of a string, for
simplicity), which can be used within the CompleteDone autocommand to
perform any subsequent actions.

Example use cases include:
 - automatic insertion of import or include statements
 - insertion of snippets for method arguments.

Fixes #2508

### CODE REVIEW

**Comment by Shougo** [comment]
I think the feature is useful for plugins.

I think the name "extra" is better than `user_data`.
It contains the extra information.
What do you think?

**Comment by puremourning** [comment]
I'm totally ambivalent on the name. I liked `user_data` because it was sufficiently different from `extra text for the popup menu` which is the description of the `menu` parameter, and it more precisely describes its usage than `data` or `extra` or something.

But like I said, I'd go with any consensus on the key name.

**Comment by lacygoill** [comment]
What about `'msg'`? It seems one of the main goal will be to communicate an information to an autocmd listening to `CompleteDone`. It could be seen as a message.

**Comment by puremourning** [comment]
I think msg is even more ambiguous

**Comment by justinmk** [comment]
+1 for user_data or data. That is a very common convention.

**Comment by puremourning** [comment]
I fixed the texts failures, though I honestly don’t understand what caused hem.

**Comment by puremourning** [comment]
Thanks, Bram!

**Pull request closed without merging**
