### PR TITLE
Win32: restoring screen not always done right (try again)

### PR DESCRIPTION
**Pull request by ghost**
I cannot reply to ML now, so I chose PR.
I quickly realized that there was a problem.
It starts with a different color when !cmd is executed, only there.

It's a little big, because the code isn't organized.
I welcome corrections.

### CODE REVIEW

**Comment by ghost** [comment]
Looks solved. The operation requires verification.

**Comment by ghost** [comment]
Removed temporary code.
If you see scrolling issues with this patch, I think it's a terminal bug. maybe.

I'm a little tired this time.

**Comment by brammool** [comment]
Can someone please try this out and provide feedback?

**Comment by ghost** [comment]
Somebody please. 
Earlier patched mentioned that single line scroll up was disabled.

**Comment by k-takata** [comment]
I tried this.
It looks that it works fine when VTP is not used, but the screen is not restored properly when VTP is used.

```
> vim --clean --cmd "set tgc"
```

When the vim ended, many blank lines are shown.

**Comment by chrisbra** [comment]
Closing this, as the account has been deleted.

**Pull request closed without merging**
