### PR TITLE
Allow extend to take Blob for second argument if the first is List

### PR DESCRIPTION
**Pull request by mattn**
Current implementation dose not allow to get a list from blob easily. It is useful if `extend([], blob)` is allowed.

### CODE REVIEW

**Comment by chdiza** [comment]
The issue title and commit message mention `expand()`, but this patch is about `extend()`.

**Comment by mattn** [comment]
Fixed

**Comment by brammool** [comment]
For this kind of functionality I would like to see a motivation, or a
kind of design document.  Adding functionality one small part at a time
has the danger of becoming inconsistent.  In this case, an alternative
would be to turn the blob into a list before passing it to extend().


-- 
In many of the more relaxed civilizations on the Outer Eastern Rim of the
Galaxy, "The Hitchhiker's Guide to the Galaxy" has already supplanted the
great "Encyclopedia Galactica" as the standard repository of all knowledge
and wisdom, for though it has many omissions and contains much that is
apocryphal, or at least wildly inaccurate, it scores over the older, more
pedestrian work in two important respects.
First, it is slightly cheaper; and second, it has the words "DON'T PANIC"
inscribed in large friendly letters on its cover.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
So you want `blob2list` ?

**Comment by brammool** [comment]
> So you want `blob2list` ?

What is the purpose?  How will a plugin use this functionality, what is
it that can't be done with existing functions.

A Blob is a binary object, which we move around.  Generally no
manipulation is needed, since it's not containing text.  Converting a
blob from or to text is not something that has an obvious purpose.

-- 
Now it is such a bizarrely improbable coincidence that anything as
mind-bogglingly useful as the Babel fish could have evolved purely by chance
that some thinkers have chosen to see it as a final and clinching proof of the
NON-existence of God.
The argument goes something like this: 'I refuse to prove that I exist,' says
God, 'for proof denies faith, and without faith I am nothing.'
'But,' says Man, 'the Babel fish is a dead giveaway, isn't it?  It could not
have evolved by chance.  It proves you exist, and so therefore, by your own
arguments, you don't.  QED.'
'Oh dear,' says God, 'I hadn't thought of that,' and promptly vanishes in a
puff of logic.
'Oh, that was easy,' says Man, and for an encore goes on to prove that black
is white and gets himself killed on the next pedestrian crossing.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
If https://github.com/vim/vim/pull/4049 will be accepted, this feature is not required.

**Comment by brammool** [comment]
Closing, since #4049 was also closed and no comments added here for quite a while.

**Pull request closed without merging**
