### PR TITLE
[cleanup] Python2 eol  2020-01-01

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by brammool** [comment]
Perhaps we can keep it so long as it's working?

**Comment by pheiduck** [comment]
> Perhaps we can keep it so long as it's working?

sure, but to keep the ci in a flow i would merge this as early as possible, otherwise it comes to failed builds because of this.

**Comment by pheiduck** [comment]
**Note:** We need to remove some Python2 Code stuff as well later

**Comment by skywind3000** [comment]
Network devices like router, switcher and nas which still run in an old linux distribution may still use python2 by default. Those devices will not easily retire and get replaced like your personal laptops if they are still working.

Vim is were known to run in various systems, if the python2 code is not harmful to the main codebase, why not keep them, at least my router can benefit from this and can still use an update-to-date vim.

**Comment by pheiduck** [comment]
[Poll](https://strawpoll.com/h4fyu5kya)

**Pull request closed without merging**
