### PR TITLE
Fix typo in autocmd.txt

### PR DESCRIPTION
**Pull request by frangio**

### CODE REVIEW

**Comment by tonymec** [comment]
In this case there is no error. The proposed change would change don't (3rd person plural, agreeing with the subject "that" meaning "buffers" [plural]) into "doesn't" (3rd person singular, not agreeing). "don't" is the correct form ("buffers that don't have a name", where the subject of "don't have" is "that" = "buffers").
In Italian it would be, IIUC, "tamponi cuali non hanno un nome". The proposed change is equivalent to "tamponi cuali non *ha un nome" which is an error.

**Comment by vim-ml** [comment]
Hi,



Op do 7 jun. 2018 10:27 schreef Tony Mechelynck <vim-dev-github@256bit.org>:

> In this case there is no error. The proposed change would change don't
> (3rd person plural, agreeing with the subject "that" meaning "buffers"
> [plural]) into "doesn't" (3rd person singular, not agreeing). "don't" is
> the correct form ("buffers that don't have a name", where the subject of
> "don't" is "that" = "buffers").
>

The patch proposes don't, so it is correct.

Christ van Willegen

**Comment by tonymec** [comment]
Oops, sorry, my bad.

**Comment by brammool** [comment]
I'll include it, thanks.

**Pull request closed without merging**
