### PR TITLE
filetype: Gentoo portage files are not recognized

### PR DESCRIPTION
**Pull request by Freed-Wu**
Problem: Gentoo portage files are not recognized
Solution: Recognize Gentoo portage files as sh

https://dev.gentoo.org/~zmedico/portage/doc/man/make.conf.5.html
https://dev.gentoo.org/~zmedico/portage/doc/man/color.map.5.html

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks but make.conf seems to be also used by BSD: https://man.freebsd.org/cgi/man.cgi?make.conf(5)  using standard make syntax. 

Also, shell syntax doesn't seem to be correct according to the gentoo documentation.

**Comment by Freed-Wu** [comment]
should be a subtype of bash, (same as ash, dash, ...) some thing like `MAKEOPTS="-j$(nproc)"` can work. so we should create a new filetype named `portage_conf` or `portage_sh`?

**Comment by chrisbra** [comment]
isn't `conf` good enough?

**Comment by Freed-Wu** [comment]
conf cannot highlight `MAKEOPTS="-j$(nproc)"`'s special syntax, IMO.

**Comment by chrisbra** [comment]
I would say that is acceptable. We are not aiming to color each and every valid syntax element.

**Comment by chrisbra** [comment]
also can you make the pattern more strict? e.g. only detect it in `/etc/portage/` ?

**Comment by chrisbra** [comment]
It seems the tests fail

**Comment by chrisbra** [comment]
@Freed-Wu are you going to finish up your various filetype PRs?

**Comment by Freed-Wu** [comment]
https://github.com/gentoo/gentoo-syntax Gentoo has a official vim plugin.
https://github.com/gentoo/gentoo-syntax/issues/66 I ask them if can they push its syntax/ftplugin/ftdetect to vim runtime.

**Pull request closed without merging**
