### PR TITLE
Adding several httpd directives to syntax file

### PR DESCRIPTION
**Pull request by zdohnal**
Hi,

I got the report for Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1655313 for missing keywords in apache syntax file. This pull request fixes the issue, would you mind adding it to the project?

### CODE REVIEW

**Comment by chrisbra** [comment]
Have you tried to contact the maintainer of the file?

**Comment by zdohnal** [comment]
@chrisbra Not yet, I sent him by email just now.

**Comment by zdohnal** [comment]
@chrisbra David reviewed the patch and he said the patch is ok.

**Comment by brammool** [comment]
The normal procedure is that the syntax maintainer includes suggested improvements, and then sends me the resulting file.  This avoids that the next time the maintainer sends me an update some improvements may be dropped again, since I might not spot that.

**Comment by zdohnal** [comment]
I talked with Bram and David and Bram merged the patch. Closing.

**Pull request closed without merging**
