### PR TITLE
Add solarized colorscheme with termguicolors support

### PR DESCRIPTION
**Pull request by venthur**
This PR adds [stock solarized](https://github.com/altercation/vim-colors-solarized) (first commit) and adds support for termguicolors (second commit).

Please note that the original solarized has not been updated since 2011 and the author is not reacting to pull requests (which are plentiful), github issues, etc. However, solarized itself is licensed under the MIT license so we can just include it in vim and modify as needed.

Please consider merging this PR in the spirit of #1665

### CODE REVIEW

**Comment by venthur** [comment]
I think the Travis CI build is failing for reasons unrelated to this PR.

**Comment by chrisbra** [comment]
solarized is known to cause many questions and confusions. That was one reason why I intentionally did not consider this colorscheme (apart from not supporting 'termguicolors'). See also [this comment](https://github.com/vim/vim/issues/1665#issuecomment-320455091). If you want to have this colorscheme distributed with Vim, options and configuration variables need to be documented in the help I think.

**Comment by venthur** [comment]
This can be done, another option would be to simplify the colorscheme to get rid of the options right? Or is there some kind of policy to stay as close as possible to the upstream?

**Comment by venthur** [comment]
Added documentation as requested. I took upstream's documentation and:

  * added documentation for the `termguicolors` support I added to the original solarized
  * Re-ordered the sections and and section numbering
  * Fixed various spelling errors and typos

I updated the `Makefile` to include `solarized.txt` and `solarized.html` but I'm not sure if I have to update something else.

**Comment by venthur** [comment]
In order to simplify the colorscheme I removed the code for the "solarized menu" and the corresponding docs for the menu. 

The menu that was only shown in GUI and allowed the user to modify the solarized options before writing them to .vimrc. This removed a great deal of code from the colorscheme.

**Comment by venthur** [comment]
I further removed code that should not belong in a colorscheme. Please let me know if there's anything else you want me to fix. I don't know how to deal with the coveralls.io "failure".

**Comment by venthur** [comment]
I think that should be it. Please review and give feedback for further improvements.

**Comment by lifepillar** [comment]
It's nice to see people wanting to push https://github.com/vim/vim/issues/1665 forward! As the maintainer of a “competing” colorscheme (Solarized 8), though, I have a few remarks:

- there is a long standing issue in Solarized (see https://github.com/altercation/solarized/issues/102); before merging this, or other colorschemes that set syntax highlight groups (e.g., `vimCommand`), I think that Vim developers should tell what to do about issues like that. For instance, they might say that colorschemes that set syntax highlight groups cannot be distributed with Vim, or that they are acceptable provided that there is a setting to turn them on/off. Or they might say that they are going to fix the issue in Vim. Or they might decide to accept colorschemes that do anything (!).

- Since it is very popular, as soon as Solarized is included in Vim people will start reporting bugs and feature requests (e.g., if this pull request is accepted as is, https://github.com/altercation/solarized/issues/102 is guaranteed to be reported as a bug). An active maintainer is mandatory. Who will maintain this?

**Comment by chrisbra** [comment]
let me ask more explicit: @venthur  are you going to maintain the new solarized colorscheme and take care of user issues and bugs?

**Comment by venthur** [comment]
@chrisbra sure! Although, looking at the current state of the files in `runtime/colors` (many of them haven't been updated for more than a decade) it is probably preferable for the project if a team of colorscheme lovers would collaboratively take care of the files.

**Comment by brammool** [comment]
Lifepillar wrote:

> It's nice to see people wanting to push
> https://github.com/vim/vim/issues/1665 forward! As the maintainer of a
> “competing” colorscheme (Solarized 8), though, I have a few remarks:
> 
> - there is a long standing issue in Solarized (see
> https://github.com/altercation/solarized/issues/102); before merging
> this, or other colorschemes that set syntax highlight groups (e.g.,
> `vimCommand`), I think that Vim developers should tell what to do
> about issues like that. For instance, they might say that colorschemes
> that set syntax highlight groups cannot be distributed with Vim, or
> that they are acceptable provided that there is a setting to turn them
> on/off. Or they might say that they are going to fix the issue in Vim.
> Or they might decide to accept colorschemes that do anything (!).
> 
> - Since it is very popular, as soon as Solarized is included in Vim
> people will start reporting bugs and feature requests (e.g., if this
> pull request is accepted as is,
> https://github.com/altercation/solarized/issues/102 is guaranteed to
> be reported as a bug). An active maintainer is mandatory. Who will
> maintain this?

The inclusion of a nice set of colorschemes has stalled, mainly because
it's difficult to decide what the minimal requirements are.

I think it would be good to have a script to check the quality of a
color scheme.  There are a few obvious things, such as either respecting
the value of 'background' or setting it.  But also that highlighting for
various things is defined, such as folding and diff mode.

This will not only make it easy to reject bad colorschemes, but also
help new developers find out what's wrong.

There have been various remarks about what a colorscheme should do, can
someone turn that into a check script?  There is the src/po/check.vim
script, it might have some useful ideas.

-- 
BLACK KNIGHT: None shall pass.
ARTHUR:       I have no quarrel with you, brave Sir knight, but I must cross
              this bridge.
BLACK KNIGHT: Then you shall die.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
>I think it would be good to have a script to check the quality of a color scheme

It is not exactly what you have in mind, because it is a pre-processor rather than a post-processor, but my [Colortemplate](https://github.com/lifepillar/vim-colortemplate) plugin performs all the checks you mention, and more.

I have added a preliminary “best practices” section at the end of  the [help file](https://github.com/lifepillar/vim-colortemplate/blob/master/doc/colortemplate.txt), which was requested by @chrisbra at https://github.com/vim/vim/issues/1665.  That is based on my experience, and there are surely several things missing (for instance, what is the best way to use `reverse` with Cursor, CursorColumn, Search/IncSearch, … so that things overlap correctly?).

**Comment by venthur** [comment]
Having a QA test script for a colorscheme is an excellent idea, I would even go further and have it run as a mandatory unit test for **every** colorscheme included in vim. This way we have a better chance of keeping the existing ones tidy and updated.

**Comment by brammool** [comment]
Lifepillar wrote:

> >I think it would be good to have a script to check the quality of a
> >color scheme
> 
> It is not exactly what you have in mind, because it is a pre-processor
> rather than a post-processor, but my
> [Colortemplate](https://github.com/lifepillar/vim-colortemplate)
> plugin performs all the checks you mention, and more.
> 
> I have added a preliminary “best practices” section at the end of  the
> [help
> file](https://github.com/lifepillar/vim-colortemplate/blob/master/doc/colortemplate.txt),
> which was requested by @chrisbra at
> https://github.com/vim/vim/issues/1665.  That is based on my
> experience, and there are surely several things missing (for instance,
> what is the best way to use `reverse` with Cursor, CursorColumn,
> Search/IncSearch, … so that things overlap correctly?).

Looks useful. However, we don't want to enforce using this
colortemplate.

How does one check a colorscheme with your tools?
I was thinking of sourcing a "check.vim" file and either getting "OK" or
some list of warnings and errors.

-- 
Westheimer's Discovery:
        A couple of months in the laboratory can
        frequently save a couple of hours in the library.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
>Looks useful. However, we don't want to enforce using this colortemplate.

Of course. The idea is that colorschemes generated with my plugin should pass all the relevant checks by default. It is just one option to make life easier for colorscheme developers, especially those who'd like to submit their work for distribution with Vim.

>How does one check a colorscheme with your tools?

One creates a template in a buffer following a compact syntax and then “compiles” the buffer into a colorscheme. Checks are performed during parsing, and errors/warnings are added to a location list. The main advantage, IMHO, is that, if there are no errors, the result is correct by construction (e.g., background settings).

I can imagine applying similar checks to colorschemes, although I guess that some things will be harder to check (for example, think about validating this pull request). Feel free to use ideas and code from Colortemplate, though!

**Comment by venthur** [comment]
I love the idea of a QA script to validate new colorschemes and unittest existing ones. I created a separate issue for that #2325 where we can further discuss the idea without hijacking this PR :)

**Comment by venthur** [comment]
Can somebody help me with the coveralls test failing? I don't see what coveralls is complaining about, and how to fix it.

**Comment by k-takata** [comment]
No need to care about that. We can simply ignore the failure.
(There is a setting in coveralls: "Coverage Decrease Threshold for failure". Only Bram can set this.)

**Comment by venthur** [comment]
Refreshed the patch.

**Comment by brammool** [comment]
I'm not including a specific colorscheme until we have a good overview of which ones should be included in the distribution.  Hopefully someone picks up that task.
I'll keep this PR open as an example of the testing stuff.

**Comment by brammool** [comment]
This can now be discussed on vim/colorschemes

**Pull request closed without merging**
