### PR TITLE
Add i_CTRL-X_CTRL-Z to stop ins-completion and allow switching to another CTRL-X mode in CTRL-X CTRL-V mode

### PR DESCRIPTION
**Pull request by zeertzjq**
An alternative to #8804.

### CODE REVIEW

**Comment by chrisbra** [comment]
Is this `ctrl-x-ctrl-z` safe to use? In particular, will `CTRL-Z` not be used by the terminal to suspend/stop the job?

**Comment by zeertzjq** [comment]
> Is this `ctrl-x-ctrl-z` safe to use? In particular, will `CTRL-Z` not be used by the terminal to suspend/stop the job?

Do terminal emulators do that? Even Linux console (tty) doesn't do that.

**Comment by zeertzjq** [comment]
> Is this `ctrl-x-ctrl-z` safe to use? In particular, will `CTRL-Z` not be used by the terminal to suspend/stop the job?

I don't think terminal emulators do that. Even Linux console (tty) doesn't do that.

**Comment by chrisbra** [comment]
I am not sure, just wondering. And there is e.g. `stty susp ^Z` not sure how common that setting is. It's one of the reasons, I tend to avoid `^Z` similar like `^S`

**Comment by zeertzjq** [comment]
Oh, it also seems to depend on shell. When using `bash` as login shell `CTRL-S` doesn't work, while it works when using `fish`. `CTRL-Z` works in either though. `susp = ^Z` is always present, but it always works nevertheless, propably because Vim ignores `SIGTSTP`.

**Comment by brammool** [comment]
> I am not sure, just wondering. And there is e.g. `stty susp ^Z` not
> sure how common that setting is. It's one of the reasons, I tend to
> avoid `^Z` similar like `^S`

Vim only supports using CTRL-Z in Normal and Visual mode to suspend.
In Insert mode currently it inserts the character 0x1a.  That doesn't
seem very useful, thus using that to stop completion should be OK.

-- 
BLACK KNIGHT: The Black Knight always triumphs. Have at you!
   ARTHUR takes his last leg off.  The BLACK KNIGHT's body lands upright.
BLACK KNIGHT: All right, we'll call it a draw.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zeertzjq** [comment]
Allowing switching to another CTRL-X mode in CTRL-X CTRL-V mode can be useful in this case: if one maps a keybinding to `<C-X><C-U>`, pressing that keybinding in Insert mode always enters user-defined completion mode. Without this, pressing that keybinding doesn't switch to user-defined completion mode in CTRL-X CTRL-V mode.

**Comment by zeertzjq** [comment]
> I am not sure, just wondering. And there is e.g. `stty susp ^Z` not sure how common that setting is. It's one of the reasons, I tend to avoid `^Z` similar like `^S`
> Vim only supports using CTRL-Z in Normal and Visual mode to suspend. In Insert mode currently it inserts the character 0x1a. That doesn't seem very useful, thus using that to stop completion should be OK.
> […](#)
> -- BLACK KNIGHT: The Black Knight always triumphs. Have at you! ARTHUR takes his last leg off. The BLACK KNIGHT's body lands upright. BLACK KNIGHT: All right, we'll call it a draw. "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net \\\ /// \\\ \\\ sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

I made `ins_compl_prep` return `TRUE` if CTRL-Z comes after CTRL-X, which prevents suspending even if `'insertmode'` is set. CTRL-Z alone still suspends if `'insertmode'` is set or inserts `0x1a` if `'insertmode'` is not set.

**Comment by brammool** [comment]
It seems to be OK now.  Can't be 100% sure.  Let me include it and let everybody try it out.

**Comment by lifepillar** [comment]
>It seems to be OK now. Can't be 100% sure. Let me include it and let everybody try it out.

FYI, I have updated MUcomplete to use this, and it does not seem to break anything.

**Comment by brammool** [comment]
> >It seems to be OK now. Can't be 100% sure. Let me include it and let
> >everybody try it out.
> 
> FYI, I have updated MUcomplete to use this, and it does not seem to
> break anything.

Thanks for checking.  Some day the whole insert mode completion code
should be rewritten, the state handling is just too confusing.


-- 
Scientists decoded the first message from an alien civilization:
        SIMPLY SEND 6 TIMES 10 TO THE 50 ATOMS OF HYDROGEN TO THE STAR
SYSTEM AT THE TOP OF THE LIST, CROSS OFF THAT STAR SYSTEM, THEN PUT
YOUR STAR SYSTEM AT THE BOTTOM OF THE LIST AND SEND IT TO 100 OTHER
STAR SYSTEMS.  WITHIN ONE TENTH GALACTIC ROTATION YOU WILL RECEIVE
ENOUGH HYDROGREN TO POWER YOUR CIVILIZATION UNTIL ENTROPY REACHES ITS
MAXIMUM!  IT REALLY WORKS!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
