### PR TITLE
feat(filetype): add foam filetype autocmds

### PR DESCRIPTION
**Pull request by FoamScience**
Adding the [OpenFOAM](https://github.com/OpenFOAM/OpenFOAM-dev) file type which was previously recognized as `cpp`.
Now we have a [TreeSitter grammar](https://github.com/FoamScience/tree-sitter-foam) and a [language server](https://github.com/FoamScience/foam-language-server), so I thought it's time Vim learns to detect OpenFOAM-related files.

- Unfortunately; the only reliable way to detect `foam` file type is by looking into the file; That's what the `dist#ft#FTfoam()` in `runtime/autoload/dist/ft.vim` does.
- The new autocmds in `runtime/autoload/dist/ft.vim` account for most of the OpenFOAM file patterns;

A typical set of OpenFOAM files can be found [here](https://github.com/OpenFOAM/OpenFOAM-dev/tree/master/tutorials/basic/scalarTransportFoam/pitzDaily) (Note the directory also contains shell scripts)
From [OpenFOAM tutorials](https://github.com/OpenFOAM/OpenFOAM-dev/tree/master/tutorials), here are the first 40 file patterns (but we're not just limited to these):
```
    241 system/fvSolution
    241 system/fvSchemes
    234 system/controlDict
    186 system/blockMeshDict
    163 constant/momentumTransport
    150 0/U
    142 0/p
    112 constant/transportProperties
    106 constant/g
     93 0/nut
     92 0/k
     91 system/decomposeParDict
     78 0/p_rgh
     77 constant/thermophysicalProperties
     67 0/epsilon
     64 0/T
     56 system/setFieldsDict
     44 0/alphat
     42 system/fvConstraints
     38 0/alpha.water.orig
     36 system/topoSetDict
     35 constant/fvModels
     28 constant/dynamicMeshDict
     25 constant/phaseProperties
     25 constant/combustionProperties
     24 0/omega
     23 system/snappyHexMeshDict
     19 system/meshQualityDict
     19 constant/thermophysicalProperties.air
     18 constant/momentumTransport.air
     18 constant/cloudProperties
     18 0/nuTilda
     17 0/U.orig
     17 0/U.air
     17 0/H2O
     16 system/surfaceFeaturesDict
     16 constant/thermophysicalProperties.water
     16 0/alpha.air.orig
     15 0/O2
     15 0/N2
```

### CODE REVIEW

**Comment by FoamScience** [comment]
@brammool Question: Would the great VIM be interested in supporting foam filetype without any syntax files.
If that's not an options, how  about I switch to a sub-filetype (`cpp.foam`)?
+ I wrote a simple test function, but not sure if it's called in CI workflows; would appreciate it if I get some orientation here.

**Comment by brammool** [comment]
Adding filetype detection without support files is OK, it still makes it easier for users to do something specific for this type of file.

The "cpp.foam" name only makes sense if this type of file is full "cpp" and adds something on top of that.  Generally that's only used for formatted comments.

**Comment by brammool** [comment]
The file name pattern is a bit complex, but I suppose it works and since FTfoam() is called to check the contents it's unlikely to get it wrong.

**Comment by FoamScience** [comment]
> The file name pattern is a bit complex, but I suppose it works and since FTfoam() is called to check the contents it's unlikely to get it wrong.

Exactly, I was especially careful to devise the most "specialized" file pattern because obviously "*" is not wise in upstream VIM; and I did sacrifice not being able to detect the type of some foam files.
+ FTfoam() won't do anything if the content of the file does not suggest that it's foam.
A good test file would be `transportProperties.c` for example; it will be recognized as c if it does not contain
```
FoamFile  <---- this is required
{
    object  something;  <-- Then, this, in this order
}
```
near the beginning. I think that's a decent criterion

**Pull request closed without merging**
