### PR TITLE
runtime: make command name for &iskeywordprg more unique

### PR DESCRIPTION
**Pull request by Konfekt**
See https://github.com/vim/vim/pull/13213/commits by @dkearns: Rename 'keywordprg' user command to ShKeywordPrg as this is just a leaking implementation detail.

### CODE REVIEW

**Comment by dkearns** [comment]
Thanks @Konfekt.  Can you please update the "Last Change" headers too?  The date of the PR is fine.

**Comment by Konfekt** [comment]
Yes, did so.

**Comment by chrisbra** [comment]
can you please add a LastChange header to the systemd filetype plugin? BTW: what is with the zsh ftplugin? It only changes the date?

**Comment by Konfekt** [comment]
Thank you @chrisbra, both of your remarks have been addressed by the latest push

**Comment by chrisbra** [comment]
thanks, looks good now.

**Pull request merged**
