### PR TITLE
Added a syntax highlighter for Poke

### PR DESCRIPTION
**Pull request by mtihlenfield**
This commit adds a syntax highlighter for the Poke language: http://www.jemarch.net/poke

### CODE REVIEW

**Comment by brammool** [comment]
The poke filetype is not yet recognized.  Can you also add an entry in runtime/filetype.vim?

**Comment by mtihlenfield** [comment]
Added the entry!

**Comment by brammool** [comment]
Thanks.  I'll include the filetype entry, the other file will be in the next runtime file update.
It appears Poke is also a natural language: https://en.wikipedia.org/wiki/Poke_language

**Comment by brammool** [comment]
In patch 8.2.2591

**Comment by mtihlenfield** [comment]
Thanks brammool! I didn't not know that... I'll pass that on to the maintainers!

**Pull request closed without merging**
