### PR TITLE
syntax: Fix #1705

### LINKED ISSUE #1705: Update syntax highlighting for HTML & CSS
There are some new features out that just need some more keywords. I haven't dug into the repo at all, although I may do so in around a week.

Just some things I noticed when editing one of my files (version 8.0, I doubt the patch matters)

HTML
--------
`<dialog>`

CSS
--------
`display: grid` and `display: flex` - presumably things like `inline-grid`, `subgrid`, `inline-flex`, etc. are also missing.

Native variables - matching the following regex: `--.*:.*` and `var(--.*)`

To go along with grid and flex, similar selectors:
`align-items`
`justify-content`
`grid-.*` - tons of things here, not listing them all. Obviously not a generic selector.
`dialog::backdrop` pseudoselector (for `dialog` HTML element)

### PR DESCRIPTION
**Pull request by JulesWang**
Fix many highlight issues.

- fix bug on % and float number in KeyFrameSelector .
- add FlexibleBox related props and attrs
- add grid related props and attrs
- add a color "rebeccapurple"
- add a tag "diaglog" in html.vim
- add "inline-flex" and "inline-grid"
- fix "small-caps" highlighting
- others

----
issues not address in #1705 

> Native variables - matching the following regex: --.*:.* and var(--.*)

not quite understand, pls show me some examples :-)

> dialog::backdrop

prefer not to fix it, because this feature is not in the w3c standard currently.

> Finally, I notice that sometimes when I page down the entire screen's worth of CSS is not highlighted. I will then page back and then forward again and it will paint properly. I do not recall seeing this in any other language that I use, so feel it may be specific to the CSS syntax rules.

need help.

### CODE REVIEW

**Comment by brammool** [comment]
Jules Wang wrote:

> Fix many highlight issues.
> 
> - fix bug and simplify code for digits and units, like % and float number in KeyFrameSelector .
> - add FlexibleBox related props and attrs
> - add grid related props and attrs
> - add a color "rebeccapurple"
> - add a tag "diaglog" in html.vim
> - add "inline-flex" and "inline-grid"
> - fix "small-caps" highlighting
> - others
> 
> ----
> issues not address in #1705 
> 
> > Native variables - matching the following regex: --.*:.* and var(--.*)
> 
> not quite understand, pls show me some examples :-)
> 
> > dialog::backdrop
> 
> prefer not to fix it, because this feature is not in the w3c standard currently.
> 
> > Finally, I notice that sometimes when I page down the entire screen's worth of CSS is not highlighted. I will then page back and then forward again and it will paint properly. I do not recall seeing this in any other language that I use, so feel it may be specific to the CSS syntax rules.
> 
> need help.

There is something that looks wrong:  The match for cssValueInteger is
deleted:

" digits
syn match cssValueInteger contained "[-+]\=\d\+" contains=cssUnitDecorators

But it is still used in several places.

Same for cssValueLength, cssValueAngle and cssValueTime.

Note that removing groups might be a problem for users who have defined
specific highlighting for these items.

-- 
Time is an illusion.  Lunchtime doubly so.
		-- Ford Prefect, in Douglas Adams'
		   "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by JulesWang** [comment]
> Note that removing groups might be a problem for users who have defined
> specific highlighting for these items.

Well, this modification is broken and is also a bad idea, I have reverted the change which is related.

**Comment by brammool** [comment]
It's easier for me if you send me the latest version of the file, instead of individual patches.

**Comment by JulesWang** [comment]
OK， I got it.  :-)

**Comment by brammool** [comment]
Included, thanks.

**Pull request closed without merging**
