### PR TITLE
More restrictive vtp, tgc more broadly

### PR DESCRIPTION
**Pull request by ghost**
This allowed ``tgc`` to always be used on conditions that are not ``term=win32``.

### CODE REVIEW

**Comment by ghost** [comment]
I'm sorry to have made you extra trouble. Be more careful. Thank you for your kind.

**Comment by brammool** [comment]
Nobuhiro Takasaki wrote:

> This allowed ``tgc`` to always be used on conditions that are not ``term=win32``.

Thanks.  I wonder if the line below, calling control_console_color_rgb()
also needs to be changed?

When using the Windows console, could 'term' be something else than
"win32"?  We could check t_Co to be 256 or more instead.  I assume that
when t_Co is 16 then using 'termguicolors' won't work.

On the other hand, we can leave the choice to the user, if it doesn't
work he'll find out soon enough.

-- 
ARTHUR:        A scratch?  Your arm's off!
BLACK KNIGHT:  No, it isn't.
ARTHUR:        Well, what's that then?
BLACK KNIGHT:  I've had worse.
                                  The Quest for the Holy Grail (Monty Python)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
I was delayed, but moved control_console_color_rgb() to the correct location.

Earlier I did not know, but ConEmu requires vim.exe to behave to act on xterm terminals.
I made vtp not collapse even if 'term' is set to 'xterm'.

**Comment by janlazo** [comment]
ConEmu works with `term=win32` but it will be limited to 8-16 colors, same as the default Windows console. It can be configured to support ANSI sequences (see https://conemu.github.io/en/AnsiEscapeCodes.html) such that `term=xterm` works.

`term=xterm` is not required but it's convenient for users on Windows 7 and 8 to use `termguicolors` without `+vcon` and to fallback to `term=win32` inside `:terminal`.

**Comment by ghost** [comment]
If I write a patch that does not limit tgc's conditions, will it be a good result?

I think now, if I limit the operating conditions, I think that we will have to make a new restriction in the future. Probably the condition exploded.

I now want to leave the choice of the correct combination (term, tgc, t_Co) to the user.

**Comment by ghost** [comment]
I think carefully and executed it.
I am happy if it is a good result.

**Comment by ghost** [comment]
In the current VTP, because of the problem of cmd.exe, we redraw 2 rows on the right side of the screen.
Since it is only a problem of cmd.exe, it will not be handled by other terminals.
In the same way as before, a line feed code is issued twice for the display of one line.
It seems that it is working well here.

**Comment by janlazo** [comment]
@ntak Is the issue on the shell or the default terminal? What if the user is running sh/bash (msys2) but uses the native Windows release of Vim instead of the bundled Vim in msys2 such that `TERM=cygwin`? I'm just curious because you're checking `$ConEmuANSI` which will be inherited in nested shells if the user is not careful.

**Comment by janlazo** [comment]
I'd check `$ConEmuANSI ==# 'ON'` because it can have a different value (ie. `OFF`). I unset it in my vimrc out of laziness since it works so far but I'm waiting for winpty to resolve https://github.com/rprichard/winpty/issues/106 so it can set/unset the environment variables automatically.

**Comment by ghost** [comment]
The cause is drawing problem with cmd.exe.
Whatever the term is, the VTP scroll of cmd.exe is broken.
Specifically, at the sequence such as "^[[T" or "^[[S", the right edge of the screen will be broken. I draw it with scroll.c every time.

If I could detect that vim.exe was launched from cmd.exe, I would not have seen ConEmuANSI.
It may be necessary to enumerate terminals other than cmd.exe so that cmd.exe can detect that it started vim.exe.

It is necessary to look for a loophole of the emulator.
Since mintty does not emulate ENABLE_VIRTUAL_TERMINAL_PROCESSING, it works normally.
Because ConEmu emulated incompletely even it, measures are necessary.

**Comment by ghost** [comment]
The current method will eventually explode.
Look for a way to ensure that cmd.exe is the parent process.
It will take a while. sorry.

**Comment by ghost** [comment]
I changed my point of view. It is better than looking at environment variables.

**Comment by janlazo** [comment]
@ntak If running powershell as the parent shell or running powershell as a child shell of cmd.exe, does the scrolling issue happen?

**Comment by ghost** [comment]
I think that there is no problem with scrolling.
I tried it here, it seems to be OK.

**Comment by janlazo** [comment]
Why did tgc test fail on Appveyor?

**Comment by chrisbra** [comment]
> Why did tgc test fail on Appveyor?

Test_termguicolors failed here:

    if has('vtp') && !has('vcon')
      " Win32: 'guicolors' doesn't work without virtual console.
      call assert_fails('set termguicolors', 'E954:')
      return
    endif

**Comment by ghost** [comment]
Thank you for your advice. How about this?

**Comment by ghost** [comment]
I can not do it ... I will try harder a little.

**Comment by ghost** [comment]
Is this OK?

**Comment by janlazo** [comment]
Any blockers to getting this merged? I want to try it out but I don't see any artifacts in the Appveyor build.

**Comment by ghost** [comment]
What's happening? Is it my mistake?

**Comment by janlazo** [comment]
@ntak I don't think it's your fault since your changes didn't touch the appveyor configuration. I'll build with your changes on my machine in the meantime.

**Comment by janlazo** [comment]
@ntak `+vcon` is always true even on cmd.exe with `t_Co=16`? I get a colorless buffer with `set tgc`. I have to use `set tgc` on ConEmu because `set notgc` limits # of colors to 16 even with `t_Co=256`.

**Comment by ghost** [comment]
I made it simple first.

**Comment by ghost** [comment]
Ah... Looking at the help, the condition is reversed.

**Comment by ghost** [comment]
I divided a number of problems now.
I have inconvenienced everyone.

**Comment by ghost** [comment]
I will close it. Thank you very much.

**Pull request closed without merging**
