### PR TITLE
Add VDF file type & syntax

### PR DESCRIPTION
**Pull request by ObserverOfTime**
This is the JSON-like data format used by Valve, aka [KeyValues](https://developer.valvesoftware.com/wiki/KeyValues).

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Can this be merged? The CI failure seems unrelated:

```
 	1 FAILED:
	Found errors in Test_play_silent():
	Test caused Vim to exit: Test_play_silent()
```

**Comment by zeertzjq** [comment]
Seems already merged

**Comment by ObserverOfTime** [comment]
Huh.

**Comment by brammool** [comment]
> Can this be merged? The CI failure seems unrelated:
> 
> ```
>  	1 FAILED:
> 	Found errors in Test_play_silent():
> 	Test caused Vim to exit: Test_play_silent()
> ```

Yeah, this test is a tiny bit flaky.  Not sure whey it would make Vim
crash, I have not been able to reproduc it or spot a problem with
valgrind or asan.

-- 
Bare feet magnetize sharp metal objects so they point upward from the
floor -- especially in the dark.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
