### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by rbtnn**
This fixed the following warnings.
コメント 2020-08-05 002951

### CODE REVIEW

**Comment by brammool** [comment]
I do not think a type cast is correct here, since the stat_T is defined in vim.h as:
typedef struct _stat64 stat_T;
Perhaps in write_viminfo() st_new and st_old should use "struct stat *" instead of stat_T?

**Comment by rbtnn** [comment]
I got it. Thank you for taking the time to explain to me.

**Comment by brammool** [comment]
Did you try replacing stat_T by "struct stat"?  If you adjust the pull request we can see what happens with CI.

**Comment by rbtnn** [comment]
I just found how to fix this. Perhaps this is good.

**Comment by brammool** [comment]
Included what was needed, let's see if any warnings remain.

**Comment by rbtnn** [comment]
Thank you for marging. 

> let's see if any warnings remain.

I got it.

**Pull request closed without merging**
