### PR TITLE
quickfix: trigger autocommands when wiping dummy buffer

### LINKED ISSUE #7517: vimgrep: missing autocommands when dummy buffer is wiped
**Describe the bug**
Using `:vimgrep` trigger `BufRead` autocommand for files searched, and if no match is found the dummy buffer is wiped. It do however not trigger a `BufUnload` or `BufWipeout` autocommand which leads to an inconsistent state.

This was originally reported as a part of the Go plugin govim, govim/govim#1008

**To Reproduce**
```
$ cd (mktemp -d)
$ cat > vimrc <<EOF
au BufRead * echom "BufRead ".expand("<abuf>")
au BufUnload * echom "BufUnload ".expand("<abuf>")
au BufWipeout * echom "BufWipeout ".expand("<abuf>")
EOF
$ echo foo > bar
$ vim -u vimrc bar
```

```
:vimgrep /abc/ *
```
No match found, BufRead is logged for buffer 2.

```
:ls!
```
No buffer 2.

**Expected behavior**
Autocommands when the dummy buffer is removed.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1234] (Or paste the result of `vim --version`.)
 ```
 VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 12 2020 19:16:17)
macOS version
Included patches: 1-1979
Compiled by leitzler@calcium
Huge version without GUI.  Features included (+) or not (-):
+acl               +cindent           +cursorshape       +file_in_path      +job               +menu              +mouse_urxvt       +popupwin          +signs             -tcl               +vartabs           -X11
+arabic            -clientserver      +dialog_con        +find_in_path      +jumplist          +mksession         +mouse_xterm       +postscript        +smartindent       +termguicolors     +vertsplit         -xfontset
+autocmd           +clipboard         +diff              +float             +keymap            +modify_fname      +multi_byte        +printer           -sound             +terminal          +virtualedit       -xim
+autochdir         +cmdline_compl     +digraphs          +folding           +lambda            +mouse             +multi_lang        +profile           +spell             +terminfo          +visual            -xpm
-autoservername    +cmdline_hist      -dnd               -footer            +langmap           -mouseshape        -mzscheme          -python            +startuptime       +termresponse      +visualextra       -xsmp
-balloon_eval      +cmdline_info      -ebcdic            +fork()            +libcall           +mouse_dec         +netbeans_intg     -python3           +statusline        +textobjects       +viminfo           -xterm_clipboard
+balloon_eval_term +comments          +emacs_tags        -gettext           +linebreak         -mouse_gpm         +num64             +quickfix          -sun_workshop      +textprop          +vreplace          -xterm_save
-browse            +conceal           +eval              -hangul_input      +lispindent        -mouse_jsbterm     +packages          +reltime           +syntax            +timers            +wildignore
++builtin_terms    +cryptv            +ex_extra          +iconv             +listcmds          +mouse_netterm     +path_extra        +rightleft         +tag_binary        +title             +wildmenu
+byte_offset       -cscope            +extra_search      +insert_expand     +localmap          +mouse_sgr         -perl              -ruby              -tag_old_static    -toolbar           +windows
+channel           +cursorbind        -farsi             +ipv6              -lua               -mouse_sysmouse    +persistent_undo   +scrollbind        -tag_any_white     +user_commands     +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN  -O2   -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc    -o vim        -lm -lncurses  -liconv -framework AppKit
```
 - OS: macOS 10.15.7
 - Terminal: iTerm2

### PR DESCRIPTION
**Pull request by leitzler**
Fixes vim/vim#7517

### CODE REVIEW

**Comment by chrisbra** [comment]
can you add a test for your change please?

**Comment by leitzler** [comment]
@chrisbra I'd love to, but I don't really know vimscript good enough. I wouldn't mind at all if someone else did add a test, otherwise I need guidance.

**Comment by lacygoill** [comment]
How about this:
```diff
diff --git a/src/testdir/test_autocmd.vim b/src/testdir/test_autocmd.vim
index f7963259b..68994ba6f 100644
--- a/src/testdir/test_autocmd.vim
+++ b/src/testdir/test_autocmd.vim
@@ -150,6 +150,15 @@ func Test_bufunload()
   bwipeout
   call assert_equal(["bufunload", "bufdelete", "bufwipeout"], s:li)
 
+  let s:li=[]
+  sp Xtest1
+  e Xtest2
+  silent! vimgrep /wontbefound/ Xtest*
+  call assert_equal(["bufunload", "bufunload", "bufwipeout"], s:li)
+  bwipeout
+  call delete('Xtest1')
+  call delete('Xtest2')
+
   au! test_bufunload_group
   augroup! test_bufunload_group
 endfunc
```

Or this:
```diff
diff --git a/src/testdir/test_autocmd.vim b/src/testdir/test_autocmd.vim
index f7963259b..17b4f543e 100644
--- a/src/testdir/test_autocmd.vim
+++ b/src/testdir/test_autocmd.vim
@@ -150,6 +150,16 @@ func Test_bufunload()
   bwipeout
   call assert_equal(["bufunload", "bufdelete", "bufwipeout"], s:li)
 
+  let s:li=[]
+  sp Xtest1
+  e Xtest2
+  silent! vimgrep /wontbefound/ Xtest*
+  call assert_true(index(s:li, "bufunload") >= 0)
+  call assert_true(index(s:li, "bufwipeout") >= 0)
+  bwipeout
+  call delete('Xtest1')
+  call delete('Xtest2')
+
   au! test_bufunload_group
   augroup! test_bufunload_group
 endfunc
```

**Comment by leitzler** [comment]
@lacygoill thanks for pointing me in the right direction.

@chrisbra I added a test, let me know if I need to update/move it.

**Pull request closed without merging**
