### PR TITLE
Test &makeprg for the SpotBugs compiler plugin

### PR DESCRIPTION
**Pull request by zzzyxwvut**

### CODE REVIEW

**Comment by zzzyxwvut** [comment]
Pending until #16001 is done, to be reset and rebased.

**Comment by zzzyxwvut** [comment]
Wow... FreeBSD did not [come through](https://cirrus-ci.com/task/6249589865447424).

**Comment by zzzyxwvut** [comment]
The initial parsing method for `&l:makeprg` was rather naïve:  
directories with `-`s in their names were not considered,  
instead `-`s were always assumed to be command flags, barring  
matches of `package-info.class` or `module-info.class`; hence  
the failure on FreeBSD and its `/tmp/cirrus-ci-build/`.  Now  
the known scratch directory `Xspotbugs` is always sought after  
for each file argument and command flags are left alone.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
