### PR TITLE
runtime: Set comments and commentstring for rpmspec

### PR DESCRIPTION
**Pull request by cryptomilk**
Set comments and commentstring for rpmspec.

### CODE REVIEW

**Comment by cryptomilk** [comment]
@ignatenkobrain

**Comment by chrisbra** [comment]
Thanks, but you should update `b:undo_ftplugin`

**Comment by cryptomilk** [comment]
Thanks for the pointer, done :-)

**Comment by chrisbra** [comment]
I think @ignatenkobrain is no longer maintaining those files, at least I haven't heard from him in a while.

**Comment by chrisbra** [comment]
So I'll merge it, thanks

**Pull request closed without merging**
