### PR TITLE
filetype: libtool files are not recognized

### PR DESCRIPTION
**Pull request by Freed-Wu**
Problem: Libtool files are not recognized
Solution: recognize libtool files as sh filetype

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks!

**Comment by chrisbra** [comment]
Hm, I have to wonder: Currently those are detected as `conf`  files, and for the few examples I have seen, it seems the `conf` filetype is more appropriate, no?

**Comment by Freed-Wu** [comment]
`libtool` is a program written in sh, which read this files as sh.

However, these files are generated by libtool, which only use simple shell syntax (comment, `var='value'`), so think there are conf is also OK.

**Comment by chrisbra** [comment]
can you then please change it then to make the `conf` filetype explicit?

**Comment by Freed-Wu** [comment]
@ileanadumitrescu95 (libtool maintainer) What is your point?

**Comment by ileanadumitrescu95** [comment]
These are control files that set variables for GNU Libtool to read from. GNU Libtool sources these files with sh for configuration, so either filetype is correct to me.

**Comment by Freed-Wu** [comment]
> GNU Libtool sources these files with sh for configuration

that's why I choose sh :smile:

**Comment by chrisbra** [comment]
yeah, but if I would be editing such a file and see the filetype is detected as `shell` I would assume all shell constructs would be valid and I might be tempted to add those there (after all the syntax supports it). Therefore I'd prefer if we keep it as `conf`

**Comment by Freed-Wu** [comment]
@ileanadumitrescu95 so do you prefer conf, or sh?

**Comment by ileanadumitrescu95** [comment]
> ... either filetype is correct to me.

I do not prefer one or the other

**Comment by Freed-Wu** [comment]
> I would assume all shell constructs would be valid

IMO, all shell syntaxes are valid in `*.la`, ... And treat them as shell can make it easy to use those developer tools for shell. Just my 2c.

**Pull request closed without merging**
