### PR TITLE
update menu for swedish

### PR DESCRIPTION
**Pull request by lesorubshayan**
after merge close https://github.com/vim/vim/pull/10723

### CODE REVIEW

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
Same comment as for #14685 
- Keep the existing Date format style
- Move the added translation to before the line resetting 'cpo' 
- Change the commit author

Thanks!

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
closing for the reasons mentioned here https://github.com/vim/vim/pull/14703#issuecomment-2092337585

**Pull request closed without merging**
