### PR TITLE
Eliminate WIN3264 macro instead of MSWIN

### PR DESCRIPTION
**Pull request by h-east**
~~We use the existing WIN3264 macro instead.~~

Define `FEAT_MSWIN` and `FEAT_GUI_MSWIN`.

Use ~~`FEAT_MSWIN`~~ `MSWIN` instead of `_WIN32`, `WIN32` and `WIN3264`.
Use `FEAT_GUI_MSWIN` instead of `FEAT_GUI_W32`.

### CODE REVIEW

**Comment by brammool** [comment]
> We use the existing WIN3264 macro instead.

We could do it the other way around, use MSWIN instead of WIN3264.
It's shorter and easier to read.

We can probably also use MSWIN instead of WIN32.  There is an OR operation on
WIN32 and _WIN64, but I guess that when _WIN64 is defined WIN32 also is
defined.

So I think we can just use MSWIN nearly everywhere, and only use _WIN64 where
it really has to be the 64 bit version.  All the rest works for both 32 and 64
bit MS-Windows.

-- 
The MS-Windows registry is no more hostile than any other bunch of state
information... that is held in a binary format... a format that nobody
understands... and is replicated and cached in a complex and largely
undocumented way... and contains large amounts of duplicate and obfuscated
information...  (Ben Peterson)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
`WIN32` is undocumented at least. Actually `_WIN32` and `_WIN64` is officially.

**Comment by mattn** [comment]
See https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2017

**Comment by h-east** [comment]
@mattn Thanks!

This microsoft site is written as follows.
- _WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.

This means that the definition below is fine, right?
```c
#ifdef _WIN32
# define MSWIN
#endif
```

Then, we can replace the part directly referencing `WIN32` or `_WIN32` with `MSWIN`, right?

**Comment by k-takata** [comment]
I thought that defining `WIN3264` was redundant, because it is exactly the same as `_WIN32`.
However, one merit for using `WIN3264` is that it can avoid misunderstanding that `_WIN32` doesn't includes `_WIN64` (which is incorrect).
`MSWIN` was used for both Win16 and Win32, but we have already dropped the support for Win16.
So now `MSWIN`, `WIN3264` and `_WIN32` (and also `WIN32`) are all the same.

Using `_WIN32` is a standard way in the Windows programming. So it is straightforward.
However, still there's a risk that someone misunderstands that it doesn't include `_WIN64`. Do we need to care such a case? If so, `MSWIN` might be better.

**Comment by k-takata** [comment]
Bram's comment:
https://groups.google.com/d/msg/vim_dev/XsEQZnQr8Ck/StHpy92xAwAJ

> It is best to separate the dependency on the compiler and Makefile from
> what we use throughout Vim code.  "MSWIN" is the easiest to understand
> for all builds on MS-Windows.  Then we can define it in one place in
> vim.h, depending on _WIN32 or WIN32 (WIN32 is defined in all the
> MS-Windows makefiles).
> 
> We can keep using _WIN64 for 64-bit specific code. 

Okay, let's use `MSWIN` and `_WIN64`.
There is a part which uses `WIN64` in `evalfunc.c`. It can be removed then.

BTW, we have also `FEAT_GUI_W32` and `FEAT_GUI_MSWIN`.
`FEAT_GUI_W32` is defined in the makefiles, and `FEAT_GUI_MSWIN` is defined in `vim.h`.
What do you think of this? Using `FEAT_GUI_MSWIN` is better?

**Comment by brammool** [comment]
> Bram's comment:
> https://groups.google.com/d/msg/vim_dev/XsEQZnQr8Ck/StHpy92xAwAJ
> 
> > It is best to separate the dependency on the compiler and Makefile from
> > what we use throughout Vim code.  "MSWIN" is the easiest to understand
> > for all builds on MS-Windows.  Then we can define it in one place in
> > vim.h, depending on _WIN32 or WIN32 (WIN32 is defined in all the
> > MS-Windows makefiles).
> > 
> > We can keep using _WIN64 for 64-bit specific code. 
> 
> Okay, let's use `MSWIN` and `_WIN64`.
> There is a part which uses `WIN64` in `evalfunc.c`. It can be removed then.
> 
> BTW, we have also `FEAT_GUI_W32` and `FEAT_GUI_MSWIN`.
> `FEAT_GUI_W32` is defined in the makefiles, and `FEAT_GUI_MSWIN` is defined in `vim.h`.
> What do you think of this? Using `FEAT_GUI_MSWIN` is better?

Yes, since it's also used for 64-bit Windows, thus the "32" part is
confusing.  I suppose FEAT_GUI is defined, so we can make it:

	#if defined(FEAT_GUI) && defined(MSWIN)
	# define FEAT_GUI_MSWIN
	#endif

And remove other places where FEAT_GUI_MSWIN is defined.

-- 
System administrators are just like women: You can't live with them and you
can't live without them.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by h-east** [comment]
All right. Thank you!
I have been busy for a few days, so I will work on weekends.
(Unofficial 30% rule can not be used! :grin:)

--
Best regards,
Hirohito Higashi (h_east)

**Comment by h-east** [comment]
I have a question.
Do we still need to support `Make_ivc.mak`?

**Comment by k-takata** [comment]
Recent versions of Visual Studio cannot open `Make_ivc.mak` (and also `Make_dvc.mak`).
I don't think we still need to support them. But is it related to this PR?

**Comment by h-east** [comment]
Yes.  We need `s/FEAT_GUI_W32/FEAT_GUI/g` in Make_ivc.mak

**Comment by brammool** [comment]
Let me know when this is ready to include.

**Comment by h-east** [comment]
My work has been completed, but the impact range is large,
I'm happy if you can have reviews by various people.

**Comment by h-east** [comment]
@mattn, @ntak and Windows developers:
JFYI, Use ~~FEAT_MSWIN~~ MSWIN instead of WIN3264, WIN32 and _WIN32.
And also use FEAT_GUI_MSWIN instead of FEAT_GUI_W32.

Reason:
	https://github.com/vim/vim/pull/3932#issuecomment-462404918
	https://github.com/vim/vim/pull/3932#issuecomment-463183221

**Comment by k-takata** [comment]
Hmm, you defined `FEAT_GUI_MSWIN` and `FEAT_GUI` differently with other platforms.
In other platforms, `FEAT_GUI_GTK` or other platform-specific macros are defined in each makefile, and `FEAT_GUI` is defined in `vim.h`. However you defined `FEAT_GUI` in Windows makefiles, and `FEAT_GUI_MSWIN` in `vim.h`. They are reversed.

**Comment by k-takata** [comment]
> JFYI, Use FEAT_MSWIN instead of WIN3264, WIN32 and _WIN32.

s/FEAT_MSWIN/MSWIN/

**Comment by h-east** [comment]
> They are reversed.

Thank you for your advice.
Indeed, the opposite is true.
I will PR later.

**Pull request closed without merging**
