### PR TITLE
syntax: make: update list of functions for GNU make 4.2

### PR DESCRIPTION
**Pull request by rohieb**
Add functions `$(file)`, `$(guile)` and put `$(subst)` in alphabetical order. Refer to <https://www.gnu.org/software/make/manual/make.html#Functions> for the list.

### CODE REVIEW

**Comment by chrisbra** [comment]
I think the current runtime file is unmaintained. Would you be interested in maintaining it?

**Comment by rohieb** [comment]
> I think the current runtime file is unmaintained. Would you be interested in maintaining it?

Hmm. Why not, shouldn't be too much of a hassle. Should I create another patch in the pull-request to take over maintenance?

**Comment by brammool** [comment]
> > I think the current runtime file is unmaintained. Would you be interested in maintaining it?
> 
> Hmm. Why not, shouldn't be too much of a hassle. Should I create
> another patch in the pull-request to take over maintenance?

Yes please.  And update the header to move the current maintainer to
previous maintainer, and add yourself as maintainer.

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by rohieb** [comment]
Alright, here it is.

**Comment by rohieb** [comment]
@brammool I think this pull request can be merged now, or do you think there are more issues to be solved?

**Comment by brammool** [comment]
It was already included, forgot to close the pull request.

**Comment by rohieb** [comment]
OK thanks :)

**Pull request closed without merging**
