### PR TITLE
Change EndOfBuffer color for desert.vim

### PR DESCRIPTION
**Pull request by EmptiedSoul**

### CODE REVIEW

**Comment by brammool** [comment]
This should most likely go to https://github.com/vim/colorschemes

**Comment by chrisbra** [comment]
ping @romainl @habamax

**Comment by habamax** [comment]
I don't like endofbuffer having different color...

Having said that, legacy desert has the same `EndOfBuffer` (linked to `NonText`)

New Desert has a different `NonText` which some thinks is better than original.

legacy
image

new
image

**Comment by habamax** [comment]
So if the fix is needed, it should be done by changing `NonText`

**Comment by romainl** [comment]
@EmptiedSoul, the remade colorschemes are all generated from templates so it is best to keep eventual changes in the templates.

Could you open an issue in https://github.com/vim/colorschemes/issues so that we work this out over there?

**Comment by chrisbra** [comment]
in that case closing it here then.

**Pull request closed without merging**
