### PR TITLE
Make fixed pipe size

### PR DESCRIPTION
**Pull request by mattn**
Current behavior is slowly since default pipe size is smaller. So make more large size.

### CODE REVIEW

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> Current behavior is slowly since default pipe size is smaller. So make
> more large size.

I can't find info on what the default size would be.  65536 seems a bit
much.  Any reason to pick this size?

This only changes the size for one of the three CreatePipe calls.
It would be helpful to add a comment to explain why that is.

I don't understand the GetOverlappedResult() call, even when reading the
msdn doc.  A comment here would also be helpful.

-- 
hundred-and-one symptoms of being an internet addict:
135. You cut classes or miss work so you can stay home and browse the web.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
Sorry, please wait merge. This patch is still wrong. Anonymous pipe is not managed overlapped I/O.

**Comment by mattn** [comment]
Fixed issue. Now we can raise error when the PIPE is full.

**Comment by mattn** [comment]
@brammool Now I did ultra improve of performance for writing data to channel. For take benchmark, I wrote small program to read data from stdin in golang.

```go
package main

import (
	"flag"
	"log"
	"os"
	"time"
)

func main() {
	var n int
	var s time.Duration
	flag.IntVar(&n, "n", 100, "bytes")
	flag.DurationVar(&s, "s", 100, "sleep")
	flag.Parse()
	b := make([]byte, n)
	for {
		time.Sleep(s)
		if _, err := os.Stdin.Read(b); err != nil {
			log.Fatal(err)
		}
	}
}
```

And Vim script to write to the stdin.

```vim
function! s:test() abort
  let job = job_start(['slow', "-n", "10000", "-s", "0ms"], {'noblock': 1, 'mode': 'raw' })
  let ch = job_getchannel(job)
  let n = 0
  let s = repeat("X", 1024)
  let l = len(s)
  let start = reltime()
  while n < 8192
    call ch_sendraw(ch, s)
    redraw
    let n += l
    echo n
  endwhile
  let seconds = reltimefloat(reltime(start))
  echo "took " . string(seconds) . "s"
endfunction

call s:test()
```
This script show seconds taken for sending 8192bytes to the stdin.

## not applied this patch

namebuf0


Sometimes, gvim hang-up while sending to channel.

namebuf2


## applied this patch

namebuf1

Current implementation use blocking since the pipe is anonymous pipe. This patch use non-blocking with make named-pipe for non-blocking. Below is a screenshot that editing typescript(1.8MB) using vim-lsp.

namebuf0

**Comment by mattn** [comment]
I'll check corner cases for this. Please wait.

**Comment by mattn** [comment]
@brammool Now, this is good to merge.

**Comment by brammool** [comment]
I thought the AppVeyor failure was just flaky, but it fails again now:
From test_terminal.vim:
3212Found errors in Test_terminal_no_cmd():
3213function RunTheTest[40]..Test_terminal_no_cmd[15]..WaitForAssert[2]..<SNR>7_WaitForCommon[11]..<lambda>30 line 1: Pattern 'look here' does not match ''

Can we fix this?

**Comment by mattn** [comment]
```
  if has('win32')
    silent exe '!start cmd /c "echo look here > ' . pty . '"'
  else
    call system('echo "look here" > ' . pty)
  endif
  call WaitForAssert({-> assert_match('look here', term_getline(buf, 1))})
```
I guess that writing pty is not applied immediately. but term_getline return empty string immediately. So we should wait bit more. This is not related on this pull-request, I guess.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> ```
>   if has('win32')
>     silent exe '!start cmd /c "echo look here > ' . pty . '"'
>   else
>     call system('echo "look here" > ' . pty)
>   endif
>   call WaitForAssert({-> assert_match('look here', term_getline(buf, 1))})
> ```
> I guess that writing pty is not applied immediately. but term_getline
> return empty string immediately. So we should wait bit more. This is
> not related on this pull-request, I guess.

No, a sleep doesn't help.  WaitForAssert() already includes a waiting
time.  I also inserted a sleep before the echo command, that doesn't
help either.

-- 
If VIM were a woman, I'd marry her.  Slim, organized, helpful
and beautiful; what's not to like?     --David A. Rogers

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
On my environment (Windows10 64bit), Test_terminal_no_cmd does not fail.

**Comment by mattn** [comment]
@brammool What OS do you use?

namebuf0

**Comment by mattn** [comment]
The test failed on OSX too.

https://travis-ci.org/vim/vim/jobs/481791050

**Comment by brammool** [comment]
> On my environment (Windows10 64bit), Test_terminal_no_cmd does not fail.

I am using Windows 7 and building with MSVC.  Would this matter?

-- 
hundred-and-one symptoms of being an internet addict:
260. Co-workers have to E-mail you about the fire alarm to get
     you out of the building.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>I am using Windows 7 and building with MSVC.  Would this matter?

I'll try this on Windows 7 in monday.

**Comment by mattn** [comment]
Closed by https://github.com/vim/vim/commit/31faed60bfd54ff8f612f6b311a6cbcd9e7ebedd

**Pull request closed without merging**
