### PR TITLE
avoid heavy redrawing cursor

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
@brammool I found another solution. Which do you like?

```diff
diff --git a/src/terminal.c b/src/terminal.c
index 5be51de9f..4ceb57cd9 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -636,7 +636,7 @@ handle_movecursor(
 	}
     }
 
-    if (is_current)
+    if (is_current && visible)
 	update_cursor();
 
     return 1;
```

**Comment by nuko8** [comment]
I found an issue with this PR's (original) patch.

For instance, when I do `cat userfunc.c` on the built-in terminal of a patched Athena, Motif, or GTK+ 2 GUIs, I often see the cursor placed in a wrong position when scrolling is done.

As for the diff that has just posted, I haven't seen the same issue so far.

But, @mattn , I have one thing to make sure about the diff before giving my conclusion: Which HEAD should I apply it to?  As no instructions are given, I applied it to the current master (8.0.0701) and tested it.  But the line number 636 shown in the diff doesn't look like that the diff was made against the current HEAD, which makes me wonder.

Or, does "another solution" mean that we should apply the diff on top of this PR's own patch?

**Comment by mattn** [comment]
Did you try my first patch? or second one? The first patch is based on previous revision. Second one is based on master/HEAD.

Additional:
But maybe both fixes issue as same as.

**Comment by nuko8** [comment]
> Did you try my first patch? or second one?

I did try the first patch and found the issue as I wrote.

> The first patch is based on previous revision. 

Can I have its hash?   I have no idea on what you are referring to "previous revision."

> Second one is based on master/HEAD.

That's the point of my question.  Actually, when I applied the posted patch to my clone repo points to master/HEAD, I got

> patching file terminal.c
> Hunk #1 succeeded at 625 (offset -11 lines).

It looks to me that the offset indicates that the diff was not made against master/HEAD.

**Comment by mattn** [comment]
Sorry. I make you confusing. Okay, I'll rebase from master.

**Comment by nuko8** [comment]
OK, 'cause I have to be AFK for hours, let me leave my conclusion now:

1. While Patch 8.0.0771 has improved the cursor drawing of the GTK+ 2 GUI much and made its built-in terminal as usable as that of the GTK+ 3 GUI, it has made scrolling of the latter GUI noticeably clumsy.
2. If we merge @mattn 's second patch into the current master/HEAD (1c84493bb) with leaving his first patch out, then it not only makes scrolling of the former GUI much smoother but also makes that of the latter GUI as smooth as pre-8.0771 versions.
3. Even with the second patch included, the Athena and Motif GUIs still needs further improvement on their cursor drawing and movement.

Therefore, though I'm still unsure whether or not the second patch was made against master/HEAD and whether or not the executables resulting from the codebase of his repo which was used to make it are the same as those I have and were tested properly,  I vote against the first patch and for the second patch, based on my own test result.

**Comment by mattn** [comment]
@nuko8 Thanks for your review.  As you mentioned about patch 8.0.0771, the cursor had appear in right location immediately. However, when lines are scrolled-up, cursor flicker many times. This patch is the avoid redrawing. To update cursor smooth, it should not call gui_update_cursor in many part. And it call gui_update_cursor at handle_movecursor while visible is true.

**Comment by nuko8** [comment]
@mattn 

Thank you for the clarification.   Now I see the issue better and confirm that your second patch works just like you described.  I highly appreciate your work on it as well as your recent intensive work on other part of the built-in terminal, helping Bram.  Keep up the good work!

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> @brammool I found another solution. Which do you like?
> 
> ```diff
> diff --git a/src/terminal.c b/src/terminal.c
> index 5be51de9f..4ceb57cd9 100644
> --- a/src/terminal.c
> +++ b/src/terminal.c
> @@ -636,7 +636,7 @@ handle_movecursor(
>  	}
>      }
>  
> -    if (is_current)
> +    if (is_current && visible)
>  	update_cursor();
>  
>      return 1;
> ```

We should store the property for the cursor visibility.
I'll merge it in.

-- 
hundred-and-one symptoms of being an internet addict:
246. You use up your free 1 Gbyte in two days.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> -- Commit Summary --
> 
>   * avoid heavy redrawing cursor
> 
> -- File Changes --
> 
>     M src/terminal.c (19)

Thanks.  I found one place a flush is still needed, otherwise the screen
is not updated after ":term ls" ends.

-- 
hundred-and-one symptoms of being an internet addict:
247. You use www.switchboard.com instead of dialing 411 and 555-12-12
     for directory assistance.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
