### PR TITLE
Fix some SEGV related to null_object.

### LINKED ISSUE #15338: [vim9class] REGRESSION: SEGV using a null_object
### Steps to reproduce

```
vim9script

def X()
    var x = null_object
    echom x
enddef
X()
```
Bisecting  indicates
https://github.com/vim/vim/commit/3164cf8f12f14b725b918e3170bb0a9085af8298
```
date:        Thu Mar 28 10:36:42 2024 +0100
summary:     patch 9.1.0219: Vim9: No enum support
```

### Expected behaviour

No exception, error message like
```
E1324: Using an Object as a String
```
Not all uses of null_object have this problem

### Version of Vim

9.1.611

### Environment

ubuntu gtk3

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by errael**
Fix #15338 plus 3 more SEGV.

The #15338 part of the fix is by @chrisbra .

### CODE REVIEW

**Comment by errael** [comment]
The failure for the test `# Do "echom" of a null object variable.` displays the wrong line number.
One of the changes, typval.c around line 269 `tv_get_bool_or_number_chk(` has no test.

**Review by yegappan — APPROVED** [review]

**Comment by errael** [comment]
Updated PR to fix the wrong line number for `# Do "echom" of a null object variable`

**Comment by chrisbra** [comment]
thanks!

**Comment by errael** [comment]
One more update on the way. Found a way to test the last untested change.

**Comment by errael** [comment]
OK. All the changes have a test that would previously SEGV.

**Pull request closed without merging**
