### PR TITLE
Add Haskell completion function

### PR DESCRIPTION
**Pull request by alx741**
Haskell omni completion for:

- GHC language extensions
- GHC dynamic options
- Core package's modules

### CODE REVIEW

**Comment by brammool** [comment]
Doesn't this require a plugin to set it up?  Or at least documentation how to use it?

**Comment by alx741** [comment]
Indeed, `setlocal omnifunc=haskellcomplete#Complete` is needed, ideally in the current `ftplugin/haskell.vim` but it would be necessary for this plugin to be already in place before asking the maintainer to add that line so it doesn't use an omni function that doesn't yet exist in the runtime.

Or, if it is ok, I could add that line to `ftplugin/haskell.vim` my self and include it in this PR, please let me know if that's the thing to do.

Edit: I added a *usage* line just in case that's enough for now

**Comment by brammool** [comment]
> Indeed, `setlocal omnifunc=haskellcomplete#Complete` is needed,
> ideally in the current `ftplugin/haskell.vim` but it would be
> necessary for this plugin to be already in place before asking the
> maintainer to add that line so it doesn't use an omni function that
> doesn't yet exist in the runtime.
> 
> Or, if it is ok, I could add that line to `ftplugin/haskell.vim` my
> self and include it in this PR, please let me know if that's the thing
> to do.

Looks like the maintainer of that ftplugin has retired.
Perhaps you can take it over?

-- 
For humans, honesty is a matter of degree.  Engineers are always honest in
matters of technology and human relationships.  That's why it's a good idea
to keep engineers away from customers, romantic interests, and other people
who can't handle the truth.
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by alx741** [comment]
Sure, that last change should do it then; So Haskell omni completion works out of the box, no user config required.

**Comment by brammool** [comment]
Thanks, I'll include it now

**Pull request closed without merging**
