### PR TITLE
ci.yml: get rid of snap

### PR DESCRIPTION
**Pull request by pheiduck**
seems to be a bottleneck for CI

### CODE REVIEW

**Comment by chrisbra** [comment]
How much faster is this?

**Comment by pheiduck** [comment]
My intention was to prevent snap upgrades due it was hanging yesterday on a CI job.

**Comment by pheiduck** [comment]
> How much faster is this?

 17m 3s compared to  [21m 54s](https://github.com/vim/vim/actions/runs/7718380848)

**Comment by chrisbra** [comment]
oh cool. I guess technically, we don't need the `systemctl disable` command? and the `rm -rf` to clean up the snap directories?

**Comment by pheiduck** [comment]
Okay CI Time is now: 16m 25s very nice.

**Pull request merged**
