### PR TITLE
fix: fuzzy completion

### PR DESCRIPTION
**Pull request by mg979**
Simpler alternative to #15193.

How it works: when using fuzzy completion, the completion leader is cut down to 1 character (if longer), the rest is stored in a "fuzzy completion leader" that is inserted later, as if the user typed it, so that the popup menu shows all matches that start with the leader and match (fuzzily) the rest of the characters.

Note that I'm using a trick to have the popup updated (simulating an additional inserted character, followed by a backslash).

### CODE REVIEW

**Comment by mg979** [comment]
fuzzy3

@glepnir @chrisbra @habamax please test/have a look.

**Comment by glepnir** [comment]
Once again, regex cannot handle fuzzy.

**Comment by mg979** [comment]
> Once again, regex cannot handle fuzzy. Spend some time understanding what fuzzy is

Just in case you take it back again.

**Comment by chrisbra** [comment]
I guess we can close this one then.

**Pull request closed without merging**
