### PR TITLE
Fix issues with specfile plugin and stop adding variable names to changelog message

### LINKED ISSUE #3842: Specfile filetype plugin is not working properly
Hi,
spec filetype plugin is not expanding variables.
Steps to reproduce:
1. change type of file from .spec.txt to .spec
[reproduce.spec.txt](https://github.com/vim/vim/files/2783943/reproduce.spec.txt)
2. open spec file in vim
3. press \c and enter your name
expected result:
new changelog message is created with version info 1.5-1
actual result:
new changelog message is created with version info 1.-1

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1297746

### LINKED ISSUE #3843: Specfile filetype plugin should not copy variable names of undefined variables to changelog message
Hi,
In my opinion it is better to not mention variable names of variables which are undefined in specfile in changelog message. Take for example variable ?dist which is defined during a build and if you are using changelog generation then you have to remove it from messages version info manually every time.
Let me please know what you think about this.

### PR DESCRIPTION
**Pull request by TomasKorbar**
resolves #3843 
resolves #3842 
Please see issues and commit messages for more info.

### CODE REVIEW

**Comment by k-takata** [comment]
Have you contact the maintainer?

**Comment by TomasKorbar** [comment]
No. I'm sorry this is my first contribution to vim. I will contact him right away.

**Review by Sarayutnang2099 — APPROVED** [review]

**Comment by brammool** [comment]
Closing, since this is not something to include.  If the maintainer does not respond consider taking over maintenance.  Then re-open the pull request (or create a new one).

**Comment by igor-raits** [comment]
LGTM

**Comment by brammool** [comment]
I'll include it then.

**Pull request closed without merging**
