### PR TITLE
Minor grammar change

### PR DESCRIPTION
**Pull request by TheProdigyLeague**
please consider revise

### CODE REVIEW

**Comment by chrisbra** [comment]
It is quite common in the help files to have 2 spaces after a sentence. It doesn't seem to make a difference for the rendered Markdown file. So let's just keep it how it is.

**Review by TheProdigyLeague — COMMENTED** [review]
Line: 90 should at the very least be "The best thing to use is" instead of the literal "The best is to use is" Bro didn't even read my PR.

**Comment by chrisbra** [comment]
Bro, I did read your PR. And I think, when looking for documentation, "the best is to use `:help`" may sound a bit strange at first but is quite right.

**Comment by TheProdigyLeague** [comment]
> Bro, I did read your PR. And I think, when looking for documentation, "the best is to use `:help`" may sound a bit strange at first but is quite right. 

> The best is to use :help
> The best is to use
> The best is to
> The best is

**The best thing to use is :help**

**Pull request closed without merging**
