### PR TITLE
Add support for abstract methods.

### PR DESCRIPTION
**Pull request by yegappan**
Add support for defining abstract methods in an abstract class (#13044)

### CODE REVIEW

**Comment by dkearns** [comment]
Thanks @yegappan 

I'll give it a run tomorrow when I'm back at a dev box.

**Comment by dkearns** [comment]
Thanks again, it looks good to me at first blush.

I did, however, notice that an abstract class is not allowed to define constructors which seems odd but maybe it makes sense given the way super-class constructors are, IIRC, entirely inaccessible from the base class.

I'll open a separate issue for that, if required, when I've made more sense of it.

**Comment by yegappan** [comment]
> 
> I did, however, notice that an abstract class is not allowed to define constructors 
> which seems odd but maybe it makes sense given the way super-class constructors
> are, IIRC, entirely inaccessible from the base class.
> 

As you cannot instantiate an abstract class, constructors are not supported in an abstract class.

**Comment by dkearns** [comment]
Right but that is abnormal in terms of the design-inspiring languages.  It would be a natural consequence of this:

> Unlike other languages, the constructor of the base class does not need to be
> invoked.  In fact, it cannot be invoked.  If some initialization from the base
> class also needs to be done in a child class, put it in an object method and
> call that method from every constructor().

**Pull request closed without merging**
