### PR TITLE
Update dircolors.vim

### PR DESCRIPTION
**Pull request by DarkStar1973**
Fix xterm bug wich replace first character with 'g' when editing file

### CODE REVIEW

**Comment by chrisbra** [comment]
please contact the syntax script maintainer and discuss the issue with him. Thanks.

**Comment by janlarres** [comment]
(I'm the maintainer)

This doesn't look right to me. First of all that function should only be called in GVim, not in xterm, since it checks `has('gui_running')`. And second, the `r` and `b` values don't make sense at that point in the code – they are only used by the preceding loop. The values that the loop in question sets are greyscale values where all of the components are supposed to be the same (I guess that part could have benefited from a comment).

Are you saying that the code is running for you even in xterm? And if yes, could you please give some more information about how exactly this can be reproduced?

**Comment by DarkStar1973** [comment]
Ok, i explain.
Excuse me i'm french, so my english isn't perfect.
Me and colleague at work have a bug with vim since ubuntu xenial (same with debian sid).
When we open a file, after a short delay the first character is replace by the character 'g', with TERM=xterm. 
So i try to find why. And when i see your code i was thinking you made a mistake (ggg instead of rgb). But with this patch, i don't have the bug of first character replace by g.

**Comment by vim-ml** [comment]
Hi DarkStar1973,

2016-5-31(Tue) 16:47:02 UTC+9 DarkStar1973:

> Ok, i explain.
> 
> Excuse me i'm french, so my english isn't perfect.
> 
> Me and colleague at work have a bug with vim since ubuntu xenial (same with debian sid).
> 
> When we open a file, after a short delay the first character is replace by the character 'g', with TERM=xterm. 
> 
> So i try to find why. And when i see your code i was thinking you made a mistake (ggg instead of rgb). But with this patch, i don't have the bug of first character replace by g. 

What version of Vim are you using?
What terminal emulator are you using?
When you using Vim version from 7.4.757 to 7.4.769, A problem occurs that you have reported.

Please see the following threads.

Issue 381 in vim: 'nocompatible' in vimrc causes the first char changed to 'g'
https://groups.google.com/d/msg/vim_dev/JB0oocqMel8/ml6ayeSmLnsJ

FS#45535 - [vim] latest version inserting g character upon opening file looks still broken
https://groups.google.com/d/msg/vim_dev/_Q26KGKB5nk/YtUM0QA9aFMJ

Patch 7.4.757
https://groups.google.com/d/msg/vim_dev/LLGjKaEzNUY/z8WvrFoxtD0J

Patch 7.4.770
https://groups.google.com/d/msg/vim_dev/BTuBkjUcoUw/KHtRSyXiRk8J

## 

Best regards,
Hirohito Higashi (a.k.a. h_east)

**Comment by chrisbra** [comment]
looks invalid, closing. If you still have the problem, please send a mail to vim-dev list, stating your environment (terminal, vim version) and we'll try to reproduce/fix it

**Pull request closed without merging**
