### PR TITLE
change hl_group to hlgroup of complete function

### PR DESCRIPTION
**Pull request by glepnir**
Problem: hl_group looks not great with kind_hlgroup.

Solution: change to hlgroup.

### CODE REVIEW

**Comment by glepnir** [comment]
or change to abbr_hlgroup and then only abbr has stripethrough ?

**Comment by Shane-XB-Qian** [comment]
> or change to abbr_hlgroup and then only abbr has stripethrough ? 

had said here: https://github.com/vim/vim/pull/15561#issuecomment-2308661282
or if you now really like to separate it, then maybe 'label_hlgroup' was a good name.

// BTW: you changed not only 'runtime(doc)', but also 'c' code, so the ticket title was confused.

-- 
shane.xb.qian

**Comment by glepnir** [comment]
label is lsp side.  rename to abbr_hlgroup or other name_hlgroup  need modifi some c code so it's next follow-up PR.

**Comment by Shane-XB-Qian** [comment]
> label is lsp side.  rename to abbr_hlgroup or other name_hlgroup  need modifi some c code so it's next follow-up PR.

'abbr' is another well know native cmd in vim, that maybe confused, so i suggested 'label';
but that is not the point, the point is how to design the hl and their belonging/priority;
if you would not make PmenuKindSel *not* be override by PmenuKind (as above my comment said), then this PR the name changing seems would not change or help something.
// BTW: it is not regarding to lsp always, it just some hl which users may like to set (or not).

-- 
shane.xb.qian

**Comment by glepnir** [comment]
word abbr respect complete-items and please do not raise unrelated issues under PR. If you have a problem with how kind works, please create an issue instead of sending a comment under an unrelated PR. I handle hlgroup issues here

**Comment by Shane-XB-Qian** [comment]
> word abbr respect complete-items and please do not raise unrelated issues under PR. If you have a problem with how kind works, please create an issue instead of sending a comment under an unrelated PR. I handle hlgroup issues here

i am saying the related issue, hl_group impacted kind_hlgroup, now hl_group striked 'kind' area too if set that.
// but well, if you are not like to listen, that's fine, i donot mind.. good luck for this topic~

-- 
shane.xb.qian

**Pull request closed without merging**
