### PR TITLE
Added sbt syntax highlighting.

### PR DESCRIPTION
**Pull request by ghost**
SBT is Scala's default build tool. It's a DSL written in Scala with some special keyword.

### CODE REVIEW

**Comment by ghost** [comment]
What's wrong with this coverage tool?

**Comment by chrisbra** [comment]
I think because of the failure in travis-ci the coverge information could not be updated. The failure shouldn't be related to your fix I believe. try to force push again, this should trigger a re-build (and hopefully update the coverage information correctly.

**Comment by ghost** [comment]
-0.004% coverage?

**Comment by ghost** [comment]
> Thanks.
 In the ftplugin and syntax file you source the Scala file.  Is that
 really correct?  I would thing Scala and its build file are different
 enough filetypes. Or can any Scala command be used in a .sbt file?
-  Bram Moolenaar on google groups(https://groups.google.com/forum/#!topic/vim_dev/9XtNuHQ4jJs)

Yes, .sbt files are Scala sources too but the build tool imports a few modules to make it look like a different DSL.

**Comment by brammool** [comment]
The ftplugin file does: "+let b:did_ftplugin = 1"
This means that the "runtime! ftplugin/scala.vim" most likely doesn't do anything.

The syntax file does not set "b:current_syntax", thus it will be set to "scala".  But the syntax does have differences, thus it's better to set to "sbt".

Perhaps also include an indent file?

**Comment by brammool** [comment]
The author of this pull request has disappeared.

**Pull request closed without merging**
