### PR TITLE
CI: use gcc builds on arm64 as well (Mac m1)

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by ichizok** [comment]
Pre-installed gcc (`/usr/bin/gcc`) is identical to clang.

https://cirrus-ci.com/task/5570503493550080 (at "Run build" phase)

```
gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.201)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by brammool** [comment]
> Pre-installed gcc (`/usr/bin/gcc`) is identical to clang.
> 
> https://cirrus-ci.com/task/5570503493550080 (at "Run build" phase)
> 
> ```
> gcc --version
> Apple clang version 14.0.0 (clang-1400.0.29.201)
> Target: arm64-apple-darwin22.1.0
> Thread model: posix
> InstalledDir: /Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```

Does this mean nobody uses the real gcc on this platform?
Then there is no point in running tests with it.

-- 
Facepalm statement #4: "3000 year old graves?  That's not possible, it's only
2014!"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ichizok** [comment]
> Does this mean nobody uses the real gcc on this platform?
> Then there is no point in running tests with it.

Yes; referred at #9326.

**Comment by brammool** [comment]
> > Does this mean nobody uses the real gcc on this platform?
> > Then there is no point in running tests with it.
> 
> Yes; referred at #9326.

Obviously we forgot about that.

Can we revert the change or is there still something useful in it?
We should at least add a comment to avoid this from happening again.

-- 
Facepalm statement #8: "Drive faster, the petrol is running out"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
