### PR TITLE
runtime(doc): Update change.txt

### PR DESCRIPTION
**Pull request by k-takata**
Fix e06f2b498ccca921f34a1bec4464f042a5a2cabd.

### CODE REVIEW

**Comment by k-takata** [comment]
The updated paragraph should be accurate than before. (I'm not sure whether this paragraph is useful, though.)

**Comment by chrisbra** [comment]
Thanks! I think it is better than before. Please also update the last Change Header.

**Comment by k-takata** [comment]
done

**Comment by chrisbra** [comment]
thanks!

**Pull request merged**
