### PR TITLE
[WIP] add eval functions for terminal

### PR DESCRIPTION
**Pull request by mattn**
* [x] add term_getattr(buf)
* [x] add term_getsize(buf)
* [x] add term_getline(buf, row)
* [x] add term_list()
* [x] add term_sendkeys(buf, keys)
* [ ] add term_wait(buf)
* [x] add term_scrape(buf, row)
* [ ] add term_start(command, options)
* [x] add term_getjob(buf)

### CODE REVIEW

**Comment by mattn** [comment]
@brammool Why the number of arguments in term_setsize is only one? Just request current size? Also do you have plan for options in term_open? what behavior of term_wait?

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> * [ ] add term_list()
> * [ ] add term_getsize(buf)
> * [ ] add term_setsize(buf)
> * [ ] add term_sendkeys(buf, keys)
> * [ ] add term_wait(buf)
> * [ ] add term_scrape(buf, row)
> * [ ] add term_open(command, options)
> * [ ] add term_getjob(buf)

Nice, thanks.

A few remarks from a quick look:

perhaps term_start() is better than term_open()?
Like we have job_start().

The core of term_scrape() should be in terminal.c.
This also needs to handle multi-byte characters.
And soon we'll need the attributes (color, bold, underline, etc.).

term_sendkeys() should work like terminal_loop(), converting Vim keys to
terminal escape sequences.  Well, we could do both raw and converted,
but converted would be the most useful.

-- 
hundred-and-one symptoms of being an internet addict:
241. You try to look for Net Search even when you're in File Manager.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> @brammool Why the number of arguments in term_setsize is only one?
> Just request current size? Also do you have plan for options in
> term_open? what behavior of term_wait?

Thanks for working on this!

The documentation needs to be updated, I only wrote some placeholders.

term_setsize() might interfere with 'termsize', need to think about 
what to do here.  Perhaps we only need 'termsize'.

Options would probably a subset of what job_start() has.  "pty" would
default to "1", and some options must be forced, such as output must go
to the terminal.

term_wait() would be used in tests to wait for the terminal to have
updated according to the job running in it.  Probably it would wait for
the channel on the job to have caught up with buffered messages.
Need to write a first test to be able to try out what works.

-- 
hundred-and-one symptoms of being an internet addict:
240. You think Webster's Dictionary is a directory of WEB sites.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
> Options would probably a subset of what job_start() has.  "pty" would
> default to "1", and some options must be forced, such as output must go
> to the terminal.

I wonder that options should be subset of what job_start has. Is it to be
options to make terminal, right? For example:

```
call term_start(&shell, {"rows": 25, "cols": 80})
```

> term_wait() would be used in tests to wait for the terminal to have
> updated according to the job running in it.  Probably it would wait for
> the channel on the job to have caught up with buffered messages.
> Need to write a first test to be able to try out what works.

I guess this is an API which may block forever. Most easy way to do is
add global variable to set/reset to detect output at term_write_job_output.
Am I something wrong?

**Comment by mattn** [comment]
> The core of term_scrape() should be in terminal.c.
> This also needs to handle multi-byte characters.
> And soon we'll need the attributes (color, bold, underline, etc.).

Do you mean it should return list which can get from vterm_screen_get_cell ?

**Comment by brammool** [comment]
> > The core of term_scrape() should be in terminal.c.
> > This also needs to handle multi-byte characters.
> > And soon we'll need the attributes (color, bold, underline, etc.).
> 
> Do you mean it should return list which can get from
> vterm_screen_get_cell ?

Probably we will want that for checking attributes.
Perhaps return [char, attr, fg, bg] and have a nice way to deal with
attr, e.g.: term_getattr(attr, 'bold')
Using a dict would be nicer, but add a lot of overhead.

For text it would be easier to just get the text.
Perhaps we can use term_getline() for that.

-- 
Vi is clearly superior to emacs, since "vi" has only two characters
(and two keystrokes), while "emacs" has five.  (Randy C. Ford)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
I implemented term_scrape return following structure.

```
[
  {
    "bg": {
      "blue": 0,
      "green": 0,
      "red": 0
    },
    "fg": {
      "blue": 240,
      "green": 240,
      "red": 240
    },
    "char": "あ"
  },
  {
    "bg": {
      "blue": 0,
      "green": 0,
      "red": 0
    },
    "fg": {
      "blue": 240,
      "green": 240,
      "red": 240
    },
    "char": "い"
  },
  ...
]
```
The list which elements is located in fixed position makes user confusing, I guess.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> I implemented term_scrape return following structure.
> 
> ```
> [
>   {
>     "bg": {
>       "blue": 0,
>       "green": 0,
>       "red": 0
>     },
>     "fg": {
>       "blue": 240,
>       "green": 240,
>       "red": 240
>     },
>     "char": "あ"
>   },
>   {
>     "bg": {
>       "blue": 0,
>       "green": 0,
>       "red": 0
>     },
>     "fg": {
>       "blue": 240,
>       "green": 240,
>       "red": 240
>     },
>     "char": "い"
>   },
>   ...
> ]
> ```
> The list which elements is located in fixed position makes user
> confusing,  I guess.

The thing is that dictionarnies are very expensive, both in memory use
and time to create them.  Lists are cheaper.
Since this structure is used for every single cell, of which there would
be thousands, this can slow down the functions a lot.

Dictionaries are easier to read though.  Perhaps a good compromise is to
use one dictionary per cell, and do the rest with lists and strings.

It's common enough to have RGB, so we can use a list with [r, g, b].

So the result for one cell could be:
   [{'bg': [0, 240, 0], 'fg': [3, 0, 255], 'char': 'Xcc', 'attr': 34]

The 'char' value is one character plus its composing characters.

The 'attr' value is a number, we can use a function to get out each
separate attribute, such as bold, underline, etc.

-- 
hundred-and-one symptoms of being an internet addict:
254. You wake up daily with your keyboard printed on your forehead.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
How about the format like `#FFBBDD` for fg/bg?

**Comment by mattn** [comment]
@brammool How about this?

```
[
  {
    "bg": "#000000",
    "fg": "#240240",
    "char": "あ",
    "attr": 179
  },
  {
    "bg": "#000000",
    "fg": "#240240",
    "char": "い",
    "attr": 179
  }
  ...
},
```

**Comment by brammool** [comment]
Yasuhiro wrote:

> @brammool How about this?
> 
> ```
> [
>   {
>     "bg": "#000000",
>     "fg": "#240240",
>     "char": "M",
>     "attr": 179
>   },
>   {
>     "bg": "#000000",
>     "fg": "#240240",
>     "char": "i",
>     "attr": 179
>   }
>   ...
> },
> ```

Yeah, that should work.  I would use "chars" instead of "char", to give
a hint that it might be more than one character.  Vterm can return up to
six.

-- 
If VIM were a woman, I'd marry her.  Slim, organized, helpful
and beautiful; what's not to like?     --David A. Rogers

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
