### PR TITLE
proposal: Add extended version of readdir()

### PR DESCRIPTION
**Pull request by k-takata**
This PR adds a function named readdirex() which is an extended version of the readdir() function.
This retrieves a list of files in a directory along with their attributes.

This might be useful when implementing file managers like Netrw.

This is much faster than calling readdir() to get a list, then calling
getfperm(), getfsize(), getftime() and getftype() for each file to get the
attributes, especially on MS-Windows.

### CODE REVIEW

**Comment by k-takata** [comment]
Benchmarks on MS-Windows:

1. readdir() only

```vim
" dirlist0.vim
func! Dirlist(d = '.')
  new
  let start = reltime()
  setlocal buftype=nofile
  let list = readdir(a:d)

  call append(line('$'), list)
  call append(line('$'), reltimestr(reltime(start)))
endfunc

call Dirlist('c:/windows/system32')
```

dirlist0.vim just lists the files in `c:/windows/system32`.
This takes about 0.02 sec in my environment.
(The number of files in the directory is about 4600.)

2. readdir() + getf????()

```vim
" dirlist1.vim
func! Dirlist(d = '.')
  new
  let start = reltime()
  setlocal buftype=nofile
  let pwd = chdir(a:d)
  let list = readdir('.')
  for f in list
    call append(line('$'), printf("%-20s", f) .. "\t"
	  \ .. printf("%-7s", getftype(f)) .. " "
	  \ .. printf("%10u", getfsize(f)) .. " "
	  \ .. strftime("%Y-%m-%d %T", getftime(f)) .. " " .. getfperm(f))
  endfor
  if pwd != ''
    call chdir(pwd)
  endif
  call append(line('$'), reltimestr(reltime(start)))
endfunc

call Dirlist('c:/windows/system32')
```

dirlist1.vim lists the files and their attributes using readdir() and
getf????() functions.
This takes about 2.6 sec in my environment. (130x slower than dirlist0.vim.)

3. readdirex()

```vim
" dirlist3.vim
func! Dirlist(d = '.')
  new
  let start = reltime()
  setlocal buftype=nofile
  let list = readdirex(a:d)

  for l in list
    call append(line('$'), printf("%-20s", l.name) .. "\t"
	  \ .. printf("%-7s", l.type) .. " "
	  \ .. printf("%10u", l.size) .. " "
	  \ .. strftime("%Y-%m-%d %T", l.time) .. " " .. l.perm)
  endfor
  call append(line('$'), reltimestr(reltime(start)))
endfunc

call Dirlist('c:/windows/system32')
```

dirlist3.vim uses the new function readdirex() to list the files and their
attributes.
This takes about 0.09 sec in my environment.
(4.5x slower than dirlist0.vim, but ~30x faster than dirlist1.vim.)

The scripts are also available at
https://gist.github.com/k-takata/63b561c9b876d9e8d26fdc73438e8842 .

**Comment by k-takata** [comment]
Another benchmarks on MS-Windows:

1. readdir()

```vim
" time-readdir.vim
let start = reltime()
echo len(readdir("c:/windows/system32"))
echo reltimestr(reltime(start))
```

This takes about 0.02 sec.

2. readdirex()

```vim
" time-readdirex.vim
let start = reltime()
echo len(readdirex("c:/windows/system32"))
echo reltimestr(reltime(start))
```

This takes about 0.03 sec.
Only 1.5x slower than readdir().
Overhead of creating dictionary for each file is not so big.

**Comment by k-takata** [comment]
On Unix, we can use readdir(), then stat() or lstat() for each file to get a list of
files and their attributes.

On MS-Windows, we use FindFirstFile() and FindNextFile() APIs to get a list of
files in a directory. These APIs return not only the names but also their
attributes. Moreover, stat() in MS-Windows is implemented by using
FindFirstFile(). So, using readdir() then stat() is a waste of time.

**Comment by k-takata** [comment]
I forgot to commit documents. Updated.

**Comment by lacygoill** [comment]
Would it be possible for the dictionary returned by `readdirex()` to include an `owner` key for the owner of the file, and a `group` key for its group?

**Comment by k-takata** [comment]
That may be easy on Unix, because lstat() returns st_uid and st_gid, and their name can be get by getpwuid() and getgrgid(). It may not have much performance penalty.
OTOH, that may not be so easy on Windows, because FindFirstFile() doesn't return such information.
It might be better to support them only on Unix.

**Comment by prabirshrestha** [comment]
Should there instead be an async version of this that uses async io under the hood?

**Pull request closed without merging**
