### PR TITLE
Implemented :redrawruler

### PR DESCRIPTION
**Pull request by ghost**
I just wanted to update the ruler safely.
It seems to be possible to simply redraw, but since the character being input to IME on vim.exe is not restored by redraw, it is not redrawn while using IME.

Now I am displaying the clock like this.
```
set ruler
set rulerformat=%=%{strftime('%H:%M:%S')}
function! UpdateRuler(...)
    execute('silent! redrawruler!')
endfunction
call timer_start(1000, 'UpdateRuler', {'repeat': -1})
```

### CODE REVIEW

**Comment by brammool** [comment]
I'm a bit surprised makefile changes are needed for :redrawruler.
Also, perhaps the cygwin/mingw makefile also needs a change?
Help text for the new command is missing.

**Comment by ghost** [comment]
I did so because imm32.lib was needed for vim.exe.
There is no way to redraw the input character in IME that disappeared by redraw, and stop updating during IME input. It came to this code for detection.

In cygwin/mingw, suppress IME detection with __GNUC__. The string disappears only in cmd.exe.

**Comment by brammool** [comment]
Looks like in the help some words are missing: 
+:redrawr[uler][!]	Redraw the ruler of the current window. When ! is
+			included all rulers are redrawn.
+			'rulerformat' includes an item that doesn't cause
+			automatic updating.

Perhaps insert "This is useful if" before 'rulerformat' ?

Now it would be nice to have a test.  I suppose ":redrawstatus" also isn't fully covered.
Perhaps a screendump would be the easiest to see what happens.

**Comment by chrisbra** [comment]
closing this as the original user has been deleted and there seems to be a bit of unrelated changes.

**Pull request closed without merging**
