### PR TITLE
Stop directory doesn't work properly in 'tags'

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  Stop directory doesn't work properly in 'tags'.
Solution: Also move the stop directory forward by one byte.

related: #15200

### CODE REVIEW

**Comment by jessepav** [comment]
Thanks for the quick turnaround! There's one issue with this patch:

The stopdir works properly only if it ends with a trailing slash `/` (which `fnamemodify()` happens to include).  If the stopdir doesn't end with a slash, searching will continue one directory too far up the tree.

**Comment by chrisbra** [comment]
Ah, it seems there is yet another bug. I think we need this one on top of the path:
```diff
diff --git a/src/findfile.c b/src/findfile.c
index 263660925..59ab37c69 100644
--- a/src/findfile.c
+++ b/src/findfile.c
@@ -1078,11 +1078,13 @@ vim_findfile(void *search_ctx_arg)
                && search_ctx->ffsc_stopdirs_v != NULL && !got_int)
        {
            ff_stack_T  *sptr;
+           // path_end may point to the NUL or the previous path separator
+           int plen = (path_end - search_ctx->ffsc_start_dir +
+                   (*path_end != NUL));

            // is the last starting directory in the stop list?
            if (ff_path_in_stoplist(search_ctx->ffsc_start_dir,
-                      (int)(path_end - search_ctx->ffsc_start_dir),
-                      search_ctx->ffsc_stopdirs_v) == TRUE)
+                      plen, search_ctx->ffsc_stopdirs_v) == TRUE)
                break;

            // cut of last dir
```

**Comment by zeertzjq** [comment]
That doesn't seems to be the correct solution, and `ff_path_in_stoplist()` already does that:
```c
    // eat up trailing path separators, except the first
    while (path_len > 1 && vim_ispathsep(path[path_len - 1]))
	path_len--;
```

**Comment by zeertzjq** [comment]
I added a fix for the problem with trailing slash in another commit.

**Comment by chrisbra** [comment]
> That doesn't seem to be the correct solution, and ff_path_in_stoplist() already does that:

That is correct, but it doesn't work correctly, because the length calculation in `vim_findfile()` is wrong. On the first iteration, path_end points to the NUL, so `path_end - ffsc_start_dir` gives the correct length of the directory, so that in `ff_path_in_stoplist()` `path[path_len-1]` correctly points to the trailing slash.

However in subsequent iterations,  `path_end` points to the last (, second last, etc) path delimiter of `ffsc_start_dir` and as such the length calculation `path_end - ffsc_start_dir` is off by one, so that one would need to check `path[path_len]` if this points to the directory delimiter

**Comment by chrisbra** [comment]
> This doesn't support relative stop directories yet, as they are not
supported in other places like findfile() either.

BTW: can't we simply convert the relative path to an absolute path then?

**Comment by zeertzjq** [comment]
> > That doesn't seem to be the correct solution, and ff_path_in_stoplist() already does that:
> 
> That is correct, but it doesn't work correctly, because the length calculation in `vim_findfile()` is wrong. On the first iteration, path_end points to the NUL, so `path_end - ffsc_start_dir` gives the correct length of the directory, so that in `ff_path_in_stoplist()` `path[path_len-1]` correctly points to the trailing slash.
> 
> However in subsequent iterations, `path_end` points to the last (, second last, etc) path delimiter of `ffsc_start_dir` and as such the length calculation `path_end - ffsc_start_dir` is off by one, so that one would need to check `path[path_len]` if this points to the directory delimiter

I don't think the length is the problem here. In `ff_path_in_stoplist()`, when `path_len` is no larger than the length of the stopdir, it uses `fnamecmp()` to compare, which may actually compare beyond `path_len` until the `NUL`.

**Comment by chrisbra** [comment]
But in any case, removing the path separator doesn't work properly, because the length is wrong.

**Comment by zeertzjq** [comment]
Oh, I see. The value of `path_len` isn't too large. It's too small.

**Comment by zeertzjq** [comment]
I added another commit to expand relative paths. However, only `tag;../` works, `tag;..` doesn't.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
