### PR TITLE
Increase max number of items in statusline

### PR DESCRIPTION
**Pull request by romgrk**
Vim throws `E541` when there are too many items in the tabline or statusline, which happens often when using tabline or statusline plugins. This PR increase the number of items from 80 to 300. I have chosen 300 because it seems like a fine number to me, isn't exagerated in terms of memory, and will probably satisfy the needs of everyone. Also because I want to stop seing that error therefore an arbitrary number is better than the current *status quo*.

Example: https://github.com/itchyny/lightline.vim/issues/220

### CODE REVIEW

**Comment by tonymec** [comment]
I wonder how you come to more than 80 statusline items. How wide is your screen? Here, in full-screen mode, gvim has 'columns' set to 310 which would give less than four characters on average for each statusline or tabline item before hitting the maximum of 80. My statusline has 16 items; I don't know how many there are on my tabline since it is built dynamically depending on the number of tabs; I think it's 4 per tab plus 6 for the close-button at far right. I would need 18 tabs before running into the current maximum (but I prefer using split-windows rather than tabs).

Just my 0.02 € of course.

Best regards,
Tony.

**Comment by romgrk** [comment]
Here is my tabline with 15 buffers. I'm happy that it doesn't affect you.

Screenshot from 2020-10-22 01-50-35

**Comment by brammool** [comment]
The space is reserved on the stack, and if you run out of stack space Vim might crash...
We increased the number a few times already, it would be better to not use a fixed maximum.

**Comment by romgrk** [comment]
What do you mean by not using a fixed maximum? Allocate on the heap? And otherwise, would a lower number be accetable? What would be that number? Thanks.

**Comment by brammool** [comment]
> What do you mean by not using a fixed maximum? Allocate on the heap?
> And otherwise, would a lower number be accetable? What would be that
> number? Thanks.

First thing to do is to find out if this function can ever be called
recursively.  I suspect that won't happen (or if it does happen there
must be something wrong and the nested call should just bail out).

Then instead of using a fixed size array on the stack, use a static
array, starting at the current size.  When more is needed it can be
reallocated to grow.  There is probably no reason to let it shrink
again.

There are a few places where the maximum size is used, thus this
requires to be inspected, the code might rely on that size while it now
will be dynamic.

-- 
hundred-and-one symptoms of being an internet addict:
108. While reading a magazine, you look for the Zoom icon for a better
     look at a photograph.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by romgrk** [comment]
I've checked for how the function could be called recursively and I couldn't find anything. I've also ran test with the following vimrc:
```vim
function! TabLabel()
  redrawtabline
  return '[label]'	
endfunc

function! StatusLabel()
  redrawstatus
  return '[label]'	
endfunc

let tabline = '%{TabLabel()}'
for i in range(150)
  let tabline .= '%#TabLine' . (i % 2 == 0 ? 'Fill' : 'Sel') . '#' . string(i)[0]
endfor
let &tabline = tabline

let statusline = '%{StatusLabel()}'
for i in range(150)
  let statusline .= '%#TabLine' . (i % 2 == 0 ? 'Fill' : 'Sel') . '#' . string(i)[0]
endfor
let &statusline = statusline

set showtabline=2
set laststatus=2
```

Everything is working well. I've implemented it as simply as I could and modified as few things as possible. I don't know about your coding style & guidelines so let me know if something is to be changed.

I've added the test described in the vimrc above in the statusline tests. Is there anything else that should be tested?

**Comment by brammool** [comment]
Please use a typedef for "struct stl_item", stl_item_T.
Prefix all items in the struct with "stl_", that makes it a lot easier to make changes.

Add a comment for stl_tiems_len that 80 is the starting value and it will grow as needed.
We could start with a lower default now to save some memory, perhaps 20?

**Comment by romgrk** [comment]
> We could start with a lower default now to save some memory, perhaps 20?

Sounds good! I've also applied the other changes requested.

**Comment by brammool** [comment]
Travis and Appveyor both fail.

**Comment by romgrk** [comment]
Seems to be ok now. One MSVC build says fail but it actually went to the end, passing all tests, but says "timed out" for some reason. Also one build in Travis failed by timeout while running :/
Should I look more into that?

**Pull request closed without merging**
