### PR TITLE
Port the tutor plugin from neovim

### PR DESCRIPTION
**Pull request by yegappan**
The github page for this plugin is at

https://github.com/fmoralesc/vim-tutor-mode

A slightly modified version of this is included in neovim. I have ported over
the plugin to Vim (with slight modifications).

### CODE REVIEW

**Comment by brammool** [comment]
So, at least part of this comes from the plugin from Felipe Morales?  Please ask him to put a license on his work.  Without a license we are not allowed to use it.  The Vim license would be best, like it applies to most of the runtime code.

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Jul 7, 2020 at 3:32 AM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

> So, at least part of this comes from the plugin from Felipe Morales?
> Please ask him to put a license on his work. Without a license we are not
> allowed to use it. The Vim license would be best, like it applies to most
> of the runtime code.
>
>
>
I reached out to Felipe Morales about the license. He has now added a
LICENSE file to the repository with reference to the Vim license.

https://github.com/fmoralesc/vim-tutor-mode/commit/e4e41af4bffadeae2549b4fa68e19b572313c286

Regards,
Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Tue, Jul 7, 2020 at 3:32 AM Bram Moolenaar <vim-dev-github@256bit.org>
> wrote:
> 
> > So, at least part of this comes from the plugin from Felipe Morales?
> > Please ask him to put a license on his work. Without a license we are not
> > allowed to use it. The Vim license would be best, like it applies to most
> > of the runtime code.
> >
> >
> >
> I reached out to Felipe Morales about the license. He has now added a
> LICENSE file to the repository with reference to the Vim license.
> 
> https://github.com/fmoralesc/vim-tutor-mode/commit/e4e41af4bffadeae2549b4fa68e19b572313c286

Great, that was quick.

Now we need to find out what in the current vimtutor is missing from
this plugin implementation.

-- 
Article in the first Free Software Magazine: "Bram Moolenaar studied
electrical engineering at the Technical University of Delft and
graduated in 1985 on a multi-processor Unix architecture."
Response by "dimator": Could the school not afford a proper
stage for the ceremony?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
I finally found some time to look at this. I have my doubts if this is better than the existing vimtutor.  It looks nicer, but it also uses several mechanisms that take it away from "raw" Vim.  The tutor is especially made in a way that users can play around with the commands.  There should not be any surprises, such as hidden text (conceal mode is used) and signs popping up depending on what the text looks like.

Does someone have experience with giving this tutor to actual new Vim users?  A teacher perhaps.

Unless there is a clear advantage, I rather stick with the "old boring" tutor, since it has worked fine for a long time.

**Comment by vim-ml** [comment]
On Mon, Jul 4, 2022 at 7:46 AM Bram Moolenaar ***@***.***>
wrote:

> I finally found some time to look at this. I have my doubts if this is
> better than the existing vimtutor. It looks nicer, but it also uses several
> mechanisms that take it away from "raw" Vim. The tutor is especially made
> in a way that users can play around with the commands. There should not be
> any surprises, such as hidden text (conceal mode is used) and signs popping
> up depending on what the text looks like.
>
> Does someone have experience with giving this tutor to actual new Vim
> users? A teacher perhaps.
>
>
Can anyone try the new tutor and give some feedback?

https://github.com/vim/vim/pull/6414

Thanks,
Yegappan


> Unless there is a clear advantage, I rather stick with the "old boring"
> tutor, since it has worked fine for a long time.
>
>
>

**Comment by nickspoons** [comment]
I've had a play with it. The makefile doesn't currently install the actual initial tutor (runtime/tutor/en/vim-01-beginner.tutor) so entering `:Tutor` in vim results in this error: "No tutorial with that name found". After moving the files to the expected location it runs well.

I do think that using this tutor is a much more pleasant experience than the standard vimtutor, and the signs changing from a red ✗ to a green ✓ when you've matched a line is nice feedback. However I also agree with Bram that the tutor should be simple, and there are some things that _might_ be confusing due to use of conceal. For example, learning to use hjkl as the first first lesson and moving around a line becomes a bit confusing when you try to navigate over the links in "Lesson 0", as `l` appears to do nothing for a while (the cursor is moving over the concealed `](holy-grail    )` part of `[like this](holy-grail    )`).

There are also some bugs:

1. After completing section 3.1 (deleting and putting lines with `dd` and `p`) the signs no longer match up with the lines:
   image
   Actually after further testing I realise that this only happens if the 4th line is deleted. But after doing that and causing this issue:
2. In lesson 3.2 the X does not become a checkmark after correcting the line:
   image
  Note that this works correctly unless the section 3.1 error has been triggered.

I didn't test further. Overall it seems like a good idea to me but might need to be more robust?

**Comment by nickspoons** [comment]
> I didn't test further. Overall it seems like a good idea to me but might need to be more robust?

Having said this, the original tutor is still there, so someone following a 10 year old recommendation to run "vimtutor" from the command line will still see the normal old tutor - which is good. Having this version as an optional plugin is a nice addition.

**Comment by lilydjwg** [comment]
I don't like the new tutor (but it's only my opinion; I'm not a teacher).

* The concealed text is indeed annoying and confusing.
* With those check marks, it feels more like a test than a tutorial. The user tends to complete them rather than explore what they can do with the thing they just learned. When I read such tutorials (Vim's old one, an Emacs one, and a helix one) I tend to try operations that the text doesn't tell me to do and understand the result. The check marks discourage this.
* Too many fancy stuff. The user will wonder how it's implemented since the tutorial itself is a text buffer in the editor. The plain text one will make the user focus on the basics it's teaching.
* The first page doesn't teach how to move cursors. The new user won't be able to read further without other materials.
* It uses existing config files, so that the behavior may be different than what the tutorial says. Those config files can be installed by a system admin on a shared machine, or by the user with OS package managers, or the OS tries to ship some "sane default" config, or the user followed a tutorial to install a customized suite but now they want to learn the basics.
* There is no translation yet (but this could be improved later).

**Comment by chrisbra** [comment]
I include this as an optional plugin. Thanks all

**Pull request closed without merging**
