### PR TITLE
MSVC: Reduce building time by reducing command execution

### PR DESCRIPTION
**Pull request by k-takata**
We currently execute several commands in the makefile to read some information, but it may take a long time.

* Stop using PowerShell to read the version information. Use the `for` command instead.
* Reduce execution of the cl command.
  Read `_MSC_VER` and `_MSC_FULL_VER` in a single execution of the cl command.

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks

**Comment by RestorerZ** [comment]
Oh @k-takata , totally agree with you that calling "heavy" powershell is not
good for performance. Using native shell commands is much better and faster.
Where possible, of course.

I let myself see how much we improved performance. And here's what happen:
``` batch
setlocal
@ set /a "count=0"
@ for /f "tokens=2,3" %%I in (version.h) do @ set /a "count+=1" & if "%%I"=="VIM_VERSION_MAJOR" ( echo MAJOR=%%J>.\major.tmp )  else if "%%I"=="VIM_VERSION_MINOR" ( echo MINOR=%%J>.\minor.tmp )
@ echo iterations of the cycle=%count%
```
``` batch
iterations of the cycle=47
```
What would you say if we used a regular expression when searching for version
numbers?
I did it this way, and this is what I got:
``` batch
setlocal
:GetMajor:
@ set /a "count=0"
@ for /F "usebackq tokens=3" %%G in (`findstr /rc:"VIM_VERSION_MAJOR[	]*[0-9]" ".\version.h"`) do @ set /a "count+=1" & echo MAJOR=%%G>.\_major.tmp
@ echo iterations of the cycle=%count%
```
``` batch
iterations of the cycle=1
```
``` batch
setlocal
:GetMinor:
@ set /a "count=0"
@ for /F "usebackq tokens=3" %%G in ( `findstr /rc:"VIM_VERSION_MINOR[	]*[0-9]" ".\version.h"`) do @ set /a "count+=1" & echo MINOR=%%G>.\_minor.tmp
@ echo iterations of the cycle=%count%
```
``` batch
iterations of the cycle=1
```
There's a tab character in square brackets.

It is possible that we could opt out of these checks.
``` makefile
!IF EXIST(.\minor.tmp)
! INCLUDE .\minor.tmp
! IF [$(RM) .\minor.tmp]
! ENDIF
!ENDIF
```

If I understand the code `!IF [{command}]` correctly, it works to check
the return code from the command, something like this:
``` makefile
!IF [{command}]]
# processing if the return code is non-zero
!ELSE
# processing for a null return code
!ENDIF
```
That is, our code could be something like this:
``` makefile
!IF ![for /F "usebackq tokens=3" %G in ( \
	`findstr /rc:"VIM_VERSION_MAJOR[	^]*[0-9^]" ".\version.h"`) do @ \
	    echo MAJOR=%G>.\_major.tmp]
! INCLUDE .\_major.tmp
! IF [$(RM) .\_major.tmp]
! ENDIF
!ENDIF
```
``` makefile
!IF ![for /F "usebackq tokens=3" %G in ( \
	`findstr /rc:"VIM_VERSION_MINOR[	^]*[0-9^]" ".\version.h"`) do @ \
	    echo MINOR=%G>.\_minor.tmp]
! INCLUDE .\_minor.tmp
! IF [$(RM) .\_minor.tmp]
! ENDIF
!ENDIF
```
And here's a search for the patch level number, I got these numbers:
``` batch
@ setlocal EnableDelayedExpansion
@ set LINE=0&& set FIND=0&& for /f "tokens=1,3 delims=,[ " %%I in (version.c) do @ (set /a "count+=1" &&  set /A LINE+=1 && if "%%J"=="included_patches" ( set /A FIND=LINE+3 ) else if "!LINE!"=="!FIND!" ( echo PATCHLEVEL=%%I>.\patchlvl.tmp && echo iterations of the cycle=!count! && exit /b ) )
@ setlocal DisableDelayedExpansion
```
``` batch
iterations of the cycle=738
```
What if we use regular expressions here too and read only the required line from
the file?

The original version I had was this:
``` batch
:GetPatchlvl:
setlocal
for /F "usebackq tokens=1 delims=:" %%G in (`findstr /nblc:"static int included_patches[]" ".\version.c"`) do @ set /a "_t=%%G+2"
for /F "skip=%_t%" %%G in (.\version.c) do (if exist ".\_patchlvl.tmp" (exit /b 1) else (set /a "_t1=%%G+0" && call echo PATCHLEVEL=%%_t1%%>.\_patchlvl.tmp))
```
But then, having seen how you, Takata-san, work with tokens, I reworked it a
bit, and it turned out like this:
``` batch
for /F %%G in ('findstr /nblc:"static int included_patches[]" "version.c"^|(set /p "_t=" ^& set /a _t+=2 ^)') do @cmd /c "for /F "skip=%%G delims=, " %%H in (version.c) do (if exist .\_patchlvl.tmp (exit /b 1) else (echo PATCHLEVEL=%%H>_patchlvl.tmp))"
```
So, the final version we might have is this:
``` makefile
!IF ![for /F "usebackq tokens=3" %G in ( \
	`findstr /rc:"VIM_VERSION_MAJOR[	^]*[0-9^]" ".\version.h"`) do \
		@ echo MAJOR=%G>.\_major.tmp]
! INCLUDE .\_major.tmp
! IF [$(RM) .\_major.tmp]
! ENDIF
!ELSE
! ERROR Could not get the major version number
!ENDIF

!IF ![for /F "usebackq tokens=3" %G in ( \
	`findstr /rc:"VIM_VERSION_MINOR[	^]*[0-9^]" ".\version.h"`) do \
		@ echo MINOR=%G>.\_minor.tmp]
! INCLUDE .\_minor.tmp
! IF [$(RM) .\_minor.tmp]
! ENDIF
!ELSE
! ERROR Could not get the minor version number
!ENDIF

!IF ![for /F %G in ('findstr /nblc:"static int included_patches[^]" \
	"version.c"^| (set /p "_t=" ^& set /a _t+=2 ^)') do \
		@cmd /c "for /F "skip=%G delims=, " %H in (version.c) do \
			@(if exist _patchlvl.tmp (exit /b) else \
			(echo PATCHLEVEL=%H>_patchlvl.tmp))"]
! INCLUDE .\_patchlvl.tmp
! IF [$(RM) .\_patchlvl.tmp]
! ENDIF
!ELSE
! ERROR Could not get the patch level number
!ENDIF

!MESSAGE Vim version: $(MAJOR).$(MINOR).$(PATCHLEVEL)
```
I quite agree that this is not the best code. And it is possible that repeated
calls of `version.h` and `version.c` files have much more overhead than
iterations of loops. To be honest, I haven't measured it. But I hope that this
code can be improved with your help, Takata-san.

**Comment by k-takata** [comment]
Executing a process in Windows is basically slow. So, we should avoid executing processes as much as possible to make it faster.
I tried your code, but it seems that your code is about 5~10% slower.

I use this to measure the time: https://gist.github.com/k-takata/298af00c0da39f31d2921aacf03a26f7
`tm nmake -f Make_mvc.mak CPUNR=foo`

**Comment by RestorerZ** [comment]
Takata-san, thank you very much for the nice measurement tool. I honestly didn't
know what to measure with.
I had a few errors during the build (below), but adding `# pragma comment(lib,
"winmm.lib")` solved everything.

> cl tm.c
> Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30152 for x86
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> tm.c
> Microsoft (R) Incremental Linker Version 14.29.30152.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:tm.exe
> tm.obj
> tm.obj : error LNK2019: unresolved external symbol __imp__timeGetTime@0 referenced in function _main
> tm.obj : error LNK2019: unresolved external symbol __imp__timeBeginPeriod@4 referenced in function _main
> tm.obj : error LNK2019: unresolved external symbol __imp__timeEndPeriod@4 referenced in function _main
> tm.exe : fatal error LNK1120: 3 unresolved externals
 
I measured the makefile. To exclude all side effects, I left only the code of
the `nmake` preprocessor, which processes the `version.h` and `version.c` files
(makefile in the attachment), and got the following result:

_tst-ver-ptch mak

[_tst-ver-ptch.mak.zip](https://github.com/user-attachments/files/16488170/_tst-ver-ptch.mak.zip)

**Comment by k-takata** [comment]
in my side:
```
>tm nmake -f _tst-ver-ptch_my.mak -nologo
Vim version: 9.1.660

0.208sec.
>tm nmake -f _tst-ver-ptch_my.mak -nologo
Vim version: 9.1.660

0.189sec.
>tm nmake -f _tst-ver-ptch_my.mak -nologo
Vim version: 9.1.660

0.208sec.
>tm nmake -f _tst-ver-ptch_takata.mak -nologo
Vim version: 9.1.660

0.157sec.
>tm nmake -f _tst-ver-ptch_takata.mak -nologo
Vim version: 9.1.660

0.180sec.
>tm nmake -f _tst-ver-ptch_takata.mak -nologo
Vim version: 9.1.660

0.175sec.
```

**Comment by RestorerZ** [comment]
Hmm, that's funny... Almost the opposite result from my measurements.
Well, thank you.
I want to thank you again for a great tool for measuring command execution time.
As for these scripts, I'll try to run the tests on a couple more machines I have. And there is an incentive to improve the code.

**Comment by RestorerZ** [comment]
@k-takata 
Takata-san, I've optimized the scripts a bit for Vim version detection.
```makefile
# Read MAJOR and MINOR from version.h.
!IF ![for /F "tokens=2,3" %G in ( \
	'findstr /rc:"VIM_VERSION_MINOR[	^]*[0-9^]" \
	/rc:"VIM_VERSION_MAJOR[	^]*[0-9^]" version.h') do \
	@if "VIM_VERSION_MAJOR"=="%G" (echo MAJOR=%H>>_ver.tmp) \
	else echo MINOR=%H>>_ver.tmp]
! INCLUDE .\_ver.tmp
! IF [$(RM) .\_ver.tmp]
! ENDIF
!ELSE
# Change this value for the new version
MAJOR =		9
# Change this value for the new version
MINOR =		1
!ENDIF
```
This will at least remove two file calls.

```
"_tst-ver-ptch_restorer.mak 19.08.2024 20:26:58,18 pass 1"
Vim version: 9.1.680

0.073sec.

"_tst-ver-ptch_restorer.mak 19.08.2024 20:26:59,24 pass 2"
Vim version: 9.1.680

0.072sec.

"_tst-ver-ptch_restorer.mak 19.08.2024 20:27:00,19 pass 3"
Vim version: 9.1.680

0.073sec.

"_tst-ver-ptch_restorer.mak 19.08.2024 20:27:01,25 pass 4"
Vim version: 9.1.680

0.073sec.

"_tst-ver-ptch_restorer.mak 19.08.2024 20:27:02,19 pass 5"
Vim version: 9.1.680

0.073sec.
```

Also, I was wondering what the discrepancy between your and my measurement
results was due to.
I used several tools and the necessary scripts (file “[measure-tools.zip](https://www.mediafire.com/file/oz5hhgnpoum6sda/measure-tools.zip/file)”) to test:
Cmdlet `Measure-Command` of PowerShell;
Tool "[ptime.exe](http://www.pc-tools.net/files/win32/freeware/ptime-10.zip)";
Tool "[TimedExec.exe](https://github.com/lordmulder/TimedExec)";
Tool "[timeit.exe](https://web.archive.org/web/20150512000719/http://www.microsoft.com/en-us/download/details.aspx?id=17657)" from Resource Kit 2003;
Tool "[timeit.exe](https://github.com/jftuga/timeit)";
Tool "[timer.exe](http://www.gammadyne.com/timer.exe)";
Tool "[timethis.exe](http://www.microsoft.com/windows2000/techinfo/reskit/default.mspx)" from Resource Kit 2000;
Tool "[tm.exe](https://gist.github.com/k-takata/298af00c0da39f31d2921aacf03a26f7)" by Takata-san.
Both current versions of the scripts in makefiles and previous ones, as well as
just batch files with these scripts were checked (file "[_tst-ver-ptch.zip](https://www.mediafire.com/file/mu98fvmt2vqgbkf/_tst-ver-ptch.zip/file)").
The measurements were performed in WinNT 6.1 32-bit MSVS 2019, WinNT 6.3 64-bit
MSVS 2019, WinNT 10.0 64-bit MSVC 2015 and MSVS 2022 (file “[measure-log.zip](https://www.mediafire.com/file/3j315hpkagaaifd/measure-log.zip/file)”).
The results are expectedly different, but the general trend is apparent.

**Pull request closed without merging**
