### PR TITLE
Add silent install option to gvim.nsi

### PR DESCRIPTION
**Pull request by twangboy**
Adds silent install/uninstall ability to the NSIS installer.

Assumes full removal if removed silently.

### CODE REVIEW

**Comment by brammool** [comment]
Shane Lee wrote:

> Adds silent install/uninstall ability to the NSIS installer.
> 
> Assumes full removal if removed silently.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/751
> 
> -- Commit Summary --
> - Add silent install option to gvim.nsi
> 
> -- File Changes --
> 
> ```
> M nsis/gvim.nsi (25)
> ```

How does someone use this?

## 

Women are probably the main cause of free software starvation.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by twangboy** [comment]
@brammool In the next release of gVim (assuming this is merged), you will be able to pass the `/S` switch to the installer so that all the dialog boxes are suppressed.

```
gvim75.exe /S
```

**Comment by brammool** [comment]
Shane Lee wrote:

> @brammool In the next release of gVim (assuming this is merged), you will be able to pass the `/S` switch to the installer so that all the dialog boxes are suppressed.
> 
> ```
> gvim74.exe /S
> ```

OK, so it uses the defaults then?

We need to have a place to document this.  Since the binary comes
without anything, perhaps it should be on vim.org ?

## 

Edison's greatest achievement came in 1879, when he invented the
electric company.  Edison's design was a brilliant adaptation of the
simple electrical circuit: the electric company sends electricity
through a wire to a customer, then immediately gets the electricity
back through another wire

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> We need to have a place to document this. Since the binary comes without anything, perhaps it should be on vim.org ?

The command line parameters for nsis installers can be found here:
http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers

Someone might want to use `/S` and `/D=install-folder`.

**Comment by twangboy** [comment]
@brammool @k-takata bump

**Comment by vim-ml** [comment]
On Wednesday, 4 May 2016 01:59:01 UTC+8, Shane Lee  wrote:

> @brammool @k-takata bump
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

Shouldn't it be high time to change the look and feel of the installer for the next release of Vim?

The NSIS installer code was re-written back in 2010 by Guopeng Wen with the silent install and other bells and whistles:
https://groups.google.com/forum/#!searchin/vim_dev/nsis$20installer/vim_dev/GpRR4rl5tkI/6VaVkrLm76MJ

Update:
https://groups.google.com/forum/#!searchin/vim_dev/nsis$20installer/vim_dev/8PektlxWJvQ/68k4_pWT5QMJ

I am currently using his code with some changes for my own use, and it is working as expected. Better looking also! :D

HTH
KF

**Comment by vim-ml** [comment]
> I am currently using his code with some changes for my own use, and it is working as expected. Better looking also! :D
> 
> Oops, forgot to add the installer that I made using Guopeng's code:
> https://dl.dropboxusercontent.com/u/21119576/%5B_Utils_%5D/gvim74-1816.exe

Please have a try.

Regards,
KF

**Comment by vim-ml** [comment]
KF Leong wrote:

> On Wednesday, 4 May 2016 01:59:01 UTC+8, Shane Lee  wrote:
> 
> > @brammool @k-takata bump
> 
> Shouldn't it be high time to change the look and feel of the installer
> for the next release of Vim?
> 
> The NSIS installer code was re-written back in 2010 by Guopeng Wen
> with the silent install and other bells and whistles:
> https://groups.google.com/forum/#!searchin/vim_dev/nsis$20installer/vim_dev/GpRR4rl5tkI/6VaVkrLm76MJ
> 
> Update:
> https://groups.google.com/forum/#!searchin/vim_dev/nsis$20installer/vim_dev/8PektlxWJvQ/68k4_pWT5QMJ
> 
> I am currently using his code with some changes for my own use, and it
> is working as expected. Better looking also! :D

There have been made a few alternatives, but unfortunately they all do
one thing well, but do not cover every aspect.  It would be great if
someone can combine them into an installer that covers everything that
the current one does.  E.g., including installing the batch files for
console use.  AND have it clearly commented, documented and tested.  I
looked at it a few times and every time realized it was too much work
for me, unfortunately.

## 

FROG: How you English say:  I one more time, mac, I unclog my nose towards
      you, sons of a window-dresser,  so, you think you could out-clever us
      French fellows with your silly knees-bent creeping about advancing
      behaviour.  (blows a raspberry) I wave my private parts at your aunties,
      you brightly-coloured, mealy-templed, cranberry-smelling, electric
      donkey-bottom biters.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
KF Leong wrote:

> > I am currently using his code with some changes for my own use, and
> > it is working as expected. Better looking also! :D
> > 
> > Oops, forgot to add the installer that I made using Guopeng's code:
> > https://dl.dropboxusercontent.com/u/21119576/%5B_Utils_%5D/gvim74-1816.exe
> 
> Please have a try.

Do you really expect someone to download an executable from dropbox and
run it?  Anybody was knows a little bit about security knows you must
never do that.

We should see the source code.

## 

SIGIRO -- irony detected (iron core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dwoz** [comment]
@vim-ml I agree it would be great if all the options could eventually get merged into one installer (the one supported by the VIM project preferably). Since the amount of work to get this is more than anyone will take on at the moment, can we at least get this patch merged? The current installer has a silent option which does not work and this PR at least resolves the bugs in the current silent option.

**Comment by twangboy** [comment]
All you need to do is add a `/S` to all the dialog boxes and choose a sane default... Please do something that allows for a completely silent installation.

**Comment by k-takata** [comment]
I'm now refactoring the NSIS installer. See #3501.
You can try it from https://github.com/vim/vim-win32-installer/releases .

**Comment by twangboy** [comment]
Closed in favor of https://github.com/vim/vim/pull/3501

**Pull request closed without merging**
