### PR TITLE
remove maintainer from syntax/sml.vim

### PR DESCRIPTION
**Pull request by dundargoc**
He mentions here that he doesn't maintain it anymore: https://github.com/vim/vim/issues/5173#issuecomment-551315275

I mailed the other person about [this](https://github.com/vim/vim/issues/5173) issue but I'll probably have a higher chance of winning the lottery than getting an answer back.

### CODE REVIEW

**Comment by dundargoc** [comment]
Is there some sort of metric Vim uses to determine if a maintainer is still actually a maintainer?

**Comment by dundargoc** [comment]
Sounds like you should be maintaining the file then lol

**Comment by brammool** [comment]
Markus actually did some maintenance in #7591
The other email address is of the Milan university, if Fabrizio was a student there, it's likely no longer valid.

**Comment by dundargoc** [comment]
OK. Shall I close this then?

**Comment by brammool** [comment]
I'll include the change to the header.  Was there anything else?

**Comment by dundargoc** [comment]
Nah.

**Comment by brammool** [comment]
Let's close it then

**Pull request closed without merging**
