### PR TITLE
Fixed typos in comments

### PR DESCRIPTION
**Pull request by ss18**
foward -> forward
immediatly -> immediately

### CODE REVIEW

**Comment by k-takata** [comment]
For runtime/autoload/sqlcomplete.vim, did you contact the maintainer?

**Comment by ss18** [comment]
@k-takata not really, it's just typo, can be safely merged.

**Comment by k-takata** [comment]
If the maintainer didn't notice this, the fix might be overwritten by the next update from the maintainer.

**Comment by ss18** [comment]
@k-takata got it, sent email to him

**Comment by brammool** [comment]
I'll include it thanks.

**Pull request closed without merging**
