### PR TITLE
Add support for evaluating Vim expressions in a heredoc

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by brammool** [comment]
Let's leave this open a few days to allow for comments.

I'm not sure if we should use `=expr` or just `expr`.  Compared to other places in Vim `=expr` would be more common,
but compared to any other language `expr` would be preferred.

The help is not clear: can the expression span multiple lines?  So I could use
```
some literal text `=
 expr line
  expr line
` more literal text
```

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Apr 10, 2022 at 11:25 AM Bram Moolenaar ***@***.***>
wrote:

> Let's leave this open a few days to allow for comments.
>
> I'm not sure if we should use =expr or just expr. Compared to other
> places in Vim =expr would be more common,
> but compared to any other language expr would be preferred.
>
> The help is not clear: can the expression span multiple lines? So I could
> use
>

An expression must be within a single line and cannot span multiple lines.
I will update the help to reflect this.

Regards,
Yegappan


> some literal text `=
>  expr line
>   expr line
> ` more literal text
>
>
>

**Comment by lacygoill** [comment]
> I'm not sure if we should use =expr or just expr. Compared to other places in Vim =expr would be more common,
   > but compared to any other language expr would be preferred.

Yes, I suggested `backtick equal` to be as consistent as possible with the existing syntax, but in practice I suspect it's hardly ever used.  Dropping the equal sign might make it easier for people coming from other languages to assimilate this new syntax.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Apr 10, 2022 at 8:53 PM lacygoill ***@***.***> wrote:

> I'm not sure if we should use =expr or just expr. Compared to other places
> in Vim =expr would be more common,
> but compared to any other language expr would be preferred.
>
> Yes, I suggested backtick equal to be as consistent as possible with the
> existing syntax, but in practice I suspect it's hardly ever used. Dropping
> the equal sign might make it easier for people coming from other languages
> to assimilate this new syntax.
>
>
>
Should we support using only backtick for expanding the Vim expression in a
heredoc?

Thanks,
Yegappan

**Comment by brammool** [comment]
The help says "If the expression evaluation fails, then it is replaced with an empty string."
I think it's better to treat an error like an error and not silently use an empty string.
If you would have an assignment with a faling expression, it would also fail.

**Comment by brammool** [comment]
I have not seen comments objecting to using the "`=expr`" form, including the equal sign.  So I guess it should be OK that way.

**Comment by brammool** [comment]
When adding another test I found that this doesn't work:
```
var x = 'X'
  code =<< eval trim END
    let b = `=x`
  END
```
This will require more work, since "x" would have to be evaluated at runtime.  Let's do that in a followup change.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Apr 17, 2022 at 3:51 AM Bram Moolenaar ***@***.***>
wrote:

> I have not seen comments objecting to using the "=expr" form, including
> the equal sign. So I guess it should be OK that way.
>
>
>
If you think using a single backquote will be easier and less confusing
than using "`=",
then we can still change this.

Regards,
Yegappan

**Comment by errael** [comment]
I've never use vimscript, or the `=` that I see around occasionally. From my perspective, whatever is consistent with what I'll see in vim9script is best; `:help script` explains vim9. Consistency with vim9 seems paramount. IMO, if the `=` is required in vim9 in situations, then OK; otherwise nuke it.

**Comment by Shane-XB-Qian** [comment]
correct the syntax highlight when with/without `trim` and `eval` (of this heredoc) as well..
// currently it is broken.

**Comment by Shane-XB-Qian** [comment]
image
image

**Comment by brammool** [comment]
@cecamp for the highlighting

**Pull request closed without merging**
