### PR TITLE
[doc] Fix tags

### PR DESCRIPTION
**Pull request by crazymaster**

### CODE REVIEW

**Comment by brammool** [comment]
Master wrote:

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/405
> 
> -- Commit Summary --
> - [doc] Fix tags
> 
> -- File Changes --
> 
> ```
> M runtime/doc/farsi.txt (2)
> M runtime/doc/windows.txt (16)
> ```

Thanks.  I'll include it.

I can't see a real name here.  For this small change that's OK, but for
including code I need to see who it's coming from.

## 

"I know that there are people who don't love their fellow man,
and I hate those people!" - Tom Lehrer

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
Bram wrote:

> I can't see a real name here.

I can see it if I click on the github profile id (→ Kenichi Ito).

**Comment by xaizek** [comment]
@dpelle, I think Bram is talking about absence of identification in redirected emails, which say just

```
From: master <vim-dev-github@256bit.org>
```

**Comment by crazymaster** [comment]
Oops, sorry.
I changed github profile id after I notice that a real name doesn't show.

**Comment by crazymaster** [comment]
s/github profile id/github user name/

**Comment by crazymaster** [comment]
Merged by https://github.com/vim/vim/commit/12969c04fe7bd27dc0cbf37709eb40a86d4a27f9

**Pull request closed without merging**
