### PR TITLE
Fix SIGSEGV due to null pointer reference of erase_internal

### PR DESCRIPTION
**Pull request by mnishz**
```
Problem:    erase_internal() doesn't check the returned value of
            getcell()
Solution:   Check the returned value of getcell()
```
This is a **draft** because I haven't validated this fix.

**Describe the bug**
Vim crashes by SIGSEGV.

**To Reproduce**
I'm not sure how to reproduce. Please let me know if anyone has some idea to recreate this.

**How to fix**
Check the returned value by getcell() if NULL or not. I found some other code that doesn't check that value, not only erase_internal().

**Expected behavior**
No SIGSEGV.

**Screenshots**
No screenshot.

**Environment (please complete the following information):**
 - Vim version: v8.2.0821
 - OS: Ubuntu 18.04
 - Terminal: mintty

**Additional context**
coredump, `cell` in `erase_internal()` looks null pointer.
```
#0  0x00007f929a195187 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x00005597c7daedd5 in may_core_dump () at os_unix.c:3408
#2  0x00005597c7daed79 in mch_exit (r=0x1) at os_unix.c:3374
#3  0x00005597c7f1e37e in getout (exitval=0x1) at main.c:1717
#4  0x00005597c7d7029e in preserve_exit () at misc1.c:2189
#5  0x00005597c7dac7d0 in deathtrap (sigarg=0xb) at os_unix.c:1099
#6  0x00007f929a559890 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00005597c7edeeb0 in erase_internal (rect=..., selective=0x0, user=0x5597c8d70ca0) at libvterm/src/screen.c:286
#8  0x00005597c7edefda in erase (rect=..., selective=0x0, user=0x5597c8d70ca0) at libvterm/src/screen.c:307
#9  0x00005597c7ee12da in erase (state=0x5597c8cc4c20, rect=..., selective=0x0) at libvterm/src/state.c:57
#10 0x00005597c7ee476d in on_csi (leader=0x0, args=0x5597c8cbeb38, argcount=0x1, intermed=0x0, command=0x4b, user=0x5597c8cc4c20) at libvterm/src/state.c:1165
#11 0x00005597c7edba32 in do_csi (vt=0x5597c8cbeae0, command=0x4b) at libvterm/src/parser.c:36
#12 0x00005597c7edc1cf in vterm_input_write (vt=0x5597c8cbeae0, bytes=0x5597c94ae670 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"..., len=0x3cf) at libvterm/src/parser.c:240
#13 0x00005597c7e643aa in term_write_job_output (term=0x5597c8d55ad0, msg=0x5597c94ae670 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"..., len=0x3cf) at terminal.c:1075
#14 0x00005597c7e645aa in write_to_term (buffer=0x5597c8d71100, msg=0x5597c94ae670 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"..., channel=0x5597c8d6fe60) at terminal.c:1146
#15 0x00005597c7f06e3b in may_invoke_callback (channel=0x5597c8d6fe60, part=PART_OUT) at channel.c:2960
#16 0x00005597c7f09e20 in channel_parse_messages () at channel.c:4652
#17 0x00005597c7d22b47 in parse_queued_messages () at getchar.c:2163
#18 0x00005597c7e7c76b in inchar_loop (buf=0x5597c81d28db <typebuf_init+91> "", maxlen=0x39, wtime=0xffffffffffffffff, tb_change_cnt=0x1ba5, wait_func=0x5597c7db27e6 <WaitForChar>, resize_func=0x5597c7dac16d <resize_func>) at ui.c:290
#19 0x00005597c7dac1d6 in mch_inchar (buf=0x5597c81d28db <typebuf_init+91> "", maxlen=0x39, wtime=0xffffffffffffffff, tb_change_cnt=0x1ba5) at os_unix.c:390
#20 0x00005597c7e7c6a9 in ui_inchar (buf=0x5597c81d28db <typebuf_init+91> "", maxlen=0x39, wtime=0xffffffffffffffff, tb_change_cnt=0x1ba5) at ui.c:224
#21 0x00005597c7d24a8f in inchar (buf=0x5597c81d28db <typebuf_init+91> "", maxlen=0xad, wait_time=0xffffffffffffffff) at getchar.c:3407
#22 0x00005597c7d24637 in vgetorpeek (advance=0x1) at getchar.c:3186
#23 0x00005597c7d21fcd in vgetc () at getchar.c:1663
#24 0x00005597c7d22591 in safe_vgetc () at getchar.c:1889
#25 0x00005597c7d814b4 in normal_cmd (oap=0x7ffced8a4ef0, toplevel=0x1) at normal.c:569
#26 0x00005597c7f1df85 in main_loop (cmdwin=0x0, noexmode=0x0) at main.c:1509
#27 0x00005597c7f1d291 in vim_main2 () at main.c:899
#28 0x00005597c7f1c975 in main (argc=0x1, argv=0x7ffced8a50f8) at main.c:438#7  0x00005597c7edeeb0 in erase_internal (rect=..., selective=0x0, user=0x5597c8d70ca0) at libvterm/src/screen.c:286
286           cell->chars[0] = 0;
(gdb) info args
rect = {
  start_row = 0xfffffffa, 
  end_row = 0xfffffffb, 
  start_col = 0xd3, 
  end_col = 0xef
}
selective = 0x0
user = 0x5597c8d70ca0
(gdb) info locals 
cell = 0x0
info = 0x5597ca1afbe8
screen = 0x5597c8d70ca0
row = 0xfffffffa
col = 0xd3
```

### CODE REVIEW

**Comment by brammool** [comment]
This looks like a problem in libvterm, please report to Paul Evans: http://www.leonerd.org.uk/code/libvterm/

**Comment by mnishz** [comment]
I sent an email to Paul Evans. I'm not sure if I was able to explain this issue correctly, though... (I got a lot of support from @vim-jp about this issue.)
In any case, I think this kind of fix is still needed. I'm trying to confirm that this fix is valid, but it hasn't recreated yet.

**Comment by mnishz** [comment]
Ah, now I understand that these code is exactly owned by libvterm and not by Vim. Thank you. I'm closing this issue.
I found how to recreate, but at this point this occurs only when I'm building my companies code.

**Comment by mnishz** [comment]
Info update
* This happens after v8.2.0795
* How to recreate
    1. Install CtrlP
    1. Launch Vim 
    1. `:botright terminal`
    1. `CTRL-w k` (to move to an upper normal window)
    1. `CTRL-p` (to open CtrlP windows)
    1. SIGSEGV
* I've emailed how to recreate, gdb log and core dump to Paul Evans.

**Comment by leonerd** [comment]
I've tried to reprroduce this.

New docker container. Built vim from source - it claims 

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 26 2020 17:43:33)
Included patches: 1-1058
```

I have CtrlP installed. I got as far as step *v* but it didn't appear to do anything. No new window appeared, but also it didn't SEGV. It happily continues running fine.

I wonder - what shell are you running inside the terminal? I have the stock interactive `bash` as a plain new debian image, and that doesn't try to print just because of a resize. From your crash log I notice it printing what looks like a plausible prompt string:

```
#25 0x000055f997ff3800 in vterm_input_write (vt=0x55f998803d20, bytes=0x55f998872b00 "\r\033[K\033]0;libvterm@libvterm-Virtual-Machine: ~\a\033[01;32mlibvterm@libvterm-Virtual-Machine\033[00m:\033[01;34m~\033[00m$ ", len=108)
```

which I could imagine e.g. `zsh` doing on terminal resize. Maybe that is a required step to reproduce?

One thing I can suggest is building libvterm with `-DDEBUG`, which add some debugging asserts about cursor position that should at least turn SIGSEGV into SIGABRT with more of a detailed assertion message. From the gdb log emailed to me it looks like it is trying to `erase()` in a silly location (involving negative row numbers). It won't directly stop it crashing but it will print more information when it does so, and possibly earlier in the sequence at the time the cursor was moved to a bad place.

**Comment by brammool** [comment]
It appears all the terminal resizing problems have been fixed by patch 8.2.1030, which makes sure that state->pos.row does not become negative.  The basic problem appears to be that when the number of rows is reduced the position is adjusted by subtracting the number of deleted rows, causing the row to possibly become negative. 
The simplest way to reproduce is using ":bot term", then ":resize" in the Vim window, which make the terminal very small, then triggering a redraw in any way.

**Comment by leonerd** [comment]
Ah that sounds quite plausible yes. 

How do I see this numbered patch?

**Comment by leonerd** [comment]
Ahyes, here I see:

https://github.com/vim/vim/commit/da58134eedf43ae4b9013c93ecbdf55e4da4b8a3

That seems reasonable. I'll add those other two bounding lines.

**Comment by leonerd** [comment]
Now in upstream libvterm; plus unit test.

```
revno: 768
committer: Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
branch nick: libvterm
timestamp: Sat 2020-06-27 12:10:14 +0100
message:
  Ensure that resize shorter does not send the cursor to a negative row
```

**Comment by brammool** [comment]
> Ah that sounds quite plausible yes. 
> 
> How do I see this numbered patch?

Search on Google with the patch number and "vim".
Should be the first entry :-).

-- 
A law to reduce crime states: "It is mandatory for a motorist with criminal
intentions to stop at the city limits and telephone the chief of police as he
is entering the town.
		[real standing law in Washington, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
> Now in upstream libvterm; plus unit test.
Thanks, I'll include the test.

> ```
> revno: 768
> committer: Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
> branch nick: libvterm
> timestamp: Sat 2020-06-27 12:10:14 +0100
> message:
>   Ensure that resize shorter does not send the cursor to a negative row
> ```

Apparently it takes 6 hours for a patch to show up on launchpad.
Any way to decrease that time?

-- 
SIGIRO -- irony detected (iron core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mnishz** [comment]
Hi @leonerd,
I'm sorry, I forgot to reply to this thread. It looks like this problem has certainly been fixed. Thanks a lot!
In fact, I found another SIGSEGV. How should I report it? Is sending e-mail like the previous one convenient for you? Or do I open a new issue on this Vim repository? (I'm not sure if it's OK, though...)
```
(gdb) bt
#0  0x00007f8df476a237 in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x000055790eed3913 in may_core_dump () at os_unix.c:3423
#2  0x000055790eed5802 in may_core_dump () at os_unix.c:3374
#3  mch_exit (r=0x1) at os_unix.c:3389
#4  0x000055790efe3048 in getout (exitval=0x1) at main.c:1713
#5  <signal handler called>
#6  putglyph (info=0x7ffcf7caadc0, pos=..., user=0x55790fcb4120) at libvterm/src/screen.c:189
#7  0x000055790efb7a88 in putglyph (state=state@entry=0x55790fc980c0, chars=chars@entry=0x55790fcb4040, width=width@entry=0x2, pos=...) at libvterm/src/state.c:27
#8  0x000055790efb8a28 in on_text (bytes=<optimized out>, len=<optimized out>, user=0x55790fc980c0) at libvterm/src/state.c:420
#9  0x000055790efb3b31 in vterm_input_write (vt=vt@entry=0x55790fcb3d80, bytes=bytes@entry=0x55790fcb44b0 "\r\033[K\033[0;31m(SSH)\033[0m \033[0;32m✅\033[0m ~\033[0;36m\033[0m$ ", len=len@entry=0x32) at libvterm/src/parser.c:329
#10 0x000055790ef697ea in term_write_job_output (len=0x32, msg=0x55790fcb44b0 "\r\033[K\033[0;31m(SSH)\033[0m \033[0;32m✅\033[0m ~\033[0;36m\033[0m$ ", term=0x55790fc86ef0) at terminal.c:1075
#11 write_to_term (buffer=buffer@entry=0x55790fcae1b0, msg=msg@entry=0x55790fcb44b0 "\r\033[K\033[0;31m(SSH)\033[0m \033[0;32m✅\033[0m ~\033[0;36m\033[0m$ ", channel=channel@entry=0x55790fcc3a20) at terminal.c:1146
#12 0x000055790efd1b6b in may_invoke_callback (channel=channel@entry=0x55790fcc3a20, part=part@entry=PART_OUT) at channel.c:2943
#13 0x000055790efd3509 in channel_parse_messages () at channel.c:4635
#14 0x000055790ee61c63 in parse_queued_messages () at getchar.c:2188
#15 0x000055790ef7c1a5 in inchar_loop (buf=buf@entry=0x55790f290d52 <typebuf_init+82> "", maxlen=0x3c, wtime=wtime@entry=0xffffffffffffffff, tb_change_cnt=0x45, wait_func=wait_func@entry=0x55790eed2a30 <WaitForChar>,
    resize_func=resize_func@entry=0x55790eed38a0 <resize_func>) at ui.c:290
#16 0x000055790eed3fb3 in mch_inchar (buf=buf@entry=0x55790f290d52 <typebuf_init+82> "", maxlen=<optimized out>, wtime=wtime@entry=0xffffffffffffffff, tb_change_cnt=<optimized out>) at os_unix.c:388
#17 0x000055790ef7b7fe in ui_inchar (buf=buf@entry=0x55790f290d52 <typebuf_init+82> "", maxlen=maxlen@entry=0x3c, wtime=wtime@entry=0xffffffffffffffff, tb_change_cnt=tb_change_cnt@entry=0x45) at ui.c:224
#18 0x000055790ee6206a in inchar (buf=0x55790f290d52 <typebuf_init+82> "", maxlen=0xb6, wait_time=0xffffffffffffffff) at getchar.c:3514
#19 0x000055790ee62959 in vgetorpeek (advance=advance@entry=0x1) at getchar.c:3293
#20 0x000055790ee6437f in vgetc () at getchar.c:1687
#21 0x000055790ef67325 in term_vgetc () at terminal.c:2028
#22 0x000055790ef6add4 in terminal_loop (blocking=0x1) at terminal.c:2476
#23 0x000055790efe2e4a in main_loop (cmdwin=0x0, noexmode=0x0) at main.c:1496
#24 0x000055790efe3c40 in vim_main2 () at main.c:895
#25 0x000055790edc969d in main (argc=<optimized out>, argv=<optimized out>) at main.c:439
```

**Comment by brammool** [comment]
Masato Nishihata - please mention the Vim version.
If it still reproduces in the current version, how to reproduce?

**Comment by mnishz** [comment]
Hi Bram, yes, I tried the latest version a while ago, but it's reproducible. So, let me describe here.

# How to reproduce
1. tmux
2. vim -Nu NONE
3. :botright vert term
4. ctrl-b % (to open a new tmux pain)

# Environment (please complete the following information):
Vim version: v8.2.1342
OS: Ubuntu 18.04 (Hyper-V)
Terminal: mintty + tmux

# Screenshots
vim_sigsegv

**Comment by mnishz** [comment]
mintty supports the following shortcut keys and this causes the same problem without tmux.
1. Alt + F11 (to maximize the terminal size)
2. vim -Nu NONE
3. :botright vert term
4. Alt + F10 (to restore the terminal size)

**Comment by brammool** [comment]
I cannot reproduce it.  I also used valgrind, it doesn't spot an error.

**Comment by mnishz** [comment]
Hmm, I see... getcell returned nullptr because `col >= screen->cols`.
https://github.com/vim/vim/blob/master/src/libvterm/src/screen.c#L81
And SEGV caused here.
https://github.com/vim/vim/blob/master/src/libvterm/src/screen.c#L189
```
(gdb) p row
$6 = 0x6
(gdb) p col
$7 = 0x1
(gdb) p *screen
$8 = {
  vt = 0x556d4f7e6980,
  state = 0x556d4f4f4ab0,
  callbacks = 0x556d4e23e000 <screen_callbacks>,
  cbdata = 0x556d4f7a1160,
  damage_merge = VTERM_DAMAGE_CELL,
  damaged = {
    start_row = 0xffffffff,
    end_row = 0x0,
    start_col = 0x0,
    end_col = 0x0
  },
  pending_scrollrect = {
    start_row = 0xffffffff,
    end_row = 0x0,
    start_col = 0x0,
    end_col = 0x0
  },
  pending_scroll_downward = 0x0,
  pending_scroll_rightward = 0x0,
  rows = 0x14,
  cols = 0x1,
  global_reverse = 0x0,
  buffers = {0x556d4f795fe0, 0x556d4f7a0690},
  buffer = 0x556d4f795fe0,
  sb_buffer = 0x556d4f810c30,
  pen = {
    fg = {
      type = 0x1,
      red = 0x0,
      green = 0xe0,
      blue = 0x0,
      index = 0x2
    },
    bg = {
      type = 0x4,
      red = 0x2b,
      green = 0x2b,
      blue = 0x29,
      index = 0x0
    },
    bold = 0x0,
    underline = 0x0,
    italic = 0x0,
    blink = 0x0,
    reverse = 0x0,
    conceal = 0x0,
    strike = 0x0,
    font = 0x0,
    protected_cell = 0x0,
    dwl = 0x0,
    dhl = 0x0
  }
}
```

**Comment by mnishz** [comment]
I tried the following change, but I still see SIGSEGV, not SIGABRT, and no additional message. Is something wrong?
```diff
diff --git a/src/Makefile b/src/Makefile
index d34a60891..a09aabb58 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -593,7 +593,7 @@ CClink = $(CC)
 # When using -g with some older versions of Linux you might get a
 # statically linked executable.
 # When not defined, configure will try to use -O2 -g for gcc and -O for cc.
-#CFLAGS = -g
+CFLAGS = -ggdb3 -DDEBUG
 #CFLAGS = -O

 # Optimization limits - depends on the compiler.  Automatic check in configure
@@ -1162,7 +1162,7 @@ INSTALL_DATA_R    = cp -r

 ### Program to run on installed binary.  Use the second one to disable strip.
 #STRIP = strip
-#STRIP = /bin/true
+STRIP = /bin/true

 ### Permissions for binaries  {{{1
 BINMOD = 755
```
```
gcc -c -I. -Ilibvterm/include -Iproto -DHAVE_CONFIG_H     -ggdb3 -DDEBUG        -DINLINE="" -DVSNPRINTF=vim_vsnprintf -DSNPRINTF=vim_snprintf -DIS_COMBINING_FUNCTION=utf_iscomposing_uint -DWCWIDTH_FUNCTION=utf_uint2cells -o objects/vterm_screen.o libvterm/src/screen.c
```

**Comment by dpelle** [comment]
I cannot reproduce.

To @mnishz : since you can reproduce, can you try with a asan build of the latest vim?

To build with asan, you need to:

1) uncomment the following line in vim/src/
```
SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
```

2) rebuild:
```
$ cd vim/src
$ make clean
$ make -j8
```

3) redirect vim stderr to a file (e.g. asan.log) to capture asan output when trying to reproduce the issue:
```
$ ./vim -Nu NONE 2> asan.log
(then reproduce the issue)
```
If a memory error occurs (out of bound, use of free memory…) the file `asan.log` will contain useful information.
So please `asan.log` to this ticket.

**Comment by mnishz** [comment]
I found a configuration causing this. I have this configuration in my .bashrc. When I uncomment these lines, this SIGSEGV doesn't occur. Maybe 2 cells characters are causing this.
```sh
PROMPT_COMMAND=__prompt_command

function __prompt_command() {
    local EXIT="$?"

    local RCol='\[\e[0m\]'
    local Green='\[\e[0;32m\]'
    local Red='\[\e[0;31m\]'
    local Yellow='\[\e[0;33m\]'
    local Cyan='\[\e[0;36m\]'

    PS1="\w${Cyan}$(__git_ps1 ' (%s)')${RCol}\$ "

    if [[ ${EXIT} == 0 ]]; then
        PS1="${Green}✅${RCol} "$PS1
    elif [[ ${EXIT} == 130 ]]; then
        PS1="${Red}🚫${RCol} "$PS1
    else
        PS1="${Yellow}💥${RCol} "$PS1
    fi

    if [ -n "$SSH_CONNECTION" ]; then
        PS1="${Red}(SSH)${RCol} "$PS1
    fi
}
```

I also tried asan (AddressSanitizer?). Is this expected one?
```
ASAN:DEADLYSIGNAL
=================================================================
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by dpelle** [comment]
@mnishz wrote:

> Maybe 2 cells characters are causing this.

Yes. I can now reproduce the bug 100% of the time with vim-8.2.1352 on Linux x86_64. This command crashes and it's completely automated (nothing to type):
```
$ ./vim --clean -c'set co=80' -c 'botright vert term' -c 'call term_sendkeys(2, "💥")' -c 'set co=40'
Vim: Caught deadly signal SEGV
Vim: Finished.
Segmentation fault (core dumped)
```
Running it with valgrind gives:
```
$ valgrind --num-callers=40 ./vim --clean -c'set co=80' -c 'botright vert term' -c 'call term_sendkeys(2, "💥")' -c 'set co=40' 2> valgrind.log

$ cat valgrind.log
==14585== Memcheck, a memory error detector
==14585== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14585== Using Valgrind-3.17.0.GIT and LibVEX; rerun with -h for copyright info
==14585== Command: ./vim --clean -cset\ co=80 -c botright\ vert\ term -c call\ term_sendkeys(2,\ "____") -c set\ co=40
==14585== 
==14585== Invalid write of size 4
==14585==    at 0x14761C: putglyph.cold (screen.c:189)
==14585==    by 0x367B5E: putglyph (state.c:27)
==14585==    by 0x368AFC: on_text (state.c:420)
==14585==    by 0x363F3B: vterm_input_write (parser.c:329)
==14585==    by 0x2FEEB9: term_write_job_output (terminal.c:1075)
==14585==    by 0x2FEEB9: write_to_term (terminal.c:1146)
==14585==    by 0x3840FE: may_invoke_callback (channel.c:2943)
==14585==    by 0x386C26: channel_parse_messages (channel.c:4635)
==14585==    by 0x1E9276: parse_queued_messages (getchar.c:2188)
==14585==    by 0x312EB4: inchar_loop (ui.c:290)
==14585==    by 0x312831: ui_inchar (ui.c:224)
==14585==    by 0x1E96D6: inchar (getchar.c:3514)
==14585==    by 0x1EA343: vgetorpeek (getchar.c:3293)
==14585==    by 0x1EBC73: vgetc (getchar.c:1687)
==14585==    by 0x2F9D14: term_vgetc (terminal.c:2028)
==14585==    by 0x300D5A: terminal_loop (terminal.c:2476)
==14585==    by 0x395DD9: main_loop (main.c:1496)
==14585==    by 0x396CC2: vim_main2 (main.c:895)
==14585==    by 0x8FA3B96: (below main) (libc-start.c:310)
==14585==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==14585== 
==14585== 
==14585== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==14585==    at 0x8FC1237: kill (syscall-template.S:78)
==14585==    by 0x2659E6: may_core_dump (os_unix.c:3423)
==14585==    by 0x2659E6: may_core_dump (os_unix.c:3418)
==14585==    by 0x2659E6: mch_exit (os_unix.c:3389)
==14585==    by 0x8D7589F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==14585==    by 0x14761B: vterm_screen_is_eol.cold (screen.c:885)
==14585==    by 0x125ACD23: ???
==14585==    by 0x367B5E: putglyph (state.c:27)
==14585==    by 0x368AFC: on_text (state.c:420)
==14585==    by 0x363F3B: vterm_input_write (parser.c:329)
==14585==    by 0x2FEEB9: term_write_job_output (terminal.c:1075)
==14585==    by 0x2FEEB9: write_to_term (terminal.c:1146)
==14585==    by 0x3840FE: may_invoke_callback (channel.c:2943)
==14585==    by 0x386C26: channel_parse_messages (channel.c:4635)
==14585==    by 0x1E9276: parse_queued_messages (getchar.c:2188)
==14585==    by 0x312EB4: inchar_loop (ui.c:290)
==14585==    by 0x312831: ui_inchar (ui.c:224)
==14585==    by 0x1E96D6: inchar (getchar.c:3514)
==14585==    by 0x1EA343: vgetorpeek (getchar.c:3293)
==14585==    by 0x1EBC73: vgetc (getchar.c:1687)
==14585==    by 0x2F9D14: term_vgetc (terminal.c:2028)
==14585==    by 0x300D5A: terminal_loop (terminal.c:2476)
==14585==    by 0x395DD9: main_loop (main.c:1496)
==14585==    by 0x396CC2: vim_main2 (main.c:895)
==14585==    by 0x8FA3B96: (below main) (libc-start.c:310)
==14585== 
==14585== HEAP SUMMARY:
==14585==     in use at exit: 2,082,898 bytes in 17,444 blocks
==14585==   total heap usage: 32,684 allocs, 15,240 frees, 17,016,294 bytes allocated
==14585== 
==14585== LEAK SUMMARY:
==14585==    definitely lost: 2,464 bytes in 2 blocks
==14585==    indirectly lost: 0 bytes in 0 blocks
==14585==      possibly lost: 6,296 bytes in 119 blocks
==14585==    still reachable: 2,074,138 bytes in 17,323 blocks
==14585==                       of which reachable via heuristic:
==14585==                         newarray           : 1,536 bytes in 16 blocks
==14585==         suppressed: 0 bytes in 0 blocks
==14585== Rerun with --leak-check=full to see details of leaked memory
==14585== 
==14585== For lists of detected and suppressed errors, rerun with: -s
==14585== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by brammool** [comment]
Thanks Dominique, I managed to make a test out of that.
I'll fix this specific crash, but @leonerd may want to check all the getcell() calls.

**Comment by mnishz** [comment]
Thank you very much for the quick fix!

**Pull request closed without merging**
