### PR TITLE
Problem: *.asm file detection is different from many build systems

### PR DESCRIPTION
**Pull request by Freed-Wu**
Problem: *.asm file detection is different from many build systems
Solution: Keep similar behaviour

https://mesonbuild.com/Release-notes-for-0-64-0.html#new-languages-nasm-and-masm

> When the nasm language is added to the project, .asm files are automatically compiled with NASM. This is only supported for x86 and x86_64 CPU family. yasm is used as fallback if nasm command is not found.
>
> When the masm language is added to the project, .masm files are automatically compiled with Microsoft's Macro Assembler. This is only supported for x86, x86_64, ARM and AARCH64 CPU families.
>
> Note that GNU Assembly files usually have .s or .S extension and were already built using C compiler such as GCC or CLANG.

We treat *.nasm as nasm, *.masm as masm, *.[SsAa] as GNU asm,
and detect b:asmsyntax for *.asm

### CODE REVIEW

**Comment by chrisbra** [comment]
I am not sure I follow, what is the reason we should follow meson here? Isn't that an unsurprising change for existing ASM users and a slightly backward incompatible change? ping @dkearns and @adah1972 they may have a word or two to say here.

**Comment by Freed-Wu** [comment]
Change default value of `g:asm_syntax` is a little riskful.

And, IMO, treat `*.nasm` as `nasm`, `*.masm` as `masm`, `*.[SsAa]` as GNU asm should be reasonable?

**Comment by adah1972** [comment]
I do not think we need to change the default values.

Although .asm files are always MASM in my environments, it is not universal. So I have my personal setting in ~/.vim/filetype.vim:

```vim
augroup filetypedetect
  au! BufReadPre,BufNewFile *.asm       let b:asmsyntax='masm'
  …
augroup END
```

People can easily do so by themselves.

**Comment by Freed-Wu** [comment]
> I do not think we need to change the default values.

OK, keep the default values.

**Comment by chrisbra** [comment]
Thanks. Let's also keep this line: 
```
au BufNewFile,BufRead *.asm,*.[sS],*.[aA],*.mac,*.lst	call dist#ft#FTasm()
```

**Comment by Freed-Wu** [comment]
Open a discussion https://github.com/vim/vim/discussions/17474

**Pull request closed without merging**
