### PR TITLE
Convert src/{digraph,hangulin}.c to utf8

### PR DESCRIPTION
**Pull request by blueyed**
I've used `iconv -f latin1 -t utf8` (since Vim detects it as latin1).
`file -bi src/digraph.c` reported "text/x-c; charset=unknown-8bit".

This makes it easier for other tools to handle, e.g. https://github.com/RPGillespie6/fastcov/issues/14.

### CODE REVIEW

**Comment by k-takata** [comment]
> I've used `iconv -f latin1 -t utf8` (since Vim detects it as latin1).

Obviously wrong for hangulin.c. It is encoded in euc-kr.

**Comment by blueyed** [comment]
> Obviously wrong for hangulin.c

Sorry, not for me obviously.. ;)
Thanks for catching - fixed!

**Comment by k-takata** [comment]
This line can be updated:
https://github.com/vim/vim/blob/94f82cbacf76767b5ac32f813e1d670501dbd0e6/.travis.yml#L99
`latin-1` and `EUC-KR` can be removed.

**Comment by brammool** [comment]
I recall some compilers didn't like the utf-8 encoded text.  But I forgot which ones.

**Comment by blueyed** [comment]
> I recall some compilers didn't like the utf-8 encoded text. But I forgot which ones.

Theres a note, but not about utf8:

> Note: Characters marked with XX are not included literally, because some
> compilers cannot handle them (Amiga SAS/C is the most picky one).

https://github.com/vim/vim/blob/8edf0e31323a4293524f51f2960f4f3064309526/src/digraph.c#L32-L36

**Pull request closed without merging**
