### PR TITLE
Makes a snappy package.

### PR DESCRIPTION
**Pull request by GarethH96**
Included snapcraft.yaml that allows you to make a .snap file. Will require `snapcraft` to build and `snapd` to install. It uses the classic confinement so then it allows for read and write.

### CODE REVIEW

**Comment by brammool** [comment]
Gareth Hulse wrote:

> Included snapcraft.yaml that allows you to make a .snap file. Will
> require `snapcraft` to build and `snapd` to install. It uses the
> classic confinement so then it allows for read and write.

I have no idea what snappy is.  Please explain what the advantage is of
including this with Vim.

-- 
A M00se once bit my sister ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by GarethH96** [comment]
> I have no idea what snappy is. Please explain what the advantage is of including this with Vim.

Here are a few things:

- works on multiple GNU/Linux distros. So for example if you install `snapd` on [Arch Linux](https://wiki.archlinux.org/index.php/Snapd) and [Debain](https://packages.debian.org/en/sid/snapd), you will have the exact same apps which are exactly the same versions; doesn't matter if they are rolling or fixed release.
- Very easy to use. To install an app - inkscape for example - do `sudo snap install inkscape`.
- It has channels. You could do `sudo snap install vlc --beta` or `sudo snap install blender-tpaw --edge` or `sudo snap install ufw --stable` or `sudo snap install <app-name> --classic.`
-  Can be sand boxed, but my setup is in 'classic' confinement, meaning it currently works like a traditional package - allowing to read and write outside of its confinement. Can be changed to 'strict' in the future.
- All the dependences are in one package, but it also has[ 'Deduplication'](http://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-Snappy-Deduplication).

More info [here](https://snapcraft.io/).

**Comment by grochmal** [comment]
That would be like including RPM, YUM, and/or DEB files.  Just like it is Arch's, Red Hat's and Debian's responsibility to make the build for Vim, so should be Snappy's responsibility.  I do not believe that adding build problems for specific environments to the application problems dealt with in this repository is a good idea.

The MS Windows installers are a special case.

Also that version string in the YAML file is just horrible.  Vim changes too often for it to be valid for long, and it is not viable that people will update it.  That is a problem waiting to happen: people will keep reporting the wrong version in bugs.  And moreover, not even Arch or Gentoo compile every patch level of Vim, Arch compiles it about once every two weeks (unless really big changes are introduced) for example.

P.S. From the little I have just read about snappy, making a big and public database of such snapcraft.yaml files and make regular builds from them sound like a project on its own.  And a pretty good project to work on to be fair.

**Comment by GarethH96** [comment]
Just found this: https://build.snapcraft.io/.

**Comment by chrisbra** [comment]
we have the appimage repository. Perhaps we can integrate this PR into the appimage repository

**Comment by GarethH96** [comment]
Can you redo the check for AppVoyer? I tried it with my forked repo and it built perfectly fine.

**Comment by chrisbra** [comment]
can you please change your PR to apply to the vim-appimage repository? I don't think it will be applied here.

**Pull request closed without merging**
