### PR TITLE
ftplugin/spec.vim: Fix syntax error

### PR DESCRIPTION
**Pull request by jamessan**
Cc @ignatenkobrain

### CODE REVIEW

**Review by igor-raits — APPROVED** [review]
LGTM

**Comment by chrisbra** [comment]
could you adjust CODEOWNERS?

**Review by igor-raits — APPROVED** [review]

**Comment by brammool** [comment]
On top of this, can we remove the superfluous parenthesis at "if" statments?

**Comment by jamessan** [comment]
That's a style issue, which could be addressed separately, if at all.

**Comment by brammool** [comment]
I'll include it.

**Pull request closed without merging**
