### PR TITLE
Add :spellrare

### PR DESCRIPTION
**Pull request by arp242**
Add :spellrare as a compliment to :spellgood and :spellwrong.

I didn't add the normal mode commands, as zr and zR is already taken for
folding. I'm not sure which keys would make sense, if any? The only
letters that are still free are zp, zq, and zy. Another alternative
might be z?

### CODE REVIEW

**Comment by brammool** [comment]
This looks like a good idea.  I think using z? would be OK. I don't think there is something else that this command would do.  This is a todo note for using it to search in not-folded text, but that could perhaps better be done with a regexp item.
Please add a test.  :spell.  There is a test in test_normal.vim, but test_spell.vim is a better place.

**Comment by arp242** [comment]
I just realized that adding an upper-cased variant for z? to add a rare word to the internal word list will be impossible. Are we okay with that?

I think that would be fine, but just checking.

**Comment by chrisbra** [comment]
> I just realized that adding an upper-cased variant for z? to add a rare word to the internal word list will be impossible. Are we okay with that?

Fine with me. If I want to have a word marked as rare, I would like to have it marked not only for the current session, but always.

**Comment by brammool** [comment]
> I just realized that adding an upper-cased variant for z? to add a
> rare word to the internal word list will be impossible. Are we okay
> with that?
> 
> I think that would be fine, but just checking.

You are right, that restricts the usage.  I think we should try hard to
make this consistent.

We could use z/ and z?, on a US keyboard ? is the shifted character of
/.  But it's hard to see the relation with "rare".

There are not many "z" letter commands still available:
	zp
	zq
	zu
	zy

Perhaps zq/zQ could be used, as I can't think of any other use for them.
It's a bit dangerous though, since ZQ is equivalent to ":q!", drops all
changes.  Perhaps a warning would be sufficient?  Or the user could map
ZQ to zQ to avoid trouble, if he never uses ZQ now.

-- 
PRINCE:    He's come to rescue me, father.
LAUNCELOT: (embarrassed) Well, let's not jump to conclusions ...
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
On 2019-04-24, Bram Moolenaar wrote:
> 
> > I just realized that adding an upper-cased variant for z? to add a
> > rare word to the internal word list will be impossible. Are we okay
> > with that?
> >
> > I think that would be fine, but just checking.
> 
> You are right, that restricts the usage. I think we should try hard to
> make this consistent.
> 
> We could use z/ and z?, on a US keyboard ? is the shifted character of
> /. But it's hard to see the relation with "rare".
> 
> There are not many "z" letter commands still available:
> zp
> zq
> zu
> zy
> 
> Perhaps zq/zQ could be used, as I can't think of any other use for them.
> It's a bit dangerous though, since ZQ is equivalent to ":q!", drops all
> changes. Perhaps a warning would be sufficient? Or the user could map
> ZQ to zQ to avoid trouble, if he never uses ZQ now.

Using zQ when a slip of the shift-key finger could easily change it
to ZQ with disastrous results seems like a bad idea.  A warning
would be annoying, especially since one presumably would use ZQ
instead of :q! to avoid keystrokes.

How about zu/zU for z-uncommon?

Regards,
Gary

**Comment by arp242** [comment]
zu is part of the zug/zuG/zuw/zuW chains. I don't think we can use that (that was also my first choice!)

I don't think zQ/ZQ typos are that likely? At least, not how I type it. Perhaps it is different for others. More importantly, zq doesn't strike me as very mnemonic, whereas z? kind-of is. I think z/ makes more sense (or rather, it's the option that sucks the least).

**Comment by chdiza** [comment]
`:spellrare` seems niche enough that it doesn't even need normal-mode commands.  A user who would use :spellrare a lot can define mappings to ape `zg` etc.

**Comment by arp242** [comment]
Yeah, that's definitely an option as far as I'm concerned, and also the reason I didn't add any normal mode commands in the initial patch. I can add some docs on how to map it in the :spellrare docs for convenience.

**Comment by arp242** [comment]
I updated the PR to mention normal mode mappings in the docs, and I added a few tests. I put them in vim_spellfile.vim. That seemed to make sense to me, since it's testing spellfile.c. I can put it in vim_spell.vim too, if people prefer.

**Comment by bdesham** [comment]
@brammool If this PR were to be updated to merge cleanly, would you be willing to merge it? I’m happy to do the work as long as it wouldn’t be a wasted effort :-)

**Comment by brammool** [comment]
> @brammool If this PR were to be updated to merge cleanly, would you be
> willing to merge it? I’m happy to do the work as long as it wouldn’t
> be a wasted effort :-)

It seems useful and consistent.  I see you added a remark in the docs
about adding mappings, that's a reasonable answer to the Normal mode
command discussion.

-- 
To keep milk from turning sour: Keep it in the cow.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
I updated the patch; should apply cleanly to latest master now; tested again, and seems all good.

**Comment by arp242** [comment]
Should be good to merge @brammool @chrisbra ?

**Pull request closed without merging**
