### PR TITLE
Update readline syntax file with some new options

### PR DESCRIPTION
**Pull request by ralish**
Simply updates the syntax file with some newer readline options. Should be pretty uncontroversial :)

### CODE REVIEW

**Comment by chrisbra** [comment]
please discuss with the syntax script maintainer

**Comment by ralish** [comment]
Already tried to get in touch with the maintainer but never got a response sadly. Assuming this syntax file has no active maintainer given there's only a "Previous Maintainer" listed.

**Comment by chrisbra** [comment]
so would you volunteer to become the new maintainer?

**Comment by ralish** [comment]
What does being a syntax file maintainer entail? I'm not opposed to it, but I'm also not a readline developer, nor do I consider myself a Vim expert.

**Comment by ralish** [comment]
Any chance this could be merged? It's a trivial patch.

**Comment by brammool** [comment]
Nikolai gave up maintenance.  I'll include this change for now.  Hopefully a real maintainer comes forward.

**Pull request closed without merging**
