### PR TITLE
cache linux-modules-extra to reduce failed downloads

### PR DESCRIPTION
**Pull request by pheiduck**
This GitHub action install Linux APT packages and cache them for later use. When executed next time with same package list, and any other environment are not changed, installed files are extracted from the cached archive.

When valid cached archive is not found, all packages are installed by apt-get command. If you want partial install/cache behavior, use this action multiple times.
ref: https://github.com/marketplace/actions/install-and-cache-apt-tools#actions-use-apt-tools

### CODE REVIEW

**Comment by pheiduck** [comment]
Package seams not available at all.
Rebase later again when it is.

**Comment by chrisbra** [comment]
Yeah, I think we need to wait until github updates the runner images

**Comment by pheiduck** [comment]
todo:
re-enable:
```
sudo depmod --verbose
sudo modprobe --verbose snd-dummy
```

**Comment by chrisbra** [comment]
is this ready?

**Comment by pheiduck** [comment]
> is this ready?

Yes, but I would apply it when the image runner update is done.https://github.com/actions/runner-images/issues/8080#issuecomment-1680088869

**Comment by pheiduck** [comment]
@chrisbra I guess we can merge it.

**Pull request closed without merging**
