### PR TITLE
Improve test coverage of spelling suggestions

### PR DESCRIPTION
**Pull request by dpelle**
This PR improves test coverage of spelling suggestions to test:
* the spellsuggest() function
* the 'spellsuggest' option

### CODE REVIEW

**Comment by dpelle** [comment]
Please don't merge this PR yet.  The newly added tests triggered
a bug found by asan in Travis, which needs to be fixed first:

```
==21585== ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6074000140e8 at pc 0xa5caa5 bp 0x7ffe0c0425f0 sp 0x7ffe0c0425e8
READ of size 4 at 0x6074000140e8 thread T0
    #0 0xa5caa4 in cleanup_suggestions /home/travis/build/vim/vim/src/spellsuggest.c:3732
    #1 0xa79489 in spell_suggest_intern /home/travis/build/vim/vim/src/spellsuggest.c:1043
    #2 0xa7b7a5 in spell_suggest /home/travis/build/vim/vim/src/spellsuggest.c:535
    #3 0x80eb7f in nv_zet /home/travis/build/vim/vim/src/normal.c:3130
    #4 0x805c15 in normal_cmd /home/travis/build/vim/vim/src/normal.c:1071
    #5 0x618063 in exec_normal /home/travis/build/vim/vim/src/ex_docmd.c:7693
    #6 0x6182df in exec_normal_cmd /home/travis/build/vim/vim/src/ex_docmd.c:7656
    #7 0x618f06 in ex_normal /home/travis/build/vim/vim/src/ex_docmd.c:7582 (discriminator 6)
    #8 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #9 0x62a922 in do_cmdline_cmd /home/travis/build/vim/vim/src/ex_docmd.c:587
    #10 0x5a57fd in execute_common /home/travis/build/vim/vim/src/evalfunc.c:2052
    #11 0x5a5c54 in f_execute /home/travis/build/vim/vim/src/evalfunc.c:2099
    #12 0x5a14cb in call_internal_func /home/travis/build/vim/vim/src/evalfunc.c:983
    #13 0xb616ec in call_func /home/travis/build/vim/vim/src/userfunc.c:1664
    #14 0xb62da2 in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:482
    #15 0x5539d5 in eval_func /home/travis/build/vim/vim/src/eval.c:1695
    #16 0x56c3bb in eval7 /home/travis/build/vim/vim/src/eval.c:2739
    #17 0x56c856 in eval6 /home/travis/build/vim/vim/src/eval.c:2335
    #18 0x56d2d5 in eval5 /home/travis/build/vim/vim/src/eval.c:2126
    #19 0x56007c in eval4 /home/travis/build/vim/vim/src/eval.c:2008
    #20 0x560aa6 in eval3 /home/travis/build/vim/vim/src/eval.c:1928
    #21 0x56120b in eval2 /home/travis/build/vim/vim/src/eval.c:1860
    #22 0xb6294d in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:452
    #23 0xb63d8c in ex_call /home/travis/build/vim/vim/src/userfunc.c:3174
    #24 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #25 0xb6076c in call_user_func /home/travis/build/vim/vim/src/userfunc.c:1054
    #26 0xb62da2 in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:482
    #27 0xb63d8c in ex_call /home/travis/build/vim/vim/src/userfunc.c:3174
    #28 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #29 0x573a15 in ex_execute /home/travis/build/vim/vim/src/eval.c:6081
    #30 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #31 0xb6076c in call_user_func /home/travis/build/vim/vim/src/userfunc.c:1054
    #32 0xb62da2 in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:482
    #33 0xb63d8c in ex_call /home/travis/build/vim/vim/src/userfunc.c:3174
    #34 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #35 0x99a654 in do_source /home/travis/build/vim/vim/src/scriptfile.c:1214
    #36 0x99b1f0 in cmd_source /home/travis/build/vim/vim/src/scriptfile.c:805
    #37 0x99b5ad in ex_source /home/travis/build/vim/vim/src/scriptfile.c:831
    #38 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #39 0x62a922 in do_cmdline_cmd /home/travis/build/vim/vim/src/ex_docmd.c:587
    #40 0xd513b7 in exe_commands /home/travis/build/vim/vim/src/main.c:3129
    #41 0xd56e67 in main /home/travis/build/vim/vim/src/main.c:444
    #42 0x2b504cf09f44 in __libc_start_main ??:?
    #43 0x448458 in _start ??:?
0x6074000140e8 is located 24 bytes to the left of 9000-byte region [0x607400014100,0x607400016428)
allocated by thread T0 here:
    #0 0x2b5046a2b55f in __interceptor_realloc ??:?
    #1 0x7a0b03 in ga_grow /home/travis/build/vim/vim/src/misc2.c:2069
    #2 0xa62e6c in add_suggestion /home/travis/build/vim/vim/src/spellsuggest.c:3552 (discriminator 1)
    #3 0xa6d199 in suggest_trie_walk /home/travis/build/vim/vim/src/spellsuggest.c:1620
    #4 0xa78261 in suggest_try_change /home/travis/build/vim/vim/src/spellsuggest.c:1181
    #5 0xa7b7a5 in spell_suggest /home/travis/build/vim/vim/src/spellsuggest.c:535
    #6 0x80eb7f in nv_zet /home/travis/build/vim/vim/src/normal.c:3130
    #7 0x805c15 in normal_cmd /home/travis/build/vim/vim/src/normal.c:1071
    #8 0x618063 in exec_normal /home/travis/build/vim/vim/src/ex_docmd.c:7693
    #9 0x6182df in exec_normal_cmd /home/travis/build/vim/vim/src/ex_docmd.c:7656
    #10 0x618f06 in ex_normal /home/travis/build/vim/vim/src/ex_docmd.c:7582 (discriminator 6)
    #11 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #12 0x62a922 in do_cmdline_cmd /home/travis/build/vim/vim/src/ex_docmd.c:587
    #13 0x5a57fd in execute_common /home/travis/build/vim/vim/src/evalfunc.c:2052
    #14 0x5a5c54 in f_execute /home/travis/build/vim/vim/src/evalfunc.c:2099
    #15 0x5a14cb in call_internal_func /home/travis/build/vim/vim/src/evalfunc.c:983
    #16 0xb616ec in call_func /home/travis/build/vim/vim/src/userfunc.c:1664
    #17 0xb62da2 in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:482
    #18 0x5539d5 in eval_func /home/travis/build/vim/vim/src/eval.c:1695
    #19 0x56c3bb in eval7 /home/travis/build/vim/vim/src/eval.c:2739
    #20 0x56c856 in eval6 /home/travis/build/vim/vim/src/eval.c:2335
    #21 0x56d2d5 in eval5 /home/travis/build/vim/vim/src/eval.c:2126
    #22 0x56007c in eval4 /home/travis/build/vim/vim/src/eval.c:2008
    #23 0x560aa6 in eval3 /home/travis/build/vim/vim/src/eval.c:1928
    #24 0x56120b in eval2 /home/travis/build/vim/vim/src/eval.c:1860
    #25 0xb6294d in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:452
    #26 0xb63d8c in ex_call /home/travis/build/vim/vim/src/userfunc.c:3174
    #27 0x627447 in do_one_cmd /home/travis/build/vim/vim/src/ex_docmd.c:2485
    #28 0xb6076c in call_user_func /home/travis/build/vim/vim/src/userfunc.c:1054
    #29 0xb62da2 in get_func_tv /home/travis/build/vim/vim/src/userfunc.c:482
Shadow bytes around the buggy address:
  0x0c0effffa7c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0effffa7d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0effffa7e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0effffa7f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0effffa800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c0effffa810: fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa
  0x0c0effffa820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0effffa830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0effffa840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0effffa850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c0effffa860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
==21585== ABORTING
```
It's also reproducible with valgrind.

**Comment by dpelle** [comment]
In previous comment, I wrote:

> Please don't merge this PR yet. The newly added tests triggered
> a bug found by asan in Travis, which needs to be fixed first

I disabled a line in `Test_spellsuggest_option_number()` which
triggered the memory error.  See FIXME comment:
```
  " FIXME: the following line is currently commented out as it triggers a
  " memory error detected in cleanup_suggestions() by asan or valgrind.
  "call assert_equal("\nSorry, no suggestions", execute('norm z='))
```

All tests now pass.  The PR can thus be merged.  The bug with
invalid memory access when re-enabling this line can be fixed
separately.

The newly added tests also found memory leaks detected
by valgrind, which can also be fixed separately.
```
$ cat valgrind.test_spell 
==17358== Memcheck, a memory error detector
==17358== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==17358== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==17358== Command: ../vim -f --clean --cmd set\ enc=utf8 -v -S XtestSpell
==17358== Parent PID: 17357
==17358== 
==17358== 
==17358== HEAP SUM==17357== 
==17357== HEAP SUMMARY:
==17357==     in use at exit: 77,240 bytes in 884 blocks
==17357==   total heap usage: 241,454 allocs, 240,570 frees, 538,324,698 bytes allocated
==17357== 
==17357== 8 bytes in 1 blocks are definitely lost in loss record 12 of 140
==17357==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17357==    by 0x2064C0: lalloc (misc2.c:925)
==17357==    by 0x2073AB: alloc (misc2.c:828)
==17357==    by 0x2073AB: vim_strnsave (misc2.c:1294)
==17357==    by 0x2B59D0: spell_suggest (spellsuggest.c:649)
==17357==    by 0x21ECFF: nv_zet (normal.c:3130)
==17357==    by 0x22046E: normal_cmd (normal.c:1071)
==17357==    by 0x1A6B8C: exec_normal (ex_docmd.c:7688)
==17357==    by 0x1A6DEF: ex_normal (ex_docmd.c:7582)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x2E88E3: call_user_func (userfunc.c:1054)
==17357==    by 0x2E88E3: call_func (userfunc.c:1636)
==17357==    by 0x2E9052: get_func_tv (userfunc.c:482)
==17357==    by 0x2EBC4F: ex_call (userfunc.c:3174)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x17B175: ex_execute (eval.c:6081)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x2E88E3: call_user_func (userfunc.c:1054)
==17357==    by 0x2E88E3: call_func (userfunc.c:1636)
==17357==    by 0x2E9052: get_func_tv (userfunc.c:482)
==17357==    by 0x2EBC4F: ex_call (userfunc.c:3174)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x27F21E: do_source (scriptfile.c:1214)
==17357==    by 0x27FF80: cmd_source (scriptfile.c:805)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x32569F: exe_commands (main.c:3129)
==17357==    by 0x32569F: vim_main2 (main.c:795)
==17357==    by 0x1370C4: main (main.c:444)
==17357== 
==17357== 9 bytes in 1 blocks are definitely lost in loss record 13 of 140
==17357==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17357==    by 0x2064C0: lalloc (misc2.c:925)
==17357==    by 0x20735E: alloc (misc2.c:828)
==17357==    by 0x20735E: vim_strsave (misc2.c:1277)
==17357==    by 0x2B5A1A: spell_suggest (spellsuggest.c:653)
==17357==    by 0x21ECFF: nv_zet (normal.c:3130)
==17357==    by 0x22046E: normal_cmd (normal.c:1071)
==17357==    by 0x1A6B8C: exec_normal (ex_docmd.c:7688)
==17357==    by 0x1A6DEF: ex_normal (ex_docmd.c:7582)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x2E88E3: call_user_func (userfunc.c:1054)
==17357==    by 0x2E88E3: call_func (userfunc.c:1636)
==17357==    by 0x2E9052: get_func_tv (userfunc.c:482)
==17357==    by 0x2EBC4F: ex_call (userfunc.c:3174)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x17B175: ex_execute (eval.c:6081)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x2E88E3: call_user_func (userfunc.c:1054)
==17357==    by 0x2E88E3: call_func (userfunc.c:1636)
==17357==    by 0x2E9052: get_func_tv (userfunc.c:482)
==17357==    by 0x2EBC4F: ex_call (userfunc.c:3174)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x27F21E: do_source (scriptfile.c:1214)
==17357==    by 0x27FF80: cmd_source (scriptfile.c:805)
==17357==    by 0x1AAF1F: do_one_cmd (ex_docmd.c:2485)
==17357==    by 0x1AAF1F: do_cmdline (ex_docmd.c:975)
==17357==    by 0x32569F: exe_commands (main.c:3129)
==17357==    by 0x32569F: vim_main2 (main.c:795)
==17357==    by 0x1370C4: main (main.c:444)
```

**Comment by brammool** [comment]
Dominique wrote:

> In previous comment, I wrote:
> 
> > Please don't merge this PR yet. The newly added tests triggered
> > a bug found by asan in Travis, which needs to be fixed first
> 
> I disabled a line in `Test_spellsuggest_option_number()` which
> triggered the memory error.  See FIXME comment:
> ```
>   " FIXME: the following line is currently commented out as it triggers a
>   " memory error detected in cleanup_suggestions() by asan or valgrind.
>   "call assert_equal("\nSorry, no suggestions", execute('norm z='))
> ```
> 
> All tests now pass.  The PR can this be merged.  The bug with
> invalid memory access when re-enabling this line can be fixed
> separately.

It was using a negative index into an array.  I fixed it now.

> The newly added tests also found memory leaks detected
> by valgrind, which can also be fixed separately.

The values saved for spell replacement were not always freed.
I have a fix for that as well.

The spellsuggest tests are very slow, any way to make them go faster?

Executed Test_spellsuggest() in  12.366452 seconds
Executed Test_spellsuggest_option_expr() in  12.839129 seconds
Executed Test_spellsuggest_option_file() in   5.594766 seconds
Executed Test_spellsuggest_option_methods() in   3.824207 seconds
Executed Test_spellsuggest_option_number() in  15.025091 seconds


-- 
I still remember when I gave up Smoking, Drinking and Sex.  It was the
most *horrifying* hour of my life!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool asked:

> The spellsuggest tests are very slow, any way to make them go faster?
> 
> Executed Test_spellsuggest() in  12.366452 seconds
> Executed Test_spellsuggest_option_expr() in  12.839129 seconds
> Executed Test_spellsuggest_option_file() in   5.594766 seconds
> Executed Test_spellsuggest_option_methods() in   3.824207 seconds
> Executed Test_spellsuggest_option_number() in  15.025091 seconds

Strange. I don't see that.  Here are the timing on my
xubuntu-18.04 (x86_64) machine:
```
$ cd vim/src/testdir
$ make test_spell
...snip...
From test_spell.vim:
Executed Test_curswant() in   0.007053 seconds
Executed Test_region_error() in   0.002829 seconds
Executed Test_spell_long_word() in   0.007913 seconds
Executed Test_spell_screendump() in   0.045237 seconds
Executed Test_spellbadword() in   0.003602 seconds
Executed Test_spellfile_value() in   0.000254 seconds
Executed Test_spellinfo() in   0.030724 seconds
Executed Test_spellreall() in   0.043250 seconds
Executed Test_spellsuggest() in   0.429255 seconds
Executed Test_spellsuggest_option_expr() in   0.440372 seconds
Executed Test_spellsuggest_option_file() in   0.211579 seconds
Executed Test_spellsuggest_option_methods() in   0.125572 seconds
Executed Test_spellsuggest_option_number() in   0.513622 seconds
Executed Test_wrap_search() in   0.000425 seconds
Executed Test_z_equal_on_invalid_utf8_word() in   0.004462 seconds
Executed Test_zeq_crash() in   0.013429 seconds
Executed Test_zz_NOSLITSUGS() in   0.011990 seconds
Executed Test_zz_Numbers() in   0.006106 seconds
Executed Test_zz_affix() in   0.027004 seconds
Executed Test_zz_affix_flags() in   0.008474 seconds
Executed Test_zz_basic() in   0.012727 seconds
Executed Test_zz_compound() in   0.046529 seconds
Executed Test_zz_prefixes() in   0.009283 seconds
Executed Test_zz_sal_and_addition() in   0.010761 seconds
Executed 24 tests in   2.020647 seconds
```
Ha. I suppose that your slow timing was with valgrind.  Tests
`Test_spellsuggest_*()` are indeed slow with valgrind.
This is what I get with valgrind:
```
From test_spell.vim:
Executed Test_curswant() in   0.314502 seconds
Executed Test_region_error() in   0.059628 seconds
Executed Test_spell_long_word() in   0.199105 seconds
Executed Test_spell_screendump() in   2.829323 seconds
Executed Test_spellbadword() in   0.069221 seconds
Executed Test_spellfile_value() in   0.007327 seconds
Executed Test_spellinfo() in   0.455414 seconds
Executed Test_spellreall() in   1.059557 seconds
Executed Test_spellsuggest() in  11.663428 seconds
Executed Test_spellsuggest_option_expr() in  11.664320 seconds
Executed Test_spellsuggest_option_file() in   5.198323 seconds
Executed Test_spellsuggest_option_methods() in   3.616479 seconds
Executed Test_spellsuggest_option_number() in  13.406443 seconds
Executed Test_wrap_search() in   0.009163 seconds
Executed Test_z_equal_on_invalid_utf8_word() in   0.110837 seconds
Executed Test_zeq_crash() in   0.329156 seconds
Executed Test_zz_NOSLITSUGS() in   0.089976 seconds
Executed Test_zz_Numbers() in   0.029268 seconds
Executed Test_zz_affix() in   0.191219 seconds
Executed Test_zz_affix_flags() in   0.040544 seconds
Executed Test_zz_basic() in   0.097713 seconds
Executed Test_zz_compound() in   0.457638 seconds
Executed Test_zz_prefixes() in   0.054875 seconds
Executed Test_zz_sal_and_addition() in   0.064288 seconds
Executed 24 tests in  52.311964 seconds
```
Not sure why yet. I'll try to find out why.

**Comment by dpelle** [comment]
I wrote earlier:

> Ha. I suppose that your slow timing was with valgrind. Tests
> `Test_spellsuggest_*()` are indeed slow with valgrind.
> [...snip...]
> Not sure why yet. I'll try to find out why.

I created PR https://github.com/vim/vim/pull/5399 to speed up `Test_spellsuggest*()` tests.
See benchmarks in the PR.

**Pull request closed without merging**
