### PR TITLE
Fix listchars with composing character

### PR DESCRIPTION
**Pull request by mattn**
Repro step:

test.txt
```
  ゙       ゚

# vim:set list listchars=eol\:$,space\:_:
```

```
$ xxd test.txt
00000000: 2020 e382 9909 20e3 829a 0a0a 2320 7669    .... .....# vi
00000010: 6d3a 7365 7420 6c69 7374 206c 6973 7463  m:set list listc
00000020: 6861 7273 3d65 6f6c 5c3a 242c 7370 6163  hars=eol\:$,spac
00000030: 655c 3a5f 3a0a                           e\:_:.
```

When open this test.txt, composing character at 2nd byte is replaced to space character specified by modeline.

image

This should be:

image

### CODE REVIEW

**Comment by tonymec** [comment]
This setting is contrary to what is said at the bottom of `:help 'listchars'` (at line 5081 of the `options.txt` helpfile):
```
The characters ':' and ',' should not be used.
```

Best regards,
Tony.

**Comment by mattn** [comment]
@tonymec I don't understand what you mean. `:` and `,` must be escaped with backslash in modeline.

**Comment by brammool** [comment]
> Repro step:
> 
> test.txt
> ```
>   ゙       ゚
> 
> # vim:set list listchars=eol\:$,space\:_:
> ```
> 
> ```
> $ xxd test.txt
> 00000000: 2020 e382 9909 20e3 829a 0a0a 2320 7669    .... .....# vi
> 00000010: 6d3a 7365 7420 6c69 7374 206c 6973 7463  m:set list listc
> 00000020: 6861 7273 3d65 6f6c 5c3a 242c 7370 6163  hars=eol\:$,spac
> 00000030: 655c 3a5f 3a0a                           e\:_:.
> ```
> 
> When open this test.txt, composing character at 2nd byte is replaced to space character specified by modeline.
> 
> image
> 
> This should be:
> 
> image

The test passes even without including the code change.

I'm confused, because the title of the pull request mentions a composing
character, while the test doesn't have a composing character.

Is the problem that when a composing character is on top of a space, the space
gets replaced, even though the final character cell is not a space, since it
has the composing character on top?


-- 
How To Keep A Healthy Level Of Insanity:
15. Five days in advance, tell your friends you can't attend their
    party because you're not in the mood.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
@brammool It seems that vim replace composing characters to non-composing characters that I wrote in test code. Now I fixed test to use \uXXXX format. The test should be fail without changes.

**Comment by mattn** [comment]
>Is the problem that when a composing character is on top of a space, the space gets replaced, even though the final character cell is not a space, since it has the composing character on top?

Yes, it's a problem I want to fix.

**Comment by mattn** [comment]
You can download the file from below.

[testfile.txt](https://github.com/vim/vim/files/2913975/testfile.txt)

**Comment by mattn** [comment]
I noticed that I must fix screenchar() too.

**Comment by mattn** [comment]
@brammool Hmm, it seems difficult to fix screenchar(). But as far as I can see, this patch works well. Do you have any idea for testing this?

**Comment by brammool** [comment]
> @brammool Hmm, it seems difficult to fix screenchar(). But as far as I
> can see, this patch works well. Do you have any idea for testing this?

This might best be done with a screenshot test.  We should probably make
a buffer with some text where 'listchars' matter and make a screenshot
dump.

Is it possible to have a space with a double-width combining character?
It currently appears to mess up the screen.  I'm not sure what terminal
emulators do (or are supposed to do) with this.

-- 
hundred-and-one symptoms of being an internet addict:
30. Even though you died last week, you've managed to retain OPS on your
    favorite IRC channel.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>Is it possible to have a space with a double-width combining character?

Yes, this is an issue that "set list" break combining character that have space character at previous.

I'm using [mintty](https://github.com/mintty/mintty) on Windows.

I'll wait merge of https://github.com/vim/vim/pull/4059

**Comment by brammool** [comment]
Any luck updating the test so that it fails without the patch?

**Comment by k-takata** [comment]
> Any luck updating the test so that it fails without the patch?

I think that #4059 must be merged before this as mattn said.

**Comment by mattn** [comment]
@brammool Now merged master branch. And fixed test to use screenstring(). test is passed.

**Comment by ychin** [comment]
Hi, just a heads up, this commit seems to have broken some unicode characters. For example, either of these would break after this commit (either draw the wrong characters or just draw completely busted results) but they used to work:

* `set listchars=space:␣`
* `set listchars=space:→`

Haven't looked too closely into this yet. Will try to debug this a little.

**Comment by mattn** [comment]
Can you provide screen shot?

**Comment by ychin** [comment]
These are the test files:

````
a b
vim:set list listchars=space\:→:
````

````
c d
vim:set list listchars=space\:␣:
````

---

Before commit: 
image

image

---

After commit:
image

image

---

Note that hex code for "␣" is 0x2423, while "#" is 0x23. I haven't looked at code yet but are we assuming a long unicode char is a composing character?

Edit: Forgot to mention the platform for the screenshot is macOS using the default terminal. However, I have tested this in Windows GVim as well.

**Comment by mattn** [comment]
What encoding and $LANG do you use?

**Comment by ychin** [comment]
en-US / utf-8. You should be able to reproduce the bug just by comparing v8.1.1077 and v8.1.1078.

**Comment by ychin** [comment]
I have found the issue. When testing for space (' ') we need to also make sure it's not a composing character. I find that testing for `mb_l == 1` works. I have made a patch that seems to work. It basically reverts back to the original code but adds the `mb_l == 1` check. The reason I use the original code instead of the new code is that the new code doesn't properly store `extra_attr` and `saved_attr2` for nbsp which results in wrong syntax highlighting.

Diff:

````diff
diff --git a/src/screen.c b/src/screen.c
index c3cc8cdfa..fefb7432d 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -4809,33 +4809,28 @@ win_line(
 #endif
 
 		// 'list': change char 160 to lcs_nbsp and space to lcs_space.
-		if (wp->w_p_list)
-		{
-		    if ((c == 160
+		if (wp->w_p_list
+			&& (((c == 160
 			      || (mb_utf8 && (mb_c == 160 || mb_c == 0x202f)))
-			    && lcs_nbsp)
+				&& lcs_nbsp)
+			|| (c == ' ' && mb_l == 1 && lcs_space && ptr - line <= trailcol)))
+		{
+		    c = (c == ' ') ? lcs_space : lcs_nbsp;
+		    if (area_attr == 0 && search_attr == 0)
 		    {
-			c = lcs_nbsp;
-			mb_c = c;
-			if (enc_utf8 && utf_char2len(c) > 1)
-			{
-			    mb_utf8 = TRUE;
-			    u8cc[0] = 0;
-			    c = 0xc0;
-			}
-			else
-			    mb_utf8 = FALSE;
+			n_attr = 1;
+			extra_attr = HL_ATTR(HLF_8);
+			saved_attr2 = char_attr; /* save current attr */
 		    }
-		    else if (c == ' ' && lcs_space && ptr - line <= trailcol)
+		    mb_c = c;
+		    if (enc_utf8 && utf_char2len(c) > 1)
 		    {
-			c = lcs_space;
-			if (mb_utf8 == FALSE && area_attr == 0 && search_attr == 0)
-			{
-			    n_attr = 1;
-			    extra_attr = HL_ATTR(HLF_8);
-			    saved_attr2 = char_attr; // save current attr
-			}
+			mb_utf8 = TRUE;
+			u8cc[0] = 0;
+			c = 0xc0;
 		    }
+		    else
+			mb_utf8 = FALSE;
 		}
 
 		if (trailcol != MAXCOL && ptr > line + trailcol && c == ' ')
````

Diff against original code:

````diff
diff --git a/src/screen.c b/src/screen.c
index 7706b6c58..fefb7432d 100644
--- a/src/screen.c
+++ b/src/screen.c
@@ -4808,13 +4808,12 @@ win_line(
 		}
 #endif
 
-		/* 'list': change char 160 to lcs_nbsp and space to lcs_space.
-		 */
+		// 'list': change char 160 to lcs_nbsp and space to lcs_space.
 		if (wp->w_p_list
 			&& (((c == 160
 			      || (mb_utf8 && (mb_c == 160 || mb_c == 0x202f)))
 				&& lcs_nbsp)
-			|| (c == ' ' && lcs_space && ptr - line <= trailcol)))
+			|| (c == ' ' && mb_l == 1 && lcs_space && ptr - line <= trailcol)))
 		{
 		    c = (c == ' ') ? lcs_space : lcs_nbsp;
 		    if (area_attr == 0 && search_attr == 0)
````

**Comment by mattn** [comment]
```
  ゙       ゚

" vim:set list listchars=space\:␣:
```
image

It seems good to me.

**Comment by ychin** [comment]
Hmm, do you have encoding set to utf-8? What language/platform are you using? I'm surprised it worked fine for you. I have tested on macOS and Windows (terminal and GUI) and they seem to be broken.

The issue as I point out in my new pull-request (#4197) is that the original commit here didn't actually prevent the composing character (0x20) from getting processed by the if statement, so it seemed like a band-aid to just remove the unicode conversion portion of the code. It also disabled the nbsp's list character's syntax highlighting.

**Comment by mattn** [comment]
encoding=UTF-8. LANG=ja_JP.UTF-8

**Comment by mattn** [comment]
FYI, Where are not terminals that can display half-width composing string correctly (without mintty).

**Comment by ychin** [comment]
Hmm, I don't fully understand why your terminal mintty can handle display the '␣', but the change did break this for all the cases I have checked (macOS Terminal, macOS iTerm, MacVim, Windows GUI and Console). Also, the original change was not addressing the issue fully which should have recognized that the space character was in a composing sequence and therefore should not be drawn over (see the PR #4197 for more details), so I think it should still be fixed. I have added tests for validating the unicode situation as well.

**Pull request closed without merging**
