### PR TITLE
updated Finnish translation.

### PR DESCRIPTION
**Pull request by flammie**
- recoded to UTF-8
- all new messages translated

Hi, I got the announcement about upcoming vim-8 so I thought it’d be about time to update the translation

### CODE REVIEW

**Comment by brammool** [comment]
Flammie Pirinen wrote:

> - recoded to UTF-8
> - all new messages translated
> 
> Hi, I got the announcement about upcoming vim-8 so I thought it=E2=80=99d b=
> e about time to update the translation

Switching encoding with patch doesn't work very well.
Can you please send me the whole updated file?

## 

hundred-and-one symptoms of being an internet addict:
71. You wonder how people walk

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by flammie** [comment]
It should be attached to this bug report now. I had to rename it since github's bug reports don't support uploading files with different suffixes or something. You can also find it in the forked repo here: https://raw.githubusercontent.com/flammie/vim/5b1ba4c078c5b921a6adb3cb5c7d7e9e50349e7e/src/po/fi.po

[fi.po.txt](https://github.com/vim/vim/files/437657/fi.po.txt)

**Comment by brammool** [comment]
Flammie Pirinen wrote:

> It should be attached to this bug report now. I had to rename it since
> github's bug reports don't support uploading files with different
> suffixes or something. You can also find it in the forked repo here:
> https://raw.githubusercontent.com/flammie/vim/5b1ba4c078c5b921a6adb3cb5c7d7e9e50349e7e/src/po/fi.po
> 
> [fi.po.txt](https://github.com/vim/vim/files/437657/fi.po.txt)

Thanks.

Sourcing check.vim reveals a few errors:

Missing "msgstr" in line 675
Missing "msgstr" in line 2014
Mismatching error/warning code in line 4806

## 

Q: How many legs does a giraffe have?
A: Eight: two in front, two behind, two on the left and two on the right

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Bram Moolenaar vim-dev-github@256bit.org wrote:

> Flammie Pirinen wrote:
> 
> > It should be attached to this bug report now. I had to rename it since
> > github's bug reports don't support uploading files with different
> > suffixes or something. You can also find it in the forked repo here:
> > 
> > https://raw.githubusercontent.com/flammie/vim/5b1ba4c078c5b921a6adb3cb5c7d7e9e50349e7e/src/po/fi.po
> > 
> > [fi.po.txt](https://github.com/vim/vim/files/437657/fi.po.txt)
> 
> Thanks.
> 
> Sourcing check.vim reveals a few errors:
> 
> Missing "msgstr" in line 675
> Missing "msgstr" in line 2014
> Mismatching error/warning code in line 4806

The 3rd error look like a problem in fi.po, but
the first 2 errors (Missing "msgstr") are not.
The first 2 errors happen now in all languages if we update the po files,
as a result of introducing plural forms.  The problem is in the script
src/po/check.vim which does not cope with the new msgid_plural as in:

#, c-format
msgid "+-%s%3ld line: "
msgid_plural "+-%s%3ld lines: "
msgstr[0] "+-%s%3ld ligne : "
msgstr[1] "+-%s%3ld lignes : "

These come from fr.po, which I will submit soon after I complete
updating the translations.

Regards
Dominique

**Comment by flammie** [comment]
I fixed the error, sorry for that I don't know how I managed to miss it. It's attached again with changed suffix: 
[fi.po.txt](https://github.com/vim/vim/files/442120/fi.po.txt)

**Comment by brammool** [comment]
Included, thanks.

**Pull request closed without merging**
