### PR TITLE
Fix segfault in regexp engine due to uninitialized memory access

### LINKED ISSUE #465: vim segfaults in nfa_regtry
Lately vim's been segfaulting rather a lot when I try to edit ReStructuredText files.  Here's a stack trace of today's crash:

```
Core was generated by `/home/mg/src/vim/src/vim practices.rst'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9ee7b48597 in kill () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: Toks failas ar aplankas neegzistuoja.
(gdb) bt
#0  0x00007f9ee7b48597 in kill () at ../sysdeps/unix/syscall-template.S:81
#1  0x000000000055d10d in may_core_dump () at os_unix.c:3389
#2  0x000000000055d0b1 in mch_exit (r=1) at os_unix.c:3355
#3  0x0000000000645cc2 in getout (exitval=1) at main.c:1529
#4  0x00000000005152e5 in preserve_exit () at misc1.c:9622
#5  0x000000000055ae5e in deathtrap (sigarg=11) at os_unix.c:1118
#6  0x00007f9ee8366d10 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f9ee7bb83df in __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
#8  0x0000000000519212 in vim_strnsave (string=0xffffffffe9efdc88 <error: Cannot access memory at address 0xffffffffe9efdc88>, len=376904638)
    at misc2.c:1268
#9  0x0000000000591dd6 in nfa_regtry (prog=0xde18a0, col=0, tm=0x0) at regexp_nfa.c:6961
#10 0x00000000005921ba in nfa_regexec_both (line=0xd8dec3 "   Fix permissions so you won't expose /etc/shadow and other secret files ::", startcol=0, tm=0x0) at regexp_nfa.c:7085
#11 0x0000000000592616 in nfa_regexec_multi (rmp=0x7fff6cf7ce60, win=0x96f4b0, buf=0x970e50, lnum=306, col=0, tm=0x0) at regexp_nfa.c:7298
#12 0x0000000000592a50 in vim_regexec_multi (rmp=0x7fff6cf7ce60, win=0x96f4b0, buf=0x970e50, lnum=306, col=0, tm=0x0) at regexp.c:8276
#13 0x00000000005dfc59 in syn_regexec (rmp=0x7fff6cf7ce60, lnum=306, col=0, st=0xe629f8) at syntax.c:3284
#14 0x00000000005dd547 in syn_current_attr (syncing=0, displaying=1, can_spell=0x0, keep_state=0) at syntax.c:2097
#15 0x00000000005dcd17 in get_syntax_attr (col=0, can_spell=0x0, keep_state=0) at syntax.c:1854
#16 0x000000000059b98f in win_line (wp=0x96f4b0, lnum=306, startrow=1, endrow=34, nochange=1) at screen.c:4402
#17 0x0000000000596355 in win_update (wp=0x96f4b0) at screen.c:2012
#18 0x0000000000593950 in update_screen (type=35) at screen.c:679
#19 0x00000000004b7708 in getcmdline (firstc=47, count=1, indent=0) at ex_getln.c:1858
#20 0x0000000000534fd9 in nv_search (cap=0x7fff6cf7d810) at normal.c:6334
#21 0x000000000052bb81 in normal_cmd (oap=0x7fff6cf7d8a0, toplevel=1) at normal.c:1163
#22 0x0000000000645992 in main_loop (cmdwin=0, noexmode=0) at main.c:1351
#23 0x00000000006452a9 in main (argc=2, argv=0x7fff6cf7dbb8) at main.c:1050
```

**Steps to reproduce**
- git clone https://github.com/mgedmin/vim-bug-465
- cd vim-bug-465
- valgrind vim -u rst.vim --noplugins example.rst +redraw +q
- watch for valgrind errors about "Conditional jump or move depends on uninitialised value(s)"

### PR DESCRIPTION
**Pull request by mgedmin**
Fixes #465.

### CODE REVIEW

**Comment by mgedmin** [comment]
Huh, the coverage decrease is because I added a three-line comment.

I humbly suggest that counting comments as "untested lines of code" is a mistake.

**Comment by mgedmin** [comment]
OTOH it is true that the code I changed is not covered by any tests.

I'm not sure how to add a test for this.  I started playing with

```
STARTTEST
:set regexpengine=2
:set cpo&vim
:syn region rstLiteralBlock start='\z(.\)\@<=:' end='^$'
ENDTEST
```

and I just don't know where to go from there.

**Comment by chrisbra** [comment]
Good findings, thanks for figuring this out. I wonder, why nobody noticed this before.

I believe, since this usually segfaults vim, it should be enough to add some lines to the buffer, that would trigger the segfault. Just moving around and redrawing should be enough to trigger a segfault.

**Comment by mgedmin** [comment]
> Good findings, thanks for figuring this out. I wonder, why nobody noticed this before.

My guess is because this caused crashes only relatively rarely.  (About twice a month for me.)

> I believe, since this usually segfaults vim, it should be enough to add some lines to the buffer, that would trigger the segfault. Just moving around and redrawing should be enough to trigger a segfault.

That's the thing: it usually _doesn't_ cause a segfault.  Presumably the 

``` c
        if (mpos->start_lnum >= 0
            && mpos->start_lnum == mpos->end_lnum
            && mpos->end_col >= mpos->start_col)
```

condition is hard to satisfy with random numbers coming from uninitialized memory, and the segfault happens inside the

``` c
            vim_strnsave(reg_getline(mpos->start_lnum)
                                + mpos->start_col,
                         mpos->end_col - mpos->start_col);

```

call when start_col/end_col point way beyond the end of the line buffer, in the middle of unmapped memory.

**Pull request closed without merging**
