### PR TITLE
Add new motion ]( and ]{

### PR DESCRIPTION
**Pull request by mattn**
Vim has four paren motion `[(`, `[{`, `])` and `]}`. When following text is given and cursor is at `|`:

```
{foo(x, y|, bar(), baz());}
```

`])` is useful to remove arguments right side.

```
{foo(x, y);}
```

But `[(` is exclusive motion.

```
{foo(x, y, bar(), |baz());}
```

`[(` remove previous `(`:

```
{foobaz());}
```

test1

This is not useful.  So this change add new motion `](` and `]{`

screenshot

### CODE REVIEW

**Comment by justinmk** [comment]
`:help o_v` is the  usual way to switch incusive/exclusive behavior. So may `dv[(` should be "fixed", rather than adding these new motions?

**Comment by andymass** [comment]
@justinmk, this might be your exact point but the exclusive/inclusive terminology has always referred to the right-most character (assuming single line), not the end of the motion.  You would either have to change o_v fundamentally or add a new qualifier, e.g., `dx[(` 'left exclusive' which is a bit specific.

@mattn, it feels weird to me to press `]` to go leftwards.  Maybe `[)` makes more sense?

Alternatively `g(` and `g[(` should be free I think.

**Comment by mattn** [comment]
>Alternatively g( and g[( should be free I think.

Yes, but `g]` is already asigned by another meaning command.

**Comment by prabirshrestha** [comment]
What vim really needs is [tree-sitter](https://tree-sitter.github.io/tree-sitter/) which neovim has adopted.

This would allow us to query lot of interesting like "go to next function", "find all functions in a module", "go to next param", "delete previous params", "delete all params".

**Comment by marcotrosi** [comment]
> What vim really needs is [tree-sitter](https://tree-sitter.github.io/tree-sitter/) which neovim has adopted.
> 
> This would allow us to query lot of interesting like "go to next function", "find all functions in a module", "go to next param", "delete previous params", "delete all params".

I think Vim is and always should be a general editor, and should not only focus on code. So not every pair of braces are necessarily code. I prefer more general solutions.

**Comment by mattn** [comment]
How about using `<>` for inclusive motion instead of `[]` ? In this case:

```
{foo(x, y, |bar(), baz());}
```

`d[(` : exclusive motion so result is `{foo|bar(), baz());}`
`d])` : exclusive motion so result is `{foo(x, y, |)}`
`d<(` : inclusive motion so result is `{foo(|bar(), baz());}`
`d>)` : inclusive motion so result is `{foo(x, y, |)}` as same as `d])`

**Comment by justinmk** [comment]
> How about using `<>` for inclusive motion instead of `[]` ? In this case:

That is mildly more appealing, but still unappealing: adding new motions to change inclusive behavior, is a huge cognitive burden. It makes much more sense to have a modifier like `v` that modifies _existing motions_. Perhaps `<c-v>` could be used. Or `vv` ("both ends inclusive").

**Comment by tyru** [comment]
> `:help o_v` is the usual way to switch incusive/exclusive behavior. So may `dv[(` should be "fixed", rather than adding these new motions?

👍 to "fix" `dv[(`

**Comment by tyru** [comment]
> Perhaps `<c-v>` could be used. Or `vv` ("both ends inclusive").

`o_CTRL-V` already exists.
`vv` conflicts with `o_v`, but I realized that there is no matter if **the prefix of** operator-pending mode's mappings conflicts (it doesn't end until receiving more keys).
So `vv` seems OK to me.

**Comment by mattn** [comment]
Implemented `dvv[(`

**Comment by andymass** [comment]
Isn't `dvv[(` also a valid sequence in vim?  You can do arbitrary `dvvVvvVvv[(`

**Comment by justinmk** [comment]
> Isn't dvv[( also a valid sequence in vim

Did it do anything useful?

**Comment by brammool** [comment]
Changing the meaning only after an operator is strange.  The [{ and [( commands move on top of the { and (.  What we need is a similar command that moves to just before the character.

Keeping it two characters would be done with [X, where X is something not in use yet.  I don't see anything that hints about whether it would move towards a ( or {.

If we do use three characters, we can add a modifier.  What could work  is using g[( and g[{.
Unfortunately g] is already taken.

The other "modifier" command key is z.  That would work: z[ and z] are unused.  so we can add z[(, z[{, z]) and z]}.  This opens the possibility to modify other commands starting with [ and ].

**Comment by andymass** [comment]
> Unfortunately g] is already taken.

Does it really matter.. since it would be using `g[` / `g(` / `g{` which are not taken?  This is good because this is an asymmetrical motion, and the mapping e.g., `g[` is asymmetrically available.

**Comment by brammool** [comment]
> > Unfortunately g] is already taken.
> 
> Does it really matter.. since it would be using `g[` / `g(` / `g{`
> which are not taken?  This is good because this is an asymmetrical
> motion, and the mapping e.g., `g[` is asymmetrically available.

Well, you would be able to move to just after a ( with g[(, but you
would not be able to move to just before a ) in any way.
When used with an operator the motion is exclusive, thus has the same
effect, but if you are in Visual mode, or just want to move to that
character, it would not be possible.  It's just a matter of time someone
asks for it, and otherwise these commands are symmetrical, so why make
this one asymmetrical?

-- 
Facepalm statement #5: "Petrol getting more expensive?  Not for me, I'm always
tanking for 20 dollars"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by Houl** [comment]
`[t` and `]t` look unused.  And they remind of the `t` command.

**Comment by brammool** [comment]
So, then it would be [t(, [t{, ]t), ]t}.   It's a bit hard to type, but it's more of a hint than using z[ and z].
Allowing uppercase helps a bit: [T(, ]T}

**Comment by Houl** [comment]
IMHO, `z[` and `z]` should be reserved for future folding (or scrolling) commands.

**Comment by mattn** [comment]
Implemented zz.

**Comment by mattn** [comment]
z is assigned for zX (folding) operator. So I added `zz` for this.

**Comment by chrisbra** [comment]
> Implemented zz.

Hm, So how is `zz.` different from `zz` (redraw current line at the center) followed by `.` (redo)?

**Comment by brammool** [comment]
I thought the favorite choice was to use [t(, [t{, ]t) and ]t}, because "t" associates with the "t" movement - to (just before) character.

**Comment by marcotrosi** [comment]
> I thought the favorite choice was to use [t(, [t{, ]t) and ]t}, because "t" associates with the "t" movement - to (just before) character.

this at least sounds reasonable and the zz comments above make me panic a little bit.

But I think my favorite proposal is <> because it needs only 2 characters.

so [,] for inclusive and <,> for exclusive

Did I miss any disadvantages @mattn with that proposal?

P.S. the g] for :tselect is so lonesome in the list of g commands that I wouldn't even mind if this gets changed.

**Comment by marcotrosi** [comment]
I understand that pressing ]) and ]{ to go left is weird.

what if we swap it?

[(  [{   ])  ]} for inclusive left and right

[)  [}  ](  ]{ for exclusive left and right

Edit: probably also confusing, is it?

**Comment by Houl** [comment]
It's desirable when text-object keys and mappings work for both Omap and Visual mode, right?  I think this defeats both `<(` and `zz` (`v_<` shifts text, `v_zz` scrolls).

**Comment by mattn** [comment]
So which is best choice?

**Comment by k-takata** [comment]
+1 for `[t(` and `[t{`.

Not sure if we need `]t)` and `]t}`. The motions themselves might be useful, but combination with operators might be not so useful. Should they be inclusive or exclusive? If they are inclusive, `d]t)` is the same as `d])`. If they are exclusive, the meaning of `d]t)` is not intuitive.

@marcotrosi 
< and > are already used for shift-left-right.
Swapping the behavior breaks the compatibility.

**Comment by sheerun** [comment]
I thingk the best mappings would be:

- `ti)` i.e. until inner )
- `ti(` i.e. until inner (
- `ta)` i.e. until outer (
- `ta(` i.e. until outer (

e.g. `dti)` would remove everything until next inner )

**Comment by sheerun** [comment]
or to avoid ambiguity with `dti`:


- `it)` i.e. until inner )
- `it(` i.e. until inner (
- `at)` i.e. until outer (
- `at(` i.e. until outer (

so `dit)` for removing all until next inner )

**Comment by andymass** [comment]
@sheerun both dti/dta and dit/dat are already useful sequences in vim

**Comment by sheerun** [comment]
what dit / dat does?

**Comment by sheerun** [comment]
I see, then maybe `dui)` - delete until inner ), it's easier to type than `d]t)`

**Comment by chrisbra** [comment]
@mattn 
> So, then it would be [t(, [t{, ]t), ]t}.

Can you please make this change and rebase? I'll have a look to include this then.

**Comment by sheerun** [comment]
Good it wrote my reasoning because it's just question mark in my mind now. For the record right now I don't think introducing `[t(, [t{, ]t), ]t}` is much helpful, but rather creating a motion command that might be not "test proof" (like disallowing future version of braces) but "concept proof", like with such rule:

- upper case SOMETHING performs action on inner text of outer-closest bracket of cursor
- lower case SOMETHING performs action on inner text of outer-closest bracket of cursor + brackets

I have NO idea what shortcut should be, sorry. Maybe it should be even disallowed in scripting and allowed only with interactive use as I would vote bracket should change in time or per-language or both

**Comment by sheerun** [comment]
The extension of this idea is repeating motion character to select greater and greater blocks of code (lower case motion character or upper case motion character), and lesser and lesser blocks / ranges with shift + v. So like https://github.com/terryma/vim-expand-region I've used it 90% over vim-native motion commands for many years without much issues

**Comment by sheerun** [comment]
And if this issue is just for single-character range something, I would accept generic one after `t` (or something else) if possible so `[t<start>, ]t<end>}` for predefined table of `[[start, end], [start, end], [start, end]]` characters, so you can be done with this design decision forever, and just add characters. 

Maybe: `[[<char>` (select text inner up to char), `]]<char>` (select text up to char, and including it, so outer)

**Comment by chrisbra** [comment]
closing for now.

**Pull request closed without merging**
