### PR TITLE
refine pandoc compiler settings

### PR DESCRIPTION
**Pull request by Konfekt**
Make some settings configurable, just in case, and be less aggressive setting output document title, in particular if provided in source buffer

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks!

**Comment by chrisbra** [comment]
Hm, there seems to be a few issues with those changes. The makeprg setting does not include the `--standalone` and the errorformat uses invalid syntax. I think I fixed those, please verify with what I merge down. Thanks

**Comment by Konfekt** [comment]
Hm... the errorformat did not change; however, I found 

```
#  /usr/local/share/vim/vim91/doc/quickfix.txt (line 1599)
:set efm=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
```

So I suppose `\"%f\"` was intended. The makeprg still included `--standalone`? In any event, thank you for adjusting the change dates, which I forgot about.

**Comment by chrisbra** [comment]
- Ah perhaps those double quotes should have been escaped? Without those escapes, the local errorformat was empty, I think because the `"` was detected as an comment sign.

- With your version of the patch, the `--standalone` went missing. I assume this needs to be there right? I had to add an extra pair of parenthesis around this part here:
```
empty(b:pandoc_compiler_lang) ?
      \ '' : ' --metadata lang='..b:pandoc_compiler_lang .
      \ ' --from='..b:pandoc_compiler_from .
      \ ' '..get(b:, 'pandoc_compiler_args', get(g:, 'pandoc_compiler_args', ''))
```
otherwise, the `--standalone` got lost

**Comment by Konfekt** [comment]
Yes, exactly. I can reproduce and found the same fix (that I don't fully understand, but in general the more parentheses, the merrier for the computer, at least). Thank you for spotting this. So the only thing missing is escaping the double quotes in errorformat.

**Pull request closed without merging**
