### PR TITLE
translation: Stop using msgconv

### LINKED ISSUE #14490: Vim clone left "dirty" after make. src/po/ru.cp1251.po is modified.
### Steps to reproduce

I occasionally see this, and I think I've seen mention of this on the dev list; it might always be the same file; this morning I happened to catch it just after it happened. I also built yesterday morning. It doesn't happen too often (the revert file I see is from January), I haven't looked at makefiles, I don't know what dependency is triggering.

If anyone knows something specific to check...

After pull, make reconfig, the console shows the make ending as:
```
...
OLD_PO_FILE_INPUT=yes msgfmt -v -o vi.mo vi.po
1410 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_CN.UTF-8.mo zh_CN.UTF-8.po
2800 translated messages.
OLD_PO_FILE_INPUT=yes msgfmt -v -o zh_TW.UTF-8.mo zh_TW.UTF-8.po
1410 translated messages.
make[2]: Leaving directory '/ref/vim/src/po'
make[2]: Entering directory '/ref/vim/src/po'
OLD_PO_FILE_INPUT=yes msgfmt -v -o cs.cp1250.mo cs.cp1250.po
1272 translated messages.
...
OLD_PO_FILE_INPUT=yes msgfmt -v -o pl.cp1250.mo pl.cp1250.po
1858 translated messages.
rm -f ru.cp1251.po
iconv -f UTF-8 -t CP1251 ru.po | \
	LANG=C sed -e 's/charset=[uU][tT][fF]-8/charset=CP1251/' \
		-e 's/# Original translations/# Generated from ru.po, DO NOT EDIT/' \
		> ru.cp1251.po
OLD_PO_FILE_INPUT=yes msgfmt -v -o ru.cp1251.mo ru.cp1251.po
2979 translated messages.
...
make[2]: Leaving directory '/ref/vim/src/po'
make[1]: Leaving directory '/ref/vim/src'
err@harmony:/ref/vim/src
$ hg st
M src/po/ru.cp1251.po
```

The diff seems to be a lot of formatting. Here's an excerpt, as seen in vim.
```
-"W17: Äëÿ ðàáîòû ñ àðàáñêîé ïèñüìåííîñòüþ ââåäèòå êîìàíäó `:set "
-"encoding=utf-8`"
+"W17: Äëÿ ðàáîòû ñ àðàáñêîé ïèñüìåííîñòüþ ââåäèòå êîìàíäó `:set encoding=utf-8`"
```
It interesting that the wrap, as shown in vim above, is happening right around column 80. With all these formatting changes it's hard to see if there are any real changes.

Using `gvim -d` to look at the checked in file and the it looks like the only changes are around the linebreak and that the translation itself has no changes.

vdiff-translation

### Expected behaviour

No modified checked-in file.

### Version of Vim

9.1.0299

### Environment

ubuntu/gtk

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by k-takata**
It caused differences from Unix-like systems.
Make sure that the same files are generated both on Windows and Unix.

Closes #14490
Closes #14601

### CODE REVIEW

**Comment by RestorerZ** [comment]
Takata-san, yes, let's remove "msgconv" from the makefile.
But that won't fix the problem completely, unfortunately.

**Comment by RestorerZ** [comment]
Oh, you've already fixed the problem with "copy /a".  Thank you!

**Comment by errael** [comment]
A question from someone who doesn't work with the translation files. A big part of this change modifies `src/po/ru.cp1251.po`. 

With this PR, the use of `msgstr` is changed to no longer uses some kind line continuation/concatenation. Is that because the change from msgconv to iconv disallows it? And/or is using this line continuation a related problem? 

(or maybe `src/po/ru.cp1251.po` is a generated file that gets checked in? (I saw mention of something like that somewhere))

**Comment by errael** [comment]
Can #14601 be closed if this is merged?

**Comment by RestorerZ** [comment]
When converted via "msgconv", it changes the formatting of both "msgid" and "msgstr".


> Can #14601 be closed if this is merged?

Hopefully yes, the problem will be solved.

**Comment by k-takata** [comment]
@errael `ru.cp1251.po` is a generated file. msgconv may or may not change the line continuation depending on the environment.
OTOH, iconv always generates the same result.

**Comment by k-takata** [comment]
I also included the fix for this comment: https://github.com/vim/vim/issues/14490#issuecomment-2282210838
And, I found that there were still more outdated converted files. I also updated them.

**Comment by k-takata** [comment]
> I also included the fix for this comment: [#14490 (comment)](https://github.com/vim/vim/issues/14490#issuecomment-2282210838)

Ah, #15471 has been already created. I removed it from this PR.

**Comment by RestorerZ** [comment]
@k-takata 
Sorry, Takata-san, just wanted to clarify. What do you mean by "depends on the environment"? Are you referring to the libraries used, specifically "libunistring"? Or something else? I just don't understand that phrase very well in English.
In all systems and versions I checked, "msgconv" changed the line continuation for some strings. Unless, of course, the `--no-wrap` switch was specified and the default line width value of `79` was used.

**Comment by chrisbra** [comment]
thanks!

**Comment by k-takata** [comment]
@RestorerZ 
I had a misunderstanding. Yes, you are correct. msgconv converts the file in the same way.
The issue was that iconv and msgconv generated different output.

**Comment by RestorerZ** [comment]
Thank you, Takata-san, for the clarification.

**Pull request closed without merging**
