### PR TITLE
Add the tagfunc feature

### PR DESCRIPTION
**Pull request by chrisbra**
This PR is about the tagfunc patch, that has been floating around in vim-dev mailinglist for several years.
(e.g. [here](https://groups.google.com/forum/#!msg/vim_dev/jWXPP2II0YA/lYw3j74snnwJ), [here](https://groups.google.com/forum/#!msg/vim_dev/jWXPP2II0YA/lYw3j74snnwJ) and the original patch comes from Lech Lorens from this [discussion](https://groups.google.com/d/msg/vim_dev/nq4zuT-lCIQ/jF-JxCt7y3EJ) in the vim-dev mailing list.

Over the years I updated it every once in a while over at the [vim-mq-patches repository](https://github.com/chrisbra/vim-mq-patches/) but I figured, it might be useful, to have it as pending PR here.

The documentation looks like this:
,----[ :h 'tagfunc' ]-
| 							*'tagfunc'* *'tfu'*
| 'tagfunc' 'tfu'		string	(default: empty)
| 			local to buffer
| 			{not in Vi}
| 			{not available when compiled without the +eval
| 			or +insert_expand feature}
| 	This option specifies a function to be used to perform tag searches.
| 	The function should take two parameters, the first of which is the
| 	pattern to be searched, while the second is a set of flags which may
| 	be used by the function to decide on its behaviour. Currently the
| 	following flags may appear:
| 		'c' - indicates that the context around the cursor position
| 		      can be used to generate more accurate results,
| 		'i' - the function is being called during insert-mode
| 		      completion.
| 	See |tag-function| for an explanation of what the function should
| 	return and an example of such a function.
`----

License & Copyright:
© 2010 Robert Webb, Lech Lorens

### CODE REVIEW

**Comment by natebosch** [comment]
If we can be allowed to communicate the result asynchronously by calling another function after it is resolved we could use this to hook up a Language Server Protocol [`textDocument/definition`](https://microsoft.github.io/language-server-protocol/specification#textDocument_definition) request with all the nice keybindings around tags.

It's relatively easy to remap `CTRL-]`, but becomes more work when we also want to support `CTRL-W ]` and similar.

**Comment by chrisbra** [comment]
async only works for external/system functions. vimscript functions itself cannot be called asynchronously

**Comment by natebosch** [comment]
If we either pass in a callback to report the results, or provide another function to report the results then we can allow async work in between in vimscript.

For instances with `balloonexpr` I think you can return an empty string and then later call `balloon_show()` with the result.

Here's a strawman allowing a result asynchronously or synchronously as long as the delay is less than 250ms

```viml
function! MyTagFunc(OnResult) abort
  call timer_start(100, {_->a:OnResult('result')})
endfunction

function! TriggerTagFunc() abort
  let trigger_time = reltime()
  call MyTagFunc(funcref('UseTagResult', [trigger_time]))
endfunction

function! UseTagResult(trigger_time, result) abort
  let delay = reltime(a:trigger_time)
  " 250ms allowed delay
  if delay[0] > 0 || delay[1] > 250000 | return | endif
  echo 'Tag result: '.a:result
endfunction
```

And if the result is available synchronously the tagfunc would look like:

```viml
function! MyTagFunc(OnResult) abort
  call a:OnResult('Result')
endfunction
```

**Comment by chrisbra** [comment]
closing in favor of #4010

**Pull request closed without merging**
