### PR TITLE
Update METAFONT and MetaPost scripts.

### PR DESCRIPTION
**Pull request by lifepillar**
An overhaul of METAFONT and MetaPost scripts, just in time for the [0x20 birthday of METAFONT](https://www.youtube.com/watch?v=0LR_lBEy7qU).

I have tried to contact the authors of those scripts, but one email has bounced back I and did not get any reply in the last two weeks from the other two authors. So, I am submitting this as a pull request.

I am available to take over as a maintainer (I have already changed the header information in the scripts).

### CODE REVIEW

**Comment by brammool** [comment]
Lifepillar wrote:

> An overhaul of METAFONT and MetaPost scripts, just in time for the [0x20 birthday of METAFONT](https://www.youtube.com/watch?v=0LR_lBEy7qU).
> 
> I have tried to contact the authors of those scripts, but one email has bounced back I and did not get any reply in the last two weeks from the other two authors. So, I am submitting this as a pull request.
> 
> I am available to take over as a maintainer (I have already changed the header information in the scripts).

Please keep the original author or maintainer in the header to give him
credit.

I assume Lifepillar is not your real name.  I need to have the real name
for copyright purposes.  I would also prefer a real name in the runtime
files.

## 

Individualists unite!

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lifepillar** [comment]
> Please keep the original author or maintainer in the header to give him credit.

My apologies, I've fixed that.

**Comment by brammool** [comment]
Thanks. I haven't heard from former maintainers, thus I'll include this.

**Comment by lifepillar** [comment]
Thanks!
I've found a typo (a missing comma) in the ftplugin files. Should I open a new pull request or may you re-open this one?

**Comment by brammool** [comment]
Lifepillar wrote:

> Thanks!
> I've found a typo (a missing comma) in the ftplugin files. Should I
> open a new pull request or may you re-open this one?

You can just send me the updated file.

## 

Q:   How many hardware engineers does it take to change a lightbulb?
A:   None.  We'll fix it in software.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
