### PR TITLE
Replace "th" on "the", remove space after "!"

### PR DESCRIPTION
**Pull request by guraga**

### CODE REVIEW

**Comment by tonymec** [comment]
That Codecov report is complete BS. The only source file changed is one `.txt` helpfile, with nothing added, nothing removed, and minimal changes in two lines, and that "affects" nine `.c` C source files, "decreasing" coverage on seven of them? Bullshit.

**Comment by dpelle** [comment]
@tonymec wrote:

>  That Codecov report is complete BS.

No, I don't think it BS. It's probably correct.

The code coverage changed only by a tiny amount 0.01%.
I believe that what happens is that, we have some tests that are time dependent
(timers, etc.) and so, depending on runs, we don't always exercise exactly
the same lines of code.  In any case, the noise caused by this is tiny.

For example, the only coverage change in channel.c is in 'if' block
like this:

```
if (chanpart->ch_deadline.tv_usec > 1000 * 1000)
...
```
Clearly this is an example where coverage could vary from time to time.

Same in os_unix.c, I see a coverage change for this 'if' block:
```
if (wtime >= 0)
  /* no character available within "wtime" */
  return 0;
```

**Comment by nuko8** [comment]
> I believe that what happens is that, we have some tests that are time dependent (timers, etc.) and so, depending on runs, we don't always exercise exactly the same lines of code.

Plus, I think the same happens in interactions between Vim and the windowing system since such interactions are inherently asynchronous; no-reply and timeout do not necessarily imply fatal errors.  When either of them happens, that makes a difference between code paths Vim runs through.

Even if Vim  is running in non-GUI mode, they can happen since the system-clipboard integration and the client-server communication between Vim instances are all implemented using X11 inter-client communication API.  That's why `src/if_xcmdsrv.c`, `src/gui.c` and `src/gui_gtk_x11.c` always be there even if a given PR has nothing to do with any of them at any rate.

Although there's a way to have the windowing system synchronize Vim to eliminate such coverage uncertainties all at once,  that would get some of the tests so slow that people would rather prefer the current uncertainty to the cleanness brought by that forced synchronization.

**Comment by brammool** [comment]
I'll include the fixes, thanks.

**Pull request closed without merging**
