### PR TITLE
Fix color issues with GTK2 and GTK3 invert rectangle function

### PR DESCRIPTION
**Pull request by valacar**
Fix for issue #11110

### CODE REVIEW

**Comment by brammool** [comment]
Does this work with all kinds of colorschemes?
I wonder why it was using the norm_pixel and back_pixel combined before.

**Comment by valacar** [comment]
Yes it should work for all colorschemes. I tested all the default colorschemes that come with Vim and a few others, and didn't see any issues in either GTK2 or GTK3 builds. The colors are simply inverted so a color like #ff00ff becomes #00ff00, and #336699 becomes #cc9966. The operation is `abs(0xffffff - color)`. Applying the same operation again gives back the original color.

As for the previous XORing of norm_pixel and back_pixel, I'm not sure, but visually it appears to change the selection's background color to the Normal highlight group's foreground color, and then the text colors inside are inverted. I suppose it might fit better with the colorscheme, but inverting the colors (with my patch) usually gives a similar appearance.

Here's a screenshot comparison of the unpatch and patched version on GTK3 using a few stock colorschemes; it should be the same on GTK2.

vim-patch-compare-colorschemes

The main difference seems to be when using a black background with a non-white foreground like the murphy or elflord colorscheme.

**Comment by brammool** [comment]
So why did the original problem happen?  Because the operation applied could not be 100% reverted?  I assume an inversion always works to get back the original color when applied twice, which is why this fix uses that.  Or was the original problem a round-off error?

**Comment by valacar** [comment]
Yeah, it's just not properly being restored. I think the math is just wrong for GTK3. I found a rather extreme case using the default color scheme, but changing the Normal highlight group to green on gray. I started Vim with:

```
vim -g --clean +"hi Normal guifg=#00ff00 guibg=#999999" +"hi"
```

Here the background is `#999999`, and selecting turns it to `#003300` (dark green). The math is:

```
orig_color = 0x999999;
xor_mix = 0x00ff00 ^ 0x999999;  // = 0x996699, Normal highlight group's foreground xor'd with background
selected_color = abs(orig - xor_mix);  // = 0x003300 (dark green)
```

Then to restore the pixels colors when it's unselected, the operation is performed again over the top of the selected color (`#003300`) in the previous calculation. We're wanting to get back the original background color of `#999999`, but instead we get `#993399` (purple):

```
unselected_color = abs(selected_color - xor_mix); // = 0x993399 (purple)
```

vim-gtk3-bad-colors

The purple blocks in the screenshot should be restored back to the original gray background, but they're not.

I haven't really looked into the reason behind the GTK2 color issues yet.

**Pull request closed without merging**
