### PR TITLE
Full support for :terminal with VTP

### PR DESCRIPTION
**Pull request by ghost**
I have read a lot of codes.
I deepened my understanding and wrote this patch.
Mainly the behavior of the default color scheme has been improved.
Even Powershell.

I wish I could write this from the beginning, I think it was cool.

### CODE REVIEW

**Comment by brammool** [comment]
Nobuhiro Takasaki wrote:

> I have read a lot of codes.
> I deepened my understanding and wrote this patch.
> Mainly the behavior of the default color scheme has been improved.
> Even Powershell.
> 
> I wish I could write this from the beginning, I think it was cool.

I would appreciate a few people trying this out on their system and give
feedback.

-- 
This message contains 78% recycled characters.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
@ntak Could you explain what the current problem is and how can we check it?
Just running vim.exe on a PowerShell window?

**Comment by ghost** [comment]
Current problems:

1)
I set the color change to cmd.exe with ConsoleScreenBufferInfoEx.
At the time, it was not set to the syntax engine of vim.exe.
Therefore, the attribute did not catch up with the scroll up the ":terminal" window.
Currently, it is set to syntax engine.
Scroll up is not broken either.

2)
I fixes the foreground/background color index value to 0/7.
It was OK with cmd.exe, but Powershell uses 0/6, and the background color was wrong.
Currently, the index is acquired and set appropriately.
Even if you refresh the screen, the background color is still appropriate.

That's it.
Recently I am using Powershell. Because it was broken, I fixed it.
What to check programatically, for the time being, it seems to be correct visually.

**Comment by ghost** [comment]
What I want you to see is that it wants to contaminate the display of the window.
In my environment, anything did work stably.

**Comment by k-takata** [comment]
I confirmed the behavior with the following steps:

* Open a PowerShell window and execute vim.exe.
* Set `:colorscheme desert`, then `:set tgc`.
* Execute `:ver`.

Without your patch, the background of `:ver` becomes blue which is unexpected.
With the patch, the background of `:ver` becomes gray which is expected.

**Comment by ghost** [comment]
Thak you very much, it has become somehow fun.

**Pull request closed without merging**
