### PR TITLE
if_lua: stop on errors in vim.command() and vim.call()

### PR DESCRIPTION
**Pull request by arp242**
This stops execution if vim.command() or vim.call() failed. This fixes
two problems:

The first is the lack of line numbers if something failed:

	Error detected while processing command line..function <SNR>48_Cmd:
	line   13:
	E1174: String required for argument 2
	E1174: String required for argument 2
	E1174: String required for argument 2
	E1174: String required for argument 2
	[..repeated many times..]

It's not at all clear *what* command failed where, and vim.command()
always returns 0. With this, it's:

	Error detected while processing command line..function <SNR>49_Cmd:
	line   13:
	E1174: String required for argument 2
	lpeg.vim/lua/lpeg.lua:131: lua: function failed

Which is much more useful.

The second is that if you have some error in a loop you'll be spammed with
errors; this is #8649

---

The big downside with this patch is that it changes the behaviour; I don't know
if any scripts relied on execution continuing after errors, but they might.

However, Lua itself stops execution out if a (Lua) function failed, vim.eval()
did as well, and it generally just makes sense IMO. It's really confusing and
surprising otherwise

An alternative might be actually returning something from luaV_command();
luaV_call() already does so. You'll have to add "if not vim.command(...) then
error("command failed") end" to everything, which doesn't seem very "Lua-like".

Another point of improvement is that the errors for "vim.fn" are
confusing; for the same as above it prints:

	Error detected while processing command line..function <SNR>48_Cmd:
	line   13:
	E1174: String required for argument 2
	[string "vim.fn = setmetatable({}, {..."]:4: lua: call_vim_function failed

Which isn't very good. Need to look in to that.

(I'll update the tests and docs later once the behaviour is decided)

### CODE REVIEW

**Comment by brammool** [comment]
Martin Tournoij wrote:

> This stops execution if vim.command() or vim.call() failed. This fixes
> two problems:
> 
> The first is the lack of line numbers if something failed:
> 
> 	Error detected while processing command line..function <SNR>48_Cmd:
> 	line   13:
> 	E1174: String required for argument 2
> 	E1174: String required for argument 2
> 	E1174: String required for argument 2
> 	E1174: String required for argument 2
> 	[..repeated many times..]
> 
> It's not at all clear *what* command failed where, and vim.command()
> always returns 0. With this, it's:
> 
> 	Error detected while processing command line..function <SNR>49_Cmd:
> 	line   13:
> 	E1174: String required for argument 2
> 	lpeg.vim/lua/lpeg.lua:131: lua: function failed
> 
> Which is much more useful.
> 
> The second is that if you have some error in a loop you'll be spammed with
> errors; this is #8649
> 
> ---
> 
> The big downside with this patch is that it changes the behaviour; I
> don't know if any scripts relied on execution continuing after errors,
> but they might.

I do hope script writers avoid any errors.  At least they might upset
users.  Unless it happens very infrequent perhaps.

The argument that it keeps going and spits out tons of errors is a
strong one.  Perhaps that's worth taking a bit of a risk of breaking
something that relies on ignoring errors.

> However, Lua itself stops execution out if a (Lua) function failed, vim.eval()
> did as well, and it generally just makes sense IMO. It's really confusing and
> surprising otherwise
> 
> An alternative might be actually returning something from luaV_command();
> luaV_call() already does so. You'll have to add "if not vim.command(...) then
> error("command failed") end" to everything, which doesn't seem very "Lua-like".
> 
> Another point of improvement is that the errors for "vim.fn" are
> confusing; for the same as above it prints:
> 
> 	Error detected while processing command line..function <SNR>48_Cmd:
> 	line   13:
> 	E1174: String required for argument 2
> 	[string "vim.fn = setmetatable({}, {..."]:4: lua: call_vim_function failed
> 
> Which isn't very good. Need to look in to that.
> 
> (I'll update the tests and docs later once the behaviour is decided)

When using something like this:

	luaL_error(L, "lua: call_vim_command failed");

Does the string get included somehow?  Otherwise it's not very clear.


-- 
Microsoft's definition of a boolean: TRUE, FALSE, MAYBE
"Embrace and extend"...?

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
> When using something like this:
>
>	luaL_error(L, "lua: call_vim_command failed");
>
> Does the string get included somehow?  Otherwise it's not very clear.

It relies on the error message from  the error message from `do_cmdline_cmd()` and `call_vim_function()`; I tried copying the way Python does it with `VimTryStart()` and `VimTryEnd()`, but I couldn't get that to work. It's all a bit confusing as there are quite a few global variables and it's not always clear what gets set when, but `msg_list` was always NULL.

I can look at it again when we decide which way we want to go with this. I'd hate to break people's scripts, but on the other hand the current behaviour is mostly just annoying during development (in your final version you don't really want any errors), and I don't think all that many people are using the Lua integration, so I *think* it might be okay, but hard to be sure.

We can also add an option maybe, so you can do e.g. `vim.fatalerrors()` in your Lua script.

**Comment by brammool** [comment]
Martin Tournoij wrote:

> > When using something like this:
> >
> >	luaL_error(L, "lua: call_vim_command failed");
> >
> > Does the string get included somehow?  Otherwise it's not very clear.
> 
> It relies on the error message from  the error message from
> `do_cmdline_cmd()` and `call_vim_function()`; I tried copying the way
> Python does it with `VimTryStart()` and `VimTryEnd()`, but I couldn't
> get that to work. It's all a bit confusing as there are quite a few
> global variables and it's not always clear what gets set when, but
> `msg_list` was always NULL.

What I was thinking about is using a local buffer, using vim_snprintf()
to add the command to the error message.  That only works if the string
is used right away, not when the pointer is used later.

> I can look at it again when we decide which way we want to go with
> this. I'd hate to break people's scripts, but on the other hand the
> current behaviour is mostly just annoying during development (in your
> final version you don't really want any errors), and I don't think all
> that many people are using the Lua integration, so I *think* it might
> be okay, but hard to be sure.
> 
> We can also add an option maybe, so you can do e.g.
> `vim.fatalerrors()` in your Lua script.

-- 
Linux is just like a wigwam: no Windows, no Gates and an Apache inside.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by arp242** [comment]
Oh yeah, adding the actual command is easy: `luaL_error()` already does sprintf-style formatting. l actually I did that before but removed it because I felt it was a bit noisy for longer commands.

**Comment by chrisbra** [comment]
@arp242 is this still useful?

**Comment by arp242** [comment]
Probably?

I haven't worked with the Lua integration since 2021, so don't really know what the current status of it is.

I don't really have the time to look at this, and don't think I will in the foreseeable future. So I'll just close it.

**Pull request closed without merging**
