### PR TITLE
runtime(vim): Update base-syntax, match shebang lines

### PR DESCRIPTION
**Pull request by dkearns**
Match shebang lines in Vim9 and legacy script.

Mark these as an error if they appear anywhere other than the first line of a legacy-script file.  In Vim9 script these match as normal line comments rather than an error.

### CODE REVIEW

**Comment by chrisbra** [comment]
oh does this actually work? can we use a shebang line and run a vimscript directly? Is this documented somewhere?

**Comment by chrisbra** [comment]
Interesting, I wasn't aware. of this. I searched the help for `shebang` but didn't find anything, so let me add this help-tag

**Comment by Shane-XB-Qian** [comment]
> oh does this actually work? can we use a shebang line and run a vimscript directly? Is this documented somewhere? 

interesting too, but how to run it directly? i tried the example in its help, then `./foo.vim` seems failed.
// via bash cli

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
You need to make it executable: `chmod +x foo.vim && ./foo.vim`

**Comment by Shane-XB-Qian** [comment]
> You need to make it executable: `chmod +x foo.vim && ./foo.vim`

yes, it was executable; after look into a bit more, seems the example of help was not accurate, it maynot find vim without path.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
The example worked for me correctly. Of course you need to remove the `:q`

**Comment by Shane-XB-Qian** [comment]
no, just the shebang needed to specify where vim is as general shebang it is. :sweat_smile:
// but nevermind, it should be no common fixed answer where vim must be.

-- 
shane.xb.qian

**Comment by chrisbra** [comment]
How about this:
```
#!/bin/vim -S

let mylogbook='$HOME/logbook.md'
exe ':e ' .. mylogbook
$
put ='## ' .. strftime('%m. %b %Y')
norm! o
```

**Comment by Shane-XB-Qian** [comment]
no, first line was the matter.

**Pull request merged**
