### PR TITLE
mswin console - Shift+Insert to paste from clipboard

### PR DESCRIPTION
**Pull request by zewpo**
Resolves Issue #15326

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks, is it possible to add a test for this?

**Comment by zewpo** [comment]
I'm not sure how to write a test script for it.  The test needs to perform a copy into windows clipboard from outside of vim, (I'm not sure how to achieve that outside of vim at the moment.)  And also to make sure that the test is actually using the old windows console-host program, (not the new windows terminal), in that it passes the input into vim to be decoded.   The new windows terminal seems to paste correctly by default.     The test harness functions that I created (last year) was pretty good for testing most low level ms-windows input events, but I'm not sure how to do the copy from outside vim bit yet.   There might be a way to emulate what we think the console is doing.  To be honest, this code is so fragile, with all sorts of conditions for old windows ansi implementation stuff, its got a lot of legacy to deal with.

**Comment by chrisbra** [comment]
yeah, I wasn't sure if those low-level key events could be used for that. accessing the windows clipboard should be possible using something like `system('echo foobar |clip')` but I am not sure, if `clip.exe` is always available and also not sure how to test that Vim is running in the old cmd.com context. 

Okay, then let me merge this once the CI is "green". Thanks!

**Comment by zewpo** [comment]
@chrisbra   fyi, I'm not Christian, I think that was a typo from a while ago.  I'm Christopher.

**Comment by chrisbra** [comment]
Yes sorry, I should know. Typo on my side, since I have to type my name too often 🙈

**Pull request closed without merging**
