### PR TITLE
add missing items for vietnamise

### PR DESCRIPTION
**Pull request by lesorubshayan**
after merge close 10726

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks, please update the header of the file

**Comment by ronin49** [comment]
@chrisbra

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
Same comment as for #14685 

- Move the added translation to before the line resetting 'cpo' 
- Change the commit author

Thanks!

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
closing for the reasons mentioned here https://github.com/vim/vim/pull/14703#issuecomment-2092337585

**Pull request closed without merging**
