### PR TITLE
Update sshd config syntax highligher

### PR DESCRIPTION
**Pull request by Jakuje**
to current openssh 8.4p1

### CODE REVIEW

**Comment by k-takata** [comment]
Have you tried contacting the maintainer?

**Comment by Jakuje** [comment]
Opening a PR does not count as contacting a maintainer?

**Comment by k-takata** [comment]
No, each runtime file is maintained by each maintainer.
https://github.com/vim/vim/blob/master/CONTRIBUTING.md#syntax-indent-and-other-runtime-files

**Comment by Jakuje** [comment]
I contacted the maintainer without any answer. I also sent the email to vim-dev without any feedback for three weeks. So what is the procedure to get some changes in?

**Comment by chrisbra** [comment]
would you volunteer to maintain this file then?

**Comment by Jakuje** [comment]
Sure, if you point me to some guidelines/documentation what is expected from me if I would maintain this file.

**Comment by brammool** [comment]
Change the header to make Dominik "previous maintainer" and add yourself as the maintainer.
I haven't heard from Dominik for more than a year, and then he was very slow to respond.
It would be preferred to have a more active maintainer.

**Comment by chrisbra** [comment]
> Sure, if you point me to some guidelines/documentation what is expected from me if I would maintain this file.

There are no actual guidelines. 

Besides what Bram said, if you intend to maintain this file on a public repo, put the repo inside the runtime file so users can find it. Also, if new keywords are added by the openssh project, send updates as you feel comfortable with them.
Then of course it helps to be re-active and react to questions or issues that might arise. :)

But in general, this is not too much of an additional effort. I get barely any messages for e.g. the sqloracle syntax file that I maintain.

Also, please update the CODEOWNERS file.

**Comment by Jakuje** [comment]
Thanks for comments. I added couple of more missing algorithms and added myself as a new maintainer. Hope I will be able to cut some time for that with every new upstream release of OpenSSH.

I am fine updating it directly here rather than setting up a new repository for this.

**Comment by brammool** [comment]
I'll include it, thanks.

**Pull request closed without merging**
