### PR TITLE
Improved keystrokes under vim.exe pop-up

### PR DESCRIPTION
**Pull request by ghost**
Avoid missing characters when typing during completion.

### CODE REVIEW

**Comment by brammool** [comment]
Can you say more about why this change would fix something?
Appveyor fails with this change.

**Comment by mattn** [comment]
I've long been bothered by the phenomenon of losing some keys when typing keys quickly with vim.exe. Now I found this issue caused of the problem. I can confirm this patch seems fixing my issue.

**Comment by mattn** [comment]
My issue occur while typing keys quickly but always completion-popup was displayed.

**Comment by brammool** [comment]
Doesn't  dropping the WaitForChar() call cause a high CPU usage?
How about changing the first argument from -1 to 10 (wait for 10 msec).
Or perhaps WaitForChar() should be changed.

**Comment by mattn** [comment]
> Doesn't dropping the WaitForChar() call cause a high CPU usage?

As far as I looked CPU usage does not be high.

**Comment by brammool** [comment]
I would like to see an explanation why calling WaitForChar() would cause a problem.
It already loops to check for any events, with delays of up to 10 - 100 msec.
If 100 msec is too much, then perhaps changing the condition in line 1598 to always use a delay of 10 msec might help.
Dropping WaitForChar() also means not calling parse_queued_messages(), thus other things probably stop working.

**Comment by mattn** [comment]
10ms also works well for me.

**Comment by brammool** [comment]
> 10ms also works well for me.

OK, let me do it like that.  Please check for any side effects or heavy
CPU load.

-- 
LAUNCELOT: I am, sir. I am a Knight of King Arthur.
FATHER:    'Mm ... very nice castle, Camelot ... very good pig country....
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
My right arm and right eyeball are permanently paralyzed, and I want to reduce the amount of keyboard typing.
Below, only the main points.

The problem is check_due_timer(), the starting point of infinite recursion, right after the position where 8.2.2076 is applied.
The first position I submitted in this PR, WaitForChar(), the origin of infinite recursion.
Take a log and visually check up to quadruple recursion.

Event management, read_console_input(), peek and read do not match, complete collapse.
This was experimentally changed to the latch structure (ensuring the consistency of peek and read) that is also implemented in the external LSI, and there is no effect.

Increased CPU occupancy, anticipation, and ruthless infinite recursion due to the environment.

**Comment by ghost** [comment]
In my environment, there is no effect after applying the patch.
More than 10% of keystrokes disappeared by eye measurement.

**Comment by brammool** [comment]
> In my environment, there is no effect after applying the patch.
> More than 10% of keystrokes disappeared by eye measurement.

I do not understand how keystrokes can get lost.  Do you some completion
plugin perhaps?

Since this is timing critical, best way to debug is by using
ch_logfile() to start writing a log and put ch_log(NULL, "some remark")
in various places in the code.  There are timestamps so you can see if
there any delays.  You could type "abcdef" etc. and see if any letter
goes missing.

-- 
Proofread carefully to see if you any words out.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
Today, this still happend on my vim.exe.

**Comment by chrisbra** [comment]
It seems this does not fix the issue and has been stalled. So I am closing this.

**Pull request closed without merging**
