### PR TITLE
Restore default links with ":hi clear"

### LINKED ISSUE #4405: How to mitigate highlighting issues when switching colorschemes?
As you know, filetype-specific syntax items and colorscheme's switching don't go very well together—the emblematic discussion of the topic likely being https://github.com/altercation/solarized/issues/102.

In a nutshell, the issue can be reproduced as follows (using Vim 8.1.1300):

1. Create a minimal colorscheme `~/.vim/colors/test.vim`:

```vim
set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'test'
hi! link vimCommand ErrorMsg
hi vimOption cterm=reverse gui=reverse
```

2. Edit your `vimrc`;

3. `:colorscheme test`

4. `:colorscheme default`

You will see that `vimCommand` is still linked to `ErrorMsg` and `vimOption` is cleared.

I have thought hard about possible workarounds and my conclusion is that this issue has no solution—except avoiding using syntax items in colorschemes—unless some new mechanism (a new command?) is introduced in Vim to deal specifically with it. Am I right?

Note that avoiding syntax items in colorschemes is somewhat limiting, as one can realize by looking at two of the most popular colorschemes (Solarized and Gruvbox): people constantly ask to tweak the highlighting for specific filetypes.

### PR DESCRIPTION
**Pull request by adscriven**
Alternative to #6956. Retains the test for switching colorschemes added in test_highlight.vim in #6956.

problem: users are unable to restore default highlighting
solution: save default links on ":hi def link", restore them on "hi clear"

Fixes #4405

### CODE REVIEW

**Comment by habamax** [comment]
I would keep the old patch though too as cleared in my opinion should be treated as "has no highlight settings" anyway.

Also the test that covers actual issue with colorschemes is also nice to have:

```
" Test default highlighting links are restored
func Test_highlight_restore_default_links()

  hi def link TestLink Identifier

  let hlTestLinkPre = HighlightArgs('TestLink')

  " Test colorscheme
  hi clear
  if exists('syntax_on')
    syntax reset
  endif
  let g:colors_name = 'test'
  hi link TestLink ErrorMsg

  " Default links should be restored
  colorscheme default

  let hlTestLinkPost = HighlightArgs('TestLink')

  call assert_equal(hlTestLinkPre, hlTestLinkPost)
  hi clear
endfunc
```

Plus as we have issue with highlighting I would move your test to `test_highlight.vim`.

**Comment by habamax** [comment]
Nice!

So we need previous patch to be able to do `:hi def GroupName` for a cleared `GroupName`. Thx!

**Comment by adscriven** [comment]
@brammool  -- @habamax and I have finished preparing the PR if you wish to review. Thanks, --Antony

**Comment by habamax** [comment]
I have built and test it with all "fancy" colorschemes I have (they redefine a lot of filetype specific highlight groups), everything works as expected.

    :e $MYVIMRC
    :colo somefancycolorscheme
    :colo default

I get restored default colors immediately.

Thank you!

**Comment by brammool** [comment]
Thanks.  This changes behavior a bit, but it won't cause problems, right?  If someone finds that it breaks their existing setup, we probably only find out by including the patch.

**Comment by bfrg** [comment]
This patch breaks my setup! I have a lot of `:hi-link` settings in my `after/syntax/<filetype>.vim` files to override the default settings. For example in `after/syntax/c.vim`:
```vim
hi link cUserLabel Identifier
```
When I run `:color {name}`, the above link is lost and I have to run `:edit` to reload the entire file. This is madness! Imagine editing several dozen files.

Why was this patch added in the first place? The colorschemes mentioned in the above issues are broken to begin with. Why would anyone put filetype-specific highlightings into a colorscheme file? It just doesn't belong there.

**Comment by brammool** [comment]
Why do you use ":color {name}" after you started editing some file?  Especially if you already have some different colors setup.  I would say it's logical that after changing colorscheme some highlighting is overruled.  Which ones depend on the colorscheme, but you can assume it clears most colors first.

**Comment by bfrg** [comment]
> Why do you use ":color {name}" after you started editing some file?

There can be many reasons to change the colorscheme during a session. For example, discussing code with colleagues who prefer a lighter or darker colorscheme. It's not uncommon to change the colors of an application while it's running. I thought that was the whole point of this patch because people kept changing colorschemes which eventually broke their syntax highlighting. But that was always an issue with the colorschemes. If we start defining filetype-specific colors like `cUserLabel` in the colorscheme file, where will it end? There are just too many syntax groups for each filetype. It makes a lot more sense to only define the general groups in the colorschemes, that is, all names under `:h highlight-default` and `:h group-names`. (And maybe new ones could be added.)

This patch now forces me to put my filetype-specific highlight-links into the colorscheme file, or use an autocommand.  Why should Vim load highlight-links like `hi link cUserLabel Indentifier` (and potentially many others) when opening Vim to edit a `python` file?

> I would say it's logical that after changing colorscheme some highlighting is overruled. Which ones depend on the colorscheme, but you can assume it clears most colors first.

I don't have a problem with clearing the colors but I would like Vim to keep the user-defined highlight-links when switching colorschemes, like the one above `hi link cUserLabel Identifier`.

I thought the whole purpose of `hi-default` was to allow users to overrule the highlighting of a syntax file. The following is from `:h :hi-default`:
```
Using [default] is especially useful to overrule the highlighting of a
specific syntax file.  For example, the C syntax file contains: >
	:highlight default link cComment Comment
If you like Question highlighting for C comments, put this in your vimrc file: >
	:highlight link cComment Question
Without the "default" in the C syntax file, the highlighting would be
overruled when the syntax file is loaded.
```
The link defined with `:highlight link cComment Question` will be deleted after switching or reloading the current colorscheme.

**Comment by k-takata** [comment]
Any problems with using the ColorScheme autocommand?

**Comment by bfrg** [comment]
I was trying to avoid the `ColorScheme` event.

Anyway, I found a solution:
```vim
" ~/.vim/after/syntax/c.vim
highlight! default link cComment Question
```
This will override the `hi-default` link set in `$VIMRUNTIME/syntax/c.vim`. When changing colorschemes, this default link will be restored. Putting it into `after/syntax/c.vim` makes more sense to me than adding it to the colorscheme or `vimrc`. Now the line won't be sourced until editing a `c` file. It's also clear where the link was originally defined.

**Comment by mg979** [comment]
Btw there is some problem introduced by the recent PRs about colorschemes. Links defined by plugins don't work anymore after a colorscheme change. What's strange is that if you change colorscheme and do

    :hi groupname

It shows the correct link, but then it doesn't work.

Moreover, before changing scheme, I can complete the group's name on `hi` commands with wildmenu, after changing colorscheme, I cannot do this anymore.

I'm seeing this with https://github.com/tommcdo/vim-exchange

**Comment by habamax** [comment]
@mg979 the plugin uses "indirect" highlight link to self defined `ExchangeRegion` group.

After `colorscheme` run, `_exchange_region` is cleared because there is no default highlight defined.

I can `:XchangeHighlightDisable` and `:XchangeHighlightEnable` to restore it.

Then if I change `_exchange_region` to `ExchangeRegion` here:
https://github.com/tommcdo/vim-exchange/blob/13d3895709277d7b35bb4e30cc6ad0409a30ff0a/plugin/exchange.vim#L223

Then it doesn't loose the highlighting.

So the fix would be to add smth like:

```
highlight default link _exchange_region ExchangeRegion
```
right after the 

https://github.com/tommcdo/vim-exchange/blob/13d3895709277d7b35bb4e30cc6ad0409a30ff0a/plugin/exchange.vim#L327

@tommcdo fyi.

**Comment by mg979** [comment]
@habamax you're right, but this wasn't happening before this PR (I confronted 8.2.1702 and 8.2.1703). So you say that for a link to be restored, the `default` keyword must be used somewhere? This is customary for syntax files, but not really for plugins, as far as I can see. Also YouCompleteMe gutter signs are broken after colorscheme switch right now, and they weren't before. Also Ycm uses links, and doesn't define a `default` for its groups.

Maybe a default should be set automatically the first time a group is defined/linked. If this isn't possible, I don't think links without default should be reset. I bet this is causing trouble for the majority of plugins that define highlight groups, right now.

**Comment by mg979** [comment]
I mean... this PR maybe has fixed something but broken something else, and I don't think asking plugin makers to adapt is a good idea. I think there's some wrong logic in this PR and it should be fixed.

**Comment by habamax** [comment]
@mg979 with this patch all links are cleared and if there was a default -- it is restored after `:hi clear` which I expect to happen. 

Yes it will break plugins that assume links are persistent as they were before the patch.

I don't have an answer on how to make persistent links and at the same time make colorschemes be able to reset those persistent links. It is kind of opposite to each other.

**Comment by habamax** [comment]
I mean it is possible to revert this patch, but then again there will be even more ppl complaining colorschemes are broken.

**Comment by mg979** [comment]
Maybe @adscriven can say if it's possible to set a default automatically the first time a highlight group is defined/linked. After all the role of the `default` keyword is to avoid overwriting an existing group, not to actively set a default. It would still work that way, even if a default group is set every time a new group is defined, with or without the `default` keyword. I think this approach could fix the problem. Otherwise this is a broken patch, for me.

**Comment by habamax** [comment]
> Maybe @adscriven can say if it's possible to set a default automatically the first time a highlight group is defined/linked. After all the role of the `default` keyword is to avoid overwriting an existing group, not to actively set a default. 
> It would still work that way, even if a default group is set every time a new group is defined, with or without the `default` keyword. I think this approach could fix the problem. Otherwise this is a broken patch, for me.

The issue is not in setting default on colorscheme call, but the clearing of a linked highlight group.

I don't think this patch is a broken one, but indeed it breaks what vim has before it.

All in all it is way simpler to fix issues in the plugins by adding `default` to `:highlight` calls.

**Comment by mg979** [comment]
> The issue is not in setting default on colorscheme call, but the clearing of a linked highlight group.

I can see that linked groups from syntax files, using `default`, aren't cleared. So `default` prevents that. Instead, plugins that define their own groups, usually don't use `default`, and they break. You say plugins should handle that, but that would mean all plugins are broken now. Again, I think the fix I proposed above is valid.

And another point is that a patch that fixes a problem to create others isn't a patch, period. And for such a patch, to even ask _all_ plugins to adapt or suffer, is just intolerable. I don't mean to be harsh but this is what I think.

**Comment by mg979** [comment]
@adscriven  so if I understood how it works now, the `default` keyword sets a default to be restored when the group is cleared. But if the default keyword is never used, when the group is cleared, the default is missing and can't be restored. This is wrong. A default should never be missing. The first time the group is assigned/linked, with `default` keyword or not, a defaut should be assigned. The `default` keyword would simply protect from reassignment, this was its job before and this would still be.

**Comment by habamax** [comment]
@mg979 I don't think all plugins are broken, but you might know it better I guess.

So, we have a couple of options here:

* Plugin authors that are affected by this patch add `default` to their `:highlight` definitions
* You or somebody else create a PR fixing the issue further down the road
* Revert the patch -- we are back to ppl complaining about broken colorschemes

**Comment by mg979** [comment]
@habamax since @adscriven made the patch, he could know better how to fix this. About the options you say, I'm totally against 1., the second would be best, but I'd rather have 3. than a misbehaving fix.

**Comment by habamax** [comment]
> @habamax since @adscriven made the patch, he could know better how to fix this. About the options you say, I'm totally against 1., the second would be best, but I'd rather have 3. than a misbehaving fix.

Actually I have introduced the part that made it possible to "totally" clear highlighting, which is the key of the issue you are calling a misbehaving fix. Without clearing, existing links would be persisted and never reassigned to "default" values.

But ok, I will leave it to you and @adscriven.

**Comment by mg979** [comment]
> Actually I have introduced the part that made it possible to "totally" clear highlighting

The patch that causes the problem is this one. Tested by building and testing 1702 and 1703.

The point is: if now it's possible to set a default and restore it, a default should be set whenever a group is assigned the first time. A default should never be missing. I don't think it's that hard. But first you (and @adscriven ) should plainly admit that the patch has a problem, and asking all plugins to fix it on their own side isn't really a solution.

**Comment by habamax** [comment]
> The patch that causes the problem is this one. Tested by building and testing 1702 and 1703.

Yes, and it includes joint work of me and @adscriven, so you can blame me for the broken highlighting of plugins.

> should plainly admit that the patch has a problem

The patch solves the issue with colorschemes unable to apply all colors from scratch, yes, it breaks plugins that were relying on, in my opinion, bad behavior of vim persisting highlight links. Would you consider this as my admission?

Do you want it to be reverted? Create a PR, reverting it.

**Comment by mg979** [comment]
I'd rather have this PR fixed, this is my proposal. But if you think the PR doesn't need a fix, I won't say anything anymore.

- **case 1**: (currently ok)
	- a syntax file sets a default group
	- colorscheme changes, the group is restored to default


- **case 2**: (currently broken)
	- a plugin defines and assigns a group, without using the `default` keyword
	- colorscheme changes, the group is cleared
	- it isn't restored, because nobody used the `default` keyword
	- solution: assign a default, whenever a group is assigned the first time, with `default` keyword or not


- **case 3**: (would break with my proposed solution)
	- a colorscheme assigns a group, without using `default`, but it's the first to assign it, so it becomes the default
	- a syntax file defines a default, but the default has been assigned already
	- colorscheme changes, and what is restored is not the syntax default, but the one set by the first colorscheme
	- solution: using the `default` keyword doesn't overwrite the currently assigned group, but it overwrites its default group.

So that if you call `hi default` with different assignments, the second one wins, but more importantly, the default assigned by the syntax file would be restored, because using `default` keyword would set a new default.

**Comment by habamax** [comment]
> I'd rather have this PR fixed, this is my proposal. But if you think the PR doesn't need a fix, I won't say anything anymore.

Sure, fix it!

But bear in mind, not only syntax files should use `default`, in my opinion, it should be used by plugin authors to allow users/colorschemes to redefine highlights. An example is the vim-exchage plugin, it does it but only for a single highlight group.

**Comment by habamax** [comment]
Just for information, YouCompleteMe has been updated to use `:highlight default`.

**Comment by brammool** [comment]
It appears in this discussion too much emphasis is put on the word "default".  It was intended as "only set the highlighting if none is defined yet".  Thus if you would define highlighting in a vimrc somewhere and later encounter "default" highlighting, the first would be kept.  If encountering "default" highlighting while none was defined yet, then it applies.  That's all that the word "default" was intended for.
A colorscheme isn't expected to define highlighting for a specific syntax, only to define the generic colors, that syntax files link to.  It does not define "default" highlighting.  It's the syntax files that define "default" highlighting, thus use whatever was already defined and only adding highlighting that wasn't defined yet.

The confusing part appears to be that "hi clear" is supposed to reset highlighting to the defaults.  However, those are not the "hi default" values, but the default colorscheme values.  Thus the text "the defaults" is unclear.

Let's be practical instead of discussing terminology: We want setting a colorscheme to undo what the current colorscheme has defined, and using ":hi clear", used in the colorscheme, is supposed to do that.  We do not really want overrides on top of the old colorscheme to be undone, they should still apply on top of the new colorscheme.  The key question is: how do we know a highlight was defined by the colorscheme and not as an override?  It looks like we just don't have that information.

**Comment by mg979** [comment]
@brammool the `default` keyword has gained a new meaning with this PR. It sets the `hlgroup->sg_deflink` if it hasn't been set before, and this link is restored on `hi clear`.

The problem is that currently all groups are cleared, also links, and they are only restored if they had a default. This wasn't the case before, because links weren't cleared.

Many plugins don't use `hi default` when they create their own highlight groups, especially if it's for plugin internal stuff. But right now the `default` keyword is pretty much required, or links (or groups, whatever) will be cleared.

Requiring plugins to use the `default` for every highlight group they define is in my opinion excessive and should be avoided. Not to mention many plugins' highlight right now will be broken by `hi clear`.

My proposed solution is this:

- a default can be set by any highlight assignment, if a default link (`hlgroup->sg_deflink`) has not been set yet.
- the `default` keyword can replace this default link whenever it's used (without need for bang)

Because anyway the `default` keyword is mostly used in syntax scripts, or by plugins that define custom syntaxes, etc. Not by colorschemes obviously, but also not by plugins that use them internally. This way, when the `default` keyword is used, the default link can be updated. It will still work as before in the sense that the `default` keyword cannot change the _current_ link if it's defined. But it will be useful to update the default that is restored with `highlight clear`.

The whole fix I proposed is a one-line change:

```c
	    if (dodefault || hlgroup->sg_deflink == 0)
```

instead of the current:
```c
	    if (dodefault && (forceit || hlgroup->sg_deflink == 0))
```
https://github.com/vim/vim/blob/1c0aa97827f30e3051ee50a0690555c2c23c0ceb/src/highlight.c#L749

I compiled it and tested it, and it works for me. If @habamax could test it as well and give his opinion it would be great.

**Comment by brammool** [comment]
First of all: the original idea was that first the color scheme is set and then other things happen, which can then add to or overrule what the color scheme has done.
In some cases the user may try out different color schemes to see what they look like before deciding what to put in the vimrc.
Dynamically switching between color schemes wasn't really something that was considered.  We can see how much we can make this work, but I don't expect it to be smooth.

When a new color scheme is selected this basically means "throw everything away and define new colors".  If plugins define their own colors, the best is that they detect a color scheme switch (and possible 'background' changing) and redefine colors to fit in with the newly selected color scheme.  Or better: don't define any colors but link to the set of standard colors.
Using the ColorScheme autocommand should work best for that.

The problem that we're trying to fix here is that when defining a new color scheme it must be able to clear the existing colors.  But since there is no standard way to define colors, that's not so easy.  I do expect "hi clear" to clear ALL colors.  That colors defined by plugins are also removed is to be expected.

**Comment by mg979** [comment]
> The problem that we're trying to fix here is that when defining a new color scheme it must be able to clear the existing colors.

This is already happening, as far as I can see.

> But since there is no standard way to define colors, that's not so easy. I do expect "hi clear" to clear ALL colors. That colors defined by plugins are also removed is to be expected.

Yes, but now highlight groups have a hidden `default` that was set with the `default` keyword, and it is restored after `hi clear`. That's where the problem is right now, because one is forced to use the `default` keyword at least once for a highlight group, otherwise it's really cleared.

Because the condition to set/update a default is too restrictive:
```c
 if (dodefault && (forceit || hlgroup->sg_deflink == 0)) 
```

This is how I think things should work:

|command| can define a default the first time it is assigned|can overwrite the currently assigned group|can overwrite the current default|
|------------|------------|----------|----------|
|`hi {group} ...` |  yes     |   yes    |   no     |
|`hi default {group} ...`     |   yes    |   no     |   yes    |
|`hi! default {group} ...`     |   yes    |   yes    |   yes    |

What is happening now is:

- only `hi default` can set a default highlight
- `hi clear` clears ALL groups and links, then restores the ones for which a default was set
- but a default is needed or it won't be restored
- moreover the `default` keyword only sets a default the first time is used (unless with bang)
- only `hi! default` can update default again

What I think is better is shown above:

- all highlight commands can set a default if it was not set (even colorschemes)
- `hi clear` clears ALL groups and links, then restores the default that was set
- `hi default` can update/overwrite the default (done by syntax files/plugins)
- `hi! default` would still update both default and current link

Example:

- a syntax file defines a default for a group, colorscheme does not
- default is now syntax
- colorscheme changes, and it reassigns group
- default was already assigned by syntax, so it is restored on `hi clear`

Or:

- a colorscheme (or plugin) defines new groups, most of them still without a default set by a syntax file
- it's the first time vim sees those groups, so it sets a default for them (what the colorscheme/plugin has set)
- a syntax is loaded, and it contains `default` assignments for some groups: their underlying default is updated
- on `hi clear`, whatever is the default is restored: whether it came from a syntax file, or from the first plugin/colorscheme that defined it, doesn't matter anymore.

`hi! default {group}` is used to force a new default AND set immediately a new group.

I think it's very straightforward and fixes all issues. Right know it's

https://github.com/vim/vim/blob/1c0aa97827f30e3051ee50a0690555c2c23c0ceb/src/highlight.c#L749

that causes problem, because it's too restrictive in the ways it sets a default, and many times there won't be any default set.

Changing it to:
```c
  if (dodefault || hlgroup->sg_deflink == 0)
```

makes it work the way I described.

**Comment by bfrg** [comment]
@mg979 I think your suggestion has one flaw, if I understood you correctly. What if colorscheme **A** defines a few colors and hi-links to those colors (maybe for a certain plugin) but colorscheme **B** doesn't?

For example:
```vim
" colorschemeA.vim
hi Foo guibg=blue guifg=white ctermbg=4 ctermfg=7
hi link FooProperty Foo
```
while `colorschemeB.vim` doesn't have any of these highlight assignments for `Foo`. Now, if I switch colorschemes from **A** to **B**, the `hi-links` from **A** would stick around, wouldn't they? (since they would be automatically set as default, and defaults are restored). I don't think users would want that. When switching colorschemes, everything that was set by **A** should be removed.

--- 

You wrote:
> Many plugins don't use hi default when they create their own highlight groups, especially if it's for plugin internal stuff.

Why would a highlight group be used only for internal stuff? I can't think of an example. What do you mean by internal stuff? Any highlight group will be used in some way, otherwise you can get rid of it.

From what I've seen so far, the majority of plugins have always used `hi default link`. In my opinion fixing your plugin will cause less trouble in the future than changing it the way you described above.

**Comment by mg979** [comment]
> Now, if I switch colorschemes from A to B, the hi-links from A would stick around, wouldn't they? (since they would be automatically set as default, and defaults are restored). I don't think users would want that. When switching colorschemes, everything that was set by A should be removed.

I think you're wrong. This is exactly what is causing problems right now. A group is assigned for three reasons:

- by colorschemes: they generally assign groups for syntax elements, that have a `default` that is declared somewhere in some syntax file, otherwise the groups wouldn't even show up. All syntax files define `default` highlights, and if they don't do it, it's their problem. As such, you don't care if the default set by the colorscheme survives the `hi clear`, because a syntax file using `default` would update the default to the expected value. And if a colorscheme uses the `default` keyword, it's also its problem, because it shouldn't. But nobody does that. If the colorscheme assigns some plugin highlight (gutter signs etc) it will work anyway. Maybe it will assign a default if the group wasn't declared before. But you don't care, the plugin is free to use the `default` keyword to say: at `hi clear`, this will be the default. And if it doesn't do that, you have the old link, that's probably good anyway.

- by plugins: you don't want to clear those, as I said. The highlight they set should be considered default if not assigned before. There's no reason not to do it.

- by syntax files: they use `default` as a rule, so they would ensure that at `hi clear` the highlight group is reverted to the syntax default.

> I don't think users would want that.

I think they would want exactly that, for the reasons I explained.

**Comment by brammool** [comment]
Some information is missing:  There is a difference between setting a link and defining a color.
A color scheme can do something like:
hi link cComment SomewhatGreen
hi link pythonComment SomewhatBlue
When switching to another colorscheme these need to be cleared, and the "hi def link cComment Comment" and "hi def link pythonComment Comment" from the syntax file need to be restored.

If a plugin overrules cComment or pythonComment, well, we can't tell the difference so they will be cleared too.  And the plugin may check the value g:colors_name to decide what to do, we definitely can't know that.  That can only be solved by the plugin using a ColorScheme autocommand.

**Pull request closed without merging**
