### PR TITLE
MS-Win Remove unnecessary use of Unicode REPLACEMENT CHAR [ U+FFFD]

### PR DESCRIPTION
**Pull request by zewpo**
Problem:  The unicode REPLACEMENT CHAR [ U+FFFD] adds unnecessary complexity to decode_key_event
Solution:  Don't encode replacement chars in encode_key_event

Potentially Closes
https://github.com/vim/vim-win32-installer/issues/294

### CODE REVIEW

**Comment by zewpo** [comment]
This one is ready for review.

**Comment by brammool** [comment]
The commented out "Test for Function Keys 'F1' to 'F12'" doesn't look good.

**Comment by zewpo** [comment]
Ahh, yes, just the lines with the asserts statements were commented out before.
That Modifiers + Fn keys test  has never worked in CI testing - but it works fine in my build for some reason.

I'm still working on figuring out why it fails in CI - separate from this PR.

**Comment by zewpo** [comment]
Closing this, the PR with fix for the mod+Fn key groups will include this

**Pull request closed without merging**
