### PR TITLE
Add typst filetype

### PR DESCRIPTION
**Pull request by GaetanLepage**
This adds the `typst` filetype for [typst](https://typst.app) documents (`.typ` extension)

### CODE REVIEW

**Comment by zeertzjq** [comment]
This PR doesn't actually work, because `.typ` files are recognized as SQL in a previous autocommand.

**Comment by GaetanLepage** [comment]
> This PR doesn't actually work, because `.typ` files are recognized as SQL in a previous autocommand.

Indeed ! I tried to copy what is being done for "conflicting filetypes".

**Comment by brammool** [comment]
> This adds the `typst` filetype for [typst](https://typst.app)
> documents (`.typ` extension)

Please add a test for this in src/testdir/test_filetype.vim.
Also fix the expectance for "file.typ".


-- 
Q: What is the difference between open-source and commercial software?
A: If you have a problem with commercial software you can call a phone
   number and they will tell you it might be solved in a future version.
   For open-source software there isn't a phone number to call, but you
   get the solution within a day.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by GaetanLepage** [comment]
I am not able to find any reference to the fact that the `.typ` extension can be used for SQL files.
But I guess that we cannot take the liberty to remove completely the `.typ` - `sql` association, can we ?

If so, I would modify the PR to directly associate `.typ` files to the `typst` filetype.

**Comment by brammool** [comment]
> I am not able to find any reference to the fact that the `.typ`
> extension can be used for SQL files.
> But I guess that we cannot take the liberty to remove completely the
> `.typ` - `sql` association, can we ?
> 
> If so, I would modify the PR to directly associate `.typ` files to the
> `typst` filetype.

The comment mentions "SQL for Oracle Designer".  That's the only hint I
can find.  Perhaps someone knows if ".typ" files are actually in use and
deserved to be recognized as "sql"?

Otherwise, recognizing the filetype by the contents is the usual
approach.  Sql and typst are hopefully different enough to tell the
difference from the first few lines.


-- 
How To Keep A Healthy Level Of Insanity:
6. In the memo field of all your checks, write "for sexual favors".

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by GaetanLepage** [comment]
I was able to find documentation about those sql `.typ` files: https://docs.oracle.com/cd/A58617_01/server.804/a58234/ott.htm

I rewrote the detection code and the test.
Now it tries to find the typical content of an sql type definition file and, if it is not able to do so, it affects the `typst` filetype.

**Pull request closed without merging**
