### PR TITLE
Distinguish between zg and zG, and zw and zW

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by vim-ml** [comment]
On 2020-05-25, Ned Batchelder wrote:
> -------------------------------------------------------------------------------
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/6140
> 
> Commit Summary
> 
>   • Distinguish between zg and zG, and zw and zW
> 
> File Changes
> 
>   • M runtime/doc/index.txt (4)
> 
> Patch Links:
> 
>   • https://github.com/vim/vim/pull/6140.patch
>   • https://github.com/vim/vim/pull/6140.diff

> diff --git a/runtime/doc/index.txt b/runtime/doc/index.txt
> index 78d557f51ef..0fa774cd656 100644
> --- a/runtime/doc/index.txt
> +++ b/runtime/doc/index.txt
> @@ -828,7 +828,7 @@ tag         char          note action in Normal mode        ~
>  |zD|           zD                 delete folds recursively
>  |zE|           zE                 eliminate all folds
>  |zF|           zF                 create a fold for N lines
> -|zG|           zG                 mark word as good spelled word
> +|zG|           zG                 internally mark word as good spelled word
>  |zH|           zH                 when 'wrap' off scroll half a screenwidth
>                                    to the right
>  |zL|           zL                 when 'wrap' off scroll half a screenwidth
> @@ -837,7 +837,7 @@ tag         char          note action in Normal mode        ~
>  |zN|           zN                 set 'foldenable'
>  |zO|           zO                 open folds recursively
>  |zR|           zR                 set 'foldlevel' to the deepest fold
> -|zW|           zW                 mark word as wrong (bad) spelled word
> +|zW|           zW                 internally mark word as bad spelled word
>  |zX|           zX                 re-apply 'foldlevel'
>  |z^|           z^                 cursor on line N (default line above
>                                    window), otherwise like "z-"

I don't think "internally" conveys the distinction very clearly.
How about "temporarily"?  Or even "for this session only", at the
expense of extra lines?

    zG       zG          mark word as good spelled word for this
                         session only

    zW       zW          mark word as wrong (bad) spelled word for
                         this session only

    zg       zg          mark word as good spelled word and save

    zw       zw          mark word as wrong (bad) spelled word and
                         save

Regards,
Gary

**Comment by nedbat** [comment]
I wasn't proposing to change the terminology. The help for zG says, "Like "zg" but add the word to the internal word list."  My goal here was to differentiate the index entries for zg and zG, which now are identical.

I'm fine with some other wording.

**Comment by chrisbra** [comment]
How about:

```patch
diff --git a/runtime/doc/index.txt b/runtime/doc/index.txt
index 78d557f51..dded70d32 100644
--- a/runtime/doc/index.txt
+++ b/runtime/doc/index.txt
@@ -828,7 +828,7 @@ tag         char          note action in Normal mode        ~
 |zD|           zD                 delete folds recursively
 |zE|           zE                 eliminate all folds
 |zF|           zF                 create a fold for N lines
-|zG|           zG                 mark word as good spelled word
+|zG|           zG                 temporarily mark word as good spelled word
 |zH|           zH                 when 'wrap' off scroll half a screenwidth
                                   to the right
 |zL|           zL                 when 'wrap' off scroll half a screenwidth
@@ -837,7 +837,7 @@ tag         char          note action in Normal mode        ~
 |zN|           zN                 set 'foldenable'
 |zO|           zO                 open folds recursively
 |zR|           zR                 set 'foldlevel' to the deepest fold
-|zW|           zW                 mark word as wrong (bad) spelled word
+|zW|           zW                 temporarily mark word as bad spelled word
 |zX|           zX                 re-apply 'foldlevel'
 |z^|           z^                 cursor on line N (default line above
                                   window), otherwise like "z-"
@@ -849,7 +849,7 @@ tag         char          note action in Normal mode        ~
                                   position the cursor at the end (right side)
                                   of the screen
 |zf|           zf{motion}         create a fold for Nmove text
-|zg|           zg                 mark word as good spelled word
+|zg|           zg                 permanently mark word as good spelled word
 |zh|           zh                 when 'wrap' off scroll screen N characters
                                   to the right
 |zi|           zi                 toggle 'foldenable'
@@ -870,7 +870,7 @@ tag         char          note action in Normal mode        ~
 |zuW|          zuW                undo |zW|
 |zuG|          zuG                undo |zG|
 |zv|           zv                 open enough folds to view the cursor line
-|zw|           zw                 mark word as wrong (bad) spelled word
+|zw|           zw                 permanently mark word as bad spelled word
 |zx|           zx                 re-apply 'foldlevel' and do "zv"
 |zz|           zz                 redraw, cursor line at center of window
 |z<Left>|      z<Left>            same as "zh"
```

**Comment by vim-ml** [comment]
On 2020-05-25, Christian Brabandt wrote:
> How about:
> 
> diff --git a/runtime/doc/index.txt b/runtime/doc/index.txt
> index 78d557f51..dded70d32 100644
> --- a/runtime/doc/index.txt
> +++ b/runtime/doc/index.txt
> @@ -828,7 +828,7 @@ tag         char          note action in Normal mode        ~
>  |zD|           zD                 delete folds recursively
>  |zE|           zE                 eliminate all folds
>  |zF|           zF                 create a fold for N lines
> -|zG|           zG                 mark word as good spelled word
> +|zG|           zG                 temporarily mark word as good spelled word
>  |zH|           zH                 when 'wrap' off scroll half a screenwidth
>                                    to the right
>  |zL|           zL                 when 'wrap' off scroll half a screenwidth
> @@ -837,7 +837,7 @@ tag         char          note action in Normal mode        ~
>  |zN|           zN                 set 'foldenable'
>  |zO|           zO                 open folds recursively
>  |zR|           zR                 set 'foldlevel' to the deepest fold
> -|zW|           zW                 mark word as wrong (bad) spelled word
> +|zW|           zW                 temporarily mark word as bad spelled word
>  |zX|           zX                 re-apply 'foldlevel'
>  |z^|           z^                 cursor on line N (default line above
>                                    window), otherwise like "z-"
> @@ -849,7 +849,7 @@ tag         char          note action in Normal mode        ~
>                                    position the cursor at the end (right side)
>                                    of the screen
>  |zf|           zf{motion}         create a fold for Nmove text
> -|zg|           zg                 mark word as good spelled word
> +|zg|           zg                 permanently mark word as good spelled word
>  |zh|           zh                 when 'wrap' off scroll screen N characters
>                                    to the right
>  |zi|           zi                 toggle 'foldenable'
> @@ -870,7 +870,7 @@ tag         char          note action in Normal mode        ~
>  |zuW|          zuW                undo |zW|
>  |zuG|          zuG                undo |zG|
>  |zv|           zv                 open enough folds to view the cursor line
> -|zw|           zw                 mark word as wrong (bad) spelled word
> +|zw|           zw                 permanently mark word as bad spelled word
>  |zx|           zx                 re-apply 'foldlevel' and do "zv"
>  |zz|           zz                 redraw, cursor line at center of window
>  |z<Left>|      z<Left>            same as "zh"

I like it.

Regards,
Gary

**Comment by brammool** [comment]
I'll include Christians suggestion.

**Pull request closed without merging**
