### PR TITLE
[vim9class] Fix `string()` to handle an object's function ref.

### LINKED ISSUE #15129: [vim9class] incorrect `string()` of funcref of object's function
### Steps to reproduce

```
vim9script

class C
    def C_F()
    enddef
endclass

var o = C.new()
var F = o.C_F
echo string(F)
```
outputs
```
function('g:C_F')
```

### Expected behaviour

I'm not sure what's correct, `function('object of C: C_F')`  seems weird but it does match a few patterns.

### Version of Vim

9.1.516

### Environment

ubuntu/gtk3

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by errael**
Fix #15129.

### CODE REVIEW

**Comment by errael** [comment]
Rebased.

@yegappan Could you  take a look? A question is if the check for a partial being a class method is OK.

**Comment by errael** [comment]
Huh, I just noticed that there's a comment I made that I can't find. Guess I didn't push the button.

This change brings the output of `string()` for an object function in line with what is looks like in a stack trace, #14390

**Comment by errael** [comment]
There's an error in `vimtags`, doesn't look familiar; maybe from the rebase. Is there anything I need to do?

**Comment by chrisbra** [comment]
> There's an error in vimtags, doesn't look familiar; maybe from the rebase. Is there anything I need to do?

that is strange, running `cd runtime/doc; make; git diff` is clean here. Looking at the diff in CI seems like it suddenly adds tags which are inside code samples in the help file. However, I cannot reproduce the failure on my side. It's clean here...

**Comment by chrisbra** [comment]
this should have been fixed by #10813 (Patch v9.0.0110), not sure why this happens now in CI again.

**Comment by errael** [comment]
> this should have been fixed by #10813 (Patch v9.0.0110), not sure why this happens now in CI again.

Fix for this found in https://github.com/vim/vim/pull/15099#issuecomment-2211425224

**Comment by chrisbra** [comment]
Thanks, I think this makes sense. Not sure about the question for partials

**Comment by errael** [comment]
1 char change to test in PR. Need to escape a `.` in `assert_match` pattern.

**Comment by errael** [comment]
> > A question is if the check for a partial being a class method is OK.

> Not sure about the question for partials

We can say that it is not not OK since the test does work.

The `pt_obj` field was added with https://github.com/vim/vim/commit/29bb67f1beefc7fd393dbfd9ee77d92f1db3a3c0 specifically for "object funcref members" so it's probably a good check.

**Comment by chrisbra** [comment]
thanks, let me include it now.

**Pull request closed without merging**
