### PR TITLE
Add complete_info() function

### PR DESCRIPTION
**Pull request by h-east**
Once the specification is decided, refactor, update the document and add more tests.

```
complete_info([{what}])
		Returns a Dictionary with information about insert mode
		completion.  see |ins-completion|.
		The items are:
		   mode		current completion mode name string.
				See |completion_info_mode| for the values.
		   pum_visible	|TRUE| if popup menu is visible.
				See |pumvisible()|.
		   items	List of completion matches.  Each item is a
				dictionary containing the entries "word",
				"abbr", "menu", "kind", "info" and "user_data".
				See |complete-items|.
		   selected	Selected item index.  First index is zero.
				Set -1 if not selected.
		   inserted	Inserted string. [NOT IMPLEMENT YET]

							*complete_info_mode*
		mode values are:
		   ""		Not in completion mode
		   "keyword"	Keyword completion |i_CTRL-X_CTRL-N|
		   "ctrl_x"	Just press |i_CTRL-X|
		   "whole_line"	Whole lines |i_CTRL-X_CTRL-L|
		   "files"	File names |i_CTRL-X_CTRL-F|
		   "tags"	Tags |i_CTRL-X_CTRL-]|
		   "path_defines"    Definition completion |i_CTRL-X_CTRL-D|
		   "path_patterns"   Include completion |i_CTRL-X_CTRL-I|
		   "dictionary"	Dictionary |i_CTRL-X_CTRL-K|
		   "thesaurus"	Thesaurus |i_CTRL-X_CTRL-T|
		   "cmdline"	Vim Command line completion |i_CTRL-X_CTRL-V|
		   "function"	User defined completion |i_CTRL-X_CTRL-U|
		   "omni"	Omni completion |i_CTRL-X_CTRL-O|
		   "spell"	Spelling suggestions |i_CTRL-X_s|
		   "eval"	|complete()| completion
		   "unknown"	Other internal modes

		If the optional {what} dictionary argument is supplied, then
		only the items listed in {what} are returned.
		Unsupported keys in {what} are ignored.
```

#### Related Issue/Thread
#3866 
https://groups.google.com/d/msg/vim_dev/6utE1ObSYY8/fOaLtsBUGwAJ

--
Best regards,
Hirohito Higashi (h_east)

### CODE REVIEW

**Comment by brammool** [comment]
> Once the specification is decided, refactor, update the document and add more tests.
> 
> ```
> complete_info([{what}])
> 		Returns a Dictionary with information about insert mode
> 		completion.  see |ins-completion|.
> 		The items are:
> 		   mode		current completion mode name string.
> 				See |completion_info_mode| for the values.
> 		   pum_visible	|TRUE| if popup menu is visible.
> 				See |pumvisible()|.
> 		   items	List of completion matches.  Each item is a
> 				dictionary containing the entries "word",
> 				"abbr", "menu", "kind", "info" and "user_data".
> 				See |complete-items|.

Is this really useful?  In some cases this list can be very long,
slowing down the operation.

> 		   selected	Selected item index.  First index is zero.
> 				Set -1 if not selected.

"Index is -1 if no item is selected (showing typed text only)"

[...]


-- 
hundred-and-one symptoms of being an internet addict:
49. You never have to deal with busy signals when calling your ISP...because
    you never log off.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by h-east** [comment]
@brammool 

> Is this really useful?  In some cases this list can be very long,
slowing down the operation.

I consider this point.
It is possible to avoid it by specifying only the entry you want to get in the argument `{what}`.

> "Index is -1 if no item is selected (showing typed text only)"

Thanks. I'll reflect later.

**Comment by prabirshrestha** [comment]
@h-east What is an example of `what` argument. Do we use it like this? `let info = complete_info({ 'mode': v:true })`? I think it would be good to have an example of this in docs.

@brammool I think getting `items` is useful as this would allow plugin authors to enable fuzzy search on it though I have no plans to support this in asyncomplete anytime soon.

**Comment by h-east** [comment]
@prabirshrestha 
Thank you for the suggestion.
I added an example in the document.

```
                Examples:
                        " Get all items
                        call complete_info()
                        " Get only 'mode'
                        call complete_info({'mode': ''})
                        " Get only 'mode' and 'pum_visible'
                        call complete_info({'mode': '', 'pum_visible': ''})
```

**Comment by andymass** [comment]
@prabirshrestha, can you explain further how having the items field would allow a plugin to implement fuzzy search?

**Comment by prabirshrestha** [comment]
@h-east using empty string seems a bit weird because it is mostly falsy `empty('') == v:true`. I would except something like this instead where `1` or `v:true` returns the object and `0` or `v:false` ignores it. 

```
let info = complete_info({ 'items': 1, mode: 0 }) " { items }
let info = complete_info({ 'items': v:true, mode: v:false }) " { items, mode }
```

@andymass 
I haven't tried it but for v2 branch of [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) you could do something like this.

```vim
function! s:omni_completor(opt, ctx) abort
    let mode = complete_info({ 'mode': '' })['mode']
    if mode == 'omni'
        let items = complete_info({ 'items': '' })['items']
        let startcol = col('.')
        call asyncomplete#complete(a:opt['name'], a:ctx, startcol, items)
    endif
endfunction

call asyncomplete#register_source({
    \ 'name': 'omnifunc',
    \ 'whitelist': ['*'],
    \ 'completor': function('s:omni_completor'),
    \ })

function! s:myfuzzy_asyncomplete_preprocessor(ctx, matches) abort
    " implement sorting/ranking and fuzzy match on a:matches
    " this function is called before asyncomplete.vim shows the popup
    call asyncomplete#preprocess_complete(a:ctx, l:items)
endfunction

let g:asyncomplete_preprocessor = [function('s:myfuzzy_asyncomplete_preprocessor')]
```

You would also like to handle pum open autocmd and call `asyncomplete#complete` if mode is `omni` but that autocmd doesn't exist yet - https://github.com/vim/vim/issues/4083. In asyncomplete.vim you can call that as many time as you want anytime.

v2 also now supports preprocessor which runs right before it shows the menu so you can modify the items. https://github.com/prabirshrestha/asyncomplete.vim/blob/f1cc9e3c9e952c666652152c38089c89471f4e18/doc/asyncomplete.txt#L55-L87 This pre-processor runs in every keystroke so you can easily implement fuzzy find. Asyncomplete also caches the sources based on startcol you don't have to worry about checking complete mode all the time. preprocess api is designed to be future compatible which mean you can call `asyncomplete#preprocess_complete` multiple times as well as asynchronously. You could create a preprocessor that run's in python thread so it doesn't block the UI. This is also why I have been very interested in builtin ducktype ecmascript support with webworkers support. It opens a lot of possibilities like these very easily. Because this preprocessor can now run without changing the core asyncomplete vim plugin it will be interesting to see how others write their own and share. Fuzzy finding is just one piece of the better autocomplete, to make it really shine one needs to implement MRU and ranking for autocomplete.

**Comment by brammool** [comment]
> @prabirshrestha 
> Thank you for the suggestion.
> I added an example in the document.
> 
> ```
>                 Examples:
>                         " Get all items
>                         call complete_info()
>                         " Get only 'mode'
>                         call complete_info({'mode': ''})
>                         " Get only 'mode' and 'pum_visible'
>                         call complete_info({'mode': '', 'pum_visible': ''})
> ```

I don't think it is needed to use a dictionary argument.  We can use a
list of strings, that is simpler:

		 " Get all items
		 call complete_info()

		 " Get only 'mode'
		 call complete_info(['mode'])

		 " Get only 'mode' and 'pum_visible'
		 call complete_info(['mode', 'pum_visible'])

-- 
hundred-and-one symptoms of being an internet addict:
61. Your best friends know your e-mail address, but neither your phone number
    nor the address where you live.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by prabirshrestha** [comment]
I had thought of array of string but since I would call this function in every keystroke it would need to be fast. 

Having said that arrays are still better interms if api.

**Comment by wsdjeg** [comment]
Why use new pr? what is the different  https://github.com/vim/vim/pull/4106 and https://github.com/vim/vim/pull/3866

**Comment by h-east** [comment]
@wsdjeg 
I sent a patch that was almost completely rewritten on # 3866.
Despite the reviews I have repeatedly made, he kept subtle.
(and he has never said thanks-word)

I do not want to waste time with me and Vim developers any more.

**Comment by h-east** [comment]
@brammool 
> I don't think it is needed to use a dictionary argument.  We can use a
list of strings, that is simpler:
[...]

I made it a dictionary because I referred to `{what}` of `getqflist()`, but the list is good for this API.

**Comment by brammool** [comment]
> @brammool 
> > I don't think it is needed to use a dictionary argument.  We can use a
> list of strings, that is simpler:
> [...]
> 
> I made it a dictionary because I referred to `{what}` of
> `getqflist()`, but the list is good for this API.

The getqflist() function has some arguments with a number value.  E.g.
"nr" specifies the quickfix list.  For complete_info() I don't think we
would ever have a number value, only a list of items to return.

I think that consistency between these two functions is not relevant.

-- 
hundred-and-one symptoms of being an internet addict:
73. You give your dog used motherboards instead of bones

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi,

On Sun, Mar 17, 2019 at 6:44 AM Bram Moolenaar
<vim-dev-github@256bit.org> wrote:
>
>
> > @brammool
> > > I don't think it is needed to use a dictionary argument. We can use a
> > list of strings, that is simpler:
> > [...]
> >
> > I made it a dictionary because I referred to `{what}` of
> > `getqflist()`, but the list is good for this API.
>
> The getqflist() function has some arguments with a number value. E.g.
> "nr" specifies the quickfix list. For complete_info() I don't think we
> would ever have a number value, only a list of items to return.
>

Yes. The getqflist() function also accepts values for the following
arguments in {what}:

id        quickfix list identifier
lines   List of lines to parse
efm    Error format to use for parsing the list of lines in 'lines'
nr       quickfix list number

As the caller can pass non-zero values for these items, the
getqflist() function uses a Dictionary instead of a List as the
argument type.

- Yegappan

> I think that consistency between these two functions is not relevant.
>

**Comment by prabirshrestha** [comment]
Updated asyncomplete v2 to use the new apis and it works great. https://github.com/prabirshrestha/asyncomplete.vim/pull/124/commits/623c744c1319ecc3d6d6e5f5a7998ee35f06bd51

Any chance we can get this PR merged to master soon?

**Comment by h-east** [comment]
@brammool (cc: @prabirshrestha )
I am busy for about a week, so I can not do this PR's work.
if possible, import as it is or improve.

--
Best regards,
Hirohito Higashi (h_east)

**Comment by mattn** [comment]
@prabirshrestha @brammool If you have opinion about this patch, pleaes let me known. I'll take over the work.

**Comment by prabirshrestha** [comment]
It is ready to be merged from my side.

**Comment by prabirshrestha** [comment]
@brammool Any update on this? Any concerns blocking the merge to master?

**Pull request closed without merging**
