### PR TITLE
Add initial XDG_CONFIG_HOME compatibility

### LINKED ISSUE #2034: [RFC] .config/vim(UNIX), AppData/Roaming/vim(Windows) directory structure
Recently, many application store there configuration files into `~/.config/xxx`. This is very useful to take-out configuration files into USB-disk or dropbox. As far as I know, many users make symbolic links into `~/Dropbox/config/vim/vimrc` from `~/.vimrc` or `~/.vim/vimrc`.

*ADDITIONAL:*

## UNIX

`$XDG_CONFIG_HOME/vim`

## Windows

`%APPDATA%\Vim`

### PR DESCRIPTION
**Pull request by txtsd**
So far this only handles the (.)vimrc file.

It currently takes care of the fallbacks on Linux. I haven't modified the VMS part because I don't understand that yet. And I couldn't find a windows version of vimrc.

Is this an okay change to start with? What recommendations do y'all have?

This will eventually fix #2034 

## Workings
if `$XDG_CONFIG_HOME` exists, and `$XDG_CONFIG_HOME/vim/vimrc` exists, it gets sourced
If not, it tries:
- `$HOME/.config/vim/vimrc`
- `$HOME/.config/.vimrc`
- `$HOME/.vim/vimrc`
- `$HOME/.vimrc`
- Then checks individual paths in `$XDG_CONFIG_DIRS` with `vim/vimrc` appended

in that order, eventually falling back to the default `VIM_DEFAULTS_FILE`.

## Misc
I've commented out messages that I want to be displayed about legacy directories, and I need help figuring out how to do that. Clearly `std::cout` is not the way to print those messages.

### CODE REVIEW

**Comment by romainl** [comment]
`$HOME/.vim` and `$HOME/.vimrc` are not legacy and shouldn't be treated that way. Having config files in $HOME _is_ the de-facto standard on UNIX-like systems. If anything, I would prefer to see the files tried in the other direction:

De-facto standard first:

    $HOME/.vimrc
    $HOME/.vim/vimrc

*then* XDG-compliant paths second, with XDG fallback:

    $XDG_CONFIG_HOME/.vimrc
    $HOME/.config/.vimrc
    $XDG_CONFIG_HOME/.vim/vimrc
    $HOME/.config/vim/vimrc

**Comment by brammool** [comment]
> So far this only handles the (.)vimrc file.
> 
> It currently takes care of the fallbacks on Linux. I haven&#39;t
> modified the VMS part because I don&#39;t understand that yet. And I
> couldn&#39;t find a windows version of vimrc.
> 
> Is this an okay change to start with? What recommendations do
> y&#39;all have?
> 
> This will eventually fix #2034 

Checking for $XDG_CONFIG_HOME/vim/vimrc looks OK to me.  It's just a
different place for the user to put his .vimrc.

I'm not so sure about the use of $XDG_CONFIG_DIRS.  I haven't
specifically set it, but the value is:

	/etc/xdg/xdg-gnome-flashback-metacity:/etc/xdg

And the first directory doesn't actually exist.  I guess this is meant
for system wide configuration.  In that case, it's probably better to
use it before the personal vimrc, so that the user can override
system-wide preferences.

-- 
Emacs is a nice OS - but it lacks a good text editor.
That's why I am using Vim.  --Anonymous

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by romainl** [comment]
Allow me to remind everyone that the content of `$HOME/.vim/` (and various other files outside of it) is not 100% "config".

Snippets, dictionaries, spell files are not "config": they are *data*, which, according to [the specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), should be stored under `$XDG_DATA_HOME/vim/`.

`.netrwhist`, `.viminfo`, views, swap files, history, etc. are "state", as defined by the spec, and as such should be stored under `$XDG_STATE_HOME/vim/`:

> * actions history (logs, history, recently used files, …)
> * current state of the application that can be reused on a restart (view, layout, open files, undo history, …) 

Cache files generated by plugins (CtrlP comes to mind, maybe there are others) fall under "cache" and should be stored under `$XDG_CACHE_HOME/vim/`.

In my opinion…

- Shoving everything into `$XDG_CONFIG_HOME/vim/` is a bad interpretation/understanding of the spec that betrays both its spirit and its letter.
- Splitting the runtime into *n* directories sounds like a lot of trouble.

**Comment by txtsd** [comment]
Thank you for your inputs! The plan is not to shove everything into `$XDG_CONFIG_HOME/vim/`. This is just the first step toward adhering to the freedesktop spec.
Keep in mind, this is my first time writing C code. I come from a Python background.

@chrisbra I'd like feedback from you too!

**Comment by Bakudankun** [comment]
I think it's not good to make hidden files under `.config` directory, which is already hidden. As Bram says, just adding `$XDG_CONFIG_HOME/vim` (and its default value) to the candidates for the personal initialization directories should be enough.

For Windows, I think `$APPDATA` instead of `$XDG_CONFIG_HOME` is appropriate. It is typically `C:\Users\USERNAME\AppData\Roaming`.
`$LOCALAPPDATA` can be used for unportable files like viminfo. It is typically `C:\Users\USERNAME\AppData\Local`.

cf. [KNOWNFOLDERID](https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid), [CSIDL](https://docs.microsoft.com/en-us/windows/win32/shell/csidl)

**Comment by chrisbra** [comment]
You shouldn't use `Bool`. We use int in the Vim code base for that and the values `TRUE` and `FALSE`. For the printing status messages, you can use `smsg()`. it supports `printf() % tokens`. 

Perhaps, write some documentation first, before going to write the patch. So we can all agree on the default or fallback-values and you do not have to change the implementation again and again.

I am not sure about windows, I generally tend to find `C:\Users\USERNAME\AppData` mysterious, but as a fallback after `$HOME/_vimfiles` I suppose this should be okay. 

For Unix, I think the most important things have already been mentioned. In my opinion, having different directories for different purposes (`$XDG_CACHE_HOME`, `$XDG_CONFIG_HOME`, `$XDG_STATE_HOME/vim`), is asking for trouble and will make the configuration for users more complex (and harder to debug), but that is just my opinion. 

One thing to keep in mind, undo files and swap files may become very long (since the path name can be encoded in the name), using something like `/home/user/config/vim/undo` may cause the complete path name to become too long (I think this has happened before for Neovim with encrypted user-homes (encfs, ecryptfs) where generally only a path limit of 200 characters (or even less, see e.g. https://unix.stackexchange.com/a/32834/303213) is possible. You don't have to solve this now, just something to be aware of (or to mention the limitation in the documentation).

**Comment by txtsd** [comment]
Thanks for your inputs!
I'll work on pseudocode first.

**Comment by txtsd** [comment]
Closing because my C skills aren't as good as I'd like them to be, and I've already moved on to `neovim`.

**Pull request closed without merging**
