### PR TITLE
runtime(AOSP): add basic syntax support for some filetypes related to AOSP

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by zeertzjq** [comment]
Test failure

**Comment by Freed-Wu** [comment]
@rubberduck203 Thanks for your GPL3 work!

**Comment by rubberduck203** [comment]
I don’t mind people using my work under whatever license I published it under, but please don’t list me as the maintainer if this is getting pulled into vim proper. I haven’t worked on AOSP in many years.

**Comment by Freed-Wu** [comment]
Great. Now how can we fix test failure?

**Comment by chrisbra** [comment]
closing then.

**Pull request closed without merging**
