### PR TITLE
rm dup gif

### PR DESCRIPTION
**Pull request by TheProdigyLeague**
why two pictures

### CODE REVIEW

**Comment by chrisbra** [comment]
What do you mean with 2 pictures? I like the current logo, because it makes it clear, that this project is about a text editor

**Comment by TheProdigyLeague** [comment]
> What do you mean with 2 pictures? I like the current logo, because it makes it clear, that this project is about a text editor

You are not noticing the duplication, sir.

**Comment by zzzyxwvut** [comment]
Why do you want to to take down the link to www.vim.org?

According to CMark, the current HTML rendering is:
```html
<h1>
    <a href="https://www.vim.org">
        <img src="https://github.com/vim/vim/raw/master/runtime/vimlogo.gif" alt="Vim The editor" />
    </a>
</h1>
```

and the proposed HTML rendering is:
```html
<h1>
    <img src="https://github.com/user-attachments/assets/53c29ca8-c166-4617-9502-f976d6b3ef3b" alt="vim" />
</h1>
```

**Comment by chrisbra** [comment]
> You are not noticing the duplication, sir.

Looks like it. Let me close it then.

**Pull request closed without merging**
