### PR TITLE
feature: support tab closing by middle button clicking on Windows

### PR DESCRIPTION
**Pull request by regomne**

### CODE REVIEW

**Comment by brammool** [comment]
Doesn't this make it too easy to close a tab?
Is using the middle mouse button a common way in MS-Windows to close a Tab?
Most mice don't even have a middle mouse button.

**Comment by k-takata** [comment]
Recent mice have a wheel and clicking it has the same effect.
Browsers like Chrome and Firefox support closing a tab by clicking a middle button, but it can be easily undone (e.g. Ctrl+Shift+T).
I'm not sure whether we should support it on Vim.

**Comment by k-takata** [comment]
> Doesn't this make it too easy to close a tab?

Ah, maybe #10747 is a measure for this.

**Comment by regomne** [comment]
The reason I put this pr is that most text editors in Windows that support tabs support closing a tab with the middle mouse button, such as VS Code, Sublime text, notepad++, Ultra Edit, Visual Studio.

> Browsers like Chrome and Firefox support closing a tab by clicking a middle button, but it can be easily undone (e.g. Ctrl+Shift+T).

Browsers just reopen a closed tab instead of undone, as the behavior of interacting through js scripts in the page can be hardly undone correctly.

**Comment by brammool** [comment]
> The reason I put this pr is that most text editors in Windows that
> support tabs support closing a tab with the middle mouse button, such
> as VS Code, Sublime text, notepad++, Ultra Edit, Visual Studio.
> 
> > Browsers like Chrome and Firefox support closing a tab by clicking a
> > middle button, but it can be easily undone (e.g. Ctrl+Shift+T).
> 
> Browsers just reopen a closed tab instead of undone, as the behavior
> of interacting through js scripts in the page can be hardly undone
> correctly.

OK, so there are other applications where one can close a tab with a
middle mouse click.  I just checked Chrome on Linux and that appears to
support it too.

Only doing this on MS-Windows GUI is rather limited.  Should at least do
it in all GUI versions.  Perhaps we don't need it in a terminal (which
shows a text line for the tabs).

-- 
hundred-and-one symptoms of being an internet addict:
147. You finally give up smoking...because it made the monitor dirty.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by regomne** [comment]
@brammool OK，I will try to add support for other platforms.

**Comment by brammool** [comment]
I tried this with Motif, but it looks like the "paste" functionality overrides it.  When I press the middle mouse button some icon appears.

**Comment by regomne** [comment]
> I tried this with Motif, but it looks like the "paste" functionality overrides it. When I press the middle mouse button some icon appears.

It seems that the default behavior of middle button pressing in motif window is [Drag&drop](http://www.ist.co.uk/motif/books/vol6A/ch-22.fm.html). I tried to turn off it according to the chapter "Turning Off Drag and Drop Functionality", but failed. Could you provide some help?

**Comment by brammool** [comment]
> > I tried this with Motif, but it looks like the "paste" functionality
> > overrides it. When I press the middle mouse button some icon
> > appears.
> 
> It seems that the default behavior of middle button pressing in motif
> window is
> [Drag&drop](http://www.ist.co.uk/motif/books/vol6A/ch-22.fm.html). I
> tried to turn off it according to the chapter "Turning Off Drag and
> Drop Functionality", but failed. Could you provide some help?

Not me.  I hope someone familiar with Motif and X11 can help out.

-- 
A computer program does what you tell it to do, not what you want it to do.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
