### PR TITLE
Suppression of E42 with quickfix

### PR DESCRIPTION
**Pull request by ghost**
I use ":silent make" a lot.
Patch 8.1.0141, "E42" error was added.
As I have seen, there seems to be some missing in the code.
If it is a specification, please ignore it.

### CODE REVIEW

**Comment by brammool** [comment]
I don't see E42 for :make.  How to reproduce?

**Comment by ghost** [comment]
I forgot the importaht thing. This is reproduced.
````
compiler! msvc
function! QFMakeConv()
    let q = getqflist()
    call filter(q, "v:val.text !~ 'Microsoft'")
    call filter(q, "v:val.text !~ 'Copyright'")
    call filter(q, "v:val.text !~ 'NMAKE'")
    call filter(q, "v:val.text !~ '^$'")
    call setqflist(q, 'r')
endfunction
autocmd! QuickFixCmdPost make call QFMakeConv()
````
In ```call setqflist([], 'r')```, the empty list does not include a line break.
In my vimrc, I erased the line breaks with ```call filter(q, "v:val.text !~ '^$')```.
":make" reads a file containing one or more newlines.
That is, if "qflist" is truly zero row, "E42" is output.
This behavior has been added from patch 8.1.0141.

**Comment by vim-ml** [comment]
Hi,

On Wed, Aug 1, 2018 at 4:36 PM, Nobuhiro Takasaki
<vim-dev-github@256bit.org> wrote:
> I forgot the importaht thing. This is reproduced.
>
> compiler! msvc
> function! QFMakeConv()
>     let q = getqflist()
>     call filter(q, "v:val.text !~ 'Microsoft'")
>     call filter(q, "v:val.text !~ 'Copyright'")
>     call filter(q, "v:val.text !~ 'NMAKE'")
>     call filter(q, "v:val.text !~ '^$'")
>     call setqflist(q, 'r')
> endfunction
> autocmd! QuickFixCmdPost make call QFMakeConv()
>
> In call setqflist([], 'r'), the empty list does not include a line break.
> In my vimrc, I erased the line breaks with call filter(q, "v:val.text !~
> '^$').
> ":make" reads a file containing one or more newlines.
> That is, if "qflist" is truly zero row, "E42" is output.
> This behavior has been added from patch 8.1.0141.
>

Thanks for sending the steps to reproduce the problem. Your patch does fix
this problem. I am attaching a patch that adds a function to check whether
the quickfix list is empty or not. This can be used to simplify the code.
I have also added a test to check for this.

- Yegappan

**Comment by ghost** [comment]
Thank you very much. I understood.
I have little knowledge of Vim script at the moment.
I will study that.

**Comment by ghost** [comment]
I'm really thankful to you.

**Pull request closed without merging**
