### PR TITLE
[WIP] Detect SGR mouse support for screen

### PR DESCRIPTION
**Pull request by xordspar0**
This is part of #4146.

### CODE REVIEW

**Comment by xordspar0** [comment]
Something is not quite right with this. `ttymouse` still gets set to `xterm` when I test this out in screen 4.7.

**Comment by brammool** [comment]
if (version >= 277 || is_iterm2 || is_mac_terminal
-				    || is_mintty)
+				    || is_mintty
+				    || (is_screen && version >= 40700))
 				set_option_value((char_u *)"ttym", 0L,
 							  (char_u *)"sgr", 0);

Since this checks for version >= 277 and screen uses something much
bigger, it would already set 'ttymouse' to "sgr".  Assuming older screen
versions don't support "sgr" it would need to be:

 			    if ((!is_screen && version >= 277)
			            || is_iterm2
				    || is_mac_terminal
				    || is_mintty
				    || (is_screen && version >= 40700))
 				set_option_value((char_u *)"ttym", 0L,
 							  (char_u *)"sgr", 0);

Maybe it doesn't work for you because 'ttymouse' is set somewhere else?
This code won't change it then.

-- 
Q: What kind of stuff do you do?
A: I collect hobbies.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by xordspar0** [comment]
It doesn't look like it's getting set somewhere else. When I turn on verbose logging I don't see anything set it. Also when I comment out that check:

```c
			// Only set 'ttymouse' automatically if it was not set
			// by the user already.
			//if (!option_was_set((char_u *)"ttym"))
			{
			    // Xterm version 277 supports SGR.  Also support
			    // Terminal.app, iTerm2, mintty, and screen 4.7+.
			    if (version >= 277 || is_iterm2 || is_mac_terminal
				    || is_mintty
				    || (is_screen && version >= 40700))
				set_option_value((char_u *)"ttym", 0L,
							  (char_u *)"sgr", 0);
			    // if xterm version >= 95 use mouse dragging
			    else if (version >= 95)
				set_option_value((char_u *)"ttym", 0L,
						       (char_u *)"xterm2", 0);
			}
```

ttymouse still ends up as `xterm`. :thinking:

**Comment by xordspar0** [comment]
The problem is here:

```c
		    // rxvt sends its version number: "20703" is 2.7.3.
		    // Screen sends 40500.
		    // Ignore it for when the user has set 'term' to xterm,
		    // even though it's an rxvt.
		    if (version > 20000)
			version = 0;
```

This is before the `ttym`-setting code, so by the time we see it, `version` has been set to 0. I've gone spelunking through the history of those lines of code to find out why they're needed, but I'm not sure I understand. (It's been there since before 7.0001 in 2004 and I'm not good enough with git blame to track it further back than that.)

Do you think it's enough to do something like this?

```c
		    if (version > 20000)
			is_not_xterm = TRUE;
```

and then use `is_not_xterm` in more places throughout the rest of this function?

**Comment by xordspar0** [comment]
Would you accept a patch to refactor this section to be more straightforward? I think something like this would be nice:

```c
if (arg[0] == 0) // This is xterm in vt100 mode or something pretending to be that.
{
    if (version >= 227)
        // Set ttym and color
    if (version >= 95)
        // Set ttym and color
    // ...
}
else if (arg[0] == 77) // This is mintty
    // Set ttym and color
else if (arg[0] == 83) // This is screen
    // Set ttym and color
else if (arg[0] == 84) // This is tmux
    // Set ttym and color
// ...
```

The arg[0] == 0 section will still be complicated because a lot of things use that, but I think overall it will be easier to understand.

**Comment by xordspar0** [comment]
If the `version > 20000` is just to detect rxvt and screen, then this is easy because rxvt also sets arg[0] to something unique: ASCII 'R', or decimal 82.

**Comment by brammool** [comment]
Jordan Christiansen wrote:

> The problem is here:
> 
> ```c
> 		    // rxvt sends its version number: "20703" is 2.7.3.
> 		    // Screen sends 40500.
> 		    // Ignore it for when the user has set 'term' to xterm,
> 		    // even though it's an rxvt.
> 		    if (version > 20000)
> 			version = 0;
> ```
> 
> This is before the `ttym`-setting code, so by the time we see it, `version` has been set to 0. I've gone spelunking through the history of those lines of code to find out why they're needed, but I'm not sure I understand. (It's been there since before 7.0001 in 2004 and I'm not good enough with git blame to track it further back than that.)
> 
> Do you think it's enough to do something like this?
> 
> ```c
> 		    if (version > 20000)
> 			is_not_xterm = TRUE;
> ```
> 
> and then use `is_not_xterm` in more places throughout the rest of this
> function?

This code has been changed bit by bit over time.  I recently refactored
it to parse the three arguments once, and had to be very careful not to
make a mistake.  Refactoring more will have the same problem, there are
very subtle, and often not documented, dependencies.

We also need to test this.  And it's best to do this before refactoring.
Let me add a simple test for libvterm, hopefully you have some time to
add all the cases currently checked for.

-- 
SIGFUN -- signature too funny (core dumped)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by xordspar0** [comment]
Ok, that sounds good. I'll add support for screen now and add tests for all of the terminals that we detect. Your libvterm test is a big help for me to know how to do that.

**Comment by xordspar0** [comment]
Screen support for SGR is done now and I've added tests for all of the terminals that we check in the ttymouse section of term.c. Two tests currently fail:

* screen < 4.7 has SGR mouse enabled. This is a bug that I'll need to fix.
* xterm < 277 also has SGR mouse enabled. I think this is a bug, but it's already this way on master. Fixing it would probably be complicated because there are other terminals that claim to be xterm patch level 95 that *do* support SGR mouse mode.

**Comment by brammool** [comment]
> Screen support for SGR is done now and I've added tests for all of the
> terminals that we check in the ttymouse section of term.c. Two tests
> currently fail:
> 
> * screen < 4.7 has SGR mouse enabled. This is a bug that I'll need to
> fix.

Let me know when that's done.

> * xterm < 277 also has SGR mouse enabled. I think this is a bug, but
> it's already this way on master. Fixing it would probably be
> complicated because there are other terminals that claim to be xterm
> patch level 95 that *do* support SGR mouse mode.

I built xterm 267 and it results in "xterm2", so that looks OK.
v:termresponse is <1b>[>0;267;0c

-- 
So when I saw the post to comp.editors, I rushed over to the FTP site to
grab it.  So I yank apart the tarball, light x candles, where x= the
vim version multiplied by the md5sum of the source divided by the MAC of
my NIC (8A3FA78155A8A1D346C3C4A), put on black robes, dim the lights,
wave a dead chicken over the hard drive, and summon the power of GNU GCC
with the magic words "make config ; make!".
		[Jason Spence, compiling Vim 5.0]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by xordspar0** [comment]
> > * screen < 4.7 has SGR mouse enabled. This is a bug that I'll need to
 fix.

> Let me know when that's done.

The strange thing is that when I test it in real life with a real screen it's fine. It's just the test that's not quite right.

> I built xterm 267 and it results in "xterm2", so that looks OK.

Ok. I just tried too, but it still failed. It must have a similar problem where it works in real life but not in the test.

**Comment by brammool** [comment]
Jordan Christiansen wrote:

> > > * screen < 4.7 has SGR mouse enabled. This is a bug that I'll need to fix.
> 
> > Let me know when that's done.
> 
> The strange thing is that when I test it in real life with a real
> screen it's fine. It's just the test that's not quite right.
> 
> > I built xterm 267 and it results in "xterm2", so that looks OK.
> 
> Ok. I just tried too, but it still failed. It must have a similar
> problem where it works in real life but not in the test.

To check this I added a test: Test_xx03_xterm_response() and it works
just fine.  You probably have a mistake in the test file somewhere.

-- 
"Software is like sex... it's better when it's free."
		-- Linus Torvalds, initiator of the free Linux OS
Makes me wonder what FSF stands for...?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by xordspar0** [comment]
It turns out that it's the order of the tests that causes some of them to fail. Any test after the macOS Terminal.app test always has ttymouse set to 'sgr'. As far as I can tell, all the tests are identical except the termresponse. I still haven't figured out if this is a bug in my tests or Vim.

**Comment by brammool** [comment]
> It turns out that it's the order of the tests that causes some of them
> to fail. Any test after the macOS Terminal.app test always has
> ttymouse set to 'sgr'. As far as I can tell, all the tests are
> identical except the termresponse. I still haven't figured out if this
> is a bug in my tests or Vim.

Oh, that's a good catch.  "is_not_xterm" and "is_mac_terminal" are never
reset.  That's fine when 'term' isn't set, but may have strange effects
when setting 'term' later.  Or in tests.  I'll make a patch for this.

-- 
The chat program is in public domain.  This is not the GNU public license.
If it breaks then you get to keep both pieces.
		-- Copyright notice for the chat program

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by xordspar0** [comment]
> Oh, that's a good catch.  "is_not_xterm" and "is_mac_terminal" are never
> reset.  That's fine when 'term' isn't set, but may have strange effects
> when setting 'term' later.  Or in tests.  I'll make a patch for this.

Great! I rebased on master, triggered the reset for those flags in the tests, and everything is working now. Let me know if there's anything I need to fix or improve. Do you need me to squash my commits or do anything else to get this ready?

**Pull request closed without merging**
