### PR TITLE
Fix broken help tags for the new 'gm' command

### PR DESCRIPTION
**Pull request by ychin**
Also re-generated tags.

### CODE REVIEW

**Comment by ychin** [comment]
I'm considering adding a test case to detect broken help tags (basically situations where running `helptags ALL` would trigger an error), but seems like most other script tests are mostly for testing code behavior. I still think it's useful though as the runtime files are not updated as frequently and it's possible for people to check out a Vim version and see errors when attempting to generate help tags.

**Comment by chrisbra** [comment]
Note, Bram has already fixed it in his local runtime repository:
https://github.com/vim/vim/commit/8b530c1ff91f07cf6b0289a536992b7dfbc86598#r35706188

Having said that, I think a test case, that runs helptags and does not error out is certainly appreciated.

**Comment by k-takata** [comment]
The [vim-jp/vimdoc-ja-working](https://github.com/vim-jp/vimdoc-ja-working) project (Japanese translation project) has a CI for this kind of issue, and @h-east found it by this CI.

Here is a script: https://github.com/vim-jp/vimdoc-ja-working/blob/master/tools/maketags.vim
and it is called with `vim -eu tools/maketags.vim` from Makefile.

I think it might be better to add this kind of check to vim/vim's CI.

**Comment by brammool** [comment]
> Note, Bram has already fixed it in his local runtime repository:
> https://github.com/vim/vim/commit/8b530c1ff91f07cf6b0289a536992b7dfbc86598#r35706188
> 
> Having said that, I think a test case, that runs helptags and does not
> error out is certainly appreciated.

"make tags" in the runtime/doc directory already has this check.

-- 
hundred-and-one symptoms of being an internet addict:
21. Your dog has its own home page.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> "make tags" in the runtime/doc directory already has this check.

"make tags" shows the duplicated tags when found, but it doesn't return an error code.
"make vimtags" returns an error code when duplicated tags are found, but doesn't show the duplicated tags.
Both are not suitable for adding to the CI. I will prepare a PR for this.

**Comment by ychin** [comment]
Closing because #5158 addressed this.

**Pull request closed without merging**
