### PR TITLE
javascript.vim: modified number literals regex

### PR DESCRIPTION
**Pull request by Veltas**
Updated syntax/javascript.vim number literal regex to support floating point number literals, `0o` prefix octal numbers, and `0b` prefix binary numbers.

Removed the unary '`-`' operator from number literal highlighting.

### CODE REVIEW

**Comment by chrisbra** [comment]
have you contacted the maintainer?

**Comment by Veltas** [comment]
@chrisbra Thanks for reply, I see now I am meant to contact maintainer so shall link this PR to them first.

**Comment by yegappan** [comment]
Can you update and rebase this PR to the latest?

**Comment by Veltas** [comment]
@yegappan these changes were collapsed and merged into master already https://github.com/vim/vim/blob/master/runtime/syntax/javascript.vim#L42

Is there anything else I can do?

**Pull request closed without merging**
