### PR TITLE
syntax: add workspace_min_width to i3config

### PR DESCRIPTION
**Pull request by thiagowfx**
Follow-up of vim PR: https://github.com/vim/vim/pull/7969/files

i3 PR: https://github.com/i3/i3/commit/94228fd9

### CODE REVIEW

**Comment by thiagowfx** [comment]
cc @hiqua

**Comment by brammool** [comment]
@mboughaba

**Comment by hiqua** [comment]
Looks good, thanks!

**Comment by brammool** [comment]
In the file I have Mohamed Boughaba  is mentioned as the maintainer.  But I also saw a version where Quentin Hibon is mentioned as the maintainer and Mohamed as "original author".  which is the right one?

**Comment by hiqua** [comment]
The second one, I'm the maintainer.

**Comment by hiqua** [comment]
https://github.com/vim/vim/pull/9467

**Comment by thiagowfx** [comment]
https://github.com/vim/vim/pull/9467 is now closed, in case you were waiting to double-check who the maintainer was, @brammool.

**Comment by brammool** [comment]
I'll include it now and update the "Last changed" date.

**Pull request closed without merging**
