### PR TITLE
Add support for the cbelow/cabove/lbelow/labove commands

### PR DESCRIPTION
**Pull request by yegappan**
Add support for the :cbelow, :cabove, :lbelow and :labove commands to jump
to errors in the current file relative to the current line.

### CODE REVIEW

**Comment by andymass** [comment]
So does `:cabo 3` mean move to the third error, counting up, above the current line?

What if there are multiple errors on the current line, are they included in the count?

**Comment by vim-ml** [comment]
Hi,

On Mon, Apr 29, 2019 at 7:48 AM Andy Massimino
<vim-dev-github@256bit.org> wrote:
>
> So does :cabo 3 mean move to the third error, counting up, above the current line?
>

Yes. If the specified count exceeds the number of entries above the
current line,
then it stops at the first error in the file.

>
> What if there are multiple errors on the current line, are they included in the count?
>

Each entry in the current line is treated as separate entries. If the
current line
has 3 entries and the specified count is 2, then the cursor will not be moved.

- Yegappan

**Comment by chrisbra** [comment]
> Each entry in the current line is treated as separate entries. If the current line has 3 entries and the specified count is 2, then the cursor will not be moved.

So with a window like this (cursor is `[|]`, error marked as `[*]`):

```
  Lorem ipsum dolor sit amet[*],
  consetetur sadipscing elitr, sed diam[*] nonumy eirmod[*] tempor[|]
~
~
```

`3cabove` would move to the line above (where `amet` is?). Wouldn't it make more sense, to have `1cabove` move at least one line up?

**Comment by vim-ml** [comment]
Hi,

On Mon, Apr 29, 2019 at 7:54 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> Hi,
>
> On Mon, Apr 29, 2019 at 7:48 AM Andy Massimino
> <vim-dev-github@256bit.org> wrote:
> >
> > So does :cabo 3 mean move to the third error, counting up, above the current line?
> >
>
> Yes. If the specified count exceeds the number of entries above the
> current line,
> then it stops at the first error in the file.
>
> >
> > What if there are multiple errors on the current line, are they included in the count?
> >
>
> Each entry in the current line is treated as separate entries. If the
> current line
> has 3 entries and the specified count is 2, then the cursor will not be moved.
>

Correction. Multiple quickfix entries on a single line case is not correctly
handled now. Will update the PR.

- Yegappan

**Comment by vim-ml** [comment]
Hi,

On Mon, Apr 29, 2019 at 8:09 AM Christian Brabandt
<vim-dev-github@256bit.org> wrote:
>
> Each entry in the current line is treated as separate entries. If the current line has 3 entries and the specified count is 2, then the cursor will not be moved.
>
> So with a window like this (cursor is [|], error marked as [*]):
>
>   Lorem ipsum dolor sit amet[*],
>   consetetur sadipscing elitr, sed diam[*] nonumy eirmod[*] tempor[|]
> ~
> ~
>
> 3cabove would move to the line above (where amet is?). Wouldn't it make more sense, to have 1cabove move at least one line up?
>

Do you think we should treat multiple errors on a single line as one entry for
the purpose of the cabove and cbelow commands?

Thanks,
Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Mon, Apr 29, 2019 at 7:54 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
> >
> > Hi,
> >
> > On Mon, Apr 29, 2019 at 7:48 AM Andy Massimino
> > <vim-dev-github@256bit.org> wrote:
> > >
> > > So does :cabo 3 mean move to the third error, counting up, above the current line?
> > >
> >
> > Yes. If the specified count exceeds the number of entries above the
> > current line,
> > then it stops at the first error in the file.
> >
> > >
> > > What if there are multiple errors on the current line, are they included in the count?
> > >
> >
> > Each entry in the current line is treated as separate entries. If the
> > current line
> > has 3 entries and the specified count is 2, then the cursor will not be moved.
> >
> 
> Correction. Multiple quickfix entries on a single line case is not correctly
> handled now. Will update the PR.

If we support moving to the entry before/after the cursor, it would be
helpful if there are many errors in a line (e.g. in an XML file).
We could use :cbefore and :cafter for that.
So you could click somewhere in the line and use :cafter to jump to the
next column with an error.  It goes to a following line if that's where
the next error is.

Then :cabove and :cbelow can actually use the count as the number of
individual lines.

Makes sense?

-- 
MARTHA'S WAY: Don't throw out all that leftover wine. Freeze into ice cubes
              for future use in casseroles and sauces.
MY WAY:       What leftover wine?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Mon, Apr 29, 2019 at 11:31 AM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
> Yegappan wrote:
>
> > On Mon, Apr 29, 2019 at 7:54 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
> > >
> > > Hi,
> > >
> > > On Mon, Apr 29, 2019 at 7:48 AM Andy Massimino
> > > <vim-dev-github@256bit.org> wrote:
> > > >
> > > > So does :cabo 3 mean move to the third error, counting up, above the current line?
> > > >
> > >
> > > Yes. If the specified count exceeds the number of entries above the
> > > current line,
> > > then it stops at the first error in the file.
> > >
> > > >
> > > > What if there are multiple errors on the current line, are they included in the count?
> > > >
> > >
> > > Each entry in the current line is treated as separate entries. If the
> > > current line
> > > has 3 entries and the specified count is 2, then the cursor will not be moved.
> > >
> >
> > Correction. Multiple quickfix entries on a single line case is not correctly
> > handled now. Will update the PR.
>
> If we support moving to the entry before/after the cursor, it would be
> helpful if there are many errors in a line (e.g. in an XML file).
> We could use :cbefore and :cafter for that.
> So you could click somewhere in the line and use :cafter to jump to the
> next column with an error.  It goes to a following line if that's where
> the next error is.
>

So the cafter and cbefore commands are used to browse through every error
in the current file?

>
> Then :cabove and :cbelow can actually use the count as the number of
> individual lines.
>
> Makes sense?
>

We will then have the following commands:

cbelow - Go to an error line below the current line in the current file
cabove - Go to an error line above the current line in the current file
cbefore - Go to an error before the current column in the current file
cafter - Go to an error after the current column in the current file

- Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> > > Correction. Multiple quickfix entries on a single line case is not correctly
> > > handled now. Will update the PR.
> >
> > If we support moving to the entry before/after the cursor, it would be
> > helpful if there are many errors in a line (e.g. in an XML file).
> > We could use :cbefore and :cafter for that.
> > So you could click somewhere in the line and use :cafter to jump to the
> > next column with an error.  It goes to a following line if that's where
> > the next error is.
> >
> 
> So the cafter and cbefore commands are used to browse through every error
> in the current file?
> 
> >
> > Then :cabove and :cbelow can actually use the count as the number of
> > individual lines.
> >
> > Makes sense?
> >
> 
> We will then have the following commands:
> 
> cbelow - Go to an error line below the current line in the current file
> cabove - Go to an error line above the current line in the current file
> cbefore - Go to an error before the current column in the current file
> cafter - Go to an error after the current column in the current file

Right.  And when giving a count to cbelow/cabove it counts all the
errors in the same line as one.  Thus if there are three matches in the
line above and one two lines up, then ":2cabove" goes two lines up.

-- 
Proofread carefully to see if you any words out.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Apr 30, 2019 at 12:41 PM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
>
> Yegappan wrote:
>
> > > > Correction. Multiple quickfix entries on a single line case is not correctly
> > > > handled now. Will update the PR.
> > >
> > > If we support moving to the entry before/after the cursor, it would be
> > > helpful if there are many errors in a line (e.g. in an XML file).
> > > We could use :cbefore and :cafter for that.
> > > So you could click somewhere in the line and use :cafter to jump to the
> > > next column with an error.  It goes to a following line if that's where
> > > the next error is.
> > >
> >
> > So the cafter and cbefore commands are used to browse through every error
> > in the current file?
> >
> > >
> > > Then :cabove and :cbelow can actually use the count as the number of
> > > individual lines.
> > >
> > > Makes sense?
> > >
> >
> > We will then have the following commands:
> >
> > cbelow - Go to an error line below the current line in the current file
> > cabove - Go to an error line above the current line in the current file
> > cbefore - Go to an error before the current column in the current file
> > cafter - Go to an error after the current column in the current file
>
> Right.  And when giving a count to cbelow/cabove it counts all the
> errors in the same line as one.  Thus if there are three matches in the
> line above and one two lines up, then ":2cabove" goes two lines up.
>

The latest updated pull request implements the above behavior. Currently
only the cabove and cbelow commands are implemented.

The current implementation supports count only after the command name
and not before the command. I did this to support only positive numbers
for the count and not use the range specification from the buffer.

- Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> > > We will then have the following commands:
> > >
> > > cbelow - Go to an error line below the current line in the current file
> > > cabove - Go to an error line above the current line in the current file
> > > cbefore - Go to an error before the current column in the current file
> > > cafter - Go to an error after the current column in the current file
> >
> > Right.  And when giving a count to cbelow/cabove it counts all the
> > errors in the same line as one.  Thus if there are three matches in the
> > line above and one two lines up, then ":2cabove" goes two lines up.
> >
> 
> The latest updated pull request implements the above behavior. Currently
> only the cabove and cbelow commands are implemented.
> 
> The current implementation supports count only after the command name
> and not before the command. I did this to support only positive numbers
> for the count and not use the range specification from the buffer.

:2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.

-- 
It's not hard to meet expenses, they're everywhere.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Wed, May 1, 2019 at 6:47 AM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
>
> Yegappan wrote:
>
> > > > We will then have the following commands:
> > > >
> > > > cbelow - Go to an error line below the current line in the current file
> > > > cabove - Go to an error line above the current line in the current file
> > > > cbefore - Go to an error before the current column in the current file
> > > > cafter - Go to an error after the current column in the current file
> > >
> > > Right.  And when giving a count to cbelow/cabove it counts all the
> > > errors in the same line as one.  Thus if there are three matches in the
> > > line above and one two lines up, then ":2cabove" goes two lines up.
> > >
> >
> > The latest updated pull request implements the above behavior. Currently
> > only the cabove and cbelow commands are implemented.
> >
> > The current implementation supports count only after the command name
> > and not before the command. I did this to support only positive numbers
> > for the count and not use the range specification from the buffer.
>
> :2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.
>

I was using RANGE in the command spec. But when a negative count is
supplied to the command, it uses the current line number from the buffer and
subtracts the specified count. I wanted to display an error for negative values.
I can use RANGE, if the value is negative, it will ignore the supplied count.

- Yegappan

**Comment by vim-ml** [comment]
Yegappan wrote:

> > > > > We will then have the following commands:
> > > > >
> > > > > cbelow - Go to an error line below the current line in the current file
> > > > > cabove - Go to an error line above the current line in the current file
> > > > > cbefore - Go to an error before the current column in the current file
> > > > > cafter - Go to an error after the current column in the current file
> > > >
> > > > Right.  And when giving a count to cbelow/cabove it counts all the
> > > > errors in the same line as one.  Thus if there are three matches in the
> > > > line above and one two lines up, then ":2cabove" goes two lines up.
> > > >
> > >
> > > The latest updated pull request implements the above behavior. Currently
> > > only the cabove and cbelow commands are implemented.
> > >
> > > The current implementation supports count only after the command name
> > > and not before the command. I did this to support only positive numbers
> > > for the count and not use the range specification from the buffer.
> >
> > :2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.
> 
> I was using RANGE in the command spec. But when a negative count is
> supplied to the command, it uses the current line number from the buffer and
> subtracts the specified count. I wanted to display an error for negative values.
> I can use RANGE, if the value is negative, it will ignore the supplied count.

I looked into the way the type of range is specified, but it has a long
history of subtle ways things work not quite as expected.  Therefore
ADDR_OTHER will default to using buffer lines.

We could add a new address type, that does not use the buffer lines.
Not sure what to call it.  ADDR_NOT_LINES is not quite right.
I did do a bit of cleanup and removed NOTADR from the command flags.
It seemed a duplicate of using ADDR_OTHER, but it turns out it isn't
quite so.

-- 
Life is a gift, living is an art.		(Bram Moolenaar)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hi Bram,

On Wed, May 1, 2019 at 9:20 AM Bram Moolenaar <Bram@moolenaar.net> wrote:
>
>
> Yegappan wrote:
>
> > > > > > We will then have the following commands:
> > > > > >
> > > > > > cbelow - Go to an error line below the current line in the current file
> > > > > > cabove - Go to an error line above the current line in the current file
> > > > > > cbefore - Go to an error before the current column in the current file
> > > > > > cafter - Go to an error after the current column in the current file
> > > > >
> > > > > Right.  And when giving a count to cbelow/cabove it counts all the
> > > > > errors in the same line as one.  Thus if there are three matches in the
> > > > > line above and one two lines up, then ":2cabove" goes two lines up.
> > > > >
> > > >
> > > > The latest updated pull request implements the above behavior. Currently
> > > > only the cabove and cbelow commands are implemented.
> > > >
> > > > The current implementation supports count only after the command name
> > > > and not before the command. I did this to support only positive numbers
> > > > for the count and not use the range specification from the buffer.
> > >
> > > :2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.
> >
> > I was using RANGE in the command spec. But when a negative count is
> > supplied to the command, it uses the current line number from the buffer and
> > subtracts the specified count. I wanted to display an error for negative values.
> > I can use RANGE, if the value is negative, it will ignore the supplied count.
>
> I looked into the way the type of range is specified, but it has a long
> history of subtle ways things work not quite as expected.  Therefore
> ADDR_OTHER will default to using buffer lines.
>
> We could add a new address type, that does not use the buffer lines.
> Not sure what to call it.  ADDR_NOT_LINES is not quite right.
> I did do a bit of cleanup and removed NOTADR from the command flags.
> It seemed a duplicate of using ADDR_OTHER, but it turns out it isn't
> quite so.
>

I updated the PR to use the new ADDR_NONE for the cbelow and cabove
commands. Now the negative and invalid ranges are properly passed to
the command function and the function checks for the invalid values and
displays an error message. This works on Linux and Mac (Travis CI builds).
But on Windows (Appveyor), the test fails. It looks like on MS-Windows,
the negative range is still converted into a buffer line number relative to
the current line number.

https://travis-ci.org/vim/vim/builds/527133913
https://ci.appveyor.com/project/chrisbra/vim/build/job/iw0t4ik7b28mwq1r

- Yegappan

**Comment by vim-ml** [comment]
Hi Bram,

On Wed, May 1, 2019 at 10:39 PM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> Hi Bram,
>
> On Wed, May 1, 2019 at 9:20 AM Bram Moolenaar <Bram@moolenaar.net> wrote:
> >
> >
> > Yegappan wrote:
> >
> > > > > > > We will then have the following commands:
> > > > > > >
> > > > > > > cbelow - Go to an error line below the current line in the current file
> > > > > > > cabove - Go to an error line above the current line in the current file
> > > > > > > cbefore - Go to an error before the current column in the current file
> > > > > > > cafter - Go to an error after the current column in the current file
> > > > > >
> > > > > > Right.  And when giving a count to cbelow/cabove it counts all the
> > > > > > errors in the same line as one.  Thus if there are three matches in the
> > > > > > line above and one two lines up, then ":2cabove" goes two lines up.
> > > > > >
> > > > >
> > > > > The latest updated pull request implements the above behavior. Currently
> > > > > only the cabove and cbelow commands are implemented.
> > > > >
> > > > > The current implementation supports count only after the command name
> > > > > and not before the command. I did this to support only positive numbers
> > > > > for the count and not use the range specification from the buffer.
> > > >
> > > > :2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.
> > >
> > > I was using RANGE in the command spec. But when a negative count is
> > > supplied to the command, it uses the current line number from the buffer and
> > > subtracts the specified count. I wanted to display an error for negative values.
> > > I can use RANGE, if the value is negative, it will ignore the supplied count.
> >
> > I looked into the way the type of range is specified, but it has a long
> > history of subtle ways things work not quite as expected.  Therefore
> > ADDR_OTHER will default to using buffer lines.
> >
> > We could add a new address type, that does not use the buffer lines.
> > Not sure what to call it.  ADDR_NOT_LINES is not quite right.
> > I did do a bit of cleanup and removed NOTADR from the command flags.
> > It seemed a duplicate of using ADDR_OTHER, but it turns out it isn't
> > quite so.
> >
>
> I updated the PR to use the new ADDR_NONE for the cbelow and cabove
> commands. Now the negative and invalid ranges are properly passed to
> the command function and the function checks for the invalid values and
> displays an error message. This works on Linux and Mac (Travis CI builds).
> But on Windows (Appveyor), the test fails. It looks like on MS-Windows,
> the negative range is still converted into a buffer line number relative to
> the current line number.
>
> https://travis-ci.org/vim/vim/builds/527133913
> https://ci.appveyor.com/project/chrisbra/vim/build/job/iw0t4ik7b28mwq1r
>

This is caused by the difference in size of the long type (64-bit vs 32-bit)
between the Linux/Mac and MS-Windows builds. To check for the negative
values, I am casting the long value to an integer. This works for the
64-bit long value and not for the 32-bit long value.

- Yegappan

**Comment by vim-ml** [comment]
Hi Bram,

On Thu, May 2, 2019 at 9:25 AM Yegappan Lakshmanan <yegappanl@gmail.com> wrote:
>
> > > Yegappan wrote:
> > >
> > > > > > > > We will then have the following commands:
> > > > > > > >
> > > > > > > > cbelow - Go to an error line below the current line in the current file
> > > > > > > > cabove - Go to an error line above the current line in the current file
> > > > > > > > cbefore - Go to an error before the current column in the current file
> > > > > > > > cafter - Go to an error after the current column in the current file
> > > > > > >
> > > > > > > Right.  And when giving a count to cbelow/cabove it counts all the
> > > > > > > errors in the same line as one.  Thus if there are three matches in the
> > > > > > > line above and one two lines up, then ":2cabove" goes two lines up.
> > > > > > >
> > > > > >
> > > > > > The latest updated pull request implements the above behavior. Currently
> > > > > > only the cabove and cbelow commands are implemented.
> > > > > >
> > > > > > The current implementation supports count only after the command name
> > > > > > and not before the command. I did this to support only positive numbers
> > > > > > for the count and not use the range specification from the buffer.
> > > > >
> > > > > :2cabove should work.  Use "RANGE" and "ADDR_OTHER" in the command spec.
> > > >
> > > > I was using RANGE in the command spec. But when a negative count is
> > > > supplied to the command, it uses the current line number from the buffer and
> > > > subtracts the specified count. I wanted to display an error for negative values.
> > > > I can use RANGE, if the value is negative, it will ignore the supplied count.
> > >
> > > I looked into the way the type of range is specified, but it has a long
> > > history of subtle ways things work not quite as expected.  Therefore
> > > ADDR_OTHER will default to using buffer lines.
> > >
> > > We could add a new address type, that does not use the buffer lines.
> > > Not sure what to call it.  ADDR_NOT_LINES is not quite right.
> > > I did do a bit of cleanup and removed NOTADR from the command flags.
> > > It seemed a duplicate of using ADDR_OTHER, but it turns out it isn't
> > > quite so.
> > >
> >
> > I updated the PR to use the new ADDR_NONE for the cbelow and cabove
> > commands. Now the negative and invalid ranges are properly passed to
> > the command function and the function checks for the invalid values and
> > displays an error message. This works on Linux and Mac (Travis CI builds).
> > But on Windows (Appveyor), the test fails. It looks like on MS-Windows,
> > the negative range is still converted into a buffer line number relative to
> > the current line number.
> >
> > https://travis-ci.org/vim/vim/builds/527133913
> > https://ci.appveyor.com/project/chrisbra/vim/build/job/iw0t4ik7b28mwq1r
> >
>
> This is caused by the difference in size of the long type (64-bit vs 32-bit)
> between the Linux/Mac and MS-Windows builds. To check for the negative
> values, I am casting the long value to an integer. This works for the
> 64-bit long value and not for the 32-bit long value.
>

I have addressed this issue in the updated PR. The get_address()
function was not properly returning the count passed to commands
with ADDR_NONE. It was returning MAXLNUM - {count}. I have
modified it to return the actual count supplied by the user.

- Yegappan

**Pull request closed without merging**
