### PR TITLE
The item 'vcon' is not described

### PR DESCRIPTION
**Pull request by ghost**
Thank you very much. I am very happy. :)

### CODE REVIEW

**Comment by ghost** [comment]
Excuse me.
Ken Takata's name is different in the commit message (patch 8.0.1531).

**Comment by k-takata** [comment]
I'm wondering that the feature name shouldn't be `has('vtp')` instead of `has('vcon')`.
As I wrote in the previous thread https://github.com/vim/vim/pull/2060#pullrequestreview-74337109, Microsoft doesn't use the term "Virtual Console" in the reference. So my proposal is:

```diff
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -9195,6 +9195,7 @@ visualextra		Compiled with extra Visual 
 			|blockwise-operators|.
 vms			VMS version of Vim.
 vreplace		Compiled with |gR| and |gr| commands.
+vtp			Virtual Terminal Processing on Win32. 'tgc'
 wildignore		Compiled with 'wildignore' option.
 wildmenu		Compiled with 'wildmenu' option.
 win32			Win32 version of Vim (MS-Windows 95 and later, 32 or
diff --git a/runtime/doc/options.txt b/runtime/doc/options.txt
--- a/runtime/doc/options.txt
+++ b/runtime/doc/options.txt
@@ -7943,8 +7943,9 @@ A jump table for the options with a shor
 
 	For Win32 console, Windows 10 version 1703 (Creators Update) or later
 	is required. Use this check to find out: >
-		if has('vcon')
-<
+		if has('vtp')
+<	("vtp" stands for Virtual Terminal Processing.)
+
 	Note that the "cterm" attributes are still used, not the "gui" ones.
 	NOTE: This option is reset when 'compatible' is set.
 
diff --git a/src/evalfunc.c b/src/evalfunc.c
--- a/src/evalfunc.c
+++ b/src/evalfunc.c
@@ -6400,7 +6400,7 @@ f_has(typval_T *argvars, typval_T *rettv
 	    n = syntax_present(curwin);
 #endif
 #ifdef FEAT_VTP
-	else if (STRICMP(name, "vcon") == 0)
+	else if (STRICMP(name, "vtp") == 0)
 	    n = has_vtp_working();
 #endif
 #ifdef FEAT_NETBEANS_INTG
```

**Comment by ghost** [comment]
I can not decide. My idea is swaying. I'm sorry, please.

**Comment by brammool** [comment]
> Thank you very much. I am very happy. :)

I had actually included it, but wasn't part of the patch:

vcon			Win32: Virtual console support is working, can use 256
			and 24 bit colors.

Note that the difference with the +vtp feature is that +vtp indicates
the feature is build into Vim, while has('vcon') indicates whether it's
working.  The +vtp is more for users to check if their Vim version has
the feature, while has('vcon') can be used to change the colors.

-- 
ROBIN:  (warily) And if you get a question wrong?
ARTHUR: You are cast into the Gorge of Eternal Peril.
ROBIN:  Oh ... wacho!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
I understood.

**Comment by k-takata** [comment]
I also respect @brammool's decision. Closing.

**Pull request closed without merging**
