### PR TITLE
Reserve 100 error codes for future enhancements to the Vim9 class support

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by chrisbra** [comment]
can you add a comment to `error.h` that error `E15XX` is reserved for vim9 class support?

**Comment by yegappan** [comment]
> can you add a comment to `error.h` that error `E15XX` is reserved for vim9 class support?

Yes. The error codes E1390 to E1499 are reserved for the Vim9 class support.

**Comment by chrisbra** [comment]
ah I misread. Yeah that is fine.

**Comment by chrisbra** [comment]
this had some conflicts. I hope I fixed them all correctly. Thanks!

**Pull request closed without merging**
