### PR TITLE
Recognize RTEXT in addition to LTEXT and CTEXT in .rc syntax.

### PR DESCRIPTION
**Pull request by vadz**
For some reason only `LTEXT` and `CTEXT` were recognized as controls, but `RTEXT` was not.

Add it too for consistency.

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks for the patch. Please note, that this is currently an experimental repository. You should however first try to contact the maintainer of the syntax file. He will then send an updated syntax file to Bram for inclusion with Vim.

**Comment by brammool** [comment]
Someone wrote:

> For some reason only `LTEXT` and `CTEXT` were recognized as controls, but `RTEXT` was not.
> 
> Add it too for consistency.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/360
> 
> -- Commit Summary --
> 
>   * Recognize RTEXT in addition to LTEXT and CTEXT in .rc syntax.

Please send this to the maintainer of the file, Heiko Erhardt.

-- 
hundred-and-one symptoms of being an internet addict:
47. You are so familiar with the WWW that you find the search engines useless.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vadz** [comment]
Unfortunately Heiko's email address in the file header doesn't seem to work any longer, so I don't know where to send this to... Considering how utterly trivial this change is perhaps it could be merged in by someone else?

**Comment by brammool** [comment]
Hi Bram!

On So, 24 Mai 2015, Bram Moolenaar wrote:

> > For some reason only `LTEXT` and `CTEXT` were recognized as controls, but `RTEXT` was not.
> > 
> > Add it too for consistency.
> > You can view, comment on, or merge this pull request online at:
> > 
> >   https://github.com/vim/vim/pull/360
> > 
> > -- Commit Summary --
> > 
> >   * Recognize RTEXT in addition to LTEXT and CTEXT in .rc syntax.
> 
> Please send this to the maintainer of the file, Heiko Erhardt.

If no one volunteers, I can take over.

Best,
Christian
-- 
Denken ist die schwerste Arbeit, die es gibt.
Das ist wahrscheinlich der Grund, warum sich so wenige damit
beschäftigen.
		-- Henry Ford

**Comment by chrisbra** [comment]
Please provide patches against my [new repository](https://github.com/chrisbra/vim-rc-syntax)

**Pull request closed without merging**
