### PR TITLE
runtime(doc): minor fixes to starting.txt

### PR DESCRIPTION
**Pull request by diegoviola**

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks!

**Comment by chrisbra** [comment]
reading it again, is it:
```
Vim will only care of the $XDG_CONFIG_HOME directory
```
or is it rather *"care for the $XDG_CONFIG_HOME"*?

**Comment by diegoviola** [comment]
> or is it rather _"care for the $XDG_CONFIG_HOME"_?

Good question, I'm really not a English native speaker.

I did ask though and suggestions were to use "use" instead, such as, "_Vim will only use $XDG_CONFIG_HOME_".

Personally, I think _for_ makes sense, but again, my English is probably not the best to judge the sentence.

**Comment by diegoviola** [comment]
> or is it rather _"care for the $XDG_CONFIG_HOME"_?

Good question, I'm really not a native English speaker.

I did ask though and suggestions were to use "use" instead, such as, "_Vim will only use $XDG_CONFIG_HOME_".

Personally, I think _for_ makes sense, but again, my English is probably not the best to judge the sentence.

**Comment by chrisbra** [comment]
Okay, let me merge it with `use` then.

**Pull request closed without merging**
