### PR TITLE
Convert screen dump XDG tests to normal tests

### PR DESCRIPTION
**Pull request by yegappan**
Screen dump tests are flaky, slow to run and not flexible.  If possible, it is better to avoid them.
Convert the screen dump tests for the new XDG feature to normal tests.

### CODE REVIEW

**Comment by yegappan** [comment]
For some reason, the last test is failing in the CI environment.  This test passes in my local Linux setup.

**Comment by chrisbra** [comment]
it seems $XDG_CONFIG_HOME is defined in the runners, so you need to unset it. https://github.com/vim/vim/commit/65e237529e732bdae8b67008f596a9ac902f5b34

**Comment by yegappan** [comment]
> it seems $XDG_CONFIG_HOME is defined in the runners, so you need to unset it. [65e2375](https://github.com/vim/vim/commit/65e237529e732bdae8b67008f596a9ac902f5b34)

Thanks .  I have updated the PR with this change.  Let us see whether the CI tests pass now.

**Comment by yegappan** [comment]
> > it seems $XDG_CONFIG_HOME is defined in the runners, so you need to unset it. [65e2375](https://github.com/vim/vim/commit/65e237529e732bdae8b67008f596a9ac902f5b34)
> 
> Thanks . I have updated the PR with this change. Let us see whether the CI tests pass now.

Now the tests are passing with that change.  Thanks.  This PR is ready now.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
