### PR TITLE
Correctly highlight newline character in incsearch mode

### LINKED ISSUE #6693: 'incsearch': "\n" highlights the first char in the line below
**To Reproduce**
1. Run `gvim --clean`
2. Execute `:set incsearch`
3. Put this text to the buffer
```
test
abc
```
4. Type `/test\n`. You should see something like this:
slash-n
Notice that `a` in `abc` is highlighted.

**Expected behavior**
`a` shouldn't be highlighted.

**Environment**
 - Vim [8.2.1424](https://github.com/vim/vim-win32-installer/releases/download/v8.2.1424/gvim_8.2.1424_x86_signed.zip)
 - OS: Windows 10 Home 1803
 - Terminal: GUI.

### PR DESCRIPTION
**Pull request by chrisbra**
fixes #6693

### CODE REVIEW

**Comment by brammool** [comment]
Appveyor succeeds but Freebsd fails...

**Comment by brammool** [comment]
Ah, you didn't include the new screendump files.

**Comment by chrisbra** [comment]
did I miss those? Oh shoot....

**Comment by chrisbra** [comment]
should be there now

**Pull request closed without merging**
