### PR TITLE
Syntax support for tmux configuration files

### PR DESCRIPTION
**Pull request by ericpruitt**
This change adds support for tmux configuration files to Vim. Please let me know if anything needs to be changed.

### CODE REVIEW

**Comment by brammool** [comment]
Eric Pruitt wrote:

> This change adds support for tmux configuration files to Vim. Please
> let me know if anything needs to be changed.

Thanks.

The filetype is called "tmux", but this is for tmux config files.  Would
it be better to call it "tmuxconf"?  Just in case there is any other
file type related to tmux.


I think the ftplugin should have a header, how about this:

" Vim filetype plugin file
" Language:	Tmux config
" Maintainer:	Eric Pruitt <eric.pruitt@gmail.com>
" Last Change:  2017 Mar 04

if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal commentstring=#\ %s


For filetype.vim:

au BufNewFile,BufRead {.,}tmux*.conf*	setf tmux

The "*" after "conf" appear to be superfluous.  If it really needs to be
there then the patter should be further down, where patterns ending in a
star are handled.

What is the {.,} for?  Doesn't tmux*.conf work?

For the syntax file: Since you use line continuation, you need to set
'cpo'.  See other syntax files for an example.

There is no need to check for Vim older than 6.0.

Can you use the Vim license instead of BSD?  It's probably compatible,
just to avoid confusion.


-- 
hundred-and-one symptoms of being an internet addict:
44. Your friends no longer send you e-mail...they just log on to your IRC
    channel.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ericpruitt** [comment]
On Sat, Mar 04, 2017 at 07:38:30AM -0800, Bram Moolenaar wrote:
> The filetype is called "tmux", but this is for tmux config files.  Would
> it be better to call it "tmuxconf"?  Just in case there is any other
> file type related to tmux.

The only other external files tmux uses are sockets, and glancing over
the list of syntax files, I can pick out a number of syntax files that
are for configuration files that do not have "conf" anywhere in the name
including like asterisk.vim, lynx.vim and elinks.vim to name a few.

> I think the ftplugin should have a header, how about this:
>
> " Vim filetype plugin file
> " Language:	Tmux config
> " Maintainer:	Eric Pruitt <eric.pruitt@gmail.com>
> " Last Change:  2017 Mar 04
>
> if exists("b:did_ftplugin")
>   finish
> endif
> let b:did_ftplugin = 1
>
> setlocal commentstring=#\ %s

Okay, I will add a header when I update the pull request after the other
issues are sorted.

> For filetype.vim:
>
> au BufNewFile,BufRead {.,}tmux*.conf*	setf tmux
>
> The "*" after "conf" appear to be superfluous.  If it really needs to be
> there then the patter should be further down, where patterns ending in a
> star are handled.

Okay, I will remove the trailing asterisk. It was already present in the
syntax file off of which I based mine, and I left it since it didn't
hurt anything to do so, but I personally always use "tmux.conf" or
".tmux.conf" for my configuration.

> What is the {.,} for?  Doesn't tmux*.conf work?

That ensures the file name is recognized as both ".tmux.conf" and
"tmux.conf". The default location for tmux configuration files is
"$HOME/.tmux.conf," but many people like myself host configuration files
in one place and create symlinks to the default locations. With this
pattern, I can edit "$HOME/.tmux.conf" or "$HOME/sysconfigs/tmux.conf"
and still get syntax highlighting without polluting the file with a
modeline. Is there a more general solution to this i.e. a Vim
configuration option? If there is, that would be great because there a
lot of syntax files for dotfiles that require the leading period to
activate syntax highlighting.

> For the syntax file: Since you use line continuation, you need to set
> 'cpo'.  See other syntax files for an example.
>
> There is no need to check for Vim older than 6.0.
>
> Can you use the Vim license instead of BSD?  It's probably compatible,
> just to avoid confusion.

I did a quick grep for "License" in the existing syntax files before
submitting this pull request and saw that some of them used BSD
licenses, so I assumed this would be fine. Would dual licensing with
"... or the Vim license" be acceptable?

Eric

**Comment by chrisbra** [comment]
I think this was included as of 214641f77df6f318a4b3a0b09723c1985, so closing.

**Comment by ericpruitt** [comment]
@brammool : I'm glad my files were included, but I wish you had conferred with me before committing them to ensure the canonical files were updated accordingly. That would make submitting changes in the future easier for me.

**Comment by ericpruitt** [comment]
Upon closer review, I see that the committed syntax file is actually going to be broken for most users because the glob matching rule was changed to "tmux*.conf". The default name of the tmux configurations is ".tmux.conf" with a leading period.

**Comment by brammool** [comment]
I included the first version, but there are still some open issues.

**Comment by brammool** [comment]
Eric Pruitt wrote:

> On Sat, Mar 04, 2017 at 07:38:30AM -0800, Bram Moolenaar wrote:
> > The filetype is called "tmux", but this is for tmux config files.  Would
> > it be better to call it "tmuxconf"?  Just in case there is any other
> > file type related to tmux.
> 
> The only other external files tmux uses are sockets, and glancing over
> the list of syntax files, I can pick out a number of syntax files that
> are for configuration files that do not have "conf" anywhere in the name
> including like asterisk.vim, lynx.vim and elinks.vim to name a few.

OK, we can use "tmux" then.

> > I think the ftplugin should have a header, how about this:
> >
> > " Vim filetype plugin file
> > " Language:	Tmux config
> > " Maintainer:	Eric Pruitt <eric.pruitt@gmail.com>
> > " Last Change:  2017 Mar 04
> >
> > if exists("b:did_ftplugin")
> >   finish
> > endif
> > let b:did_ftplugin = 1
> >
> > setlocal commentstring=#\ %s
> 
> Okay, I will add a header when I update the pull request after the other
> issues are sorted.
> 
> > For filetype.vim:
> >
> > au BufNewFile,BufRead {.,}tmux*.conf*	setf tmux
> >
> > The "*" after "conf" appear to be superfluous.  If it really needs to be
> > there then the patter should be further down, where patterns ending in a
> > star are handled.
> 
> Okay, I will remove the trailing asterisk. It was already present in the
> syntax file off of which I based mine, and I left it since it didn't
> hurt anything to do so, but I personally always use "tmux.conf" or
> ".tmux.conf" for my configuration.
> 
> > What is the {.,} for?  Doesn't tmux*.conf work?
> 
> That ensures the file name is recognized as both ".tmux.conf" and
> "tmux.conf". The default location for tmux configuration files is
> "$HOME/.tmux.conf," but many people like myself host configuration files
> in one place and create symlinks to the default locations. With this
> pattern, I can edit "$HOME/.tmux.conf" or "$HOME/sysconfigs/tmux.conf"
> and still get syntax highlighting without polluting the file with a
> modeline. Is there a more general solution to this i.e. a Vim
> configuration option? If there is, that would be great because there a
> lot of syntax files for dotfiles that require the leading period to
> activate syntax highlighting.

So, it's to make botoh tmux.conf and .tmux.conf work.  That's fine.

> > For the syntax file: Since you use line continuation, you need to set
> > 'cpo'.  See other syntax files for an example.
> >
> > There is no need to check for Vim older than 6.0.
> >
> > Can you use the Vim license instead of BSD?  It's probably compatible,
> > just to avoid confusion.
> 
> I did a quick grep for "License" in the existing syntax files before
> submitting this pull request and saw that some of them used BSD
> licenses, so I assumed this would be fine. Would dual licensing with
> "... or the Vim license" be acceptable?

Just the Vim license would be mentioned.  You can always distribute it
under another license if you wish to do so (assuming you are the only
author).

-- 
From "know your smileys":
 @:-()	Elvis Presley

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ericpruitt** [comment]
> Just the Vim license would be mentioned. You can always distribute it under another license if you wish to do so (assuming you are the only author).

You already merged the file with the BSD header. That aside, I have updated the source repository and regenerated the syntax files for this pull request to match the style of changes you made.

Eric

**Comment by brammool** [comment]
I'll include the changes.  I'll align the header in the ftplugin a bit to make it more readable.
Thanks!

**Comment by ericpruitt** [comment]
This pull request was closed, but the changes are not in the repository.

**Comment by k-takata** [comment]
Bram always closes PR/Issue when he merges the changes into his local repository.
Please wait next update of runtime files.

**Comment by ericpruitt** [comment]
> Bram always closes PR/Issue when he merges the changes into his local repository.

When he merged the first set of changes with his incorrect modifications, he didn't close the PR at all. Chris did _after_ they had already been pushed to GitHub.

**Pull request closed without merging**
