### PR TITLE
add support for some commands in recent cmake versions.

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by chrisbra** [comment]
please discuss with the runtime file maintainers (mentioned at the top of the file)

**Comment by cyyever** [comment]
@dmerejkowsky please review this patch.

**Comment by cyyever** [comment]
@chrisbra  I can't contact the maintainer ,what to do next?

**Comment by cyyever** [comment]
@brammool   I can't contact the maintainer ,what to do next?

**Comment by brammool** [comment]
> @brammool   I can't contact the maintainer ,what to do next?

What do you mean with "can't contact"?

Let me CC Dimitri.


-- 
All true wisdom is found on T-shirts.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Review by dmerejkowsky — APPROVED** [review]

**Pull request closed without merging**
