### PR TITLE
Add map table help

### PR DESCRIPTION
**Pull request by yuki-yano**
Added a table to help to check where the map is applied.

### CODE REVIEW

**Comment by brammool** [comment]
There already is a table at ":help map-overview".  It's a different form, either will work.  I don't think we need two.

**Comment by k-takata** [comment]
Oh, I thought this was a good idea.
The table is much easier to understand than `:help map-overview`.

**Comment by brammool** [comment]
Would it be relevant enough to have both?

**Comment by k-takata** [comment]
To be honest, I suggested @yuki-yano create this PR.
I thought this table was worthy of inclusion in the official document.
But, yes, the problem is that we have duplicated information. I leave this to you.

**Comment by TonalidadeHidrica** [comment]
An important advantage is that we can see the entire table at a glance.  In my opinion visual contents is better than textual information.

**Comment by rbtnn** [comment]
It seems that `*map-table*` is valid because this is not a command.
https://github.com/vim/vim/pull/8209/files#diff-f35d708d4c55517f9599b4a8f7a37a2089f32f421791055318bf1a3529b7abd9R65

**Comment by brammool** [comment]
Some users may prefer the modes fully spelled out, some may find the table more useful.  So let's include both.

**Comment by yuki-yano** [comment]
Thanks.
Is there any work I should do?

**Comment by TonalidadeHidrica** [comment]
@yuki-yano As @rbtnn mentioned above, you should change *:map-table* to *map-table*.

**Comment by yuki-yano** [comment]
The above has been corrected.
@brammool Can you please re-open PR?

**Comment by yuki-yano** [comment]
Sorry.
It was closed and the change was not reflected.

Can I create the PR again?

**Comment by brammool** [comment]
> The above has been corrected.
> @brammool Can you please re-open PR?

I have already included this.  I'll send out a runtime files update
soon.


-- 
Facepalm statement #1: "I'm going to New York tomorrow, hopefully I have time
to visit the White House"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
