### PR TITLE
Add missing filetype tests

### PR DESCRIPTION
**Pull request by sheerun**
I've noticed that you were missing some filetype tests, so I've added them

### CODE REVIEW

**Comment by sheerun** [comment]
There might be some duplicates so it probably needs review

**Comment by brammool** [comment]
The test is failing...

**Comment by sheerun** [comment]
It seems these new tests actually discovered a bug in filetypes.vim, it's fixed as well now

**Comment by sheerun** [comment]
Something is wrong with github, I'll open another one

**Pull request closed without merging**
