### PR TITLE
Fix typo in g:netrw_dirhistmax from 'supppress' to 'suppress'

### PR DESCRIPTION
**Pull request by aeolyus**

### CODE REVIEW

**Comment by chrisbra** [comment]
pinging charles here @cecamp 

But noted, as mentioned in the neovim issue, please send those things directly to the maintainer in the future. They may not notice here directly. Thanks.

**Comment by aeolyus** [comment]
> pinging charles here @cecamp
> 
> But noted, as mentioned in the neovim issue, please send those things directly to the maintainer in the future. They may not notice here directly. Thanks.

Oh okay sorry about that, noted for the future!

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by cecamp** [comment]
I saw it, but unfortunately I sent a netrw update to Bram just before I saw the note.  So, I've fixed it in my copy, but it won't be in the distribution for awhile.

**Comment by chrisbra** [comment]
I am closing this here.

**Pull request closed without merging**
