### PR TITLE
Add an option for using jump list like tag stack

### PR DESCRIPTION
**Pull request by yegappan**
Port the "jumpoptions" support from NeoVim:

https://neovim.io/doc/user/motion.html#jumplist-stack
https://github.com/neovim/neovim/commit/39094b3faedde9601160806901941e4808925410
https://github.com/neovim/neovim/pull/11530
https://vi.stackexchange.com/questions/18344/how-to-change-jumplist-behavior

### CODE REVIEW

**Comment by brammool** [comment]
So with this option set you can move through a tree.  When going back up a branch and then down another branch, CTRL-O still takes you further up the tree.  A note in the help would help users understand this.

The disadvantage is that branches that were visited before are gone.  I wonder if we could somehow remember them.  The big question is what command would navigate through this?  With CTRL-I you would have to pick the branch to go into.  And you need to know where you are.  Since jumps are not that predictable that would be too complex.

Perhaps we can use something similar to undo: add a timestamp to each position, so that you can go back and forward in time.  That would combine the behavior with the option on and off, using different commands instead of setting an option.  We would need to remember two jumplists.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, Jan 24, 2021 at 1:10 PM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

> So with this option set you can move through a tree. When going back up a
> branch and then down another branch, CTRL-O still takes you further up the
> tree. A note in the help would help users understand this.
>
I have updated the help text to include the above note.

> The disadvantage is that branches that were visited before are gone. I
> wonder if we could somehow remember them. The big question is what command
> would navigate through this? With CTRL-I you would have to pick the branch
> to go into. And you need to know where you are. Since jumps are not that
> predictable that would be too complex.
>
> Perhaps we can use something similar to undo: add a timestamp to each
> position, so that you can go back and forward in time. That would combine
> the behavior with the option on and off, using different commands instead
> of setting an option. We would need to remember two jumplists.
>
It makes sense to have multiple branches in the jump list and allow a user
to
browse through different branches. But why do we need to associate a
timestamp with each jump location? Unlike the undo tree, why would a user
need to go back in the jump list based on time?

Regards,
Yegappan

**Comment by brammool** [comment]
About the timestamp: I know the experience when you know you looked at some line of code just before, but don't know how to jump back there.  If we have a jump list organised by time, you could jump to each position you have seen before, in the order they were last visited.  Like the :earlier and :later undo commands.  You don't have to remember what path in the tree you followed and how to backtrack, you just navigate through time.

**Comment by epheien** [comment]
> So with this option set you can move through a tree. When going back up a branch and then down another branch, CTRL-O still takes you further up the tree. A note in the help would help users understand this.
> 
> The disadvantage is that branches that were visited before are gone. I wonder if we could somehow remember them. The big question is what command would navigate through this? With CTRL-I you would have to pick the branch to go into. And you need to know where you are. Since jumps are not that predictable that would be too complex.
> 
> Perhaps we can use something similar to undo: add a timestamp to each position, so that you can go back and forward in time. That would combine the behavior with the option on and off, using different commands instead of setting an option. We would need to remember two jumplists.

In actual use, some jumplists are not needed, similar to forward and backward in browsers.
Really disappointed that this PR was closed.

**Comment by wallacegibbon** [comment]
It's really disappointed that this PR had closed. I've switch to NeoVim just for "**set jumpoptions=stack**". It's so important for code navigation when you use Vim as an IDE.

**Comment by Shane-XB-Qian** [comment]
> It's really disappointed that this PR had closed. I've switch to NeoVim just for "**set jumpoptions=stack**". It's so important for code navigation when you use Vim as an IDE.

@wallacegibbon could you try was this really matching your demand? 
// was that really same experience like neovim or so-called IDE?

**Pull request closed without merging**
