### PR TITLE
Night mode

### PR DESCRIPTION
**Pull request by ghost**
I made the night mode with gratitude.
Kelvin is red for small values and blue for large values.
Usually, it is slightly red.

### CODE REVIEW

**Comment by brammool** [comment]
Nobuhiro Takasaki wrote:

> I made the night mode with gratitude.
> Kelvin is red for small values and blue for large values.
> Usually, it is slightly red.

What does this do that can't be done with a colorscheme?

-- 
hundred-and-one symptoms of being an internet addict:
151. You find yourself engaged to someone you've never actually met,
     except through e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
The color of ':terminal' also changes. This is not possible with colorscheme.

I have an eye disorder and it is difficult to keep looking at the normal colored screen.
The ConPTY support has had some impact on my eyes.
I want to contribute a little more to Vim.

**Comment by brammool** [comment]
Nobuhiro Takasaki wrote:

> The color of ':terminal' also changes. This is not possible with colorscheme.
> 
> I have an eye disorder and it is difficult to keep looking at the
> normal colored screen.
> The ConPTY support has had some impact on my eyes.

Well, what runs in a terminal window should work the same as it does in
the terminal run by itself.  Are you using Vim as a way to adjust the
terminal colors?  Perhaps this can be done by the terminal itself.  That
is a more generic solution than trying to do this with Vim.

-- 
hundred-and-one symptoms of being an internet addict:
156. You forget your friend's name but not her e-mail address.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
I found the problem with the VTP implementation and sent a fix.
Since I knew the existence of ```:highlight Terminal```, I implemented it there.

**Comment by ghost** [comment]
I was wrong. It was already supported. Oh…
For now, I will refocus on this.

**Comment by ghost** [comment]
There is no addition.
If a defect is found in the function, fix it.

My eyes are less tired.
The time I can write code has been extended.
I think it would be useful to someone else.

**Comment by ghost** [comment]
Make up what is missing and resubmit. Thank you very much.

**Comment by ghost** [comment]
This feature was also included in Windows 10. Close quietly.

**Pull request closed without merging**
