### PR TITLE
Improve debcontrol xs vcs fields

### LINKED ISSUE #9224: debcontrol: Fields XS-Debian-Vcs-Git and such are not highlighted
### Steps to reproduce

Get a package from a Debian derivative (eg. Ubuntu) that defines a field such as `XS-Debian-Vcs-Git`

    wget http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-keyring/gnome-keyring_40.0-3ubuntu1.debian.tar.xz
    tar -xf gnome-keyring_40.0-3ubuntu1.debian.tar.xz
    vi debian/control

What I see is that the fields `Vcs-Git` and `Vcs-Browser` are properly highlighted, but the fields `XS-Debian-Vcs-Git` and `XS-Debian-Vcs-Browser` are not.

Screenshot from 2021-11-26 15-56-42

### Expected behaviour

The values for the fields `XS-Debian-Vcs-Git` and `XS-Debian-Vcs-Browser` should be highlighted.

### Operating system

Debian Sid

### Version of Vim

`2:8.2.3565-1+b1`

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by elboulangero**
Closes: #9224

### CODE REVIEW

**Comment by brammool** [comment]
The file is maintained by Debian, please check the header for who to contact.

**Comment by jamessan** [comment]
Looks good, @elboulangero.  I've applied the changes to the vim-debian repo and will send an update to Bram soon.

**Comment by chrisbra** [comment]
closing then

**Comment by elboulangero** [comment]
Thanks everyone!

**Pull request closed without merging**
