### PR TITLE
Update runtime files for Scala

### PR DESCRIPTION
**Pull request by ches**
Brings a handful of fixes from upstream vim-scala, including:

  - https://github.com/derekwyatt/vim-scala/pull/148
  - https://github.com/derekwyatt/vim-scala/pull/152
  - https://github.com/derekwyatt/vim-scala/pull/159
  - Several highlighting group fixes and flexibility extensions by @jdanbrown

/cc @derekwyatt

### CODE REVIEW

**Comment by brammool** [comment]
I am awaiting a response from @derekwyatt

**Comment by derekwyatt** [comment]
Sorry @brammool.  I'll get back to this with @ches right away.

**Comment by ches** [comment]
We're just needing an okay sign-off from @derekwyatt here, correct? I.e. CI build failures are not a problem (I don't believe they relate to the runtime files, or these in particular). I think Derek was under the impression that we need to fix something.

**Comment by derekwyatt** [comment]
Ah, yes that's definitely my impression. There are checks that are failing and, I assumed, we had to figure out why that's so (although to @ches 's point, that would probably be a little head-scratchy).

**Comment by brammool** [comment]
These failures happen once in a while, they are completely unrelated to the Scala changes.

**Comment by derekwyatt** [comment]
Ah, then we're good. 👍

**Comment by brammool** [comment]
Thanks for checking, I'll include it now.

**Pull request closed without merging**
