### PR TITLE
Vim9: Add support for enums

### PR DESCRIPTION
**Pull request by yegappan**
Add support for enums. Example:

```
enum Day
  Monday,
  Tuesday
endenum
var d: Day = Day.Monday
```

A enum is a class (similar to Java) and a enum value is an instance of the class.

### CODE REVIEW

**Comment by yegappan** [comment]
This PR is now ready.

**Comment by errael** [comment]
Is there an `enum` method/variable for obtaining the `enum` name as a string? Java has a method name() to return the declared `enum` value. Maybe a `const` string would be appropriate for `vim9script`. That's what you'd want to use for a dict key.

**Comment by chrisbra** [comment]
can a few people please try it out?

**Comment by bfrg** [comment]
I think there should be some help tags for the enum class variables `ordinal` and `values`, so that it's easier to find. For example, `enum-ordinal` and `enum-values`.

**Comment by zzzyxwvut** [comment]
Hooray!  Below is my port of "Item 38: Emulate extensible  
enums with interfaces" from  _Effective Java_, [3rd Edition](https://github.com/jbloch/effective-java-3e-source-code).

The original code (Java) is available [here](https://github.com/jbloch/effective-java-3e-source-code/tree/master/src/effectivejava/chapter6/item38).

Currently, class methods of an enumeration are not available  
for directly helping with instantiation of its values (see  
FIXME in the port) so a script local function (`Operator()`)  
is resorted to.  Can this restriction be lifted?

```
vim9script

interface Operation
    def Apply(x: float, y: float): float
endinterface

def Operator(): func(func(float, float): float): func(float, float): float
    return (F: func(float, float): float) => (x: float, y: float) => F(x, y)
enddef

enum BasicOperation implements Operation
### FIXME: E1366 & E340 & E685
#   PLUS(BasicOperation._Operator()((x: float, y: float): float => x + y), "+"),
#   MINUS(BasicOperation._Operator()((x: float, y: float): float => x - y), "-"),
#   TIMES(BasicOperation._Operator()((x: float, y: float): float => x * y), "*"),
#   DIVIDE(BasicOperation._Operator()((x: float, y: float): float => x / y, "/"))

### FIXME: E117 & E340 & E685
#   PLUS(_Operator()((x: float, y: float): float => x + y), "+"),
#   MINUS(_Operator()((x: float, y: float): float => x - y), "-"),
#   TIMES(_Operator()((x: float, y: float): float => x * y), "*"),
#   DIVIDE(_Operator()((x: float, y: float): float => x / y, "/"))

    PLUS(Operator()((x: float, y: float): float => x + y), "+"),
    MINUS(Operator()((x: float, y: float): float => x - y), "-"),
    TIMES(Operator()((x: float, y: float): float => x * y), "*"),
    DIVIDE(Operator()((x: float, y: float): float => x / y), "/")

    const Op: func(float, float): float
    const symbol: string

    def new(Op: func(float, float): float, symbol: string)
        this.Op = Op
        this.symbol = symbol
    enddef

    static def _Operator(): func(func(float, float): float): func(float, float): float
        return (F: func(float, float): float) => (x: float, y: float) => F(x, y)
    enddef

    def Apply(x: float, y: float): float
        return this.Op(x, y)
    enddef

    def ToString(): string
        return this.symbol
    enddef
endenum

enum ExtendedOperation implements Operation
### FIXME: E1366 & E340 & E685
#   EXP(ExtendedOperation._Operator()((x: float, y: float): float => pow(x, y)), "^"),
#   REM(ExtendedOperation._Operator()((x: float, y: float): float => 0.0 + float2nr(x) % float2nr(y)), "%")

### FIXME: E117 & E340 & E685
#   EXP(_Operator()((x: float, y: float): float => pow(x, y)), "^"),
#   REM(_Operator()((x: float, y: float): float => 0.0 + float2nr(x) % float2nr(y)), "%")

    EXP(Operator()((x: float, y: float): float => pow(x, y)), "^"),
    REM(Operator()((x: float, y: float): float => 0.0 + float2nr(x) % float2nr(y)), "%")

    const Op: func(float, float): float
    const symbol: string

    def new(Op: func(float, float): float, symbol: string)
        this.Op = Op
        this.symbol = symbol
    enddef

    static def _Operator(): func(func(float, float): float): func(float, float): float
        return (F: func(float, float): float) => (x: float, y: float) => F(x, y)
    enddef

    def Apply(x: float, y: float): float
        return this.Op(x, y)
    enddef

    def ToString(): string
        return this.symbol
    enddef
endenum

#const x = str2float(input("Enter a decimal value x: " ))
#const y = str2float(input("Enter a decimal value y: " ))
#redraw!

const x = 7.0
const y = 3.0

for value in (BasicOperation.values + ExtendedOperation.values)
    echo printf("%f %s %f = %f", x, value.ToString(), y, value.Op(x, y))
endfor

```

**Comment by errael** [comment]
Couple problems: https://github.com/vim/vim/discussions/14278#discussioncomment-8923158, https://github.com/vim/vim/discussions/14278#discussioncomment-8923184

**Comment by yegappan** [comment]
> Is there an `enum` method/variable for obtaining the `enum` name as a string? `Java` has a method `name()` to return the declared `enum` value. Maybe a builtin `const name = ...` would be appropriate for `vim9script`. That's what you'd want to use for a `dict` key.

The PR has been updated to support the `name` object variable.

**Comment by yegappan** [comment]
> I think there should be some help tags for the enum class variables `ordinal` and `values`, so that it's easier to find. For example, `enum-ordinal` and `enum-values`.

Added these tags to the help.

**Comment by yegappan** [comment]
> Couple problems: [#14278 (comment)](https://github.com/vim/vim/discussions/14278#discussioncomment-8923158), [#14278 (comment)](https://github.com/vim/vim/discussions/14278#discussioncomment-8923184)

The latest updated PR should handle these issues.

**Comment by zzzyxwvut** [comment]
This line in (`:help enumvalue`) should read "instance":
> enum value is essentially an instace

------------------------------------------------------------

By the way, moon counts for the `Planet` enumeration have  
fallen behind:
1) Jupiter, 95 ([source](https://en.wikipedia.org/wiki/Moons_of_Jupiter)).
2) Saturn, 146 ([source](https://en.wikipedia.org/wiki/Moons_of_Saturn)).

Do you think, Mercury (no moons), Venus (no moons), Mars  
(Phobos and Deimos) would be more "stable" examples?

------------------------------------------------------------

Maybe a gentle warning in the documentation about relying on  
"ordinal" values would be helpful, saying that whenever new  
enumeration values are interspersed with the old values _or_  
whenever old values are rearranged, any previous assumptions  
regarding, say, a mapping between "name" and "ordinal" can  
be invalidated.

```
vim9script

enum CountV1
    ONE, TWO
endenum

for value in CountV1.values
    echo printf("%d: %s", value.ordinal, value.name)
endfor

enum CountV2
    ZERO, ONE, TWO
endenum

for value in CountV2.values
    echo printf("%d: %s", value.ordinal, value.name)
endfor
```
------------------------------------------------------------

The introduced "name" should also be mentioned here:
> An enum is a class with class variables for the enum value objects and an object
> variable for the ordinal: >

because the translated class definition that follows this  
exposes "name":

```
      public const name: string
      public const ordinal: number
```

**Comment by zzzyxwvut** [comment]
Suppose I want to store enumeration values as dictionary  
keys, and use `string()` for them.  How can I later undo  
that conversion, as I get `E121` with `eval(string(Foo.BAR))`?

**Comment by zzzyxwvut** [comment]
There is a regression between pre- and post-"name" builds.

Before, _this_ worked:

```
vim9script

enum Count
    ONE, TWO

    static const _names: list<string> = Count.values
            ->reduce((nn, e) => extend(nn, [string(e)
                            ->matchlist('Count\.\(.\{-}\)\s')
                            ->get(1, 'Count')]),
                    [])

    def ToString(): string
        return _names[this.ordinal]
    enddef
endenum

echo Count.ONE.ToString()
echo Count.TWO.ToString()
```

After, neither the above nor the below examples work, `E340` &  
`E685`:

```
vim9script

enum Count
    ONE, TWO

    static const copies: list<Count> = copy(Count.values)
endenum

echo string(Count.values)
echo string(Count.copies)
```

The enumeration "values" can no longer be referenced from  
within the enumeration body.

**Comment by errael** [comment]
> Suppose I want to store enumeration values as dictionary keys, and use `string()` for them. How can I later undo that conversion, as I get `E121` with `eval(string(Foo.BAR))`?

Can use the `name` constant for the key, like `Planet.earth.name`, it is immutable.

**Comment by zzzyxwvut** [comment]
Also, with the "name" support, class variables leak into  
"values".

```
vim9script

enum Count
    ONE, TWO

    const zero: number = 0
    static const many: number = v:numbermax
endenum

for value in Count.values
    echo printf("%2d: %s", type(value), value)
endfor
```

**Comment by errael** [comment]
> Also, with the "name" support, class variables leak into
> "values".

An `enum` is just a specialized `class`. Before `name` support, echoing  `Planet.earth` would output all class variables, just like with any class.

**Comment by errael** [comment]
Another "Internal Error" https://github.com/vim/vim/discussions/14278#discussioncomment-8932872

**Comment by yegappan** [comment]
> Also, with the "name" support, class variables leak into "values".
> 
> ```
> vim9script
> 
> enum Count
>     ONE, TWO
> 
>     const zero: number = 0
>     static const many: number = v:numbermax
> endenum
> 
> for value in Count.values
>     echo printf("%2d: %s", type(value), value)
> endfor
> ```

Thanks.  The updated PR address this issue.

**Comment by yegappan** [comment]
> Suppose I want to store enumeration values as dictionary keys, and use `string()` for them. How can I later undo that conversion, as I get `E121` with `eval(string(Foo.BAR))`?

With the latest PR, you should be able to convert an enum value to a string and then back to an enum value using eval().

**Comment by chrisbra** [comment]
Thanks for working on this. let me include this now.

**Comment by zzzyxwvut** [comment]
A few observations made with a `v9.1.0219` build.

------------------------------------------------------------

This next example is still broken (`E340`).  The "values"  
can't be queried during _static_ variable initialisation.  But  
it used to work before the arrival of "name" and, according  
to [this explanation](https://github.com/vim/vim/discussions/14278#discussioncomment-8936229),

> The class variables are initialized one at a time starting from the enum
> value class variables.

it should continue to work:

```
vim9script

enum CountV1
    ONE, TWO

    static def Values(): list<CountV1>
	return CountV1.values	# This is supported.
    enddef

    static def CopyValues(): list<CountV1>
	return copy(Values())	# This is supported.
    enddef
endenum

echo string(CountV1.Values())




# Note that "name_" is superfluous when "name" is available.
enum CountV2
    OTHER(""), ONE("ONE"), TWO("TWO")

    const name_: string

    def new(name_: string)
	this.name_ = name_
    enddef

    # This is E340 for either!
#   static const _names: dict<CountV2> = slice(CountV2.values, 1)
    static const _names: dict<CountV2> = slice(CountV2.Values(), 1)
	->reduce((d: dict<CountV2>, v: CountV2) => extend(d, {[v.name_]: v}),
	    {})

    static def Values(): list<CountV2>
	return CountV2.values	# This is supported.
    enddef

    static def FromString(text: string): CountV2
	return get(_names, text, CountV2.OTHER)
    enddef

    def ToString(): string
	return this.name_
    enddef
endenum

echo CountV2.FromString(CountV2.ONE.ToString()).ToString()
echo CountV2.FromString(CountV2.TWO.ToString()).ToString()
echo CountV2.FromString("THREE").ToString()
```

------------------------------------------------------------

Unlike usual `:class`es, there are nooks and crannies in  
enumerations where class methods must always be qualified by  
their enumeration name.

```
vim9script

enum Count
    ONE("ONE"), TWO("TWO")

    const name_: string

    def new(name_: string)
	this.name_ = Name(name_)
    enddef

    static def Name(name_: string): string
	return name_
    enddef

### E117!
#   static const MANY: string = Name("MANY")
    static const MANY: string = Count.Name("MANY")
endenum
```

If this is expected, it deserves documenting.

------------------------------------------------------------

https://github.com/vim/vim/blob/3164cf8f12f14b725b918e3170bb0a9085af8298/runtime/doc/vim9class.txt#L975-L976

(These sentences were probably written before the support  
of non-`const` variables.)

I think we need to better express in the documentation about  
the extent of immutability for enumeration values.  That is,  
the value membership (_what_ "values" describe a particular  
enumeration) can't be changed after declaration and until,  
if ever, any future amendment; otherwise, apart from special  
variables, "ordinal" and "name" and "values", enumeration  
authors can decide how and what variables can be changed  
after construction.  For example,  

```
vim9script

enum Planet
    Earth(1, false),
    Jupiter(95, true),
    Saturn(146, true)

    var moons: number
    var has_rings: bool

    def GetMoons(): number
	return this.moons
    enddef

    static def UpdateMoonCounts(counts: list<number>)
	var planets: list<Planet> = copy(Planet.values)

	for value in counts
	    const planet: Planet = remove(planets, 0)
	    planet.moons = value
	endfor
    enddef

    def ToString(): string
	return printf("{ordinal: %d, moons: %d, has_rings: %s}",
			this.ordinal, this.moons, this.has_rings)
    enddef
endenum

echo Planet.values->mapnew((i: number, v: Planet) => v.ToString())
Planet.UpdateMoonCounts([Planet.Earth.GetMoons(), 1 + Planet.Jupiter.GetMoons()])
echo Planet.values->mapnew((i: number, v: Planet) => v.ToString())
```

------------------------------------------------------------

Conversions like `eval(string(Foo.BAR))` are now supported,  
so enumeration values should also be mentioned:

https://github.com/vim/vim/blob/3164cf8f12f14b725b918e3170bb0a9085af8298/runtime/doc/builtin.txt#L2305-L2310

------------------------------------------------------------

Although it is not advertised, but it is now possible to use  
class methods for the construction of enumeration values.  
Can "protected" class methods be allowed as well (`E1366`)?

```
vim9script

g:gettext_trace = 1

const Tracer: func(string): void = exists("g:gettext_trace")
    ? (text: string) => {
	echomsg text
    }
    : (text: string) => {
    }

enum Count
### E1366
#   ONE(Count._Gettext("One")),
#   TWO(Count._Gettext("Two"))

    ONE(Count.Gettext("One")),
    TWO(Count.Gettext("Two"))

    const text: string

    def new(text: string)
	this.text = text
    enddef

#   static def _Gettext(text: string): string
    static def Gettext(text: string): string
	const text_: string = gettext(text)
	Tracer(text_)
	return text_
    enddef

    def ToString(): string
	return this.text
    enddef
endenum
```

**Comment by yegappan** [comment]
> A few observations made with a `v9.1.0219` build.
> 

Can you open separate issues for each of the items so that it is easier to track them?

> This next example is still broken (`E340`). The "values" can't be queried during _static_ variable initialisation. But it used to work before the arrival of "name" and, according to [this explanation](https://github.com/vim/vim/discussions/14278#discussioncomment-8936229),
> 
> > The class variables are initialized one at a time starting from the enum
> > value class variables.
> 
> it should continue to work:
> 

I have created PR https://github.com/vim/vim/pull/14329 to address this.

> ```
> vim9script
> 
> enum CountV1
>     ONE, TWO
> 
>     static def Values(): list<CountV1>
> 	return CountV1.values	# This is supported.
>     enddef
> 
>     static def CopyValues(): list<CountV1>
> 	return copy(Values())	# This is supported.
>     enddef
> endenum
> 
> echo string(CountV1.Values())
> 
> 
> 
> 
> # Note that "name_" is superfluous when "name" is available.
> enum CountV2
>     OTHER(""), ONE("ONE"), TWO("TWO")
> 
>     const name_: string
> 
>     def new(name_: string)
> 	this.name_ = name_
>     enddef
> 
>     # This is E340 for either!
> #   static const _names: dict<CountV2> = slice(CountV2.values, 1)
>     static const _names: dict<CountV2> = slice(CountV2.Values(), 1)
> 	->reduce((d: dict<CountV2>, v: CountV2) => extend(d, {[v.name_]: v}),
> 	    {})
> 
>     static def Values(): list<CountV2>
> 	return CountV2.values	# This is supported.
>     enddef
> 
>     static def FromString(text: string): CountV2
> 	return get(_names, text, CountV2.OTHER)
>     enddef
> 
>     def ToString(): string
> 	return this.name_
>     enddef
> endenum
> 
> echo CountV2.FromString(CountV2.ONE.ToString()).ToString()
> echo CountV2.FromString(CountV2.TWO.ToString()).ToString()
> echo CountV2.FromString("THREE").ToString()
> ```
> 
> Unlike usual `:class`es, there are nooks and crannies in enumerations where class methods must always be qualified by their enumeration name.
>

You will see the same behavior with a class declaration also.  You need to qualify a class variable name
with the class name when used in a class variable initialization.

> 
> ```
> vim9script
> 
> enum Count
>     ONE("ONE"), TWO("TWO")
> 
>     const name_: string
> 
>     def new(name_: string)
> 	this.name_ = Name(name_)
>     enddef
> 
>     static def Name(name_: string): string
> 	return name_
>     enddef
> 
> ### E117!
> #   static const MANY: string = Name("MANY")
>     static const MANY: string = Count.Name("MANY")
> endenum
> ```
> 
> If this is expected, it deserves documenting.
> 
> https://github.com/vim/vim/blob/3164cf8f12f14b725b918e3170bb0a9085af8298/runtime/doc/vim9class.txt#L975-L976
> 
> (These sentences were probably written before the support of non-`const` variables.)
> 
> I think we need to better express in the documentation about the extent of immutability for enumeration values. That is, the value membership (_what_ "values" describe a particular enumeration) can't be changed after declaration and until, if ever, any future amendment; otherwise, apart from special variables, "ordinal" and "name" and "values", enumeration authors can decide how and what variables can be changed after construction. For example,
> 

Can you create a PR with updates to the help text?

> ```
> vim9script
> 
> enum Planet
>     Earth(1, false),
>     Jupiter(95, true),
>     Saturn(146, true)
> 
>     var moons: number
>     var has_rings: bool
> 
>     def GetMoons(): number
> 	return this.moons
>     enddef
> 
>     static def UpdateMoonCounts(counts: list<number>)
> 	var planets: list<Planet> = copy(Planet.values)
> 
> 	for value in counts
> 	    const planet: Planet = remove(planets, 0)
> 	    planet.moons = value
> 	endfor
>     enddef
> 
>     def ToString(): string
> 	return printf("{ordinal: %d, moons: %d, has_rings: %s}",
> 			this.ordinal, this.moons, this.has_rings)
>     enddef
> endenum
> 
> echo Planet.values->mapnew((i: number, v: Planet) => v.ToString())
> Planet.UpdateMoonCounts([Planet.Earth.GetMoons(), 1 + Planet.Jupiter.GetMoons()])
> echo Planet.values->mapnew((i: number, v: Planet) => v.ToString())
> ```
> 
> Conversions like `eval(string(Foo.BAR))` are now supported, so enumeration values should also be mentioned:
> 
> https://github.com/vim/vim/blob/3164cf8f12f14b725b918e3170bb0a9085af8298/runtime/doc/builtin.txt#L2305-L2310
> 
> Although it is not advertised, but it is now possible to use class methods for the construction of enumeration values. Can "protected" class methods be allowed as well (`E1366`)?
>

This restriction is not unique to enums.  This restriction is applicable to class definition also.

> 
> ```
> vim9script
> 
> g:gettext_trace = 1
> 
> const Tracer: func(string): void = exists("g:gettext_trace")
>     ? (text: string) => {
> 	echomsg text
>     }
>     : (text: string) => {
>     }
> 
> enum Count
> ### E1366
> #   ONE(Count._Gettext("One")),
> #   TWO(Count._Gettext("Two"))
> 
>     ONE(Count.Gettext("One")),
>     TWO(Count.Gettext("Two"))
> 
>     const text: string
> 
>     def new(text: string)
> 	this.text = text
>     enddef
> 
> #   static def _Gettext(text: string): string
>     static def Gettext(text: string): string
> 	const text_: string = gettext(text)
> 	Tracer(text_)
> 	return text_
>     enddef
> 
>     def ToString(): string
> 	return this.text
>     enddef
> endenum
> ```

**Comment by errael** [comment]
Using v9.1.225

I was going to create an issue, but the discussion is continuing here in the closed PR.

@zzzyxwvut @yegappan

A `class`', and initially an `enum`'s, default `string()` method provides useful
debug information by including instance variables in the string return.
If wanted it can be overridden to something more useful to the programmer.

In a recent change to `enum` classes, the default `string()` method now returns
something of the form "Planet.earth" rather than output something like a `class`.
I believe this change was made related to 

```
class variables leak into "values".
```

in comment https://github.com/vim/vim/pull/14224#issuecomment-2023939547,
if `values` refers to an `enum`'s static `values`, like `list<Planet>`,
then _the statement doesn't make sense_.
`string(obj)` has always included class variables.

The change to `string(enum_value)` removes some useful
functionality: the display of instance contents. It also diverges enum from class.

There is also, in https://github.com/vim/vim/pull/14224#issuecomment-2023172587
```
Suppose I want to store enumeration values as dictionary
keys, and use string() for them. How can I later undo
that conversion, as I get E121 with eval(string(Foo.BAR))?
```

I didn't fully understand this on first read. Looking again, it seems that
the idea is to be able to use both "Planet.earth" and "Count.ONE" as keys
in a dict and reconstruct the original enum value using `eval(key)`.

The change to `enum`'s `string()` also handles this, but breaks expected
usage of `string()` for a class.

Here's a suggestion to facilitate constructing a dict key for an enum.
Add an instance variable `class_name` to an enum value. Then the developer
can do
```
    var e = Planet.earth
    some_dict[e.class_name .. '.' .. e.name] = something
```
A similar possibility would be adding a builtin method/var `AsKey()`/`as_key`
to the enum instance; then `e.as_key->split('.')[0]` is `Planet`.

Note that any of these changes to string() for specific purposes, like generating
a dict key, seems to interfere/conflict with the idea of being able to override `string()`a.

If `class_name` isn't needed/wanted, then consider something specific to enums.

**Comment by errael** [comment]
Oops, crossed in transit. Depending on what new enum issues are opened, I will either append my comments of https://github.com/vim/vim/pull/14224#issuecomment-2026660762 to one of them or open a new issue for it.

**Comment by errael** [comment]
Opened #14330 instead of comment in here.

**Comment by zzzyxwvut** [comment]
> Can you create a PR with updates to the help text?

I'll see to it tomorrow.

**Comment by zzzyxwvut** [comment]
I have created [a PR](https://github.com/vim/vim/pull/14349), documenting a few details touched upon  
in the above comments (a couple lines, really).  It should  
probably retain its draft status until some proposal will  
have been submitted on the matter of `string()` and `eval()`  
for enumerations and classes.

**Comment by zzzyxwvut** [comment]
There are now four enumeration examples collected in [a gist](https://gist.github.com/zzzyxwvut/2710e866e8f759a24a562a758cc35099)
that were ported from the source code for _Effective Java_,
3rd Edition.

Enjoy!

**Comment by zzzyxwvut** [comment]
Sure.  Point me to this wiki.

**Comment by Shane-XB-Qian** [comment]
what the content is? (sry I am not able to open gist link) if it was about the example of vim9 script enum vs java enum, perhaps just write it into vim help doc as well (just simply it which not too lengthy should be fine).

--
shane.xb.qian

**Comment by zzzyxwvut** [comment]
[Here](https://github.com/vim/vim/wiki/Vim9-enumerations-with-a-dash-of-jam-and-pickles) is a Q & A wiki entry.  It should capture the essence  
of some ported examples.

**Pull request closed without merging**
