### PR TITLE
avoid to enter insert-mode by :startinsert

### PR DESCRIPTION
**Pull request by mattn**
how to reproduce
1. :terminal
2. CTRL-W N
3. :startinsert

### CODE REVIEW

**Comment by mattn** [comment]
One more fix. avoid I/A on visual mode.

1. :terminal
2. CTRL-N
3. VI

**Comment by brammool** [comment]
Yasuhiro wrote:

> how to reproduce
> 1. :terminal
> 2. CTRL-W N
> 3. :startinsert

-    if (term_use_loop())
+    if (term_use_loop() || term_in_normal_mode())

Shouldn't that be term_job_running(curbuf->b_term) ?


-- 
hundred-and-one symptoms of being an internet addict:
129. You cancel your newspaper subscription.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>Shouldn't that be term_job_running(curbuf->b_term) ?

It accept entering into insert-mode after job finished.

**Comment by mattn** [comment]
Or should we add new function that check `curbuf->b_term != NULL` ?

**Comment by brammool** [comment]
Yasuhiro wrote:

> >Shouldn't that be term_job_running(curbuf->b_term) ?
> 
> It accept entering into insert-mode after job finished.

That also happens with term_in_normal_mode(), after the job finished the
terminal will not be in Terminal-Normal mode.  And it's OK to enter
insert mode then.

-- 
Why is it called "Windows"?  "Gates" would be more appropriate...

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
