### PR TITLE
runtime:ftplugin: let &keywordprg use :term

### PR DESCRIPTION
**Pull request by Konfekt**
See https://github.com/neovim/neovim/pull/30409

### CODE REVIEW

**Comment by habamax** [comment]
Not sure if I like the idea of nvim specific checks in vim runtime files.

On the other hand it is already in some of runtime files, including netrw: https://github.com/vim/vim/blob/4298c5f472a05486d6e26988cf10f4d04c80afd2/runtime/plugin/netrwPlugin.vim#L159

it is also in ruby and rust:
- https://github.com/vim/vim/blob/4298c5f472a05486d6e26988cf10f4d04c80afd2/runtime/autoload/rust.vim#L533
- https://github.com/vim/vim/blob/4298c5f472a05486d6e26988cf10f4d04c80afd2/runtime/autoload/rubycomplete.vim#L629

**Comment by Konfekt** [comment]
I understand. To ease maintenance, I  removed the first variant using `:!less` which does not work on Neovim, and try `:!term less`, assuming that most Vim now supply a `:term` command.
This term command output incompatibility is a pain point

**Comment by chrisbra** [comment]
Thanks. Again it would be nicer if the zsh filetype went directly via my upstream repo. But I have fixed that now.

**Comment by Konfekt** [comment]
Yes, I thought of it but wasn't sure there's a preference in order; would've added a PR for your repo, but glad to hear that it's already sorted out

**Comment by chrisbra** [comment]
yes, I want to make it easy for users to use runtime files in both projects and if feasible, I think it is beneficial for both projects to keep the logic more or less in one runtime file. But if upstream runtime file maintainers have a different opinion, then it is ultimatively their decision.

**Pull request closed without merging**
