### PR TITLE
AVR assembler syntax file

### PR DESCRIPTION
**Pull request by mhitza**
The first vim syntax file I've written so most of it is straight inspired from fasm.vim. With that in mind, maybe checks like `if version < 600` shouldn't be necessary at this point?

### CODE REVIEW

**Comment by brammool** [comment]
Marius Ghita wrote:

> The first vim syntax file I've written so most of it is straight
> inspired from fasm.vim. With that in mind, maybe checks like `if
> version < 600` shouldn't be necessary at this point?

Yes, the version check isn't needed these days.

Otherwise the syntax file looks OK.  But can you please add a
"Maintainer" entry in the header?

## 

"You know, it's at times like this when I'm trapped in a Vogon airlock with
a man from Betelgeuse and about to die of asphyxiation in deep space that I
really wish I'd listened to what my mother told me when I was young!"
"Why, what did she tell you?"
"I don't know, I didn't listen!"
        -- Arthur Dent and Ford Prefect in Douglas Adams'
           "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mhitza** [comment]
@brammool removed my line from the syntax autodetection file (worked a bit more with avra assembly examples and that's not that common of a pattern), added maintainer line and removed the version checks. Also squashed all my commits into one.

However I have a question, I saw that there is a file synmenu.vim, is ordering important in that file? And If I were to make an entry what's with the numbers prefixing each line? And what number should I use?

**Comment by brammool** [comment]
Marius Ghita wrote:

> @brammool removed my line from the syntax autodetection file (worked a
> bit more with avra assembly examples and that's not that common of a
> pattern), added maintainer line and removed the version checks. Also
> squashed all my commits into one.
> 
> However I have a question, I saw that there is a file synmenu.vim, is
> ordering important in that file? And If I were to make an entry what's
> with the numbers prefixing each line? And what number should I use?

I often forget to update synmenu.vim, even though it should be updated
for every new filetype.  The numbers are just for ordering the entries,
pick one to keep the list alphabetically.  Once in a while I'll do an
update to renumber them.

## 

hundred-and-one symptoms of being an internet addict:
31. You code your homework in HTML and give your instructor the URL.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mhitza** [comment]
If missed, I rebased my last commit updating the synmenu.vim file. From my position it's ready to include for the next release

**Comment by brammool** [comment]
Sorry it took so long.  I included the syntax file, but I commented the line that sets 'isident'.  That is a global option thus should not be set in a syntax file.
Setting 'iskeyword' is also suspicious for a syntax file.  I left it in, but please consider another solution.  Users may find changing 'iskeyword' unexpected.

**Pull request closed without merging**
