### PR TITLE
Add syntax support for Java switch expressions

### PR DESCRIPTION
**Pull request by njhanley**

### CODE REVIEW

**Comment by lacygoill** [comment]
Did you try to contact the maintainer of the java syntax plugin?
<https://github.com/vim/vim/blob/113cb513f76d8866cbb6dc85fa18aded753e01da/runtime/syntax/java.vim#L3-L4>

They have a repo here on github.

**Comment by njhanley** [comment]
That repo has had no activity since the day after it was created three years ago.

**Comment by lacygoill** [comment]
> That repo has had no activity since the day after it was created three years ago.

I guess that means "no".  Next time, mention this information in the OP.

**Comment by chrisbra** [comment]
ping @fleiner

**Comment by qdii** [comment]
ping could we merge this?

**Comment by brammool** [comment]
Claudio did respond in March, let me send him an email directly.

**Comment by chrisbra** [comment]
@njhanley can you please rebase? @fleiner can you please ACK?

**Review by dkearns — APPROVED** [review]
@chrisbra, I don't think we've heard from Claudio for some time and this look fine to me.

**Comment by chrisbra** [comment]
thanks for pinging. Let me merge it

**Comment by zzzyxwvut** [comment]
Unfortunately, the treatment of `yield` is incomplete: `yield`
statements and `yield` methods should be distinguishable.

```java
class Test
{
	public static void main(String[] args)
	{
		System.out.println(switch (args.length) {
			case 0 -> {
				System.err.println("no arguments");
				yield "java";
			}
			default -> {
				System.err.format("%d arguments%n", args.length);
				yield java.util.Arrays.toString(args);
			}
		});
		Thread.yield();
	}
}
```

The Java Specification has this to [say](https://docs.oracle.com/javase/specs/jls/se21/html/jls-3.html#jls-3.8):
> Since the term `yield` is excluded from UnqualifiedMethodIdentifier, any invocation of a method named `yield` must be qualified, thus distinguishing the invocation from a `yield` statement ([§14.21](https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-14.21)). 

Here is my [attempt](https://github.com/fleiner/vim/pull/8/commits/58fb53bc72e187c5530bad6630c188b9735f9d54).

**Comment by chrisbra** [comment]
Unfortunately, I don't know if @fleiner is still active. You may want to send the PR here to this repo instead

**Comment by zzzyxwvut** [comment]
@dkearns, as far as I remember, no _fundamental_ contexts are  
defined in terms of `:syn-region` in `syntax/java.vim` (namely,  
`class`, `interface`, "method", etc.); there are minor contexts:  
comments (`javaComment`, `javaLineComment`, `javaDocComment`),  
a few recursive definitions (`javaParenT*`; `javaDocSnippetTag`,  
`javaGenerics`, `javaStrTempl`->`javaStrTemplEmbExp`-\>`TOP`:
see my patches).

But individual tokens and grouped tokens are matchable; e.g.  
there is `javaFuncDef` but neither `throws` (`javaMethodDecl`)   
nor `return` (`javaStatement`) belong to its `:syn-contains`  
or `:syn-nextgroup`.  (I suspect that `syntax/java.vim` steams  
in the wake of `syntax/c.vim` in this regard.)

```java
class Test
{
////////////////////////// javaMethodDecl
////////////////////////// |    |
/////////////////// javaFuncDef |
/////////////////// |    | |    |
/////////////////// V    V V    V
	static byte read() throws java.io.IOException

/////// javaBraces
/////// |
/////// V
	{
/////////////// javaStatement
/////////////// |    |
/////////////// V    V
		return (byte) 0;
	}
/////// ^
/////// |
/////// javaBraces
}
```

So in order to not lose syntax bearings, sooner or later you  
tend to end up with awkward and humongous regexps that do  
a lot of looking around.  It is feasible to incrementally  
form contexts, but I wonder, if there was a reason against  
their introduction at the time.

------------------------------------------------------------

I haven't received any response from Claudio Fleiner when I  
last emailed him on 30 Sept., 2022.

**Comment by zzzyxwvut** [comment]
@chrisbra, that PR is huge and, across its 29 commits, I've  
touched or introduced over half of all lines.  I think, it  
would be easier on the eyes of volunteering reviewers and  
prudent for me to cherry pick a few commits at a time, write  
necessary screen dumps along, and present them as a series  
of PRs to this repo.

Are we okay with this diverging action towards the upstream?

**Comment by chrisbra** [comment]
> Are we okay with this diverging action towards the upstream?

I haven't heard from Claudio in quite some time. So yes.


>  I think, it
would be easier on the eyes of volunteering reviewers and
prudent for me to cherry pick a few commits at a time, write
necessary screen dumps along, and present them as a series
of PRs to this repo.

That sounds like a good plan.

**Pull request merged**
