### PR TITLE
Make repeat() accept Blob

### PR DESCRIPTION
**Pull request by Bakudankun**
There is no way to make a large Blob with a simple step, so I made `repeat()` accept a Blob.
Can be very fast when making a zero-filled Blob.

### CODE REVIEW

**Comment by brammool** [comment]
Probably making "slen" and "len" a size_t avoids that LGTM warning.  Change "len <= 0" to "len == 0" then.
Better bail out early if "n <= 0".

**Comment by Bakudankun** [comment]
@brammool 
I think the LGTM warning is about already fixed things, isn't it?
It says "1 alert when merging `b5e02f1`", which does not include the latest commit `df37334`.

**Comment by Bakudankun** [comment]
The latest analysis says "No new or fixed alerts".
https://lgtm.com/projects/g/vim/vim/rev/pr-75992f9a88e876ce0720953b3f496dcfb01da6ef

**Comment by Bakudankun** [comment]
Bailing out when n <= 0 sounds reasonable.
I'll fix that.

**Pull request closed without merging**
