### PR TITLE
Add strptime() function to complement strftime()

### PR DESCRIPTION
**Pull request by StephenWall**

### CODE REVIEW

**Comment by brammool** [comment]
There is something wrong with this pull request, the diff comes up empty.
And the "merged" message is bogus.
And I can't seem to close it.
Please create a new pull request.

**Comment by k-takata** [comment]
@StephenWall Do you use https://github.com/apps/pull?
I recommend you not to use a master branch to create a pull request.

**Comment by k-takata** [comment]
We can still see the diff with https://github.com/vim/vim/compare/master...30ff54693b3af710074b022a5081e605b324b693 .
But I wonder whether this is worth to be included, because this only works if a compiler has strptime().
So, this doesn't work when compiled with MSVC.

**Comment by brammool** [comment]
> We can still see the diff with https://github.com/vim/vim/compare/master...30ff54693b3af710074b022a5081e605b324b693 .

Thanks, that works

> But I wonder whether this is worth to be included, because this only
> works if a compiler has strptime().
> So, this doesn't work when compiled with MSVC.

I have hopes that it can be made to work:
https://stackoverflow.com/questions/321849/strptime-equivalent-on-windows

It's quite difficult parsing date and time manually, thus it's useful to
add if available.  E.g. I have a script to sort email on a date in the
header.  Thus I think it's a good addition.

-- 
hundred-and-one symptoms of being an internet addict:
96. On Super Bowl Sunday, you followed the score by going to the
    Yahoo main page instead of turning on the TV.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by StephenWall** [comment]
Hrm.  Thought I had posted a reply here, but I don't see it.  Looks like you got it sorted out OK, do you need anything else from me for this?

I at one time had a yacc-based parser that could parse a date without the caller specifying a format - it worked it out itself.  The only problem area was US vs Euro dates - mm/dd/yy vs dd/mm/yy could cause confusion.  Unfortunately I can't seem to find it anymore. :(

**Comment by brammool** [comment]
It can't be made to work for all kinds of date formats, but we could have some examples of how to try a few formats, assuming sufficient info is available.  E.g. in a mail header I see "Mon, 25 Nov 2019 14:16:35 -0800".

**Pull request merged**
