### PR TITLE
Move files are not recognized

### PR DESCRIPTION
**Pull request by amaanq**
https://github.com/move-language/move
Problem: Move files are not recognized.
Solution: Add a pattern for Move files. (Amaan Qureshi)

### CODE REVIEW

**Comment by brammool** [comment]
> https://github.com/move-language/move
> Problem: Move files are not recognized.
> Solution: Add a pattern for Move files. (Amaan Qureshi)

Is there a better name than "move"?
Without that github link it is very hard to find information about it.

-- 
From "know your smileys":
 :-| :-|   Deja' vu!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by amaanq** [comment]
searching for "move language" gives me information on it..

there's this too for reference: https://move-book.com/

**Comment by brammool** [comment]
> searching for "move language" gives me information on it..
> 
> there's this too for reference: https://move-book.com/

I suppose it's best to just call it "move" then.  "movelang" would be
more specific, but inconsistent with other filetype names.

-- 
From "know your smileys":
 :-*	A big kiss!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by amaanq** [comment]
> 
> > searching for "move language" gives me information on it..
> > 
> > there's this too for reference: https://move-book.com/
> 
> I suppose it's best to just call it "move" then.  "movelang" would be
> more specific, but inconsistent with other filetype names.
> 
> -- 
> From "know your smileys":
>  :-*	A big kiss!
> 
>  /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
> ///                                                                      \\\
> \\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
>  \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
> 

agreed, thanks!

**Pull request closed without merging**
