### PR TITLE
correctly redraw for cursorbinded windows. 

### LINKED ISSUE #10014: 'cursorbind' horizontal scrolling behavior is inconsistent depending whether 'cursorline' is set in inactive window
### Steps to reproduce

1. Run `vim --clean`
2. `:set sidescroll=1` (`sidescroll=1` makes the difference more obvious)
3. `:set nowrap`
4. Insert a long line of text
5. `:20vsplit`
6. `:windo set cursorbind`
7. Move cursor horizontally in the wider window. The narrower window is not horizontally scrolled.
8. `:windo set cursorline`
9. Move cursor horizontally in the wider window. The narrower window is horizontally scrolled.

### Expected behaviour

'cursorbind' horizontal scrolling behavior should be consistent whether 'cursorline' is set or not. I'm not sure which behavior is better.

### Version of Vim

8.2.4621

### Environment

Operating system: Arch Linux
Terminal: kitty
Value of $TERM: xterm-kitty
Shell: fish

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by chrisbra**
fixes #10014 

- add some tests
- slightly unrelated: clarify documentation on test scripts

### CODE REVIEW

**Comment by brammool** [comment]
I'll include it.  However, the test passes without the code change.  Should at least one test not have 'cursorline' set?

**Comment by chrisbra** [comment]
Hm, all 4 test fail for me without the patch. 

> Should at least one test not have 'cursorline' set?

Like this I assume?

```
call term_sendkeys(buf, ":windo :set cursorline\<cr>")
```

**Comment by chrisbra** [comment]
sorry for late notice, 
can you please un-comment the last line in the test: 

```
  "call delete('Xhor_scroll')
```

That slipped through when I debugged the test. 

Thanks

**Comment by brammool** [comment]
Christian wrote:

> sorry for late notice, 
> can you please un-comment the last line in the test: 
> 
> ```
>   "call delete('Xhor_scroll')
> ```
> 
> That slipped through when I debugged the test. 

I also didn't notice.  Will make a quick patch.

-- 
I am also told that there is a logical proof out there somewhere
that demonstrates that there is no task which duct tape cannot handle.
					-- Paul Brannan

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Christian wrote:

> Hm, all 4 test fail for me without the patch. 
> 
> > Should at least one test not have 'cursorline' set?
> 
> Like this I assume?
> 
> ```
> call term_sendkeys(buf, ":windo :set cursorline\<cr>")
> ```

Hmm, perhaps if you build without FEAT_SYN_HL defined.  If I comment out
that validate_cursor() call then the tests fail.
If I add the condition that was there, the tests pass.  Thus either
'cursorline' or 'cursorcolumn' is set in those tests.

-- 
"So this is it," said Arthur, "we are going to die."
"Yes," said Ford, "except...no!  Wait a minute!"  He suddenly lunged across
the chamber at something behind Arthur's line of vision.  "What's this
switch?" he cried.
"What?   Where?" cried Arthur, twisting around.
"No, I was only fooling," said Ford, "we are going to die after all."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
> Hmm, perhaps if you build without FEAT_SYN_HL defined.  If I comment out
> that validate_cursor() call then the tests fail.
> If I add the condition that was there, the tests pass.  Thus either
> 'cursorline' or 'cursorcolumn' is set in those tests.

Ah yes that is true. I actually added the cursorcolumn setting later to verify in the screendump test,
that the cursor is moved in both windows. Otherwise it wasn't clear from the dump,
that both windows where scrolled. 

Let me amend the test and that a scroll is also performed with neither cursorline and cursorcolumn.
PR coming

**Pull request closed without merging**
