### PR TITLE
Update tutor.tr.utf-8 (fix typos/errors/replace words)

### PR DESCRIPTION
**Pull request by bitigchi**
Hello,

There were quite a number orthographical and grammatical mistakes. In addition to these, replaced the foreign loanword tuş (button, French) with the Turkish equivalent "düğme", and the loanword kelime (word, Arabic) with the Turkish equivalent "sözcük" for better clarity and text quality.

### CODE REVIEW

**Comment by k-takata** [comment]
Maybe tutor.tr.iso9 also needs to be updated.

**Comment by brammool** [comment]
I'll include it, thanks.  The problem with long lines remains.

**Comment by brammool** [comment]
I tried using "iconv -f UTF-8 -t ISO-8859-1 tutor.tr.utf-8 > tutor.tr.iso9" but it gives an error.

**Comment by brammool** [comment]
ah, forgot to change the -1 to -9, then it works:
	iconv -f UTF-8 -t ISO-8859-9 tutor.tr.utf-8 > tutor.tr.iso9

**Pull request closed without merging**
