### PR TITLE
Add tests for handling mouse in a terminal

### PR DESCRIPTION
**Pull request by yegappan**
This PR is ready to be merged.

### CODE REVIEW

**Comment by brammool** [comment]
Just one test is failing.  Is it flaky?

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, May 10, 2020 at 12:26 PM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

> Just one test is failing. Is it flaky?
>
>
>
The failing list is pasting text using the middle mouse button in a terminal
window. In the failed case, instead of pasting the '*' register, it pasted
the '+' register.
In all the other previous runs and other test runs, this test is passing. I
am not sure
why in this particular run this test failed.

Regards,
Yegappan

**Comment by brammool** [comment]
If it's about using the selection, perhaps some X request was delayed?  Just guessing.

**Comment by vim-ml** [comment]
Hi Bram,

On Sun, May 10, 2020 at 2:33 PM Bram Moolenaar <vim-dev-github@256bit.org>
wrote:

> If it's about using the selection, perhaps some X request was delayed?
> Just guessing.
>
>
>
I addressed this problem by using a normal register instead of the clipboard
to paste using the middle mouse button.

- Yegappan

**Pull request closed without merging**
