### PR TITLE
W32 GUI: ctrl_minus as ^_

### LINKED ISSUE #10817: W32 GUI: Ctrl+- produces ^- and not ^_ any more
### Steps to reproduce

(Reported on vim_use by  Salman Halim <salmanhalim@gmail.com>)

8.2 w32 gvim used to produce ^_ when Ctrl+- was press.
9.0 w32 gvim produces ^- instead.

E.g. mapping:

```imap <C-_> TEST```

stopped to work and need to be worked around like this:

```imap <C--> TEST```

### Add info/related

GTK3 GUI produces ^_ so perhaps to be consistent it is better to fix it?

### Expected behaviour

^_ is produced

### Version of Vim

9.0.100

### Environment

OS: Windows

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by ant0sha**
NOTE: consider it as WIP state - due to unclear status of imap

(an attempt to fix #10817)

In principle the functionality for ^_ is recovered and works, but what i don't understand, is a subtle difference:

both old w32 gvim 8.1. and new gtk3 gvim allow this mapping and it works:

  ```imap <C-_> BINGO```

with this patch in w32 gvim9 it _do not work_, but only:

  ```exec "imap \x1f BINGO"```

Any ideas, why? Can it be that way mappings are working was changed recently?

### CODE REVIEW

**Comment by ant0sha** [comment]
> NOTE: consider it as WIP state - due to unclear status of imap
> 
> (an attempt to fix #10817)
> 
> In principle the functionality for ^_ is recovered and works, but what i don't understand, is a subtle difference:
> 
> both old w32 gvim 8.1. and new gtk3 gvim allow this mapping and it works:
> 
> `imap <C-_> BINGO`
> 
> with this patch in w32 gvim9 it _do not work_, but only:
> 
> `exec "imap \x1f BINGO"`
> 
> Any ideas, why? Can it be that way mappings are working was changed recently?

half a day lost with such a small thing.... nested call of gvim from testcase was missing -N thus ```imap  <C-_> ...``` was not working but only crude ```exe "imap \x1f ...```. Case closed - PR is ready for merge from my point of view.

**Comment by brammool** [comment]
One of the tests is failing:
Found errors in Test_GUI_lowlvl_QWERTY_Ctrl_minus_Ex():
7981
	command line..script D:/a/vim/vim/src/testdir/runtest.vim[468]..function RunTheTest[44]..Test_GUI_lowlvl_QWERTY_Ctrl_minus_Ex[47]..SwapExists Autocommands for "*"..function HandleSwapExists line 10: Unexpected swap file: .Xresult.swp

**Comment by ant0sha** [comment]
> One of the tests is failing: Found errors in Test_GUI_lowlvl_QWERTY_Ctrl_minus_Ex(): 7981 command line..script D:/a/vim/vim/src/testdir/runtest.vim[468]..function RunTheTest[44]..Test_GUI_lowlvl_QWERTY_Ctrl_minus_Ex[47]..SwapExists Autocommands for "*"..function HandleSwapExists line 10: Unexpected swap file: .Xresult.swp

very strange. File is created with "write Xresult" so no swap file has to be involved.

renamed file to rule out CI working on some outdated commit. Lets see how that performs.

**Comment by brammool** [comment]
When writing a file Vim checks that there isn't a swap file for it, to avoid overwriting a file that's being edited in another Vim instance.

**Comment by zewpo** [comment]
Hi @ant0sha 

I created a new method **test_mswin_event**, specifically for windows.   It works for windows gui as well as windows console. 
 This new method functionally overlaps with **test_gui_event**.   Actually, when the windows gvim gui is running test_mswin_event is effectively just a wrapper alias for test_gui_event.     

One thing to note that impacts on this PR #10823, is that I changed one of the arguments for test_gui_event; the "event" arg for sending "keyup" or "keydown", previously was named "sendevent", that is renamed to "key".   

```
---        "sendevent" send a low-level GUI event.
+++        "key"    send a low-level keyboard event.
```

Long story short - I'm now trying to add some more tests to the new test_mswin_event.vim test script file, making use of the new method to also cover the Ctrl minus question raised here.  

Couple things to note; to being able to map `\<C-_>`

When in angle brackets like that, I assume that these are interpreted as a sequence of raw keys.   Problem is, underscore is not a raw key. There is no actual raw unmodified key on my keyboard that is underscore '_'   

On my keyboard, (on a Dell XPS 15 with US keyboard layout) - I have one key that is physically stamped with two characters, the raw character is '-' the hyphen character, and in the higher Shift position shows an '_' underscore character.

image

According to ms website;
https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

```
VK_OEM_MINUS | 0xBD | For any country/region, the '-' key
VK_SHIFT | 0x10 | SHIFT key
VK_CONTROL | 0x11 | CTRL key
```

Pressing the VK_OEM_MINUS key by itself sends a [0xBD] keydown event, and releasing it sends [0xBD] keyup event - and the windows keyboard driver maps that to the ascii character '0x2D' for hyphen '-'

To get the underscore character, I have to press VK_SHIFT and VK_OEM_MINUS together, sends [0x10, 0xBD], down and up, and the windows keyboard driver maps that to the ascii character '0x5F' for underscore '_'

ie, ` \<S--> is '_'  #('0x5F')`

Now, pressing the keys VK_CONTROL and VK_OEM_MINUS, sends [0x11, 0xBD], down and up, and the windows keyboard driver maps that to the ascii character '0x1F', stylized as  '^_'

ie,` \<C--> is '^_' #('0x1F')`


Long winded way for me to say that I don't know how to physically type \<C-_> on my keyboard!

Is the expectation that pressing  VK_CONTROL and VK_OEM_MINUS can be mapped FROM ` \<C-_>`?

I'd like to write test for this with the new test_mswin_event, but I'm not certain what the expected outcome should be.

**Comment by ant0sha** [comment]
> Long winded way for me to say that I don't know how to physically type <C-_> on my keyboard!

There is no way,( On us keyboard layout) as best of my knowledge.  You can only hold  "Ctrl", and press "minus" that should in w32 gvim result in "Ctrl" followed by "underscore" put into vim internal keystrokes buffer for processing (well with some CSI prefix if I remember correctly). Without patch it puts literally "Ctrl" followed by "minus". Windows does nothing with that as far as I know, at least in gvim.

**Comment by zewpo** [comment]
Yeah, I see C-- converts to C-_ in the win32 console, but not at the moment in the GUI.

I don't know why it was removed from the GUI, but it looks like it was removed in this patch;

> patch 8.2.4807: processing key eveints in Win32 GUI is not ideal 
> LemonBoy on 4/23/2022, 7:45:52 AM
> Problem:    Processing key eveints in Win32 GUI is not ideal.
> Solution:   Improve processing of key events. (closes #10155)

I'm reading through the code, to see if I can figure out why it happened.

Hey @LemonBoy  any ideas why this was removed?

**Comment by zewpo** [comment]
I think your patch for gui_w32.c is correct.  

It makes w32 gui gvim behave like it used to, for nearly 20 years, up until patch 8.2.4807 4/23/2022,  and it will bring it back in line with the GTK version, as well as the windows console and xterm versions too.

I'm just about to submit a new PR with a couple of fixes for the test_mswin_event method, and it will also include test scripts that can cover this  PR.   If @brammool  is OK to merge just the .c code fix of this PR,  - then my next PR will include test scripts with something along the following lines;

```
" Test for QWERTY Ctrl+- which should result in ^_
" issue #10817 and PR #10823
func Test_QWERTY_Ctrl_minus()
  CheckMSWindows
  new

  call SendKeyGroup([s:VK.CONTROL, s:VK.OEM_MINUS])
  let ch = getcharstr(0)
  call assert_equal(nr2char(0x1f),ch)

  %d _
  imapclear
  imap <C-_> BINGO
  call SendKey(s:VK.KEY_I)
  call SendKeyGroup([s:VK.CONTROL, s:VK.OEM_MINUS])
  call SendKey(s:VK.ESCAPE)
  call ExecuteBufferedKeys()
  call assert_equal('BINGO', getline('$'))

  %d _
  imapclear
  exec "imap \x1f BILBO"
  call SendKey(s:VK.KEY_I)
  call SendKeyGroup([s:VK.CONTROL, s:VK.OEM_MINUS])
  call SendKey(s:VK.ESCAPE)
  call ExecuteBufferedKeys()
  call assert_equal('BILBO', getline('$'))

  imapclear
  bw!
endfunc
```

**Comment by brammool** [comment]
> Yeah, I see C-- converts to C-_ in the win32 console, but not at the
> moment in the GUI.

The function that handles these exceptions is may_adjust_key_for_ctrl().


> I don't know why it was removed from the GUI, but it looks like it was
> removed in this patch;
> 
> > patch 8.2.4807: processing key eveints in Win32 GUI is not ideal 
> > LemonBoy on 4/23/2022, 7:45:52 AM
> > Problem:    Processing key eveints in Win32 GUI is not ideal.
> > Solution:   Improve processing of key events. (closes #10155)
> 
> I'm reading through the code, to see if I can figure out why it happened.
> 
> Hey @LemonBoy  any ideas why this was removed?

This patch had several undesired side effects which had to be fixed.
This might be one more.

It would be nice to add the fix and a regression test at the same time.
But that would require including the patch for the MS-Windows event
testing first.  Is that feasible?

-- 
To the optimist, the glass is half full.
To the pessimist, the glass is half empty.
To the engineer, the glass is twice as big as it needs to be.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by zewpo** [comment]
Thanks  @brammool  for referring us to `may_adjust_key_for_ctrl()`
I was able to see how that's used in x11, gtk and term versions, so have added it into gui_w32.c.  
See PR  https://github.com/vim/vim/pull/11760

Actually, looking at `may_adjust_key_for_ctrl()`,  - I guess it's worth adding that to os_win32.c terminal console version too.  Will update PR #11760 with that today sometime.

**Comment by brammool** [comment]
Do we still need this PR or did it get included with PR #11760 ?
If it's still needed, please merge the recent changes.

**Comment by zewpo** [comment]
I believe that #11760 incorporates the essence of this PR.
ie, adding may_adjust_key_for_ctrl() to gui_w32.c resolved what this PR was intended for, 
it resolves issue #10817
#11760  also includes the respective test cases.
@ant0sha can confirm.

**Comment by ant0sha** [comment]
> I believe that #11760 incorporates the essence of this PR. ie, adding may_adjust_key_for_ctrl() to gui_w32.c resolved what this PR was intended for, it resolves issue #10817 #11760 also includes the respective test cases. @ant0sha can confirm.

Thanks, I confirm, please close this PR.

**Pull request closed without merging**
