### PR TITLE
Add autocmd_get() and autocmd_set() functions to get and set autocmds

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by bfrg** [comment]
Is there a way to set a callback function directly instead of a command?

**Comment by yegappan** [comment]
>
> Is there a way to set a callback function directly instead of a command, just like we can set callbacks for jobs,
> timers or popups?
>

Currently you can use only an Ex command to handle an autocmd event.
It is possible to modify this to support a callback function.

- Yegappan

**Comment by brammool** [comment]
What does autocmd_set() do when there already is an autocommand with the same group?  When using ":autocmd" it would get added, which probably works best.  Having a "delete" flag for autocmd_set() seems strange.  Perhaps it's better to use autocmd_add() and autocmd_delete().

**Comment by vim-ml** [comment]
Hi Bram,

On Tue, Apr 26, 2022 at 2:00 PM Bram Moolenaar ***@***.***>
wrote:

> What does autocmd_set() do when there already is an autocommand with the
> same group? When using ":autocmd" it would get added, which probably works
> best.
>

Yes. The behavior of autocmd_set() is the same as the ":autocmd" command.
If an autocommand already exists for a given group, event and pattern,
then the new command is added to the list.


> Having a "delete" flag for autocmd_set() seems strange. Perhaps it's
> better to use autocmd_add() and autocmd_delete().
>
>
>
I will add a separate function for deleting autocmds.

Regards,
Yegappan

**Comment by bfrg** [comment]
@yegappan Currently it is not documented how `autocmd_set()` behaves when both `bufnr` and `pattern` are specified.

**Comment by bfrg** [comment]
I think this PR also addresses #6339.

**Comment by yegappan** [comment]
>
> @yegappan Currently it is not documented how `autocmd_set()` behaves when both `bufnr` and `pattern` are specified.
>

I have updated the help text to describe how buffer-local autocmds can be added and deleted.

**Comment by bfrg** [comment]
Personally I preferred the previous version where a buffer number could be specified directly without doing any string concatenation like `'<buffer=' .. bufnr(mybuf) .. '>'`.

The documentation just wasn't clear enough whether the `bufnr` or `pattern` option had precedence when both were specified.

I think it would be a lot more readable if we could set the buffer number directly, especially in `vim9script`.

**Comment by yegappan** [comment]
> Personally I preferred the previous version where a buffer number could be specified directly without doing 
> any string concatenation like `'<buffer=' .. bufnr(mybuf) .. '>'`.
>
> The documentation just wasn't clear enough whether the `bufnr` or `pattern` option had precedence when both
> were specified.
> 
> I think it would be a lot more readable if we could set the buffer number directly, especially in `vim9script`.

I have updated the PR to support specifying the buffer number and updated the doc.

**Comment by brammool** [comment]
I'll leave this open for comments a couple of days.

Nit: "automatic commands" isn't used in the help, only "autocmds" and "autocommands".  It's a weird name anyway, but we're stuck with it.

**Comment by bfrg** [comment]
I think the documentation in `:h autocmd_delete()` is outdated.

In the examples of `autocmd_delete()` the function is called with the entry `'delete'` which doesn't exist.

And what is the purpose of `nested` or `once` in `autocmd_delete()`? Aren't these options only useful for `autocmd_add()`?

**Comment by bfrg** [comment]
The documentation uses `{cmds}` or `{cmd}` to refer to the arguments in `autocmd_delete({cmds})` and `autocmd_add({cmds})`. I think this is a bit confusing since there's already an entry called `cmd`.

**Comment by brammool** [comment]
@yegappan  can you respond to the comments by @bfrg ?

**Comment by vim-ml** [comment]
Hi,

On Sat, Apr 30, 2022 at 3:24 AM bfrg ***@***.***> wrote:

> I think the documentation in :h autocmd_delete() is outdated.
>
> In the examples of autocmd_delete() the function is called with the entry
> 'delete' which doesn't exist.
>

I have updated the examples for autocmd_delete() to remove the 'delete"
item.


> And what is the purpose of nested or once in autocmd_delete()? Aren't
> these options only useful for autocmd_add()?
>
>
>
These are optional items. You can get a list of autocmds using the
autocmd_get() function
and pass the list to autocmd_delete() to remove the autocmds. In this case,
these items
will be present.

- Yegappan

**Comment by lacygoill** [comment]
One common pitfall when adding an autocmd is to forget to wrap it inside a self-clearing augroup.

Bad:
```vim
autocmd CursorHold * echomsg 'do something'
```
Good:
```vim
augroup MyGroup
    autocmd!
    autocmd CursorHold * echomsg 'do something'
augroup END
```
The first snippet is bad, because if for some reason the script is sourced multiple times, there will be a duplicate autocmd:
```vim
vim9script
var code = 'autocmd CursorHold * echomsg "do something"'
[code]->writefile('/tmp/script.vim')
source /tmp/script.vim
source /tmp/script.vim
autocmd CursorHold
```
    --- Autocommands ---
    CursorHold
        *         echomsg "do something"
                  echomsg "do something"


Depending on the cost of the executed command and/or the frequency of the event, this might slow Vim down noticeably, or even cause errors.

---

Now, here is how we can rewrite the good snippet with the new functions:
```vim
vim9script
if exists('#MyGroup')
    autocmd_delete([{group: 'MyGroup', event: '*'}])
endif
autocmd_add([{group: 'MyGroup', event: 'CursorHold', pattern: '*', cmd: "echomsg 'do something'"}])
```
The whole `if exists()` block is cumbersome to read/write every single time we need to add an autocmd.  Would it make sense for the dictionaries expected by `autocmd_add()` to support an extra `unique` boolean option (`true` by default)?

When `unique` is true, the autocmd would not be added if it's inside an augroup which already includes the same autocmd.  And since `unique` would be `true` by default, we could completely omit the previous `if exists()` block.

**Comment by nickspoons** [comment]
@brammool's comment from the mailing list, which hasn't come through to github:

> The whole `if exists()` block is cumbersome to read/write every single time we need to add an autocmd.

Using "silent!" helps though.  Here you don't care about errors.

> Would it make sense for the dictionaries expected by `autocmd_add()` to support an extra `unique` boolean option (`true` by default)?
> 
> When `unique` is true, the autocmd would not be added if it's inside an augroup which already includes the same autocmd.  And since `unique` would be `true` by default, we could completely omit the previous `if exists()` block.

It's probably better to add a "replace" argument: If an autocommand for this group and event already exists, replace it with this one.  This works better when someone edits the .vimrc to change the command, sourcing the file again should use the new one, not keep the old one.

    autocmd_add([{replace: true, group: 'MyGroup', event: 'CursorHold', pattern: '*', cmd: "echomsg 'do something'"}])

**Comment by nickspoons** [comment]
> It's probably better to add a "replace" argument: If an autocommand for this group and event already exists, replace it with this one.

I think either `unique` or `replace` are both fine (although `unique` is more descriptive in my mind), as long as the default value is `true` so we normally don't need to use it, or even know about it! It is very rare that an autocmd should _not_ replace an existing one with the same group and event.

**Comment by vim-ml** [comment]
Hi,

On Mon, May 23, 2022 at 1:40 PM Nick Jensen ***@***.***>
wrote:

> It's probably better to add a "replace" argument: If an autocommand for
> this group and event already exists, replace it with this one.
>
> I think either unique or replace are both fine (although unique is more
> descriptive in my mind), as long as the default value is true so we
> normally don't need to use it, or even know about it! It is very rare that
> an autocmd should *not* replace an existing one with the same group and
> event.
>
>
> If the 'replace' item is specified, then autocmd_add() will remove all the
commands
associated with an autocmd event in the group and add the new command.  If a
group is not specified, then the default group will be used. This is same
as running
the following command:

autocmd! {group} {event} {pat} {cmd}

If we make 'replace' the default, then a call to autocmd_add() in a .vimrc
file will
remove commands added by a plugin (in the default group) for that event.
A user may not expect this. So we should not make 'replace' as the default.

- Yegappan

**Comment by lacygoill** [comment]
> If a group is not specified, then the default group will be used.
   > [...]
   > If we make 'replace' the default, then a call to autocmd_add() in a .vimrc
   > file will remove commands added by a plugin (in the default group) for that event.
   > A user may not expect this.

IMO, an autocmd should always be added in a named augroup; not in the default one.  Unless we're quickly testing some feature.

I was not clear enough in the previous post, sorry.  My idea was for `unique`/`replace` to be considered only when the autocmd was placed in a named augroup.  Because AFAIK the default augroup can't be cleared specifically (right?).  So, it wouldn't make sense for `autocmd_add()` to provide a feature which was not also provided by `:autocmd`.

And if `replace` is ignored for the default augroup, then there would be no issue (right?).

The only counter-argument I can find is that it would make `replace` more complicated to understand.  But IMO, doing what the user expects is more important.  And to quote [`:help local-options`](https://vimhelp.org/options.txt.html#local-options):

   > Unfortunately, doing what the user expects is a bit complicated...

Anyway, the mere introduction of `replace` would already be a big improvement.  Making it default for *named* augroups would be even better, but not that important.

Thank you very much for working on these functions, they're very useful.

**Comment by vim-ml** [comment]
Yegappan wrote:

> On Mon, May 23, 2022 at 1:40 PM Nick Jensen ***@***.***>
> wrote:
> 
> > It's probably better to add a "replace" argument: If an autocommand for
> > this group and event already exists, replace it with this one.
> >
> > I think either unique or replace are both fine (although unique is more
> > descriptive in my mind), as long as the default value is true so we
> > normally don't need to use it, or even know about it! It is very rare that
> > an autocmd should *not* replace an existing one with the same group and
> > event.
> >
> >
> > If the 'replace' item is specified, then autocmd_add() will remove all the
> commands
> associated with an autocmd event in the group and add the new command.  If a
> group is not specified, then the default group will be used. This is same
> as running
> the following command:
> 
> autocmd! {group} {event} {pat} {cmd}
> 
> If we make 'replace' the default, then a call to autocmd_add() in a .vimrc
> file will
> remove commands added by a plugin (in the default group) for that event.
> A user may not expect this. So we should not make 'replace' as the default.

Right, having "replace" be the default goes against what would normally
be expected.  For example:

	autocmd_add( ... some group and event ..., command one)
	autocmd_add( ... some group and event ..., command two)

Here the user adds two commands for the same group and event.  Both
should be added.  Having the second one remove the first one is very
unexpected.  Note that the two commands could be far apart.

-- 
Facepalm statement #4: "3000 year old graves?  That's not possible, it's only
2014!"

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by lacygoill** [comment]
There is another issue: it's not easy to use `autocmd_add()` to install an autocmd listening to several events.
```vim
vim9script
autocmd_add([{group: 'SomeGroup', event: 'BufEnter,WinEnter,VimEnter', pattern: '*', cmd: 'echomsg "do something"'}])
autocmd
```
    --- Autocommands ---
    SomeGroup  BufEnter
        *         echomsg "do something"

Notice that `autocmd_add()` has ignored everything after the comma (i.e. `WinEnter` and `VimEnter`).

It would be useful for the `event` key to either accept a comma-separated list of events, or better yet a list of strings.  Trying the latter currently gives `E730`:
```vim
vim9script
autocmd_add([{group: 'SomeGroup', event: ['BufEnter', 'WinEnter', 'VimEnter'], pattern: '*', cmd: 'echomsg "do something"'}])
```
    E730: Using a List as a String

**Comment by lacygoill** [comment]
And I guess the same limitation applies to a comma-separated list of patterns.

**Comment by brammool** [comment]
> There is another issue: it's not easy to use `autocmd_add()` to install an autocmd listening to several events.
> ```vim
> vim9script
> autocmd_add([{group: 'SomeGroup', event: 'BufEnter,WinEnter,VimEnter', pattern: '*', cmd: 'echomsg "do something"'}])
> autocmd
> ```
>     --- Autocommands ---
>     SomeGroup  BufEnter
>         *         echomsg "do something"
> 
> Notice that `autocmd_add()` has ignored everything after the comma
> (i.e. `WinEnter` and `VimEnter`).

This should at least give an error.

> It would be useful for the `event` key to either accept a
> comma-separated list of events, or better yet a list of strings.
> Trying the latter currently gives `E730`:
> ```vim
> vim9script
> autocmd_add([{group: 'SomeGroup', event: ['BufEnter', 'WinEnter', 'VimEnter'], pattern: '*', cmd: 'echomsg "do something"'}])
> ```
>     E730: Using a List as a String

Comparing the alternatives:
	event: 'BufEnter,WinEnter,VimEnter',
	event: ['BufEnter', 'WinEnter', 'VimEnter']

Just using a string with commas is shorter and has less puncutation.
Is there a reason to use a list?

-- 
You cannot propel yourself forward by patting yourself on the back.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LemonBoy** [comment]
+1 for using lists for lists of things, otherwise there would be no point in having types other than strings (and reinvent a poor man's TCL).

**Comment by brammool** [comment]
> +1 for using lists for lists of things, otherwise there would be no
> point in having types other than strings (and reinvent a poor man's
> TCL).

Conceptually using a list for what is a list of words makes a lot of
sense.

You could even avoid writing the list by doing:
	'OneEvent,TwoEvent,ThreeEvent'->split(',')

If you are allergic to square brackets ...

-- 
"My particular problem is with registry entries, which seem to just
accumulate like plastic coffee cups..."           -- Paul Moore

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
