### PR TITLE
testdir/test_exists.vim: add test for empty environment variable

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/neovim/neovim/pull/10657

### CODE REVIEW

**Comment by k-takata** [comment]
Setting an empty string to an environment variable deletes the variable on Windows.
So, `exists()` will return 0 on Windows.

**Comment by blueyed** [comment]
> Setting an empty string to an environment variable deletes the variable on Windows.

Is that a Windows issue, or due to how Vim does it?
It appears to work with Neovim, which uses libuv.

For setting: https://github.com/neovim/libuv/blob/c41b31ed3b88aacae1d8498d0f3f6bbc20d56f9a/src/win/util.c#L1456-L1484

But likely more related to how it gets it: https://github.com/neovim/libuv/blob/c41b31ed3b88aacae1d8498d0f3f6bbc20d56f9a/src/win/util.c#L1456-L1484
It uses `GetEnvironmentVariableW` and checks for `ERROR_ENVVAR_NOT_FOUND` when it gets an empty value.

**Comment by k-takata** [comment]
> Is that a Windows issue, or due to how Vim does it?

It's the behavior of [`_wputenv`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-wputenv?view=vs-2019). The `set` command of cmd.exe is also the same. So, this behavior is natural for Windows users.
It seems that `SetEnvironmentVariable` API can set an empty string, but it doesn't set an environment variable for C runtime library. So we cannot use it. (E.g. gettext depends on it.)

**Comment by blueyed** [comment]
I see.  Should we adjust this test and the one in https://github.com/vim/vim/pull/4751 for win32 behavior then?

**Comment by k-takata** [comment]
I think so.

**Comment by blueyed** [comment]
btw: I've also noted that `getenv()` might return something that `environ()` does not contain:
```vim
unlet! $VIMRUNTIME
" Fails
echo environ()['VIMRUNTIME']
" Works
echo getenv('VIMRUNTIME')
echo environ()['VIMRUNTIME']
```
This is due to the side-effect of `vim_getenv` handling and setting this.

**Comment by brammool** [comment]
This is not portable, different systems have different ideas about whether an environment variable with an empty value exists or not.
The special handling of $VIMRUNTIME is documented, I thought.  Anyway, one should not delete it.
I don't think we should have a test for undefined behavior.

**Comment by blueyed** [comment]
> different systems have different ideas about whether an environment variable with an empty value exists or not.
> I don't think we should have a test for undefined behavior.

I think Vim is defining it in this case (since Neovim handles it differently on the same system (Windows)), and if the special behavior with win32 is kept, then it would be good to have this tested / documented.
It is not "undefined" really as in "changes randomly".

**Pull request closed without merging**
