### PR TITLE
Cython files are not recognized

### PR DESCRIPTION
**Pull request by amaanq**
https://cython.org/

Problem: Cython files are not recognized.
Solution: Add a pattern for Cython files. (Amaan Qureshi)

### CODE REVIEW

**Comment by brammool** [comment]
Conflicts with Pyrex patterns.  Perhaps the difference can be seen in the file contents?

**Comment by amaanq** [comment]
Both Pyrex and Cython are extensions of Python to interop with C, syntax will be very similar to Python and I don't know of an easier way to distinguish them. Cython seems to be used far more in my opinion, last stable release of Pyrex was 12 years ago and seems to be hardly used (I hadn't heard of it until you pointed it out).

**Comment by chrisbra** [comment]
You could add a `filetype_pyx` variable and simply document that the user should set those variables to have `cython` files instead of `pyrex`, see https://github.com/vim/vim/blob/4b3fab14dbde971f15d8783e9ef125b19fdbc829/runtime/doc/filetype.txt#L135-L142

**Comment by chrisbra** [comment]
closing for inactivity

**Pull request closed without merging**
