### PR TITLE
Minor update of syntax files

### PR DESCRIPTION
**Pull request by ghost**
Add ‘`Enable`’ and ‘`Download-Upgradeable-Packages-Debdelta`’
    to file `runtime/syntax/aptconf.vim`
Add ‘`colored-stats`’ and ‘`show-mode-in-prompt`’
    to file `runtime/syntax/readline.vim`

### CODE REVIEW

**Comment by chrisbra** [comment]
Please first contact the maintainers of the appropriate syntax files. They will send updated files to Bram for inclusion. when they don't react, please contact vim-dev ml

**Comment by ghost** [comment]
##### For `runtime/syntax/readline.vim`

Well, I've been in touch with Nikolai and last I heard, he didn't have enough time to continue maintaining it anymore, so he asked me to send my changes, which is what I just did and whether I would like to take maintainership of it. I’m ok with that, just not sure how to do so.

##### For `runtime/syntax/aptconf.vim`

The e-mail has been sent, just waiting for the reply.

**Comment by vim-ml** [comment]
Hi rbazaud!

On So, 25 Okt 2015, rbazaud wrote:

> ##### For `runtime/syntax/readline.vim`
> 
> Well, I've been in touch with Nikolai and last I heard, he didn't have enough time to continue maintaining it anymore, so he asked me to send my changes, which is what I just did and whether I would like to take maintainership of it. I’m ok with that, just not sure how to do so.

If you want to take maintainership, make your changes, edit the header 
and put yourself as the maintainer, moving Nikolai to the Previous 
Maintainer and then send the complete file for inclusion with Vim and 
refer to this thread.

Best,

## Christian

Das sichere Zeichen des beginnenden Alters ist, daß man geschwind
noch einige Jugendtorheiten begeht.
        -- Anonym

**Comment by ghost** [comment]
Hi Christian, thanks for the information. I’ve sent the file `readline.vim` to Bram, with Nikolai in `cc` (I’d have put you as well but I don’t have your e-mail address). I’ve committed the change of maintainer name and squashed the commit.

**Comment by brammool** [comment]
rbazaud wrote:

> Add ‘`Enable`’ and ‘`Download-Upgradeable-Packages-Debdelta`’
>     to file `runtime/syntax/aptconf.vim`
> Add ‘`colored-stats`’ and ‘`show-mode-in-prompt`’
>     to file `runtime/syntax/readline.vim`
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/vim/vim/pull/462
> 
> -- Commit Summary --
> - Minor update of syntax files
> 
> -- File Changes --
> 
> ```
> M runtime/syntax/aptconf.vim (8)
> M runtime/syntax/readline.vim (4)
> ```

Can you please add your full name to the github account?
I have no idea who "rbazaud" is.

I prefer the updated files to be emailed, so that I have a history of
where something is coming from.

## 

Q: What is a patch 22?
A: A patch you need to include to make it possible to include patches.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
My profile has been updated as requested, FWIW my full name is in every one of my commits and it was also accessible one click after the page refered to in a previous message. It is also in the file sent by e-mail.

The proposition has been sent by e-mail as well (same as the pull request which passed successfully every integration test as it's not code _stricto sensu_). Never got any reply from the supposed `aptconf.vim` maintainer, which isn't very surprising in itself (I’ve given a possible explanation by e-mail).

**Comment by chrisbra** [comment]
Has this file been included yet?

**Comment by ghost** [comment]
I don't think so.

2016-05-19 17:25 GMT+02:00 Christian Brabandt notifications@github.com:

> Has this file been included yet?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/vim/vim/pull/462#issuecomment-220359625

## 

_Raphaël Bazaud_

**Comment by k-takata** [comment]
It seems that they are all included. Closing.

**Pull request closed without merging**
