### PR TITLE
Add HEEx ftplugin

### PR DESCRIPTION
**Pull request by mhanberg**
Sets basic stuff like the comment string and the tab settings.

### CODE REVIEW

**Comment by brammool** [comment]
i'll include it, thanks.  Setting and restoring 'cpo' is not really needed in this case.

**Review by habamax — COMMENTED** [review]
`b:undo_ftplugin` is missing

**Comment by mhanberg** [comment]
@brammool really sorry about this, but I made a couple of mistakes here.

`commentstring` should be `set commentstring=<%!--\ %s\ --%>`
`comments` should be `set comments=:<%!--` (I'm not actually sure if that `:` needs to be there for `comments`).

This comment syntax was added in Elixir 1.14, which was released very recently, and should be used moving forward.

Thanks, and sorry about that.

**Comment by brammool** [comment]
> @brammool really sorry about this, but I made a couple of mistakes here.
> 
> `commentstring` should be `set commentstring=<%!--\ %s\ --%>`
> `comments` should be `set comments=:<%!--` (I'm not actually sure if that `:` needs to be there for `comments`).
> 
> This comment syntax was added in Elixir 1.14, which was released very
> recently, and should be used moving forward.
> 
> Thanks, and sorry about that.

Thus the comment style mentioned here is no longer used anywhere:
```
	<%# This is a comment. %>
```

Seems like a drastic change.

Adding the undo variable, I end up with this:

```

setlocal shiftwidth=2 softtabstop=2 expandtab

setlocal comments=:<%!--
setlocal commentstring=<%!--\ %s\ --%>

let b:undo_ftplugin = 'set sw< sts< et< com< cms<'
```

-- 
hundred-and-one symptoms of being an internet addict:
119. You are reading a book and look for the scroll bar to get to
     the next page.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
