### PR TITLE
new command :xrestore to restore X11 connection after X11 server restart

### PR DESCRIPTION
**Pull request by adizero**
Added new command :xrestore to reinitialize connection to X11 server. Useful after X server restarts (e.g. when running Vim for a long time inside screen/tmux and connecting from different machines). Requires +clipboard feature to be compiled in Vim.

Usage:

Reinitialize connection to X11 server running on localhost:11.0: 

```
:xrestore localhost:11.0
```

Reinitialize connection while keeping X11 server from the last invocation of this command (if it was never executed with an argument, then the X11 server address is the one, that Vim read during startup from DISPLAY environment variable):

```
:xrestore
```

### CODE REVIEW

**Comment by OSS542** [comment]
has this command been removed ?

**Comment by jeenuv** [comment]
I'm occasionally [troubled](https://groups.google.com/forum/#!topic/vim_use/QNuq7_s6P9A) by bad rendering after an X server disconnection/restart, so am looking forward to this PR getting merged!

**Comment by jeenuv** [comment]
Seeing this has been closed, is there an alternative/workaround?

**Comment by rakus** [comment]
@jeenuv Patch 8.1.1307 introduced then new command `:xrestore`. See the commit Bram used to close this pull request.

**Pull request closed without merging**
