### PR TITLE
Clear termguicolors guibg with :hi * guibg=NONE

### PR DESCRIPTION
**Pull request by nickspoons**
This is a patch by @nuko8 from #981, allowing terminal vim to clear the background when using termguicolors

### CODE REVIEW

**Comment by chrisbra** [comment]
You forgot to mention which problem this fixes.

**Comment by nickspoons** [comment]
@chrisbra in terminal vim when using `:set termguicolors` it is not possible to clear the background (allowing transparency or the terminal background to be displayed). `:hi Normal guibg=NONE` has no effect, so the only way to get a transparent background in a true color terminal is by not setting the guibg - which in many cases means patching colorschemes.

This patch (not written by me) allows `:hi Normal guibg=NONE` to clear an existing `guibg` highlight. See #981 for more information.

**Comment by brammool** [comment]
Nick Jensen wrote:

> This is a patch by @nuko8 from #981, allowing terminal vim to clear
> the background when using termguicolors

Can we have some examples of what this fixes?  And how do we know this
doesn't break anything?

-- 
"You're fired." (1980)
"You're laid off." (1985)
"You're downsized." (1990)
"You're rightsized." (1992)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nickspoons** [comment]
Here's an example of an unpatched vim (above) and a patched vim (below) on black terminal backgrounds. The unpatched can't clear its guibg highlight so keeps the grey background colour which gets set in the colorscheme.
guibg-example

For each of these, the command `:hi Normal` outputs `Normal        xxx ctermfg=223 guifg=#ebdbb2`.

@brammool the current tests pass. I don't know how to otherwise ensure that it doesn't break anything else.

**Comment by nickspoons** [comment]
Minimum steps to reproduce:

1. vim -u NONE
2. `:set termguicolors`
3. `:hi Normal guibg=Red`
4. `:hi Normal guibg=NONE`

Without this patch, the background remains red.

I have built and tested vim and gvim on Arch linux, and vim on cygwin (Windows 7)

**Comment by joaqo** [comment]
Hey, sorry if I am reviving an old ticket, but just got to this PR after a couple of hours of debugging my vimrc using google. It seems that this PR will solve my particular problems. Do you guys know if it will get accepted any time soon? Should I just build it myself? Thanks a lot for the work you are doing, and sorry if this kind of pinging old PRs is frowned upon.

**Comment by gpakosz** [comment]
Landed here as well after having read #981.

Could this PR be revived by chance?

**Comment by gpakosz** [comment]
Thanks Bram 👍

**Comment by mcepl** [comment]
Awesome! My vim looks reasonably now, not like a malnourished tiger. Thank you. Made me even make [out-of-cycle build on my COPR](https://copr.fedorainfracloud.org/coprs/build/721742/) for Fedora/RHEL.

**Comment by nickspoons** [comment]
Thanks Bram, this is great.

**Pull request closed without merging**
