### PR TITLE
Update syntax/dosini.vim to the latest version

### PR DESCRIPTION
**Pull request by xuhdev**
The latest version is in https://github.com/xuhdev/syntax-dosini.vim/blob/master/syntax/dosini.vim. I've sent the file to Bram at the end of June, unfortunately it wasn't able to make into the Vim repository. RIP!

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks.

**Comment by chrisbra** [comment]
@xuhdev I think this patch introduced a slight regression. Can you please have a look at the patch posted here: https://groups.google.com/g/vim_use/c/9zccgo_RIqM/m/4OOjewNOBgAJ

Do you want to incorporate this into your version first or can I go ahead and merge it?

Thanks,
Chris

**Comment by xuhdev** [comment]
On 8/20/23 01:58, Christian Brabandt wrote:
> @xuhdev <https://github.com/xuhdev> I think this patch introduced a slight regression. Can you please have a look at the patch posted here: https://groups.google.com/g/vim_use/c/9zccgo_RIqM/m/4OOjewNOBgAJ <https://groups.google.com/g/vim_use/c/9zccgo_RIqM/m/4OOjewNOBgAJ>
> 
> Do you want to incorporate this into your version first or can I go ahead and merge it?
> 

I'm good with either way. I've merged the PR you created. Feel free to port it to this repo.

Thanks

**Comment by chrisbra** [comment]
okay I have merged it in 690963924

**Pull request merged**
