### PR TITLE
win32: Remove old code for VC++ 6.0 or older

### PR DESCRIPTION
**Pull request by k-takata**
There were many #ifdefs for VC6. Make the code cleaner.

### CODE REVIEW

**Comment by k-takata** [comment]
Maybe we can also remove the code for VC++ 7.0/7.1 (VS 2002/2003)?

**Comment by brammool** [comment]
I can include this one first.  I think the oldest that still works in VC 2008, or studio 9.0..  Haven't tried it though.
Supporting older versions can be useful in some cases, newer versions tend to drop support for older MS-Windows.

**Comment by k-takata** [comment]
VC 2005 is the last version that supports building for Windows 9x.
VC 2010 is the last version that supports building for Windows XP without adding the `/subsystem` linker option. Also, this is the last version that doesn't support the C99 style variable declaration.
VC 2013 is the last version before switching to Universal CRT.
VC 2015 is the last version that includes Windows SDK 7.1 that supports building for Windows XP.

VC 2008 and VC 2012 are not so notable, I think.

We use VC 2010 on AppVeyor, so it might be better to make VC 2010 as the oldest support version?

**Comment by brammool** [comment]
Ken Takata wrote:

> VC 2005 is the last version that supports building for Windows 9x.
> VC 2010 is the last version that supports building for Windows XP without adding the `/subsystem` linker option. Also, this is the last version that doesn't support the C99 style variable declaration.
> VC 2013 is the last version before switching to Universal CRT.
> VC 2015 is the last version that includes Windows SDK 7.1 that supports building for Windows XP.
> 
> VC 2008 and VC 2012 are not so notable, I think.
> 
> We use VC 2010 on AppVeyor, so it might be better to make VC 2010 as
> the oldest support version?

That makes sense.  I suppose there are not so many differences betwen VC
2008 and 2010.

We should also update INSTALLpc.txt.  I actually can't find the place
where to download older versions now.

-- 
Why don't cannibals eat clowns?
Because they taste funny.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
