### PR TITLE
xdiff: re-sync to git 2.33

### PR DESCRIPTION
**Pull request by chrisbra**
We have imported xdiff from git 3 years ago. Let's sync with upstream from git release 2.32.

### CODE REVIEW

**Comment by yegappan** [comment]
I am interested in this updated xdiff library getting merged. It will be good to
merge it early before the Vim9 release so that any regressions can be addressed.

**Comment by brammool** [comment]
It looks like several tests are failing.

**Comment by jimman2003** [comment]
Seems to me like an unrelated problem with the CI distro

**Comment by brammool** [comment]
@chrisbra can you push an update (sync) so that CI is triggered?

**Comment by chrisbra** [comment]
I am away currently, will do it once I return

**Comment by chrisbra** [comment]
updated and rebased to git v2.33.0

**Comment by chrisbra** [comment]
should be good now.

**Comment by chrisbra** [comment]
BTW: I am not sure if this makes sense, but I further refactored it to make future merging easier. I have not included it here, the diff on top would be this one here: https://github.com/chrisbra/vim/compare/xdiff_update...chrisbra:xdiff_update2?expand=1

Would it make sense to add this on top of it?

**Comment by brammool** [comment]
Let's include this first.  Then make a pull request for the other changes.

**Comment by brammool** [comment]
I wonder, some comments are back from // to /* */ form, is that what xdiff uses?

**Comment by chrisbra** [comment]
> I wonder, some comments are back from // to /* */ form, is that what xdiff uses?

Yes, that's what the source uses, see e.g. here: https://github.com/gitster/git/blob/v2.33.0/xdiff/xhistogram.c

**Comment by brammool** [comment]
Christian wrote:

> > I wonder, some comments are back from // to /* */ form, is that what
> > xdiff uses?
> 
> Yes, that's what the source uses, see e.g. here:
> https://github.com/gitster/git/blob/v2.33.0/xdiff/xhistogram.c

I'll add a note in the README that these should not be changed to //
comments.

-- 
Back off man, I'm a scientist.
              -- Peter, Ghostbusters

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
