### PR TITLE
Highlight more awk comments

### PR DESCRIPTION
**Pull request by jmdevin**
Some awk comments are not highlighted. The following is valid awk:
```awk
{ # Comment
    for (i = 0; # BAD
        i < 1; # BAD
        i++) # Comment
    { # Comment
        print # Comment
    } # Comment
} # Comment
```
In vim, the two comments `# BAD` are not currently highlighted. This fixes that issue.

### CODE REVIEW

**Comment by jmdevin** [comment]
@dkearns for review.

**Comment by chrisbra** [comment]
Thanks. Can you please create a syntax test for awk for this issue?

**Comment by jmdevin** [comment]
I think I added the test correctly. I'd like to expand it to be more comprehensive, but not a lot of time right now, unless there's anything specific you'd prefer added to it.

**Review by dkearns — APPROVED** [review]
Thanks.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
