### PR TITLE
Renamed "makefile_*.mak" for Vim documentation

### PR DESCRIPTION
**Pull request by RestorerZ**
The files "makefile_all.mak" and "makefile_mvc.mak" have been renamed to "make_all.mak" and "make_mvc.mak", respectively, for consistency with the adopted one.

### CODE REVIEW

**Comment by k-takata** [comment]
"Make_all.mak" and "Make_mvc.mak" might be better than "make_*.mak".

**Comment by chrisbra** [comment]
yes, please rename to `Make_mvc` like in the src directory to match the style

**Comment by RestorerZ** [comment]
> "Make_all.mak" and "Make_mvc.mak" might be better than "make_*.mak".

Done.

**Comment by chrisbra** [comment]
thanks!

**Pull request merged**
