### PR TITLE
Add %check as allowed section in SPEC files.

### PR DESCRIPTION
**Pull request by mcepl**
@ignatenkobrain What do you think?

### CODE REVIEW

**Comment by igor-raits** [comment]
LGTM

**Comment by mcepl** [comment]
> LGTM

So, how I should proceed to get this merged?

**Comment by chrisbra** [comment]
the usual way is to have the runtime file maintainer send an update to Bram for inclusion.

**Comment by mcepl** [comment]
> the usual way is to have the runtime file maintainer send an update to Bram for inclusion.

The hope that Bram would actually follow ``vim_dev`` is probably just a fantasy, right?

**Comment by igor-raits** [comment]
I remember in past @brammool has merged runtime PR related to spec.vim where I gave lgtm. Let's see if this is still the case...

**Comment by brammool** [comment]
I'll include it and update the date in the header, thanks.

**Pull request closed without merging**
