### PR TITLE
Update menu_it_it.latin1.vim

### PR DESCRIPTION
**Pull request by djemar**
Fixed typos.

### CODE REVIEW

**Comment by azazello4** [comment]
Fixed typos in Italian translation.

**Comment by brammool** [comment]
> Fixed typos.

It appears you have made all the shorcut keys lowercase.
They were uppercase for a reason.

-- 
If they don't keep on exercising their lips, he thought, their brains
start working.
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by djemar** [comment]
> 
> Fixed typos.
> It appears you have made all the shorcut keys lowercase. They were uppercase for a reason.
> […](#)
> -- If they don't keep on exercising their lips, he thought, their brains start working. -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy" /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\\ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\ \\\ an exciting new programming language -- http://www.Zimbu.org /// \\\ help me help AIDS victims -- http://ICCF-Holland.org ///

I'm sorry, which is? I didn't find any issue using them like this.

**Comment by vim-ml** [comment]
The uppercase letters can be used to express a menu choice without using
the mouse.
E.g.
<ALT>mt
does "Modify, Select All"

...contacting the maintainer could have helped.

Antonio


On Sun, Dec 16, 2018 at 6:22 PM Diego Marino <vim-dev-github@256bit.org>
wrote:

> Fixed typos.
> It appears you have made all the shorcut keys lowercase. They were
> uppercase for a reason.
> … <#m_-7634097560847384827_>
> -- If they don't keep on exercising their lips, he thought, their brains
> start working. -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy" ///
> Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\ ///
> sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\ \\ an
> exciting new programming language -- http://www.Zimbu.org /// \\ help me
> help AIDS victims -- http://ICCF-Holland.org ///
>
> I'm sorry, which is? I didn't find any issue using them like this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim/vim/pull/3693#issuecomment-447660336>
>
> --
> --
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
>
> ---
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>


-- 
   /||\    | Antonio Colombo
  / || \   |  azc100@gmail.com
 /  ()  \  | antonio@geekcorp.com
(___||___) |   azc10@yahoo.com

**Comment by djemar** [comment]
> 
> The uppercase letters can be used to express a menu choice without using the mouse. E.g. <ALT>mt does "Modify, Select All" ...contacting the maintainer could have helped. Antonio
> […](#)
> On Sun, Dec 16, 2018 at 6:22 PM Diego Marino ***@***.***> wrote: Fixed typos. It appears you have made all the shorcut keys lowercase. They were uppercase for a reason. … <#m_-7634097560847384827_> -- If they don't keep on exercising their lips, he thought, their brains start working. -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy" /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \\ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\ \\ an exciting new programming language -- http://www.Zimbu.org /// \\ help me help AIDS victims -- http://ICCF-Holland.org /// I'm sorry, which is? I didn't find any issue using them like this. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <[#3693 (comment)](https://github.com/vim/vim/pull/3693#issuecomment-447660336)> -- -- You received this message from the "vim_dev" maillist. Do not top-post! Type your reply below the text you are replying to. For more information, visit http://www.vim.org/maillist.php --- You received this message because you are subscribed to the Google Groups "vim_dev" group. To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.*** For more options, visit https://groups.google.com/d/optout.
> -- /||\ | Antonio Colombo / || \ | azc100@gmail.com / () \ | antonio@geekcorp.com (___||___) | azc10@yahoo.com

I know, but they work the same without them being uppercase.

**Comment by vim-ml** [comment]
...but then you have to know in advance which letter to type. Having them
uppercased means not to have to memorize everything. A.

On Sun, Dec 16, 2018 at 8:33 PM Diego Marino <vim-dev-github@256bit.org>
wrote:

> The uppercase letters can be used to express a menu choice without using
> the mouse. E.g. mt does "Modify, Select All" ...contacting the maintainer
> could have helped. Antonio
> … <#m_1885094882183546752_>
> On Sun, Dec 16, 2018 at 6:22 PM Diego Marino ***@***.***> wrote: Fixed
> typos. It appears you have made all the shorcut keys lowercase. They were
> uppercase for a reason. … <#m_-7634097560847384827_> -- If they don't keep
> on exercising their lips, he thought, their brains start working. --
> Douglas Adams, "The Hitchhiker's Guide to the Galaxy" /// Bram Moolenaar --
> Bram@Moolenaar.net -- http://www.Moolenaar.net \ /// sponsor Vim, vote
> for features -- http://www.Vim.org/sponsor/ \ \ an exciting new
> programming language -- http://www.Zimbu.org /// \ help me help AIDS
> victims -- http://ICCF-Holland.org /// I'm sorry, which is? I didn't find
> any issue using them like this. — You are receiving this because you are
> subscribed to this thread. Reply to this email directly, view it on GitHub <#3693
> (comment) <https://github.com/vim/vim/pull/3693#issuecomment-447660336>>
> -- -- You received this message from the "vim_dev" maillist. Do not
> top-post! Type your reply below the text you are replying to. For more
> information, visit http://www.vim.org/maillist.php --- You received this
> message because you are subscribed to the Google Groups "vim_dev" group. To
> unsubscribe from this group and stop receiving emails from it, send an
> email to ***@***.*** For more options, visit
> https://groups.google.com/d/optout.
> -- /||\ | Antonio Colombo / || \ | azc100@gmail.com / () \ |
> antonio@geekcorp.com (___||___) | azc10@yahoo.com
>
> I know, but they work the same without them being uppercase.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vim/vim/pull/3693#issuecomment-447669340>
>
> --
> --
> You received this message from the "vim_dev" maillist.
> Do not top-post! Type your reply below the text you are replying to.
> For more information, visit http://www.vim.org/maillist.php
>
> ---
> You received this message because you are subscribed to the Google Groups
> "vim_dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to vim_dev+unsubscribe@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.
>


-- 
   /||\    | Antonio Colombo
  / || \   |  azc100@gmail.com
 /  ()  \  | antonio@geekcorp.com
(___||___) |   azc10@yahoo.com

**Comment by djemar** [comment]
> 
> ...but then you have to know in advance which letter to type. Having them uppercased means not to have to memorize everything. A. On Sun, Dec 16, 2018 at 8:33 PM Diego Marino <vim-dev-github@256bit.org> wrote:
> […](#)
> The uppercase letters can be used to express a menu choice without using the mouse. E.g. mt does "Modify, Select All" ...contacting the maintainer could have helped. Antonio … <#m_1885094882183546752_> On Sun, Dec 16, 2018 at 6:22 PM Diego Marino ***@***.***> wrote: Fixed typos. It appears you have made all the shorcut keys lowercase. They were uppercase for a reason. … <#m_-7634097560847384827_> -- If they don't keep on exercising their lips, he thought, their brains start working. -- Douglas Adams, "The Hitchhiker's Guide to the Galaxy" /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net \ /// sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \ \ an exciting new programming language -- http://www.Zimbu.org /// \ help me help AIDS victims -- http://ICCF-Holland.org /// I'm sorry, which is? I didn't find any issue using them like this. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <#3693 (comment) <[#3693 (comment)](https://github.com/vim/vim/pull/3693#issuecomment-447660336)>> -- -- You received this message from the "vim_dev" maillist. Do not top-post! Type your reply below the text you are replying to. For more information, visit http://www.vim.org/maillist.php --- You received this message because you are subscribed to the Google Groups "vim_dev" group. To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.*** For more options, visit https://groups.google.com/d/optout. -- /||\ | Antonio Colombo / || \ | ***@***.*** / () \ | ***@***.*** (___||___) | ***@***.*** I know, but they work the same without them being uppercase. — You are receiving this because you commented. Reply to this email directly, view it on GitHub <[#3693 (comment)](https://github.com/vim/vim/pull/3693#issuecomment-447669340)> -- -- You received this message from the "vim_dev" maillist. Do not top-post! Type your reply below the text you are replying to. For more information, visit http://www.vim.org/maillist.php --- You received this message because you are subscribed to the Google Groups "vim_dev" group. To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.*** For more options, visit https://groups.google.com/d/optout.
> -- /||\ | Antonio Colombo / || \ | azc100@gmail.com / () \ | antonio@geekcorp.com (___||___) | azc10@yahoo.com

But they are still underlined.

**Comment by brammool** [comment]
> But they are still underlined.

The convention is to have the shortcut keys in upper case.
How they are displayed is different per system.

-- 
How To Keep A Healthy Level Of Insanity:
2. Page yourself over the intercom. Don't disguise your voice.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by djemar** [comment]
> The convention is to have the shortcut keys in upper case. How they are displayed is different per system.

Fair enough. Then why not making the first letter of a word the shortcut? Even if there's another with the same letter, I'd prefer to cycle through them than to have uppercase letters in the middle of words.

**Comment by vim-ml** [comment]
I prefer something univocal... Actually there are corrections to do to make
them so.

**Comment by djemar** [comment]
> 
> I prefer something univocal... Actually there are corrections to do to make them so.
> […](#)
> On Mon, Dec 17, 2018 at 11:38 AM Diego Marino ***@***.***> wrote: The convention is to have the shortcut keys in upper case. How they are displayed is different per system. Fair enough. Then why not making the first letter of a word the shortcut? Even if there's another with the same letter, I'd prefer to cycle through them than to have uppercase letters in the middle of words.

I still think it is a not so great UI/UX, I've never seen any other piece of software doing like so.

**Comment by brammool** [comment]
Closing, since there was no progress and suggested fixes were not acted upon.

**Pull request closed without merging**
