### PR TITLE
Invoke autocommands on entering and leaving the cmdline-window

### PR DESCRIPTION
**Pull request by itchyny**
Problem: There's no event to do something after the cmdline-window is closed (execute `:q` or press `<C-c>` in cmdline-window). There's CmdwinLeave event but it is triggered before cmdline-window is closed so it's hard to do something with the latest active window.
Solution: Add new event `CmdwinLeavePost`, which is triggered after cmdline-window is closed.

What do you think?

### CODE REVIEW

**Comment by brammool** [comment]
> Problem: There's no event to do something after the cmdline-window is
> closed (execute `:q` or press `<C-c>` in cmdline-window). There's
> CmdwinLeave event but it is triggered before cmdline-window is closed
> so it's hard to do something with the latest active window.
> Solution: Add new event `CmdwinLeavePost`, which is triggered after
> cmdline-window is closed.
> 
> What do you think?

There is no WinLeavePost either.  You can use a WinEnter autocommand
that uses something that was set by CmdwinLeave or WinLeave.

	au * CmdwinLeave let g:left_command_win = 1
	au * WinEnter call WinEnter()
	func WinEnter()
	  if g:left_command_win
	    let g:left_command_win = 0
	    " work work work
	  endif
	endfunc

Any disadvantage?

-- 
hundred-and-one symptoms of being an internet addict:
6. You refuse to go to a vacation spot with no electricity and no phone lines.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by itchyny** [comment]
Thanks Bram for quick reply. The problem is that with your code (assuming the small fix to swap the event name and *) g:left_command_win remains 1 after closing the cmdline-window with :q. WinEnter event is not fired on closing the cmdline-window.

**Comment by itchyny** [comment]
Is there any chance to change the WinEnter event been fired on closing the cmdline-window?
Removing `block_autocmds` and `unblock_autocmds` is easy, but that would be a breaking change.

**Comment by brammool** [comment]
> Is there any chance to change the WinEnter event been fired on closing the
> cmdline-window?
> Removing `block_autocmds` and `unblock_autocmds` is easy, but that would be a
> breaking change.

I'm not really against it.  WinEnter happens very often and I don't expect
autocommands to do anything drastic.  Perhaps they update the status line or
some colors.  Which would actually be appropriate when leaving the command line
window.

-- 
How To Keep A Healthy Level Of Insanity:
6. In the memo field of all your checks, write "for sexual favors".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by itchyny** [comment]
Bram, is there any chance to get this pull request merged?

**Comment by brammool** [comment]
> Bram, is there any chance to get this pull request merged?

I need to have another look at it. Moved it up in the todo list.

-- 
Microsoft says that MS-Windows is much better for you than Linux.
That's like the Pope saying that catholicism is much better for
you than protestantism.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
