### PR TITLE
Termdebug: Chatty Breakpoint handling

### PR DESCRIPTION
**Pull request by GitMensch**
until now the user did not had any direct feedback and commonly the cmd just kept `:Break` or `:Clear`, now that is replaced by an appropriate message

### CODE REVIEW

**Comment by brammool** [comment]
I'll include it, thanks.

**Comment by GitMensch** [comment]
I wasn't sure about if this is appropriate or not. Nice to know that it is.
Note: #9140 is the technical more important point.

**Comment by brammool** [comment]
If someone doesn't like the messages we could always remove it again.

**Comment by GitMensch** [comment]
@brammool wrote:

> If someone doesn't like the messages we could always remove it again.

I still like those but found an issue: The chatty handling now also triggers when a breakpoint is enabled or disabled. Will do a follow-up PR.

**Pull request closed without merging**
