### PR TITLE
filetype: add support for Zephyr Devicetree overlay

### PR DESCRIPTION
**Pull request by xudongzheng**
Reference: https://docs.zephyrproject.org/latest/build/dts/howtos.html

### CODE REVIEW

**Comment by xudongzheng** [comment]
I've added a minimalist example for both ZMK and Zephyr. Both use pretty standard DeviceTree syntax.

**Comment by zeertzjq** [comment]
The test you need to modify is here:
https://github.com/vim/vim/blob/9f32069b8c4f74aa6af47e2f0ec07f2745feac57/src/testdir/test_filetype.vim#L242

**Comment by xudongzheng** [comment]
I've modified `src/testdir/test_filetype.vim` to include `.overlay`.

I've kept the `runtime/syntax/testdir` commits but let me know if they should be removed.

**Comment by chrisbra** [comment]
thanks

**Pull request closed without merging**
