### PR TITLE
Correct the command 10.1 in usr_10.txt help file

### PR DESCRIPTION
**Pull request by tin-z**

### CODE REVIEW

**Comment by k-takata** [comment]
The change is not needed, because the "^" after "qa" does move back to the beginning of the line.

**Comment by tin-z** [comment]
No, it's not, because if i go to the end of the line, then to the next line, then stop recording the macro, and last repeat the change by typing "@a" three times, i will have the following output:

	#include "stdio.h"
	fcntl.#include "h"
	unistd.#include "h"
	stdlib.#include "h"

instead of :

	#include "stdio.h"
	#include "fcntl.h"
	#include "unistd.h"
	#include "stdlib.h"

But doesn't matter, i remove tomorrow the pull request if is ok

**Comment by k-takata** [comment]
Does it occur with `vim --clean`?

**Comment by tin-z** [comment]
Yes

**Comment by k-takata** [comment]
What is the exact key sequence? If you type exactly the same as the instruction, you should get the correct result.
(When I skipped to type "^" after "qa", I get the same result as you.)

**Pull request closed without merging**
