### PR TITLE
support :terminal on Windows

### PR DESCRIPTION
**Pull request by mattn**
* use libvterm on Windows
* use winpty to be possible to handle escape sequence
* dynamic loading of winpty.dll

terminal

### CODE REVIEW

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> * use libvterm on Windows
> * use winpty to be possible to handle escape sequence
> * dynamic loading of winpty.dll
> 
> terminal

Thanks for working on this!

Can you please add something to the INSTALL text file about how to get
winpty and make Vim build with it?

Would be nice to reduce code duplication, e.g. setting the job options.

-- 
% cat /usr/include/sys/errno.h
#define	EPERM		1		/* Operation not permitted */
#define	ENOENT		2		/* No such file or directory */
#define	ESRCH		3		/* No such process */
[...]
#define EMACS		666		/* Too many macros */
%

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
done. please check.

**Comment by mattn** [comment]
@brammool I could enable colors. Currently, disabled on code. How about this?

42169b9e87f5c673

**Comment by mattn** [comment]
Remaining issue is delay of moving cursor. Do you have any idea? This delay happen on GUI version.

**Comment by mattn** [comment]
Ah, sorry, maybe few last commit is not merged.

**Comment by mattn** [comment]
@brammool Could you merge following patch? Some multi-byte characters are not displayed correctly.
```diff
diff --git a/src/terminal.c b/src/terminal.c
index df40866ba..bc632e7cb 100644
--- a/src/terminal.c
+++ b/src/terminal.c
@@ -628,9 +628,15 @@ term_update_window(win_T *wp)
 		{
 #if defined(FEAT_MBYTE)
 		    if (enc_utf8 && c >= 0x80)
+		    {
 			ScreenLinesUC[off] = c;
+			ScreenLines[off] = ' ';
+		    }
 		    else
+		    {
 			ScreenLines[off] = c;
+			ScreenLinesUC[off] = NUL;
+		    }
 #else
 		    ScreenLines[off] = c;
 #endif
@@ -642,7 +648,7 @@ term_update_window(win_T *wp)
 		++off;
 		if (cell.width == 2)
 		{
-		    ScreenLines[off] = ' ';
+		    ScreenLines[off] = NUL;
 		    ScreenLinesUC[off] = NUL;
 		    ++pos.col;
 		    ++off;
```

**Comment by mattn** [comment]
closed by https://github.com/vim/vim/commit/8f84c3a8666cea04484ec93fa05386bf33f93f5a

**Pull request closed without merging**
