### PR TITLE
Fix: Check if "inet_ntop()" is available

### PR DESCRIPTION
**Pull request by ichizok**
I had overlooked "inet_ntop()" check: Windows supports it since Vista and later.
https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inetntopw

### CODE REVIEW

**Comment by ichizok** [comment]
Ref: https://github.com/vim/vim/pull/5944#issuecomment-615554129

**Comment by brammool** [comment]
> I had overlooked "inet_ntop()" check: Windows supports it since Vista and later.
> https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inetntopw

Should we make the WINVER default 0x0600 now?  I suppose that works for
most people.

If I run a Vim built with 0x0600 on Windows XP, what happens?


-- 
Are leaders born or made?  And if they're made, can we return them under
warranty?
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> If I run a Vim built with 0x0600 on Windows XP, what happens?

If WINVER is set to 0x0600, we cannot detect at compile time if we use new APIs that are not available in Windows XP.
Then the binary won't work on XP.

**Comment by brammool** [comment]
Ken Takata wrote:

> > If I run a Vim built with 0x0600 on Windows XP, what happens?
> 
> If WINVER is set to 0x0600, we cannot detect at compile time if we use
> new APIs that are not available in Windows XP.
> Then the binary won't work on XP.

Right, so it will give an error and bail out.  We still support Windows
XP, thus I like to keep the default set for that.

Then I suppose this patch is the right way to do this.

-- 
The acknowledged parents of reengineering are Michael Hammer and James Champy.
When I say they're the "parents" I don't mean they had sex - and I apologize
for making you think about it.  I mean they wrote the best-selling business
book _Reengineering the Corporation_, which was published in 1993.
   Businesses flocked to reengineering like frat boys to a drunken
cheerleader.  (This analogy wasn't necessary, but I'm trying to get my mind
off that Hammer and Champy thing.)
				(Scott Adams - The Dilbert principle)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
