### PR TITLE
[WIP] Give user a possibility to suppress "reading from stdin" message

### PR DESCRIPTION
**Pull request by msva**
How about finally (after all that years, tons of emails in the mailing lists and messages on the IRC) give users possibility to suppress that noisy message, if they know what and why they are doing (i.e. set env variable)?

### CODE REVIEW

**Comment by chrisbra** [comment]
See #1552. 
Also your change need some documentation. However I am not sure, this is the best way to do it.

**Comment by ZyX-I** [comment]
I more like the idea of the command-line option, not the environment variable. This will also answer where to change documentation.

**Comment by msva** [comment]
Okay, I'll try to rework it to obey `-V0`, if nobody has objections...

**Comment by chrisbra** [comment]
You might also want to look at the appveyor failure, just to make sure it will build on Windows. Thanks.

**Comment by dmitrivereshchagin** [comment]
May be add new flag to `'shortmess'`?

**Comment by msva** [comment]
@dmitrivereshchagin, `shortmess` is empty (at least, many `SHM_*`'s I checked is 0) in mode, mentioned in #1552, so making this through shortmess will only suppress it for cases like `vimpager`, but not for that case.

**Comment by msva** [comment]
Also, making it to obey `-V0` is not an option too, since, it seems, it is default anyway (so, it means, that message will just disappear, which is the case @brammool wants to avoid)...

Let's brainstorm it a bit more...

**Comment by brammool** [comment]
Dmitri Vereshchagin wrote:

> May be add new flag to `'shortmess'`?

We have --not-a-term to surpress the "not a tty" warning.
Using a command line argument for surpressing the other message is
probably what a user would look for.  --silent-stdin-read perhaps?
Or just --read-stdin, which would do the same as "-" but not give the
message.

-- 
hundred-and-one symptoms of being an internet addict:
137. You decide to stay in college for an additional year or two,
     just so you can have the free Internet access.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by msva** [comment]
Yeah, I just thought about something like this, but was unable to invent a proper option name :)
I like the idea of `--read-stdin`.

**Comment by msva** [comment]
1) I'm stuck with **proper** way to pass something from `main` to `fileio` without 

2) @brammool also, people asking make vim to print this warning on stderr instead of stdin. So, wouldn't you mind about changing `mch_msg` to `mch_errmsg` in `src/fileio.c`?

3) also, it is 5a.m. here, so, I'll continue work on this tomorrow.

**Comment by msva** [comment]
1) I'm stuck with **proper** way to pass something from `main` to `fileio` without inventing new entities...

2) @brammool also, people asking make vim to print this warning on stderr instead of stdin. So, wouldn't you mind about changing `mch_msg` to `mch_errmsg` in `src/fileio.c`?

3) also, it is 5a.m. here, so, I'll continue work on this tomorrow.

**Comment by msva** [comment]
I almost done the `--read-stdin`, but I stuck with a bit unpredictable issue: `vim` still prints empty line, even if that message was suppressed...
And it is way too much `printf`'s of `"\n"` across the code, to find it. Can anybody help me figure it out?

**Comment by msva** [comment]
Uhm... And it is also `get_option_value` unvavailable in 'tiny' vim... So, then I either should look for another way to implement that (without utilizing options, which looked like good idea, since it was also be possible to easily check if that option was used in plugins), or leave 'reading from stdin' warning in tiny version...

**Comment by msva** [comment]
So, I did it in second way (keeping warning for `tiny` and `small` builds).
And I'll also be glad to hear comments about another ways to fix that.

Also, I still can't find why (and how) vim prints that empty line... And it is definitely not just `"\n"` somewhere (I tried to replace all orphaned `"\n"` conditions across the code with something custom, but vim anyway prints this empty line)...

**Comment by brammool** [comment]
> 1) I'm stuck with **proper** way to pass something from `main` to `fileio` without 
> 
> 2) @brammool also, people asking make vim to print this warning on stderr instead of stdin. So, wouldn't you mind about changing `mch_msg` to `mch_errmsg` in `src/fileio.c`?
> 
> 3) also, it is 5a.m. here, so, I'll continue work on this tomorrow.

I would suggest:

- Add a READ_SILENT flag to the readfile() flags.
- In read_stdin() pass this flag to open_buffer(), if desired.
- in the mparm_T struct add a flag edit_silent.
- Set edit_silent for the --read-stdin argument
- pass edit_silent to read_stdin()

Add some comments here and there about what the flags mean.

-- 
hundred-and-one symptoms of being an internet addict:
155. You forget to eat because you're too busy surfing the net.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by svnpenn** [comment]
https://github.com/neovim/neovim/pull/6298

**Comment by kenorb** [comment]
See: 234d162 and #1552.

**Pull request closed without merging**
