### PR TITLE
Append the fold marker to the existing comment when possible.

### PR DESCRIPTION
**Pull request by LemonBoy**
We just need to recycle some code that's used in do_join that checks
whether a given line ends with an unclosed comment.

Ref #1544

### CODE REVIEW

**Comment by brammool** [comment]
Lemonboy wrote:

> We just need to recycle some code that's used in do_join that checks
> whether a given line ends with an unclosed comment.
> 
> Ref #1544

Thanks.  Why did you move skip_comment() to another file? Now it's hard
to see if it changed.

Can you please write a test for this change?  Would go in
src/testdir/test_fold.vim


-- 
From "know your smileys":
 C=}>;*{)) Drunk, devilish chef with a toupee in an updraft,
	   a mustache, and a double chin

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by LemonBoy** [comment]
> Thanks.  Why did you move skip_comment() to another file? Now it's hard
to see if it changed.

Because it was defined as a static method in `ops.c` because it was only used by that file, since we now need it from within `fold.c` I've moved it into `misc1.c`. 

> Can you please write a test for this change? Would go in src/testdir/test_fold.vim

Done.

**Comment by brammool** [comment]
LemonBoy wrote:

> > Thanks.  Why did you move skip_comment() to another file? Now it's hard
> > to see if it changed.
> 
> Because it was defined as a static method in `ops.c` because it was
> only used by that file, since we now need it from within `fold.c` I've
> moved it into `misc1.c`. 

Well, can just make it non-static without moving.  It's not like it fits
better in misc1.c.
 
> > Can you please write a test for this change? Would go in
> > src/testdir/test_fold.vim
> 
> Done.

Thanks!

-- 
A meeting is an event at which the minutes are kept and the hours are lost.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teto** [comment]
thanks for it lemonboy !

2017-03-12 20:37 GMT+01:00 Bram Moolenaar <notifications@github.com>:

**Pull request closed without merging**
