### PR TITLE
Remove BeOS code

### PR DESCRIPTION
**Pull request by bitigchi**
Since Haiku support is available, it makes sense to get rid of old BeOS
code. Documentation will be handled later, in order to keep necessary
information.

### CODE REVIEW

**Comment by brammool** [comment]
I suppose this code has not been maintained for a while, might not even build.
If someone thinks it would be good to keep anyway, please speak up!

**Comment by Begasus** [comment]
Before this is done we should probably see if anyone still running BeOS gets a chance to check on this.
As a side note, would it be advisable to use python 3.7 over python 2.7 at this stage?

**Comment by brammool** [comment]
Well, I haven't heard anything for more than a month.  I also have no idea if the current code even builds.
Python 2 has been deprecated, maintenance is stopped, thus Python 3 should be used if possible.

**Comment by Begasus** [comment]
We've checked the build with python 3.7 that seems to be working OK: https://ibb.co/7pmx65Y

**Comment by Begasus** [comment]
FWIW, @bitigchi is looking into bumping our vim version at: https://github.com/haikuports/haikuports/pull/4900
You could check progress there too :)

**Pull request closed without merging**
