### PR TITLE
enable travis-ci.org automated testing

### PR DESCRIPTION
**Pull request by dagar**
Login to https://travis-ci.org/profile to enable

### CODE REVIEW

**Comment by dagar** [comment]
Build + testing takes about 2 minutes and looks like this. https://travis-ci.org/dagar/vim/jobs/55827735

**Comment by mattn** [comment]
This repository is work in progress for migrating.

See https://groups.google.com/forum/#!topic/vim_dev/Io5A_Zir--k
> NOTE: Before the actual migration the current repository on github will 
be wiped!

**Comment by mattn** [comment]
And this is the thing bram will decide, but we vim-dev is developing with patch file in ML. So we will not accept pull-request.

**Comment by zmughal** [comment]
There is also a CI running at <https://github.com/vim-jp/vim-ci>.

**Pull request closed without merging**
