### PR TITLE
Sync ocaml runtime scripts from ocaml/vim-ocaml

### PR DESCRIPTION
**Pull request by jiangyinzuo**
Synced from https://github.com/ocaml/vim-ocaml

### CODE REVIEW

**Comment by jiangyinzuo** [comment]
@rgrinberg @Maelan @mmottl Could you please review the PR?

**Comment by rgrinberg** [comment]
Was there anything modified in these files in this sync? If not, then there's nothing to review and this should be good to go.

**Comment by jiangyinzuo** [comment]
> Was there anything modified in these files in this sync? If not, then there's nothing to review and this should be good to go.

I have not modified anything, just copied the corresponding files from [ocaml/vim-ocaml](https://github.com/ocaml/vim-ocaml)

**Comment by chrisbra** [comment]
alright, thanks. Let me include it then

**Pull request closed without merging**
