### PR TITLE
Add Javascript syntax support for new regexp flags (u unicode,y sticky,s dotAll)

### PR DESCRIPTION
**Pull request by LongJohnCoder**
Javscript regular expressions now have support for new flags (u unicode,y sticky,s dotAll)

### CODE REVIEW

**Comment by chrisbra** [comment]
Unfortunately, there is no maintained javascript syntax file. Would you be willing to become new maintainer?

**Comment by LongJohnCoder** [comment]
Unfortunately taking on maintenance of the JavaScript syntax file isn't something I have time for at the moment. :-(

**Comment by chrisbra** [comment]
that's a pity. We have a couple of open issues for the javascript syntax file and nobody willing to step up. Don't expect a solution to this soon

**Comment by brammool** [comment]
This is simple enough to include

**Pull request closed without merging**
