### PR TITLE
Explicitly turn off VTP by variable

### PR DESCRIPTION
**Pull request by ghost**
Some older compatible terminal apps will complete the procedure for turning on VTP, even if it is not supported.
```set vtp=0``` turns off VTP. To turn it on again, ```set vtp=1```.
(From vim_use discussion)

### CODE REVIEW

**Comment by brammool** [comment]
> Some older compatible terminal apps will complete the procedure for turning on VTP, even if it is not supported.
> ```set vtp=0``` turns off VTP. To turn it on again, ```set vtp=1```.
> (From vim_use discussion)

For a user who doesn't know what 'vtp' means the name is obscure.
Is there a longer name we can use?

The documentation needs a few improvements.  E.g., mention that the
option is only available with the +vtp option.

-- 
hundred-and-one symptoms of being an internet addict:
252. You vote for foreign officials.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
If the value of this option is only 0 or 1, how about use boolean style like `forcevtp` and `noforcevtp`?

Or how about `disablevtp`/`nodisablevtp`?
I don't think this option should reflect the current status whether VTP is used or not, because we can use `has('vcon')`. 
I suggest the following specification:

```
						*'disablevtp'*
'disablevtp'		boolean (default off)
			global
			{not available when compiled without the |+vtp|
			feature}
	When off, VTP (Virtual Terminal Processing) is automatically used when
	Vim detects that it is available. (It is available on win32 console on
	Windows 10 version 1703 or later.)
	When on, stop using VTP even Vim detects that it is available.  If
	you are using a 3rd party terminal application which doesn't support
	VTP, turn this option on.
```

(I don't remember well whether VTP is always used on Win10 1703 (or later) or used only when 'tgc' is set or t_Co=256 is set. If latter, the above help needs to be updated.)

**Comment by ghost** [comment]
Yes, don't have multiple statuses.
That way, I will use it almost the same.

I am always grateful for your help.
I can prepare from now.

**Comment by ghost** [comment]
VTP is turned on in all cases except '16 palette color'. If there is no VTP, only '16 palette color' can be used.

**Comment by k-takata** [comment]
Two messages are not forwarded here.
https://groups.google.com/d/msg/vim_dev/VoTS9bLD5Sw/rLK43E9mBgAJ
https://groups.google.com/d/msg/vim_dev/VoTS9bLD5Sw/r-zSQopmBgAJ

**Comment by ghost** [comment]
I thought it was a debate from the beginning, so I chose '&vtp'.
Well, double denial is not cool.

Can I use 'virtualterminal' / 'novirtualterminal' ?
Because 'windowsterminal' is also waiting. At this time, automatic detection is not possible.

**Comment by brammool** [comment]
Searching on the internet I find lots of results for VTP, but none related to our use: Virtual Terminal Processing.  Isn't this mostly called "Windows Terminal"?  Or is that something else?

The option could be something like "trywinterm" for "try using windows terminal".  When on you still only get windows terminal support of it was detected (otherwise it can't work, right?).
And "notrywinterm" if you don't want to try using windows terminal, even when it's detected.

Is that less confusing?

**Comment by ghost** [comment]
The word 'VTP' was first written that way during the pre-release stage.
The official document at a later date became 'Virtual Terminal Sequences'. 'VTS' ?
This is the sequence supported by ConPTY running on Windows10 'conhostV2'.

There is a Windows Terminal that is supporting the same VTS.
https://github.com/microsoft/terminal/releases
This and ConPTY have the same API, but have a different bug.
The interface and device attribute query (DA) are completely the same as ConPTY, but the behavior is completely different, so the user has to make their own selection.

I brought an implementation of 'trywinterm'. Is this what you mean?

**Comment by brammool** [comment]
I'm still not clear on terminology.  If I understand it correctly, we have three terminal-like environments:
- The good old Windows console, only supporting 16 colors
- The new Windows Terminal, still under development, supporting many colors
- The ConPTY implementation, which is what we use for the terminal window.
Is that correct?

**Comment by ghost** [comment]
https://github.com/microsoft/terminal/labels?page=2&sort=name-asc
Look at the label Product series. This is the classification method used by Microsoft.

The current situation should be:
Product-Cmd.exe (16 good old colors)
Product-Conhost (Windows 10 cmd.exe that I usually use)
Product-Conpty ('*PseudoConsole' API terminal)
Product-Terminal (Windows Store application)
That's four. There is no common term between them.

Supplement:
The winpty terminal is built into Vim, so it needs support, but I think it is complete.
Product-Powershell looks like Product-Conhost with a different shell. I used to have problems with coloring, but I think it was solved.
Product-WSL behaves like ConPTY. The inside seems to work with ConPTY.

The above is except 3rd-party Terminal.

**Comment by ghost** [comment]
Can I set a new environment variable VIMVTP?
In order for the command to specify VTP behavior, .vimrc must be able to detect the terminal type.
Also, detecting the type of terminal is not realistic.
The environment on the user's side, probably the environment variable set also changes for each terminal, I want to rely on it.

set "VIMVTP=vtp:enable"
and
set "VIMVTP=vtp:disable,scrollpatch=disable"
I want to write like.

**Comment by brammool** [comment]
> Can I set a new environment variable VIMVTP?
> In order for the command to specify VTP behavior, .vimrc must be able to detect the terminal type.
> Also, detecting the type of terminal is not realistic.
> The environment on the user's side, probably the environment variable set also changes for each terminal, I want to rely on it.
> 
> set "VIMVTP=vtp:enable"
> and
> set "VIMVTP=vtp:disable,scrollpatch=disable"
> I want to write like.

We generally avoid environment variables, except for some standard ones,
because they can easily be set and forgot.

Why can't we detect the type of terminal?  Isn't there an API for that?

If Vim can't detect the terminal, then how would you set that
environment variable to the right value in the right place?

-- 
Don't be humble ... you're not that great.
                      -- Golda Meir

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by ghost** [comment]
There are many terminals, new terminals are increasing, and the combinations are endless.

There is no common API.
Some terminals do not have individual APIs.
Microsoft does not recognize cmd.exe compatible terminals.
Setting the VTP flag will result in an error on older Windows, nothing will happen on compatible terminals (ie the flag will be set).
The meaning was defined for an undefined flag that should have no meaning.

With the advent of WindowsTerminal, "CSI DA (^[[0c)" is destroyed (returns the equivalent of ConPTY) and cannot be relied on.

Currently, cmd.exe compatible terminal is not detected at all.
The appropriate values ​​assume cmd.exe.
Earlier I used a lot of stamina to support an English-only terminal called "Take Command". I can't do that anymore. I think the origin of this PR was its terminal.

So far, I remember that changing environment variables requires special techniques. After all it seems to implement the command.

Forget VIMVTP.

**Comment by DHowett-MSFT** [comment]
> Microsoft does not recognize cmd.exe compatible terminals.

The windows console host hosts _all_ commandline applications on windows. cmd, wsl, vim, powershell, they all use the same VT code.

Vim should be using `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on all versions of windows after 10240.

**Comment by ghost** [comment]
Relying on the newly added flag breaks operation on all compatible terminals.
Reports of destruction are all downvote to me.
Hea!

**Comment by DHowett-MSFT** [comment]
> Relying on the newly added flag breaks operation on all compatible terminals.

When an application cannot use ENABLE_VIRTUAL_TERMINAL_PROCESSING, it can implement its own Compatibility mode. This is what Vim does already! :smile:

**Comment by ghost** [comment]
Compatible terminals simply ignore the added flag.
Therefore, the application needs to provide a new means for manually selecting the sequence to be transmitted. And this issue exists.
The difference between the position of saying "follow me" to all compatible terminals and the position of not being able to say it.

**Comment by DHowett-MSFT** [comment]
This does not need to be an option.

## What we have today

1. On linux, macos, unix, bsd, Vim uses VT sequences
2. On Windows, Vim uses "internal" VT and translates to Win32 API

## Proposal

Can we do this?

1. On linux, macos, unix, bsd, Vim uses VT sequences
2. On Windows, Vim tries `ENABLE_VIRTUAL_TERMINAL_PROCESSING`
   1. _If it returns TRUE_, Vim uses VT sequences
   2. If it returns false, Vim uses "internal" VT and translates to Win32 API

This would make Vim work very well on all versions of Windows 10 _and_ in new terminals that support VT (like ConEmu)

**Comment by ghost** [comment]
The problem is how to listen to Vim's petition from a VT unsupported terminal (paid product!) That returns "TRUE" even after trying the flag. Again, I have no authority.
In other words, I have no right to answer. Just follow.

**Comment by brammool** [comment]
Dustin L. Howett wrote:

> This does not need to be an option.
> 
> ## What we have today
> 
> 1. On linux, macos, unix, bsd, Vim uses VT sequences
> 2. On Windows, Vim uses "internal" VT and translates to Win32 API
> 
> ## Proposal
> 
> Can we do this?
> 
> 1. On linux, macos, unix, bsd, Vim uses VT sequences
> 2. On Windows, Vim tries `ENABLE_VIRTUAL_TERMINAL_PROCESSING`
>    1. _If it returns TRUE_, Vim uses VT sequences
>    2. If it returns false, Vim uses "internal" VT and translates to Win32 API
> 
> This would make Vim work very well on all versions of Windows 10 _and_
> in new terminals that support VT (like ConEmu)

It generally sounds like a good idea to avoid the Escape-sequence to
Win32 API translation.  This then depends on how well the Escape
sequences are implemented.  What terminal and version exactly is being
emulated?  I assume it won't be covering 100%, is there a specification
of which ones are 100% right?  Vim can easily work around missing
entries, but entries that don't work exactly as expected will cause
problems.

This matters especially for color support, mouse dragging and similar
things that are not part of the basic terminals.

-- 
A mathematician is a device for turning coffee into theorems.
					Paul Erdos
A computer programmer is a device for turning coffee into bugs.
					Bram Moolenaar

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Now looking at this patch again, I see that it makes a difference whether the option is never set, set to true or set to false.  Problem is that it's then not possible to go back to the initial situation.  It would be better to have an option with three values:  Detect the terminal, force-disable vtp, force-enable vtp.

Then we can call the option 'winterm' with the values empty (default), "off" and "on".

Unfortunately I don't feel confortable making these changes without a setup to try it out.  And Nobuhiro appears to be inactive.  Anybody else wants to take this over?

**Pull request closed without merging**
