### PR TITLE
runtime(requirements): add support

### PR DESCRIPTION
**Pull request by Freed-Wu**
runtime/filetype.vim have requirements, however its syntax is missing.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Related: https://github.com/raimon49/requirements.txt.vim/issues/19

**Comment by zeertzjq** [comment]
The following test change is needed:
```diff
diff --git a/src/testdir/test_compiler.vim b/src/testdir/test_compiler.vim
index 4b710df07..3bcfb87a6 100644
--- a/src/testdir/test_compiler.vim
+++ b/src/testdir/test_compiler.vim
@@ -71,10 +71,10 @@ func Test_compiler_completion()
   call assert_match('^"compiler ' .. clist .. '$', @:)
 
   call feedkeys(":compiler p\<C-A>\<C-B>\"\<CR>", 'tx')
-  call assert_match('"compiler pbx perl\( p[a-z]\+\)\+ pylint pyunit', @:)
+  call assert_match('"compiler pbx perl\( p[a-z_]\+\)\+ pylint pyunit', @:)
 
   call feedkeys(":compiler! p\<C-A>\<C-B>\"\<CR>", 'tx')
-  call assert_match('"compiler! pbx perl\( p[a-z]\+\)\+ pylint pyunit', @:)
+  call assert_match('"compiler! pbx perl\( p[a-z_]\+\)\+ pylint pyunit', @:)
 endfunc
 
 func Test_compiler_error()
```

**Comment by Freed-Wu** [comment]
> The following test change is needed:

It looks like another PR?

**Comment by Freed-Wu** [comment]
@raimon49 Any problem about including it to vim runtime (which respect MIT)?

**Comment by Freed-Wu** [comment]
Now test should pass.

**Pull request closed without merging**
