### PR TITLE
":verbose pwd" to print the scope of current directory

### PR DESCRIPTION
**Pull request by tyru**
Hi @brammool .

Sometimes I want to know the scope of current directory, to know which the path comes from.

How do you think?

### CODE REVIEW

**Comment by tyru** [comment]
Oops, I forgot to write about example.
This PR introduces `:verbose pwd` output like below (current directory = `/path/to/dir`).

### Tab-local (:tcd)

```
:verbose pwd
[tabpage] /path/to/dir
```

### Window-local (:lcd)

```
:verbose pwd
[window] /path/to/dir
```

### Global (:cd)

```
:verbose pwd
[global] /path/to/dir
```

**Comment by brammool** [comment]
That can be useful.  Please add a test that after a sequence of cd/lcd/tcd commands the right message is printed.

**Comment by tyru** [comment]
@brammool Okay. Added tests and help.

**Comment by tyru** [comment]
Unrelated tests seems failed.
https://travis-ci.org/vim/vim/jobs/636706074?utm_medium=notification&utm_source=github_status

**Pull request closed without merging**
