### PR TITLE
__sun should be used instead of sun to detect Solaris/illumos to allo…

### PR DESCRIPTION
**Pull request by pyhalov**
…w build with -std=c99

### CODE REVIEW

**Comment by brammool** [comment]
Since when is "__sun" defined?  Perhaps we still need "sun" for older systems.
Old Sun systems tend to die out very slowly...

**Comment by dhduvall** [comment]
It's defined by the compiler, so it depends on how old a compiler you think people are using.  `__sun` is documented by the Studio compilers as far back as 4.2, which dates to 1996.  The next oldest copy I found is 2.0.1, dating from 1993, and that only documents `sun`.  GCC 3.4.3 (dated 2005) predefines it, too.  I don't know how much further back that one supports it.

**Comment by tgc** [comment]
gcc 2.95 also defines __sun.
```
$ uname -srp
SunOS 5.6 sparc
$ /usr/tgcware/gcc29/bin/gcc -E -dM - < /dev/null | grep sun
#define __sun 1 
#define __sun__ 1 
#define sun 1 
```
See also the 'Solaris' section here:
https://sourceforge.net/p/predef/wiki/OperatingSystems/

**Comment by brammool** [comment]
Tom Christensen wrote:

> gcc 2.95 also defines __sun.
> ```
> $ uname -srp
> SunOS 5.6 sparc
> $ /usr/tgcware/gcc29/bin/gcc -E -dM - < /dev/null | grep sun
> #define __sun 1 
> #define __sun__ 1 
> #define sun 1 
> ```
> See also the 'Solaris' section here:
> https://sourceforge.net/p/predef/wiki/OperatingSystems/

Perhaps we should do:

#if defined(sun) || defined(__sun)
# define SUN_SYSTEM
#endif

To catch them all?  And then use SUN_SYSTEM where needed.

-- 
hundred-and-one symptoms of being an internet addict:
80. At parties, you introduce your spouse as your "service provider."

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dhduvall** [comment]
Do you have any evidence of people using twenty-plus-year-old compilers to compile vim on Solaris (well, SunOS at that point, I guess)?  If not, I think just using __sun should be fine.  If so, then perhaps

    #if defined(sun) && !defined(__sun)
    # define __sun 1
    #endif

and then you get to use the modern macro.

**Pull request closed without merging**
