### PR TITLE
update for javascript indent file

### PR DESCRIPTION
**Pull request by bounceme**
Lots of small improvements to the regexes and code quality. Also in this update is a better algorithm for determining objects from block statements (even labeled block statements are recognized)

### CODE REVIEW

**Comment by brammool** [comment]
Bounceme wrote:

> Lots of small improvements to the regexes and code quality. Also in
> this update is a better algorithm for determining objects from block
> statements (even labeled block statements are recognized)

I'm confused about who is the maintainer of the file now.  The file
itself says:

```
" Maintainer: vim-javascript community
```

So I have no idea who's patches I should include.
Not having a full name makes it even more difficult.
I have no idea who made this pull request and what his/her relation with
"vim-javascript community" is.

## 

hundred-and-one symptoms of being an internet addict:
70. ISDN lines are added to your house on a hourly basis

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bounceme** [comment]
Hello Bram, sorry for the confusion. I'm the same person who originally sent the indent file 11 days or so ago,here is the contributors page for the project: https://github.com/pangloss/vim-javascript/graphs/contributors . The indent file is and always has been part of this repo: https://github.com/pangloss/vim-javascript , and though I'm really the only recent indentation contributor (the version sent to you is 90% written by me) the project operates from the github repo.this works well as the repo has a large amount of users who sporadically contribute ( though the maintainers audit p.r's )

**Comment by bounceme** [comment]
I guess if you want assurance that the updates aren't coming from random people you could just accept my p.r's only. github p.r's are convenient because you can verify who sent it and it also shows diffs and patch files on the vim-def mailing list

**Comment by bounceme** [comment]
a tiny update here: https://github.com/vim/vim/pull/999/commits/19534350539a01fec213de66ce4ddbc8066b2cc0

**Comment by brammool** [comment]
> Hello Bram, sorry for the confusion. I'm the same person who
> originally sent the indent file 11 days or so ago,here is the
> contributors page for the project:
> https://github.com/pangloss/vim-javascript/graphs/contributors . The
> indent file is and always has been part of this repo:
> https://github.com/pangloss/vim-javascript , and though I'm really the
> only recent indentation contributor (the version sent to you is 90%
> written by me) the project operates from the github repo.this works
> well as the repo has a large amount of users who sporadically
> contribute ( though the maintainers audit p.r's )

Can you please add your real name to your github account?
If I only look at the headr your messages look like spam to me.
No idea what to call you.  For most people I can at least find a name on
their github page.

If you are going to update the indent file and send me a new version
when it's OK, then please add yourself as the maintainer.  Otherwise we
keep having this problem of not knowing whether you are some random
person or someone actually involved in the maintenance.

## 

hundred-and-one symptoms of being an internet addict:
75. You start wondering whether you could actually upgrade your brain
    with a Pentium Pro microprocessor 80.  The upgrade works just fine.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bounceme** [comment]
I put myself as maintainer as instructed

**Comment by brammool** [comment]
Thanks, I'll include it now.  There are some drastic changes, so please watch out for comments.

**Pull request closed without merging**
