### PR TITLE
update ChordPro syntax

### PR DESCRIPTION
**Pull request by bbolli**
Add missing directives according to the documentation at
https://www.chordpro.org/chordpro/chordpro-directives/

### CODE REVIEW

**Comment by dkearns** [comment]
@niboan

**Comment by bbolli** [comment]
@dkearns , the original author doesn't seem to be active on GitHub. Their last contribution was in December 2020.

**Comment by dkearns** [comment]
Have you tried emailing Niels at the address in the header?  The general procedure is to push all changes through the maintainers if possible.

**Comment by bbolli** [comment]
Yes, months ago. Never got a reply, that's why I try here now.

**Comment by brammool** [comment]
> Yes, months ago. Never got a reply, that's why I try here now.

His email address looks permanent.  Let me try send him a message.

-- 
The MS-Windows registry is no more hostile than any other bunch of state
information... that is held in a binary format... a format that nobody
understands... and is replicated and cached in a complex and largely
undocumented way... and contains large amounts of duplicate and obfuscated
information...  (Ben Peterson)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by niboan** [comment]
I'm still here ;-)

I'm sorry I haven't responded, I've been quite busy on my day job lately.

First of all, I'm glad that ChordPro isn't dead, it's been quite useful for me through the time, although I haven't been using it much for some time.

I looked at the new syntax shortly when @bbolli e-mailed me, and concluded that the new additions to the syntax were quite extensive. I couldn't find a description of what was changed from the original syntax, so I put it on on my todo list for later.

It seems there is much more than this PR contains, like embedded Pango syntax, new environment directives and a lot more.
With Easter coming up, I have some free time, so I could look into including more features.

**Comment by niboan** [comment]
I've got an updated syntax file.
@dkearns, what's the procedure, should I just make a new PR?

**Comment by dkearns** [comment]
@niboan, yes you can make a PR or just email Bram the update.  A PR might be better in case @bbolli and others have comments.

Thanks.

**Comment by niboan** [comment]
Created PR #10222.
The update adds support for most new features, including new directives, meta-data, conditional directives, embedded abc notation syntax and more.

**Comment by bbolli** [comment]
Closing this PR as it's superseded by #10222. Thanks, @niboan !

**Pull request closed without merging**
