### PR TITLE
Add Scala into Vim runtime.

### PR DESCRIPTION
**Pull request by Petesta**
This PR references this [issue](https://github.com/vim/vim/issues/907).

### CODE REVIEW

**Comment by brammool** [comment]
Pete Cruz wrote:

> - Add Scala into Vim runtime.

It appears these files are maintained by Derek Wyatt.
I prefer if the author or maintainer submits the files
for inclusion.  That way I know this is intentional, and not picking up
random file that seem useful from the internet.

## 

Those who live by the sword get shot by those who don't.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
OK. Thanks Bram. I'll get to this as soon as possible.

**Comment by Petesta** [comment]
@derekwyatt Are these the files we'd like to integrate into Vim's runtime? Would it be possible for you to do this? Since it appears I'm not able to create the PR since I'm not the maintainer.

**Comment by chrisbra** [comment]
closing in favor of #995

**Pull request closed without merging**
