### PR TITLE
[WIP] if_pyth: add "id" to Window attributes

### PR DESCRIPTION
**Pull request by blueyed**
Should have a test probably.

I wasn't sure if it should go into test87/test88 still, or src/testdir/test_python{2,3}.vim.

Should also get added to the other interfaces then (Ruby etc).

### CODE REVIEW

**Comment by brammool** [comment]
Please add the test in test_python[23].vim.  The test87 and test88 are quite hard to maintain.

**Comment by blueyed** [comment]
Ok.  Any idea about the current failure with https://github.com/blueyed/vim/blob/if_py-winid/src/testdir/if_ver-2.vim ?
It works for me locally, and also does not appear to fail the build:
```
Python 3:
Error detected while processing /Users/travis/build/vim/vim/src/testdir/if_ver-2.vim:
line    7:
The command "if [[ "${BUILD}" = "yes" ]]; then
  "${SRCDIR}"/vim --version
  "${SRCDIR}"/vim --not-a-term -u NONE -S "${SRCDIR}"/testdir/if_ver-1.vim -c quit > /dev/null
  "${SRCDIR}"/vim --not-a-term -u NONE -S "${SRCDIR}"/testdir/if_ver-2.vim -c quit > /dev/null
  cat if_ver.txt
fi
" exited with 0.
```

The failure is due to test86 there, so I guess it can be used for testing then already, since it needs to be adjusted anyway:
```
# Check if the test.out file matches test.ok.
446c446
< window:__dir__,__members__,buffer,col,cursor,height,id,number,options,row,tabpage,valid,vars,width
---
> window:__dir__,__members__,buffer,col,cursor,height,number,options,row,tabpage,valid,vars,width
```

**Comment by blueyed** [comment]
btw: Neovim currently has `.handle` on its Python API already to refer to the ID.

Would you be OK with using "handle" instead of "id" here also for compatibility?

**Comment by blueyed** [comment]
> Error detected while processing /Users/travis/build/vim/vim/src/testdir/if_ver-2.vim:

That's due to py3 not being used in some builds.

**Comment by brammool** [comment]
Daniel Hahler wrote:

> btw: Neovim currently has `.handle` on its Python API already to refer
> to the ID.
> 
> Would you be OK with using "handle" instead of "id" here also for
> compatibility?

It's called Window ID everywhere, "handle" does not ring a bell in any
way.  Why did they pick that?

-- 
DINGO: Wicked wicked Zoot ... she is a bad person and she must pay the
       penalty.  And here in Castle Anthrax, we have but one punishment
       ... you must tie her down on a bed ... and spank her.  Come!
GIRLS: A spanking!  A spanking!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfredl** [comment]
Neovim doesn't use `.handle` for windows specifically, but for any object type. I guess `.id` makes more sense for an attribute only added to "window" type.

**Comment by brammool** [comment]
> Neovim doesn't use `.handle` for windows specifically, but for any
> object type. I guess `.id` makes more sense for an attribute only
> added to "window" type.

I don't think we are going to implement much of what Neovim is doing
here, thus I prefer "id".  If needed "handle" can be added as well, but
it probably doesn't help anyone in practice.

-- 
"Intelligence has much less practical application than you'd think."
		  -- Scott Adams, Dilbert.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by bfredl** [comment]
@brammool I think the only functional difference in Neovim is for tabpages. It seems tabpage numbers (`tabpagenr()` and so forth) aren't persistent, but refers only to the relative position of the tab, just like window numbers do. So IIUC there is currently no unique and persistent id for tabpages in vim (like window ids), but maybe this functionality has never been requested.

**Comment by chrisbra** [comment]
It seems this got stalled and no test added. So I close this.

**Pull request closed without merging**
