### PR TITLE
win: handle <s-bs> like <bs> in terminal

### LINKED ISSUE #10279: Pressing Shift+Backspace results in Îy character in Powershell
### Steps to reproduce

1. Install Vim on a windows machine using `choco install vim`
2. Enter following in vimrc:
```
set number
set belloff=all
syntax on
set backspace=indent,eol,start
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set ruler
```

3. Open vim in Powershell
4. Enter some text then press Shift+Backspace in insert mode

### Expected behaviour

That it would delete the previous character or at the very least do nothing.

### Version of Vim

8.2, compiled Jan 7 2022 23:03:22

### Environment

Windows 11 on a standard powershell terminal

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by chrisbra**
fixes #10279

most likely the newly added test fails. it seems to work interactively, not sure why it doesn't work in the test suite

### CODE REVIEW

**Comment by brammool** [comment]
any progress on making the tests pass?

**Comment by chrisbra** [comment]
Nope, I don't understand why it doesn't work when run as test but works when run interactively. I may try to convert it to a terminal test instead.

**Comment by brammool** [comment]
Tests are still failing...

**Comment by chrisbra** [comment]
yes I know. I give up with that test.

**Pull request closed without merging**
