### PR TITLE
filetype: LLVM IR files are not recognized

### PR DESCRIPTION
**Pull request by Freed-Wu**
Problem: LLVM IR files are not recognized
Solution: recognize LLVM IR files as llvm filetype

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks. How about a test? I had some troubles finding some original lifelines files, but if this is for the lifelines genealogy, then there are some examples here: https://github.com/lifelines/lifelines/blob/master/reports

**Comment by chrisbra** [comment]
Thanks. Please also change the Maintainer line here.

**Review by zeertzjq — COMMENTED** [review]
Why is the same autocommand repeated twice?

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
