### PR TITLE
Add dialog element

### PR DESCRIPTION
**Pull request by jorgesumle**
I made a mistake before, so this is a fix technically. It helps with https://github.com/vim/vim/issues/1705

### CODE REVIEW

**Comment by jorgesumle** [comment]
Also, I want to resign as the HTML maintainer, and propose @Konfekt, who has been [working on supporting HTML syntax folding](https://notabug.org/jorgesumle/vim-html-syntax/pulls/10), because right now I don't have time to review or code much.

**Comment by brammool** [comment]
I'll include the patch, thanks.  Did Enno confirm he wants to take over?

**Comment by jorgesumle** [comment]
> Did Enno confirm he wants to take over?

This is what Enno wrote 8 months ago:

> if you deem that I could better take of this syntax file, then I will do so. I would think about a text inviting web developers taking over maintenance, but offering mine instead.

**Comment by Konfekt** [comment]
Well, I know nothing about HTML, but I am happy to help out.

**Comment by Konfekt** [comment]
While we are at it, what about this explantion in `:help html-syntax`
```
HTML comments are rather special (see an HTML reference document for the
details), and the syntax coloring scheme will highlight all errors.
However, if you prefer to use the wrong style (starts with <!-- and
ends with -->) you can define >
	:let html_wrong_comments=1
```
It seems ancient, as wrong comments are all I know.

**Pull request closed without merging**
