### PR TITLE
Gh vim 4738 netrw gx

### LINKED ISSUE #4738: netrw's "gx" functionality doesn't open URLs anymore in macOS
**Describe the bug**
The latest Vim has updated to a newer version of netrw, which seems to have broken the `gx` functionality. In the past, positioning the cursor on an URL and press `gx` would open the URL in a web browser (using the `open` command). The updated netrw would instead try to curl it, which seems wrong.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `vim --clean` (or `gvim --clean`, etc.) in macOS.
2. Enter insert mode and type "https://www.vim.org"
3. Go to normal mode and type `gx`.
4. Observe that Vim doesn't open the URL in a web browser.

**Expected behavior**
Vim should open the URL in a web browser.

**Screenshots**
If applicable, copy/paste the text or add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Vim version [e.g. 8.1.1755]
 - OS: macOS 10.14 (haven't tested others yet)

**Additional context**
Bug was introduced in 85850f3a5ef9f5a9d22e908ef263de8faa265a95. Originally I got this bug filed against MacVim at https://github.com/macvim-dev/macvim/issues/925 so cross-referencing here.

This is a netrw bug so I'm not sure if this is the correct place to post it, but with the ownership question I'm not 100% sure who owns netrw now and where I should file a bug for it to be fixed and updated to Vim's bundled plugin.

### PR DESCRIPTION
**Pull request by mcepl**
Bundled new version of netrw breaks gx command.

Fixes vim/vim#4738

### CODE REVIEW

**Comment by blayz3r** [comment]
Is this ready? gx fails on windows too

**Comment by k-takata** [comment]
@cecamp Could you check this?

**Comment by mcepl** [comment]
This has been [merged to neovim](https://github.com/neovim/neovim/pull/10938) and it works just fine for me and AFAIK everybody else. Ask Bram to merge this.

**Comment by chrisbra** [comment]
included as of https://github.com/vim/vim/commit/589edb340454e7f1b19358f129287a636d53d0e1#diff-532bf738932796a9a60951fb92334bac

**Pull request closed without merging**
