### PR TITLE
fix(completion): completion next word when fuzzy enable

### LINKED ISSUE #15412: Adding keyword completion not working with fuzzy completion
### Steps to reproduce

Deactivate fuzzy completion if needed `:set completeopt-=fuzzy`.
In insert mode, type in `alpha bravo charlie`, then `<enter>`, and on the new line type `al<c-n><c-x><c-n>`.
The first `<c-n>` completes `al` into `alpha`, then the `<c-x><c-n>` enters the _adding keyword completion_ mode, and inserts `bravo` (the only match). Another `<c-x><c-n>` would insert `charlie`.

If you try to do this with `set completopt+=fuzzy`, `alpha` is inserted on `<c-n>` but the chained completion is not triggered on `<c-x><c-n>`, and `bravo` is not inserted.

### Expected behaviour

See the **Steps to reproduce**.
Thanks again for bringing fuzzy completion to Vim!

### Version of Vim

9.1.636

### Environment

Tested on Windows (but would suspect the issue is the same on other OSes)

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by glepnir**
Problem: when cursor after a word which already in buffer no completion is given or shown.

Solution: if word before cursor is matched return next word as completion result.

Fix #15412

### CODE REVIEW

**Comment by glepnir** [comment]
cc @egesip

**Comment by egesip** [comment]
Thanks for the fix. It works but I have to press `<c-x><c-n>`  _twice_ to "chain" the completions.

Using the same `alpha bravo charlie` example line, I type `alp`, press `<c-n>`, I get `alpha` inserted (the only match), then I press `<c-x><c-n>`, I immediately get `bravo` inserted when fuzzy is off, while I get a menu with `alpha` and `alpha bravo` and nothing inserted when fuzzy is on (this is the first difference in behavior). 

From there, I then press `<c-n>` to get `bravo` inserted, I then press `<c-x><c-n>` again, it doesn't insert anything and says "hit end of paragraph" (whereas it immediately inserts `charlie` when fuzzy if off), I have to press `<c-x><c-n>` again and now `charlie` is inserted (second difference in behavior).

**Comment by glepnir** [comment]
thanks for your feedback. i am really appreaciate . about first different i have update patch. about 2 i am not sure i understand. could you check it again. and if two no works  could you give a clear reproduce step 1. xx 2. xx thanks

**Comment by egesip** [comment]
Thanks! The first difference is fixed with the new patch!
The second difference is still there, let me try to highlight it:
* case fuzzy off:
    1. Input the line `alpha bravo charlie` as usual.
    2. On the next line, type `alp`, then press `<c-n>`, vim inserts `alpha` and the message line says `-- Keyword completion (^N^P) The only match`.  
    3. Now press `<c-x><c-n>`, vim **inserts** `bravo`, and the message line says `-- Adding keyword completion (^N^P) The only match`.
    4. Now press  `<c-x><c-n>` again, vim **inserts** `charlie` and the message line says  `-- Adding keyword completion (^N^P) The only match`.
* case fuzzy on:
    1.  Input the line `alpha bravo charlie` as usual.
    2. On the next line, type `alp`, then press `<c-n>`, vim inserts `alpha` and  the message line says `-- Keyword completion (^N^P) The only match`.  (up to here, this is the same behavior as the case fuzzy off).
    3. Now press `<c-x><c-n>`, vim **does not insert** `bravo` and the message line says `-- Adding keyword completion (^N^P) Hit end of paragraph`.
    5. Press `<c-x><c-n>` again, now vim **inserts** `bravo` and the message line says `-- Adding keyword completion (^N^P) The only match`
    6. Press `<c-x><c-n>` again, vim **does not insert** `charlie`, the message line says `-- Adding keyword completion (^N^P) Hit end of paragraph`.
    7. Press  `<c-x><c-n>` again, now vim **inserts** `charlie`, etc..

**Comment by glepnir** [comment]
I can't reproduce it works fine with me `alp` insert alpha and then <C-x><C-N> i got bravo where am i missing 

test_case

**Comment by egesip** [comment]
You're right! I had to bissect my vimrc to find the culprit: `set complete-=i`.
Very strange...
So in summary, to reproduce the issue, you need:
```
set completeopt+=fuzzy
set complete-=i
```

If put `i` back in (`set complete+=i`), then it works fine.

**Comment by glepnir** [comment]
emm i just use default complete value it does not include i

**Comment by egesip** [comment]
Weird, on my machine, the help says `'complete' 'cpt' string (default: ".,w,b,u,t,i")` (i.e. it _does_ include `i`...)
But anyway, if you cannot reproduce it, perhaps it is a Windows specific issue?
The fact that adding/removing the scanning of include files triggers the bug on Windows and not on Linux smells like a bad memory access, but I've got no real clue here.

**Comment by glepnir** [comment]
sry it's my mistake i mixed up the nvim and vim in my env. I have update patch for problem 2.

**Comment by egesip** [comment]
Your latest patch fixes the issue!
Thanks!

**Comment by glepnir** [comment]
aha good to know did you still get any problem on this patch . if not i will mark as ready for review.

**Comment by egesip** [comment]
Less coding than usual for me this week, but so far so good!
Thank you!

**Comment by glepnir** [comment]
no worry . I just solved the conflict but i want continue waiting for you test for a while . because i am not sure with other edge cases if have.

**Comment by glepnir** [comment]
@egesip  hello do you still get any problem? could i mark as ready ?

**Comment by egesip** [comment]
Hello @glepnir, sure, let's go!
Thank you.

**Comment by chrisbra** [comment]
So is this ready to be included?

**Comment by glepnir** [comment]
@egesip  confirmed it works fine so i think can be merge.

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
