### PR TITLE
resolv.vim: Add IPv6 syntax highlighting for nameserver

### PR DESCRIPTION
**Pull request by djlucas**

### CODE REVIEW

**Comment by chrisbra** [comment]
as mentioned on the vim_use list, have you contacted the maintainer?

**Comment by djlucas** [comment]
I have, just sent this PR as example.

**Comment by brammool** [comment]
No update, and I haven't heard from this maintainer for a while, let me include this improvement.
If you like, could you volunteer to become the maintainer?

**Comment by brammool** [comment]
This was included some time ago

**Pull request closed without merging**
