### PR TITLE
Improve readability of CI script

### PR DESCRIPTION
**Pull request by ichizok**
* Use anchors and aliases to handle env-set and matrix easily.

* Use literal style - insert linefeed to each command.

* (extra) Make "ci/" directory and move appveyor.bat to there, in order to classify resources properly.

### CODE REVIEW

**Comment by chrisbra** [comment]
I like how much cleaner and readable the travis script looks. Thanks!

**Comment by brammool** [comment]
Somehow Travis failed.  Unrelated?

**Comment by chrisbra** [comment]
The error from Travis is this:

> Executing Test_1_set_secure()issing on display ":99.0".
> ': free(): invalid next size (fast): 0x00000000024efa20 ***
> Vim: Caught deadly signal ABRT
> Vim: Finished.
> Aborted (core dumped)

don't know why this wouldn't show up in the current ci runs.

**Comment by dpelle** [comment]
```
Executing Test_1_set_secure()issing on display ":99.0".
': free(): invalid next size (fast): 0x00000000024efa20 ***
Vim: Caught deadly signal ABRT
Vim: Finished.
Aborted (core dumped)
```

It's a shame that CI does not show a stack trace when there is a crash.
Since it says "core dumped", CI could probably be changed so that it
runs gdb post-mortem with the "bt full" command to get the call stack.

**Pull request closed without merging**
