### PR TITLE
Do not convert CR into NL when `ICRNL` is set

### PR DESCRIPTION
**Pull request by ichizok**
For https://github.com/vim/vim/issues/1998

I think Vim should pass user input CR and NL to term-tty without conversion.

current circumstances;

1. `-icrnl` and `-inlcr`:

User input | Vim converts | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR| CR| CR
NL | NL | NL | NL

2. `+icrnl` and `-inlcr`:

User input | Vim converts | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR &rarr; NL | NL | NL
NL | NL | NL | NL

3. `-icrnl` and `+inlcr`:

User input | Vim converts | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR | CR | CR
NL | NL | NL &rarr; CR | CR

4. `+icrnl` and `+inlcr`:

User input | Vim converts | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR &rarr; NL | NL &rarr; CR | CR
NL | NL | NL &rarr; CR | CR

The cases of 2 and 4 cause input problem. That is, term-tty receives only CR or NL from user even if the status of `ICRNL` changed (e.g. by using interactive-tool) after terminal started, while in `terminal_loop`.

Fix:

2'. `+icrnl` and `-inlcr`:

User input | <del>Vim converts</del> | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR | CR &rarr; NL | NL
NL | NL | NL | NL

4'. `+icrnl` and `+inlcr`:

User input | <del>Vim converts</del> | term-tty converts | term-job receives
-----------|--------------|-------------------|------------------
CR | CR | CR &rarr; NL | NL
NL | NL | NL &rarr; CR | CR

### CODE REVIEW

**Comment by tonymec** [comment]
What are icrnl and inlcr? A helpgrep search for them finds no result.

Best regards,
Tony.

**Comment by ichizok** [comment]
Sorry for my lack of explanation. `icrnl` and `inlcr` are terminal input modes (`ICRNL` and `INLCR`), they are not the elements of Vim .

**Comment by chrisbra** [comment]
those can be set by e.g. `stty`. Does this PR change the default behaviour?

**Comment by ichizok** [comment]
What does "the default behavior" mean?
I propose "Vim send user input CR/NL as it is into term-tty".

**Comment by chrisbra** [comment]
Isn't 4 (`+icrnl +inlcr`) the default (e.g. when the terminal runs with `stty sane`) does? That would mean it would change the cr and nl semantics for the terminal, not?

**Comment by brammool** [comment]
There is insufficient information here.
For a start, you mention "user input CR", how is that entered?
Does the Enter key product a CR or a NL?
Or is this typing CTRL-M?
Please give a specific example of what fails that the patch is fixing.

**Comment by ichizok** [comment]
> Isn't 4 (+icrnl +inlcr) the default (e.g. when the terminal runs with stty sane) does? That would mean it would change the cr and nl semantics for the terminal, not?

For example, zsh sets both `+icrnl` and `+inlcr` when waiting for key-in.

**Comment by ichizok** [comment]
> For a start, you mention "user input CR", how is that entered?
> Does the Enter key product a CR or a NL?
> Or is this typing CTRL-M?
> Please give a specific example of what fails that the patch is fixing.

Regardless of the way CR is generated. (pressing enter/return key, typing Ctrl-M, or)
The point is the situation that Vim receives CR from input-source (e.g. `read(0, ...)`).

Example:
As above comment, zsh sets `+icrnl` and `+inlcr` so under current Vim processing (also after v8.0.1261) zsh cannot receives NL from tty (associated with `:terminal`).
And zsh translates received CR to NL and NL to CR in internal.
That is, when user inputs CR, zsh on `:terminal` raises a key-event associated with NL against user expect.

As another (trivial) example, on `:terminal` with `+icrnl`, typing `Ctrl-V Ctrl-M` shows '^J', not '^M'.

**Comment by ichizok** [comment]
zsh on `:terminal` (`+icrnl` and `+inlcr`): 

input to Vim | Vim converts | term-tty converts | zsh receives | zsh translates (internal)| zsh actual key-event
------------|---------------|-------------------|-------------|---------------|---------------------
CR | CR &rarr; NL | NL &rarr; CR | CR | CR &rarr; NL | associated with NL
NL | NL | NL &rarr; CR | CR | CR &rarr; NL | associated with NL

This pull-req:

input to Vim | <del>Vim converts</del> | term-tty converts | zsh receives | zsh translates (internal)| zsh actual key-event
------------|---------------|-------------------|-------------|---------------|---------------------
CR | CR | CR &rarr; NL | NL | NL &rarr; CR | associated with CR
NL | NL | NL &rarr; CR | CR | CR &rarr; NL | associated with NL

**Comment by ichizok** [comment]
Additionally: This PR includes stop the conversion of NL to CRNL (when `-onlcr`).

Example of problem:

`vim --clean +'term bash'` and do the following commands;

```
bash-4.4$ stty -onlcr
bash-4.4$ echo -e "123\n456"
```

expected (and actual on other usual terminals):

```
bash-4.4$ echo -e "123\n456"
                            123
                               456
                                  bash-4.4$
```

actual:

```
bash-4.4$ echo -e "123\n456"
123
456
bash-4.4$
```

**Comment by brammool** [comment]
Why revert 8.0.1261?  That breaks any shell or program changing the tty settings.

**Comment by ichizok** [comment]
My understanding is 8.0.1261 is for fix #1998, and just this PR can fix it (without 8.0.1261).

As above my comments, I think the conversion CR to NL causes some problems and Vim should not do it.
Could you tell me specifically what situation the conversion is for?

**Comment by brammool** [comment]
I don't understand what you are doing here.  Input and output are being mixed up.  The conversions of libvterm appears to be missing.
Try running ":term cat file" and see that the nl to cr-nl is needed.

**Comment by brammool** [comment]
Hmm, actually, the essential part appears to be to avoid VTERM_KEY_ENTER, so that libvterm won't convert CR.

**Comment by ichizok** [comment]
> I don't understand what you are doing here. Input and output are being mixed up. The conversions of libvterm appears to be missing.

The conversion is done by tty (associated with `:term`) itself when`+icrnl` or `+onlcr`.

> Try running ":term cat file" and see that the nl to cr-nl is needed.

I tried it (`:term cat vim/configure`) on Vim with this PR, it was displayed correctly.
(On Ubuntu 16.04 GNOME-terminal / macOS 10.13.1 Terminal.app)

The result of `:term stty -a` is below. (on Ubuntu GNOME-terminal)

```
speed 38400 baud; rows 28; columns 169; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

This means there are both `+icrnl` and `+onlcr` by default, so as for output to term-tty (e.g. `:term cat file`), the output of one NL from `cat file` to tty is translated into CRNL by tty itself, therefore Vim receives CRNL.

**Comment by brammool** [comment]
Now I can no longer reproduce the old problem that the CR was missing when writing NL.  OK, let's include most of your change, and we'll see if something fails then.

**Pull request closed without merging**
