### PR TITLE
Accepts a string in map(), mapnew() and filter()

### PR DESCRIPTION
**Pull request by rbtnn**
Currently for-in statement accepts a string but the first argument of map(), mapnew() and filter() does not accept a string. 
This will accept a string to the first argument of  map(), mapnew() and filter().

|               | Blob | String    | List    | Dict   |
|-----------|------|--------|------|------|
|for-in {expr}       | yes  | yes    | yes  |  -   |
| map({expr}, )     | yes  |  - → **yes**   | yes  | yes  |
|mapnew({expr}, )  | yes  |  - → **yes**     | yes  | yes  |
| filter({expr}, )  | yes  |  -  → **yes**  | yes  | yes  |
|redulce({expr}, ) | yes  |  -     | yes  |  -   |

### CODE REVIEW

**Comment by lacygoill** [comment]
Could we also support `sort()`?

Right now, to sort the characters in a string, we first have to `split()` it, then `join()` it at the end:
```vim
echo 'irejhnqpmgyoxvclukfbsatzwd'->split('\zs')->sort()->join('')
```
    abcdefghijklmnopqrstuvwxyz

If `sort()` accepted a string, we could simplify the code like this:
```vim
echo 'irejhnqpmgyoxvclukfbsatzwd'->sort()
```
Which is shorter and more readable.

FWIW, I would use this for a flag in my tabline which monitors whether `'cpoptions'` was unexpectedly modified.  Currently, I have to write this expression:

    &cpoptions->split('\zs')->sort() != cpoptions_save ? '[cpo]' : ''

`sort()` is necessary to normalize the flags.  If it accepted a string, I would write:

    &cpoptions->sort() != cpoptions_save ? '[cpo]' : ''

**Comment by rbtnn** [comment]
>Could we also support sort()?

@lacygoill I guess we can support it too. I want to supports only map(), mapnew() and filter() in this PR.

**Comment by lacygoill** [comment]
Understood.  Thank you for your work on this PR.

**Comment by brammool** [comment]
It looks like the code handles composing characters individually.  For filter() that would be less useful - normally if you decide to drop a character the following composing character should also be dropped, otherwise it goes on top of the previous character.
That also makes the code simpler: use mb_ptr2len() to isolate a character, including composing characters.

**Comment by rbtnn** [comment]
>It looks like the code handles composing characters individually. For filter() that would be less useful - normally if you decide to drop a character the following composing character should also be dropped, otherwise it goes on top of the previous character.

I'm sorry. I did not understand how you want to fix it.
If you want to affect the first argument of map(), mapnew() and filter(), I think we should not it affected for the argument because Vim' string is immutable.

>That also makes the code simpler: use mb_ptr2len() to isolate a character, including composing characters.

I used mb_ptr2len().

**Comment by brammool** [comment]
It looks better now.  But I still don't see a composing character in the test.  Please also test map() and filter() with some composing characters.  See "
:help patterns-composing" for info.

**Comment by rbtnn** [comment]
> See ":help patterns-composing" for info.

Thanks you. I did not know this help. I'll add tests.

**Pull request closed without merging**
