### PR TITLE
syntax: gitcommit, gitsendemail: highlight pseudo-headers

### PR DESCRIPTION
**Pull request by rohieb**
cc @tpope

### CODE REVIEW

**Comment by chrisbra** [comment]
I think this rather belongs to https://github.com/tpope/vim-git

**Comment by rohieb** [comment]
> I think this rather belongs to https://github.com/tpope/vim-git

Huh. Should we remove those files then here?

**Comment by chrisbra** [comment]
> Huh. Should we remove those files then here?

No, but that is the upstream repository for the runtime files in Vim.

**Comment by rohieb** [comment]
Alright then, I'll submit it there :)

**Pull request closed without merging**
