### PR TITLE
Add neighbor window information to getwininfo()

### PR DESCRIPTION
**Pull request by yegappan**
Add the neighbor window information to the getwininfo() function.
It returns the window ID of the windows above, right, below and left
of the specified window in a list. If a neighbor window is not present,
then it is set to 0.

### CODE REVIEW

**Comment by brammool** [comment]
Yegappan wrote:

> Add the neighbor window information to the getwininfo() function.
> It returns the window ID of the windows above, right, below and left
> of the specified window in a list. If a neighbor window is not present,
> then it is set to 0.

It should be clearer what happens if there are several windows on a
side. It would also be useful to mention what this can be used for.


-- 
hundred-and-one symptoms of being an internet addict:
219. Your spouse has his or her lawyer deliver the divorce papers...
     via e-mail.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by blueyed** [comment]
> It should be clearer what happens if there are several windows on a side.

I think this has been addressed, hasn't it?

> It would also be useful to mention what this can be used for.

My use case with https://github.com/blueyed/vim-qf_resize is to automatically resize location list / quickfix windows, and for this I need information from windows above the current (qf) one (`&winfixheight` and `&filetype` currently).

**Comment by andymass** [comment]
I think Bram means it should be pointed out in the documentation that the window neighbors are those which wincmd h, wincmd j, wincmd k, wincmd l jump to.  By the way, what about `winnr('j')` etc?

@blueyed your use-case is still unclear.  Why exactly do you need to know the window above to resize the quickfix?  And the window "above" the quickfix is not the same as the window which `wincmd k` jumps to, which you appear to be implicitly assuming.

**Comment by blueyed** [comment]
> what about `winnr('j')` etc

Interesting idea.

> Why exactly do you need to know the window above to resize the quickfix?

To see if it has a fixed height and if it is a qf window itself.
IIRC the algo wants to find the first non-fixed-non-qf window, because this gets resized when the quickfix window appears, and needs to be resized then when resizing the qf window.
This assumes &noequalalways, and vim-qf_resize is meant to resize a qf window to e.g. 2 lines, if that's enough, and uses percentages (of &lines) otherwise.

> And the window "above" the quickfix is not the same as the window which wincmd k jumps to

Why not?

**Comment by andymass** [comment]
One might have a layout like this:

        +----------------+----------------------+
        |                |                      |
        |  REGULAR       |    LOCLIST           |
        +---------------------------------------+
        |                                       |
        |    QUICKFIX                           |
        +---------------------------------------+

In QUICKFIX, using `wincmd K` will either go to REGULAR or LOCLIST (with winfixheight), depending on the cursor position.  If it goes to REGULAR your algorithm assumes the window is elastic and can be resized.  If it goes to LOCLIST it assumes it can't.

**Comment by blueyed** [comment]
Ah, sure.
TBH I wasn't aware that this depends on the cursor position.. :D

So in this case I assume the `neighbor` information would also be incosistent / depending on the cursor position.

I think what @brammool mentioned in https://github.com/vim/vim/issues/3203#issuecomment-405042379 makes sense: having all the information might be better for me use case, and I might be able to even see from there already which window was resized when the qf window appeared etc.

**Comment by chrisbra** [comment]
I think this has been included as of https://github.com/vim/vim/releases/tag/v8.1.0185

**Comment by yegappan** [comment]
Moving the support for getting the neighbor window information to the winnr() function.
Closing this pull request and opening a new pull request for the change.

**Pull request closed without merging**
