### PR TITLE
update slovak menu

### PR DESCRIPTION
**Pull request by lesorubshayan**
close https://github.com/vim/vim/pull/10721

### CODE REVIEW

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
Same comment as for #14685 
- Keep the existing Date format style
- Move the added translation to before the line resetting 'cpo' 
- Change the commit author

Thanks!

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
thanks!

**Pull request closed without merging**
