### PR TITLE
Update tmux syntax file

### PR DESCRIPTION
**Pull request by ericpruitt**
The change updates the tmux syntax files since there have been several releases since it was originally submitted.

CC: @blueyed who filed https://github.com/ericpruitt/tmux.vim/issues/6.

### CODE REVIEW

**Comment by chrisbra** [comment]
> setlocal iskeyword+=-

Do not use that. Use `syntax iskeyword` instead.

**Comment by ericpruitt** [comment]
> Do not use that. Use syntax iskeyword instead.

Why?

**Comment by chrisbra** [comment]
> Why?

Because the option influences too many areas in Vim (e.g. what is being matched by `/\k`, how the word movements work, etc.). You do not want to have those side effects just for a syntax rule. Therefore the specific command `:syntax iskeyword` has been introduced. That does not have the side effects and only allows to specify what to consider keywords in syntax files. I think the help also talks about it at `:h syn-iskeyword`

**Comment by ericpruitt** [comment]
Thanks. I believe suggestions should be accompanied with explanations so the people you're correcting can learn. I'm not the original author of this syntax file, and I'm not particularly knowledge about Vim's many syntax highlighting commands.

**Comment by ericpruitt** [comment]
I tried replacing that line with `syntax iskeyword=@,48-57,_,192-255,-`, but this results in none of the keywords in tmuxOptions and tmuxCommands being highlighted. What am I doing wrong?

**Comment by chrisbra** [comment]
> `syntax iskeyword=@,48-57,_,192-255,-`

According to the help, it should be `syntax iskeyword @,48-57,_,192-255,-` I think.

**Comment by ericpruitt** [comment]
I've updated the pull request.

**Comment by brammool** [comment]
Thanks, I'll include it now.

**Pull request closed without merging**
