### PR TITLE
Support using a script-local function when setting a *func option

### PR DESCRIPTION
**Pull request by yegappan**

### CODE REVIEW

**Comment by lacygoill** [comment]
Thank you for working on this.

The test works thanks to the `x` flag passed to `feedkeys()`, but in practice the feature does not work.  If we remove `x`, we still get an error:
```vim
vim9script
def CountSpaces(type = ''): string
    if type == ''
        return 'g@'
    endif
    normal! '[V']y
    echomsg getreg('"')->count(' ')
    return ''
enddef
set operatorfunc=s:CountSpaces
nnoremap <expr> <F4> <SID>CountSpaces()
['a b c d e']->setline(1)
feedkeys("\<F4>_")
```
    E120: Using <SID> not in a script context: s:CountSpaces

And an interactive usage is closer to `feedkeys()` without the `x` flag, than with it.
You can check this by removing `feedkeys()` from the previous snippet, and typing `<F4>_` manually.  Again, you should get the previously mentioned error.

---

Although, I'm not sure the issue is with this PR.  This is an issue which I noted a long time ago.

If a mapping is defined in a Vim9 script, and it's pressed by `feedkeys()` with the `x` flag, the Vim9 syntax is used:
```vim
vim9script
nnoremap <F3> <Cmd>1yank<cr>
feedkeys("\<F3>", 'x')
```
    E1050: Colon required before a range: 1yank

But this might be unexpected, because usually in a mapping, it's the legacy syntax which is used (even in a Vim9 script):
```vim
vim9script
nnoremap <F3> <Cmd>1yank<cr>
feedkeys("\<F3>")
```
    no error

**Comment by vim-ml** [comment]
Hi,

On Thu, Dec 16, 2021 at 7:27 PM lacygoill ***@***.***> wrote:

> Thank you for working on this.
>
> The test works thanks to the x flag passed to feedkeys(), but in practice
> the feature does not work. If we remove x, we still get an error:
>
> vim9scriptdef CountSpaces(type = ''): string
>     if type == ''
>         return 'g@'
>     endif
>     normal! '[V']y
>     echomsg getreg('"')->count(' ')
>     return ''enddefset operatorfunc=s:CountSpacesnnoremap <expr> <F4> <SID>CountSpaces()
> ['a b c d e']->setline(1)feedkeys("\<F4>_")
>
> E120: Using <SID> not in a script context: s:CountSpaces
>
> And an interactive usage is closer to feedkeys() without the x flag, than
> with it.
> You can check this by removing feedkeys() from the previous snippet, and
> typing <F4>_ manually. Again, you should get the previously mentioned
> error.
>

I tried using the above script with the patch. I don't see the E120 error.
It properly counts and prints the number of spaces. I tried using both
feedkeys()
to send <F4> and by manually pressing <F4>_.
Are you testing this script with the patch?

Regards,
Yegappan


> ------------------------------
>
> Although, I'm not sure the issue is with this PR. This is an issue which I
> noted a long time ago.
>
> If a mapping is defined in a Vim9 script, and it's pressed by feedkeys()
> with the x flag, the Vim9 syntax is used:
>
> vim9scriptnnoremap <F3> <Cmd>1yank<cr>feedkeys("\<F3>", 'x')
>
> E1050: Colon required before a range: 1yank
>
> But this might be unexpected, because usually in a mapping, it's the
> legacy syntax which is used (even in a Vim9 script):
>
> vim9scriptnnoremap <F3> <Cmd>1yank<cr>feedkeys("\<F3>")
>
> no error
>
>
>

**Comment by lacygoill** [comment]
I don't know why but I can't reproduce anymore.  Now, the feature works as expected with the patch.

Sorry for the confusion, and thank you again for the new syntax.

**Comment by lacygoill** [comment]
There is still another possible issue.  In Vim9, we never need `s:`.  Except here:
```vim
vim9script
def CountSpaces(type = ''): string
    if type == ''
        return 'g@'
    endif
    normal! '[V']y
    echomsg getreg('"')->count(' ')
    return ''
enddef
set operatorfunc=CountSpaces
nnoremap <expr> <F4> <SID>CountSpaces()
['a b c d e']->setline(1)
feedkeys("\<F4>_")
```
    E117: Unknown function: CountSpaces

Vim only looks for `CountSpaces` in the global namespace; it doesn't look in the script-local one.

It seems weird that we can drop `s:` everywhere, except when setting a `'*func'` option.

**Comment by lacygoill** [comment]
> It seems weird that we can drop `s:` everywhere, except when setting a `'*func'` option.

Never mind, it's a different issue.  There are other corner cases, where we can't drop `s:`.  I'll open a separate issue later.

**Pull request closed without merging**
