### PR TITLE
Add support for fuzzy completion to command-line completion

### PR DESCRIPTION
**Pull request by yegappan**
Fuzzy completion is supported for the following: buffer names, argument list, autocmd groups/events, built-in command
names, environment variables, built-in and user defined function names, highlight group names, menu names,
syntax group names, and sub options for commands.

Fuzzy completion is not supported for file names and directory names.

### CODE REVIEW

**Comment by brammool** [comment]
Have some people tried this out?  How well does it work?

The help should say a bit more about what "fuzzy" means for this. Something like ordering matches by "best match" instead of alphabetical?

**Comment by vim-ml** [comment]
Hi Bram,

On Sat, Feb 19, 2022 at 11:36 AM Bram Moolenaar ***@***.***>
wrote:

> Have some people tried this out?
>
No. It will be good if others can try this out and give some feedback.

How well does it work?
>
The help should say a bit more about what "fuzzy" means for this. Something
> like ordering matches by "best match" instead of alphabetical?
>
>
>
I have updated the help text.

Regards,
Yegappan

**Comment by vim-ml** [comment]
On Sat, Feb 19, 2022 at 12:18 PM Yegappan Lakshmanan
***@***.***> wrote:
>
> Hi Bram,
>
> On Sat, Feb 19, 2022 at 11:36 AM Bram Moolenaar ***@***.***> wrote:
>>
>> Have some people tried this out?
>
> No. It will be good if others can try this out and give some feedback.
>

Currently the cmdline fuzzy completion works in the following cases.

1. Buffer name completion for the ":buffer", ":sbuffer", ":bdelete",
":bwipeout", ":bunload", ":checktime",
    "sign place file="  commands and user defined commands with
"-complete=buffer" argument.
2. Built-in and user defined Ex command names.
3. Option names in the ":set" command
4. Variable and function names in a Vim expression
5. Autocmd group and event names.
6. Environment variable names.
7. Highlight group name
8. Menu names
9. Syntax group names

It is not supported for file/directory names, tag names and color scheme names.

- Yegappan

**Comment by Shane-XB-Qian** [comment]
> Have some people tried this out? How well does it work?

there was a try in the past, check #7872 around the bottom of that ticket.

**Comment by brammool** [comment]
Looks like comments have quieted down, let me include this now.

**Comment by habamax** [comment]
It works okay but results are not that useful as I thought they would be.

For example, I have a `FixSpaces` user command and when I try to find it with `:fi<tab>` or `:Fi<Tab>` I get following:

image

It is really deep down the list:
image


vim-fuzzy


PS, `:fs` finds `:FixSpaces` right away, which is convenient indeed.

**Comment by habamax** [comment]
I also have `:Sy` command and whey I do `:sy<tab>`

image

**Comment by habamax** [comment]
And this is indeed strange...

I have my own implementation of fuzzy command selection (using built in functions) and I get this:

image

**Comment by vim-ml** [comment]
Hi,

Thanks for testing and reporting the problem. I found the issue (basically
regular expression matching
is used instead of fuzzy matching for some matches). I will send out a PR.

Regards,
Yegappan

**Comment by vim-ml** [comment]
Hi,

On Thu, Feb 24, 2022 at 7:50 AM Maxim Kim ***@***.***> wrote:

> And this is indeed strange...
>
> I have my own implementation of fuzzy command selection (using built in
> functions) and I get this:
>

These issues should now be addressed by patch 8.2.4465. Can you try the
latest image?

Thanks,
Yegappan

**Comment by habamax** [comment]
Yes, it works very well now, thank you!

**Pull request closed without merging**
