### PR TITLE
php syntax: update buildin openssl functions

### PR DESCRIPTION
**Pull request by jelly**
Update the buildin openssl functions to the latest status on php.net.

### CODE REVIEW

**Comment by chrisbra** [comment]
please contact the syntax file maintainer

**Comment by jelly** [comment]
@chrisbra mail him or just mention @JasonWoof?

**Comment by chrisbra** [comment]
it depends. If he is active on github metioning his user name might suffice. Nevertheless I would write him an email, just to make sure.

**Comment by JasonWoof** [comment]
The @JasonWoof mention did send me an email. That works :-)

This patch looks good to me. Thanks @jelly !

I merged it locally, updated the "Last Change" date and sent the updated file to Bram via email like I do.

I don't have commit access here, so somebody else will have to take the appropriate action with this pull request page.

**Comment by brammool** [comment]
Will be included in the next runtime file update

**Pull request closed without merging**
