### PR TITLE
translate new menu items on ukrainian(uk_ua utf8)

### PR DESCRIPTION
**Pull request by lesorubshayan**
@chrisbra after merge this, close 10725

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks, please update the header of the file

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
Same comment as for #14685 
- Move the added translation to before the line resetting 'cpo' 
- Change the commit author

Thanks!

**Comment by ronin49** [comment]
@chrisbra

**Comment by chrisbra** [comment]
closing for the reasons mentioned here https://github.com/vim/vim/pull/14703#issuecomment-2092337585

**Pull request closed without merging**
