### PR TITLE
Create pcmk.vim

### PR DESCRIPTION
**Pull request by wtmpx**
Hi,
Is it possible to add this file to syntax directory?
https://raw.githubusercontent.com/ClusterLabs/crmsh/a9a07aa54ce9e8f4e801232badb9a4f40233ecae/contrib/pcmk.vim

I also wrote these today in filetype.vim file:

" PCMK - HAE - crm configure edit
au BufNewFile,BufRead *.pcmk             setf pcmk

### CODE REVIEW

**Comment by chrisbra** [comment]
that should be submitted by their authors, so we know we can distribute it with vim. Also the author should state, whether the vim license applies.

**Comment by wtmpx** [comment]
Hi, 
Is this what you looking for?
https://github.com/ClusterLabs/crmsh/blob/master/COPYING 

Thanks

**Comment by chrisbra** [comment]
Yeah, something like that. However we would still like to have that handed in by their respective upstream authors, because they know best when it has a certain version that is ready to be included by Vim (and so they can then also update those runtime files every now and then, whenever they feel a new version should be distributed).
You might want to go ahead and file an issue at their repository to ask them to submit their work to Bram for distribution with Vim.

**Comment by wtmpx** [comment]
The last date the file modified is 5 years ago. Sep 10, 2012 
I don't know why they didn't include it with vim even they wrote it. 
I'm new to this github thing. I saw something missing and I felt I have to connect the puzzles

**Comment by wtmpx** [comment]
Hi,
I have been informed that my changes to filetype.vim is approved. Now this
file is needed.

Since it have been untouched since 5 years, I think we are safe to include
it.

Thanks
Ahmad

On Nov 1, 2017 15:00, "Christian Brabandt" <notifications@github.com> wrote:

Yeah, something like that. However we would still like to have that handed
in by their respective upstream authors, because they know best when it has
a certain version that is ready to be included by Vim (and so they can then
also update those runtime files every now and then, whenever they feel a
new version should be distributed).
You might want to go ahead and file an issue at their repository to ask
them to submit their work to Bram for distribution with Vim.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vim/vim/pull/2275#issuecomment-341114012>, or mute the
thread

**Comment by brammool** [comment]
No progress for a long time, therefore closing.

**Pull request closed without merging**
