### PR TITLE
Added Lithuanian translation of Tutor v. 1.4 by Laurynas Stančikas

### PR DESCRIPTION
**Pull request by rimas-kudelis**
This translation has been available for free download from lietuvybe.org, then lietuvybe.akl.lt, then lietuvybė.lt since at least 2006[1], but nobody ever bothered to contribute it upstream.

I'm not sure if the original author's email still works, but I'm positive that he wouldn't mind his work being shared more widely. I don't think it makes much sense to distribute it only via the website dedicated to Lithuanian language and localization in IT, which lietuvybė.lt is.

[1] https://web.archive.org/web/20060222162117/http://lietuvybe.org/files/vim-tutor-lt.txt

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks, I am a bit skeptical because we haven't heard from the author. Can you at least add some copyright for the Lithuanian translation?

**Comment by rimas-kudelis** [comment]
Hi, no problem, but please elaborate what you mean. The author has already credited himself at the end of the file, and I made the commit by his name, so I assumed that this would be enough.

I just made an attempt to contact who I presume is the author on LinkedIn (because an attempt to contact by email failed immediately). If he responds, I'll ask him to chime in here personally.

For a bit more context, the website where this file is distributed (lietuvybė.lt), has been edited by mostly myself for the past 10+ years, so it's not like I'm stealing the file from some random place. :) I'm actually hosting it on GitHub pages since this January, so the same file is also already available here: https://github.com/lietuvybe-lt/lietuvybe.lt/blob/main/content/nuorodos/vim-tutor-lt.txt.

**Comment by chrisbra** [comment]
ah, okay I didn't see the credit line. Okay, let's wait if he responds on linkedin.

**Comment by rimas-kudelis** [comment]
Okay, let's give it a week or so. If he doesn't answer, I hope you'll accept the file.

BTW, I just discovered that this file was freely available as far back as 2001, so it's really old news by now: https://web.archive.org/web/20010806014748/http://www.lietuvybe.org/vim-tutor-lt.txt.

**Comment by chrisbra** [comment]
okay let me merge it

**Comment by rimas-kudelis** [comment]
Thanks! I think I'll make a new PR soon because I couldn't resist and updated the file to 1.7.

**Pull request merged**
