### PR TITLE
support 10terminal to make terminal rows 10

### PR DESCRIPTION
**Pull request by mattn**
added `:10terminal` to make rows 10. also test.

### CODE REVIEW

**Comment by vim-ml** [comment]
On Sat, Aug 5, 2017 at 5:49 PM, mattn <vim-dev-github@256bit.org> wrote:
> Commit Summary
>
> support 10terminal to make terminal rows 10

Wouldn't it be better if the number range before the :terminal command
is interpreted as the range of lines to be fed to the stdin of the
command to be run?

For example when editing a shell file and there is a chunk lines, say
from lines  5 to 20, and you would like to run them directly you can
do something like this:

:5,20terminal

and vim would then spawn 'shell' and feed the lines 5 to 20 to the
'shell' stdin. And when the last line is fed the shell terminates due
to EOF and then vim would then go out of the terminal mode into the
terminal normal mode.

Same goes for the visual line-wise selection (:'<,'>terminal).

nazri

**Comment by mattn** [comment]
All of &shell doesn't accept stdin. For example, cmd.exe doesn't.

**Comment by brammool** [comment]
Yasuhiro Matsumoto wrote:

> All of &shell doesn't accept stdin. For example, cmd.exe doesn't.

But it would work for filter-like commands.  E.g.:

	1,10w !wc
	
counts words and puts the output on the screen, then:

	1,10terminal wc

Would put the result in a terminal window.  Of course more useful if the
output is longer or takes some time to get the result.

It's possible to have:

	10terminal

Use "10 for the window size, and at the same time:

	10,20terminal

To pipe the selected lines to a command.  But it's unusual to have the
command behave differently depending on how many items are in the range.
Also:

	10 split | terminal ++curwin

Already sets the window size.  Bit more typing though.

-- 
I am always surprised in the Linux world how quickly solutions can be
obtained.  (Imagine sending an email to Bill Gates, asking why Windows
crashed, and how to fix it...  and then getting an answer that fixed the
problem... <0>_<0> !)		              -- Mark Langdon

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
I'm okay to change behavior to use stdin for the address. However, empty argument for :10,20terminal should be error, I think.

```
10 split | terminal ++curwin
```
Maybe :terminal ++rows=10 is another candidate.

**Comment by brammool** [comment]
Yasuhiro wrote:

> I'm okay to change behavior to use stdin for the address. However,
> empty argument for :10,20terminal should be error, I think.

You mean, to avoid accidentlly sending text to the shell, you never know
what it will do?

> ```
> 10 split | terminal ++curwin
> ```
> Maybe :terminal ++rows=10 is another candidate.

I thought of something like that, but there actually are lots of ways to
specify what kind of window to open.  I thought it would be a lot easier
to first open the window and then run the terminal inside it.

-- 
It might look like I'm doing nothing, but at the cellular level
I'm really quite busy.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by mattn** [comment]
>You mean, to avoid accidentlly sending text to the shell, you never know what it will do?

Yes, it is. But this is not strong opinion.

> I thought of something like that, but there actually are lots of ways to specify what kind of window to open.  I thought it would be a lot easier to first open the window and then run the terminal inside it.

Make sense. So that open terminal which read from buffer as stdin with rows 10 should be:

:10 split | %terminal ++curwin

Right?

**Comment by brammool** [comment]
Yasuhiro wrote:

> >You mean, to avoid accidentlly sending text to the shell, you never
> >know what it will do?
> 
> Yes, it is. But this is not strong opinion.
> 
> > I thought of something like that, but there actually are lots of
> > ways to specify what kind of window to open.  I thought it would be
> > a lot easier to first open the window and then run the terminal
> > inside it.
> 
> Make sense. So that open terminal which read from buffer as stdin with rows 10 should be:
> 
> :10 split | %terminal ++curwin
> 
> Right?

Yes.

-- 
SOLDIER: What?  Ridden on a horse?
ARTHUR:  Yes!
SOLDIER: You're using coconuts!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
