### PR TITLE
Add functions to set/get cursor and mark position using character count

### PR DESCRIPTION
**Pull request by yegappan**
Add the following functions:

  getcharpos()  -  Get the character position of the cursor or a mark. For non multibyte text, same as getpos().
  setcharpos()  -  Set the character position of the cursor or a mark. For non multibyte text, same as setpos().
  charcol()  -  Get the character count of the cursor or a mark in a line. For non multibyte text, same as col().
  getcursorcharpos()  -  Get the character position of the cursor. For non multibyte text, same as getcurpos().
  setcursorcharpos()  -  Set the character position of the cursor. For non multibyte text, same as cursor().

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
@yegappan great, https://github.com/vim/vim/pull/6955#issuecomment-692608089 so now looks solved 'char' column, one day we may can `w` `e` `b` for real char/word.

**Comment by Shane-XB-Qian** [comment]
@brammool @yegappan there is a regression/not-compatible issue:
in the past `cursor(line, col)`, that 'col' can be a 'string' type, now must be 'int'.
for now, not sure caused by this, or vim9, since vim9 made type check looks strict..

**Comment by vim-ml** [comment]
Hi,

On Sat, Jan 16, 2021 at 6:55 AM Shane-XB-Qian <vim-dev-github@256bit.org>
wrote:

> @brammool <https://github.com/brammool> @yegappan
> <https://github.com/yegappan> there is a regression/not-compatible issue:
> in the past cursor(line, col), that 'col' can be a 'string' type, now
> must be 'int'.
> for now, not sure caused by this, or vim9, since vim9 made type check
> looks strict..
>
>
>
It is a regression caused by this change. I added a check to make sure
the column argument is a number. I didn't realize plugins are passing string
for this argument. I will create a PR to address this.

Regards,
Yegappan

**Comment by Shane-XB-Qian** [comment]
>  I didn't realize plugins are passing string for this argument. I will create a PR to address this.

yea, some plugins did not treat type very clear, since it's implicit for legacy vim script. waitting... thx. :-)

**Comment by Shane-XB-Qian** [comment]
BTW: pls consider if to add some test case in 'test_cursor_func.vim' as well, for now, those all were 'number', but no 'string'.. :-)

**Pull request closed without merging**
