### PR TITLE
Update tutor.es

### PR DESCRIPTION
**Pull request by rodoviario**
Added missing "r" in "curso" and changed "primera" with "segunda" which is the correct word for the meaning of the lesson. I don't understand why the pull request shows 271 lines deleted and inserted. I only added an "r" and changed a word.

### CODE REVIEW

**Comment by k-takata** [comment]
> I don't understand why the pull request shows 271 lines deleted and inserted.

The encoding of the file is latin1, but you changed it to utf-8. Please change it back to latin1.

**Comment by rodoviario** [comment]
I'm sorry for the inconvenience

Well, I edited directly in github.com. I am trying to find the encoding
setting on the editor, but there is none. I haven't changed de encoding nor
touching anything but the "edit" button.

I will keep searching

**Comment by rodoviario** [comment]
I have found the reason. If I edit "tutor.es"... github.com detects its
encoding and inform's me that it will be transcoded on commit to UTF-8

automatic change

But if I edit the other file "tutor.es.utf-8" github.com doesn't do any
transcode. I think that I should create a pull request with the same 2
changes to that file instead, and go on if it doesn't alter all that
lines... and delete the previous pull request. I will leave the new pull
request to the other file ready, and wait for you answer before closing
this pull request. What do you think?

**Comment by brammool** [comment]
I'll use the changes from tutor.es.utf-8.

**Pull request closed without merging**
