### PR TITLE
runtime(doc,syntax): help formatting and add syntax

### PR DESCRIPTION
**Pull request by Milly**
- Apply `helpExample`.
- Remove `helpHeader` from URL, because `helpURL` takes priority.
- Fix indentation.
- Add `N` emphasis to `helpSpecial`.

### CODE REVIEW

**Comment by chrisbra** [comment]
Thanks. I had to guess what this is for:
```
syn match helpSpecial		"^\t[enfLlbghNEpticCuUwWkmMjJP]N "ms=s+2,me=e-1
```
It seems this is for `:h cinoptions-values`? If that is the case, it seems there are a few flags missing and it rather should be this?
```
syn match helpSpecial           "^\t[enfLlbghNEpticCuUwWkmMjJP>}{^:=+/)#]N "ms=s+2,me=e-1
```

**Comment by Milly** [comment]
> ```
> syn match helpSpecial           "^\t[enfLlbghNEpticCuUwWkmMjJP>}{^:=+/)#]N "ms=s+2,me=e-1
> ```

`{non-alphanumeric-symbol}N` are not needed as they are already matched:
```vim
syn match helpSpecial		"\<N\>"
```

**Comment by chrisbra** [comment]
Well, the highlighting is off for those characters

**Comment by Milly** [comment]
I understand that the results vary depending on `'iskeyword'`.

**Pull request closed without merging**
