### PR TITLE
runtime(debsources): Set comment and commentstring

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by chrisbra** [comment]
@jamessan

**Comment by dkearns** [comment]
This needs to go into a new filetype plugin.

**Comment by jamessan** [comment]
Thanks for the idea, @przepompownia.  I'll add a new ftplugin upstream and create a PR along with some other changes to the Debian files.

**Comment by chrisbra** [comment]
okay, thanks all. closing now

**Comment by przepompownia** [comment]
Indeed, the vast majority of similar examples takes place in `ftplugin`. 

@jamessan Please fix it also in Neovim while you are paying attention to this issue. 

Thanks all too.

**Comment by chrisbra** [comment]
neovim automatically syncs from Vim distribution.

**Comment by przepompownia** [comment]
> neovim automatically syncs from Vim distribution.

Good to know. I still don't see how automated some changes can be, although I browse the recent Neovim commits and look into Vim patches.

**Pull request closed without merging**
