### PR TITLE
Support using object and class methods as funcrefs

### LINKED ISSUE #11981: [vim9script] Cannot pass (instance or static) method to function
### Steps to reproduce

Source this script:

```vim
vim9script

def Map(F: func(number): number): func(number): number
  return (n: number) => F(n)
enddef

def Double(n: number): number
  return 2 * n
enddef

class Math
  def Double(n: number): number
    return 2 * n
  enddef

  static def StaticDouble(n: number): number
    return 2 * n
  enddef
endclass

echo Map(Double)(24)                # OK
echo Map((n: number) => 2 * n)(24)  # OK

const math = Math.new()

echo Map(math.Double)(24)           # Error: E1326
echo Map(Math.StaticDouble)(24)     # Error: E1338
```

### Expected behaviour

The script should run without errors.

### Version of Vim

9.0.1306

### Environment

macOS 13.2
Apple Terminal
xterm256-color
ZSH 5.8.1

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by yegappan**
Fixes #11981, #12417 #12960 and #12324.

### CODE REVIEW

**Comment by errael** [comment]
I've been trying a variety of things, haven't been able to break it (yet?). 

While trying stuff with `call` and varargs, I ran into something that _may_ be an issue at the end of the following script.

```
vim9script

class C
  def VA(...args: list<number>): list<number>
	return args
  enddef
  static def SVA(...args: list<any>): list<any>
	return args
  enddef
endclass
var obj = C.new()

echo call(obj.VA, [4, 2])

var FF: func
FF = obj.VA
echo call(FF, [ 1, 2, 3])
echo call(C.SVA, [ 7, 9 ])
echo call("C.SVA", [ 7, 9 ])	# <<< Unknown function: C.SVA
```

**Comment by yegappan** [comment]
> I've been trying a variety of things, haven't been able to break it (yet?).
> 

Thanks for testing the PR and it is good to hear that you didn't encounter any issues.

>
> While trying stuff with `call` and varargs, I ran into something that _may_ be an issue at the end of the following script.
> 
> ```
> vim9script
> 
> class C
>   def VA(...args: list<number>): list<number>
> 	return args
>   enddef
>   static def SVA(...args: list<any>): list<any>
> 	return args
>   enddef
> endclass
> var obj = C.new()
> 
> echo call(obj.VA, [4, 2])
> 
> var FF: func
> FF = obj.VA
> echo call(FF, [ 1, 2, 3])
> echo call(C.SVA, [ 7, 9 ])
> echo call("C.SVA", [ 7, 9 ])	# <<< Unknown function: C.SVA
> ```

Using the object/class method name as a string is currently not supported. You can use it as a funcref (as you have already found out). I will update the documentation.

**Comment by errael** [comment]
> Using the object/class method name as a string is currently not supported

FWICT, using a variable in a string for a function name doesn't work, so I don't think **object method** could ever be used as a string. But maybe static.

**Comment by errael** [comment]
Found something, looks weird.
(fails both in def and script level)

```
T1 111
Error detected while processing :source buffer=2[16]..function <SNR>11_FDef[2]..C.F2:
line    2:
E1327: Object required, found number
```

```
vim9script

class C
  this.val: number
  def F2(): number
	#return 3 		# <<< this works in all cases
	return this.val		# <<< fails when invoked with `call`
  enddef
endclass

def FDef(obj: C)
    echo "T1" obj.F2()
    echo "T2" call(obj.F2, [])
enddef

FDef(C.new(111))
```

**Comment by errael** [comment]
Don't even need to use `call`

```
vim9script

class C
  this.val: number
  def F2(): number
	return this.val
  enddef
endclass

var obj = C.new(333)
echo obj.F2()
var F = obj.F2
echo F()
```

**Comment by chrisbra** [comment]
thanks! let me merge it now, those problems can then be fixed in a followup PR.

**Comment by chrisbra** [comment]
included as of 29bb67f1beefc7fd393dbfd9ee77d92f1db3a3c0

**Comment by yegappan** [comment]
> Don't even need to use `call`

I have created the PR https://github.com/vim/vim/pull/13341 to address this.

> 
> ```
> vim9script
> 
> class C
>   this.val: number
>   def F2(): number
> 	return this.val
>   enddef
> endclass
> 
> var obj = C.new(333)
> echo obj.F2()
> var F = obj.F2
> echo F()
> ```

**Pull request closed without merging**
