### PR TITLE
syntax/make.vim updates

### PR DESCRIPTION
**Pull request by rohieb**
A few small changes:

- don't generally parse strings in make code
- also highlight file names in 'include' lines
- and some cleanup and housekeeping

### CODE REVIEW

**Comment by chrisbra** [comment]
the maintainer seems to be inactive. Would you volunteer to maintain that file?

**Comment by brammool** [comment]
Roland already took over maintenance :-). I'll include it, thanks.

**Comment by chrisbra** [comment]
that should be mentioned in the runtime file then :/

**Comment by chrisbra** [comment]
ah, I missed, that it is already there. Sorry.

**Pull request closed without merging**
