### PR TITLE
LineNrAbove and LineNrBelow background wrong on wrapped lines

### PR DESCRIPTION
**Pull request by zeertzjq**
Problem:  LineNrAbove and LineNrBelow background wrong on wrapped lines.
Solution: Update number column also for wrapped part of a line.

### CODE REVIEW

**Comment by chrisbra** [comment]
thanks. Can you show before/after screenshots?

**Comment by luukvbaal** [comment]
In Neovim we have renamed "number_only" to "col_rows" in a similar patch. Might I suggest doing the same here instead of obfuscating an integer value in a boolean variable name?

**Comment by zeertzjq** [comment]
I don't really like the `col_rows` variable name and I don't think `number_only` sounds boolean-only, but I'll add the `== 0` / `> 0` checks.

**Comment by luukvbaal** [comment]
Yeah I suppose "col_rows" also obfuscates the fact that only the columns are being redrawn l, which is arguably more important. TBH my main reason for replacing "number_only" was the fact that not only the number, but also the fold and sign columns are redrawn.

**Comment by zeertzjq** [comment]
Before:
Before

After:
After

**Pull request closed without merging**
