### PR TITLE
Rename .tzs to the correct .tzst

### LINKED ISSUE #8105: Files with extension .tzst are handled differently from .tar.zst
**Describe the bug**
`.tzst` extension is an [equivalent](https://en.wikipedia.org/wiki/Tar_(computing)#Suffixes_for_compressed_files) of `.tar.zst`, however, vim seems to handle them differently.

While it correctly opens `.tar.zst` as an archive, it seems to open `.tzst` as a file, thus mangling it.

Here's an example on two identical files named differently:

image

**Environment (please complete the following information):**
vim --version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 26 2021 00:21:09)
Included patches: 1-2653 ### (also tried compiling git 1-2760, still happens)
Compiled by Arch Linux
```
Terminal: Konsole

### PR DESCRIPTION
**Pull request by C0rn3j**
Fixes #8105

### CODE REVIEW

**Comment by cecamp** [comment]
II've included the tzs -> tzst changes; you can find the updated version of [tar.vim here](http://www.drchip.org/astronaut/vim/index.html#TAR).

**Comment by C0rn3j** [comment]
> II've included the tzs -> tzst changes; you can find the updated version of [tar.vim here](http://www.drchip.org/astronaut/vim/index.html#TAR).

I am not sure I understand the process of getting the changes included in git master, I see they are still not present there, is there anything else I need to do?

**Comment by k-takata** [comment]
You might want to check @cecamp's prerelease version if it is correct.
Once @cecamp thinks it is ready for release, he will send it to Bram, then Bram will include it in this repository.

**Comment by C0rn3j** [comment]
Thanks for the explanation, that makes sense!

@cecamp 
I've opened the .vba file and sourced it, which installed it - 
```
ls -lah ~/.vim/plugin/tarPlugin.vim 
.rw-r--r-- c0rn3j c0rn3j 2.3 KB Sun Jun 13 13:18:36 2021  /home/c0rn3j/.vim/plugin/tarPlugin.vim
```

Unforunately, then opening a .tzst file has the same behavior, and .tar.zst files are now broken too.
Removing tarPlugin.vim makes .tar.zst files work again at least.

**Pull request closed without merging**
