### PR TITLE
Runtime (syntax, doc) for Fortran

### PR DESCRIPTION
**Pull request by Ajit-Thakkar**
Small addition to Fortran syntax script, and documentation update for Fortram syntax and indent.

### CODE REVIEW

**Comment by e-kwsm** [comment]
Regression of 6863084d3bd044700973e6180ccb1a044566ec46 (#13629):

https://github.com/vim/vim/blob/7d0abf2cb6969932dea55bbb67b3ce793fd86b36/runtime/syntax/fortran.vim#L136

Here `\<` is missed, hence e.g. `MODULE` in `use myMODULE` and `FUNCTION` in `var = myFUNCTION(0)` are wrongly highlited.

**Review by e-kwsm — APPROVED** [review]

**Review by e-kwsm — CHANGES_REQUESTED** [review]
Regression of 6863084d3bd044700973e6180ccb1a044566ec46 (#13629):

https://github.com/vim/vim/blob/7d0abf2cb6969932dea55bbb67b3ce793fd86b36/runtime/syntax/fortran.vim#L136

Here `\<` is missed, hence e.g. `MODULE` in `use myMODULE` and `FUNCTION` in `var = myFUNCTION(0)` are wrongly highlighted.

Would you fix it?

**Comment by Ajit-Thakkar** [comment]
> Regression of [6863084](https://github.com/vim/vim/commit/6863084d3bd044700973e6180ccb1a044566ec46) (#13629):
> 
> https://github.com/vim/vim/blob/7d0abf2cb6969932dea55bbb67b3ce793fd86b36/runtime/syntax/fortran.vim#L136
> 
> Here `\<` is missed, hence e.g. `MODULE` in `use myMODULE` and `FUNCTION` in `var = myFUNCTION(0)` are wrongly highlighted.
> 
> Would you fix it?

Yes, I'll fix it properly.

**Comment by Ajit-Thakkar** [comment]
OK now?
@e-kwsm

**Review by e-kwsm — APPROVED** [review]
LGTM

**Comment by chrisbra** [comment]
thanks!

**Pull request merged**
