### PR TITLE
Fixed ubsan errors in fold.c

### PR DESCRIPTION
**Pull request by dpelle**
This PR fixes the following ubsan errors in `fold.c`:
```
fold.c:1317:38: runtime error: applying zero offset to null pointer
fold.c:2909:41: runtime error: applying zero offset to null pointer
fold.c:3101:10: runtime error: applying zero offset to null pointer
```
These are the most frequent ubsan errors at https://api.travis-ci.org/v3/job/722925624/log.txt
There are other similar unrelated ubsan errors in `eval.c`, `vim9compile.c`, `spellfile.c`, `spellsuggest.c`, `viminfo.c` still left to be fixed.

### CODE REVIEW

**Comment by mgedmin** [comment]
Ooh, I think this might fix #6830.

**Comment by mgedmin** [comment]
Yep, just tested this, it definitely fixes #6830.

**Comment by dpelle** [comment]
@mgedmin wrote:

> Yep, just tested this, it definitely fixes #6830

Good to know.  I did not expect this.  I thought that these were minor
undefined behavior, unlikely to have consequences in practice.
I did not expect that pointer arithmetic, with `NULL`, without dereferencing
would cause issues in practice.

I'm curious whether #6830 happenned only when building with optimization,
a undefined behavior is less likely to have consequences with `-O0`

I see that CI failed on Windows: `Test_autoread_file_deleted` failed
but I assume it's unrelated to this change.

**Comment by mgedmin** [comment]
@dpelle there's actual dereferencing of `fp` in the

```c
		next = fp->fd_top + off;
```

line and your PR here adds an `if (fp != NULL && ...)` guard above it.

**Comment by brammool** [comment]
Thanks.  I think I already fixed the first couple of parts of this patch, but not the last one that changes valid_fold().
Although I think it's better to check ga_len being > 0 than ga_data being NULL.  When folds are removed it's possible that ga_data is not NULL while there are no entries, thus ga_len is zero.  Although pointer computations would work, and asan won't complain, it's still not useful.
I suppose using (NULL + 0) is not valid according to the standard, although in practice it will not fail.  The C standard has drifted off from being practical to "standardized".  It's been dominated by compiler writers instead of users...

**Pull request closed without merging**
