### PR TITLE
installer: Install also Lua DLL

### PR DESCRIPTION
**Pull request by k-takata**
Discussed at https://github.com/vim/vim-win32-installer/issues/182.

### CODE REVIEW

**Comment by chrisbra** [comment]
should we not also have distribute it in the non-installer case?

**Comment by k-takata** [comment]
We don't have a script for packaging in this repository.
It should be covered by another PR in vim/vim-win32-installer (https://github.com/vim/vim-win32-installer/pull/183/files#diff-7a8dc79054e4fc2dca1c4105e18b40f0R287).

**Comment by brammool** [comment]
Hmm, I don't think there are more than a few plugins using Lua.  It's a chicken-egg situation, but adding the dll won't help much.

**Comment by brammool** [comment]
Let's not do this.  Lua isn't used often enough to include the dll.  The user can install it if needed, or it may already be installed.

**Comment by skywind3000** [comment]
I mean no disrespect to Bram, but can we reconsider this PR ?
Since things changed, we don't have anyone familiar with vim9script implementation right now.

**Comment by skywind3000** [comment]
Or we can postpone any Vim9-related discussions until future development gets on track.

**Pull request closed without merging**
