### PR TITLE
Es translation

### PR DESCRIPTION
**Pull request by victorhck**
updating spanish translation

### CODE REVIEW

**Comment by brammool** [comment]
Can you fix the conflicts?

**Comment by brammool** [comment]
I just pushed another update, please sync to that

**Comment by victorhck** [comment]
> Can you fix the conflicts?

I think it's done! Hope nothing breaks! :)

**Comment by brammool** [comment]
CI reports errors.  You can run "make check" to find problems.

**Comment by brammool** [comment]
Looks like you also need to update src/po/vim.dexktop and src/po/gvim.desktop to make CI pass.

**Comment by victorhck** [comment]
> Looks like you also need to update src/po/vim.desktop and src/po/gvim.desktop to make CI pass.

I did it. I updated the *.desktop.in files adding missing GenericName[es]  field
(thanks for your patience!)

**Comment by brammool** [comment]
Wrong way around, a line needs to be removed from the .in files.  I'll do that and check it.
You'll see it after the next runtime files update.

**Comment by victorhck** [comment]
> Wrong way around, a line needs to be removed from the .in files. 

oops! don't know what is needed to remove.
There's something else what is needed to be translated or review?

**Comment by brammool** [comment]
> > Wrong way around, a line needs to be removed from the .in files. 
> 
> oops! don't know what is needed to remove.
> There's something else what is needed to be translated or review?

Not right now.  After the next runtime file updates, please check if
things look OK.  And if there are any changed messages (I try to
minimize this, but we also wan to make sure the messages are good).

-- 
hundred-and-one symptoms of being an internet addict:
207. You're given one phone call in prison and you ask them for a laptop.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
