### PR TITLE
Update Perl runtime files

### PR DESCRIPTION
**Pull request by hoelzro**
Hi Bram,

The fine folk of vim-perl have some changes to the Perl runtime files we'd like you to incorporate into upstream Vim.

Thanks!

### CODE REVIEW

**Comment by brammool** [comment]
Rob Hoelz wrote:

> The fine folk of vim-perl have some changes to the Perl runtime files
> we'd like you to incorporate into upstream Vim.

Thanks.

This adds a tap syntax file, but that is not a recognized filetype.
How are tap files recognized?

I assume the Vim license applies to all the new stuff?

-- 
hundred-and-one symptoms of being an internet addict:
123. You ask the car dealer to install an extra cigarette lighter
     on your new car to power your notebook.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by hoelzro** [comment]
@brammool I can't say since I don't use `tap.vim`, but I assume people will dump their test results to a file and `setf tap` by hand.

The Vim license does indeed apply - do you need that reflected in a header on the file?

**Comment by brammool** [comment]
Best is if the file type is recognize, if not from the file name then from the contents.  That's what users are used to, without it they may not have an idea there is support for the file type.

Yes, please add the license to the file header to avoid any confusion.  Just saying "License: Same as Vim" should be sufficient.

**Comment by hoelzro** [comment]
@brammool Ok, I'll add the license to the headers.  I'll also add an autocmd to associate `.tap` files with the new TAP syntax

**Comment by chrisbra** [comment]
This seems to have been included. Closing.

Note, https://github.com/vim/vim/issues/4339 so you might want to send updated perl6 runtime files to Bram.

**Pull request closed without merging**
