### PR TITLE
Update ms windows build doc

### PR DESCRIPTION
**Pull request by shaneharper**

### CODE REVIEW

**Comment by brammool** [comment]
The paths in Makefile are for the current directory when following the instructions, they are not relative to the Makefile itself.

**Comment by brammool** [comment]
Why remove the section for "Terminal support"?

**Comment by shaneharper** [comment]
Previously the "Terminal support" section had special instructions such as
to download dlls from https://github.com/rprichard/winpty (patch 8.0.0742).

Now there are no special instructions for building the terminal feature on
MS Windows; TERMINAL=yes doesn't even need to be specified as that is the
default.

**Comment by brammool** [comment]
Alright, I'll include it then.

**Pull request closed without merging**
