### PR TITLE
fix spelling errors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by k-takata** [comment]
Could you report each maintainer for the runtime files?

**Comment by ghost** [comment]
Do you mean request a review to all maintainers?

**Comment by k-takata** [comment]
Yes. (or mail to each of them)

**Comment by ghost** [comment]
For convenience, in the meantime, I have removed files changed in runtime/* for this PR.

**Comment by brammool** [comment]
I'll include the configure fix, thanks.

**Pull request closed without merging**
