### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by KoLogicDev**
More suitable for github readme.

### CODE REVIEW

**Comment by mattn** [comment]
This repository is work in progress for migrating.

See https://groups.google.com/forum/#!topic/vim_dev/Io5A_Zir--k
> NOTE: Before the actual migration the current repository on github will 
be wiped!

**Comment by mattn** [comment]
And this is the thing bram will decide, but we vim-dev is developing with patch file in ML. So we will not accept pull-request.

**Comment by zenware** [comment]
@KoLogicDev You should submit it the usual way because the markdown formatted readme file is significantly better than the one they already have. It looks nicer, it looks especially nice when rendered, and the table of contents actually makes it more easily navigable from within vim :v:

**Comment by icyflame** [comment]
:+1:

**Comment by frewsxcv** [comment]
I have to email a patch in order to contribute to this project? That's archaic for 2015 and will result in people not contributing to your project. I guess this is why neovim was created...

**Comment by mattn** [comment]
@frewsxcv I know PR is useful. But not ready. Why u are in hurry up?

**Comment by frewsxcv** [comment]
This isn't my PR. I was just commenting about your 'no pull request' policy. I don't want to start a debate, I am just disappointed with the workflow.

**Comment by mattn** [comment]
As I said in above, This is thing bram will decide. What I can say is "not ready".

**Comment by chrisbra** [comment]
@frewsxcv Note: This is a snapshot repository. It is not clear, this repository will survive. How changes are handled isn't even decided yet, so no reason to complain. Besides sending patches is the traditional way to work, that works very well, even for big projects like the linux kernel.

**Comment by vyp** [comment]
Also, Torvalds has extensively written about his problems with github's web ui/'pull requests' feature in this thread: https://github.com/torvalds/linux/pull/17#issuecomment-5654674. Not saying that Moolenaar has the same view (of course I do not know), just pointing out some possible arguments against its use.

**Comment by gilligan** [comment]
I guess people that think the way vim is being developed is silly should just move on to neovim and don't start discussions here. I did.

**Comment by blueyed** [comment]
Maybe PRs should must be deactivated until the final repo is up?

**Comment by frewsxcv** [comment]
> PRs should must be deactivated

One can't deactivate pull requests for a repository on GitHub

**Pull request closed without merging**
