### PR TITLE
Add CursorLineSign and CursorLineFold highlight groups

### PR DESCRIPTION
**Pull request by gpanders**
These are similar to the SignColumn and FoldColumn groups but only take
effect for the cursor line and when the 'cursorline' option is set.

### CODE REVIEW

**Comment by brammool** [comment]
Asan reports a couple of memory leaks, please fix that.

**Comment by gpanders** [comment]
Forgot a `vim_free` in `sign_define_from_dict`. Should be fixed now.

**Comment by gpanders** [comment]
These tests are failing:

```
From test_alot.vim:
	Found errors in Test_very_large_count_64bit():
	command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[455]..function RunTheTest[44]..Test_very_large_count_64bit line 7: command did not fail: norm 44444444444444p
	Found errors in Test_very_large_count_block_64bit():
	command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[455]..function RunTheTest[44]..Test_very_large_count_block_64bit line 8: command did not fail: norm 44444444444444p
```

Not sure how or if that's related to these changes though.

**Comment by chrisbra** [comment]
looks like those currently also happen on master, so probably unrelated

**Comment by brammool** [comment]
Please sync to head, then the failures should be gone.

**Comment by gpanders** [comment]
Done

**Pull request closed without merging**
