### PR TITLE
build fails on Mac OS X 10.4/10.5

### PR DESCRIPTION
**Pull request by evanmiller**
libdispatch was introduced in OS X 10.6, so its presence needs to be checked before blindly including <dispatch/dispatch.h> in src/os_macosx.m.

### CODE REVIEW

**Comment by brammool** [comment]
> libdispatch was introduced in OS X 10.6, so its presence needs to be
> checked before blindly including &lt;dispatch/dispatch.h&gt; in
> src/os_macosx.m.

The CI for Mac OS failed because of an unrelated problem.  I should have
fixed that now, please trigger CI again to see if it passes now.

-- 
Did you ever stop to think...  and forget to start again?
                                  -- Steven Wright

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by evanmiller** [comment]
I don't see a button for re-triggering CI; do you want me to push a no-op commit?

**Comment by brammool** [comment]
> I don't see a button for re-triggering CI; do you want me to push a no-op commit?

Syncing to head should work.


-- 
Life is a gift, living is an art.		(Bram Moolenaar)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by evanmiller** [comment]
Synced but seeing lots of failures now...

**Comment by brammool** [comment]
> Synced but seeing lots of failures now...

Probably the hashtab change that caused problems.  After fixing that
strangely the Mac CI fails in the python indenting.  Not sure why.
You could just try again.

-- 
Two cows are standing together in a field.  One asks the other:
"So what do you think about this Mad Cow Disease?"
The other replies: "That doesn't concern me. I'm a helicopter."

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by evanmiller** [comment]
After syncing a couple of times I'm seeing test failures on macOS normal and huge. It's quite possible my patch introduced this failure so I'd appreciate another set of eyes on it. Thanks.

**Comment by brammool** [comment]
Did you sync past 9.0.1100 ?  That fixed a problem that can make tests fail.

**Comment by evanmiller** [comment]
> Did you sync past 9.0.1100 ? That fixed a problem that can make tests fail.

Yes, it is synced to the latest. I wonder if there is something about the inclusion order that it preventing the new HAVE_DISPATCH_DISPATCH_H from being defined.

**Comment by brammool** [comment]
> > Did you sync past 9.0.1100 ? That fixed a problem that can make tests fail.
> 
> Yes, it is synced to the latest. I wonder if there is something about
> the inclusion order that it preventing the new
> HAVE_DISPATCH_DISPATCH_H from being defined.

It looks like HAVE_DISPATCH_DISPATCH_H is missing from src/config.h.in.

-- 
ROBIN:  (warily) And if you get a question wrong?
ARTHUR: You are cast into the Gorge of Eternal Peril.
ROBIN:  Oh ... wacho!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by evanmiller** [comment]
Thanks – seems to be passing now.

**Pull request closed without merging**
