### PR TITLE
Do not run filetype detect for directories in netrw

### LINKED ISSUE #9875: Directories named *.com treated as dcl files
### Steps to reproduce

0. Setup vim with netrw.

```
% cat test.vim
set nocompatible
filetype plugin on
```

2. Create a directory `% mkdir -p google.com/example`.
3. Open said directory in vim `% vim -u test.vim google.com/example`
4. Press `-` to open the `google.com` directory
5. `echo &ft` returns `dcl`.

### Expected behaviour

I expect the directory to have a filetype of `netrw` as other directories do, not `dcl`.

I'm fine being able to override this, and have tried to do so with:

```viml
autocmd BufReadPost *.com set filetype=netrw
```

And failed.

### Version of Vim

8.2.4227

### Environment

OS: macOS 12.0.1
Terminal: Kitty
$TERM: xterm-256color
shell: zsh 5.8

### Logs and stack traces

```shell
```

### PR DESCRIPTION
**Pull request by teoljungberg**
Resolves #9875, #9099

### CODE REVIEW

**Comment by brammool** [comment]
I actually think there is never a point in "filetype detect" to try figure out the filetype for a directory.
Or we should just set filetype to "directory".
How about that?  Would that break anything?

**Comment by brammool** [comment]
Actually, it appears "filetype detect" already rejects directories.  In the netrw plugin it uses a buffer to display the directory contents, but that buffer is not a directory itself.

Hmm, I have trouble reproducing the original problem.  How do you get the filetype to be something else than "netrw"?

**Comment by habamax** [comment]
I guess this is related to https://github.com/vim/vim/issues/9099 which is easy to reproduce.

**Comment by brammool** [comment]
OK, I'll include it.  Let me close the other issues and leave this one open for Charles.

**Comment by brammool** [comment]
> I guess this is related to https://github.com/vim/vim/issues/9099
> which is easy to reproduce.

Aha, it requires using ":Explore".  I was using ":edit".

-- 
This is an airconditioned room, do not open Windows.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by teoljungberg** [comment]
I’ve reproduced this using `:Explore` and entering a directory under a `.vim` or `.com` and then bubbling back up to the parent directory, that corresponds to setting `ft={vim,dcl}` respectively - while it should be `netrw`.

**Comment by teoljungberg** [comment]
@brammool While resolving the merge conflicts I saw that https://github.com/vim/vim/commit/3c053a1a5ad2a3c924929e11f2b9af20a8b901e2 was merged into master yesterday.

Which includes the gist of this patch.

Should we then close this PR?

**Comment by teoljungberg** [comment]
I tested out https://github.com/vim/vim/commit/3c053a1a5ad2a3c924929e11f2b9af20a8b901e2 and what’s on main and it works as expected.

**Pull request closed without merging**
