### PR TITLE
term_gettitle() was not tested

### PR DESCRIPTION
**Pull request by dpelle**
This PR adds a test for term_getttile() which was not tested
according to codecov:

https://codecov.io/gh/vim/vim/src/master/src/terminal.c#L4971

### CODE REVIEW

**Comment by dpelle** [comment]
Newly added Test_term_gettitle() fails in CI despite passing locally on my laptop.
I don't know why yet. So please don't merge unless I or someone else can figure
out why it fails in CI.

**Comment by dpelle** [comment]
@dpelle wrote:

> Newly added Test_term_gettitle() fails in CI despite passing locally on my laptop.

I noticed that travis does not run with a real X-server, it uses Xvfb.
I started locally Xvfb on my machine:
```
$ Xvfb :99
```
Then in another terminal:
```
$ export DISPLAY=:99
$ cd vim/src/testdir
$ make
```
And I could reproduce the same failure as in Travis:
```
Found errors in Test_term_gettitle():
function RunTheTest[40]..Test_term_gettitle[11]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>6 line 1: Expected '[No Name] - VIM' but got ''
function RunTheTest[40]..Test_term_gettitle[14]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>7 line 1: Pattern 'Xfoo (.*[/\\\\]testdir) - VIM' does not match ''
function RunTheTest[40]..Test_term_gettitle[17]..WaitForAssert[2]..<SNR>6_WaitForCommon[11]..<lambda>8 line 1: Expected 'foo' but got ''
```
I don't know  yet how to fix it, but at least I can now reproduce the issue.
If there is no simple way to fix it (?), it does not really look worth testing term_gettitle().

**Comment by chrisbra** [comment]
you might be able to connect to that display using a vnc viewer and check what is happening there.

**Comment by k-takata** [comment]
Bram's comment is not forwarded here:
https://groups.google.com/d/msg/vim_dev/Kbjr-Sr69Mk/MxIrWuW9DwAJ

**Comment by dpelle** [comment]
Even after starting a window manager with `DISPLAY=:99`, the test still fails in the same way.
Anyway, even if starting a window manager made the test pass, I don't think it would be good.
Vim test should in my opinion pass even without a window manager.  A window manager
is optional (even if it's practically almost a must for end-users).
I'm giving up on this PR now now unless someone has an idea.
Anyway, it would only slightly increase code coverage.

**Comment by brammool** [comment]
Dominique wrote:

> Even after starting a window manager with `DISPLAY=:99`, the test
> still fails in the same way.
> Anyway, even if starting a window manager made the test pass, I don't
> think it would be good.
> Vim test should in my opinion pass even without a window manager.  A
> window manager
> is optional (even if it's practically almost a must for end-users).
> I'm giving up on this PR now now unless someone has an idea.
> Anyway, it would only slightly increase code coverage.

I think we have been looking in the wrong direction.  The test runs Vim
in the terminal window.  Vim will connect to the X server, if possible,
to get the old window title.  If this doesn't work, then the 'title'
option will be off.  Thus you have to explictly do ":set title".
Hopefully it works then.

-- 
In Joseph Heller's novel "Catch-22", the main character tries to get out of a
war by proving he is crazy.  But the mere fact he wants to get out of the war
only shows he isn't crazy -- creating the original "Catch-22".

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dpelle** [comment]
@brammool  wrote:

> I think we have been looking in the wrong direction. The test runs Vim
> in the terminal window. Vim will connect to the X server, if possible,
> to get the old window title. If this doesn't work, then the 'title'
> option will be off. Thus you have to explictly do ":set title".
> Hopefully it works then.

Value of `&title` is indeed 0 when using `Xvfb :99`.
But doing `set title` in the test does not fix the test.

We can however skip the test when  `&title` is 0,
which will skip the test in CI. I did that in this pull
request:
```
 if !has('title') || &title == 0 || empty(&t_ts)
    throw "Skipped: can't get/set title"
  endif
```

I see that the PR has now a merge conflict because
somehow `Test_term_gettitle()` was added in master
in this commit, which was probably not what you
intended to do:
```
commit 1e1153600c0377472d62cc553173fe555ddcf5a7 (tag: v8.1.0711)
Author: Bram Moolenaar <Bram@vim.org>
Date:   Wed Jan 9 23:01:02 2019 +0100

    patch 8.1.0711: test files still use function!
    
    Problem:    Test files still use function!.
    Solution:   Remove the exclamation mark.  Fix overwriting a function.
```

**Comment by brammool** [comment]
Dominique wrote:

> @brammool  wrote:
> 
> > I think we have been looking in the wrong direction. The test runs Vim
> > in the terminal window. Vim will connect to the X server, if possible,
> > to get the old window title. If this doesn't work, then the 'title'
> > option will be off. Thus you have to explictly do ":set title".
> > Hopefully it works then.
> 
> Value of `&title` is indeed 0 when using `Xvfb :99`.
> But doing `set title` in the test does not fix the test.

Strange, I would expect that setting 'title' would make it possible to
manipulate the title.  It works when I try it out locally.  I do notice
that the status line isn't updated immediately, but term_gettitle()
should work right away.
 
> We can however skip the test when  `&title` is 0,
> which will skip the test in CI. I did that in this pull
> request:
> ```
>  if !has('title') || &title == 0 || empty(&t_ts)
>     throw "Skipped: can't get/set title"
>   endif
> ```

OK, but it won't show up in coverage then.

> I see that the PR has now a merge conflict because
> somehow `Test_term_gettitle()` was added in master
> in this commit, which was probably not what you
> intended to do:
> ```
> commit 1e1153600c0377472d62cc553173fe555ddcf5a7 (tag: v8.1.0711)
> Author: Bram Moolenaar <Bram@vim.org>
> Date:   Wed Jan 9 23:01:02 2019 +0100
> 
>     patch 8.1.0711: test files still use function!
>     
>     Problem:    Test files still use function!.
>     Solution:   Remove the exclamation mark.  Fix overwriting a function.
> ```

I was playing around with it and it was hiding in that large patch.
It's basically disabled though.

-- 
A computer program does what you tell it to do, not what you want it to do.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
