### PR TITLE
Add support for sourcing a script from the current buffer

### PR DESCRIPTION
**Pull request by yegappan**
This is based on the feature supported in Neovim with some enhancements.
Parts of the following commits are in this PR:

Commit: https://github.com/neovim/neovim/commit/4d5dbea4f402c76de4419977f7f89d3dec572510
Author: Vikram Pal <vikrampal659@gmail.com>

Commit: https://github.com/neovim/neovim/commit/afdc9e61502a9f02c8cf5156652a1bde027e4345
Author: Sean Dewar <seandewar@users.noreply.github.com>

Commit: https://github.com/neovim/neovim/commit/d4ed51eb4492d4358eb4ab0c939802f2a5fdc636
Author: Sean Dewar <seandewar@users.noreply.github.com>

Commit: https://github.com/neovim/neovim/commit/6188926e00081ae4b1a33d5fd12692a6749a2144
Author: Sean Dewar <seandewar@users.noreply.github.com>

### CODE REVIEW

**Comment by habamax** [comment]
Is it legacy vimscript only?

**Comment by habamax** [comment]
Indeed it is, at least according to the test I can see.

So the source command would behave differently for vim9script buffers?

1. `source %` would work fine
2. `source` or `%source` would fail?

**Comment by Shane-XB-Qian** [comment]
it sounds like another/alternative `import` ..

**Comment by vim-ml** [comment]
Hi,

On Fri, Mar 18, 2022 at 12:30 AM Maxim Kim ***@***.***>
wrote:

> Indeed it is, at least according to the test I can see.
>
> So the source command would behave differently for vim9script buffers?
>
>    1. source % would work fine
>    2. source or %source would fail?
>
>
>
Sourcing a vim9 script from a buffer can be supported in a future PR.

Regards,
Yegappan

**Comment by habamax** [comment]
> Sourcing a vim9 script from a buffer can be supported in a future PR.

Nice, thank you.

**Comment by brammool** [comment]
Instead of concatenating all the lines into one long buffer, allocate each line separately and make the growarray a list of pointers to the lines.  Avoids a very long string when the buffer is big, and avoids the need to split it again later.  Even the "STRLEN(p->buf)" at the start of get_str_line() is quite inefficient.

There should be a test that "1,3source fname" fails.
The help should mention "[range] source" separately, mentioning "[range]" and "[fname]" together is confusing.

**Comment by matveyt** [comment]
I remember I checked how this feature works in Neovim with respect to SID. They allocate a new anonymous SID (unvisible in `scriptnames` output) as soon as `source` tries to access it. So running the same "ranged" source twice (may) result in two new SIDs. Is this how it's done in this PR too? Or is there some more clever implementation?

**Comment by brammool** [comment]
@matveyt: it should use the same SID for a buffer, based on the buffer number.

**Comment by vim-ml** [comment]
Hi,

On Fri, Mar 18, 2022 at 3:41 AM Shane-XB-Qian ***@***.***> wrote:
>
> it sounds like another/alternative import ..
>

This is not an alternative to the import mechanism. The ":source"
command is an existing
command to source Vim scripts. It sources Vim Ex commands from a file.
This PR adds
support for sourcing the Ex commands from the current buffer. This is
useful for quickly
trying out a fragment of a Vim script. There is a already an item in
the todo list for this
support.

Regards,
Yegappan

**Comment by Shane-XB-Qian** [comment]
> > it sounds like another/alternative import ..
> 
> This is not an alternative to the import mechanism. The ":source"
> command is an existing command to source Vim scripts.

thx for reply.
i've forgot why i said that..
perhaps due to ':so' some functionality like 'import' do.. :-)

-- 
shane.xb.qian

**Comment by vim-ml** [comment]
Hi,

On Sat, Mar 19, 2022 at 4:52 AM matveyt ***@***.***> wrote:

> I remember I checked how this feature works in Neovim with respect to SID.
> They allocate a new anonymous SID (unvisible in scriptnames output) as
> soon as source tries to access it. So running the same "ranged" source
> twice (may) result in two new SIDs. Is this how it's done in this PR too?
> Or is there some more clever implementation?
>
>
> I have modified that implementation. It uses the same script ID for a
given buffer.

Regards,
Yegappan

**Comment by Shane-XB-Qian** [comment]
@yegappan @brammool 
your guys' mailbox looks just free from jail this afternoon
// which i thought you were sleeping actually
// which should be not really you sent it at that time
since those mail looks were sent some months ago and duplicate............ :-)

**Comment by brammool** [comment]
I guess messages forwarding from the maillist to github is catching up with messages from around April.

**Pull request closed without merging**
