### PR TITLE
Include the variable tabstop feature

### PR DESCRIPTION
**Pull request by chrisbra**
this is the variable tabstop feature from #857 

Unfortunately, github closed that PR, when I force pushed an update, so here is the new PR.

### CODE REVIEW

**Comment by chrisbra** [comment]
updated to latest master

**Comment by eraserhd** [comment]
Is this feature (assuming it is included) the best way to implement computed tabstops?  I'm writing a lisp plugin which, based on previous lines of code, knows where code could be indented and I'm wondering whether I should +1 this and update vartabstops and such when the cursor changes line or just nmap <Tab> and such.

**Comment by croscato-zz** [comment]
I am testing this PR right now and it is awesome.
A very nice feature to work with assembly files.
Hope to see this integrated in mainstream soon.

**Comment by chrisbra** [comment]
Updated for 8.1.0020

**Comment by jdek** [comment]
Is there anything I, as a vim user interested in this feature, can do to get this merged quicker/soon?

As a sidenote, anyone using Homebrew can just add to the Formula to use this right away (which works as of current master (a15b0a936d2013e99e9323da9b920a5d93e4fb5a).

Add:
```
  patch do
    url "https://patch-diff.githubusercontent.com/raw/vim/vim/pull/2711.patch"
    sha256 "cc50d3cebae137b74d26f26d1513cc3a95f80819b189fc4bfe90b67413d4dba0"
  end
```
and:
```
  opts << "--with-vartabs"
```
To the relevant areas in `brew edit vim`.

**Pull request closed without merging**
