### PR TITLE
i3config: Line continuation is not detected for 'set' command

### PR DESCRIPTION
**Pull request by julio-b**
Problem:  Valid i3config syntax is highlighted as error.
Solution: Skip over line-breaks correctly.

### CODE REVIEW

**Comment by julio-b** [comment]
Before/After screeshot:
2024-04-12-205158_370x255_scrot
CC: @hiqua @JosefLitos

**Comment by JosefLitos** [comment]
Never thought about that, looks good.

Though, could I ask you to base the changess off of my plugin, where I keep the syntax? - I made a couple other changes that were just regarding string inner command parsing, so I didn't bother updating it here, so if you could take those changes and add this one / I will add this change to the file right now. (It would also require the swayconfig file update)

**Review by litoj — CHANGES_REQUESTED** [review]
`\$` cannot be part of the start match because then the `i3ConfigVariable` highlight won't work:
obrazek

I fixed it and pushed the commit to [i3config.vim](https://github.com/JosefLitos/i3config.vim/blob/master/syntax/i3config.vim#L108)

**Comment by julio-b** [comment]
> Never thought about that, looks good.
> 
> Though, could I ask you to base the changess off of my plugin, where I keep the syntax? - I made a couple other changes that were just regarding string inner command parsing, so I didn't bother updating it here, so if you could take those changes and add this one / I will add this change to the file right now.

> (It would also require the swayconfig file update)

I don't use sway, but it seems that swayconfig by default  [includes i3config](https://github.com/vim/vim/blob/e74cad3321ce1dcefc1fc64f617511275b6cd930/runtime/syntax/swayconfig.vim#L19C1-L19C29). So it should recognize the new `set` syntax, right?


> `\$` cannot be part of the start match because then the `i3ConfigVariable` highlight won't work:

Hm, i can't reproduce this. Maybe this is because in your version you added `matchgroup=i3ConfigKeyword`?

> obrazek
> 
> I fixed it and pushed the commit to [i3config.vim](https://github.com/JosefLitos/i3config.vim/blob/master/syntax/i3config.vim#L108)

Nice! I see that you didn't include the `keepend` there. In my testings it was required. Otherwise the `set` region may be expanded to the next line incorrectly. E.g this syntax is not valid because the `\` on the second line is missing:
```
set $mycmd xterm \
       -e bash
       -c "program"
```
Thank you!

**Comment by JosefLitos** [comment]
> E.g this syntax is not valid because the \ on the second line is missing...

When you do `:Inspect` on the extra string line, does it really show also being under the `i3ConfigSet` group? For me it did not, but that may be because of the refactoring I did, but haven't yet pushed/updated to vim.

In my case it also gets highlighted, but because of a fixup long-block-highlighting mechanism for swayconfig, but when set to i3config syntax I wasn't able to reproduce it.

Would you mind, if I made a separate PR with updating `i3config` (and `swayconfig`) with my overall refactor and included my version of the fix there?

**Review by litoj — APPROVED** [review]

**Comment by chrisbra** [comment]
@JosefLitos You approved, so I'll merge. Please feel free to send an updated PR for `i3config` and `swayconfig` to further improve it.

**Pull request merged**
