### PR TITLE
Update man.vim

### PR DESCRIPTION
**Pull request by 532910**
wider character range can be used in manSectionHeading

### CODE REVIEW

**Comment by brammool** [comment]
Jason Franklin is the maintainer of this file, see the header.
I don't see a way to remove me from the reviewers...

**Comment by 532910** [comment]
Sorry, I did not understand, should Jason be notified separately?

**Comment by k-takata** [comment]
Each runtime file is maintained by each maintainer. You should contact the maintainer first.

**Comment by 532910** [comment]
I sent him a letter.

**Comment by brammool** [comment]
> Sorry, I did not understand, should Jason be notified separately?

We just started using the "ownership" mechanism of github, it's still
incomplete.  We haven't used email addresses yet, I suppose that will be
OK, so long as they appear in the file header.  Perhaps someone can
volunteer to write a script to do this?

-- 
   Arthur pulls Pin out.  The MONK blesses the grenade as ...
ARTHUR:  (quietly) One, two, five ...
GALAHAD: Three, sir!
ARTHUR:  Three.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
> We haven't used email addresses yet, I suppose that will be OK

It seems that it only works if the email address is added to a GitHub user.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax

**Comment by brammool** [comment]
Ken Takata wrote:

> > We haven't used email addresses yet, I suppose that will be OK
> 
> It seems that it only works if the email address is added to a GitHub user.
> https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax

So it must still be on a github account.  Using the github user name
would then be better, email addresses can change.

-- 
   [Another hideous roar.]
BEDEVERE: That's it!
ARTHUR:   What?
BEDEVERE: It's The Legendary Black Beast of Aaaaarrrrrrggghhh!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Pull request closed without merging**
