### PR TITLE
Fixed checking window width with conceal(s).

### LINKED ISSUE #9443: conceal does not re-calculate width and wrap lines.
### Steps to reproduce

`:source` this code.
```
set columns=80 wrap conceallevel=3
syntax match XXX /X\+/ conceal cchar= 
finish


XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYY
```

### Expected behaviour

`YYYY` in a line but
image

### Version of Vim

8.2.3877

### Environment

Windows 11. gvim.exe

### Logs and stack traces

_No response_

### PR DESCRIPTION
**Pull request by mattn**
Fixes #9443

### CODE REVIEW

**Comment by LemonBoy** [comment]
This PR is missing a test case.

**Comment by mattn** [comment]
Hmm, test case is wrong. will fix.

**Comment by mattn** [comment]
It seems that this vsplit obstacle reproduce failing on test.

https://github.com/vim/vim/blob/aaadb5b6f76ea03e5eb460121f3dbf46ad04ce50/src/testdir/term_util.vim#L73-L74

**Comment by brammool** [comment]
It also fails on FreeBSD, is that a hint somehow?

**Comment by zeertzjq** [comment]
The test doesn't seem to fail without the PR?

**Comment by mattn** [comment]
>The test doesn't seem to fail without the PR?

Yes, without this PR, result should be
```
YYY
Y
```

**Comment by mattn** [comment]
ah, sorry. I forgot to push.

**Comment by zeertzjq** [comment]
With this PR, lines below a line whose height changes can be glitched:

https://user-images.githubusercontent.com/35768171/169544734-23fc61e8-04cb-4443-b460-fe7ad7830cd2.mp4

**Comment by mattn** [comment]
Could you please take screenshot?

**Comment by zeertzjq** [comment]
https://user-images.githubusercontent.com/35768171/169547709-e7d3c199-8cf9-40c6-a64f-d24ebd686eac.mp4

**Comment by mattn** [comment]
Is it possible to redraw with CTRL-L ?

**Comment by zeertzjq** [comment]
Redrawing with CTRL-L doesn't fix the glitch.

**Comment by mattn** [comment]
As far as I'm trying this on my linux box, CTRL-L fixes the glitch.

**Comment by zeertzjq** [comment]
Oops I was wrong. Redrawing with CTRL-L fixes the glitch.

**Comment by zeertzjq** [comment]
Without `concealcursor=n` there are some other glitches:

https://user-images.githubusercontent.com/35768171/169555513-b98cea83-00ee-41b7-955f-0fd23b11613c.mp4

**Comment by mattn** [comment]
@zeertzjq Could you please try last change?

**Comment by zeertzjq** [comment]
Glitches still exist:

With `concealcursor=n`:

https://user-images.githubusercontent.com/35768171/169720184-66451595-3d52-4d3a-9f56-cf1183763900.mp4

Without `concealcursor=n`:

https://user-images.githubusercontent.com/35768171/169720383-f9d5d1da-02b0-4c0e-8d71-3686967efd68.mp4

**Comment by mattn** [comment]
Hmm, can't repro.

**Comment by zeertzjq** [comment]
I'll provide recordings with screenkey:

With `concealcursor=n`:

https://user-images.githubusercontent.com/35768171/169721636-8ea7b56a-093e-4cd4-989d-49f0f2a499b6.mp4

Without `concealcursor=n`:

https://user-images.githubusercontent.com/35768171/169721899-a2b328d5-653a-4e75-ba4c-fee33a526975.mp4

**Comment by mattn** [comment]
Can't repro. I'm trying this on vim.exe and gvim.exe on Windows & Linux on terminal.

**Comment by zeertzjq** [comment]
I just checked again. I was checking this PR using `gh pr checkout 10442`, building with `make`, and then running Vim with `VIMRUNTIME=./runtime ./src/vim --clean`

**Comment by mattn** [comment]
ec67ec37754e5a0b024336d7137213bc87ca482c is included in `git log` ?

**Comment by zeertzjq** [comment]
Yes
```
commit f0decb5a19d88c25bed7c7d23c098055985d4f99 (HEAD -> fix-9443)
Merge: ec67ec377 9b2edfd3b
Author: Yasuhiro Matsumoto <mattn.jp@gmail.com>
Date:   Mon May 23 02:10:42 2022 +0900

    Merge branch 'master' into fix-9443

commit ec67ec37754e5a0b024336d7137213bc87ca482c
Author: Yasuhiro Matsumoto <mattn.jp@gmail.com>
Date:   Mon May 23 00:42:47 2022 +0900

    check FEAT_CONCEAL

commit b75510b101c1b1cc4b9a06a2cdcf647fbf74565b
Author: Yasuhiro Matsumoto <mattn.jp@gmail.com>
Date:   Mon May 23 00:36:15 2022 +0900

    return wl_size
```

**Comment by brammool** [comment]
Yes, this is a hard problem to solve.  Also, since conceal depends on syntax highlighting, it would require syntax syncing whenever a column position in a line is to be computed.  That adds a lot of complexity and can make it very slow.

A long term solution I have been thinking of is to use text properties that change text inside a line (hide/replace/add).  Then the problem is at least local to the line.  Still complicated, but doable.

**Comment by CarloWood** [comment]
Hi, is this still being worked on? I'd really love to see this fixed.

**Comment by simlei** [comment]
Is there any development on this?

**Comment by chrisbra** [comment]
It seems this has stalled and doesn't fix the issue yet. I am closing this for now. Please consider creating a new PR if you have a working solution. Thanks.

**Pull request closed without merging**
